### ISSUE TITLE
how to configure channel interceptors

### ISSUE THREAD

**Issue by joelmarty** [spring-cloud/spring-cloud-stream#1000]
Hi,

I am looking into a simple way that would allow to register interceptors on cloud stream channels (most specifically on kafka channels).

Since we could not find anything in the cloud stream / kafka-binder documentations, I have been looking into spring messaging but I can't really get a satisfactory answer.
If this feature is not yet supported, is it a planned one ?

Currently we do it using BeanPostProcessors to call addInterceptor() on the selected AbstractMessageChannel instances.

**Comment by mbogoevici** [comment]
@joelmarty Being Spring Integration channels, normal interception works.

See https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/interceptor/BoundChannelsInterceptedTest.java#L67 for an example and the reference documentation for SI: http://docs.spring.io/spring-integration/reference/htmlsingle/#channel-interceptors

**Comment by joelmarty** [comment]
That's simpler than expected, maybe some documentation would help for people who are not familiar with spring integration.
Anyways, I think it covers my needs. Thanks!

**Comment by mbogoevici** [comment]
Sure thing - thanks for the suggestion :)
