### ISSUE TITLE
React to consumer rebalance

### ISSUE THREAD

**Issue by janoskranczler** [spring-cloud/spring-cloud-stream#1004]
Hi guys,
Is there any way I can react on a consumer rebalance (Kafka), if `autoRebalanceEnabled` is set to `false`? In Kafka client there is `ConsumerRebalanceListener`, but how can I listen on rebalance in SCS?
(And if I can, what is the simplest way to determine the partition count before and after the rebalance?)

**Comment by ilayaperumalg** [comment]
Hi @janoskranczler ,

For tracking this better, please create Kafka binder related issues here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka

I will move this now.

**Comment by ilayaperumalg** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#166
