### ISSUE TITLE
Scheduling the StreamListener

### ISSUE THREAD

**Issue by nitishasgekar** [spring-cloud/spring-cloud-stream#1005]
I have a requirement where I push some messages in a queue in RabbitMQ when a target system is not available. I need to keep trying to process these messages every X minutes  . Wondering if there is a way to achieve this using Spring Cloud Stream . Is there a way to schedule the StreamListener somehow ? . If not , can it be a feature that can be added to SCS ?

**Comment by ilayaperumalg** [comment]
Hi @nitishasgekar, It looks like you want to combine Spring Cloud Task to trigger based on the scheduler. Please checkout https://cloud.spring.io/spring-cloud-task/

**Comment by artembilan** [comment]
What you requesting is called `retry` and it is supported by the `RabbitTemplate`: http://docs.spring.io/spring-amqp/reference/html/_reference.html#template-retry.

On the other hand Spring Integration provides `RequestHandlerRetryAdvice`: http://docs.spring.io/spring-integration/reference/html/messaging-endpoints-chapter.html#retry-advice

The `@ServiceActivator` can be supplied with the `adviceChain` referring to the `RequestHandlerRetryAdvice`.

Right, `@StreamListener` doesn't support that, but should it? If we can shift a message to the `@ServiceActivator` with any selected logic above.

I'm not familiar with Spring Cloud Task, so @ilayaperumalg 's answer might make sense, too. We just need more info from you about your use-case. Some code snippet would be helpful.

**Comment by mbogoevici** [comment]
Related to binding lifecycle control in #763 #963

**Comment by sabbyanandan** [comment]
If the requirement is to do schedule-driven data processing, we recommend Spring Cloud Task for that. Doing that via Spring Cloud Stream may result in side effects.
