### ISSUE TITLE
producer headerMode=raw

### ISSUE THREAD

**Issue by lwshuo** [spring-cloud/spring-cloud-stream#1006]
Hi team!

I want to send message that only has a json payload, no headers, because the consumer is not spring cloud stream based and expects pure json. I tried setting headerMode to raw on producer and that didn't work, it still add id, timestamp and contentType headers.

my gradle is
`  compile('org.springframework.cloud:spring-cloud-stream:1.2.2.RELEASE')
  compile('org.springframework.cloud:spring-cloud-starter-stream-kafka:1.2.1.RELEASE')`

my config is 
![image](https://user-images.githubusercontent.com/25490314/27662557-3b56b3a8-5c2c-11e7-88dc-5a787381afb3.png)

If I misunderstood what headerMode is for, is there other ways to send message without any headers?
Thank you!

**Comment by sobychacko** [comment]
@lwshuo can you try this for headerMode? `spring.cloud.stream.default.producer.headerMode=raw`
or `spring.cloud.sream.bindings.DomainUnsubscribed.producer.headerMode=raw`?

**Comment by ilayaperumalg** [comment]
Hi @lwshuo, I noticed you have a typo in your config. It should be `bindings` instead of `binding`.

**Comment by lwshuo** [comment]
@ilayaperumalg thank you so much!
