### ISSUE TITLE
@StreamListener with POJOs should propagate message headers

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#1010]
[StreamListenerMessageHandler](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerMessageHandler.java#L38) explicitly doesn't copy headers. I believe it should.

> Mark Fisher: the basic idea is that IF you are operating at the level of Message, you have opted to take over full control... obviously not the case for POJOs

**Comment by dsyer** [comment]
FWIW I am using a copy of `StreamListenerMessageHandler` (in the same package) and it works for me.

**Comment by mbogoevici** [comment]
Merged in master with indicated changes via: https://github.com/spring-cloud/spring-cloud-stream/commit/205d4579a409008a9e798f141c5f806cda7710eb

Cherry-picked in 1.2 with changes to preserve the current default behaviour :https://github.com/spring-cloud/spring-cloud-stream/commit/e386d11bf7ac0a4892cc237ab9559fd6cb8afad7
