### ISSUE TITLE
Not able to test Spring Cloud Streams using spring-boot-tests

### ISSUE THREAD

**Issue by Salaboy** [spring-cloud/spring-cloud-stream#1021]
For some reason I cannot test streams with Spring boot tests. I've created a reproducer (https://github.com/Salaboy/test-spring-cloud-streams) and this thread in stackoverflow: 

https://stackoverflow.com/questions/45127365/test-spring-cloud-streams-with-spring-cloud-test/45129726?noredirect=1#comment77260206_45129726

It looks like a bug, but it might be a configuration issue. There doesn't seem to be covered in the documentation or in the project's tests. This seems to me like a very common scenario that people will want to test.

**Comment by viniciusccarvalho** [comment]
Have you tried to change it to 1.3 and boot 1.5.4? I have a very similar project with those versions and work as expected.

**Comment by Salaboy** [comment]
So there is definitely something broken in spring boot 2 or the new version of the stream project. I'm more than happy to look into it if I get some kind of pointers on what might be failing. But I'm not too familiar with the code to debug it.

**Comment by Salaboy** [comment]
@viniciusccarvalho I haven't tried, but I need to get it working with spring-boot 2 anyway. There is no point in my setup to downgrade to get it working. I would rather help fixing this in the new versions of the project.

**Comment by viniciusccarvalho** [comment]
I'm not sure to be honest, I only know that 1.3 it seems to work. And we are not currently actively working on 2.0 until 1.3 goes GA. 

We need to improve the testing section on the docs, I think one of the reasons for this to be failing is that there's other ways for you to test instead of using this approach.

You could use a TestBinder and MessageCollector to write your unit tests, like I said we need to improve the section and perhaps add a few more examples.

Is there a reason why you need boot2 given that we are still ~6 months away from it's GA release?

**Comment by Salaboy** [comment]
@viniciusccarvalho TestBinder and MessageCollector are OK to test that your producer is generating and sending the messages correctly, but our integration tests are checking that the ones that consume the message is dealing with those messages correctly. In the same way that we test using TestRestTemplate we would love to test our @Input and @Output streams. 
We want to align our framework (activiti.org) with spring boot 2 and we are also targeting to release our project in about 6 months, and for us it is a perfect opportunity to contribute back to the spring cloud project finding out what is working and what is not. Any estimate on when 1.3 will be ready? I will downgrade my example to see if that works on 1.3 but just to make a case to fix 2.0.

**Comment by viniciusccarvalho** [comment]
1.3 GA should be out by end of Sep (but don't hold me hostage to that :) )

I'm trying the code on 2.0 ATM, I'll see if I can make it work, like I said I have a very similar project on 1.3 that works, not your code, but very similar. I'll see if I can post something today

**Comment by Salaboy** [comment]
@viniciusccarvalho thanks a lot.. I will downgrade and test and get back with the results as well. I really appreciate the feedback on this.

**Comment by viniciusccarvalho** [comment]
@Salaboy Thank you for the feedback. Looking forward to see what is coming next with activiti integration ;) 

PS: I'm a bit slow due PTO, but I'll do my best to get something back to you

**Comment by viniciusccarvalho** [comment]
Eureka! @Salaboy so I found the culprit, what's going on is that `TestBinder` is actually the only binder being created. So you would need to actually use it to collect messages. Remove `spring-cloud-stream-test-support` from your dependencies list and it will default to the RabbitBinder. You will then see your exchanges being created and the test passes :)

**Comment by Salaboy** [comment]
👍
