### ISSUE TITLE
how can i dynamically change the sink in aggregateApplicationBuilder?

### ISSUE THREAD

**Issue by japanbhatt** [spring-cloud/spring-cloud-stream#1022]
I am using spring cloud stream with aggregate application builder which allows me to chain up the source processors and sink. Now I have a use-case where in need to have 2 sinks and based on some logic I need to route the message to either of the sink/processor. How can I achieve it via aggregate application builder configuration?

**Comment by mbogoevici** [comment]
@japanbhatt A similar issue exists here: https://github.com/spring-cloud/spring-cloud-stream/issues/450

Given your use case though, you could try using Spring Integration directly and put all your components in a single application (flow). Aggregation has been designed for bringing together applications that were designed to run independently, but for some reason they need to run in a single VM.
