### ISSUE TITLE
Add contentType support for @Output annotation

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#1027]
As described by @markpollack, it would be interesting to have support for contentType selection on the annotation level, as well as the properties file.

```java
    @Output(contentType="application/json")
    MessageChannel hotDrinks();

    @Output
    MessageChannel coldDrinks();
```

@mbogoevici @garyrussell do you think we can add this for 1.3 GA? Doesn't seem to be a complex thing to implement

**Comment by garyrussell** [comment]
Seems reasonable; I guess a property, if present, should override it.

**Comment by viniciusccarvalho** [comment]
Moving this back to backlog, we will need to wait for some changes on how we handle serialization that only makes sense on 2.0 line

**Comment by SyedMuhammadSufyian** [comment]
Guys I am working on this issue .
