### ISSUE TITLE
Error channel binding is not adding any custom interceptors.

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#1028]
When we set content-type on error channel destinations, it's not taking any effect and that's due to the fact that we are not adding any interceptors for error channel binding. 

```
spring.cloud.stream.bindings:
  error:
    destination: error-channel
    content-type: application/*+avro
```

**Comment by artembilan** [comment]
Has been fixed via https://github.com/spring-cloud/spring-cloud-stream/commit/22141a8dce93f32d10825ba9fb0cb4d5e29fcb95
