### ISSUE TITLE
Issue with payloads in customsink

### ISSUE THREAD

**Issue by rahulvijay24feb** [spring-cloud/spring-cloud-stream#1032]
Hi,
I am observing weird behavior on my custom sink on PCF. I have a custom sink setup importing Logsink module. This module sinks data to my Gemfire and MySQL DB. Pseudo code here : https://github.com/rahulvijay24feb/CustomGemfireDBSink

Issue: Few events are not caught by my customsink. These events are not received by my loggerSink method. For such entries I see a log being recorded in the payload with the application name, but the method does not receive it.

Signature of loggerSink :
@serviceactivator(inputChannel = Sink.INPUT)
public void loggerSink(String payload) {

**Comment by rahulvijay24feb** [comment]
Enabling debug logs, I can below descrepency:


Bad Event ( Misses being consumed by mySinkConfiguration class) has below log:

2017-07-31T22:47:06.334-04:00 [APP/PROC/WEB/0] [OUT] 2017-08-01 02:47:06.334 DEBUG 14 --- [.planogramIPE-1] ssor$ReplyProducingMessageHandlerWrapper : org.springframework.cloud.stream.app.log.sink.LogSinkConfiguration.logSinkHandler.serviceActivator.handler received message: GenericMessage 

Good Event(Succesfully consumed by mySinkCongfiguration)  has below log:

2017-07-31T22:47:06.340-04:00 [APP/PROC/WEB/0] [OUT] 2017-08-01 02:47:06.340 DEBUG 14 --- [.planogramIPE-1] o.s.i.handler.ServiceActivatingHandler : ServiceActivator for [org.springframework.integration.handler.MethodInvokingMessageProcessor@5c69515f] (sinkConfiguration.loggerSink.serviceActivator.handler) received message: GenericMessage

**Comment by artembilan** [comment]
The problem that you subscribe twice to the `DirectChannel` with its round-robin dispatching strategy. So, that is not surprise your custom logger receives one set of messages and default one imported on the same channel - another.

Considering to declare that `Sink.INPUT` as a `PublishSubscribeChanne` `@Bean`.

**Comment by rahulvijay24feb** [comment]
Found the root cause to be two service activators. One in my SinkConfiguration and an other in LogSinkConfiguration. Implemented a self LogSinkConfiguration removing service activator. It fixed the issue.

**Comment by rahulvijay24feb** [comment]
@artembilan : Thank you . Below reference document explains the creation of a custom application as 

"As a reminder, this involves:

adding the starter to your project
choosing the binder
adding the main class and importing the starter configuration.
After doing so, you can simply add the additional configuration for the extra features of your application."




http://docs.spring.io/spring-cloud-stream-app-starters/docs/1.0.4.RELEASE/reference/html/_introduction.html



Should this scenario of not having a PublishSubscribeChannel does not cause a problem in all cases?

**Comment by artembilan** [comment]
That is not a problem of that Docs, neither Spring Cloud Stream. That is the cause of understanding that binding channel is always `DirectChannel`:
```
@Override
public SubscribableChannel createInput(String name) {
	SubscribableChannel subscribableChannel = new DirectChannel();
	this.messageChannelConfigurer.configureInputChannel(subscribableChannel, name);
	return subscribableChannel;
}
``` 
and when we have several subscriber to it, we always end up with the round-robin distribution.

That doc doesn't say that you should import existing subscriber and add your own, though.

I won't mind to mention something in the doc, but need to determine first of all that it isn't there already somewhere in the http://docs.spring.io/spring-cloud-stream/docs/Chelsea.SR2/reference/htmlsingle/index.html

**Comment by rahulvijay24feb** [comment]
@artembilan : Thanks for the clarification Artem. I see the information in Spring cloud stream. Might be something on getting the events from imported started app while creating custom app would be helpful.
