### ISSUE TITLE
Jackson module  ParameterNamesModule is not auto registered

### ISSUE THREAD

**Issue by mariuszs** [spring-cloud/spring-cloud-stream#1046]
Sample project compiled with `-parameters` flag:

https://github.com/mariuszs/spring-stream-consumer-sample

> Error: MessageConversionException: Could not read JSON: Can not construct instance of com.example.streamconsumer.Foo: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)

**Comment by viniciusccarvalho** [comment]
I'm not sure if I follow your issue or the sample project. 

If you need an ObjectMapper with custom configuration, just provide one using `@Bean`, this should override the default one from spring-boot, and it will be the one picked by the framework.

**Comment by mariuszs** [comment]
Ok, you are right. I forget that `ParameterNamesModule` is not auto registered when it is on classpath. Thanks,

**Comment by mariuszs** [comment]
Hmm, it should be autoregistered... I have `spring-boot-starter-web` on classpath.

`JacksonAutoConfiguration`
--

	@Configuration
	@ConditionalOnJava(JavaVersion.EIGHT)
	@ConditionalOnClass(ParameterNamesModule.class)
	static class ParameterNamesModuleConfiguration {

		@Bean
		@ConditionalOnMissingBean(ParameterNamesModule.class)
		public ParameterNamesModule parameterNamesModule() {
			return new ParameterNamesModule(JsonCreator.Mode.DEFAULT);
		}

	}

**Comment by viniciusccarvalho** [comment]
The module is being auto configured, you can check it by just putting a break point on the code. I don't know however why is it not working. I tested a simple rest boot application and you sample would fail on that example either. There may be other things you need to configure in jackson, I'm not sure, but the objectmapper being created is definitely being setup with the module.

**Comment by mariuszs** [comment]
Ok, this is jackson issue. Thank for your help

https://github.com/FasterXML/jackson-databind/issues/1631
