### ISSUE TITLE
Provide azure-service-bus binder in spring cloud stream

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-stream#1047]
https://github.com/Azure/meta-azure-service-broker/issues/138

**Comment by viniciusccarvalho** [comment]
@cforce We have started an event-hubs binder, but I don't believe it will see the light of day before 2.0 release is out somewhere around end of Fall 2017

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-starters#47
