### ISSUE TITLE
Binding<T> implementation should implement SmartLifecycle

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#1053]
The binders should return an implementation that delegates it's lifecycle to the underlying target. This would allow us to control lifecycle of the Binding and register error handlers at the appropriate time.

**Comment by olegz** [comment]
`Lifecycle` was added to `Binding` here https://github.com/spring-cloud/spring-cloud-stream/commit/67d310da8c3aa91109ade5558e80c2c8ccb9d970, so closing
