### ISSUE TITLE
New interfaces for binding control

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#1055]
Provide a couple of new interfaces that binders may implement:

```java
public interface Seekable {
   boolean seek(Long offset);
}
```

```java
public interface Resumable
  boolean pause();
  boolean play();
}
```

Those two interfaces will be exposed via Actuator endpoints for users to play/pause/seek consumers

Implementations may reuse the lifecycle methods start/stop, but it may not be the case.

Start/Stop still plays a role for producers if setting `autoStartEnabled`

**Comment by markfisher** [comment]
`play()` should be `resume()`, and I'd argue that the interface should be `Pausable` since you first have to pause before you can resume ;)

**Comment by olegz** [comment]
Moved it to RC2, given the release timings issue of https://github.com/spring-projects/spring-integration-kafka/pull/199/
Basically we can't release RC1 depending on snapshot of spring-integration-kafka and the above issue, just missed SI 5.0.2 by a day ;)

**Comment by sobychacko** [comment]
Closing via https://github.com/spring-cloud/spring-cloud-stream/commit/dff7416a7ded0d37152ca11f741d727feb8ca742.

**Comment by yharsh** [comment]
How to disable a channel to get configure during application boot up using something like `autoStartEnabled`.
