### ISSUE TITLE
Message Channel Binders should return a list of interceptors

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#1056]
The MessageChannel binders should return a list for interceptors, so that the AbstractMessageChannel Binder can query and register them. This will allow concrete implementations to add behavior on top of the interceptors already added by the framework.

**Comment by olegz** [comment]
At the moment we have only two interceptors and most of the functionality that was in them have been removed (delegated elsewhere). If I understand correctly the above would expose Message Channels for to variety of changes that can be introduced with interceptors. While this may be ok in the _general purpose_ framework like SI, I am afraid that given that SCSt is not a  _general purpose_ framework the unintended side-effect it may cause should be evaluated firs. Also, there seem to be no real business need for it as of yet. 
So, will close it for now, but feel free to reopen it if specific need arises and we can discuss if interceptors are the best way to address such need
