### ISSUE TITLE
Add support for FluxMessageChannel

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#1063]
With the new support for reactive in SI 5.0, we can leverage when binders return a `FluxMessageChannel` we should use `Flux.from(fluxMessageChannel)` as opposed to using `Flux.create(messageHandler -> ...)` that we use today

**Comment by olegz** [comment]
This is already provided in Spring Integration and we are currently using it for functions support, so I am closing this one.
