### ISSUE TITLE
Add TCK infrastructure for Content-Type support

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1071]
As a developer, I'd like to improve the TestBinder test coverage also to include SerDe workflows.

**Acceptance:**
- Add test coverage for SerDe workflows
- Assert on positive and negative content-type conversions

**Comment by olegz** [comment]
I think with with https://github.com/spring-cloud/spring-cloud-stream/issues/1127 we should reconsider the whole approach in general. While the above commit at this moment is strictly in core, the greater idea is to turn it into a "new" test binder
