### ISSUE TITLE
increasing of max.request.size parameter does not affect on version 3.3.0

### ISSUE THREAD

**Issue by ahmetbardiz** [spring-cloud/spring-cloud-stream#1082]
Like the issue #587 changes on parameter max.request.size through the producer.properties file do not affect on runtime. When I run the producer on console it always get the default value of max.request.size = 1048576 despite of its being a bigger value.  I run the the producer command like below:

 sudo ./bin/connect-standalone etc/schema-registry/connect-avro-standalone.properties etc/kafka-connect-jdbc/mssql.properties

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#221
