### ISSUE TITLE
Switch master to 2.0.0

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1087]
This requires new branch and CI plans for 1.3.x. 

Also, we would have to update all the binder implementations and starters project to 2.0.0.

**Comment by sobychacko** [comment]
All tasks for this issue have been resolved.

1.3.x branches are in place for Scst, kafka binder and rabbit binder.
Ditmars.x branch is created for starters.
Master branches in all repositories are now building 2.0.0 and Elmhurst snapshots.
