### ISSUE TITLE
Make `MessageCollector` 1.x/2.x compatible

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-stream#1101]
without this type no proper serialization takes place and messages get `byte[]` body instead of the one basing on the `contentType`. Previously the default was json.

**Comment by olegz** [comment]
@marcingrzejszczak  We had some internal discussions and I am actually rather reluctant to do anything with _ MessageCollector_ (at least at this point). My primary motivation is that with _<?>_, one should not have expectation of any type of automatic conversion. So what you get is what message looks like on the wire (which could itself be beneficial). Sure this could be improved by possibly creating some type of test utility to process message through the same type conversion  logic used when dealing with user code, but that would be different requirement all together.
Also, the _contentType_ and it's role in the conversion is being questioned as well. 

Thoughts?

**Comment by marcingrzejszczak** [comment]
Adding @dsyer 

IMO this is a breaking change. Anybody who was using the `MessageCollector` at this point will get broken if the sent message was a String JSON. 

I mean I've managed to work this around so I'm no longer affected. I guess I'll need to change the sent object (I currently send a String whereas apparently, I should be sending sth else).

**Comment by olegz** [comment]
@marcingrzejszczak I am coming to the same realization ;)
Anyway, it is fixed with this PR https://github.com/spring-cloud/spring-cloud-stream/pull/1115 once it is merged which is hopefully by tomorrow

**Comment by sobychacko** [comment]
This issue is addressed with PR #1115
