### ISSUE TITLE
Refactor AbstractTestBinder to interact with actual interceptors instead of relying on test channels

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1111]
_From @sabbyanandan on October 25, 2017 19:4_

As a developer, I'd like to refactor the binder tests to use the actual interceptors, so we can validate the real functional abilities as opposed to merely relying on test channels for the message in/out.

_Copied from original issue: spring-cloud/spring-cloud-stream-binder-kafka#238_

**Comment by olegz** [comment]
Was resolved with these two commits
https://github.com/spring-cloud/spring-cloud-stream/commit/4cc66ae0e004a8ae81e6d66073cf0167355eeb86
https://github.com/spring-cloud/spring-cloud-stream/commit/6eff89ca6c4dfc6ae9e0777e5f97e63c45615afc
