### ISSUE TITLE
Configurable message source name delimiter in tests

### ISSUE THREAD

**Issue by JacobASeverson** [spring-cloud/spring-cloud-stream#1116]
I'm in the process of creating a binder implementation for Amazon SQS which unfortunately doesn't allow the period (`.`) character in queue names. From http://docs.aws.amazon.com/cli/latest/reference/sqs/create-queue.html:

> The name of the new queue. The following limits apply to this name:
> * A queue name can have up to 80 characters.
> * Valid values: alphanumeric characters, hyphens (- ), and underscores (_ ).
> * A FIFO queue name must end with the .fifo suffix.
> 
> Queue names are case-sensitive.

The abstract test classes use hardcoded names such as `foo.0` which result in `400` errors from the SQS API. I'd like to provide a hook to be able to override the message source/target name delimiter so such a name could be `foo-0` instead. I'd be happy to submit a PR but want to make sure this would be a welcomed change.

**Comment by olegz** [comment]
@JacobASeverson I wonder if a simpler approach would be to change the queue names in Abstract test classes to something commonly accepted (i.e., underscores  ```foo_0```)
In any event your contribution is definitely welcomed and we can debate some of the details later when you have a PR.

**Comment by garyrussell** [comment]
Bear in mind, however, that Spring Cloud DataFlow uses dots in destination names..

    dataflow:>stream create ticktock --definition "time | log" --deploy

Uses kafka topic `ticktock.time`

So if the SQS binder would be used in that environment, dataflow would need some configuration option.

**Comment by JacobASeverson** [comment]
That's interesting, thanks for the heads up @garyrussell. I'll have a look at DataFlow and submit a ticket. I'll table this in the meantime.

**Comment by olegz** [comment]
While Gary's point is very valid, I want to make sure it is clear that it's the issue that needs to be addressed in data flow. So I say proceed with your changes and we will see what impact it may have on data flow and what can we do to limit it.

**Comment by JacobASeverson** [comment]
Will do, thanks @olegz.

**Comment by garyrussell** [comment]
Thanks; I was just trying to point out that the origin of the names in the tests was from XD (SCDF's predecessor), so just "fixing" the tests isn't a total solution.
