### ISSUE TITLE
Why CompositeMessageChannelConfigurer can not be customized

### ISSUE THREAD

**Issue by lanmolsz** [spring-cloud/spring-cloud-stream#1123]
The `CompositeMessageChannelConfigurer` bean is defined in `org.springframework.cloud.stream.config.BindingServiceConfiguration`.

It has a `messageChannelConfigurers` field that config the implementation of `MessageChannelConfigurer`. 
But I can't add a custom implementation of `MessageChannelConfigurer` to the `messageChannelConfigurers` list.

**Comment by olegz** [comment]
@lanmolsz I am sorry you're having an issue. Could you please elaborate more on your use case as to what are you trying to accomplish?

**Comment by lanmolsz** [comment]
When I configured spring.cloud.stream.default.contentType = applicaion/json in `application.properties`.

It will be added to the header header in the message, read source code that contentType is ContentTypeConvertingInterceptor added to the header of the message.

CompositeMessageChannelConfigurer 
-> MessageConverterConfigurer 
-> ContentTypeConvertingInterceptor

If I also want to add my custom configuration for MessageChannel, At first I wanted to implement the MessageChannelConfigurer interface,However, CompositeMessageChannelConfigurer can not be extended

**Comment by olegz** [comment]
You can now configure it as any other `@Bean`
