### ISSUE TITLE
Spring-cloud-stream and spring-cloud-config messing up multiple binder config

### ISSUE THREAD

**Issue by HaVonTe1** [spring-cloud/spring-cloud-stream#1124]
**issue**
I found an issue when using spring-cloud-stream and spring-cloud-config using multiple binders.
Starting the demo app without config-service everything works perfect. All bindings are directed to their dedicated connection.

Activating the config-service results in false connections. All bindings are directed to the default connection. Erroneous exchanges/queues are created.

**how to reproduce**

I made a demo app to show it.
https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-

In there is a `demoservice` with simple config in application.yml:

```json
spring:
  rabbitmq:
    host: localhost
    virtual-host: /defaultVH
    username: defaultUser
    password: defaultPassword
  cloud:
    stream:
      bindings:
        sampleQueueA:
          binder: rabbit-A
          contentType: application/x-java-object
          group: groupA
          destination: sampleQueueA
        sampleQueueB:
          binder: rabbit-B
          contentType: application/x-java-object
          group: groupB
          destination: sampleQueueB
      binders:
        rabbit-A:
          defaultCandidate: false
          inheritEnvironment: false
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                virtualHost: /vhA
                username: userA
                password: paswdA
                port: 5672
                connection-timeout: 10000
        rabbit-B:
          defaultCandidate: false
          inheritEnvironment: false
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                virtualHost: /vhB
                username: userB
                password: paswdB
                port: 5672
                connection-timeout: 10000
```

There is also a bootstrap.yml for using the config-service:
```json
spring:
  main:
    banner-mode: "off"
  application:
    name: demo-service
  cloud:
    config:
      enabled: true #change this to use config-service
      retry:
        maxAttempts: 3
      discovery:
        enabled: false
      fail-fast: true
```
When setting `spring.cloud.config.enabled=false` the rabbit connections are just fine:

[image_rabbit_good](https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-/blob/master/rabbit_con_good.png)

But with `spring.cloud.config.enabled=true` the connections are messed up. 

[image_rabbit_bad](https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-/blob/master/rabbit_con_bad.png)

I made 100% sure the config-service is delivering the exact same properties like the application.yml of the demoservice includes.

**expected behaviour**
Regardless of using the config-service. The connections should be the same.

**Comment by olegz** [comment]
@HaVonTe1 Didn't you raise the same issue in spring-cloud-config the other day? I thought I saw something similar.

**Comment by HaVonTe1** [comment]
Yes I did. I dont know if this is a config-service or cloud-stream issue. The config guys didnt comment on this so I thought of giving it a try here also.

**Comment by olegz** [comment]
Thanks, I'll give it a look and reach out to the config team as well.

**Comment by olegz** [comment]
@HaVonTe1 I've pinged the 'config' guys, possibly some extra config being pulled up as part of the switch to s-c-config. They are looking at it. Will let you know.

Thank you for being patient

**Comment by dsyer** [comment]
The problem with your configuration is that it defines `spring.rabbitmq.*` in the config server, and these properties always take precedence over the ones provided by the binder in Spring Cloud Stream. The problem essentially stems from the way Spring Cloud Stream creates the binder's `ApplicationContext`. You can probably work around it by making config server properties lower priority (http://cloud.spring.io/spring-cloud-static/Dalston.SR4/single/spring-cloud.html#overriding-bootstrap-properties).

**Comment by HaVonTe1** [comment]
The definition of `spring.rabbitmq.*` is necessary for Actuator. Without this config, the "/health" check will use default credentials (guest/guest@/) in `RabbitHealthIndicator`. 
Disabling this indicator is not an option. We must make sure Rabbit is up and running.

>  and these properties always take precedence over the ones provided by the binder in Spring Cloud Stream.

I dont think this is correct. 
This would not explain why everything is fine when the config-service is switched off.

> You can probably work around it by making config server properties lower priority 

Do you mean adding the binding configs in bootstrap.yml and telling the demoservice to ignore the properties from config-service?

Well this would mean to disable the config-service at all. Right? Why use it at all in further??

**Comment by dsyer** [comment]
> I dont think this is correct.

It is. When the config server is switched off that property source is not used, so it can't get in the way.

> Well this would mean to disable the config-service at all.

That's not what I suggested. Did you read the documentation in that link?

**Comment by HaVonTe1** [comment]
Ok. It is hard to understand why some properties are only used when they are serverd by the config-service. Please forgive me my confusion.

I read the docs in the link but what I understood was:
- set spring.cloud.config.overrideSystemProperties=false
- use SystemProperties/Environment Vars to set up the bindings

Is this correct? Or can you provide an example?

**Comment by dsyer** [comment]
Per the user guide I would say that you need to set `spring.cloud.config.allowOverride=true` (in the remote properties) and either `spring.cloud.config.overrideSystemProperties=false` or `spring.cloud.config.overrideNone=true`. You don't need to set any system properties (that's kind of the point of what the Stream binder is doing).

**Comment by HaVonTe1** [comment]
I am sorry, but it didnt work.

I made a branch in my demo project on github to test your suggestions.

https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-/tree/issue/1124

Please have a look at it and tell me if I made something wrong.

**Comment by HaVonTe1** [comment]
Based on your hints about the role of the `spring.rabbitmq.*` properties I found a solution/workaround.

See https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-/tree/workaround

I still think this is a serious issue and needs resolving but the workaround helps me to go further withour getting rid of cloud-config.

Thanks a lot.

I lay it up to you to close this issue or not.

**Comment by dsyer** [comment]
I sent a PR to your sample repo (https://github.com/HaVonTe1/spring-cloud-stream-multiplebinder-config-issue-/pull/1). You need to put the override settings in the remote properties as well.

**Comment by HaVonTe1** [comment]
@dsyer I merged the PR and tested it. 
It worked like a charm.
I still would like to classify  this as some kind of workaround. Because the config file deliverd from cloud-config differs from the one that would be used without cloud-config. But I guess this is more than acceptable.

I realy want to thank you for your help.

**Comment by dsyer** [comment]
> I still would like to classify this as some kind of workaround. 

That's why I said "You can probably work around it by making config server properties lower priority".

**Comment by olegz** [comment]
@HaVonTe1 is it ok to resolve this issue or there are still some outstanding questions you have?

**Comment by HaVonTe1** [comment]
By creating the  new issue (1136) I am fine. This can be closed.

**Comment by dsyer** [comment]
#1136 is nothing to do with this is it? This issue is still open as far as I know.

**Comment by HaVonTe1** [comment]
Oh Ok. Sry. I got confused.

**Comment by olegz** [comment]
@HaVonTe1  Is this still an issue?

**Comment by olegz** [comment]
I think that this issue is related/same as https://github.com/spring-cloud/spring-cloud-stream/issues/1273 which have been addressed now. Please feel free to reopen it if you believe it is still an issue

**Comment by GovindRajuSavi** [comment]
: Can you please help me with, why it is not creating the Virtualhosts in respective users.
 
![image](https://user-images.githubusercontent.com/47241347/53238589-9c460a00-36bf-11e9-8eb2-d7bdf7b1d541.png)

Attempting to connect to: [localhost:5672]
2019-02-22 16:25:10.151  WARN 47440 --- [ 127.0.0.1:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured (Exception message: Socket closed)
2019-02-22 16:25:10.155  WARN 47440 --- [:0:0:0:0:1:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured (Exception message: Socket closed)
2019-02-22 16:25:10.336  INFO 47440 --- [eueA.groupA-253] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@34d19ae6: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
=================================================
I ran the same program for me its not creating the any Virtual-Hosts 
![image](https://user-images.githubusercontent.com/47241347/53238332-1033e280-36bf-11e9-94b9-08bad2aece84.png)

------
![image](https://user-images.githubusercontent.com/47241347/53238458-43767180-36bf-11e9-98e1-14b54f7a1942.png)
====
![image](https://user-images.githubusercontent.com/47241347/53238492-5be68c00-36bf-11e9-9832-0682d7961192.png)
