### ISSUE TITLE
Expose MessageHandlerMethodFactory as a bean

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1135]
As described in [INT-4363](https://jira.spring.io/browse/INT-4363) both frameworks (SI and SCSt) create an instance of _MessageHandlerMethodFactory_ resulting in _InvocableHandleMethod_ instances created with different set of `argumentResolvers` which essentially leads to a possibility of different results simply based on how operation is annotated (e.g., `@ServiceActivator(inputChannel="input"` or `@StreamListener("input")`). I am currently tracking few cases where it is true.

Allowing `MessageHandlerMethodFactory` to be a shared infrastructure bean would bring consistency to the above use case while also giving SCSt certain level of control for cases where SI configuration is not in play (i.e., Streaming binders such as KStream, DStream etc). In other words if such bean is declared as `@ConditionalOnMissingBean` in parent configuration the underlying framework such as SCSt could determine if it can reuse the same instance or override one with its own resulting in consistent set of _InvocableHandleMethod_ and `argumentResolvers` across all data handling operations.

**Comment by olegz** [comment]
Just to clarify 'MessageHandlerMethodFactory' is already a bean in SCSt, however in relation to what's described in [INT-4363](https://jira.spring.io/browse/INT-4363), it has to be either `@ConditionalOnMissingBean` or our version of it should take precedence over the one in SI to ensure consistent set of 'argumentResolvers' regardless of the handling annotation used. 
This issue also implies that we need to use the same version of MessageConverter between SI and SCSt. And in this case our converter should take precedence as well to ensure that Message conversion is consistent between Integration and Streaming binders where SI may not be available.

**Comment by artembilan** [comment]
The related SI JIRA https://jira.spring.io/browse/INT-4363 has been fixed.

See its PR for more information: https://github.com/spring-projects/spring-integration/pull/2285

**Comment by olegz** [comment]
@artembilan thank you guys!
