### ISSUE TITLE
kstream branch and multiple outputs

### ISSUE THREAD

**Issue by kmandalas** [spring-cloud/spring-cloud-stream#1141]
When using the KStream API we can "split" a given stream to branches and then "route" different branches to different output topics: 
- https://kafka.apache.org/0100/javadoc/org/apache/kafka/streams/kstream/KStream.html#branch(org.apache.kafka.streams.kstream.Predicate...)
- https://kafka.apache.org/0100/javadoc/org/apache/kafka/streams/kstream/KStream.html#to(java.lang.String)

Can this be done when using Spring Cloud kstream binder (i.e. `KStreamProcessor`, `StreamListener` etc.)?
At the current example(s) for kstreams, I see that `@SendTo` is used for a single output and there is no indication in the reference documentation either. Maybe @sobychacko can provide a quick answer to this issue.

**Comment by sobychacko** [comment]
@kmandalas Right now we don't have a way to bind multiple KStream target types. I created an issue in the Kafka binder repo: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/265
Hopefully, we should be able to provide this feature in 2.0.

**Comment by sabbyanandan** [comment]
Also, @kmandalas, it'd be great if you can share the high-level use-case requirements. It would help with the development and use-case validation. Feel free to update spring-cloud/spring-cloud-stream-binder-kafka#265 with any relevant information as you find fit.

**Comment by sabbyanandan** [comment]
@kmandalas: Thanks for the write-up on spring-cloud/spring-cloud-stream-binder-kafka#265. I'll close this in favor of kafka-binder issue.
