### ISSUE TITLE
how to configure a global DLX?

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-stream#1144]
I dont want to set a DLX to each bindings

**Comment by olegz** [comment]
@ExtremeYu Did you get a chance to go through this [document](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.M3/reference/htmlsingle/#rabbit-dlq-processing)?
I just want to make sure that if its not sufficient enough we can update it. 
Anyway, please give it a shot and let us know.

**Comment by ExtremeYu** [comment]
@olegz I have read,but  i only see the reference to configure the dlx like this:spring.cloud.stream.rabbit.bindings**.input.consumer**.auto-bind-dlq=true,which make me thought one quene must setup one dead quene

**Comment by garyrussell** [comment]
By default, if `autoBindDlq` is true, with no other settings, the queue is configured with a DLQ bound to exchange `DLX`. If `.consumer.prefix` is set to some value, say `foo`, the DLX is `foo.DLX`. Or, you can set `.consumer.dead-letter-exchange` to explicitly name the dead-letter exchange.

By default, the DLQ name is `<queueName>.dlq` (or `<prefix>.<queueName>.dlq`) but can be specified with `.consumer.dead-letter-queue-name`.

>which make me thought one quene must setup one dead quene

No; the framework will create the dead-letter exchange, queues, and bindings.

`autoBindDlq` must be set on each binding; there is no global binding property `defaultAutoBindDlq`.

**Comment by olegz** [comment]
I am closing this issue as it appears that explanation from @garyrussell is sufficient enough, but please feel free to reopen it if you have more questions.
