### ISSUE TITLE
how to setup a exchange without yml profile?

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-stream#1145]
like this? 
![image](https://user-images.githubusercontent.com/16620268/33250822-e508da12-d36d-11e7-9998-46c8ec11fe67.png)

**Comment by olegz** [comment]
I am not sure I fully understand what you're trying to accomplish. It appears you are trying to use java-config to configure things that framework already does for you. 
What are you trying to gain by doing that? 
If something is missing (some feature), please let's discuss it and see if we can improve within the framework.

**Comment by ExtremeYu** [comment]
thanks reopen latter
