### ISSUE TITLE
The dead queue already exist,but spring rabbit not found.

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-stream#1149]
![image](https://user-images.githubusercontent.com/16620268/33272105-1fe989c8-d3c4-11e7-92af-9a406ce24d7f.png)

![image](https://user-images.githubusercontent.com/16620268/33272197-6a89d046-d3c4-11e7-8bb1-78292fda3709.png)

![image](https://user-images.githubusercontent.com/16620268/33272275-9a17fdba-d3c4-11e7-978e-8f310411cb3e.png)

**Comment by ExtremeYu** [comment]
floow the doc to recive the dead queue message ,but failed to statrt

**Comment by sabbyanandan** [comment]
Hi, @ExtremeYu. It appears you're using the [DLQ-processing sample](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/05079c3976275867551c5dc290b597f3b5301d82/spring-cloud-stream-binder-rabbit-docs/src/main/asciidoc/dlq.adoc) from the docs. It has no direct relevance to Spring Cloud Stream's programming model, though. It might be better for us to review if you can share a sample project and configurations.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-rabbit#112
