### ISSUE TITLE
Dynamic instance count and instance index for a microservice architecture in Kubernetes?

### ISSUE THREAD

**Issue by christophetd** [spring-cloud/spring-cloud-stream#1151]
Similar to: https://stackoverflow.com/questions/37579939/changing-spring-cloud-stream-instance-index-count-at-runtime

I'm interested to run a Spring Cloud Stream application in Kubernetes. In this context, it is not possible to know in advance the number of instances of a service, neither the index of a specific instance.

I feel like this is a big issue, since microservice architectures are by essence dynamic, and the number of instances of a service subject to change very quickly (e.g. autoscaling, instance crashing, etc.).

Do you foresee any solution to this, or is Spring Cloud Stream simply not suitable to this kind of setup? I'm guessing a solution would need to have platform-specific implementations (e.g. a Kubernetes adapter to know how many instances are of the service are running).

Thanks.

**Comment by christophetd** [comment]
Thanks! Looking forward to @markfisher or @jldec's input.

**Comment by olegz** [comment]
@christophetd I am going to close it for now but suggest if you still have question to either reopen it here or in spring-cloud-function project

**Comment by jhonToni** [comment]
Hi, I have a similar problem.
I'm working with microservices and Kafka broker.
I'm using skaffold for continuous debugging on my kubernetes cluster.
My project have one backend app and one user service.
When i scaling up or down the backend i want that the messages for a particular partition to always go to the same instance.
The documentation suggest me to declaring two properties:

```
spring.cloud.stream.instanceIndex=<current instance index>
spring.cloud.stream.instanceCount=<instances count>
```


How to do this dinamically for supporting kubernetes scaling?
Are there any ways to do this in runtime?
