### ISSUE TITLE
How can I send delay message?

### ISSUE THREAD

**Issue by xjune123** [spring-cloud/spring-cloud-stream#1162]
How can I send delay message?  All message do not  need process imedietely.For example, it is 12:00 ,we need consumer consue at 18:00.

**Comment by sabbyanandan** [comment]
Hi, @xjune123: If you've to process messages at a scheduled window, there is no reason to run the application in a streaming mode. A streaming application tends to run 24/7. In your use-case, it will be sitting idle for the most majority of the time.

Please review Spring Batch and Spring Cloud Task projects; you can use the programming model from these projects to consume messages from brokers such as Rabbit or Kafka. However, the difference is that you'll launch the batch-job at a schedule window (_e.g., 18:00)_ to consume the messages for downstream processing. The applications in this format are transient; they run for a finite time and shutdown when the processing completes. It will continue to re-launch at the scheduled window.

Lastly, questions like this are better discussed in StackOverflow format; please consider asking it there going forward.
