### ISSUE TITLE
spring cloud stream spend too many time to startup,over 30s

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-stream#1165]
![q __ ln0jfspt u be6oeu](https://user-images.githubusercontent.com/16620268/34427300-ead512ea-ec7b-11e7-9da9-de15ff6b6028.png)
![1514508532](https://user-images.githubusercontent.com/16620268/34427305-ef4638b8-ec7b-11e7-9d10-0f45586b736a.jpg)

**Comment by ExtremeYu** [comment]
it spend time too much!

**Comment by garyrussell** [comment]
You need to provide __much more information__ - your application, configuration, etc.

It is impossible for anyone to provide a useful comment on the minimal information you have provided.

A good starting point would be a complete startup log.

**Comment by ncc0706** [comment]
@ExtremeYu The first impression you are Chinese, I guess right

**Comment by ExtremeYu** [comment]
@ncc0706 稳

**Comment by olegz** [comment]
@ExtremeYu are there any progress on this with regard to logs as suggested by @garyrussell?

**Comment by olegz** [comment]
It appears this issue had stalled, so I am closing it. If you still believe there is an issue, feel free to reopen and provide additional details.
