### ISSUE TITLE
autoCreateTopics didn't work

### ISSUE THREAD

**Issue by ChangeDev** [spring-cloud/spring-cloud-stream#1181]
I have read some source code of SCSt, and I noticed that ```org.springframework.cloud.stream.binder.kafka.provisioning KafkaTopicProvisioner.createTopicsIfAutoCreateEnabledAndAdminUtilsPresent``` method，it says: if autoCreateTopics is true and adminUtilsOperation != null, then go to create topics and partitions.
and the adminUtilsOperation  only present if Kafka10Present or Kafka09Present (e.g. Kafka-clients must be 0.9.x.x or 0.10.x.x).  But in SCSt's Official website,  it says:
![image](https://user-images.githubusercontent.com/26902117/34980906-e1f553a6-fae0-11e7-8127-e3e2cc54d353.png).

**Comment by ChangeDev** [comment]
In addition, my SCSt'version is 1.3.0.

**Comment by ChangeDev** [comment]
Is there any wrong configuration in my project?

**Comment by ChangeDev** [comment]
Finally, I downgrade kafka-clients from 0.11.x.x to 0.10.x.x, the project works fine . It create topics and partitions according to my configuration.

**Comment by olegz** [comment]
@sobychacko @garyrussell can one of you please take a look at this and if necessary move to s-c-s-b-kafka?

**Comment by garyrussell** [comment]
You have to use the kafka11 binder instead of the kafka binder to use the 0.11 client with 1.3.x.

You have to override the kafka-clients, spring-kafka, spring-integration-kafka and kafka jars; see [this discussion on gitter](https://gitter.im/spring-cloud/spring-cloud-stream?at=5a42cda9ffa3e37919821737).

**Comment by ChangeDev** [comment]
Thanks a lot @garyrussell. It's really difficult for user to find compatibility jars when using kafka-clients 0.11.
So why don't you add compatibility jars  to docs or compatibility matrix .

**Comment by ChangeDev** [comment]
I have tried my project with :
<table>
<tr>
<td>spring-cloud-stream</td>
<td>1.3.0 (default referenced by spring-cloud-stream-dependencies Ditmars.RELEASE)</td>
</tr>
<tr>
<td>kafka-clients</td>
 <td>0.11.0.0</td>
</tr>
<tr>
<td>spring-cloud-stream-binder-kafka11</td>
<td>1.3.0.RELEASE</td>
</tr>
<tr>
<td>spring-kafka</td>
<td>1.3.2.RELEASE</td>
</tr>
<td>spring-integration-kafka</td>
<td>2.3.0.RELEASE</td>
</tr>
<td>kafka_2.11</rd>
<td>0.11.0.0 (same version as kafka-client)</td>
</td>
</table>
But when I run my app, I got a
 ```.NoSuchMethodError:org.springframework.cloud.stream.binding.StreamListenerMessageHandler.setNotPropagatedHeaders```.
I followed the source code, and found that ```org.springframework.cloud.stream.binding.StreamListenerMessageHandler``` is in spring-cloud-stream 1.3.0 and the method ```org.springframework.integration.handler.AbstractReplyProducingMessageHandler.setNotPropagatedHeaders()``` is in spring-integration-core 4.3.9(I found this jar is referenced by spring-cloud-stream 1.3.0).
Finally, I upgrade spring-integration-core to 4.3.12 and it work fine.

**Comment by garyrussell** [comment]
Thanks; I'll add that to the project page.
