### ISSUE TITLE
Inconsistent use of this.prefix in AvroSchemaRegistryClientMessageConverter.resolveSchemaForWriting

### ISSUE THREAD

**Issue by jmax01** [spring-cloud/spring-cloud-stream#1202]
Currently the prefix is hard coded in `AvroSchemaRegistryClientMessageConverter.resolveSchemaForWriting` to `vnd`:
 
```java
		if (headers instanceof MutableMessageHeaders) {
			headers.put(MessageHeaders.CONTENT_TYPE,
					"application/vnd." + schemaReference.getSubject() + ".v"
							+ schemaReference.getVersion() + "+avro");
}
```
I suspect the `prefix` field should be used consistently: 
```java
		if (headers instanceof MutableMessageHeaders) {
			headers.put(MessageHeaders.CONTENT_TYPE,
					"application/" + this.prefix + "." + schemaReference.getSubject() 
						+ ".v" + schemaReference.getVersion() + "+avro");
		}
```

**Comment by olegz** [comment]
@jmax01 this is indeed true and is being fixed. In fact there is already a PR that incorporates the change https://github.com/spring-cloud/spring-cloud-stream/pull/1198 (although unrelated to your issue). 
The main problem as you see is hat it relies on `MutableMessageHeaders` which as a user you do not control.
So I am keeping this issue open and linked to #1198
