### ISSUE TITLE
Include more jdbc drivers on the schema registry server pom

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#1206]
Currently we only ship with H2, but we could copy what the dataflow and skipper servers do today, by shipping MariaDB/PostgreSQL/SQLServer drivers as well which would allow users to just switch them via properties not requiring to rebuild the uber jar and include the drivers themselves.

**Comment by olegz** [comment]
I can't say I am fully on board with that. Having one allows me to get something to work out of the box. If I want to use different DB why can't I just bring the driver myself? Why have an ap with the classpth polluted with jars one will not use?

**Comment by viniciusccarvalho** [comment]
I've discussed this with @sabbyanandan. It's something both dataflow and skipper do today, with no much harm. You can at any point bring your own driver, this just lowers the barrier to start it up. The fact that dataflow has multiple drivers bundled within it helped quite a lot during our database acceptance tests scenarios, we only had to repackage for oracle and db2.

Just a suggestion, feel free to reject it, I don't mind

**Comment by olegz** [comment]
That's fine, we can still discuss it, and possibly do it if there is value. Just not sure about RC1.
