### ISSUE TITLE
AvroSchemaRegistryClientMessageConverter registers schema formats inconsistently.

### ISSUE THREAD

**Issue by jmax01** [spring-cloud/spring-cloud-stream#1217]
AvroSchemaRegistryClientMessageConverter.afterPropertiesSet:

```java
    //with print pretty	
    this.schemaRegistryClient.register(toSubject(schema), AVRO_FORMAT,
							schema.toString(true));
```
AvroSchemaRegistryClientMessageConverter.resolveSchemaForWriting:
```java
  //The ParsedSchema.representation is not print pretty
  SchemaRegistrationResponse response = this.schemaRegistryClient.register(
  toSubject(schema), AVRO_FORMAT, parsedSchema.getRepresentation());
```
This should be configurable via `AvroMessageConverterProperties`

Modified in PR:

- `AvroMessageConverterProperties`
- `AvroMessageConverterAutoConfiguration`
- `AvroSchemaRegistryClientMessageConverter`
- `ParsedSchema`

PR forthcoming

**Comment by olegz** [comment]
Merged as 275c212d4705d6fceae17b5ba3e27c8a6d88452f
