### ISSUE TITLE
Inconsistent use of AvroSchemaRegistryClientMessageConverter.AVRO_FORMAT 

### ISSUE THREAD

**Issue by jmax01** [spring-cloud/spring-cloud-stream#1218]
There are multiple spots where "avro" is supplied as a string when it should be sourced from AvroSchemaRegistryClientMessageConverter.AVRO_FORMAT.

- `super(Arrays.asList(new MimeType("application", "*+avro")));`
- `this.versionedSchema = Pattern.compile("application/" + this.prefix
				+ "\\.([\\p{Alnum}\\$\\.]+)\\.v(\\p{Digit}+)\\+avro");`
- `		_headers.put(MessageHeaders.CONTENT_TYPE,
				"application/" + this.prefix + "." + schemaReference.getSubject() 
				+ ".v" + schemaReference.getVersion() + "+avro");`
- `		return MimeType.valueOf("application/*+avro").includes(mimeType);`

Also it should be noted that reference to the "application/*+avro" MimeType should be via a constant.

**Comment by olegz** [comment]
Merged
