### ISSUE TITLE
Update relevant documentation on changes in Initializer

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1225]

**Comment by snicoll** [comment]
So the user experience is now to select "Spring Cloud Stream" or "Reactive Spring Cloud Stream" depending on your "target" environment (this is similar to what you do with "Web" or "Reactive Web" for webapp development.

Once you've selected your "flavour", you need a binder, either "RabbitMQ" or "Kafka". Initializr will bring the proper binder implementation based on this choice.

Please note that the test support jar is now also automatically added when any of the Spring Cloud Stream is selected.

What would be nice is two sections in the documentation that explains what you should select and perhaps a link to a sample or even a minimal sample in  the doc itself. Once we have that we can link those two sections from the Spring Cloud Stream and Reactive Spring Cloud Stream entries.

**Comment by olegz** [comment]
Update the release notes with it as well

**Comment by snicoll** [comment]
@olegz did this issue got closed with the wrong commit or am I missing something?

> What would be nice is two sections in the documentation that explain what you should select and perhaps a link to a sample or even a minimal sample in the doc itself. Once we have that we can link those two sections from the Spring Cloud Stream and Reactive Spring Cloud Stream entries.

To be clear, this request is about documenting how users can get started on start.spring.io now that there is an explicit support. The only commit I see is a bout "Binding visualization and control"

**Comment by olegz** [comment]
@snicoll No, commit is correct, but let me explain. The Initializer instructions went into [Quick Start](https://github.com/spring-cloud/spring-cloud-stream/commit/b93c784b56a9cd08c95cd4339f020edaeeef87b9#diff-369a0fe7a77fddec73a04336c6c349bdR121) section that we didn't have before. So I believe there is enough detail there.

**Comment by snicoll** [comment]
> No, commit is correct

This issue has been closed with a commit that sounds unrelated to the purpose of this issue. Thanks for the link, I can now look at what has changed.
