### ISSUE TITLE
Documentation should warn about MaxDirectMemorySize

### ISSUE THREAD

**Issue by odedia** [spring-cloud/spring-cloud-stream#1226]
Hi,

Based on the issue below:

https://github.com/cloudfoundry/java-buildpack-memory-calculator/issues/17

It appears that spring cloud stream kafka binder needs a good amount of direct memory buffer. 

However, in pivotal cloud foundry java buildpack, MaxDirectMemorySize is set to 10M by default. 

We noticed a lot of Direct Buffer Memory errors when we reached 20 partitions in a single instance running on PCF. When listening to 4-5 topics, it’s quite a reasonable scenario. We could not reproduce locally so it was very hard to find the root cause. 

I think it is important to explain the relationship between Kafka and direct buffer memory, and that JAVA_OPTS parameter should set -XX:MaxDirectMemorySize to a higher value in PCF when using cloud steam Kafka. 

Thanks.

**Comment by olegz** [comment]
@odedia Keep in mind that Spring Cloud Stream via Spring-Kafka are just the consumers of Apache Kafka API and technology in general. So what you pointing out is really not a Spring issue. And even with regard to documentation it also belongs in Apache Kafka documentation. So consider raising the issue with them.

So I am closing it with "won't fix" label with hopes that the explanation makes sense.
