### ISSUE TITLE
Multiple partition support per Sink instance

### ISSUE THREAD

**Issue by tajdars** [spring-cloud/spring-cloud-stream#1232]
I've a RabbitMQ binder based Stream Sink Service with parent set to : 

	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-build</artifactId>
		<version>1.3.7.RELEASE</version>
		<relativePath /> 
	</parent>

The input Topic is partitioned,
How can we get more than 1 Topic partition assigned to a  Sink Service instance ?

Basically we want to limit the  # of Sink Service instances but still get the parallelism across partitions.

Thanx,

**Comment by garyrussell** [comment]
It's not currently supported to consume from multiple partitions on one instance with the RabbitMQ binder. The app's `instanceIndex` determines which queue the instance consumes from.

You need at least one instance per partition. You can increase the consumer concurrency in each instance to provide parallelism.

**Comment by tajdars** [comment]
Thanx Gary,

Could we accept this as a feature request ?

We need the messages in a partition to be processed in order (single-threaded).
Increasing the consumer concurrency within a partition is not an option for us.

**Comment by olegz** [comment]
Please raise a separate issue in rabbit binder https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit and we'll see what we can do. You can also give it a try, submit a PR and we'll review it

**Comment by tajdars** [comment]
Hi @olegz , I will raise this on the rabbit binder side. 
Just thinking, wouldn't this be a generic feature applicable to multiple binders ?

Thanx,

**Comment by olegz** [comment]
Possible, but that should come naturally, so originate with Rabbit and then realize that it may be fixed in Stream core. Basically it is simpler that way since in when it's in Rabbit it's in-context

**Comment by olegz** [comment]
@garyrussell hmm, I kind of like this and thinking, may be that should not be treated as a workaround but rather "tips-and-tricks" with supporting sample?
I mean I am not against adding first class support in the future, but would prefer to bake it first and the above seems pretty clean
