### ISSUE TITLE
BinderAwareChannelResolver is not posting Sleuth Trace headers to Kafka (Cloud Version : Dalston.RELEASE)

### ISSUE THREAD

**Issue by WhiteLagoon** [spring-cloud/spring-cloud-stream#1245]
Hi,
I am new to spring cloud stream project.

I am trying to implement sleuth tracing with kafka stream binder for inter-communication tracing between Microservices. I am using BinderAwareChannelResolver class to create dynamic producer. But in kafka traceid,spanid not passing. Seems like TraceChannelInterceptor is not intercepting while using I am using 
bindingawarechannelresolver.resolveDestination(topicName).send(message);

I am using spring cloud version Dalston.RELEASE.

Here is the code : 

```
`@Autowired
    BinderAwareChannelResolver resolver;

public void send(String channelname) {
        String test = "{'app':'test'}";
        Message message = MessageBuilder.withPayload(test).setHeader("messageSent", "true").build();
        resolver.resolveDestination(channelname).send(message);
}
```
In producer app logs --> ```[2018-02-24T02:15:11.011Z] [9eb0c4d3f1a68ead,d75e395a3c9efd20,true] ```

in consumer app logs --> ```[2018-02-24T02:15:12.012Z] [10afe58f5b908b11,10afe58f5b908b11,false]```

in kafka console consumer log ---> ```�contentType   "text/plain"originalContentType    "application/json;charset=UTF-8"messageSent   "true"{'app':'test'}```

Can I get some help for that? Is there any workaround to fix this isssue? 
Thanks

**Comment by olegz** [comment]
@WhiteLagoon this is a known issue in 1.3 branch. We just (2 hours ago) released 2.0.RC1 where it has been fixed https://github.com/spring-cloud/spring-cloud-stream/commit/746dbc1bd3416e145ef55434dd4130dd0c0632ad, so please give it a try
Tagging @marcingrzejszczak as he was the initial reporter of it and verified the fix before it was merged.

**Comment by WhiteLagoon** [comment]
But I have a question, I am using spring boot version 1.5.8 with cloud version Dalston.RELEASE.
Can I use org.springframework.cloud:spring-cloud-stream:2.0.0.RC1 with those dependencies ?


Also I can't see any maven milestone release for spring-cloud-stream:2.0.0.RC1. 
When it will be available?
Thanks

**Comment by olegz** [comment]
It is available as of yesterday. If you go through the links that I included in the previous response (the announcement) you'll see the link to the mavenrepo

**Comment by WhiteLagoon** [comment]
Hi,
I have added the dependency cloud-stream-2.0.0.RC1 in my project. But even after adding, my project is not running.

Here is the stacktrace ::
[](https://github.com/WhiteLagoon/sample-cloud-stream-with-kafka-with-sleuth/blob/master/sample_service1/errorlog.txt)

here is my build.gradle
[](https://github.com/WhiteLagoon/sample-cloud-stream-with-kafka-with-sleuth/blob/master/sample_service1/build.gradle)

please have a look.

Thanks.

**Comment by olegz** [comment]
You have upgrade to Spring-Boot 2.0.0.RC2. The framework is indirectly referencing an SI class that did not exist prior to 5.x version.
That is visible from:
```
Caused by: java.lang.ClassNotFoundException: org.springframework.integration.support.converter.ConfigurableCompositeMessageConverter
        at java.net.URLClassLoader.find
```
Sure you can individually override certain versions of dependencies brought up by boot, but that implies a lot of internal knowledge, so as I said the best path forward is to simply upgrade to BOOT 2.0

**Comment by WhiteLagoon** [comment]
Thanks for your help.
But still if is there any workaround for this Spring BOOT version that might be very helpful. 

Thanks

**Comment by olegz** [comment]
@WhiteLagoon unfortunately back porting it would be a bit too complex since we trace the root of the issue back to Spring Integration so the bulk of the work was actually done there. In any event, in Spring there is *always* workaround and this case is no exception. If you look at the original JIRA that reported this exact issue @artembilan describes one of the workarounds. Here it is - https://github.com/spring-cloud/spring-cloud-stream/issues/1219
Meanwhile I hope your question got answered an no more action on this is required, so I am closing it, but feel free to raise a new one or reopen this one if you feel there is more to do.

**Comment by WhiteLagoon** [comment]
Hi,
Sorry for reopening this. This is just for review.
Yes you provided a workaround on #1219. But I don't have that much knowledge to implement that.
If you have any sample code it will be very helpfull.

But I got a workaround to pass the traceid and span id in through dynamic kafka producer.
using BindingService class.

Please have a look 
`https://github.com/WhiteLagoon/sample-cloud-stream-with-kafka-with-sleuth/blob/master/sample_service1/src/main/java/com/subhajit/sleuth/sample_service1/controller/DynamicProducer.java`


Please tell this workaround I can use it or not.
Thanks

**Comment by marcingrzejszczak** [comment]
This is how I did it for Sleuth - https://github.com/spring-cloud/spring-cloud-sleuth/commit/aa8edc9e7d500e3410794c5d2d5c7b9d64b17a93

**Comment by WhiteLagoon** [comment]
Hi, 
It's working. Its pushing the traceid and spanid to kafka. Now the TraceChannelIntereceptor is intercepteting the channel message and adding sleuth headers.

Thank you so much for your help.
