### ISSUE TITLE
Deprecate/Remove errorChannel->destination binding

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#1246]
This is confusing, and unnecessary; the proper way to send failed messages to a destination is via a DLQ implementation in a binder, where the binder can decide and/or enhance what is sent to the DLQ.

Messages on `errorChannel` are `ErrorMessage`s with a `Throwable` payload.

The rabbit and kafka binders attach the inbound raw data as a header.

If users want to take a different action to what the binder DLQ processing does, they can add a `@ServiceActivator` to consume `ErrorMessage`s from the global `errorChannel` or individual input `error` channels.

**Comment by artembilan** [comment]
Why just not have an internal `MessageChannel` in between `errorChannel` and target destination and include all the existing `ChannelInterceptor`s to let that `ErrorMessage` to be converted to expected `byte[]`?
Thanks

**Comment by olegz** [comment]
Closing it as duplicate to #1398
