### ISSUE TITLE
Deprecate MessageCollector in favor of TestBinder

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1253]
Given the new test binder i think we should use the opportunity to start quietly deprecating the existing test binder by simply removing references to it from the doc and instead show the new test binder and explain its benefits

- [x] Deprecate MessageCollector
- [x] Refactor binder impls to use the TestBinder
- [x] Draft a wiki with sample
- [x] Revise docs

**Comment by sabbyanandan** [comment]
Depends on #1314

**Comment by olegz** [comment]
So it is effectively deprecated with https://github.com/spring-cloud/spring-cloud-stream/commit/c56b4d1ea96a370b896886334ac72e734542e264. I've removed all references to it from the doc and included multitude of samples both functional and StreamListener. I've also added a task to https://github.com/spring-cloud/spring-cloud-stream/issues/1805 to ensure the deprecation is explicitly announced in the docs
