### ISSUE TITLE
global error channel and destination specific error channel are picking messages alternatively 

### ISSUE THREAD

**Issue by vikrantch-hk** [spring-cloud/spring-cloud-stream#1263]
running test first time(or odd time) : destination specific error channel is getting error and sending it to output channel (expected behavior)

running test second time(or even time) : global error channel is getting error then destination specific error channel is getting error but not sending it to output channel (expected behavior)

Error handler class : 
```
@EnableBinding(Processor.class)
public class ErrorHandler {
	
	
	@Autowired
	Deserializer deserializer;
	
	@ServiceActivator(inputChannel = "testhk24.hel1.errors" ,outputChannel="customDlqTopic", async="false", requiresReply="true", sendTimeout="0")
	public byte[] errorChannel(ErrorMessage em) {
		//em = null;
		byte[] arr = (byte[])((MessagingException)em.getPayload()).getFailedMessage().getPayload();
		System.out.println("error has been reported hel1 "+deserializer.deserializeMessage(arr).getEventJson()+" "+deserializer.deserializeMessage(arr).getEventJson() );
		return arr;
	}

	@ServiceActivator(inputChannel = "testhk24.hel2.errors" ,outputChannel="customDlqTopic2", async="false", requiresReply="true", sendTimeout="0")
	public byte[] errorChannel2(ErrorMessage em) {
		byte[] arr = (byte[])((MessagingException)em.getPayload()).getFailedMessage().getPayload();
		System.out.println("error has been reported hel2 "+deserializer.deserializeMessage(arr).getEventJson()+" "+deserializer.deserializeMessage(arr).getEventJson() );
		return arr;
		//em = null;
	}
	
	
	@ServiceActivator(inputChannel = "errorChannel", async="false", requiresReply="false", sendTimeout="0")
	public byte[] errorChannel3(ErrorMessage em) {
		byte[] arr = (byte[])((MessagingException)em.getPayload()).getFailedMessage().getPayload();
		System.out.println("global error has been reported "+deserializer.deserializeMessage(arr).getEventJson()+" "+deserializer.deserializeMessage(arr).getEventJson() );
		return arr;
		//em = null;
	}
```

**Comment by artembilan** [comment]
@garyrussell ,

Pay attention to this, please:
```
@ServiceActivator(inputChannel = "testhk24.hel1.errors" 
```

Can't it happen that `@ServiceActivator` is processed before Bindings and therefore that `testhk24.hel1.errors` is auto-created as `DirectChannel` instead of expected `PublishSubscribeChannel`?

Because then in the end we have:
```
if (defaultErrorChannel != null) {
	BridgeHandler errorBridge = new BridgeHandler();
	errorBridge.setOutputChannel(defaultErrorChannel);
	errorChannel.subscribe(errorBridge);
```
I mean we add one more subscriber to our `errorChannel` and have a round-robin balancing according a `DirectChannel` nature.

**Comment by artembilan** [comment]
@vikrantch-hk ,

I think a workaround for you is like:
```
@Bean(name = "testhk24.hel1.errors")
SubscribableChannel myError|Channel() {
    return new PublishSubscribeChannel();
}
```

**Comment by vikrantch-hk** [comment]
@artembilan thanks I'll try and let you know :)

**Comment by vikrantch-hk** [comment]
@artembilan should I make errorChannel bean as PublishSubscribeChannel also

**Comment by artembilan** [comment]
Well, it is as like that by default: https://docs.spring.io/spring-integration/docs/5.0.2.RELEASE/reference/html/messaging-channels-section.html#channel-special-channels

**Comment by vikrantch-hk** [comment]
@artembilan now pattern of error channel calling is consistent but every alternate time destination error channel is not sending message to outputchannel

**Comment by artembilan** [comment]
>  every alternate time destination error channel is not sending message to outputchannel

Sorry, that isn't clear for me what you mean.

Maybe you can turn on `DEBUG` for the `org.springframework.integration` category and take a look into logs how your messages are traveling. Especially I'm interested in the part of `preSend` on the `testhk24.hel1.errors` and above.

**Comment by vikrantch-hk** [comment]
presend is getting called always for CUSTOM_DLQ_TOPIC1, CUSTOM_DLQ_TOPIC2 but flow doesn't go in stream listener for CUSTOM_DLQ_TOPIC1, CUSTOM_DLQ_TOPIC2 second time (every even time)

**Comment by artembilan** [comment]
Hm. That sounds like a different story. 

Have we fixed already your concern about odd-even on the `testhk24.hel1.errors` ?
So, let's close the ticket!

Maybe the same happens on your `customDlqTopic`, but that still looks like a different story.

Please, don't confuse us with complex configurations, like showing these two topics,

That's your application, but we have here a lot of different stuffs to deal with: simple code from your with proper description - quicker reaction from us and less comments like this mine for nothing.

Thanks for understanding

**Comment by vikrantch-hk** [comment]
it's ultimately same issue error messages are being sent to output channels odd times only not even times

**Comment by vikrantch-hk** [comment]
is there a way to by pass global errorchannel and handle channel specific errors in channel specific errorchannels only

**Comment by artembilan** [comment]
So, you have several subscribers to that `customDlqTopic` as well.

Your last comment is not related. Anyway the answer is "No". By default global `errorChannel` has just `LoggingHandler` subscriber, nothing more. The problem is somehow with your `DirectChannel`s and several subscriber for them. Nothing more is there about round-robin.

**Comment by vikrantch-hk** [comment]
there is one subscriber for @ServiceActivator(inputChannel = "testhk24.hel2.errors" ,outputChannel="customDlqTopic2" , problem is every alternate time serviceactivator is not pushing error message to outputchannel topic

**Comment by artembilan** [comment]
Well, you see you still don't format code properly... :sigh:

And GH issues are not a chat.

Please, share with us as simple Spring Cloud Stream app as possible with the detailed README how to reproduce and what is expected. We will pull it locally and play with the code, logs and debug mode to determine what's going on. 

That's my vision because I don't feel the feature properly, so I don't have an immediate answer what and how should be configured.

**Comment by vikrantch-hk** [comment]
@artembilan thanks a lot that's been a great help my topic stream listener wasn't configured properly now error channels behavior is consistent :)

**Comment by garyrussell** [comment]
>Pay attention to this, please:

Sorry - I have been busy this week and missed this mention somehow.

@artembilan please open an issue; we should at least log a warning if the application has predeclared an unexpected channel type, and add a warning to the documentation.

I suppose another work-around would be to `@Autowire` the error channel and manually subscribe a `MessageHandler` to it.

**Comment by garyrussell** [comment]
I guess another option would be to NOT bridge it to the global `errorChannel` if it's not a pub/sub channel (and log a warn).
