### ISSUE TITLE
Revise the error infrastructure logic

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream#1269]
When we have a code like:
```
@ServiceActivator(inputChannel = "myDestination.myGroup.errors")
public byte[] errorChannel(ErrorMessage em) {
```

We end up with the `DirectChannel` and subscriber for the service activator. At the same time we still subscribe a `BridgeHandler` for the global `errorChannel` as a second subscriber to this auto-created channel. And we end up with the round-robin distribution where `ErrorMessage` is sent.

Reconsider a logic do not register a `BridgeHandler` for the global `errorChannel` when the target mesage channel is not `PublishSubscribeChannel`. Or do that via `WireTap`...

See more info in the https://github.com/spring-cloud/spring-cloud-stream/issues/1263#issuecomment-369606969

**Comment by garyrussell** [comment]
Also consider the implications when a DLQ is configured since the DLQ handler is also subscribed to the binding's input channel.

**Comment by olegz** [comment]
@sobychacko @artembilan @garyrussell I believe this one #1398 once addressed will effectively resolve this ticket. Correct?
