### ISSUE TITLE
spark streaming processor support

### ISSUE THREAD

**Issue by komushi** [spring-cloud/spring-cloud-stream#1274]
Similar to Spring XD spark streaming processor example
https://github.com/spring-projects/spring-xd-samples/tree/master/spark-streaming-wordcount-java-processor

Will a similar processor be supported with scs?

**Comment by sabbyanandan** [comment]
Hi, @komushi. We don't have plans to integrate Spark Streaming in the programming model. If the requirement is to perform stateful operations, please have a look at [Project Reactor](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RC2/reference/htmlsingle/#_reactor_based_handlers) (see [example1](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/reactive-processor) & [example2](https://github.com/sabbyanandan/sensoraverage)) and [Kafka Streams](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RC2/reference/htmlsingle/#_apache_kafka_streams_binder) (see [examples](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams)) integration. 

Also, we have a few [OOTB Task applications](https://github.com/spring-cloud-task-app-starters?utf8=%E2%9C%93&q=spark&type=&language=) to launch Spark Jobs.

Lastly, for questions like this, it'd be great if you can use [StackOverflow](https://stackoverflow.com/questions/tagged/spring-cloud-stream) going forward.

**Comment by komushi** [comment]
Thanks a lot
