### ISSUE TITLE
Where has the module spring-cloud-stream-codec gone?

### ISSUE THREAD

**Issue by philiplourandos** [spring-cloud/spring-cloud-stream#1277]
I'm trying to upgrade https://github.com/spring-cloud/spring-cloud-stream-binder-jms so that we can upgrade to spring-boot 2 for our projects. There is a dependency on org.springframework.cloud.stream.config.codec.kryo.KryoCodecAutoConfiguration. Has this been moved to another module/project or been deprecated?

**Comment by olegz** [comment]
@philiplourandos  Yes, the module is no longer used  and was removed in Spring Cloud Stream 2.0.0.RELEASE which [has been released few days ago](https://spring.io/blog/2018/04/10/announcing-general-availability-of-spring-cloud-stream-elmhurst-release-2-0-0-release). 
We've also [deprecated type-based serialization such as Kryo and Java serialization](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/#spring-cloud-stream-preface-notable-deprecations).
That said, the module is still available in 1.3 so you can use it.
Also, keep in mind that only [Kafka](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka) and [Rabbit](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit) binders are currently supported and neither requires Kryo.

I am closing this issue as the question has been answered, but feel free to open another issue if you have more questions/concerns.
