### ISSUE TITLE
Rework bindings endpoint to avoid using verbs in URIs

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-stream#1286]
It's generally considered bad practice to use verbs in a URI of a RESTful API (even for very loose definitions of RESTful):

 - https://apigee.com/about/blog/technology/restful-api-design-nouns-are-good-verbs-are-bad
 - https://blog.philipphauer.de/restful-api-design-best-practices/#use-nouns-instead-of-verbs-for-resources

The current bindings endpoint exposes four different resources, each with a verb in its URI, for controlling the state of a binding:

- `http://<host>:<port>/actuator/bindings/start/{name}`
- `http://<host>:<port>/actuator/bindings/stop/{name}`
- `http://<host>:<port>/actuator/bindings/pause/{name}`
- `http://<host>:<port>/actuator/bindings/resume/{name}`

Each resource only supports `POST` requests.

The approach that's generally recommend for this sort of thing is to provide a single `state` resource instead:

- `http://<host>:<port>/actuator/bindings/state/{name}`

A `GET` request can be used to query the resource's current state and a `POST` request can be used to update the state. The payload of the `POST` request is used to indicate the desired state of the resource. For example, a stopped binding could be started by making a `POST` request with the following body:

```
{
    "state": "STARTED"
}
```

**Comment by olegz** [comment]
Given that this is new functionality that has never been released publicly we can certainly change it and what Andy is saying makes perfect sense.

**Comment by sobychacko** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream/commit/e939e09e95f51cffa16354721ccae6765e11cb25
