### ISSUE TITLE
Kafka messages are reprocessed

### ISSUE THREAD

**Issue by YossiShasha** [spring-cloud/spring-cloud-stream#1290]
We have a micro-services that produces and consumes messages from Kafka using spring-boot and spring-cloud-stream. 
<br>versions: <br>
spring-boot: 1.5.8.RELEASE <br>
spring-cloud-stream: Ditmars.RELEASE <br>
Kafka server: kafka_2.11-1.0.0 <br>

**EDIT:**
We are working in a Kubernetes environment using StatefulSets cluster of 3 Kafka nodes and a cluster of 3 Zookeeper nodes. 

We experienced several occurrences of old messages that are reprocessed when those messages where already processed few days ago. <br>
Several notes: <br>

 1. Before that happens the following logs were printed (there are more similar lines this is just a summary)

> Revoking previously assigned partitions [] for group enrollment-service <br>
> Discovered coordinator dev-kafka-1.kube1.iaas.watercorp.com:9092 (id: 2147483646 rack: null) <br>
> Successfully joined group enrollment-service with generation 320 <br>

 2. The above-mentioned incidents of revoking and reassigning of partitions happens every few hours. And just in few of those incidents old messages are re-consumed. In most cases the reassigning doesn't triggers message consumption.
 3. The messages are from different partitions.
 4. There are more than 1 message per **partition** that is being reprocessed.

application.yml: 

<pre>
spring:
  cloud:
      stream:
        kafka:
          binder:
            brokers: kafka
            defaultBrokerPort: 9092
            zkNodes: zookeeper
            defaultZkPort: 2181
            minPartitionCount: 2
            replicationFactor: 1
            autoCreateTopics: true
            autoAddPartitions: true
            headers: type,message_id
            requiredAcks: 1
            configuration:
              "[security.protocol]": PLAINTEXT #TODO: This is a workaround. Should be security.protocol
          bindings:
            user-enrollment-input:
              consumer:
                autoRebalanceEnabled: true
                autoCommitOnError: true
                enableDlq: true
            user-input:
              consumer:
                autoRebalanceEnabled: true
                autoCommitOnError: true
                enableDlq: true
            enrollment-mail-output:
              producer:
                sync: true
                configuration:
                  retries: 10000
            enroll-users-output:
              producer:
                sync: true
                configuration:
                  retries: 10000
        default:
          binder: kafka
          contentType: application/json
          group: enrollment-service
          consumer:
            maxAttempts: 1
          producer:
            partitionKeyExtractorClass: com.watercorp.messaging.PartitionKeyExtractor
        bindings:
          user-enrollment-input:
            destination: enroll-users
            consumer:
              concurrency: 10
              partitioned: true
          user-input:
            destination: user
            consumer:
              concurrency: 5
              partitioned: true
          enrollment-mail-output:
            destination: send-enrollment-mail
            producer:
              partitionCount: 10
          enroll-users-output:
            destination: enroll-users
            producer:
              partitionCount: 10
</pre>

Is there any configuration that I might be missing? What can cause this behavior?

**Comment by olegz** [comment]
@YossiShasha I see you are using Kafka 1.x with Spring Cloud Stream 1.x. I am not sure we were even supporting Kafka 1.x with Ditmars, but @garyrussell may clarify.
That said, We are currently in RC2 and release is imminent. This release and Kafka binder specifically designed around Kafka version 0.11+ so please consider upgrading to Boot 2.0.0.RELEASE, Spring Cloud Stream 2.0.0.RC2 , Cloud Finchley M8

**Comment by garyrussell** [comment]
Ditmars pulls in a very old Spring-Kafka version (1.1.x); at a minimum, I would recommend upgrading to the 1.3.0 kafka11 binder, which is provided as a stand-alone artifact for Ditmars; the dependency overrides are discussed at the bottom of [the project page](https://cloud.spring.io/spring-cloud-stream/). It uses spring-kafka 1.3.x which has a much simpler threading model, thanks to KIP-62.

**Comment by YossiShasha** [comment]
OK, thanks guys. We will upgrade to Spring Cloud Stream 2.0.0.RC2. When I will have conclusions on whether the upgrade has solved this problem or not I will update here.

**Comment by olegz** [comment]
@YossiShasha at this point given that you're using Kafka I would probably recommend to upgrade to Spring Cloud Stream 2.0.0.BUILD-SNAPSHOT to avoid falling into a trap of https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/322 (although there is an easy workaround described there). But we'll have RC3 today/tomorrow so the snapshot is pretty solid at this point and a good representation of what to expect in RELEASE (shortly).

**Comment by garyrussell** [comment]
That all being said, I am not aware of any situation where the framework would reset an offset to cause message reprocessing - I have seen problems with kafka's `enable.auto.commit.offset` in the past; I would definitely recommend making sure that's false, so the container controls the offsets. The binder sets it to false by default so it shouldn't be `true` unless you override it (which doesn't appear to be the case in your .yml).

**Comment by YossiShasha** [comment]
@garyrussell you mean enable.auto.commit property?
For some reason this value is set to true as the logs are showing:

<pre>
        ....
        auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [dev-kafka-kafka:9092]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = 
        ....
</pre>

But processing messages from days ago (and more than 1 message per partition) is something that can be caused by this configuration?

**Comment by YossiShasha** [comment]
That's really strange. The printing of this configuration is triggered by /health call like described here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/243 
The Consumer configuration that is printed in startup is indeed `enable.auto.commit = false` as we would expect since we are not overriding the configuration in our .yml.

**Comment by garyrussell** [comment]
That's a dummy consumer used to check the health; it uses the default consumer factory which has `enable.auto.commit` true; it's not pertinent since that consumer never actually consumes anything.

The issue of spitting out the config each time is fixed, as noted in that issue.

So; with `false` on the real consumer, I have no clue how messages can get reprocessed.

**Comment by olegz** [comment]
It appears the question has been answered, so I am closing this issue. Feel free to re-open it if you still have concerns

**Comment by YossiShasha** [comment]
So the actual problem is the one that is described in the following ticket: https://issues.apache.org/jira/browse/KAFKA-3806. Using the suggested workaround fixed it.
