### ISSUE TITLE
Unable to create StreamsBuilderFactoryBean bean

### ISSUE THREAD

**Issue by Veske** [spring-cloud/spring-cloud-stream#1300]
I followed this page: http://cloud.spring.io/spring-cloud-stream/ to set up the dependecy versioning for my Kafka stream processor.

As we use Kafka 0.11.0x, I was looking into the dependency matrix and read out this information:

![screen shot 2018-03-13 at 18 15 26](https://user-images.githubusercontent.com/5602603/37354523-89aca1d2-26ea-11e8-9348-2737fba0e20c.png)

So I opted to the following versions:

- spring-boot-starter-parent: 2.0.0.RELEASE
- spring-cloud-stream-dependencies: Elmhurst.RC3
- spring-kafka: 2.0.3.RELEASE
- kafka-clients: 0.11.0.2

According to the matrix, this should be a working version combination. But when I look into the 
`KafkaStreamsBindingInformationCatalogue` class, it is trying to build a bean for `StreamsBuilderFactoryBean` which does not exist in `spring-kafka 2.0.3`. It was renamed to `StreamsBuilderFactoryBean` in `spring-kafka 2.1x` from `KStreamBuilderFactoryBean`.

What is the official way to use the version combination then if one would take this class conflict into consideration? I would like to use the DLQ feature of the new spring cloud stream, but as of now I am forced to use a kafka 0.11x version.

**Comment by Veske** [comment]
Would I need to set some parameters in that case to say in what protocol I am speaking in or does Spring cloud stream handle this automatically?

**Comment by garyrussell** [comment]
No; even Spring doesn't have to deal with it; it's handled automatically by Kafka - the client and broker negotiate.

**Comment by garyrussell** [comment]
Matrix updated.

**Comment by garyrussell** [comment]
The only caveat is you must not set `spring.cloud.stream.kafka.binder.auto-add-partitions` to `true` with that combination.

**Comment by Veske** [comment]
Thank you, can close this issue. The solution to use latest Kafka client seems to work.
