### ISSUE TITLE
Documentation typo in converters topic

### ISSUE THREAD

**Issue by Veske** [spring-cloud/spring-cloud-stream#1303]
In the documentation paragraph: https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RC3/reference/htmlsingle/#_user_defined_message_converters

There is a line saying to use the `@StreamMessageConverter` on top of a custom converter bean method. Right after that the code sample advises the reader to use `@StreamConverter` instead.
```
    @Bean
    @StreamConverter
    public MessageConverter customMessageConverter() {
        return new MyCustomMessageConverter();
    }
```
The code sample should probably use the correct annotation also.

**Comment by olegz** [comment]
This will be addressed in #1313
