### ISSUE TITLE
Avro deserialization reader schema required even when writer schema available

### ISSUE THREAD

**Issue by elric77** [spring-cloud/spring-cloud-stream#1304]
This flow chart in this documentation: https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/schema-evolution.html#_schema_resolution_process_deserialization states that if a reader schema is not present it will be set to the writer schema.  The code seems to contradict this though
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AbstractAvroMessageConverter.java#L132-L148

It seems you must have a reader schema set via the spring.cloud.stream.schema.avro.readerSchema property.  If that is the case, why even bother fetching the writer schema from the registry?  I probably don't understand Avro enough, but shouldn't it be possible for downstream consumers to not have any reader schema defined and just use the writer schema from the registry to deserialize Avro messages?

**Comment by olegz** [comment]
Actually you may have been looking at the wrong code.
In `AvroMessageConverterConfiguration:59` there is a code that will check if `readerSchema` is set and if so it will be propagated to the actual `AvroSchemaRegistryClientMessageConverter`.
Then the attempt to determine `writerSchema` by first checking if `readerSchema` is present:
```
89: Schema writerSchema = resolveWriterSchemaForDeserialization(mimeType);
90: Schema readerSchema = resolveReaderSchemaForDeserialization(targetClass);
```
. . . basically the resolution process you're referring to.

Now, while there may still be an issue and/or room for improvement, the important thing to realize is the code in question is in the specific implementation of the `MessageConverter` which in itself is one of the extension points of _spring-cloud-stream_ and if this particular one doesn't serve your purpose, you can always provide your own implementation either from scratch or extended from the existing one and than bootstrapped as a `@Bean` in your app while additionally annotated with `@StreamMessageConverter`.

**Comment by elric77** [comment]
Hi Oleg, thank you for the response.
It's very possible that I'm not following the flow properly.  Also, I probably should of stated the actual observation: when you use a GenericRecord and do not provide a reader schema but do provide a writer schema deserialization will fail because a reader schema is not found.  I do not have any proof though and you would know the code better.

The team decided to use JSON schema instead of Avro for now so this isn't really a problem anymore.  I'll try writing a custom MessageConverter if this comes up again.

Thank you for looking into this.

**Comment by olegz** [comment]
I will close it for now, but sure feel free to reopen it if you still have issues
