### ISSUE TITLE
Provide a way to customize error handling on Source, Sink and Processor

### ISSUE THREAD

**Issue by noahmonster** [spring-cloud/spring-cloud-stream#1305]
I have been unable to find a way to override the default behavior when one of my Processors throws an exception.  Currently, all of the exceptions seem to get passed to a handler in the binder that I'm using.  I'm using the Kafka Binder, and the exceptions are all getting logged with `org.springframework.kafka.listener.LoggingErrorHandler`

This is problematic for me because I have people's personal information in the Kafka messages that I don't want in my logs.  I *could* turn off logging for the `LoggingErrorHandler`, but really I just want to prevent it from logging the Kafka message.

Really, it would be nice to provide a custom error handler for my Processor via some sort of annotation/configuration.

**Comment by olegz** [comment]
@noahmonster as you may have heard we [just released Spring Cloud Stream 2.0.0.RELEASE](https://spring.io/blog/2018/04/10/announcing-general-availability-of-spring-cloud-stream-elmhurst-release-2-0-0-release) which contains several bug fixes and enhancements directly related to your question. It also contains a completely new [Error Handling](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/#spring-cloud-stream-overview-error-handling) section which provides details you are looking for.

Please go thru it and let us know if something is missing and/or your question/concern is addressed.

Thank you

**Comment by olegz** [comment]
@noahmonster do you believe there is anything that still needs to be done or should we close it?

**Comment by noahmonster** [comment]
It seems like this will be sufficient.  I'm still a bit unclear as to how this will play with the existing error handling and whether `LoggingErrorHandler`, as noted above, will still be called.

**Comment by olegz** [comment]
Well, let us know if you believe something is still a miss
