### ISSUE TITLE
Typo "critiical" in reference guide

### ISSUE THREAD

**Issue by EHJ-52n** [spring-cloud/spring-cloud-stream#1322]
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#partitioning as a typo in section 2.5 Partitioning Support:

> Partitioning is a critical concept in stateful processing, where it is **critiical**, for either performance

It should be **critical** both times with single **i**s.

**Comment by olegz** [comment]
Actually it has already been fixed on the master, but thanks for looking into that anyway
