### ISSUE TITLE
Any plan to support redis Pub/Sub based streaming?

### ISSUE THREAD

**Issue by half-dead** [spring-cloud/spring-cloud-stream#1329]

**Comment by sabbyanandan** [comment]
Hi, @half-dead. Thanks for your interest in Spring Cloud Stream! We have had a [redis-binder](https://github.com/spring-cloud/spring-cloud-stream-binder-redis), but it hasn't been maintained in a long time. In Spring Cloud Stream, the framework builds upon a few opinions, as described in the [main-concepts](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.BUILD-SNAPSHOT/reference/htmlsingle/#_main_concepts) section, and Redis doesn't fully address all the requirements yet.

However, there's a [spec for Redis Streams](https://gist.github.com/antirez/68e67f3251d10f026861be2d0fe0d2f4) (see also [here](http://antirez.com/news/116)), which comes with consumer-groups, offset management and the like. We will revisit the binder implementation when Redis 5.0 is released. 

In the meantime, please try out RabbitMQ or Kafka binders and let us know if you have any feedback.

**Comment by half-dead** [comment]
Thanks for quick response, we're currently using RabbitMQ.
I'm only asking this because we're more familiar and comfortable with redis.
