### ISSUE TITLE
is there a kafka sample or documentation ?

### ISSUE THREAD

**Issue by iamiddy** [spring-cloud/spring-cloud-stream#134]

**Comment by Blackbaud-KevinHutson** [comment]
@iamiddy 
:+1: More samples would be nice. 
I found this today but I haven't had a chance to test the approach. It only has a producer, no consumer.
https://github.com/jbrisbin/tfl-ingest

**Comment by mbogoevici** [comment]
Hi,

Unfortunately we haven't put together a set of dedicated examples yet (we welcome contributions!). Generally speaking though, taking any of the current examples and switching to the Kafka binder should work.

Hope this helps,
Marius

**Comment by frosenberg** [comment]
How do you switch to the Kafka binder? Does this mean changing all `pom.xml` files of the modules?

**Comment by olmoser** [comment]
a straight forward (but compile time only) way to control which binder should be used could be maven profiles for the various binders. Although i'm not a big fan of this approach it would also make sure that the size of the fat JAR stays reasonable (in contrast to including all binders in the packaging phase and using properties to control which binder should be applied). It really depends on whether you need this runtime configurable or nor.

**Comment by mbogoevici** [comment]
From the simple point of view of the uberjar - compiling the 'correct' binder is the way to go. 

Using the module launcher, you can modify the classpath of the launched module at runtime (regardless what binder they have been packaged with) via boot properties, i.e.  `--includes=org.springframework.cloud:spring-cloud-stream-binder-kafka:1.0.0.BUILD-SNAPSHOT --excludes=::*-binder-redis` to swap the binder without recompiling.

If you are using Spring Cloud Data Flow, you can currently pass include/exclude properties per module (e.g. `module.`as well as using the `module.*.includes` idiom).

**Comment by sabbyanandan** [comment]
Hi @iamiddy, @Blackbaud-KevinHutson, @olmoser, @frosenberg: Hopefully, @mbogoevici's suggestions were helpful. We will be addressing documentation in general with examples via: #212 as soon as we wrap-up #138, #172, and #173.

Please let us know if you have any other questions or feedback. Closing this for now.
