### ISSUE TITLE
Add a spring-cloud-stream-binder for Amazon SQS

### ISSUE THREAD

**Issue by mstine** [spring-cloud/spring-cloud-stream#135]
Seems like this should be relatively easy by leveraging the SQS support in Spring Cloud AWS. We'd like to use this to support https://github.com/spring-cloud/spring-cloud-netflix/issues/545, so that we can use SQS when running Spring Cloud Services on PWS.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-starters#8
