### ISSUE TITLE
Spring Cloud Stream vs Spring Kafka

### ISSUE THREAD

**Issue by steve-roy** [spring-cloud/spring-cloud-stream#1350]
Hi,

When would it be recommended to develop against Spring Kafka vs Spring Cloud Stream?

Thank you,
- steve

**Comment by steve-roy** [comment]
Thanks Gary.  That helps.

Could you provide an example or two of opinionated configuration that can be overridden?  Where does the opinion come in?

**Comment by garyrussell** [comment]
Some examples:

On the consumer side. if there is an instanceCount, the binder will create a topic with `instanceCount * concurrency` partitions; can be overridden with the binder property `minPartitionCount`.

If a binding has a `group`, the `auto.offset.reset` is set to `earliest` (so new groups start from the beginning), with no group, `auto.offset.reset` is `latest` (start from the topic end).

Consumer retry is configured with default parameters (e.g. 3 delivery attempts), can be overrridden.

etc, etc.

The "opinions" are either in code, or default values in `KafkaProducerProperties`, `KafkaConsumerProperties` (kafka specific) or other properties (common to all binders, such as retry).

Generally, you should refer to properties documentation in the Spring Cloud Stream docs.

**Comment by steve-roy** [comment]
Thanks!
