### ISSUE TITLE
Default spring.cloud.stream.rabbit.* properties to appy to multiple consumers?

### ISSUE THREAD

**Issue by yngwietiger** [spring-cloud/spring-cloud-stream#1360]
Is there a way to specify default RABBIT properties to apply to multiple consumers?

e.g. I currently have some configuration like this:

```
spring.cloud.stream.rabbit.bindings.testChannel.consumer.bindingRoutingKey=TEST
spring.cloud.stream.rabbit.bindings.testChannel.consumer.auto-bind-dlq=true
spring.cloud.stream.rabbit.bindings.testChannel.consumer.dlq-ttl=10000
spring.cloud.stream.rabbit.bindings.testChannel.consumer.dlq-dead-letter-exchange=

spring.cloud.stream.rabbit.bindings.testChannel2.consumer.bindingRoutingKey=TEST2
spring.cloud.stream.rabbit.bindings.testChannel2.consumer.auto-bind-dlq=true
spring.cloud.stream.rabbit.bindings.testChannel2.consumer.dlq-ttl=10000
spring.cloud.stream.rabbit.bindings.testChannel2.consumer.dlq-dead-letter-exchange=
```

But it would be cleaner if I could just specify defaults for the DLQ properties, like:

```
spring.cloud.stream.rabbit.bindings.default.consumer.auto-bind-dlq=true
spring.cloud.stream.rabbit.bindings.default.consumer.dlq-ttl=10000
spring.cloud.stream.rabbit.bindings.default.consumer.dlq-dead-letter-exchange=

spring.cloud.stream.rabbit.bindings.testChannel.consumer.bindingRoutingKey=TEST
spring.cloud.stream.rabbit.bindings.testChannel2.consumer.bindingRoutingKey=TEST2
```
And it becomes even more obvious when I have like 5 or more queueus.

I thought I saw a ticket once (can't find it now), but not sure if there was ever any resolution.

BTW, I'm on version 1.2.1.RELEASE of spring-cloud-starter-stream-rabbit.

Is this possible? Is it in the works? Is there a better way to do this for lots of queues? I'm tempted to develop my own utility to build all queues/bindings/etc and avoid having a ton of configuration. 

Thanks.

**Comment by garyrussell** [comment]
It is not currently possible; we are considering adding this as a future enhancement.

**Comment by sobychacko** [comment]
For core producer/consumer properties, the defaults are applied as `spring.cloud.stream.default.<producer>|<consumer>.<property-name>`. For the extended properties, we will need to have something that is consistent. For example, for the rabbit binder, `spring.cloud.stream.rabbit.default.consumer.bindingRoutingKey=TEST` which will be applied against all the consumer bindings. Same should be applied for the extended producer properties as well.
