### ISSUE TITLE
Error handling 

### ISSUE THREAD

**Issue by azmym** [spring-cloud/spring-cloud-stream#1363]
I am using spring cloud reactive stream and confused for error handling, 
Currently I have the following logic with Kafaka 
```
flux<message>.flatMap(some-business)
                .flatMap(some-business)
                .map(some-business)
                .retry()
                .subscribe()
``` 
my exception when error happen the exception will be captured by retry, and retry again with the same message, but actually it retry again with another message !! , when using doOnError() , the stream is terminating and stop consume messaging, would you please provide advice ?

**Comment by sabbyanandan** [comment]
Hi, @smaldini. In our recent sync-up, @artembilan had mentioned about a few improvements coming up in 3.2.0. In the meantime, do you have any suggestions on the best practices for the described scenario?

**Comment by olegz** [comment]
@azmym any chance you can post a sample app that fails somewhere in the github?

**Comment by azmym** [comment]
@olegz my current application is not failing but not meet business exception, currently business requirement is when an error has been happened during message processing, keep try with the same message and don't process another message, but when using retry() and error happen, the application leave the current one (unacknowledged) and get the next message !!!

application.properties
```
#Kafka configuration
spring.kafka.bootstrap-servers=192.168.99.100:9092
#Binder Configuration
spring.cloud.stream.kafka.binder.brokers=192.168.99.100
spring.cloud.stream.kafka.binder.defaultBrokerPort=9092
spring.cloud.stream.kafka.binder.zkNodes=192.168.99.100
#Cofigure reading topic
spring.cloud.stream.bindings.inputTopic.destination=test
spring.cloud.stream.bindings.inputTopic.group=testGroup
spring.cloud.stream.kafka.bindings.inputTopic.contentType=application/json
spring.cloud.stream.kafka.bindings.inputTopic.consumer.autoCommitOffset=false
spring.cloud.stream.kafka.bindings.inputTopic.consumer.partitioned=true
```
Binder interface
```
public interface BinderProcessor {

    String INPUT="inputTopic";

    String OUTPUT="outputTopic";

    @Input(INPUT)
    SubscribableChannel inputTopic();

    @Output(OUTPUT)
    MessageChannel outputTopic();
}
```

```
@EnableBinding(BinderProcessor.class)
@Component
public class FlowManager extends BasicFlow {

@StreamListener
    public void manage(@Input(BinderProcessor.INPUT) Flux<Message> message) {
      message.map(productMessage ->
         convert((byte[]) productMessage.getPayload())
     ).retry()
     .subscribe();
    }

  private static Optional<JsonNode> convert(byte[] productByte) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            return Optional.of(mapper.readTree(productByte));
        } catch (IOException e) {
            throw new BusinessException("Error parsing product json", e);
        }
    }
}
```
Now when IOException be fired, the main stream will resubscribe and process the next message, I wanna to keep try with the same message and fire the exception multi time so we can see that in mentoring screen and fix the problem /message before processing the next one , 

I hope this example illustrated my current case

**Comment by olegz** [comment]
@azmym We are in the process of a bit of a restructuring by bringing spring-cloud-function](https://github.com/spring-cloud/spring-cloud-function) as a dependency to spring-cloud-stream. With that we're bringing an improved reactive support, so stay tuned for updates.
That said, for your case you may find it a bit simpler (at least for now) to have a simple Message Handler instead of reactive. Keep in mind that re-try is already wired up via RetryTemplate in Message Listener Container. So your application should look as follows:
```
@EnableBinding(BinderProcessor.class)
@Component
public class FlowManager extends BasicFlow {

@StreamListener
 public void manage(Message<JsonNode> jsonNode) {
      // do whatever you need to do and if it fails it will automatically retry
      // see https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/#spring-cloud-stream-overview-error-handling for more details
 }

```
Also, as you can see you don't need to manually convert the message since it will be automatically converted for you by the framework since `application/json` is the default content type since 2.0.

Please give it a try and let us know if you still have any more questions.
