### ISSUE TITLE
Make Jackson an optional dependency

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#1364]
Even if JSON is a default content type, as a user I would like the option at least to use Gson (and possibly other libraries supported by Spring Boot).

I just changed spring-cloud-function-web to use Gson. It uses the same conventions as Spring Boot, but makes Gson the only mandatory dependency. That way the user can easily switch to Jackson just by including it in the classpath.

**Comment by olegz** [comment]
Given that we're moving toward s-c-function programming model which already provides type conversion support natively via MessageConverters, there is really nothing to do here
