### ISSUE TITLE
Improve AggregateApplication developer experience

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1371]
As a developer, I'd like to revisit the `AggregateApplication` expectations, so we can come up with a set of improvements to simplify the development and testing experience.

**Acceptance:**
- Study the interoperability between Spring Cloud Function and Spring Cloud Stream
- Determine the programming vs. binding model boundaries
- Think about the developer experience wrt business logic as a standalone pluggable beans
- Think about the testing experience of pluggable beans in the context of suppliers and consumers

**Comment by PedroAlvarado** [comment]
Allow me to raise awareness of the two issues below in the context of Aggregate Applications. 

https://github.com/spring-cloud/spring-cloud-stream/issues/449
https://github.com/spring-cloud/spring-cloud-stream/issues/450

Architecturally, being able to run applications standalone or collocated/aggregated in-jvm with minimal friction(e.g not having to write two different apps from scratch) can be a major differentiator between SCS and anything else in the market while providing a versatile runtime/programming model. 

I understand that this may not be in the scope of this issue, nonetheless, this feedback may be relevant in the context of said improvements.

**Comment by sabbyanandan** [comment]
Hi, @PedroAlvarado. Thanks for showing interest in this improvement. It helps validate and further solidifies the direction.

We are indeed looking into decoupling the expectations of standalone applications as full-blown uber-jars, but instead reimagining them as simple reusable functions. That, you could plug it at a supplier, consumer, or both positions, and as well as be able to chain them into coherent flows. 

Early days, though, so please bear with us until we get around the nuances. Once we have something to share with the community, it'd be great to have you try it out.

**Comment by olegz** [comment]
@PedroAlvarado just to confirm what @sabbyanandan stated this is indeed work in progress as we speak. We'll be sharing the details soon.
