### ISSUE TITLE
Unable to set binding properties using external property source 

### ISSUE THREAD

**Issue by bruto0** [spring-cloud/spring-cloud-stream#1374]
JNDI property source, to be specific.
Using Spring Cloud Stream 2.0.0

It's a very simple use case I'm trying to implement: a request/reply processor in a Spring Boot app deployed as a web app to an application server.
So I have
```
@EnableBinding(Processor.class)
@SpringBootApplication
public class RootConfig extends SpringBootServletInitializer {
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(RootConfig.class);
    }

    @StreamListener(Processor.INPUT)
    @SendTo(Processor.OUTPUT)
    public MyMessageType kafkaProcessor(MyMessageType requestMessage) {
        ...
    }
}
```

I want to set topic names for both request and response externally so I have defined JNDI string properties for that (correctly named `spring.cloud.stream.bindings.input/output.destination`), but they do not work as I get this when running the app (with Jetty via Gretty plugin):
```
[o.s.c.s.b.BindableProxyFactory] main Binding outputs for :interface org.springframework.cloud.stream.messaging.Processor 
[o.s.c.s.b.BindableProxyFactory] main Binding :interface org.springframework.cloud.stream.messaging.Processor:output 
[o.s.c.s.b.k.p.KafkaTopicProvisioner] main Using kafka topic for outbound: output 
[o.s.c.s.b.BindableProxyFactory] main Binding inputs for :interface org.springframework.cloud.stream.messaging.Processor 
[o.s.c.s.b.BindableProxyFactory] main Binding :interface org.springframework.cloud.stream.messaging.Processor:input 
[o.s.c.s.b.k.KafkaMessageChannelBinder] main Listened partitions: Partition(topic = input, partition = 0, leader = 0, replicas = [0], isr = [0], offlineReplicas = []) 
```
Started debugging the application and found out that ConfigurationPropertiesBindingPostProcessor triggers before BindingServiceConfiguration.bindingService so BindingServiceProperties.bindings is empty at the time the former looks for properties to override and can't find `bindings.input/bindings.output`

Is there something I am doing wrong or is this an actual issue?

**Comment by olegz** [comment]
I was able to reproduce it, so looking into it

**Comment by olegz** [comment]
@bruto0 I just had a chance to dig into that and it doesn't appear to be a bug and is an expected behavior when it comes to custom sources. (see https://github.com/spring-projects/spring-boot/issues/3511). 
That said, I do have a question. . . From your explanation above I can't determine how your property source is identified in the actual app? Could you please clarify?

**Comment by bruto0** [comment]
I forgot, Oleg :)
never even committed this experiment to any repo, switched to Spring Kafka Integration when it didn't work
