### ISSUE TITLE
Clarify a couple of concepts

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-stream#1375]
As a relative newcomer to Spring Cloud Stream, I found a couple of things that took a while to make sense to me.

1) Assumed that `@SendTo` would be the polar opposite of `@StreamListener`.

Putting up a sample Stream app where a user types in a message, a `Source` grabs that message and sends it to a `Sink`.
In the [Stream refdoc](https://docs.spring.io/spring-cloud-stream/docs/Fishtown.BUILD-SNAPSHOT/reference/htmlsingle/#_spring_cloud_stream_core), I can find a lot of information about a `Sink`, but almost none about `Sources` or `Producers`.
So, I intuitively assumed for the `Source` part of things, I just needed a method that returned the object I wanted (`UserMessage`) annotated with `@SendTo`, where `@SendTo` would just take care of sending my object encapsulated in a Spring `Message` to the desired channel, similarly to Spring Integration's `@Publisher`.
Turned out that apparently, `@SendTo` only works in conjunction with `@StreamListener`.
I needed to send a message in an apparently lower level way, e.g., `this.source.output().send(new GenericMessage<>(userMessage));`

2) Using `@EnableBinding(Source.class)` or `@EnableBinding(Sink.class)` with `@EnableBinding(Processor.class)` fails in mysterious ways.

I thought a nice use case would be to have a `Source` sending data to a `Producer`, which would process the message and send it to a `Sink`.

This would fail with an error message like:

> [ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.0.1.RELEASE:run (default-cli) on project spring-cloud-gcp-pubsub-binder-sample: An exception occurred while running. null: InvocationTargetException: Invalid bean definition with name 'input' defined in org.springframework.cloud.stream.messaging.Sink: bean definition with this name already exists - Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.stream.messaging.Processor; factoryMethodName=input; initMethodName=null; destroyMethodName=null -> [Help 1]

After a little digging, I found out that by using them in conjunction, Stream is trying to create a channel called `input` or `output` multiple times, and it fails because of that.
This effectively means that `Source`, `Sink` and `Processor` can only be bound once, and `Processor` can't be bound at the same time as `Source` or `Sink`.
Maybe this should be called out in the reference doc somewhere, and people should be encouraged to build their own interfaces with the desired flows.

**Comment by sobychacko** [comment]
Hi @joaoandremartins 
1. You can either autowire the message channel and then call send on that directly or can use an `InboundChannelAdapter`. Here is an example: https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/sink-samples/jdbc-sink/src/main/java/demo/SampleJdbcSink.java#L105
2. Yes, if you mix processor and source/sink in the same context, you will get that behavior. The best way to avoid that, as you alluded to, is to create a separate binding interface for the processor.

**Comment by joaoandremartins** [comment]
@sobychacko feel free to close the issue.
I just intended to let you know about some friction I had when I started to use Spring Cloud Stream.
Perhaps some of these could be addressed on a more comprehensive reference document.

**Comment by sabbyanandan** [comment]
Hi, @joaoandremartins. Thanks for the update. Though we anticipate the source, processor, and sink contracts linearly map to Spring Cloud Data Flow primitives, from the (Spring Cloud Stream) framework perspective, it is open and composable. And you have a valid point; someone else could bump into a similar situation. Given the context and the recent experience, it'd be great if you could contribute a doc PR adding a note about it. The docs are in the same repo as code - see [here](https://github.com/spring-cloud/spring-cloud-stream/tree/master/spring-cloud-stream-core-docs/src/main/asciidoc).

**Comment by olegz** [comment]
Given that we've deprecated and removing reactive module as well as the need for `@EnableBinding` there is nothing to clarify here other then use reactive support natively provided by spring-cloud-function
