### ISSUE TITLE
Support for multiple binder implementations in the same app

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#138]
As a user, I'd like to consume messages from one middleware type and produce them in another (for instance).

**Comment by dsyer** [comment]
Which issue is it a duplicate of @sabbyanandan ?

**Comment by mbogoevici** [comment]
@dsyer 

I believe @sabbyanandan was referring to https://jira.spring.io/browse/XD-3563 https://jira.spring.io/browse/XD-3564 and https://jira.spring.io/browse/XD-3565

**Comment by mbogoevici** [comment]
Also https://github.com/spring-cloud/spring-cloud-stream/issues/140

**Comment by mbogoevici** [comment]
But I think that is a mistake, as #140 says something different.
