### ISSUE TITLE
Add (javax.)Validation Support for Stream Listener

### ISSUE THREAD

**Issue by dharrigan** [spring-cloud/spring-cloud-stream#1382]
Hi,

Just like Spring MVC, it would be great if StreamListener annotated methods could be additionally annotated with a `@Valid` annotation for the method parameter, then the converted message type could be validated using standard `javax.validation` (and spring validation) processes before the body of the method is invoked (i.e., in the example below, before fooRepository is called).

Something akin to this:

```
data class Foo(

   @field:NotBlank
   @field:Length(min = 1, max = 10)
   val name

)
```

```
@StreamListener(INPUT)
fun createNewFooInDatabase(@Valid foo: Foo) = fooRepository.create(foo)
```

A message that fails validation would be put unto any configured Error channel for alerting or handling by other business processes.

-=david=-

**Comment by olegz** [comment]
David

I am not sure what's required from us? I mean don't you just need to implement and register a validator for your object and register it with DataBinder?

**Comment by nhomble** [comment]
I'm just getting familiar with the codebase so sorry if the analysis is wrong. I think I see your point, @olegz, about 
> just need to implement and register a validator 

Since the ```PayloadArgumentResolver``` does take an optional validator to validate the incoming payload if it is annotated for validation. But I think the issue is that ```BindingServiceConfiguration::messageHandlerMethodFactory``` does not take a validator in its bean definition so it is never set on factory. If we set that in the factory, then annotating ```@Valid``` on the ```@Payload``` parameter should work like @dharrigan is expecting. Thoughts?

**Comment by dharrigan** [comment]
I think that would definitely help. Having the (optional) ability to validate a payload received by a StreamListener (which by design is meant to deserialise back into an object) would be mighty helpful!

**Comment by dharrigan** [comment]
Hi,

I've got a PR cooking that adds a Validator to the unreleased version of Spring Cloud Stream and it appears to work. I'll probably need a bit of assistance in answering a few questions, but in general the approach seems to be okay.

-=david=-

**Comment by olegz** [comment]
The best way is to submit a PR in whatever form it is and we'll work with you. The main thing is to include some level of testing.

**Comment by dharrigan** [comment]
Hi Oleg,

I've pushed up a branch (GH-1382) on my repo with the change. It's quite simple - however, I'm not too sure how to test it, also:

The class where the change is, BinderFactoryConfiguration is marked as deprecated. What to do?

If there is no validator found (i.e., if a JSR-303 implemenation is not found on the classpath), I'm not quite sure if a "null" for validator will be passed in.

Would you be able to offer some assistance on how to test and offer some guidance on the other points?

Thank you.

-=david=-

**Comment by dharrigan** [comment]
Here is a little (incomplete) example that shows a possible usage of the change:

```
private val LOGGER = KotlinLogging.logger { }

@Configuration
@EnableBinding(KafkaBindings::class)
class StreamConfig {

    @StreamListener(CONTRACT_CREATE)
    fun contractCreate(@Valid contractCreate: ContractCreate) {
        LOGGER.info { "Received [$contractCreate]." }
    }

    @Bean
    fun errorFlow(): StandardIntegrationFlow = IntegrationFlows.from("errorChannel")
        .routeByException {
            it.subFlowMapping(MethodArgumentNotValidException::class.java) { subFlow ->
                subFlow.handle { messageHandler ->
                    (messageHandler.payload as? MethodArgumentNotValidException)?.let { manve ->
                        manve.bindingResult?.fieldErrors?.forEach { fieldError ->
                            LOGGER.error { "[${fieldError.objectName}.${fieldError.field}] rejected [${fieldError.rejectedValue}] because [${fieldError.defaultMessage}]." }
                        }
                    }
                }
            }
        }.get()

}

data class ContractCreate(

    val id: String,

    @field:Length(min = 1, max = 5)    
    val foo: String,

    @field:Length(min = 4, max = 3)
    val bar: String

)
```

If `foo` or `bar` fail validation, then the subFlow will fire. Inside that subFlow could be specific business logic to fix the data up, or route onwards to another channel for processing elsewhere (or error logging/reporting/metrics).

**Comment by dharrigan** [comment]
Hi,

I've pushed up a new commit that includes two tests - a test for valid validation and a test for invalid validation. I hope that helps to progress this issue :-)

-=david=-
