### ISSUE TITLE
Queue length and overflow policy

### ISSUE THREAD

**Issue by ssudhaiyer** [spring-cloud/spring-cloud-stream#1383]
I'm using rabbitMq with spring-cloud. I have a requirement to process only the last message put in the queue. I would like to programmatically set queue length (max-length) to 1 and over flow policy to drop-head to achieve this. 

I'm opening this issue as suggested by Gary. Currently only the max-length is exposed on the binding and not overflow policy.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-rabbit#155
