### ISSUE TITLE
Dynamically instantiating child classes whose parent have @StreamListener

### ISSUE THREAD

**Issue by filpano** [spring-cloud/spring-cloud-stream#1396]
Hello! We are using Spring Cloud Stream as the underlying implementation for event messaging in our microservice-based architecture. We wanted to go a step further and provide an abstraction layer between our services and the Spring Cloud Stream library to allow for dynamic channel subscriptions without too much boilerplate configuration code in the services themselves.

The original idea was as follows:

The `messaging-library` provides a `BaseHandler` abstract class which all individual services must implement. All handlers of a specific service would like to the same input channel, though only the one corresponding to the type of the event to handle would be called. This looks as follows:

    public abstract class BaseEventHandler<T extends Event> {
        @StreamListener
        public abstract void handle(T event);
    }

Each service offers its own `events` package, which contains `N` EventHandlers. There are plain POJOs which must be instantiated programmatically. This would look as follows:

    public class ServiceEventHandler extends BaseEventHandler<ImportantServiceEvent> {
    
        @Override
        public void handle(ImportantServiceEvent event) {
            // todo stuff
        }
    }

Note that these are simple classes and not Spring beans at this point, with `ImportantServiceEvent` implementing `Event`. 

Our `messaging-library` is scanned on start-up as early as possible, and performs handler initialization. To do this, the following steps are done:

- We scan all available packages in the classpath which provide some sort of event handling and retrieve all subclasses of `BaseEventHandler`.
- We retrieve the `@StreamListener` annotation in the hierarchy of the subclass, and change its value to the corresponding input channel for this service.
- Since our handlers might need to speak to some other application components (repositories etc.), we use `DefaultListableBeanFactory` to instantiate our handlers as singleton, as follows:

        val bean = beanFactory.createBean(eventHandlerClass, AutowireCapableBeanFactory.AUTOWIRE_BY_TYPE, true);
        beanFactory.registerSingleton(eventHandlerClass.getSimpleName(), bean);

After this, we ran into several issues.

The Spring Cloud Stream `@StreamListener` annotation cannot be inherited as it is a method annotation.  Despite this, some mechanism seems to be able to find it on the parent (as the `StreamListenerAnnotationBeanPostProcessor` is registered) and attempts to perform post-processing upon the `ServiceEventHandler` being initialized. Our assumption is that the Spring Cloud Stream uses something like `AnnotationElementUtils.findAllMergedAnnotations()`.

As a result of this, we thought that we *might* be able to alter the annotation value of the base class prior to each instantiation of a child class. Due to this, we thought that although our `BaseEventHandler` would simply get a new value which would then stay constant at the end of this initialization phase, the child classes would be instantiated with the correct channel name *at the time of instantiation*, since we do not expect to rebind. However, this is not the case and the value of the `@StreamListener` annotation that is used is always the one on the base.

The question is then: is what we want possible with Spring Cloud Stream? Or is it rather a plain Java problem that we have here (does not seem to be the case)? Did the Spring Cloud Stream team foresee a  use case like this, and are we simply doing it completely wrong? 

This question was also posted on [StackOverflow](https://stackoverflow.com/questions/50970269/modifying-annotation-value-in-superclass-and-dynamically-instantiating-child-cla) in case it might help garner a bit more attention.

**Comment by garyrussell** [comment]
Since the same people monitor SO and GitHub issues, it's rather pointless to post in both places.

You should be able to subclass the BPP; it specifically has this extension point:

```java
	/**
	 * Extension point, allowing subclasses to customize the {@link StreamListener}
	 * annotation detected by the postprocessor.
	 *
	 * @param originalAnnotation the original annotation
	 * @param annotatedMethod the method on which the annotation has been found
	 * @return the postprocessed {@link StreamListener} annotation
	 */
	protected StreamListener postProcessAnnotation(StreamListener originalAnnotation, Method annotatedMethod) {
		return originalAnnotation;
	}
```

Then override the bean definition with yours

```java
	@Bean(name = STREAM_LISTENER_ANNOTATION_BEAN_POST_PROCESSOR_NAME)
	public static StreamListenerAnnotationBeanPostProcessor streamListenerAnnotationBeanPostProcessor() {
		return new StreamListenerAnnotationBeanPostProcessor();
	}
```

**Comment by olegz** [comment]
I am still struggling to understand if what you're doing is actually adding a value. Let me see if I understand it correctly.
1. You create a very generic handler definition and annotate it with StreamListener. 
2. Then you have some custom code  to perform some type of scanning and then post processing to bootstrap and bind the actual handler.

If so, you are partially re-implementing what spring-cloud-stream already does. If I am correct, why do you believe there is an added value in this approach? Wouldn't it be simpler to have a library of handlers as plain POJOs and then bootstrap them as beans in the actual app? The end result is the same, but without any of the custom code. Also, keep in mind that `registerSingleton` doesn't mean your bean is part of AC lifecycle so there are things to think about there as well, but that is just a side note. . .

Don't get me wrong, I may be missing something from your explanation but that is how I understand it now, so please clarify. Also, we're always looking for ways to improve user experience so (given the size of your effort) I am equally interested seeing if it is something we may be missing from the framework itself.

**Comment by olegz** [comment]
I am closing it for now as it seemed to go stale. Please reopen it if you feel there are things to do/discuss.
