### ISSUE TITLE
PartitionKeyExtractorStrategy is not called for a dynamic message channel

### ISSUE THREAD

**Issue by YossiShasha** [spring-cloud/spring-cloud-stream#1397]
While trying to send a message to a dynamic message channel the PartitionKeyExtractorStrategy Bean is not called in order to determine the partition that this message should be sent to.

The relevant code snippet:

    @Value("${messaging.dynamic-destinations.partitionCount}")
    private int partitionCount;

    @Autowired
    private BinderAwareChannelResolver binderAwareChannelResolver;

    @RequestMapping(value = "/send_to_topic/{topic_name}", method = RequestMethod.POST)
    @ResponseStatus(HttpStatus.OK)
    public void sendToTopic(@RequestBody String payload, @PathVariable("topic_name") String topicName,
                            @RequestHeader(HttpHeaders.CONTENT_TYPE) Object contentType) {
        binderAwareChannelResolver.resolveDestination(topicName).send(MessageBuilder.withPayload(payload)
                .copyHeaders(Collections.singletonMap(MessageHeaders.CONTENT_TYPE, contentType)).build());
    }

A possible pointer (I may be wrong) : It seems that the `MessageConverterConfigurer` is not registering a `PartitioningInterceptor` to this message channel and the the reason for this is that the `ProducerProperties.isPartitioned()` returns false.

**Comment by olegz** [comment]
Have you configured `spring.cloud.stream.bindings.output.producer.partitionCount` property?

**Comment by YossiShasha** [comment]
No I haven't. But adding this property didn't help

**Comment by olegz** [comment]
Actually part of the issue is that `output` in the property name corresponds to the actual destination name. In your case the destination name is dynamic and I am afraid we are not currently supporting this. 
We will try to address it as an enhancement for 2.1

**Comment by olegz** [comment]
Also, I presume you are using Kafka. If so please see this response from @garyrussell on SO. https://stackoverflow.com/questions/50947699/spring-cloud-stream-dynamic-destination-partitioncount-property
