### ISSUE TITLE
Remove error.destination property altogether

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#1398]
Avoid error.destination property and rely on DLQ mechanism provided by the binders. See this isse: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/395

**Comment by reddy-s** [comment]
Hi, Has there been any progress on this?

**Comment by olegz** [comment]
@reddy-s I am not sure what you are asking. Yes, progress has been made and the issue was resolved on June 27, 2018.
If you still believe there is an issue please raise a new one. There is no point on commenting on resolved issues.
