### ISSUE TITLE
Add @Qualifier to AbstractBinder's RetryTemplate

### ISSUE THREAD

**Issue by jmax01** [spring-cloud/spring-cloud-stream#1405]
Our DLQ ITs were failing mysteriously until we discovered that our Kafka DLQ topics were only being written to _after_ our `RetryTemplate`-executed assertion logic had timed out.

Removing our `RetryTemplate` from the context allowed the tests to [pass](https://gitter.im/spring-cloud/spring-cloud-stream?at=5b365ba4b086c90e8d0266c1).

Picking up an arbitrary `RetryTemplate` as the default for Bindings seems risky.

Since no mutator is available the current workaround is to subclass [AbstractBinder](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractBinder.java) implementations and override `buildRetryTemplate`.

The culprits:

```java

      @Autowired(required=false) // this would need to be refactored into constructor in the future
       private RetryTemplate retryTemplate;

	/**
	 * Create and configure a default retry template unless one
	 * has already been provided via @Bean by an application.
	 *
	 * @param properties The properties.
	 * @return The retry template
	 */
	protected RetryTemplate buildRetryTemplate(ConsumerProperties properties) {
		RetryTemplate rt = this.retryTemplate;
		if (rt == null) {
			rt = new RetryTemplate();
			SimpleRetryPolicy retryPolicy = new SimpleRetryPolicy();
			retryPolicy.setMaxAttempts(properties.getMaxAttempts());
			ExponentialBackOffPolicy backOffPolicy = new ExponentialBackOffPolicy();
			backOffPolicy.setInitialInterval(properties.getBackOffInitialInterval());
			backOffPolicy.setMultiplier(properties.getBackOffMultiplier());
			backOffPolicy.setMaxInterval(properties.getBackOffMaxInterval());
			rt.setRetryPolicy(retryPolicy);
			rt.setBackOffPolicy(backOffPolicy);
		}
		return rt;
}
```

**Comment by garyrussell** [comment]
I concur that there must be some "opt-out" mechanism for auto-wiring any `RetryTemplate` that happens to be in the application context; `RetryTemplate` is ubiquitous and there can easily be an instance in the context meant for some other purpose.

Perhaps a marker interface could be used, or a new property to opt-out of autowiring.

**Comment by olegz** [comment]
Wait, for 2.0 we specifically allowed `RetryTemplate` to be configured as a bean and that would override the one pre-configured by the framework, so unless I am missing something i don't think I agree with the "arbitrary" remark.
Yes, I do agree that we can/should further qualify it to address Gary's concern, but that is a separate subject, so I want to make sure we're talking about the same thing.

**Comment by jmax01** [comment]
> It also seems to me that specific binding properties should take precedence over this autowiring.
This was my feeling also.

**Comment by olegz** [comment]
So, @jmax01 do you mind changing the title of this issue or I can do that? We can certainly address it rather quickly with regard to qualifier.

**Comment by jmax01** [comment]
Is changing the title to "Add `@Qualifier` to `AbstractBinder's` `RetryTemplate`" acceptable?
