### ISSUE TITLE
MessageChannel should specify whether it is an inbound or outbound channel

### ISSUE THREAD

**Issue by ngbalk** [spring-cloud/spring-cloud-stream#1425]
Copying from:
https://github.com/spring-projects/spring-integration/issues/2525

I've noticed that when I'm using Spring Cloud Streams (take the Sink.class and Source.class for example), both MessageChannels "output" and "input" are created as DirectChannels.

```java
public interface Sink {

	String INPUT = "input";

	@Input(Sink.INPUT)
	SubscribableChannel input();

}
```
```java
public interface Source {

	String OUTPUT = "output";

	@Output(Source.OUTPUT)
	MessageChannel output();

}
```

I actually have no way of knowing whether this DirectChannel is an output or an input (besides looking at the bean name, but I wouldn't want to rely on that).

It would be helpful for me, especially when using a `@GlobalChannelInterceptor`, to know whether a MessageChannel is an input or output (i.e. annotated with `@Input` or `@Output`).  That way, in a `ChannelInterceptor.preSend()` I could do some checking of whether this is an inbound message or an outbound message and apply logic accordingly.

Curious to hear what people think / maybe I'm missing something obvious.

NOTE: I raised this on DirectChannel because I see that it applies to both inbound and outbound channels, and other channels are more specific to either inbound or outbound.  However perhaps this makes sense in another class too...

Thanks
Nick

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-integration/issues/2525#issuecomment-408216396

**Comment by olegz** [comment]
You can now test if the channel is `DirectWithAttributesChannel` and if it is, then you can look at the attributes as such:
```
DirectWithAttributesChannel inputChannel = (DirectWithAttributesChannel) testSink.input();
DirectWithAttributesChannel outputChannel = (DirectWithAttributesChannel) testSource.output();
assertThat(inputChannel.getAttribute("type")).isEqualTo(Sink.INPUT);
assertThat(outputChannel.getAttribute("type")).isEqualTo(Source.OUTPUT);
```

**Comment by ngbalk** [comment]
This is amazing!

**Comment by santoshdahal12** [comment]
In the newer version,  Sink interface is removed and therefore we cannot use Sink.INPUT.  Would be nice if there was a constant exposed to determine whether channel is of input or output type. 

I see that "input" string is hardcoded here https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/SubscribableChannelBindingTargetFactory.java#L73

Any thoughts on exposing this as a constant so that we can rely on framework itself rather than creating a new constant
