### ISSUE TITLE
Support Spring Boot 2.1

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-stream#1426]
Spring Boot 2.1.0.M1 is based on Spring Framework 5.1.0.RC1 which supports Java 11. To use the long-term Java 11 it would be nice if Spring Cloud Stream would be based on Spring Boot 2.1.

**Comment by sobychacko** [comment]
Spring Boot 2.1.0 is not going to GA until later this year. RC1 is scheduled for 9/20/18 (https://github.com/spring-projects/spring-boot/milestones). Spring Cloud Stream 2.1.0 will be GA'ed in September most likely and therefore we can't base that on Boot 2.1. I am afraid we still need to baseline `ScSt` on Boot 2.0.x.

**Comment by artembilan** [comment]
More over there is need Spring Cloud foundation based on Spring Boot 2.1...

**Comment by olegz** [comment]
@juergenzimmermann keep in mind you can always override the actual dependency and still use the boot version that you wish.

**Comment by garyrussell** [comment]
That is unlikely to work; Boot 2.1 needs spring-kafka 2.2 and spring-rabbit 2.1 which will probably not work with SCSt 2.1.

As @artembilan said, there needs to be cloud release train for Boot 2.1 compatibility.

**Comment by juergenzimmermann** [comment]
Another compatibility problem is Project Reactor.

- Spring Boot 2.1 requires the _Californium_ release train of Project Reactor, and Spring Boot 2.0 requires _Bismuth_.
- Californium references `io.projectreactor.netty:reactor-netty`, and Bismuth references `io.projectreactor.ipc:reactor-netty`.

**Comment by spencergibb** [comment]
Spring Cloud Core (Bus, Config, Netflix, etc...) will need a boot 2.1 compatible release of spring-cloud-stream. We are hoping to have an M1 by Spring One.

**Comment by spencergibb** [comment]
> keep in mind you can always override the actual dependency and still use the boot version that you wish.

You can not as there are incompatibilities with boot 2.1.

**Comment by sobychacko** [comment]
@juergenzimmermann We are going to upgrade ScSt 2.1 to use Spring Boot 2.1.0.

**Comment by spencergibb** [comment]
Should I open a separate issue for something like
```
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'integrationArgumentResolverMessageConverter' defined in class path resource [org/springframework/cloud/stream/config/ContentTypeConfiguration.class]: @Bean definition illegally overridden by existing bean definition: Generic bean: class [org.springframework.integration.support.converter.ConfigurableCompositeMessageConverter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null
```
