### ISSUE TITLE
inconsistency in the compatibility matrix for kafka

### ISSUE THREAD

**Issue by sgandon** [spring-cloud/spring-cloud-stream#1427]
the https://spring.io/projects/spring-kafka states that for the *Spring for Apache Kafka Version*
1.3.x, the kafka clients compatible are 0.11.0.x, *1.0.x* .
But in this repo documentation : https://github.com/spring-cloud/spring-cloud-stream/wiki/Kafka-Client-Compatibility
the compatible clients are 0.11.0.x, 0.10.2.x and there is no 1.0.x version mentionned.
Which one is the truth please and can you make it consistent ?

**Comment by garyrussell** [comment]
The matrix on the Spring for Apache Kafka site is the correct matrix for Spring for Apache Kafka itself.

The matrix on the SCSt Wiki represents what has been tested there.

Since versions of SCSt before 2.0 use the scala jars for provisioning, and the scala jars have to match the kafka-clients, it may not work with newer versions.

I will try to find some time to test it; if you have already used that combination, and it works, we can update the Wiki.

Generally, it would be much better all around if you can upgrade to 2.0.x.

**Comment by sgandon** [comment]
Thanks for your quick answer, unfortunatly going to 2.0.x would force use to upgrade to Springboot 2.0 too and we have an incompatible library that prevent us to do so yet.
This is not very clear when you say " it may not work with newer versions.", cause since SCS depends on *spring-kafka* and spring-kafka says it compatible with 1.0.x could it be possible it does not work in spring cloud stream ?

**Comment by garyrussell** [comment]
The following works, as long as the topics are already provisioned; automatic provisioning of topics will need some changes to the binder configuration.

```xml
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Edgware.SR4</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
			<version>1.3.6.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-kafka</artifactId>
			<version>2.3.0.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka_2.11</artifactId>
			<version>1.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
```

**Comment by garyrussell** [comment]
You will not, however, be able to use spring-kafka-test's embedded kafka broker in this configuration.

**Comment by garyrussell** [comment]
I'll take a look at the 1.3.x kafka11 binder - it might be possible to get it to work with this combo - but it hasn't had any love for a while.

**Comment by garyrussell** [comment]
This is not at all trivial; the whole provisioning infrastructure has change. Can you explain why you need to use the 1.x clients? The [confluent matrix](https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix) explains that older clients can talk to newer brokers.

As I said above, if you don't care about auto-provisioning, it will work ok.

**Comment by sgandon** [comment]
We do not yet need to use the 1.x client as our usage of Kafka is pretty basic and the provisionning of the topics is not done by the applications.
I just wanted to clarifiy the documentation as I thought there was some inconsistancy.
This is much clearer now.

**Comment by garyrussell** [comment]
Thanks; I have added a note to the wiki.
