### ISSUE TITLE
Stream clients are required to set 'spring.main.allow-bean-definition-overriding=true'

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-stream#1429]
See PR #1428 

https://github.com/spring-cloud/spring-cloud-stream/issues/1426#issuecomment-411147908

**Comment by spencergibb** [comment]
See also https://github.com/spring-projects/spring-boot/issues/14014

**Comment by sobychacko** [comment]
@spencergibb Can you try again with the latest ScSt 2.1.0 snapshot. This issue is addressed where `ContentTypeConfiguration` is unable to re-define a bean that is already defined through Spring Integration.

**Comment by spencergibb** [comment]
Looks like 85b34be7336e3d320caf016aa1965d09940c18d4 fixed it

**Comment by artembilan** [comment]
I think we need to revise something in Spring Integration since it looks like the condition there `if (!registry.containsBeanDefinition(IntegrationContextUtils.ARGUMENT_RESOLVER_MESSAGE_CONVERTER_BEAN_NAME)) {` doesn't work and everything what we have in the `IntegrationRegistrar` is really registered too early. I believe we can move our infrastructure to a `BeanFactoryPostProcessor` implementation:
```
/**
* Modify the application context's internal bean factory after its standard
 * initialization. All bean definitions will have been loaded, but no beans
 * will have been instantiated yet. This allows for overriding or adding
 * properties even to eager-initializing beans.
 * @param beanFactory the bean factory used by the application context
 * @throws org.springframework.beans.BeansException in case of errors
 */
void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException
```

Key words here are `All bean definitions will have been loaded`.

Will prepare something soon...

**Comment by sobychacko** [comment]
@artembilan Please ping once you have that fix in SI. Until then, we can let this change be in core stream so that downstream projects can continue.

**Comment by artembilan** [comment]
I've raised JIRA on the matter https://jira.spring.io/browse/INT-4517, because it turned out that we need to revise our attitude for those auto-registered beans in case of parent-chilld configuration.
That's how the PR didn't appear yesterday in the evening 😄

**Comment by sobychacko** [comment]
@wilkinsona I think with the changes that @artembilan is making in Spring Integration we should be able to address this issue where we override a `MessageConverter` bean in Spring Cloud Stream. That is the only bean that we are overriding in the framework. There is another bean (`BinderTypeRegistry`), that we are overriding in unit tests for mocking purposes. We don't expect this bean to be overridden by end-user applications as that is a rare use case. Most of the time, they use one of the provided binders by the framework (Kafka, rabbit, kinesis etc.). If they indeed come up with a new binder implementation and provide their own registry bean, in that case, I am afraid they have to enable bean overriding. Does that make sense? or am I missing something?

**Comment by olegz** [comment]
To Andy's point if we marked BinderTypeRegistry 
 as `@ConditionalOnMissingBean(BinderTypeRegistry.class)` is *only* to support tests, it is simply wrong. There are other ways to achieve what we want in tests.

**Comment by olegz** [comment]
So, I've created https://github.com/spring-cloud/spring-cloud-stream/issues/1430. Basically that conditional is a bug and should have never been there.

**Comment by spencergibb** [comment]
Also found
```
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'binderFactory' defined in org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration; factoryMethodName=binderFactory; initMethodName=null; destroyMethodName=(inferred); defined in org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration] for bean 'binderFactory': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.stream.config.BinderFactoryConfiguration; factoryMethodName=binderFactory; initMethodName=null; destroyMethodName=(inferred); defined in org.springframework.cloud.stream.config.BinderFactoryConfiguration] bound.
```

**Comment by artembilan** [comment]
FYI, whoever is interested in: https://github.com/spring-projects/spring-integration/pull/2537
