### ISSUE TITLE
Remove ConditionalOnMissingBean from BinderTypeRegistry bean definition.

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1430]
As discussed [here](https://github.com/spring-cloud/spring-cloud-stream/issues/1429#issuecomment-411403792) the `Conditional` is only to support testing and there are absolutely no expectation for user to ever override `BinderTypeRegistry`.

**Comment by wilkinsona** [comment]
The javadoc for `BinderTypeRegistry` says the following:

> A `BinderTypeRegistry` bean is created automatically based on information found in the `META-INF/spring.binders` files provided by binder implementors. This can be overridden by registering a `BinderTypeRegistry` bean in the context.

It looks like either the javadoc is wrong and should be changed too, or that the `BinderTypeRegistry` bean is intended to back off so that the user can provide their own.

**Comment by olegz** [comment]
Yes, Javadoc should be changed.
