### ISSUE TITLE
Document new TestBinder and it's capabilities

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-stream#1431]
```
public interface PollingSink {
	String INPUT = "input";

	@Input(PollingSink.INPUT)
	PollableMessageSource input();
}
```

java.lang.ClassCastException: org.springframework.cloud.stream.test.binder.TestSupportBinder cannot be cast to org.springframework.cloud.stream.binder.PollableConsumerBinder
	at org.springframework.cloud.stream.binding.BindingService.doBindPollableConsumer(BindingService.java:173)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:113)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:234)

**Comment by ghilainm** [comment]
@dturanski I have exactly the same issue. I have introduced a pollable message source and I ended up with the same error as you. It is blocking for me as it influences as it makes all my tests fail.

**Comment by olegz** [comment]
At the moment we are not planning to add this feature to this test binder. 
We actually have a new test binder which does support pollable message source and you can see the example [here](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/test/SampleStreamApp.java). Also if you want o use it in your project [here are the important maven bits you will need](https://github.com/spring-cloud/spring-cloud-stream/pull/1241)

**Comment by ghilainm** [comment]
@olegz Is it already released? Is it referenced somewhere in the documentation? Because for the moment in the documentation only this artifact is referenced
` testImplementation("org.springframework.cloud:spring-cloud-stream-test-support")`

and by default this artifact instantiate a test binder which is not compatible with pollableMessageSource

**Comment by olegz** [comment]
Yes it is. It's been out since 2.0, we just didn't publicize/blog about it. 
Also, to use it and not deal with conflicts, remove `spring-cloud-stream-test-support` from your dependencies

**Comment by ghilainm** [comment]
@olegz Just for my understanding which isn't it the public solution if it supports more use case?

**Comment by olegz** [comment]
Not sure I understand the question, but it is intended for public consumption and we will fully document it. It just didn't happen yet

**Comment by VictorKrapivin** [comment]
> We actually have a new test binder which does support pollable message source and you can see the example [here](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/test/SampleStreamApp.java). Also if you want o use it in your project [here are the important maven bits you will need](https://github.com/spring-cloud/spring-cloud-stream/pull/1241)

Example mentioned above (SampleStreamApp) is not working for me. It writes 

```
Polled payload: polled data
Handling payload: Hello
```

But i believe should be  
```
Polled payload: Hello
Handling payload: Hello
```
??

**Comment by ghilainm** [comment]
@olegz and @VictorKrapivin  Do you have an example of project, not inside the spring sources, which shows how to instantiate this test binder? I am struggling with the Maven/Gradle dependencies that I should use and the configuration to set up to instantiate that test binder!

**Comment by VictorKrapivin** [comment]
@ghilainm I'm not sure this will be helpful, but here is https://gist.github.com/VictorKrapivin/83c7e41efedce14db98c28bfb37622c8 my pom.xml
Java code is the same as https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/test/SampleStreamApp.java

**Comment by cahlen** [comment]
+1 for requesting some documentation about this new test binder, especially with something like gradle.

**Comment by olegz** [comment]
I've changed this issue to 'document`, so we'll do before the release. Meanwhile, here is what you need to defined as your dependency to include it into your project 
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream</artifactId>
    <version>${project.version}</version>
    <type>test-jar</type>
    <scope>test</scope>
    <classifier>test-binder</classifier>
</dependency>
. . .
<plugins>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.0.2</version>
        <executions>
	    <execution>
		<configuration>
		    <includes>
			 <include>**/integration/*</include>
		    </includes>
		    <classifier>test-binder</classifier>
		</configuration>
                <goals>
                    <goal>test-jar</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
</plugins>
```
You can retrofit the above to Gradle i guess

**Comment by cahlen** [comment]
> > We actually have a new test binder which does support pollable message source and you can see the example [here](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/binder/test/SampleStreamApp.java). Also if you want o use it in your project [here are the important maven bits you will need](https://github.com/spring-cloud/spring-cloud-stream/pull/1241)
> 
> Example mentioned above (SampleStreamApp) is not working for me. It writes
> 
> ```
> Polled payload: polled data
> Handling payload: Hello
> ```
> But i believe should be
> 
> ```
> Polled payload: Hello
> Handling payload: Hello
> ```
> ??

@olegz I'm able to get the binder working now too.  I didn't notice the comments within the `TestChannelBinder` class.  

But I'm also having the same issue that @VictorKrapivin is running into -- whatever data I'm consuming with the `PollableMessageSource` always returns the string `polled data`.  Can you point me to a test using the new test-binder where this isn't the case?
