### ISSUE TITLE
Support Poller or PeriodicTrigger config in PollableMessageSource

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-stream#1433]
Currently the MessageHandler must provide this logic. It would be nice to be able to autowire a Poller or maybe a simple trigger.

**Comment by olegz** [comment]
@dturanski do you want to take a crack at it? Seems reasonable

**Comment by olegz** [comment]
Turning it into documentation issue as @garyrussell  [example from the old PR](https://github.com/spring-cloud/spring-cloud-stream/pull/1591#issuecomment-466418073) to use Scheduled task makes all the difference. We just need to document it
