### ISSUE TITLE
abour EnableBinding harverst

### ISSUE THREAD

**Issue by SkyvenXiong** [spring-cloud/spring-cloud-stream#1435]
EnableBinding  declared as Inherited ,but it get by  BindingBeansRegistrar  ,it is use AnnotatedElement.getDeclaredAnnotations. but this method ignores inherited annotations.

i   use the SubscribableChannel like

`
public interface Subscriber {
    String SUBSCRIBR = "subscriber";

    @Input(SUBSCRIBR)
    SubscribableChannel subscriber();
}

@EnableBinding(value = {Subscriber.class})
public class SinkReceiver {

    protected   Logger logger = LoggerFactory.getLogger(SinkReceiver.class);
}
//The above  code is in  my framework

//@EnableBinding(value = {Subscriber.class})
public class PersonHandler extends SinkReceiver {
    @StreamListener(value = Subscriber.SUBSCRIBR,condition = "headers['type']=='person'")
    public void handle(Person person) {
        logger.info("Received:"+person);
    }
}
//The above code is in my project
`

if i do not declare EnableBinding in PersonHandler , it not work well .

i think this is a design defect.

**Comment by olegz** [comment]
That is correct. The `@EnableBinding` is required as it will trigger the creation of the channels and supporting infrastructure.
Perhaps you can post a sample of your application somewhere in github so we can look
