### ISSUE TITLE
Errors when Kafka messages are waiting and SI DSL is used

### ISSUE THREAD

**Issue by jbrisbin** [spring-cloud/spring-cloud-stream#144]
If I set up an app that uses `@EnableBinding(Sink.class)` and inject that `Sink` into a `@Bean` method, then use `IntegrationFlows.from` to create a flow from the `.input()`, I immediately get error messages saying there are no subscribers. It seems that it's trying to deliver the messages from Kafka that are currently being published before all the appropriate consumers have been attached.

If I call `Sink.input().subscribe()` and pass my own `MessageHandler`, I don't see any errors. It seems like it's only when I use spring-cloud-stream in combination with the Java DSL that it creates problems.

**Comment by jbrisbin** [comment]
This is actually a little bigger scope, I think, and not confined to the Java DSL. If I create a method with the `@ServiceActivator` annotation on it, then I get a console full of error messages when I start my sink application and messages are waiting for me on a Kafka topic.

**Comment by garyrussell** [comment]
It sounds like the components are being started in the wrong order.

In Spring XD, we start modules right to left - so the channel in the "consumer" module has a subscriber bound to it.

We also set autoStartup to false on "producer" modules and start the module after it's bound to the bus.

It sounds like the kafka consumer is being started before your consumer is subscribed to the input() channel.

**Comment by jbrisbin** [comment]
If you look [here](https://github.com/jbrisbin/tfl-ingest) you can see the setup I'm using (which I think is about as bare-bones as it gets). The `kafka-source` app is a Boot app that pulls data from a REST API and sends messages to Kafka via the s-c-s `Source`. The `riak-sink` is the other half and pulls data from Kafka via s-c-s `Sink`. This is the app that shows the problem. If I change [this](https://github.com/jbrisbin/tfl-ingest/blob/master/riak-sink/src/main/groovy/com/basho/ingest/TrackerNetRiakSink.groovy#L29) to a `@ServiceActivator` I see the errors immediately on startup if the `kafka-source` app is running and has published messages.

**Comment by garyrussell** [comment]
Yeah - I just don't know enough (yet) about how s-c-s starts the bindings - @mbogoevici is the expert; we need to be sure your ServiceActivator is subscribed before the kafka adapter (in the binding) is started.

i.e. the sink has to be bound before the source.

**Comment by mbogoevici** [comment]
My initial impression was that the IntegrationFlows are created and subscribe to their channels after SmartLifecycles are started, which explains why we have this issue with IntegrationFlow beans, but not with @ServiceActivators for example. Could be wrong, cannot say for sure until reproducing. I'll try doing that on Friday if no one wans to pick this up before that.

**Comment by garyrussell** [comment]
I don't see a ServiceActivator in your project, but you could try setting the phase attribute to Integer.MIN_VALUE so it is started early. You can do the same using the dsl (by setting the phase on the GenericEndpointSpec).

**Comment by garyrussell** [comment]
@mbogoevici The flows just register beans the same way as annotations and XML so they should participate in the `SmartLifecycle` initialization, just like any bean.

**Comment by mbogoevici** [comment]
thanks @garyrussell I think I have a pretty good idea why this happens - bindings are created through a SmartLifecycle that starts early, so that sources don't have the same problem, but that is breaking sinks. So we need separate lifecycle phases for inputs and outputs. That is a fairly easy fix.

**Comment by garyrussell** [comment]
In XD, the module is fully started (all endpoints bound) before it's bound to the bus (in postProcessModule()).

I am assuming in s-c-s the "bus" adapter is in the same context as the sink so it needs to be started in a late phase (MAX_VALUE).

Similarly, with a source, the producer side must be bound before the source message producer (so it doesn't start too early) so the producer side of the binding should be started in an early phase (MIN_VALUE).

**Comment by mbogoevici** [comment]
Yes, that's what I meant. The current channel binding lifecyle bean needs to be broken in two and inputs and outputs need to be handled differently. I believe that XD had a different way if addressing this, not that it really matters right now :)

**Comment by mbogoevici** [comment]
Should be addressed here: https://github.com/spring-cloud/spring-cloud-stream/pull/148

**Comment by mbogoevici** [comment]
Closed as the PR is closed.
