### ISSUE TITLE
Remove ConditionalOnProperty in FunctionConfiguration

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-stream#1452]
`@ConditionalOnProperty("spring.cloud.stream.function.name")` requires scst app starter developers to: 

```
@Autowired(required=false)
IntegrationFlowFunctionSupport function support
...
if (support != null)
``` 

Since we don't know a priori if it's enabled or not.

**Comment by dturanski** [comment]
Reverted the commit since it caused numerous test failures

**Comment by olegz** [comment]
After discussing it with @dturanski this one is a bit more involved plus we're not yet fully convinced that it is necessary. Perhaps we can revisit it some other time
