### ISSUE TITLE
Question: How to do Unit Testing on Sources and Sinks?

### ISSUE THREAD

**Issue by theonlyguills** [spring-cloud/spring-cloud-stream#147]
What would be the current best practice for unit testing apps that rely on cloud stream rabbit? Is there an easy way to disable all the cloud stream autoconfig, rabbit autoconfig, etc and mock the Sources/Sinks?

Changing the dependencies in test or depending on a local Rabbit server for unit testing doesn't seem like the best idea.

**Comment by mbogoevici** [comment]
Hi @theonlyguills an example on how to unit test is here: https://github.com/spring-cloud/spring-cloud-stream-modules/tree/master/ftp-source

It is using SCS' test support binder: https://github.com/spring-cloud/spring-cloud-stream/tree/master/spring-cloud-stream-test-support

**Comment by theonlyguills** [comment]
Awesome thanks for a quick reply.
