### ISSUE TITLE
Support auto suggest for `spring.cloud.stream.default`

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-stream#1489]
[This section](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#binding-properties) of documentation says

> To avoid repetition, Spring Cloud Stream supports setting values for all channels, in the format of spring.cloud.stream.default.<property>=<value>.

>In what follows, we indicate where we have omitted the spring.cloud.stream.bindings.<channelName>. prefix and focus just on the property name, with the understanding that the prefix ise included at runtime.

But this information is not captured [here](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/resources/META-INF/additional-spring-configuration-metadata.json)

Because of this, the auto suggest will not show `default` as a child of `spring.cloud.stream` when editing `application.yml` & `application.properties`

Can you add appropriate entry [here](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/resources/META-INF/additional-spring-configuration-metadata.json) so that the suggestions match whats mentioned in the documentation

**Comment by olegz** [comment]
I am going to close this issue as this is not the functionality provided by Spring Cloud Stream and instead is related to general IDE tooling  and configuration plugin.
