### ISSUE TITLE
AbstractBinder ApplicationContext type assertion

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#1493]
Currently it asserts the context is an `AbstractApplicationContext` - change to `GenericApplicationContext` so we can use the new `registerBean()` methods without casting.

**Comment by Kent1** [comment]
I am trying to use Spring Cloud Stream on an existing application (Spring framework, not spring boot). I get the following error `Object of class [org.springframework.web.context.support.XmlWebApplicationContext] must be an instance of class org.springframework.context.support.GenericApplicationContext`

Obviously, i am not an expert in ApplicationContexts and i am doing experimental things here, but couldn't that be a problem for other people ?
