### ISSUE TITLE
Default binding properties are not respected

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-stream#1507]
[The documentation](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#binding-properties) specifies : 
> To avoid repetition, Spring Cloud Stream supports setting values for all channels, in the format of spring.cloud.stream.default.<property>=<value>.

It seems this is not true. I have a repro here : https://github.com/snussbaumer/repro-streams-primitive-default-properties

This is my application : 

```java
@SpringBootApplication
@EnableBinding(TestBus.class)
@RestController
public class ReproApplication {

    @Autowired
    private MessageChannel testOutput;

    @GetMapping("/test")
    public void test(@RequestParam("message") String message) {
        testOutput.send(MessageBuilder.withPayload(message).build());
    }

    @StreamListener(TestBus.TEST_INPUT)
    public synchronized void onTestTopicInput(String message) {
        System.out.println("******************");
        System.out.println("Received message : " + message);
        throw new RuntimeException("oooops");
    }

    public interface TestBus {

        String TEST_INPUT = "testInput";

        String TEST_OUTPUT = "testOutput";

        @Input(TEST_INPUT)
        MessageChannel testInput();

        @Output(TEST_OUTPUT)
        MessageChannel testOutput();
    }

    public static void main(String[] args) {
        SpringApplication.run(ReproApplication.class, args);
    }
}
```

and this is `application.properties`

```
server.port=8080
spring.cloud.stream.binder.brokers=kafka
spring.cloud.stream.binder.zkNodes=zookeeper
spring.cloud.stream.default.consumer.max-attempts=1
spring.cloud.stream.bindings.testInput.destination=test
spring.cloud.stream.bindings.testInput.destination.group=testConsumerGroup
spring.cloud.stream.bindings.testOutput.destination=test
```

please note the `spring.cloud.stream.default.consumer.max-attempts=1` : this should disable retries by default on all consumers, but when I do a `curl localhost:8080/test?message=hello` I see `Received message: hello` three times in the console, so the default value of `max-attemps = 3` is still active.

I can workaround the problem for now with the property `spring.cloud.stream.bindings.testInput.consumer.max-attempts=1` to disable retries, but I have to copy this for each consumer, and should not be necessary according to the documentation.

I suspect this comes from the behaviour of `MergeableProperties.merge`  that states : 
> If source property is null then override with the same from mergable.

`max-attempts` (and many other properties in `ConsumerProperties`) are primitive types, and thus can not be null, thus preventing this merge, no ?

`MergeableProperties.merge` is called from `EnvironmentEntryInitializingTreeMap.put` and putting breakpoints there confirms this hypothesis, but I may be missing a piece of the puzzle...

**Comment by snussbaumer** [comment]
LOL ! I'll check the open issues a bit more carefully next time !!

I confirm everything works  as expected with the latest snapshot.

Thanks !

**Comment by olegz** [comment]
No, you're good! What are the chances of that ever happening again? ;)
Anyway, thank you!
