### ISSUE TITLE
Metrics of spring.integration.send

### ISSUE THREAD

**Issue by ninja-inc** [spring-cloud/spring-cloud-stream#1509]
I developed a message consumer application with Spring Cloud Stream but I found metrics is not counted up as I expect.

(1) When it consumes a message and it is acknowledged, `spring.integration.send` is counted up 2 times (type: channel -> 1, type: handler -> 1).

(2) When it consumes a message and it throws `AmqpRejectAndDontRequeueException`, `spring.integration.send` is counted up 10 times (result: success -> 3, result: failure -> 7, my assumption is that success 3 corresponds to max attempt 3 but I don't know how failure is counted up 7 times).

But my expectation is that `spring.integration.receive` is counted up instead `spring.integration.send`  (I refered [Spring Integration metrics.adoc](https://github.com/spring-projects/spring-integration/blob/master/src/reference/asciidoc/metrics.adoc)) as my application is consuming messages, not publishing messages.

What I want to do is to distinguish failures of publishing a message and consuming a message strictly.

Is this correct behavior as you expect? If so, is there any way to distinguish metrics from publishing and consuming?
Or am I missing something important?

This is [sample application](https://github.com/ninja-inc/demo-stream-metrics) to produce this. (I tries to write test code to produce this automatically but I failed..)

**Comment by artembilan** [comment]
The `spring.integration.receive` metric is applied only for the `PollableChannel`. Since all the channels created by the Spring Cloud Stream are only `DirectChannel`, there is not going to be `spring.integration.receive`.
More over the `spring.integration.send` part really perform a `MessageHandler` directly. That's how in case of success the `spring.integration.send` is really equal to the `.tag("type", "handler")`.

Why you have so much `failure` and not really equal to `max attempt 3` need to be investigated.
Will take a look into your sample later.

Thank you!

**Comment by ninja-inc** [comment]
@artembilan 
Thank you for the information!

>Why you have so much failure and not really equal to max attempt 3 need to be investigated.

Now I am working on common monitoring and alerting things for my department and I want to know it only when publishing a message fails because logically consuming a message can fail but we don't expect publishing fails so I want to monitor only this failure but if we monitor `spring.integration.send`, it contains consuming failure too and it is counted up many times, mentioned in (2).
I know if we implement some custom metrics, we can monitor only it but I thought we can use some default ones.
(About `max attempt 3`, it does not matter much for me. I just thought the reason why failure is counted up 7 times is due to max attempt behavior.)

So now we don't have any methods to distinguish from publishing and consuming from default metrics?

**Comment by olegz** [comment]
@artembilan while related this seems to be an SI related discussion. Could you please see if you can move it to SI JIRA and close this.

**Comment by olegz** [comment]
@artembilan @ninja-inc given the above discussion and the fact that currently there is no direct metric interaction in spring-cloud-stream (only via SI), I am closing it assuming any further requests/discussion will move to [SI JIRA](https://jira.spring.io/projects/INT/issues).
