### ISSUE TITLE
Acknowledgement for Sending Message

### ISSUE THREAD

**Issue by VikasJindal84** [spring-cloud/spring-cloud-stream#151]
Hi,

Currently there is no way to find out if Kafka message is successfully delivered . I tried to use 
MessageChannel.send , it always returns true ,even if zookeeper and kakfa server is down.

So, my requirement is to have a way to get a confirmation about delivery of message to kafka server.

**Comment by mbogoevici** [comment]
Hi Vikas,

Thanks for reporting this. Noted. This needs to be an enhancement to Spring Integration Kafka, as well as properly handling this inside Spring Cloud Stream.

Cheers,
Marius

**Comment by artembilan** [comment]
Looks like this should be fixed together with the https://github.com/spring-projects/spring-integration-kafka/issues/62

**Comment by mbogoevici** [comment]
It would depend on it, but more to it than just that.

**Comment by VikasJindal84** [comment]
Hi,

Now spring-integration-kafka has support for ProducerListener : https://github.com/spring-projects/spring-integration-kafka/commit/325d0b294c825252f5313bd9696229d198b0d38e

Any plan for providing support for ProducerListener in spring-cloud-stream-binder-kafka ?

**Comment by mbogoevici** [comment]
This is currently addressed by https://github.com/spring-cloud/spring-cloud-stream/issues/316

**Comment by sabbyanandan** [comment]
This is already addressed by spring-cloud/spring-cloud-stream#253, so closing this issue.
