### ISSUE TITLE
Usenative encoding ingored in FunctionInvoker

### ISSUE THREAD

**Issue by kavukcutolga** [spring-cloud/spring-cloud-stream#1536]
Spring cloud stream function invoker by default using message converters after getting output from function.

org.springframework.cloud.stream.function.FunctionInvoker*:

    return input.concatMap(message -> {  
       return Flux.just(message)  
                .doOnNext(originalMessageRef::set)  
                .map(this::resolveArgument)  
                .transform(this.userFunction::apply)  
                .retryBackoff(consumerProperties.getMaxAttempts(),  
      Duration.ofMillis(consumerProperties.getBackOffInitialInterval()),  
      Duration.ofMillis(consumerProperties.getBackOffMaxInterval()))  
                .onErrorResume(e -> {  
                   onError(e, originalMessageRef.get());  
     return Mono.empty();  
      });  
    }).log().map(resultMessage -> toMessage(resultMessage, originalMessageRef.get())); //

```
	@SuppressWarnings("unchecked")
	private <T> Message<O> toMessage(T value, Message<I> originalMessage) {
		if (logger.isDebugEnabled()) {
			logger.debug("Converting result back to message using the original message: " + originalMessage);
		}
		Message<O> returnMessage = (Message<O>)
				(value instanceof Message
						? value
						: this.messageConverter.toMessage(value, originalMessage.getHeaders(), this.outputClass));
		if (returnMessage == null) {
			if (value.getClass().isAssignableFrom(this.outputClass)) {
				returnMessage = (Message<O>) MessageBuilder.withPayload(value).copyHeaders(originalMessage.getHeaders()).removeHeader(MessageHeaders.CONTENT_TYPE).build();
			}
		}
		Assert.notNull(returnMessage, "Failed to convert result value '" + value + "' to message.");
		return returnMessage;
	}

```
But when useNativeEncoding set to true seems like result should be returned directly ? Any ideas about this, do you think this should be patched ?

    output:  
      destination: events  
      producer:  
        useNativeEncoding: true

**Comment by olegz** [comment]
@kavukcutolga Thank you for your contribution. Will review

**Comment by kavukcutolga** [comment]
@olegz thanks I am working on test cases waiting for your feedback

**Comment by kavukcutolga** [comment]
@olegz just raised a complete PR https://github.com/spring-cloud/spring-cloud-stream/pull/1538.
