### ISSUE TITLE
Consumer and Producer properties are not propagated to function properties

### ISSUE THREAD

**Issue by kavukcutolga** [spring-cloud/spring-cloud-stream#1543]
**Spring Cloud Stream Function Support**

Supplier and Consumer the producer/consumer properties are propagated to the FunctionProperties during binding but for Functions they are not. Since for functions there is also a processor involved like below:

`@EnableBinding(Processor.class) public class App {
`

So in AbstractMessageChannelBinder we skip this due to a conditional check please see : 

[conditional_check](https://github.com/spring-cloud/spring-cloud-stream/blob/7e811a72c6e7d2ce2f551bb779875d191e852922/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L200)

Also I can provide a patch with some guidance about what to do

**Comment by olegz** [comment]
@kavukcutolga I believe it is fixed. I was researching its history and specifically why did we care about the `processor` only and traced it down to this commit a0b4617ac771109033d98664e2c1699157d2c1fe. 
I believe it was lingering from an unrelated effort (explained a bit in the commit message).

Thank you so much for spotting it and feel free to contribute as much as you want. Even if it's just tests to validate this or that.

Cheers

**Comment by kavukcutolga** [comment]
@olegz thanks for update, I need to validate it for my project, surely I can put some unit test as well
