### ISSUE TITLE
management.health.binders.enabled is not specified in spring-configuration-metadata.json

### ISSUE THREAD

**Issue by kaleev** [spring-cloud/spring-cloud-stream#1551]
management.health.binders.enabled property in not specified in spring-configuration-metadata.json.
Because of that it is not possible to get contextual help for it when working with application.properties/yaml in IDE.

**Comment by artembilan** [comment]
Such a property must be present in the `additional-spring-configuration-metadata.json` file: https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/htmlsingle/#configuration-metadata-additional-metadata
