### ISSUE TITLE
Problems adding specific configuration for a binder

### ISSUE THREAD

**Issue by jorgefr** [spring-cloud/spring-cloud-stream#1569]
Hi,

I found some issues when I wanted to use a specific environment configuration for one of the binders I'm using.

I'm using `spring-cloud-stream 2.0.0.RELEASE` (as a dependency from `spring-cloud-stream-binder-kinesis 1.0.0.RELEASE`) and `spring-boot 2.0.3.RELEASE`. 

 I need to use 2 kinesis streams: input and output. I need to define different credentials for each because they live in different AWS accounts. I finally could do it by defining `spring.main.sources`, but with some workarounds.

My configuration looks like this:

```
....
spring.cloud.stream:
   bindings:
     input:
       ...
     output:
       ...
       binder: myBinder
   binders:
      myBinder:
        type: kinesis
        defaultCandidate: false
        environment:
          spring:
            main.sources: my.config.KinesisOutputConfiguration
            cloud.bootstrap.enabled: false
....
```

The idea of using `spring.main.sources` was suggested by @artembilan in https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/74. 
I didn't know either that the `SpringApplication` could be customized through configuration like that, or that `spring-cloud-stream` was integrating that functionality.

Before starting describing the problem, my apologies if the issues don't have to do with this library specifically. While debugging to find what the issue was, I saw that many different libraries are involved, so `spring-cloud-stream` is my first guess.

### The first problem
The first problem I found is that the property `spring.main.sources` was being ignored in my case until I included the dependency `spring-cloud-commons`.

The short explanation is that this dependency contains an environment post processor called `HostInfoEnvironmentPostProcessor` that reorders the property sources of the environment.

The longer explanation, I had to debug a lot to find the reason:

When `SpringApplication#prepareEnvironment` tries to bind the properties to the Application class,
one of the invoked methods in the call stack is `org.springframework.boot.context.properties.source.ConfigurationPropertySources#get`. It searches for the first property source called `configurationProperties` and the binding will only pick the property sources defined in the list after that one.

The `spring.main.sources` property is available in the property source `commandLineArgs`, and in my case, it was in the list before `configurationProperties`, so it was being ignored. `HostInfoEnvironmentPostProcessor` moves the`configurationProperties` element to the beginning of the list and that causes `commandLineArgs` to be processed for binding the properties to `SpringApplication`

I'm not sure if this is the expected behaviour, but it was not obvious for me with the knowledge I have about  the framework and libraries of `Spring`, and after reading the docs of [spring-cloud-stream docs](https://github.com/spring-cloud/spring-cloud-stream/blob/master/docs/src/main/asciidoc/spring-cloud-stream.adoc)  and others.

### The second problem
The second problem I found is that when I added the dependency `spring-cloud-context` to the project. The beans defined in `KinesisOutputConfiguration` started to be instantiated twice. I solved it when I added `spring.cloud.bootstrap.enabled: false`. This was also not obvious for me and I'm not sure if I will have any problems by doing this.

### The third problem
The third problem was when I tried to use `@Profile` in the configuration class and activating the profile with `spring.main.additionalProfiles`. This was my first attempt before using `spring.main.sources` but I could never get it working.

It looks like with the current implementation of `SpringApplication`, the profile is added after the environment is prepared, so the environment doesn’t consider all the profiles.

### Conclusion
So don't know if I did some big mistakes. Otherwise some components might be missing in the library, or maybe some documentation about it.

I can prepare a small sample project to show the exact configuration that I had.

Thanks!

**Comment by olegz** [comment]
@jorgefr Thank you for detailed explanation. We will certainly look into that, although at the moment I do not see it as spring-cloud-stream issue. Probably more spring boot related.
And yes, _small sample project_ would be ideal as it would help us to triage the issue.

@artembilan if you have any additional feedback, feel free to jump in.

**Comment by jorgefr** [comment]
Hi @olegz. Thanks for the answer. I uploaded a small sample project to https://github.com/jorgefr/spring-cloud-kinesis-stream-sample. 
In the README, I added what you need to do to reproduce each case.
I hope I've described everything correctly and it works out of the box. Otherwise, please let me know

**Comment by artembilan** [comment]
While I'm looking into your sample, please, consider to use the latest Spring Cloud Stream and also `1.1.0.BUILD-SNAPSHOT` for Kinesis Binder. 
There is the fix in the master not available for the `1.0.0.RELEASE`: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/a2b730e48d220afcd585ae9cb1461022ae1daf33

**Comment by artembilan** [comment]
This is what I see so far. Spring Boot has the code like this:
```
private ConfigurableEnvironment prepareEnvironment(
			SpringApplicationRunListeners listeners,
			ApplicationArguments applicationArguments) {
		// Create and configure the environment
		ConfigurableEnvironment environment = getOrCreateEnvironment();
		configureEnvironment(environment, applicationArguments.getSourceArgs());
		listeners.environmentPrepared(environment);
		bindToSpringApplication(environment);
		if (this.webApplicationType == WebApplicationType.NONE) {
			environment = new EnvironmentConverter(getClassLoader())
					.convertToStandardEnvironmentIfNecessary(environment);
		}
		ConfigurationPropertySources.attach(environment);
		return environment;
}
```

We can get that `spring.main.sources` bound in the `bindToSpringApplication()` only of there is no `ConfigurationPropertySources.ATTACHED_PROPERTY_SOURCE_NAME` in the `environment` yet. Otherwise all the properties biding in based only in that wrapper.

By default we have this in the `BinderProperties`:
```
/**
 * Whether the configuration will inherit the environment of the application itself. Default: true
 */
private boolean inheritEnvironment = true;
```

So, when we prepare an `environment` for the target binder we inherit everything else from the parent which already has the mentioned above `ConfigurationPropertySources.ATTACHED_PROPERTY_SOURCE_NAME`.
That's how we don't our `spring.main.sources` processed from the additional `commandLineArgs` properties source.

Please, consider to use `spring.binders.myBinder.inheritEnvironment = false` property over there. 

That should be an answer for two first your concerns.

Will investigate a profile issue tomorrow...

**Comment by artembilan** [comment]
To activate profile on that your additional `@Configuration` you need to use this property `spring.profiles.active=output`. But `inheritEnvironment` must remain `false`.

So, summarize our discussion you need this YAML:
```
...
    binders:
      myBinder:
        type: kinesis
        defaultCandidate: false
        environment:
          spring:
            main:
              sources: com.samples.config.KinesisOutputConfiguration
            profiles:
              active: output
        inheritEnvironment: false
``` 

Remove your `@ToExcludeFromAppContext` customization. Uncomment `@Profile("output")`  on the `KinesisOutputConfiguration` class.
And remove `@ComponentScan(excludeFilters` from the `SpringCloudKinesisStreamApplication`.

**Comment by artembilan** [comment]
From the Framework perspective it looks like would be better to remove a `ConfigurationPropertySources.ATTACHED_PROPERTY_SOURCE_NAME` from the parent `Environment` before merging when we have an `inheritEnvironment = true` (default).
This way Spring Boot will prepare a new one for this binder's application context and will consume our additional properties we would like to have in that binder configuration.

**Comment by olegz** [comment]
@artembilan  I agree, but may not have a full grasp, so a PR would probably shed more light.

**Comment by artembilan** [comment]
You should use `Greenwich` fopr Spring Cloud. The place we have a fix is not Spring Framework 5.0.x.
So, you have to upgrade the whole stack.

I'm not sure that we need to worry about `spring-cloud-context` over there at all.

I've tested your sample with the `spring.profiles.active`, so that was my feedback to you.

With the mentioned fix you don't need to worry about `inheritEnvironment = false` any more. It is properly propagated.

**Comment by jorgefr** [comment]
Thanks for your answer again.
I just tried with `Greenwich` and I see some changes in the behaviour:
- `spring.profiles.active` doesn't still work for me. 
- `spring.main.sources` now works only when `inheritEnvironment = false` and when I give `KinesisOutputConfiguration` more priority than `org.springframework.cloud.stream.binder.kinesis.config.KinesisBinderConfiguration`.

Regarding `spring.profiles.active` with my current version, it still doesn't work for me for some reason. I have the following config:

```   
    binders:
      myBinder:
        type: kinesis
        defaultCandidate: false
        inheritEnvironment: false
        environment:
          spring:
            profiles.active: output
```
Commented the exclusion annotation and un-commented the `@Profile` and it is not working. I'm checking with a breakpoint and also that the log line is not printed.


The issue with `spring-cloud-context` in this case it is not that important because it is clearer what I need to do by reading the error (at least for me). But it is still weird that it changes the behaviour of the application.

**Comment by artembilan** [comment]
Would you mind to reflect those changes in your sample and share with us?

**Comment by jorgefr** [comment]
Will do. Let's see if today I have some time already

**Comment by jorgefr** [comment]
Hi @artembilan, sorry for the delay.

I did the different tests in different branches:

- Branch `finchley-spring-main-sources-no-inherit-environment-works`: It is the original master + `inheritEnvironment = false`. It works as you said.
- Branch `greenwich-spring-main-sources`: It is the `finchley-spring-main-sources-no-inherit-environment-works` but using `Greenwich` instead of `Finchley`. It works only when `inheritEnvironment = false` and when I give `KinesisOutputConfiguration` more priority than `org.springframework.cloud.stream.binder.kinesis.config.KinesisBinderConfiguration`.


- Branch `finchley-active-profiles`: It is the original master + `inheritEnvironment = false` + `spring.profiles.active` instead of `spring.main.sources`. It still fails to pick up the class. By disabling environment inheritance, the profile is this time correctly set to active before calling `listeners.environmentPrepared(environment);` but I think the class doesn't get loaded because no component scan is taking effect.
- Branch `greenwich-active-profiles`:  It is the `finchley-active-profiles` but using `Greenwich` instead of `Finchley`. It still fails to pick up the class both with or without environment inheritance enabled or disabled. I guess the problem might have the same cause as with `Finchley`.

**Comment by artembilan** [comment]
Unfortunately we can't talk here about `Finchley` because there is no proper fix over there.
Also your application is too complicated to follow.

Is there really a way to reproduce it even without Kinesis?

Thanks for understanding!
