### ISSUE TITLE
Regression when using 'org.springframework.messaging.MessageHeaders' as message handler argument

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream#1575]
Looks like commit [a731021](https://github.com/spring-cloud/spring-cloud-stream/commit/a731021b435fee31f210a96af80401e6833ee9fa) has introduced a regression where 'MessageHeaders' can no longer be used as an argument to a message handler.

```java
@StreamListener(Processor.INPUT)
@SendTo(Processor.OUTPUT)
public String handle(MessageHeaders headers) {..}
```

`SmartPayloadArgumentResolver`'s `public boolean supportsParameter(MethodParameter parameter)` should _not_ return `true` if parameter is of type `org.springframework.messaging.MessageHeaders`

Affected version(s): 2.1.0.RC4

**Comment by olegz** [comment]
Yes, we've discovered it this morning as well. Will be fixed before the release

**Comment by Walliee** [comment]
Great! Look forward to it. 
Is there an ETA on when 2.1.0 will be released?

**Comment by olegz** [comment]
yeah, Monday
