### ISSUE TITLE
Requeueing a message should not be considered an error

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream#1578]
I would like to propose two changes when handling a message requeue in `DefaultPollableMessageSource`.

1. An error message shouldn't be sent to the `errrorChannel` if exception is(or wraps an exception) of type `RequeueCurrentMessageException`

https://github.com/spring-cloud/spring-cloud-stream/blob/d7e88a3a9cf367a9152ccef2b4eeb428b1eec42f/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultPollableMessageSource.java#L209-L215

2. Exception handling in `public boolean poll(MessageHandler handler, ParameterizedTypeReference<?> type)` shouldn't let the `RequeueCurrentMessageException` enclosing exception escape.

https://github.com/spring-cloud/spring-cloud-stream/blob/d7e88a3a9cf367a9152ccef2b4eeb428b1eec42f/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultPollableMessageSource.java#L226-L237

IMHO requeueing a message is not an exceptional circumstance from the poller's perspective. Maybe the poll method should return `false` in such a situation?

**Comment by olegz** [comment]
I am trying to understand as to why do you believe this should be different? I mean why should error handling during polling be handled differently then during event dispatching? All we're doing with polling is allowing throttling (rate control) of the event dispatch, everything else should stay the same for consistency sake. In other words polling is just another even dispatcher, right?

What we may consider is introducing a simple `Message<?> poll()` operation with some hooks essentially giving user full control, but even then we need to be careful to not go outside of scope of spring cloud stream

**Comment by Walliee** [comment]
Right, but I don't view `RequeueCurrentMessageException` as an error. It's already being treated differently as a message is requeued instead of being rejected if the exception wraps `RequeueCurrentMessageException`. The fact that an exception is used to convey that we don't want this message to be processed yet shouldn't semantically equate to it being an error, right?

I am finding it hard to imagine a case where errorChannel or poller would do something with this information. Most error handlers aren't going to be written to account for `RequeueCurrentMessageException`, for e.g. having `org.springframework.integration.handler.LoggingHandler` listen on the `errorChannel` would mean an exception is logged every time a message is requeued. 

This is not a blocker for me as I can easily take care of the requeueing in my message handler by getting the ack callback, requeue and return (even though it will be indicated to the poller as if a message was just processed as the poll method will return `true`) but felt like it made sense for SCS to do the same and return `false`. 

```java
AcknowledgmentCallback ackCallback = StaticMessageHeaderAccessor
				.getAcknowledgmentCallback(message);
AckUtils.requeue(ackCallback);
```
Please feel free to close if you think otherwise.

**Comment by olegz** [comment]
I see your point @Walliee . . .
