### ISSUE TITLE
RC3 to RELEASE regression? (unresolvable circular reference?) 

### ISSUE THREAD

**Issue by dharrigan** [spring-cloud/spring-cloud-stream#1584]
Hi,

I'm encountering a *very* strange issue that only happens if I bump my spring cloud stream dependency from RC3 to RELEASE. Here is what I'm observing (which I'm running a test that simply tries to load up the context):

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   payloadHandler defined in file [/home/david/tmp/circular-stream/out/production/classes/com/dharrigan/handler/PayloadHandler.class]
      ↓
   payloadGatewayRouter defined in file [/home/david/tmp/circular-stream/out/production/classes/com/dharrigan/router/PayloadGatewayRouter.class]
      ↓
   jacksonObjectMapper defined in class path resource [org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration$JacksonObjectMapperConfiguration.class]
      ↓
   jacksonObjectMapperBuilder defined in class path resource [org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration$JacksonObjectMapperBuilderConfiguration.class]
      ↓
   standardJacksonObjectMapperBuilderCustomizer defined in class path resource [org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration$Jackson2ObjectMapperBuilderCustomizerConfiguration.class]
      ↓
   spring.jackson-org.springframework.boot.autoconfigure.jackson.JacksonProperties
┌─────┐
|  BindingHandlerAdvise defined in class path resource [org/springframework/cloud/stream/config/BindingServiceConfiguration.class]
↑     ↓
|  org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration
↑     ↓
|  spring.mvc-org.springframework.boot.autoconfigure.web.servlet.WebMvcProperties
└─────┘
```

If I switch to Fishtown.RC3, this error goes away. 

I've got a stripped down project which I'll commit to my git repo and link here (once I've tidyed it up a bit).

In the meantime, any ideas?

**Comment by olegz** [comment]
No ideas David other then it appears to be boot related.
Please do post a reproducible version so we can take a look

**Comment by dharrigan** [comment]
Hi,

Could you try this please? 

`git clone https://github.com/dharrigan/issue-1584`

-=david=-

**Comment by olegz** [comment]
That doesn't look like strip down version ;), but let me see

**Comment by dharrigan** [comment]
Hi,

Well, the package names have been changed to protect the innocent and 99.9% of the business logic has been removed to protect the ego of others :-)

-=david=-

**Comment by olegz** [comment]
Actually what is this: `spring.mvc-org.springframework.boot.autoconfigure.web.servlet.WebMvcProperties`?  I am still digging (need to configure Kotlin environment in IDE), but was wondering if you know

**Comment by dharrigan** [comment]
Checking...

**Comment by olegz** [comment]
Unfortunately I can't even build it
```* Where:
Build file '/Users/olegz/tmp/issue-1584/build.gradle.kts' line: 7

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.3.11'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.3.11')
  Searched in the following repositories:
    maven(http://nexus.itbts.net/repository/maven-public)
```

**Comment by dharrigan** [comment]
Hi,

Please pull, I forgot to remove the link to our internal repo cache.

-=david=-

**Comment by olegz** [comment]
Ok, was able to reproduce, so let me see

**Comment by dharrigan** [comment]
Hi,

I'm deep in the bowels of spring, I think something screwy is going on -
you're right that "spring.mvc-org" is wrong. There is a prefix of
"spring.mvc", so perhaps there's something in terms of bean resolution that
is adding on a "-".
-=david=-

I prefer encrypted and signed messages.
Fingerprint: 110A F423 3647 54E2 880F ADAD 1C52 85BF B20A 22F9

No trees were harmed in the sending of this message, however, a number of
electrons were inconvenienced.

This email is sent without prejudice.
