### ISSUE TITLE
ModuleLauncher does not allow to take remoteRepositories that need username and password.

### ISSUE THREAD

**Issue by frosenberg** [spring-cloud/spring-cloud-stream#159]
Let's assume I need to launch a module that sits in a private maven repo (which needs a user/pwd):

```
java -jar target/spring-cloud-stream-module-launcher-1.0.0.BUILD-SNAPSHOT.jar --modules=io.myorg.custom.module:elasticsearch-sink:1.0.0.BUILD-SNAPSHOT -spring.cloud.stream.bindings.input=ticktock --remoteRepositories=http://mvnrepo.myorg.org/repositories/snapshots
```

The code will fail with an unauthorized error (401). For some reason there is no way to pass in the repository identifier that defined the password in `~/.m2/settings.xml`. 

Maybe something simple like the convention below will be good enough?

``` 
--remoteRepositories=<repoIdentifier>::http://mvnrepo.myorg.org/repositories/snapshots
```

This `<repoIdentifier>` could be used instead of the autogenerated on in the code and needs to match the `server` entry in `settings.xml`. If none is given, the auto-generated one could be used. However, the code still needs to be 'fixed' to also consider `settings.xml`, which currently seems to be ignored.

Let me know if that makes sense. I can do a PR....

**Comment by ericbottard** [comment]
We shall add support for repository authentication.
I'm not sure we want (or can even, as I'd have to have a look at how Aether works) the code to rely on a local `settings.xml` file. Generally speaking, it is assumed that the admin (and hence the deployer implementation) may be running in a cloud environment, where no previous human installation/interaction has happened. Ideally, all configuration should be done through Spring Cloud Dataflow, not through the native tools (this relates to my comment about the `kubernetes.` options in your kubernetes deployer implementation)

I created https://jira.spring.io/browse/XD-3634 to track this

**Comment by sabbyanandan** [comment]
This is already in scope for the generic cloud deployer w-i-p.
