### ISSUE TITLE
Document the configuration of relevant properties when connecting to/from existing message-broker infrastructure

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1592]
As a user, I'm attempting to connect to existing Rabbit infrastructure including the predefined exchange/queue resources; however, I'm unable to determine what properties to enable/disable, so the framework doesn't auto-create them differently.

More background in slack conversation [here](https://pivotal.slack.com/archives/C1RU2QDJL/p1548358151171700).

Notes:
- @garyrussell suggested adding a new section (perhaps: `Using SCSt to consume from existing infrastructure (exchange/queue)` that could be useful as a reference.
- It might also be helpful to define the requirement first, and follow-up with an example in this section. 
- Probably also clarify this in the context for both Rabbit and Kafka binders.

**Comment by garyrussell** [comment]
>Probably also clarify this in the context for both Rabbit and Kafka binders.

There's really no complexity with Kafka since the `destination` is simply the topic name,  but I suppose it won't hurt to mention that.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-kafka #629](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/629) via [**ZenHub**](https://www.zenhub.com/)
