### ISSUE TITLE
Reference documentation should list the binders that are available.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream#1598]
These are listed in the project page, but not in the reference documentation.

**Comment by olegz** [comment]
@markpollack [they are](http://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.1.0.RELEASE/single/spring-cloud-stream.html#_binder_implementations), but until we go to a better look-and-feel i do agree it is not always obvious. Tagging @sabbyanandan . . .

**Comment by sabbyanandan** [comment]
+1. We already have it in the docs, but it just needs to be elevated, and it will once when we have the new UI/UX PR merged upstream in spring-cloud-build.
