### ISSUE TITLE
Extended Binding Properties metadata broken

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#1601]
Extended binding properties are now returned as 

```java
	public Map<String, T> getBindings() {
		return this.bindings;
	}
```

Previously (2.0.x)

```java
	public Map<String, RabbitBindingProperties> getBindings() {
		return bindings;
	}
```

The type is lost and so content-assist in STS and IDEA is broken for these properties.

Metadata:

```json
    {
      "name": "spring.cloud.stream.rabbit.bindings",
      "type": "java.util.Map<java.lang.String,T>",
      "sourceType": "org.springframework.cloud.stream.binder.rabbit.properties.RabbitExtendedBindingProperties"
    },
```

Vs.

    {
      "sourceType": "org.springframework.cloud.stream.binder.rabbit.properties.RabbitExtendedBindingProperties",
      "name": "spring.cloud.stream.rabbit.bindings",
      "type": "java.util.Map<java.lang.String,org.springframework.cloud.stream.binder.rabbit.properties.RabbitBindingProperties>"
    }

**Comment by olegz** [comment]
We obviously need to raise it with boot team and I will, but meanwhile I'll push a fix that will both preserve the base method yet generates proper type information.

**Comment by garyrussell** [comment]
https://github.com/spring-projects/spring-boot/issues/15850
