### ISSUE TITLE
BinderAwareChannelResolver thread safety during binding initialization

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream#1603]
Even though new binding registration via `BinderAwareChannelResolver#resolveDestination(String channelName)` is protected by a `synchronized` block, it is still susceptible to multiple threads trying to publish a message concurrently and some threads failing due to incomplete binding infrastructure setup.

https://github.com/spring-cloud/spring-cloud-stream/blob/ac98622ad1e0dfe05db6b304571f29822b3c71cc/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BinderAwareChannelResolver.java#L107-L155

Consider the following scenario:
1. T1 comes in and tries to resolve destination for the channel name C
2. Since it's the first time channel name C is being resolved, it is not found by `BeanFactoryMessageChannelDestinationResolver`'s resolveDestination method
3. We then enter the `synchronized` block to initialize binding
4. Channel C is successfully created and registered with `beanFactory` but there is still other things that happen after this step
5. Now, either the `this.newBindingCallback.configure(channelName, channel,
						producerProperties, extendedProducerProperties)`  or the `this.bindingService.bindProducer(channel,
					channelName)` takes some time.
6. T2 comes in trying to resolve destination for channel C
7. Since the message channel bean exists in the beanFactory it is returned
8. T2 tries to publish a message on channel C 
9. `send(Message<?> message)` on the channel throws an exception like this `org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel`

I created a test demonstrating this behavior: https://github.com/Walliee/dynamic-destination-threading-bug

I think moving `this.beanFactory.registerSingleton(channelName, channel);` to be the last line in `BinderAwareChannelResolver#resolveDestination(String channelName)` would resolve this issue without any side-effects.

**Comment by olegz** [comment]
The actual issue is with the `super` code block that is outside of the synch block.
This probably need  a bit more thought, but with a small restructuring of the code it seems to work. Will push a fix shortly.

**Comment by olegz** [comment]
Also, @Walliee my apology about implying your PR broke the build. It didn't as it was broken before due to the unrelated change!

**Comment by Walliee** [comment]
@olegz No worries. As always, thank you for looking into it promptly!

Is there an ETA on the v2.1.1 patch?

**Comment by olegz** [comment]
I am aiming for this Monday, Feb 11.
