### ISSUE TITLE
MessageHandlingException on KafkaNull payload

### ISSUE THREAD

**Issue by akutschera** [spring-cloud/spring-cloud-stream#1607]
I am writing a test for Kafka Tombstone records, which are represented as a KafkaNull payload.
Up until spring-cloud-dependencies Grennwich.RC2 the tests work. With Greenwich.RELEASE they fail.
My Listener method looks like this:
```java
    @ServiceActivator(inputChannel = "returnBook")
    public void returnBook( @Payload(required = false) Book message,
                            @Header(KafkaHeaders.MESSAGE_KEY) String key ) {
    }
```
The Stacktrace begins with

    org.springframework.messaging.MessageHandlingException: nested exception is 
    org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method 
    returnBook(org.springframework.kafka.support.KafkaNull,java.lang.String) cannot be found on type 
    com.example.demo.kafka.TopicReader$$EnhancerBySpringCGLIB$$75eef271

I've attached a simple demo program that fails/works with the respective versions set
I can also make the tests pass when I downgrade the version of spring-cloud-stream from 2.1.0.RELEASE to 2.1.0.RC4, that's why I assume the problem is a spring-cloud-stream issue.

[kafka-null-example.zip](https://github.com/spring-cloud/spring-cloud-stream/files/2846704/kafka-null-example.zip)

**Comment by olegz** [comment]
This has been addressed with [this commit](https://github.com/spring-cloud/spring-cloud-stream/commit/ac98622ad1e0dfe05db6b304571f29822b3c71cc) and will be available with 2.1.1 release shortly.
Tagging @garyrussell

**Comment by garyrussell** [comment]
@akutschera Please try to remove Lombok when submitting samples; it's a pain for those of us who prefer not to use it. This one was not too bad I just had to generate a couple of accessors; but sometimes we get samples than can take significant time to remove Lombok.

(But a sample with Lombok is better than non at all 😄 , so thanks anyway).

Just to clarify; RC4 used the native Spring Integration argument resolvers; but the release added a payload resolver above the one that handles `KafkaNull`.

The commit @olegz pointed too adds support for it to the SCSt resolver.

**Comment by akutschera** [comment]
Sorry for the lombok. I'll do better next time.
Thanks for reacting so quickly.
I'll close this issue then
