### ISSUE TITLE
BindingHandlerAdvise forces to validate beans

### ISSUE THREAD

**Issue by ceremo** [spring-cloud/spring-cloud-stream#1681]
Hi,
I found a difference of behaviour when I include in my project the spring-cloud-bus dependency, this carries the transitive dependency spring-cloud-stream, and when I enable autoconfiguration always is validating beans (with @ConfigurationProperties annotation) that are not supposed to be validated. If I remove this dependency the behaviour is what I expect, only validates beans with the @Validated annotation or implementing Validator interface.

The problem is related with this issue https://github.com/spring-cloud/spring-cloud-stream/issues/1573 included in the 2.1 version. The class BindingServiceConfiguration is defining a bean of type BindingHandlerAdvise that creates a ValidationBindHandler, this is used in ConfigurationPropertiesBinder when is resolving the bindHandler.

I include a simple project to show this.
[spring-cloud-bus-example-app.zip](https://github.com/spring-cloud/spring-cloud-stream/files/3042167/spring-cloud-bus-example-app.zip)

Thxs.

**Comment by ceremo** [comment]
Sorry but I disagree with the last comment, I think it's an issue of spring-cloud-stream or at least a combination with spring-boot. 

In my sample there is a test(`DemoApplicationTests`) to prove that the `BindingHandlerAdvice` is causing the validation of all the beans with `@ConfigurationProperties`, this test disables the BindingServiceConfiguration (`@EnableAutoConfiguration(exclude = BindingServiceConfiguration.class)`) and with this the context loads correctly, that means `TestNonValidatedDomainClass` bean won't be validated.

If there is a `ConfigurationPropertiesBindHandlerAdvisor` (`BindingHandlerAdvice`) defined in the context the `ConfigurationPropertiesBinder` of spring-boot is going to resolve with this handler, please check the methods `getBindHandler` and `getBindHandlerAdvisors`. If you think there is a problem of spring-boot resolving the handler with the advisors defined in the context, I could try to open an issue to them, but who defines the handler advisor is spring-cloud-streams.

Thxs.

**Comment by olegz** [comment]
I am actually seeing this behavior now, let me see what's going on
