### ISSUE TITLE
How to Access Aiven's Schema Registry in Spring Cloud Stream

### ISSUE THREAD

**Issue by mvadood** [spring-cloud/spring-cloud-stream#1689]
I'm using spring cloud stream alongside [Aiven][1]'s schema registry which  uses [confluent's schema registry][2]. Aiven's schema registry is secured with a password. Based on [these][3] instructions, these two config parameters need to be set to successfully access the schema registry server.

     props.put("basic.auth.credentials.source", "USER_INFO");
     props.put("basic.auth.user.info", "avnadmin:schema-reg-password");

Everything is fine when I only use vanilla java's kafka drivers, but if I use Spring cloud stream, I don't know how to inject these two parameters. At the moment, I'm putting "basic.auth.user.info" and "basic.auth.credentials.source" under "spring.cloud.stream.kafka.binder.configuration" in the application.yml file.

Doing this, I'm getting "401 Unauthorized" on the line where the schema wants to get registered. 

  [1]: https://aiven.io/kafka
  [2]: https://github.com/confluentinc/schema-registry
  [3]: https://help.aiven.io/kafka/kafka-add-ons/using-schema-registry-with-aiven-kafka

**Comment by sobychacko** [comment]
@mvadood Thank you for the issue. I think there is also a parallel [StackOverflow thread](https://stackoverflow.com/questions/55701542/how-to-access-a-confluent-schema-registry-server-secured-with-a-password-using-s) going on. Closing this issue here in favor of the SO thread.
