### ISSUE TITLE
Add support of multiple binding routing keys in Stream Rabbit

### ISSUE THREAD

**Issue by domainname** [spring-cloud/spring-cloud-stream#1693]
Currently we can bind with only one routing key in Stream Rabbit via configuration in yaml file. That prevent us from combining multiple message flows (with different routing key) into one.

Ideally, I want support like this:

```
spring.cloud.stream.rabbit.bindings.<channel-name>.consumer.binding-routing-keys=key1,key2,key3
```

**Comment by olegz** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-rabbit #242](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/242) via [**ZenHub**](https://www.zenhub.com/)
