### ISSUE TITLE
Messages are acknowledged right after emit, not after process in reactive consumers.

### ISSUE THREAD

**Issue by kgonia** [spring-cloud/spring-cloud-stream#1694]
When reactive consumers are used messages are acknowledged right after emit. Is it expected behavior? 
Documentation doesn't describe this behavior and it is not consistent with non-reactive stream listener where message is acknowledge after process.

**Comment by olegz** [comment]
@KrzychuJedi when you are asking about reactive consumers are you asking specifically about reactive module or spring-cloud-function support which [provides reactive support natively](https://spring.io/blog/2018/08/28/spring-cloud-stream-fishtown-m2-2-1-0-m2-release-announcement)?

**Comment by KrzychuJedi** [comment]
@olegz I'm asking about reactive stream listener. If my description is insufficient, I can provide an example. But at start I want to know if it is expected behavior.

**Comment by olegz** [comment]
The reality is that while we provide reactive as a programming model, until we are dealing with the actual reactive sources/targets there is not much we can do to address this given asynchronous nature of reactive API. We certainly can't and should not try to do something that can go agains the nature of the reactive API.

**Comment by kgonia** [comment]
@olegz  So to not go agains reactive API you go agains MQTT protocol? Maybe problem is with trying connect old non-reactive code based on listeners with reactive API? 

MQTT client from Project Reactor teams doesn't have such problem ;)

**Comment by olegz** [comment]
True, but we need MQTT binder. "problem is with trying connect old non-reactive code " - that is what I was trying to explain in my comment.

**Comment by kgonia** [comment]
@olegz Ok, So it least it would be nice if that behavior would be mentioned in docs.

**Comment by olegz** [comment]
We will. There are a lot of new things coming with regard to both functional development and reactive for spring-cloud-stream 3.0 so there are going to be blogs and major doc updates
