### ISSUE TITLE
Spring cloud reactive steam's (SCF) Processor is not working with ParallelFlux and Schedulers

### ISSUE THREAD

**Issue by msshitole** [spring-cloud/spring-cloud-stream#1696]
In our reactive stream Processor app, when we try parallel processing with Schedulers. The Flux gets stuck after some seconds.
Whereas the parallel processing with Schedulers works fine in Source and Sink apps. 
Could you please check on this. Here is the sample code
```
@SpringBootApplication
@EnableBinding(Processor.class)
public class ParallelProcessorApplication {

    public static void main(String[] args) {
        SpringApplication.run(ParallelProcessorApplication.class,
                "--spring.cloud.stream.function.definition=process");
    }

    @Bean
    public Function<Flux<Long>, ParallelFlux<Long>> process() {
        return longFlux ->
                longFlux.parallel(4)
                        .runOn(Schedulers.elastic())
                        .doOnNext(i -> System.out.println(Thread.currentThread().getName() + " -> " + i));
    }

}
```

Here is the working code from the Source application. In source application, it works as expected.

```
@SpringBootApplication
@EnableBinding(Source.class)
public class ParallelSourceApplication {

    public static void main(String[] args) {
        SpringApplication.run(ParallelSourceApplication.class,
                "--spring.cloud.stream.function.definition=emit");
    }

    @Bean
    public Supplier<ParallelFlux<Long>> emit() {
        return () -> Flux.interval(Duration.ofMillis(1))
                         .parallel(4)
                         .runOn(Schedulers.parallel())
                         .doOnNext(i -> System.out.println(Thread.currentThread().getName() + " -> " + i));
    }

}
```
@olegz 
If require more details, will push my sample projects to gitHub. Thank you in advance!

P.S

There is another issue with Processor and Sink apps. If I chose `Schedulers.parallel()` instead of `Schedulers.elastic()`. Then parallel processing not works. It does not spawn multiple threads. Whereas the same works fine with Source app fine. Kindly check below processor code for this issue:

The sample code is here
```
@Bean
    public Function<Flux<Long>, ParallelFlux<Long>> process() {
        return longFlux ->
                longFlux.parallel(4)
                        .runOn(Schedulers.parallel())
                        .doOnNext(i -> System.out.println(Thread.currentThread().getName() + " -> " + i));
    }
```

In the ouput logs, you can see only **parallel-1** for all the emitted elements. Whereas the expected behavior is. I should see **parallel-1** **parallel-2** **parallel-3** **parallel-4** etc.
```
parallel-1 -> 1
2019-04-23 16:00:39.261  INFO 32457 --- [     parallel-1] reactor.Flux.ConcatMap.1                 : onNext(1)
parallel-1 -> 2
2019-04-23 16:00:39.263  INFO 32457 --- [     parallel-1] reactor.Flux.ConcatMap.1                 : onNext(2)
parallel-1 -> 3
2019-04-23 16:00:39.272  INFO 32457 --- [     parallel-1] reactor.Flux.ConcatMap.1                 : onNext(3)
parallel-1 -> 4
2019-04-23 16:00:39.286  INFO 32457 --- [     parallel-1] reactor.Flux.ConcatMap.1                 : onNext(4)
parallel-1 -> 5
2019-04-23 16:00:39.308  INFO 32457 --- [     parallel-1] reactor.Flux.ConcatMap.1                 : onNext(5)
parallel-1 -> 6
2019-04-23 16:00:39.320  INFO 32457 --- [     parallel-1] reactor.Flux.ConcatMap.1                 : onNext(6)
parallel-1 -> 7
2019-04-23 16:00:39.336  INFO 32457 --- [     parallel-1] reactor.Flux.ConcatMap.1                 : onNext(7)
parallel-1 -> 8
```
I think both issue are related. Kindly do let us know If different issue needed for the same. Thank you!

**Comment by olegz** [comment]
So, I am not sure at the moment that using `ParallelFlux` in the context of spring-cloud-stream handler is a good idea. Let me explain:
While we provide a support for reactive abstractions  we internally create a delegation model from MessageListener to reactive listener. Which means in the end you are still at the mercy of MessageListening Container, task executor and so on.

So if you do want to parallelise i would simply increase concurrency settings on consumer binding `spring.cloud.stream.bindings.input.consumer.concurrency=3`, otherwise there could be unintended consequences and potential loss of messages

**Comment by msshitole** [comment]
@olegz Thanks for letting us know the internal handling details. Still, it would be better to handle this hanging error in some ways. In this case, we should through some exceptions back to the message handler/processor. So that user can be aware of the root cause for the hang/stuck after processing a few messages.

Nevertheless, as you suggested, will give a try parallelizing by the below config. Thanks for the suggestion!
>spring.cloud.stream.bindings.input.consumer.concurrency=3

In case, if ParallelFlux is not supported or not a good idea. Still, as a user, I would like to use ParallelFlux for internal business logic for some intensive method. And while returning to the MessageListener,  I can covert parallelFlux to the sequential Flux like `parallelFlux.sequential()`. 
In this case, below code should work but this also hangs in between...
For example:
```
@Bean
    public Function<Flux<Long>, Flux<Long>> process() {
        return longFlux ->
                longFlux.parallel(4)
                        .runOn(Schedulers.parallel())
                        .doOnNext(i -> System.out.println(Thread.currentThread().getName() + " -> " + i))
                        .doOnNext(i -> someIntensiveOperation())
                        .sequential();
    }
```

Could you please check if it makes a sense. Your thoughts on this. Thank you very much!

**Comment by msshitole** [comment]
@olegz I am doing some intensive regex matches on the large collection/flux internally. Hence this bug fix is immensely important for us. Could you please check on this. 

It's totally OK if not works on the message-handler level. But at least it should allow using in any of the methods for some business logic internally. Your thoughts on this. Thank you in advance!

**Comment by olegz** [comment]
@msshitole  We won't be documenting it for reactive module as we are fading it away in favor of spring-cloud-function native flux support and at some point in the near future we'll write a section about what you should expect when using flux with non-reactive binders such as Rabbit and Kafka as well as what one _should and should not do_ .

Feel free to raise another issue for documentation around usage of flux and its implications, but there is nothing we can/should do here and I think I've already explained that parallelisation in your case would cause more complexity.
