### ISSUE TITLE
Make SpEL usage consistent across all including custom modules

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#170]
As a user, I'd like to use SpEL expressions inline at the stream definition level, so I can operate on the payload consistently while using any OOTB, including the custom modules.

**Acceptance Criteria:**
* Applicability of SpEL expression is consistent across the modules 
* Utility function exist and overridable for custom modules 
* Applied across OOTB modules and verifiable via test fixtures 
* Implementation details are documented with examples

**Comment by sabbyanandan** [comment]
Core functionality will be supported at the SI level through [INT-3874](https://jira.spring.io/browse/INT-3874).

**Comment by artembilan** [comment]
I might visit the XD stand up call to know more, but sorry me for missing that and share, please, more info what to do there in SI and what exactly should be implemented here.

Thanks in advance!
