### ISSUE TITLE
AvroSchemaRegistryClientMessageConverter not finding objects in reflectionCache

### ISSUE THREAD

**Issue by PhilHardwick** [spring-cloud/spring-cloud-stream#1701]
I'm getting an `org.springframework.cloud.stream.schema.SchemaNotFoundException` at `org.springframework.cloud.stream.schema.avro.AvroSchemaRegistryClientMessageConverter.extractSchemaForWriting(AvroSchemaRegistryClientMessageConverter.java:350)`.

I believe this is because when it gets the cache on https://github.com/spring-cloud/spring-cloud-stream/blob/a9b1b4f2bbcf73a6e27472f002a452b828356c63/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AvroSchemaRegistryClientMessageConverter.java#L370 the `getCache()` doesn't pass through the name to the cache manager:
https://github.com/spring-cloud/spring-cloud-stream/blob/a9b1b4f2bbcf73a6e27472f002a452b828356c63/spring-cloud-stream-schema/src/main/java/org/springframework/cloud/stream/schema/avro/AvroSchemaRegistryClientMessageConverter.java#L417.

If you agree, happy to submit a PR for this.

**Comment by olegz** [comment]
Yes, please submit a PR. What you explained makes sense, but PR will certainly clarify

**Comment by quells2** [comment]
Hi, will this still be backported into v2.2.1? I don't see any references to this issue it in the list of commits on the `2.2.x` branch.
