### ISSUE TITLE
Not able to create custom RetryTemplate using @StreamRetryTemplate while using multiple binders

### ISSUE THREAD

**Issue by shadabmadhav** [spring-cloud/spring-cloud-stream#1702]
I am using spring cloud stream with multiple binders . I tried to create custom RetryTemplate using @StreamRetryTemplate . Bean of custom RetryTempalte is being created but not injecting in AbstractBinder. When i tried with single binder its working properly.

Version : Greenwich.SR1

Custom Retry Template Code Snippet ->
```@StreamRetryTemplate
public RetryTemplate myRetryTemplate() {
    RetryTemplate retryTemplate = new RetryTemplate();
    SimpleRetryPolicy simple = new SimpleRetryPolicy(4);
    retryTemplate.setRetryPolicy(simple);
    return retryTemplate;
}

application.yml ->

server:
  port: 7777
spring:
  cloud:
    stream:
      binders:
        kafka_binder:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: localhost:9092
      bindings:
        input:  
          destination: EMPLOYEE-TOPIC-R1-P1
          binder: kafka_binder
          contentType: application/json
          group: so51247113`

**Comment by olegz** [comment]
What you are asking is not available in the version you are using but it is available in 2.2.0.RC1
Please see [this section](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.2.0.RC1/spring-cloud-stream.html#_retry_template) of the user guide. At the end of the section it explains how to deal with multiple templates per binding.

**Comment by shadabmadhav** [comment]
@olegz , Thanks for your reply . I am not trying per binding retry template . I am looking for common Retry Template for all binders with above mentioned configuration .   I have gone through [this](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.1.2.RELEASE/single/spring-cloud-stream.html#_retry_template) document

**Comment by olegz** [comment]
Have you tried `spring.cloud.stream.default.<property>=<value>`? This way it will apply to all bindings

**Comment by olegz** [comment]
Also, as I stated earlier the version you are using and the document you are pointing to did not have that feature. It was recently added

**Comment by cyuegit** [comment]
i have the same problem@mdshadabali15.I am using spring cloud stream with multiple binders

**Comment by cyuegit** [comment]
@onobc 
i have the same problem.I am using spring cloud stream with multiple binders.
spring-cloud-stream-binder-kafka 3.2.1
spring-cloud-stream-binder-rabbit 3.2.1
