### ISSUE TITLE
asciidocs: unresolved link

### ISSUE THREAD

**Issue by andysworkshop** [spring-cloud/spring-cloud-stream#1703]
[2.3.2. Deprecated Classes and Methods](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#spring-cloud-stream-preface-deprecation-classes-methods).

There's an unresolved hyperlink in the text:

The following is a quick summary of notable deprecations. See the corresponding {spring-cloud-stream-javadoc-current}[javadoc] for more details.

**Comment by sabbyanandan** [comment]
Thank you for reporting. It'd be better if you can stick to the latest GA release. As of today, we are at 2.2 GA and the docs are [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.2.0.RELEASE/home.html). And, this section is not relevant in 2.2 release line.
