### ISSUE TITLE
Could not intercept message in ChannelInterceptor while using Kstream Type

### ISSUE THREAD

**Issue by desertTown** [spring-cloud/spring-cloud-stream#1704]
hi
I got a problem when I want to intercept the message using ChannelInterceptor 
It work while I use SubscribableChannel type as input channel

`    @Input(MESSAGE_EVENTS_IN)`
`    SubscribableChannel input();`

but if I use KStream as input channel and I cannot  intercept the message in ChannelInterceptor's preSend method. It seems ChannelInterceptor  cannot intercept message type of KStream.

`@Input(MESSAGE_EVENTS_IN)`
`    KStream<?, ?> input();`

is there any suggestion to intercept the KStream message and add some common header?

Thanks

**Comment by olegz** [comment]
KStream binder does not use MessageChannels as it binds directly to a KStream exposed by Kafka giving you more control.

**Comment by desertTown** [comment]
> KStream binder does not use MessageChannels as it binds directly to a KStream exposed by Kafka giving you more control.

Thanks for your reply, olegz.
for another question:
 >  as you said, KStream is not the  channel-based binder
 >  so is there any idea to intercept the KStream Data?   such as rewrite the header...

**Comment by garyrussell** [comment]
The next version of Spring for Apache Kafka (2.3) adds a `HeaderEnricher` which can be used in a stream definition to add headers. It will be available when the Kafka binder moves to that version.

In the meantime, you can implement something similar yourself (although it may not need the added complexity of expression-based header values).

The [commit is here](https://github.com/spring-projects/spring-kafka/commit/69a6ac355710e263deac227629227a575c2a9597).

**Comment by desertTown** [comment]
> The next version of Spring for Apache Kafka (2.3) adds a `HeaderEnricher` which can be used in a stream definition to add headers. It will be available when the Kafka binder moves to that version.
> 
> In the meantime, you can implement something similar yourself (although it may not need the added complexity of expression-based header values).
> 
> The [commit is here](https://github.com/spring-projects/spring-kafka/commit/69a6ac355710e263deac227629227a575c2a9597).

thanks
