### ISSUE TITLE
Add standardized way to pass props from Deployers/Admin to ModuleLauncher

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#171]
There is a need to customize the ModuleLauncher behavior (itself, NOT pass options to modules that are launched, which is already supported) for example to set the location of the maven repository.

**Comment by mbogoevici** [comment]
I think that this is a Spring Cloud Data Flow requirement. The Module Launcher already supports this, but the admin server does not pass any of such settings.

**Comment by sabbyanandan** [comment]
You're correct! I reopened the JIRA issue. Closing it.
