### ISSUE TITLE
Spelling error in document

### ISSUE THREAD

**Issue by yanxinyuan** [spring-cloud/spring-cloud-stream#1714]
There are some spelling errors in spring cloud stream [document](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.SR2/reference/htmlsingle/#_what_s_new_in_2_0)(v2.0).

The code example in the document, 
```
@Autowire  -> Wrong annotation
private Source source  

public void sayHello(String name) {
    source.output().send(MessageBuilder.withPayload(name).build());
}
```
But there isn't existing **Autowire** annotation, it should be the **Autowired** annotation.

**Comment by olegz** [comment]
Fixed with 4d9399ae131e8e682a3e01eefe24679f8719ef30
