### ISSUE TITLE
using RabbitMQ and HEADERS exhange type, queue is not bound to exchange

### ISSUE THREAD

**Issue by rabiori** [spring-cloud/spring-cloud-stream#1749]
case:
https://stackoverflow.com/questions/56735273/using-spring-cloud-stream-with-rabbitmq-with-exchange-type-headers

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-rabbit #254](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/254) via [**ZenHub**](https://www.zenhub.com/)
