### ISSUE TITLE
Add support to provide a mechanism to track Send Result Metadata

### ISSUE THREAD

**Issue by NLatyshev** [spring-cloud/spring-cloud-stream#1750]
Hi everyone.

Is there way to know if message sent or not?

For example, I have Kafka binder and use MessageChannel to produce message to some topic (e.g. in some controller). Method send always returns true (and I didn't found any other method to pass callback) even if Kafka connection lost. So seems user newer find out he/she request is lost.

Can someone suggest resolution? Is it documentation defect or just the functionality is absent (and not planned)

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-kafka #694](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/694) via [**ZenHub**](https://www.zenhub.com/)
