### ISSUE TITLE
Method, ServerController.findBySubjectAndVersion(@PathVariable("subject") String subject,@PathVariable("format") String format)  is actually findBySubjectAndFormat

### ISSUE THREAD

**Issue by jmax01** [spring-cloud/spring-cloud-stream#1760]
Method, `ServerController.findBySubjectAndVersion(String subject, String format)`,  is actually `findBySubjectAndFormat`

PR incoming

https://github.com/spring-cloud/spring-cloud-stream/blob/b5a64eac1406369d21ae2281519caf08404555b5/spring-cloud-stream-schema-server/src/main/java/org/springframework/cloud/stream/schema/server/controllers/ServerController.java#L138

**Comment by sabbyanandan** [comment]
@jmax01: It appears we didn't receive a PR from your branch yet - just a friendly reminder.

**Comment by sobychacko** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream/commit/0ad15247f6736959a3c6307e4eef0a7139c142bf
