### ISSUE TITLE
Bind message properties to modules

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#177]
As a s-c-s developer, I'd like to support XD-like features where modules bind to incoming messages via expressions or other mechanism, so I can bind message properties to every microservice modules.

**Comment by ericbottard** [comment]
Please clarify what this is.
Is this transparent support for `--foo` and `--fooExpression`?

**Comment by sabbyanandan** [comment]
I wrote this initially with `header-enricher` in mind, but this story belongs to SCSM repo. Closing this.
