### ISSUE TITLE
Actuator binding kafka don't show default kafka consumer properties

### ISSUE THREAD

**Issue by iguissouma** [spring-cloud/spring-cloud-stream#1774]
I have the following configuration as kafka default conumer (autoCommitOffset =false):

![image](https://user-images.githubusercontent.com/9085108/61941734-5952d000-af98-11e9-9657-d6ab9a73785c.png)

When I see the /actuator/bindings/my-binding on my application, I have the default values (autoCommitOffset =true)

![image](https://user-images.githubusercontent.com/9085108/61942307-70de8880-af99-11e9-8813-4807a01afaa6.png)

Version used: Greenwich.RELEASE

**Comment by olegz** [comment]
You need to upgrade spring-cloud-sream to 2.2.x. There were issues with defaults which have been addressed, so please upgrade and let us know

**Comment by iguissouma** [comment]
Seems working with Hoxton.M1

![image](https://user-images.githubusercontent.com/9085108/61957629-fb39e300-afbf-11e9-97fb-fa1bbf42d6c5.png)

![image](https://user-images.githubusercontent.com/9085108/61957681-17d61b00-afc0-11e9-8c73-13e7cae4fa13.png)

I'm not sure if it's a problem or is the expected behaviour, suppose I add enableDlq on the previous configuration I will have an Exception thrown while starting consumer:
Caused by: java.lang.IllegalArgumentException: DLQ support is not available for anonymous subscriptions. this can happens too when the topic does not exist on the kafka broker.

When I go to /actuator/bindings I have the following error:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jul 26 16:13:52 CEST 2019
There was an unexpected error (type=Internal Server Error, status=500).
Could not write JSON: Binding implementation `org.springframework.cloud.stream.binding.BindingService$LateBinding` must implement this operation before it is called; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Binding implementation `org.springframework.cloud.stream.binding.BindingService$LateBinding` must implement this operation before it is called (through reference chain: java.util.ArrayList[0]->org.springframework.cloud.stream.binding.BindingService$LateBinding["input"])
```

When spring cloud stream cannot start consumer, we cannot determine which bindind cannot be started on logs.

Thanks.

**Comment by olegz** [comment]
The "Caused by: java.lang.IllegalArgumentException: DLQ support is not available for anonymous subscriptions. this can happens too when the topic does not exist on the kafka broker." - is intentional as the error message explains why it is not possible. The subsequent actuator error is related. 

What we can do is better address the "we cannot determine which binding cannot be started on logs." by providing a more informative error message.

If you don't mind I'll rephrase the issue description (or you can do the same) and we can address it for 3.0.0.M3. Let me know.

**Comment by iguissouma** [comment]
I expected that the list of bindings will show even there's a problem starting a consumer and the status of binding can be 'starting'...

Yes, it would be useful to add more informative error message.
You can open another issue(it will be more clear), I will add more description if needed.
Example of logs where the topicName can be useful

```
org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner

this.logger.error("Failed to create topics", ex.getCause());
this.logger.error("Failed to obtain partition information", ex);
this.logger.error("Cannot initialize Binder", ex);
```



We can close this issue if there's no way to fix this Internal server error that occurs when one binding is not created on the actuator bindings.

Thanks.

**Comment by olegz** [comment]
Well, there is no "starting" state as it really failed, but I will try to add a more informative message.

**Comment by olegz** [comment]
The issue has been addressed:
The error message is more informative in the log:
```
Caused by: java.lang.IllegalArgumentException: DLQ support is not available for anonymous subscriptions to 'input' topic. . .
```
And visualisation as well:
<img width="857" alt="Screenshot 2019-07-30 at 13 56 05" src="https://user-images.githubusercontent.com/172397/62127224-d7351500-b2d1-11e9-86de-e7c1442eb95b.png">
