### ISSUE TITLE
Unresolved directive in documentation

### ISSUE THREAD

**Issue by RoganDawes** [spring-cloud/spring-cloud-stream#1777]
![image](https://user-images.githubusercontent.com/159883/62607835-087b9980-b8ff-11e9-97fc-f55c44aeab4f.png)

https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.1.0.BUILD-SNAPSHOT/reference/htmlsingle/#architecture

**Comment by olegz** [comment]
Please raise the issue wit the appropriate project. This issue tracker for spring-cloud-stream project

**Comment by snicoll** [comment]
@olegz That's my fault, I've redirected @RoganDawes to [the wrong issue tracker](https://twitter.com/snicoll/status/1159015560694419457) 🤦‍♂️

**Comment by olegz** [comment]
No problem @snicoll, was jus a bit confused ;)
