### ISSUE TITLE
Consider Supporting Request Reply model with Spring Cloud Function Reactive

### ISSUE THREAD

**Issue by sabareeshkkanan** [spring-cloud/spring-cloud-stream#1800]
Linking related issue here. #815  which is still open. As more people adapting micro-service architecture there are several services which in turn needs some kind or request reply model when communicating through messaging model. Native support to this will be greatly appreciated.

**Comment by olegz** [comment]
This would be better realized with binders build on top of req/rep capable protocols such as RSocket etc. Doing it with standard messaging binders such as Rabbit, Kafka would be cumbersome and  most likely not the right tool for the job.
We are working on relaxing binder APIs to allow these type pf binders. And in fact you can also do it today with Spring Cloud Function RSocket support - https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-rsocket
