### ISSUE TITLE
Add state to Eureka when deploying s-c-s modules

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#182]
As a s-c-s user, I'd like to have my modules add/update it's current state to Eureka, so I can use the repository to discover the current sate of the module as needed.

**Comment by mbogoevici** [comment]
Are this and https://github.com/spring-cloud/spring-cloud-stream/issues/185 duplicates by any chance? If not, we should make them a little more different.
