### ISSUE TITLE
Spring java format plugin

### ISSUE THREAD

**Issue by ArtyomGabeev** [spring-cloud/spring-cloud-stream#1826]
Hi,

What do you think about adding spring java format plugin for this project + binders implementations: 
https://github.com/spring-io/spring-javaformat

**Comment by ArtyomGabeev** [comment]
One of the difference I see is max line in spring javaformat is 120, whenever there looks like it's 90.

**Comment by olegz** [comment]
Not a fan of any kind of auto-formatting especially when it comes to limiting the length of the line.
So, I guess it's a no. 
Yet feel free to re-open it if you have more justification/concerns that you'd like to bring in the open.
