### ISSUE TITLE
Make s-c-s modules searchable by its name

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#184]
As a s-c-s user, I'd like to search the modules by it's name aside from the default *spring.application.name* offered by boot, so I can also fetch modules by it's name.

**Comment by ericbottard** [comment]
Please clarify which "search" feature we're talking about here. `spring.application.name` is something bound at runtime when the module is executing, so is this search about searching all running modules?
If not, then are we talking about *registered* modules? In which case 1) this is more of a dataflow issue (not sure what the rules regarding issue creation are yet) 2) and module shouldn't be uniquely identified by its name (rather type+name)
