### ISSUE TITLE
Stream getting dropped with onDropped

### ISSUE THREAD

**Issue by ranjith1235** [spring-cloud/spring-cloud-stream#1840]
I am using spring cloud stream for connecting to RabbitMQand then using reactive Cassandra library to save it to db. But after few times the stream stops processing and after some debugging found the following in the logs. 

2019-10-25 19:28:56.213  [cluster1-nio-worker-1] DEBUG r.c.p.Operators - onNextDropped: org.springframework.data.cassandra.core.cql.session.DefaultBridgedReactiveSession$DefaultReactiveResultSet@31aab3cf. 

Why would the streamListener stop completely for onNextDropped. Is there a way for me to ignore onNextDropped and continue processing the messages.

**Comment by olegz** [comment]
Please forward your concern to appropriate casandra forum. Spring Cloud Stream doesn't know anything about Casandra or any other library chosen by the user.
