### ISSUE TITLE
Partitioning support broken in functional programming model

### ISSUE THREAD

**Issue by chringwer** [spring-cloud/spring-cloud-stream#1855]
The `partitionKeyExpression` property stops having effect once `spring.cloud.stream.function.definition` is set. I think this due to the absence of the `PartitioningInterceptor` which would have previously been configured as part of the `MessageConverterConfigurer`. However, that bean does not get registered any more in case of a function definition being present:

https://github.com/spring-cloud/spring-cloud-stream/blob/253f3d6547b75f108df9f6aa61ff5f8a24c8a0f6/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BinderFactoryAutoConfiguration.java#L216

Is there another way to enable partitioning support in the functional programming model or should this be fixed?

**Comment by olegz** [comment]
At this moment I am looking at this as an enhancement, given hat we're trying to make functions work independent from the fact that at the moment it is backed by Spring Integration and thus channels. So it should be fixed

**Comment by olegz** [comment]
Just an FYI, the code you mentioned above is specifically related to delegating most of the functionality to spring-cloud-function (such as type conversion etc), but as you pointed out there is a side-effect. 
Anyway, we'll be doing SR1 before the end of the year, so you should have a fix for it soon.
