### ISSUE TITLE
Custom Message headers have changed between v2 and v3

### ISSUE THREAD

**Issue by smitp33** [spring-cloud/spring-cloud-stream#1856]
Not sure if this the right repo to raise this as the issue may be further down the stack ...

We have just upgraded one of our microservices from the `GermanTown` to `Horesham` release level. This service is producing kafka messages containing avro encoded payloads.

Older services now can now longer read the messages due to the following error:

```Caused by: java.lang.IllegalArgumentException: Unknown type for contentType header value: class [B```

When we look at the `GenericMessage` output we can see that the output is showing the following: 

```contentType=[B@64df63b5```

On the previous version of code the same debug statement shows:

```contentType=application/vnd.ourschemaname.v1+avro```

If we upgrade the consumers to the same level as the producer then this all works.

It would appear that the way the headers are being added has changed and this has adversely affected the interoperability between messages being consumed by v2 and v3 consumers ....

**Comment by fran-man** [comment]
Very similar issue raised (and apparently fixed) in the cloud stream kafka binders about a year ago.

Not sure how related these are but the symptoms are almost identical:

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/509

**Comment by olegz** [comment]
So avro message converter was coming from schema registry module which is no longer part of core distribution and instead is now a separate project. You can see a separate link to it in https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.0.RELEASE/reference/html/index.html 
And here is the link to it's Github page - https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.0.RELEASE/reference/html/index.html
So it's maven coordinates have changed as well. See:
- https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-schema-registry-client/
- https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-schema-registry-core/
- https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-schema-registry-server/

We missed mentioning it in `What's New` section but will be releasing SR1 shortly (few weeks) where we'll mention it explicitly and provide more directives.
Hope this resolves your concerns, but please feel free to reopen it if you still have issues.

**Comment by smitp33** [comment]
Not sure that this explains all the behaviour we have seen though. We have also seen that a custom header that we add is also now displaying as `bytes` instead of a `string`, so its like the additional integration specific string headers (in addition to the normal kafka headers) is changed en-mass rather than just for the avro specific ones. Could this be done to different versions of the binders being used in different projects?
