### ISSUE TITLE
Refactor s-c-s samples to use @ConfigurationProperties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#186]
The spring-cloud-streams samples have module options classes copied over from XD.
They should use a pure @ConfigurationProperties approach, making sure metadata is generated/hand written as appropriate.

@Mixins are still referenced there but obviously can't work, so provide an equivalent

**Comment by mbogoevici** [comment]
I would rather convert spring-cloud-stream samples into integration tests - which is the way that we are more or less using them. WDYT @sabbyanandan ? cc @markfisher

**Comment by markpollack** [comment]
I'm sure we will eventually have an examples repo, so bite the bullet now?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-samples#20
