### ISSUE TITLE
Unable to follow test examples in spring-cloud-stream 3.x

### ISSUE THREAD

**Issue by brmakana** [spring-cloud/spring-cloud-stream#1886]
Hello,

I'm trying to follow the testing guide here: https://github.com/spring-cloud/spring-cloud-stream/blob/master/docs/src/main/asciidoc/spring-cloud-stream.adoc#testing

but I'm not sure how to pull in the required dependency to get classes like `TestChannelBinderConfiguration`; I'm using Gradle. 

Are there plans to publish the "test jar" with these classes?

**Comment by krzysztof1980** [comment]
Hi, try this one:
testImplementation(group: 'org.springframework.cloud', name: 'spring-cloud-stream', classifier: 'test-binder')

**Comment by brmakana** [comment]
Thanks @krzysztof1980, that works!
