### ISSUE TITLE
A Function<Flux, Flux> seems to be invoked once for each message instead of sending all messages through a single input Flux

### ISSUE THREAD

**Issue by lbilger** [spring-cloud/spring-cloud-stream#1891]
I am currently switching from Spring Cloud Stream 2.x to 3.x. I have a Consumer that takes a `Flux` of `Message`s and aggregates data coming in from that `Flux`. It is bound to a Kafka topic.

Before 3.x, we used the `@StreamListener` annotation to bind the Consumer to the Kafka topic. It worked as expected, calling the method exactly once and then sending messages through the `Flux`.

When upgrading to 3.x (3.0.1.RELEASE to be precise), this method no longer works so I tried to switch to the functional configuration. I got it mostly to work but now I face the problem that my Consumer's `accept` method is called once with a new `Flux` for every message, which means I can't aggregate messages in the `Flux` processing. 

I tried to set up a new application from Spring Initializr as well and get the same results. Also, the example at https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/processor-samples/reactive-processor-kafka states in the README that data should be aggregated, outputting `Data received: foobarfoobarfoo` and so on, but when I run it as per instructions, I get a single `Data received` for each `foo` and `bar`.

**Comment by olegz** [comment]
@lbilger thank you for reporting it. I was ale to reproduce it and it will be available in the next release (Horsham.SR2/3.0.2.RELEASE) or on the snapshot as soon as this issue is resolved.

**Comment by olegz** [comment]
@lbilger indeed there is an issue, but it feels like we went over our head a bit. We need Flux.just so we can have a retry logic (via `retryBackoff`) for individual message failures which obviously goes counter trying to do any kind of windowing inside user function.

Need to think a bit, but will address it regardless. . .

**Comment by lbilger** [comment]
@olegz for us, this is the main reason we are using Flux as a function argument rather than just the message. We use it to buffer messages for a while and then process a batch of them at once. We have our own retry mechanism in the user function, using a combination of `cache` and `retryBackoff`. The `cache` makes sure the last message before the error is replayed when `retryBackoff` kicks in. Maybe you can use that idiom, too?

**Comment by olegz** [comment]
@lbilger Understood, and we just had a discussion precisely about that. Basically what we have decided is the following:  As much as we tried to bring some of the binder features into reactive functions mechanism, we keep on stumbling into similar issues. The main difference is; In reactive function, the unit of processing  is the entire stream, while in imperative is a single message. So the existing error per-message handling mechanism that we hooked up to the reactive function is the main cause of the issue. In other words by introducing a feature we also introduced the problem.

Anyway, we decided to fix it by not being too clever and simply give you a raw stream (Flux) and as you said, he error handling, retries etc., will e the responsibility of the user.

**Comment by olegz** [comment]
@lbilger so reverting [this commit](https://github.com/spring-cloud/spring-cloud-stream/commit/a5e990b2d099fca3d58fda09234a5b392e659bb7) appears to resolve the issue.
If you get a chance give it a shot, meanwhile i'll create a few tests as well and then if all confirmed will resolve the issue

**Comment by lbilger** [comment]
@olegz I could verify it works in the reactive-processor-kafka example now. However it did not work in my real code. After some investigation, this seems to be due to my processor being a `Consumer`, not a `Function`. Changing it to a `Function` fixes the problem. I think it should work the same for a `Consumer`.

**Comment by olegz** [comment]
Well, it could not do the same for `Consumer` since Consumers by definition return void, so we have no reference to the passed Flux, which means you have to subscribe inside of the consumer manually.

**Comment by lbilger** [comment]
Yes, that's what we used to do - we had a `Consumer` that subscribed to the `Flux` passed in. I changed it now to a `Function<Flux<Message>, Mono<Void>>`, calling `then()` on the `Flux` as the last action instead of `subscribe()`. This seems to do the trick. Would this be your suggested solution?
If that is the case, it should at least be documented that reactive-style message processing doesn't work for `Consumer`s like it does for `Function`s.

**Comment by olegz** [comment]
Yeah as far as `then`. As for the docs it is documented in [SCF documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.1.RELEASE/reference/html/spring-cloud-function.html#_consumer), but i think you're right, we need to add something to the stream docs as well, so will do that
