### ISSUE TITLE
Add support for handling return types that are collection of Messages

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#1896]
Collection in this case implies anything (i.e., Flux, array, list etc).

This is different than a collection of non-Messages.
Collection of messages must be treated effectively as splitter where each item in a collection is an individual message to be sent out

But, collection of non-messages should be aggregated into a single payload (as it happens already)

**Comment by artembilan** [comment]
The point is to have a function signature like this `Function<?, Iterable<Message<?>>>`, where list could be a `Flux`, an array, `Stream` etc. In other words anything what could be treat as one-to-many.
In Spring Cloud Stream terms: I would like to consume one but produce many from my function.
Similar functionality exists already in Spring Integration - `AbstractMessageProducingHandler`:
```
protected void sendOutputs(Object result, Message<?> requestMessage) {
		if (result instanceof Iterable<?> && shouldSplitOutput((Iterable<?>) result)) {
			for (Object o : (Iterable<?>) result) {
				this.produceOutput(o, requestMessage);
			}
		}
		else if (result != null) {
			this.produceOutput(result, requestMessage);
		}
	}

	protected boolean shouldSplitOutput(Iterable<?> reply) {
		for (Object next : reply) {
			if (next instanceof Message<?> || next instanceof AbstractIntegrationMessageBuilder<?>) {
				return true;
			}
		}
		return false;
	}
```

But here in Spring Cloud Stream I think we can extract a generic type from the function signature during configuration phase.

See also issue which leads to unexpected behavior, but the premise is the same - one-to-many function: https://github.com/spring-cloud/spring-cloud-stream/issues/1885

**Comment by olegz** [comment]
The actual change is in SCF side, see https://github.com/spring-cloud/spring-cloud-function/commit/35d3c45959f543ec7476590d53b576bf847476f0
