### ISSUE TITLE
API docs link incorrectly redirects to the reference guide

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#1897]
As a user, while attempting to gain access to the SCSt's API Docs, clicking the API link redirects to the reference guide instead.

Go to `Learn`, click `API Doc` -> https://spring.io/projects/spring-cloud-stream#learn

In Spring projects, the API docs are usually available under https://docs.spring.io — somehow, the SCSt API docs (see: https://docs.spring.io/spring-cloud-stream/docs) aren't getting published since the Fishtown release. Where else do we stage them?

**Comment by olegz** [comment]
The issue was with our javadocs not being generated at all - https://github.com/maxcellent/javadoc.io/issues/36#issuecomment-583312540 and it was because we had things like `P#someMethod()..)` which is recognised by IDE but not by javadoc API
