### ISSUE TITLE
ApplicationJsonMessageMarshallingConverter fails to convert Message<List<Map<String,Object>>>

### ISSUE THREAD

**Issue by lperez2592** [spring-cloud/spring-cloud-stream#1898]
Encountered the following situation, which feels like a legit bug, when trying to use Spring Cloud Stream with function composition.

When `function A returns Message<List<Map<String,Object>>>, function B takes in Message<List<Map<String,Object>>> and both function A and B are classes that implement Function, using the following function composition` as a message handler:

```yml
spring.cloud.stream.function.definition: A|B
```

Will result in ApplicationJsonMessageMarshallingConverter failing to convert correctly the List<Map<String,Object>> payload in the Message.

Function B will receive Message<List<Map<String,Object>>>, but `all the elements of the payload list are null.`

Debugged the problem and the issue seems to be that: 
`ApplicationJsonMessageMarshallingConverter.convertFromInternal`
should probably not try to convert the payload  just as its base class overridden method:
`MappingJackson2MessageConverter.convertFromInternal`
does not, when it detects that target class is already the same as the payload class.

I have written a sample app that reproduces the issue and tries to pinpoint the above described through some function composition tests.
Please see: https://github.com/lperez2592/spring-cloud-stream-message-conversion-bug

**Comment by olegz** [comment]
We can't really go with the same approach as in `MappingJackson2MessageConverter` as it is too rudimentary and does not take into account generics and the fact that individual values in List/Map could themselves be of different type.

That said, I am about to push a fix that takes care of that.

**Comment by lperez2592** [comment]
Ahh I see. Your fallback is the right place to do it because of the reason you describe. 
Suggestion came from realizing that if you don't pass a ConversionHint, then the conversion delegates to the superclass overridden method. In that case the list does convert correctly as well. 
Thanks for the super quick response.
