### ISSUE TITLE
"Dispatcher has no subscribers for channel" when using reactive configuration

### ISSUE THREAD

**Issue by ErolPeel** [spring-cloud/spring-cloud-stream#1900]
We are using Spring Cloud Stream in a reactive manner. Our underlying implementation is Pub/Sub.

Our messaging configuration looks like this:
```
@Configuration
@RequiredArgsConstructor
public class MessagingConfiguration {

    private final SubscriptionService subscriptionService;

    @Bean
    public Function<Flux<WaypointStatusTransitionEventMessage>, Flux<NotificationMessage>> handleWaypointStatusTransitionEvent() {
        return waypointStatusTransitionEventFlux -> waypointStatusTransitionEventFlux.flatMap(waypointStatusTransitionEventMessage -> {
            return subscriptionService.handleWaypointStatusTransitionEvent(waypointStatusTransitionEventMessage.toDomain())
                    .map(NotificationMessage::fromDomain);
        });
    }

    @Bean
    public MessageConverter messageConverter(ObjectMapper objectMapper) {
        MappingJackson2MessageConverter converter = new MappingJackson2MessageConverter();
        converter.setObjectMapper(objectMapper);
        return converter;
    }

}
```

This our application.properties:
```
spring.cloud.stream.default-binder=pubsub
spring.cloud.stream.binding-retry-interval=0
spring.cloud.stream.bindings.wst.content-type=application/json
spring.cloud.stream.bindings.wst.destination=waypoint-status-transitions
spring.cloud.stream.bindings.wst.group=transport-notification-service
spring.cloud.stream.bindings.notifications.content-type=application/json
spring.cloud.stream.bindings.notifications.destination=notifications
spring.cloud.stream.function.bindings.handleWaypointStatusTransitionEvent-in-0=wst
spring.cloud.stream.function.bindings.handleWaypointStatusTransitionEvent-out-0=notifications
spring.cloud.function.definition=handleWaypointStatusTransitionEvent
```

We are encountering this repeatedly (every 100 ms or so) in our error log:
> 2020-01-31 10:53:05.806 ERROR 2691 --- [sub-subscriber2] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.wst'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[375], headers={spanParentSpanId=68b21b1b1ac8f2df, spanId=a3fef7b35ed2a533, spanTraceId=5e33c83418f77ec968b21b1b1ac8f2df, X-B3-SpanId=a3fef7b35ed2a533, X-B3-ParentSpanId=68b21b1b1ac8f2df, X-B3-Sampled=0, X-B3-TraceId=5e33c83418f77ec968b21b1b1ac8f2df, id=b27bce27-23cb-66b0-fd48-69bfd72a5b98, spanSampled=0, contentType=application/json, gcp_pubsub_original_message=PushedAcknowledgeablePubsubMessage{projectId='dev-eta-project', subscriptionName='waypoint-status-transitions.transport-notification-service', message=data: "{\n  \"waypointId\" : 347710,\n  \"newStatus\" : \"COMPLETED\",\n  \"reason\" : \"OVERDUE_COMPLETED\",\n  \"timestamp\" : \"2020-01-31T06:24:53.780685Z\",\n  \"trackingId\" : \"TEST-HaNdl\",\n  \"transportId\" : \"8cd8b9c1-bd0a-4dad-929f-9dd622243b6c\",\n  \"transportOwner\" : \"G3Ur7iu7\",\n  \"transportWaypointCount\" : 1,\n  \"waypointOrder\" : 0,\n  \"waypointCountryCode\" : \"AT\",\n  \"waypointCity\" : \"Vienna\"\n}"
> attributes {

All the Google hits to "Dispatcher has no subscribers for channel" haven't yet provided any solution for us. Do you know, how we can resolve this problem?

**Comment by olegz** [comment]
@ErolPeel can you please paste a full stack trace and provide more details? The exception simply means that your input destination (wst) is  not subscribed to. But that would not be a random/sporadic issue (as I believe you are eluding to). It would be rather binary subscribed or not and if not then why. Your description makes me believe that it works for some messages and not for others.

Also, why do you register `MappingJackson2MessageConverter` and setting `spring.cloud.stream.bindings.notifications.content-type=application/json` explicitly. We already pre-register json converter which extends from `MappingJackson2MessageConverter`. And as far as `content-type`, the `application/json` is the default. And while this may be harmless, I am wondering if there is something else that is registered/configured that we may not show.

In any event, the best thing you can do is create a small project with only essentials to reproduce the issue, something one of use can clone and diagnose as at the moment the reactive functionality is very well tested and all; test are passing and my initial attempt to reproduce the issue from your explanation is unsuccessful.

**Comment by ErolPeel** [comment]
> @ErolPeel can you please paste a full stack trace and provide more details? The exception simply means that your input destination (wst) is not subscribed to. But that would not be a random/sporadic issue (as I believe you are eluding to). It would be rather binary subscribed or not and if not then why. Your description makes me believe that it works for some messages and not for others.
> 
> Also, why do you register `MappingJackson2MessageConverter` and setting `spring.cloud.stream.bindings.notifications.content-type=application/json` explicitly. We already pre-register json converter which extends from `MappingJackson2MessageConverter`. And as far as `content-type`, the `application/json` is the default. And while this may be harmless, I am wondering if there is something else that is registered/configured that we may not show.
> 
> In any event, the best thing you can do is create a small project with only essentials to reproduce the issue, something one of use can clone and diagnose as at the moment the reactive functionality is very well tested and all; test are passing and my initial attempt to reproduce the issue from your explanation is unsuccessful.

We have solved the problem by now.

Every message that we processed caused an exception. After we fixed this, the above error no longer occurred.

About `MappingJackson2MessageConverter` and JSON: we did not know better so we registered it this way.

**Comment by PyAntony** [comment]
So how did you solve the problem? I am facing the same issue...
