### ISSUE TITLE
Function<Flux, Mono<Void>> requires an output destination

### ISSUE THREAD

**Issue by kschlesselmann** [spring-cloud/spring-cloud-stream#1911]
While trying to find a setup that doesn't overwhelm my reactive consumer with messages I stumbled upon #1891. I changed my `Consumer<Flux>` to `Function<Flux, Mono<Void>>` and ended up with
```
⠀WARN⠀[Producer clientId=producer-1] Error while fetching metadata with correlation id 2801 : {myFunction-out-0=UNKNOWN_TOPIC_OR_PARTITION}
```
To get everything up and running I configured an output destination `consumer-dump` which is a senseless topic. Is there a way to get the same setup without unnecessary infrastructure components?

**Comment by kschlesselmann** [comment]
@olegz In Gitter you mentioned a fix in Horsham.SR2 (3.0.2) which would use a _single_ `Flux` for all messages. If `limitRate` would work on this `Flux` wouldn't a `Consumer<Flux>` with manual `subscribe` in combination with `limitRate` be a better solution than this "pseudo `Function`"?

**Comment by olegz** [comment]
Sure, but that means the control of the stream is completely passed to the user, where with pseudo function it is still managed by the framework exposing further possibility for improvements and enhancements.

**Comment by kschlesselmann** [comment]
Yep, that's correct. As long as I don't have to configure something for a `Mono<Void>` output I'm fine with either solution :-)

**Comment by olegz** [comment]
No, you wouldn't have to. It would be recognised as Consumer from the signature, but in this case framework would be able to subscribe. That's actually the beauty of using *only* `Function` where Mono<Void> effectively represents a signal yet giving us (the framework) reference to the stream
