### ISSUE TITLE
Sleuth integration with EmitterProcessor is broken

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-stream#1913]
The snippet below shows the problem of not being able to pass the tracing information from the current thread in a non reactive application to the emitter processor. The processor changes threads and does not populate the new thread with tracing information.

```java
public void emitEvent(Event event) {
		emitterProcessor.ifAvailable(processor -> {
			// [Thread1] Thread Local -> traceId: 1
			log.info("Emitting event [{}]", event);
			processor.onNext(event); 
				// -> [Thread2]
		});
	}
```

**Comment by marcingrzejszczak** [comment]
Most likely doing this first https://github.com/spring-cloud/spring-cloud-stream/issues/1912 (by e.g. removing usage of `EmitterProcessor`) would fix things.

**Comment by olegz** [comment]
@marcingrzejszczak given that #1912 is addressed an you have an alternative mechanism, perhaps there is nothing to do here other then document that given nature of unpredictability of the threading model in the reactive API it is not friendly with Sleuth
