### ISSUE TITLE
Support partitioning properties for Gemfire binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#192]
Using these as a starting point, support the standard binder partitioning properties:

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-binders/spring-cloud-stream-binder-spi/src/main/java/org/springframework/cloud/stream/binder/BinderProperties.java#L69

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-binders/spring-cloud-stream-binder-spi/src/main/java/org/springframework/cloud/stream/binder/MessageChannelBinderSupport.java#L663

**Comment by pperalta** [comment]
Closed in favor of https://github.com/spring-cloud/spring-cloud-stream-binder-gemfire/issues/2
