### ISSUE TITLE
Add support for DLQ error handling within functional reactive programming model

### ISSUE THREAD

**Issue by mzalewski82** [spring-cloud/spring-cloud-stream#1922]
I think it's very similar to https://github.com/spring-cloud/spring-cloud-stream/issues/1729
As a base I used this example: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.3.RELEASE/reference/html/spring-cloud-stream.html#_dlq_dead_letter_queue
The problem I found:
```
@Bean
    public Function<String, String> uppercase() {
        throw new RuntimeException("intentional");
    }
```
is handling errors as expected, but
```
@Bean
    public Function<Flux<String>, Flux<String>> uppercase() {
        return flux -> flux.map(this::uppercase);
    }

    private String uppercase(String string) {
        throw new RuntimeException("intentional");
    }
```
does not. Message ends up in DLQ but, retry doesn't work and processing ends with an exception:
```
org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.uppercase-in-0'
```
All following messages will go directly to DQL without going through the stream declared in _uppercase_ method as it's not subscribed.

**Comment by olegz** [comment]
That would be quite difficult to do without causing side-effects. The major difference is understanding of the big difference between reactive and imperative functions. 

Imperative function gets invoked on each message, so the uint of processing within the imperative function is `Message`, hence any error handling or other concerns can be handled on per-message basis.

Reactive function gets invoked only once during the startup of the application context with Publisher representing the entire stream as input. So the unit of processing in reactive function is the entire stream. It is the user who handles individual messages indies reactive pipeline (e.g., `map(message ->{doSomething}`), but at that point it is completely outside of spring-cloud-stream control. On top of that reactive style is primarily used for advanced use cases where user may want to buffer, cache, window, merge aggregate etc. which now introduces the state and so on. So the expectations is that once chosen the reactive - you are in reactive world and thankfully the API is rich enough for you to handle errors, retries etc.

We're constantly looking at how to improve, but we need to make sure that any improvement does not affect other areas of the reactive API.

I'll keep the issue open for now to see if there is something else needs to be discussed, but as of now I do not forcee any action on it.

**Comment by mzalewski82** [comment]
Thanks for the comment. I agree that reactive world gives all the tools needed to handle errors, but I can see one possible action, please update docs to make clear how it behaves.

**Comment by raycheung** [comment]
I'm facing a similar issue. I understand the difference between imperative style and reactive style as mentioned, however I'm confused with the current error handling in reactive style.

In imperative style, as mentioned in the reference doc, Sprung would provide the `RetryTemplate` and such by default to reprocess the same message 3 times.

Whereas in reactive style, seems there is no similar mechanism. Especially when we do slightly more advanced operation, e.g. `flatMap()`, outputting `Tuple2<Flux, Flux>`, `retry()`, etc., the Kafka binder layer may not connect again after the Exception bubbles up to the Flux -- not to mention that Exception won't reach the DLQ as said above.

Is there any recommendation how to handle retry / error on the reactive style please? I'm eager to move on to the reactive style with all the powerful tools but lacking an integrated error handling would be the hurdle.

**Comment by ghahramani** [comment]
Same for me, I tried many cases; I searched a lot but no success, could you please provide a guidance or add it to the documentation how can we have retrying and dlq even if we have to handle it?

**Comment by kyleloomis** [comment]
Hi,

I came across this and a few other posts regarding this issue, but haven't been able to find a workaround. My particular issue has to do with deserialization exceptions. I have a reactive sink that accepts `TestNotification` messages as a serialized byte array. During normal operations, the sink receives well-formed data from a kafka topic, deserializes, then processes the message.

```
@Bean
fun testSink(): Function<Flux<TestNotification>, Mono<Void>> = Function { stream ->
    stream.flatMap {
        doSomething(it)
    }.onErrorResume {
        logger.error("Failure processing notification with error `${it.message}`")
        Mono.empty()
    }.then()
}
```

Whenever the data is not well-formed (cannot be deserialized to `TestNotification`), then an exception is thrown.

```
java.lang.IllegalArgumentException: Failed to convert input: GenericMessage [payload=byte[38], headers={kafka_offset=105, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@7ac57514, deliveryAttempt=1, kafka_timestampType=CREATE_TIME, kafka_receivedPartitionId=1, kafka_receivedTopic=test_sink, kafka_receivedTimestamp=1615949848318, contentType=application/json, kafka_groupId=test_sink}] to class com.test.notification.TestNotification
```

I have tried to implement a custom deserializer (extending `org.apache.kafka.common.serialization.Deserializer`) without much success; there doesn't seem to be a way to log and return no data. Given that there's no DLQ workaround, is there a way to override the deserializer, log and continue without throwing an exception? In order to fit into the reactive stream paradigm, I am thinking there could be a way to generically return `Mono.empty<T>()` or `Mono.just<T>(...)` depending on if the deserialization was successful or not.

Here is my attempt. Will use this as a temporary hack until I figure out a better way.

```

inline fun <reified T> Flux<ByteArray>.deserialize(): Flux<T> {
    return this.flatMap {
        try {
            Mono.fromCallable {
                val r: T = objectMapper.readValue(it.byteToString(), T::class.java) // cannot use `.readValue<T>(...) due to Kotlin type erasure

                r
            }.onErrorResume {
                Mono.empty()
            }
        } catch (e: Exception) {
            Mono.empty()
        }
    }
}


@Bean
fun testSink(): Function<Flux<ByteArray>, Mono<Void>> = Function { stream ->
    stream.deserialize<TestNotification>().flatMap {
        doSomething(it)
    }.onErrorResume {
        logger.error("Failure processing notification with error `${it.message}`")
        Mono.empty()
    }.then()
}
```

**Comment by ghahramani** [comment]
Hi @vishalmamidi,

I have implemented my own version of DLQ by using StreamBridge, basically, you need to implement the `onErrorNext `and send your message to DLQ via StreamBridge and then return `Mono.empty()`, just bear in mind you need to use `onErrorStop()` to prevent any strange behaviour with your up/down stream errors so it will make sure the error goes to `onErrorNext` not to `onErrorContinue`. Here is the code snippet I used

```
@Bean
    @ConditionalOnProperty("app.reader.writerTest.enabled", havingValue = "true", matchIfMissing = true)
    fun writerTest(
        streamBridge: StreamBridge,
        properties: AppProperties
    ) = Function<Flux<Message<TestReaderRequest>>, Mono<Void>> { item ->
        item
            .logSignal(logger, "reading writerTest message")
            .map {
                println("TEST: $it")
                it
            }
            .flatMap { request ->
                Mono
                    .just("Service Test")
                    .map {
                        throw Exception("Testing DLQ")
                    }
                    .handleDlq(request, streamBridge, logger, properties.messaging.retry.threshold)
            }
            .then()
    }

fun <T> Mono<T>.handleDlq(request: Message<*>, streamBridge: StreamBridge, logger: Logger, retryThreshold: Int = 1) =
    onErrorResume { exception -> handleDlq<T>(request, retryThreshold, streamBridge, logger, exception) }
        .onErrorStop()

fun <T> Flux<T>.handleDlq(request: Message<*>, streamBridge: StreamBridge, logger: Logger, retryThreshold: Int = 1) =
    onErrorResume { exception -> handleDlq<T>(request, retryThreshold, streamBridge, logger, exception) }
        .onErrorStop()

private fun <T> handleDlq(
    request: Message<*>,
    retryThreshold: Int,
    streamBridge: StreamBridge,
    logger: Logger,
    exception: Throwable
): Mono<T> {
    logger.error(
        "Unable to finish the operation of request: $request due to: ",
        exception
    )
    val receivedTopic = request.headers[RECEIVED_TOPIC]
    val attempts = request.headers[DELIVERY_ATTEMPT, AtomicInteger::class.java] ?: AtomicInteger(1)
    val topic = if (attempts.get() < retryThreshold) {
        attempts.incrementAndGet()
        logger.info("About to retry the message of $request for topic: $receivedTopic, attempt #${attempts.get()} from $retryThreshold")
        receivedTopic.toString()
    } else {
        // TODO: needs to find the dlq name from application.yml
        val dlq = receivedTopic.toString() + "-dlq"
        logger.info("About to send the message of $request to dlq: $dlq after retrying ${attempts.get()} time(s)")
        dlq
    }
    val message = MessageBuilder
        .fromMessage(request)
        .setHeaders(buildRetryOrDlqMessageHeaders(request, attempts, topic, exception))
        .build()

    streamBridge.send(topic, message)
    return Mono.empty()
}

private fun buildRetryOrDlqMessageHeaders(
    request: Message<*>,
    attempts: AtomicInteger,
    topic: String,
    exception: Throwable
): MessageHeaderAccessor {
    val messageHeaders = MessageHeaderAccessor(request)

    messageHeaders.setHeader("spring.cloud.stream.sendto.destination", topic)
    messageHeaders.setHeader(DELIVERY_ATTEMPT, attempts)
    messageHeaders.setHeader(DLT_ORIGINAL_TOPIC, request.headers[RECEIVED_TOPIC])
    messageHeaders.setHeader(DLT_EXCEPTION_FQCN, exception.javaClass.name)
    messageHeaders.setHeader(DLT_EXCEPTION_MESSAGE, exception.message)
    messageHeaders.setHeader(DLT_EXCEPTION_STACKTRACE, exception.stackTraceToString())

    return messageHeaders
}
```

Let me know if you have any questions, hope it helps

**Comment by olegz** [comment]
We will not be able to do it since in reactive programming spring-cloud-stream has nothing to do with the actual stream. We are not even handling it. Remember that unlike imperative function that is a message handler and gets invoked by the framework on each message, reactive function is initialization function. It is executed only once during initialization and from that point it's all in the hands of reactive API.

**Comment by ghahramani** [comment]
I am not sure if the statement is fully correct, I understand the initialization is only once in the framework but I do understand that you can handle the error with onErrorContinue and onErrorResume and other function with similar behaviour and change the whole stream flow in the framework and if someone wants to override it they can do it with onErrorStop and other function that is provided for the purpose, so the imperative function handling might be easier but it is not impossible for framework to handle the reactive stream

**Comment by AbdulZafar-Smarsh** [comment]
Any updates on having an implicit DLQ functionality support for reactive frameworks?

**Comment by sobychacko** [comment]
See this comment here: https://github.com/spring-cloud/spring-cloud-stream/pull/1730#issuecomment-1910536341
