### ISSUE TITLE
Cannot test Spring Cloud Stream Batch Mode using spring-cloud-stream-test-support and Spring Cloud Contract

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-stream#1925]
Hi,

this might be a cross Spring Cloud Contract and Spring Cloud Stream bug but thought I would start here.

In a nutshell I cannot test spring cloud stream batch mode via spring-cloud-stream-test-support where I have two problems

- Batchmode always expects an array which does not play nice with spring cloud contract.
- Acknowledgement is always null.

If you look at my project https://github.com/davidmelia/spring-cloud-function-examples.git which is a Spring Cloud Stream project which accepts FX Rate Events.  I have set this up in batch mode and none batch mode to simulate the bug.  **SpringCloudContractKafkaIssuesTest** is the main test which contains the bugs.

**Bug 1: Array marshalling problem when testing Spring Cloud Stream, in batch mode**

_should_send_an_avro_fx_rate_batch_event.groovy_ represents the publisher contract which always emits a single FX Rate Event.   This poses a problem in that spring cloud stream, in batch mode, seems to get confused and expects an array - see _SpringCloudContractKafkaIssuesTest.testAvroFxRateBatchEvent_FailsBecauseBatchExpectsAnArrayButEventsArePublishedIndividually_

You can get around this by changing the contract to emit an array but this is wrong as the event is a single object.  See  _SpringCloudContractKafkaIssuesTest.testAvroFxRateBatchEvent_SpoofyTheContractSoItEmitsAnArrayWhichIsWrongButThenGetAckIsNull_ for the hack 

**Bug 2: Acknowledgement is always null**
_SpringCloudContractKafkaIssuesTest.testAvroFxRateEvent_FailsBecauseAckIsNull_ illustrates that, when testing, acknowledgement is alway null.   Is this a bug or how would I simulate this in my test?

Thanks

**Comment by olegz** [comment]
yes, test-support module is living its last days, we are considering deprecating as we have a better testing support which is effectively a whole new test binder with the goal of supporting binder's core functionality. Please see [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.3.RELEASE/reference/html/spring-cloud-stream.html#_testing) and refactor your tests and let us know if you still have issues

**Comment by davidmelia** [comment]
Hi, I've created a new branch https://github.com/davidmelia/spring-cloud-function-examples/tree/SpringIntegrationTestBinder with the new binder but still struggling to get this to play nice.  I get the array deserialize issue but also a new behaviour is stubTrigger.trigger used to block but now doesn't.  (see SpringCloudContractKafkaIssuesTest)

How does spring cloud contract stub runner and this new test binder play together?

Thanks

**Comment by olegz** [comment]
Please remove
```
dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
```
There is more about it [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.3.RELEASE/reference/html/spring-cloud-stream.html#_testing)

**Comment by davidmelia** [comment]
@olegz I assume you mean comment out
```
 <!--       <dependency>
           <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-support</artifactId>
            <scope>test</scope>
       </dependency>	 -->	
```

which I have already done in my branch.

**Comment by olegz** [comment]
yes, corect. sorry

**Comment by olegz** [comment]
Closing it due to inactivity
