### ISSUE TITLE
Option for ignoring messages

### ISSUE THREAD

**Issue by marinkreso95** [spring-cloud/spring-cloud-stream#1926]
Let's say I have some consumer that reads messages from a stream in which is ingested a vast number of messages per second. I want to consume only a subset of these messages, e.g. every 100th message or one message in 10 minutes. 

Is there some option in this library to achieve this?

**Comment by olegz** [comment]
For the future when asking question pease use our dedicated [stack-overflow channel](https://stackoverflow.com/tags/spring-cloud-stream) as it is better servers the greater community.

That said, yes you can do that using reactive API by using one of the `skip` operations
Something like:
```
@Bean
public Function<Flux<String>, Flux<String>> uppercaseTenthMessage() {
     return flux -> flux.skip...
}
```
