### ISSUE TITLE
routing-key-expression for default producer property gets exception on application startup

### ISSUE THREAD

**Issue by canayozel** [spring-cloud/spring-cloud-stream#1927]
Why:
To be able to set a routing-key-expression to all producers in the application.
When:
add the following propert to applciation.properties
`spring.cloud.stream.rabbit.default.producer.routing-key-expression=headers.routingKey`
Expected:
  sets the routing-key-expression to all producers in the application.
Actual:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.stream.rabbit.default.producer.routing-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.rabbit.default.producer.routing-key-expression
    Value: headers.routingKey
    Origin: class path resource [application.properties]:37:68
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]
```

**Comment by olegz** [comment]
What version of spring-cloud-stream you are using?

**Comment by canayozel** [comment]
Sorry I forgot to put it there 
3.0.1.RELEASE 

The one included in spring-coud Hoxton.SR1.

**Comment by olegz** [comment]
FWIW can you upgrade to Hoxton SR3?
Meanwhile I'll take a look

**Comment by canayozel** [comment]
Thanks, I cannot upgrade to Hoxton SR3 ath this moment, because of a classpath problem.
```
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.gcp.security.firebase.FirebaseTokenValidator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 31 common frames omitted
```

**Comment by canayozel** [comment]
Just an update the case is also reproducible for non-default definitions when used such as 
headers.['routing-key']

**Comment by olegz** [comment]
Similar to #1932 this only happens in multiple binder or environment customisation scenarios due to not linking parent/child context between the app and the binder.
