### ISSUE TITLE
Add TAP support for Rabbit binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#193]
As a user, I'd like to *tap* the primary pipeline, so I can fork the same data and do some ad-hoc analysis without impacting the original stream.

For background and design notes, please refer to [XD-3519](https://jira.spring.io/browse/XD-3519)

**Comment by spencergibb** [comment]
@garyrussell mentioned that #190 would be fixed as part of this.
