### ISSUE TITLE
Spring Cloud Streams Supplier NOT Converting Java List or Array types into JSON Array

### ISSUE THREAD

**Issue by jschabowsky** [spring-cloud/spring-cloud-stream#1944]
Version: Hoxton.SR3
Problem Statement: 
Data format must contain a top level array per provided JSON Schema document. Items in the array are formed by POJO. Jackson allows this to be done by either: 
1) POJO[] - Array option
2) List<POJO> - Java Collections
3) Class that extends ArrayList<POJO> 

Data Example That Conforms to Schema: 
[{
  "posNeg" : 38,
  "notes" : "Please stop using the \"total\" field. Use \"totalTestResults\" instead.",
  "death" : 2,
  "pending" : 9,
  "hospitalizedCurrently" : null,
  "lastUpdateEt" : "4/08 00:00",
  "negativeScore" : null,
  "onVentilatorCumulative" : null,
  "hospitalized" : null,
  "score" : null,
  "negative" : 27,
  "total" : 47,
  "commercialScore" : null,
  "hospitalizedCumulative" : null,
  "positiveScore" : null,
  "inIcuCumulative" : null,
  "state" : "MP",
  "totalTestResults" : 38,
  "inIcuCurrently" : null,
  "checkTimeEt" : "4/08 09:00",
  "dateChecked" : "2020-04-08T13:00:00Z",
  "negativeRegularScore" : null,
  "fips" : "69",
  "onVentilatorCurrently" : null,
  "dateModified" : "2020-04-08T04:00:00Z",
  "positive" : 11,
  "recovered" : null,
  "grade" : null,
  "hash" : "fc4064365adad098b07d74713760ce03285637a3"
}, {
  "posNeg" : 287,
  "notes" : "Please stop using the \"total\" field. Use \"totalTestResults\" instead.",
  "death" : 1,
  "pending" : 35,
  "hospitalizedCurrently" : null,
  "lastUpdateEt" : "4/07 19:00",
  "negativeScore" : null,
  "onVentilatorCumulative" : null,
  "hospitalized" : null,
  "score" : null,
  "negative" : 242,
  "total" : 322,
  "commercialScore" : null,
  "hospitalizedCumulative" : null,
  "positiveScore" : null,
  "inIcuCumulative" : null,
  "state" : "VI",
  "totalTestResults" : 287,
  "inIcuCurrently" : null,
  "checkTimeEt" : "4/07 22:49",
  "dateChecked" : "2020-04-08T02:49:00Z",
  "negativeRegularScore" : null,
  "fips" : "78",
  "onVentilatorCurrently" : null,
  "dateModified" : "2020-04-07T23:00:00Z",
  "positive" : 45,
  "recovered" : 39,
  "grade" : null,
  "hash" : "774495bea74b59747d36e874a53d7fb231dca678"
} ]

Have had a method signature of: 
    public Supplier<List<POJO>> retrieveAndPublish() { }
    public Supplier<POJO[]> retrieveAndPublish() {}
    public Supplier <POJOList> retrieveAndPublish() {} (Where POJOList extends ArrayList<POJO>
   All above have content-type: application/json in bindings file. 
 
All of those options results in:
[{"payload":"eyJwb3NOZWciOjY5MTMsIm5vdGVzIjoiUGxlYXNlIHN0b3AgdXNpbmcgdGhlIFwidG90YWxcIiBmaWVsZC4gVXNlIFwidG90YWxUZXN0UmVzdWx0c1wiIGluc3RlYWQuIiwiZGVhdGgiOjYsInBlbmRpbmciOm51bGwsImhvc3BpdGFsaXplZEN1cnJlbnRseSI6bnVsbCwibGFzdFVwZGF0ZUV0IjoiNC8wNyAxNToxNSIsIm5lZ2F0aXZlU2NvcmUiOjEsIm9uVmVudGlsYXRvckN1bXVsYXRpdmUiOm51bGwsImhvc3BpdGFsaXplZCI6MjMsInNjb3JlIjo0LCJuZWdhdGl2ZSI6NjcwMCwidG90YWwiOjY5MTMsImNvbW1lcmNpYWxTY29yZSI6MSwiaG9zcGl0YWxpemVkQ3VtdWxhdGl2ZSI6MjMsInBvc2l0aXZlU2NvcmUiOjEsImluSWN1Q3VtdWxhdGl2ZSI6bnVsbCwic3RhdGUiOiJBSyIsInRvdGFsVGVzdFJlc3VsdHMiOjY5MTMsImluSWN1Q3VycmVudGx5IjpudWxsLCJjaGVja1RpbWVFdCI6IjQvMDcgMTU6MzEiLCJkYXRlQ2hlY2tlZCI6IjIwMjAtMDQtMDdUMTk6MzE6MDBaIiwibmVnYXRpdmVSZWd1bGFyU2NvcmUiOjEsImZpcHMiOiIwMiIsIm9uVmVudGlsYXRvckN1cnJlbnRseSI6bnVsbCwiZGF0ZU1vZGlmaWVkIjoiMjAyMC0wNC0wN1QxOToxNTowMFoiLCJwb3NpdGl2ZSI6MjEzLCJyZWNvdmVyZWQiOjI5LCJncmFkZSI6IkEiLCJoYXNoIjoiZjhlMjM4YjUxODI1ZmVlNzQxZDNlNWQyOTkwZTVmZGI5NzhlZDM0OCJ9","headers":{"contentType":{"type":"application","subtype":"json","parameters":{},"charset":null,"concrete":true,"wildcardSubtype":false,"wildcardType":false},"id":"82210d4e-0e18-eac4-dfaa-8b7439096d21","timestamp":1586372971936}},{"payload":"eyJwb3NOZWciOjE4OTgyLCJub3RlcyI6IlBsZWFzZSBzdG9wIHVzaW5nIHRoZSBcInRvdGFsXCIgZmllbGQuIFVzZSBcInRvdGFsVGVzdFJlc3VsdHNcIiBpbnN0ZWFkLiIsImRlYXRoIjo2NSwicGVuZGluZyI6bnVsbCwiaG9zcGl0YWxpemVkQ3VycmVudGx5IjpudWxsLCJsYXN0VXBkYXRlRXQiOiI0LzA4IDAwOjAwIiwibmVnYXRpdmVTY29yZSI6MSwib25WZW50aWxhdG9yQ3VtdWxhdGl2ZSI6bnVsbCwiaG9zcGl0YWxpemVkIjozMTQsInNjb3JlIjozLCJuZWdhdGl2ZSI6MTY3NTMsInRvdGFsIjoxODk4MiwiY29tbWVyY2lhbFNjb3JlIjoxLCJob3NwaXRhbGl6ZWRDdW11bGF0aXZlIjozMTQsInBvc2l0aXZlU2NvcmUiOjEsImluSWN1Q3VtdWxhdGl2ZSI6bnVsbCwic3RhdGUiOiJBTCIsInRvdGFsVGVzdFJlc3VsdHMiOjE4OTgyLCJpbkljdUN1cnJlbnRseSI6bnVsbCwiY2hlY2tUaW1lRXQiOiI0LzA4IDA5OjAyIiwiZGF0ZUNoZWNrZWQiOiIyMDIwLTA0LTA4VDEzOjAyOjAwWiIsIm5lZ2F0aXZlUmVndWxhclNjb3JlIjowLCJmaXBzIjoiMDEiLCJvblZlbnRpbGF0b3JDdXJyZW50bHkiOm51bGwsImRhdGVNb2RpZmllZCI6IjIwMjAtMDQtMDhUMDQ6MDA6MDBaIiwicG9zaXRpdmUiOjIyMjksInJlY292ZXJlZCI6bnVsbCwiZ3JhZGUiOiJCIiwiaGFzaCI6IjEwNWNmNDA4NWYxMTFiMGQ4YmNlNzU3OWZhMDMzNjM1MTllN2FhYTMifQ==","headers":{"contentType":{"type":"application","subtype":"json","parameters":{},"charset":null,"concrete":true,"wildcardSubtype":false,"wildcardType":false},"id":"a10ad195-49d8-e392-b2f3-6d2915714492","timestamp":1586372971936}}]

Meanwhile if I call objectMapper.writeValueAsString(POJO) it looks like the data snipped provided where its a Array of Objects that conform to the JSON Schema. Thus, the only way I have figured out to get it to work is to change the signature to: 
public Supplier<String> retrieveAndPublish() { }
and return objectMapper.writeValueAsString(POJO). 

Ironically, If I do the writeValueAsString option, and that data flowing across the wire is a json array, the following consumer WORKS: 
public Consumer<List<CovidTracking_StatesCurrentData>>splitAndPublish() {}

So the issue is, why is the supplier and consumer serialization/serialization not symmetrical?

**Comment by olegz** [comment]
Can you provide a code sample or at least revise the title and the description? I am honestly not following as to what is the issue. 
I mean what does it mean `Spring Cloud Streams Supplier and JSON Arrays being passed to Consumer`? What do you mean `serialization/serialization not symmetrical?`?

**Comment by jschabowsky** [comment]
Supplier: 

package com.solace.covidtracking.states;

@SpringBootApplication
public class Application {

    private static final Logger logger = LoggerFactory.getLogger(Application.class);
	private ObjectMapper objectMapper = new ObjectMapper();

    public static void main(String[] args) {
        SpringApplication.run(Application.class);
    }

    @Bean
    public Supplier<CovidTracking_StatesCurrentData> retrieveAndPublish() {
        // Add business logic here.
        return () -> {
            RestTemplate restTemplate = new RestTemplateBuilder().build();
            CovidTracking_StatesCurrentData parsedData = null;
            boolean error = true;
            String data = null;
            String result = null;
            logger.info("Making REST request to CovidData");
            data = restTemplate.getForObject("https://covidtracking.com/api/states", String.class);
			try{
				parsedData = objectMapper.readValue(data, CovidTracking_StatesCurrentData.class);
               // logger.info(objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(parsedData));
                result = objectMapper.writeValueAsString(parsedData);
			} catch (JsonProcessingException e) {
				logger.error("There was a problem parsing the response data: " + data);
				logger.error(e.getMessage());
			}

			return parsedData;

        };
    }

}

----------------------------------------------------
Object:

package com.solace.covidtracking.states;

public class CovidTracking_StatesCurrentData extends ArrayList<CovidTracking_StatesCurrentData.CovidTracking_StatesCurrentDataItems> {


    public static class CovidTracking_StatesCurrentDataItems {

        public CovidTracking_StatesCurrentDataItems() {
        }


        public CovidTracking_StatesCurrentDataItems(String notes, Integer posNeg, Integer death, Integer pending, Integer hospitalizedCurrently, String lastUpdateEt, Integer negativeScore, Integer onVentilatorCumulative, Integer hospitalized, Integer score, Integer negative, Integer total, Integer commercialScore, Integer hospitalizedCumulative, Integer positiveScore, Integer inIcuCumulative, String state, Integer totalTestResults, Integer inIcuCurrently, String checkTimeEt, String dateChecked, Integer negativeRegularScore, String fips, Integer onVentilatorCurrently, String dateModified, Integer positive, Integer recovered, String grade, String hash) {
            this.posNeg = posNeg;
            this.notes = notes;
            this.death = death;
            this.pending = pending;
            this.hospitalizedCurrently = hospitalizedCurrently;
            this.lastUpdateEt = lastUpdateEt;
            this.negativeScore = negativeScore;
            this.onVentilatorCumulative = onVentilatorCumulative;
            this.hospitalized = hospitalized;
            this.score = score;
            this.negative = negative;
            this.total = total;
            this.commercialScore = commercialScore;
            this.hospitalizedCumulative = hospitalizedCumulative;
            this.positiveScore = positiveScore;
            this.inIcuCumulative = inIcuCumulative;
            this.state = state;
            this.totalTestResults = totalTestResults;
            this.inIcuCurrently = inIcuCurrently;
            this.checkTimeEt = checkTimeEt;
            this.dateChecked = dateChecked;
            this.negativeRegularScore = negativeRegularScore;
            this.fips = fips;
            this.onVentilatorCurrently = onVentilatorCurrently;
            this.dateModified = dateModified;
            this.positive = positive;
            this.recovered = recovered;
            this.grade = grade;
            this.hash = hash;
        }


        private Integer posNeg;
        private String notes;
        private Integer death;
        private Integer pending;
        private Integer hospitalizedCurrently;
        private String lastUpdateEt;
        private Integer negativeScore;
        private Integer onVentilatorCumulative;
        private Integer hospitalized;
        private Integer score;
        private Integer negative;
        private Integer total;
        private Integer commercialScore;
        private Integer hospitalizedCumulative;
        private Integer positiveScore;
        private Integer inIcuCumulative;
        private String state;
        private Integer totalTestResults;
        private Integer inIcuCurrently;
        private String checkTimeEt;
        private String dateChecked;
        private Integer negativeRegularScore;
        private String fips;
        private Integer onVentilatorCurrently;
        private String dateModified;
        private Integer positive;
        private Integer recovered;
        private String grade;
        private String hash;

        public Integer getPosNeg() {
            return posNeg;
        }

        public CovidTracking_StatesCurrentDataItems setPosNeg(Integer posNeg) {
            this.posNeg = posNeg;
            return this;
        }

        public String getNotes() {
            return notes;
        }

        public CovidTracking_StatesCurrentDataItems setNotes(String notes) {
            this.notes = notes;
            return this;
        }

        public Integer getDeath() {
            return death;
        }

        public CovidTracking_StatesCurrentDataItems setDeath(Integer death) {
            this.death = death;
            return this;
        }

        public Integer getPending() {
            return pending;
        }

        public CovidTracking_StatesCurrentDataItems setPending(Integer pending) {
            this.pending = pending;
            return this;
        }

        public Integer getHospitalizedCurrently() {
            return hospitalizedCurrently;
        }

        public CovidTracking_StatesCurrentDataItems setHospitalizedCurrently(Integer hospitalizedCurrently) {
            this.hospitalizedCurrently = hospitalizedCurrently;
            return this;
        }

        public String getLastUpdateEt() {
            return lastUpdateEt;
        }

        public CovidTracking_StatesCurrentDataItems setLastUpdateEt(String lastUpdateEt) {
            this.lastUpdateEt = lastUpdateEt;
            return this;
        }

        public Integer getNegativeScore() {
            return negativeScore;
        }

        public CovidTracking_StatesCurrentDataItems setNegativeScore(Integer negativeScore) {
            this.negativeScore = negativeScore;
            return this;
        }

        public Integer getOnVentilatorCumulative() {
            return onVentilatorCumulative;
        }

        public CovidTracking_StatesCurrentDataItems setOnVentilatorCumulative(Integer onVentilatorCumulative) {
            this.onVentilatorCumulative = onVentilatorCumulative;
            return this;
        }

        public Integer getHospitalized() {
            return hospitalized;
        }

        public CovidTracking_StatesCurrentDataItems setHospitalized(Integer hospitalized) {
            this.hospitalized = hospitalized;
            return this;
        }

        public Integer getScore() {
            return score;
        }

        public CovidTracking_StatesCurrentDataItems setScore(Integer score) {
            this.score = score;
            return this;
        }

        public Integer getNegative() {
            return negative;
        }

        public CovidTracking_StatesCurrentDataItems setNegative(Integer negative) {
            this.negative = negative;
            return this;
        }

        public Integer getTotal() {
            return total;
        }

        public CovidTracking_StatesCurrentDataItems setTotal(Integer total) {
            this.total = total;
            return this;
        }

        public Integer getCommercialScore() {
            return commercialScore;
        }

        public CovidTracking_StatesCurrentDataItems setCommercialScore(Integer commercialScore) {
            this.commercialScore = commercialScore;
            return this;
        }

        public Integer getHospitalizedCumulative() {
            return hospitalizedCumulative;
        }

        public CovidTracking_StatesCurrentDataItems setHospitalizedCumulative(Integer hospitalizedCumulative) {
            this.hospitalizedCumulative = hospitalizedCumulative;
            return this;
        }

        public Integer getPositiveScore() {
            return positiveScore;
        }

        public CovidTracking_StatesCurrentDataItems setPositiveScore(Integer positiveScore) {
            this.positiveScore = positiveScore;
            return this;
        }

        public Integer getInIcuCumulative() {
            return inIcuCumulative;
        }

        public CovidTracking_StatesCurrentDataItems setInIcuCumulative(Integer inIcuCumulative) {
            this.inIcuCumulative = inIcuCumulative;
            return this;
        }

        public String getState() {
            return state;
        }

        public CovidTracking_StatesCurrentDataItems setState(String state) {
            this.state = state;
            return this;
        }

        public Integer getTotalTestResults() {
            return totalTestResults;
        }

        public CovidTracking_StatesCurrentDataItems setTotalTestResults(Integer totalTestResults) {
            this.totalTestResults = totalTestResults;
            return this;
        }

        public Integer getInIcuCurrently() {
            return inIcuCurrently;
        }

        public CovidTracking_StatesCurrentDataItems setInIcuCurrently(Integer inIcuCurrently) {
            this.inIcuCurrently = inIcuCurrently;
            return this;
        }

        public String getCheckTimeEt() {
            return checkTimeEt;
        }

        public CovidTracking_StatesCurrentDataItems setCheckTimeEt(String checkTimeEt) {
            this.checkTimeEt = checkTimeEt;
            return this;
        }

        public String getDateChecked() {
            return dateChecked;
        }

        public CovidTracking_StatesCurrentDataItems setDateChecked(String dateChecked) {
            this.dateChecked = dateChecked;
            return this;
        }

        public Integer getNegativeRegularScore() {
            return negativeRegularScore;
        }

        public CovidTracking_StatesCurrentDataItems setNegativeRegularScore(Integer negativeRegularScore) {
            this.negativeRegularScore = negativeRegularScore;
            return this;
        }

        public String getFips() {
            return fips;
        }

        public CovidTracking_StatesCurrentDataItems setFips(String fips) {
            this.fips = fips;
            return this;
        }

        public Integer getOnVentilatorCurrently() {
            return onVentilatorCurrently;
        }

        public CovidTracking_StatesCurrentDataItems setOnVentilatorCurrently(Integer onVentilatorCurrently) {
            this.onVentilatorCurrently = onVentilatorCurrently;
            return this;
        }

        public String getDateModified() {
            return dateModified;
        }

        public CovidTracking_StatesCurrentDataItems setDateModified(String dateModified) {
            this.dateModified = dateModified;
            return this;
        }

        public Integer getPositive() {
            return positive;
        }

        public CovidTracking_StatesCurrentDataItems setPositive(Integer positive) {
            this.positive = positive;
            return this;
        }

        public Integer getRecovered() {
            return recovered;
        }

        public CovidTracking_StatesCurrentDataItems setRecovered(Integer recovered) {
            this.recovered = recovered;
            return this;
        }

        public String getGrade() {
            return grade;
        }

        public CovidTracking_StatesCurrentDataItems setGrade(String grade) {
            this.grade = grade;
            return this;
        }

        public String getHash() {
            return hash;
        }

        public CovidTracking_StatesCurrentDataItems setHash(String hash) {
            this.hash = hash;
            return this;
        }

        public String toString() {
            return "CovidTracking_StatesCurrentDataItems ["
                    + "posNeg: " + posNeg
                    + " notes: " + notes
                    + " death: " + death
                    + " pending: " + pending
                    + " hospitalizedCurrently: " + hospitalizedCurrently
                    + " lastUpdateEt: " + lastUpdateEt
                    + " negativeScore: " + negativeScore
                    + " onVentilatorCumulative: " + onVentilatorCumulative
                    + " hospitalized: " + hospitalized
                    + " score: " + score
                    + " negative: " + negative
                    + " total: " + total
                    + " commercialScore: " + commercialScore
                    + " hospitalizedCumulative: " + hospitalizedCumulative
                    + " positiveScore: " + positiveScore
                    + " inIcuCumulative: " + inIcuCumulative
                    + " state: " + state
                    + " totalTestResults: " + totalTestResults
                    + " inIcuCurrently: " + inIcuCurrently
                    + " checkTimeEt: " + checkTimeEt
                    + " dateChecked: " + dateChecked
                    + " negativeRegularScore: " + negativeRegularScore
                    + " fips: " + fips
                    + " onVentilatorCurrently: " + onVentilatorCurrently
                    + " dateModified: " + dateModified
                    + " positive: " + positive
                    + " recovered: " + recovered
                    + " grade: " + grade
                    + " hash: " + hash
                    + " ]";
        }
    }
}

**Comment by olegz** [comment]
Thank you, will take a look tomorrow

**Comment by jschabowsky** [comment]
> Can you provide a code sample or at least revise the title and the description? I am honestly not following as to what is the issue.
> I mean what does it mean `Spring Cloud Streams Supplier and JSON Arrays being passed to Consumer`? What do you mean `serialization/serialization not symmetrical?`?

Sorry there was a typo in the last one: I meant serialization/deserialization is not symmetrical in that a Consumer can take in the JSON and turn it into any of my three options (List, Array or Class that Extends Array List) But the supplier is unable to get any of those objects into an Array of JSON Objects.  Hope that clears it all up.

**Comment by martensa** [comment]
Hi, 
I am facing the same issue. I am trying to use a supplier in order to get a List of POJOs deserialized into an array of JSON objects, but I get the same result as Jonathan.
The described workaround works for me, just returning the byte array directly. Would be great if this can be fixed somehow.

**Comment by olegz** [comment]
This has actually been addressed as part of another fix a bit earlier. So I would suggest upgrading to Hoxton.SR5.
In any event I just added a test for this specific case as part of this issue.
