### ISSUE TITLE
"Unknown type for contentType header value" after updating kafka binder version from 2.2.1 to 3.0.3

### ISSUE THREAD

**Issue by amitgupta9501** [spring-cloud/spring-cloud-stream#1947]
I have updated kafka binder version from 2.2.1 to 3.0.3 ('org.springframework.cloud:spring-cloud-stream-binder-kafka:3.0.3.RELEASE') in producer service. Consumer service is using kafka binder version 2.2.1
When producer is producing event to consumer then it gives below error at consumer side
ERROR:
"org.springframework.messaging.MessageDeliveryException: Dispatcher failed to deliver Message; nested exception is java.lang.IllegalArgumentException: Unknown type for contentType header value: class" error

as kafka binder changes are not backward compatible. I got solution mentioned in below issue

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/863

and made changes in my consumer service given in below PR, its works for me

https://github.com/spring-cloud/spring-cloud-stream/commit/81755865c8b5c172104a61261d6d940d25b7eecd

Can anyone suggest this kind of changes for producer side, Because I don't want update any code in consumer side.

Thanks in Advance...

**Comment by sobychacko** [comment]
@amitgupta9501 The relevant changes have gone to Spring Cloud Stream only after `3.0.3.RELEASE`. Did you try the latest snapshot? (`3.0.4.BUILD-SNAPSHOT`)

**Comment by amitgupta9501** [comment]
@sobychacko Thanks for your reply

I have tried with below snapshot in my producer service.
'org.springframework.cloud:spring-cloud-stream-binder-kafka:3.0.4.BUILD-SNAPSHOT'

I am still getting same error.

**Comment by sobychacko** [comment]
@amitgupta9501 We will take a look.

**Comment by amitgupta9501** [comment]
Hi @sobychacko 

I have also tried with 3.0.5.BUILD-SNAPSHOT in my producer service and still getting same error.

**Comment by olegz** [comment]
You must provide a reproducible sample/test. We have tests for it and several users have confirmed the fix, so it must be something else , but until we're able to reproduce there is no issue.

**Comment by sabbyanandan** [comment]
This has been already addressed in Spring Cloud Function. @olegz will share the link to the commit.
