### ISSUE TITLE
Reactive producer canceled subscriber

### ISSUE THREAD

**Issue by aleksandrmarchuk** [spring-cloud/spring-cloud-stream#1951]
**Is your feature request related to a problem? Please describe.**
Yes it related to a problem. During use of reactive functions producer i've faced with message conversion issue and noticed that once one of the messages fail conversion we no longer able to produce new messages since there is no active subscribers on EmitterProcessor
For message producing used this approach https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.4.RELEASE/reference/html/spring-cloud-stream.html#_using_reactor_api 

**Describe the solution you'd like**
ability to avoid stopping of producer after 1 invalid message

**Describe alternatives you've considered**
onError... reactor API methods doesn't help as conversion done within library flux stream

**Additional context**
here is just sample app which intentionally fails for conversion step to reproduce the problem with canceled subscribers for EmitterProcessor
https://github.com/aleksandrmarchuk/spring-cloud-function-producer-demo

**Comment by olegz** [comment]
This issue may have been neglected by us and now 3.1 is at EOL. Lot's of changes and improvements went into 3.2.x, so please upgrade and if problem persists please raise a new issue.
