### ISSUE TITLE
num.stream.threads not taking effect

### ISSUE THREAD

**Issue by sam-browne** [spring-cloud/spring-cloud-stream#1959]
Spring Cloud streams project processing a Kafka topic with multiple partitions for high throughput. Previously on Hoxton.RELEASE then migrated to Hoxton.SR3.

App configured with single input and output topic:

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              num.stream.threads: 5

Yet upon startup logging shows

2020.05.12T04:57:43.472-0500 [logLvl=INFO] [thr=main ctgy='org.apache.kafka.streams.StreamsConfig'] [TraceID=, SpanID=] - StreamsConfig values: 
	num.stream.threads = 1

And throughput obviously severely reduced.

Needed to specifically add

      bindings:
        input:
          consumer:
            concurrency: 5

To trigger correct logging/initialisation of:

2020.05.12T04:59:42.416-0500 [logLvl=INFO] [thr=main ctgy='org.apache.kafka.streams.StreamsConfig'] [TraceID=, SpanID=] - StreamsConfig values: 
	num.stream.threads = 5

Wondering if it relates to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/845/commits/1cc50c1a40d1d01843746cc8b55e5db362b81faf

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-kafka #899](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/899) via [**ZenHub**](https://www.zenhub.com/)
