### ISSUE TITLE
Configuration which allows to disable cloud stream

### ISSUE THREAD

**Issue by revoorunischal** [spring-cloud/spring-cloud-stream#1962]
I have a spring boot application which has two functionalities Http requests and kafka Messages handling. I want this application to run in mode which is enabled from application.yml i.e if the user wants to enable it only for http requests then kafka should not be connected.

I could achieve this using normal spring boot kafka plugin by disabling auto configure using the following property at @KafkaListener,

> autoStartup="${module.put:false}"

Now we are trying to move to cloud stream and the only way I found to disable it by removing the libraries of cloud stream and binder. Is there any better way to disable it using properties with auto config mode or is there any manual config option available?

**Comment by olegz** [comment]
Sorry, but O am struggling with the concept you are describing. You are effectively bringing spring-cloud-stream auto-configuration , but then also saying you have no intention on using it. IMHO, it goes counter to both spring-boot semantics as well as the concept of microservices. 
Sure I understand your motivation (code reusability etc), but it would be just as easy to package several applications of different distinct flavors as opposed to one with many flavors and control it via yaml file. 

This approach may also lead to potential class-path collisions when same dependent libraries of different versions are brought by two different core components (e.g., stream and http). In this case even if you disable a particular flavor such dependent libraries may still bring you issues

**Comment by revoorunischal** [comment]
The main advantage of this as you said code reusability and also code maintainability. 

With this approach the scalability of the application could be easier without modifying much. Like the same application can be brought up with 3 instances of both and 2 extra instances to support high load of http request.

I agree with you regarding the path collision. But, since we have modular structure we are able to manage the version mis match by providing the latest versions.

**Comment by AmosWang0626** [comment]
Me too, I hope to solve this problem by excluding automatic configuration.

E.g. @SpringBootApplication(exclude = {XxxxAutoConfiguration.class})

**Comment by sabbyanandan** [comment]
Hi, folks. Spring Cloud Stream is a framework that attempts to provide the scaffolding to build message-driven microservices rapidly. And, it brings the production-ready characteristics out-of-the-box to make the application run resiliently in various deployment platforms and with a message broker of choice. 

While there're options to mix SCSt with other responsibilities such as exposing RESTful endpoints in the same application, having to disable the SCSt's auto-configuration (i.e., the core value proposition of the framework) to make the other functional bits in the same application work, seems like a smell.

Besides that, there's going to be anomalies like the classpath collision that @olegz is referring to.
