### ISSUE TITLE
Add support for BeanDefinitionDsl based function scanning 

### ISSUE THREAD

**Issue by banginji** [spring-cloud/spring-cloud-stream#1964]
**Describe the issue**
A spring boot application crashes with a BeanCreationException when a java.util.function.Supplier is specified with spring-context's BeanDefinitionDsl for Kotlin. The application ingests spring-cloud-streams and spring-kafka libraries

**To Reproduce**
Create a simple spring boot app and define a bean of return type java.util.function.Supplier using BeanDefinitionDsl

**Version of the framework**
spring-cloud-stream-3.0.4.RELEASE

**Expected behavior**
Application runs successfully and a Kafka consumer is able to read the data sent by the Supplier bean

**Additional context**
The application runs fine if the bean is setup in the traditional way of defining a config class annotated with `@Configuration` and a bean annotated with `@Bean`. The issue only occurs when the bean is defined using BeanDefinitionDsl

##### Code setup
```kotlin
@SpringBootApplication
class KafkaFnKtApplication

fun main(args: Array<String>) {
	runApplication<KafkaFnKtApplication>(*args) { addInitializers(beans()) }
}

fun beans() = beans {
	bean("uFunTopic") { Supplier { "Hello from functional supplier" } }
}
```

##### Issue
The issue occurs in the FunctionConfiguration#extractPollableAnnotation method where when it tries to instantiate the factoryMethod var using FactoryMetadata#getSources, the bean does not have any metadata for sources.

**Comment by olegz** [comment]
I believe this has been resolved indirectly a while back. Feel free to reopen this issue or raise a new one if that is not the case
