### ISSUE TITLE
TestSupportBinder problem with custom MessageConverter.

### ISSUE THREAD

**Issue by jlojosnegros** [spring-cloud/spring-cloud-stream#1970]
Hi, 

Updating from Springboot 2.1.x to 2.2.6 found a problem when using MessageCollector to test.

I was using KryoMessageConverter and found it was no more in the defaultConverters, so I created a new CustomConverter, but my tests still fails.

After some debugging I have found that, *while my CustomConverter is called to "serialize" the output message*, **It is not called to deserialize the message captured by MessageCollector**. 

When I send the message to the Kafka channel, the `InboundMessageConvertingInterceptor` added by `TestSupportBinder`, builds its `CompositeMessageConverterFactory` with no parameters, that is only with the default MessageConverters, and so, when tries to "deserialize" the message in the tests it fails to do so and raise an Exception because the payload is null.

Update: 
I have been modifying locally TestSupportBinder, InboundMessageConvertingInterceptor and CompositeMessageConverterFactory to receive a List<MessageConverter> parameter with the custom MessageConverter defined by user and it works .

**Comment by sabbyanandan** [comment]
Please refer to [testing-guide](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.6.RELEASE/reference/html/spring-cloud-stream.html#_testing) for more details. Thanks.
