### ISSUE TITLE
Deserialization-exception-handler: sendtodlq not working with Spring Boot 2.3.0.RELEASE

### ISSUE THREAD

**Issue by Elvendir94** [spring-cloud/spring-cloud-stream#1971]
Hi!
I'm using Spring Boot 2.3.0.RELEASE with spring-cloud-dependencies Hoxton.SR4
I've set my application properties like below:
![image](https://user-images.githubusercontent.com/18270670/82822142-92ecb400-9ea5-11ea-94c9-680161627661.png)

I can't start my application because of this error:
![image](https://user-images.githubusercontent.com/18270670/82822313-db0bd680-9ea5-11ea-8a26-9d6d8ed85043.png)

I can run this application with Spring Boot 2.2.7.RELEASE version and sendtodlq is working.

I've also raised an issue here: https://github.com/spring-projects/spring-boot/issues/21564

**Comment by olegz** [comment]
@Elvendir94 Hoxton.SR4 is not compatible with boot 2.3, But Hoxton.SR5 will be compatible with it and should be released very shortly (this week)
