### ISSUE TITLE
Dynamic output destination resolution header not resolving for reactive API

### ISSUE THREAD

**Issue by natraj09** [spring-cloud/spring-cloud-stream#1978]
**Describe the issue**
I am using Reactive API  with Kafka binder . 
As an alternate solution to this open issues https://github.com/spring-cloud/spring-cloud-stream/issues/1922#issuecomment-594369030.  I decided to use dynamic destination feature to implement retries . This  error handling approach with dynamic destination works fine with Imperative style , it doesn't seem to work the Reactive API

**Version**
Hoxton.SR5

**To Reproduce**

1. Run application here https://github.com/natraj09/spring-cloud-stream-playground/blob/retry/reactive-processor-kafka/src/main/java/reactive/kafka/ReactiveProcessorApplication.java

2. Hit the endpoint `http://localhost:8080` with any `url` payload
```
{
	"url": "www.google.com"
}
```

3. With Reactive API its not processing when the rest endpoint is hit even though there is an error thrown in the method and it enters the catch statement
```
@Bean
	public Function<Flux<Message<Map>>, Flux<Message<Map>>> testProcess() {
		return data -> data.flatMap(inbound -> {
			try {
				restTemplate.build().getForObject(inbound.getPayload().get("url").toString(), Object.class);
				return Mono.just(MessageBuilder.fromMessage(inbound).setHeader("spring.cloud.stream.sendto.destination", "rest-output").build());
			} catch (Exception e) {
				return Mono.just(MessageBuilder.fromMessage(inbound)
						.setHeader(X_RETRIES_HEADER, new Integer(0))
						.setHeader("spring.cloud.stream.sendto.destination", "rest-input-error").build());
			}
		});
	}
```

4. Uncomment the imperative method [testProcess](https://github.com/natraj09/spring-cloud-stream-playground/blob/retry/reactive-processor-kafka/src/main/java/reactive/kafka/ReactiveProcessorApplication.java#L72) . ReRun the application , dynamic destination is resolved. When you hit the endpoint you can see the output from the testSink consumer

```
@Bean
	public Function<Message<Map>, Message<Map>> testProcess() {
		return inbound -> {
			try {
				restTemplate.build().getForObject(inbound.getPayload().get("url").toString(), Object.class);
				return MessageBuilder.fromMessage(inbound).setHeader("spring.cloud.stream.sendto.destination", "rest-output").build();
			} catch (Exception e) {
				return MessageBuilder.fromMessage(inbound)
						.setHeader(X_RETRIES_HEADER, new Integer(0))
						.setHeader("spring.cloud.stream.sendto.destination", "rest-input-error").build();
			}
		};
	}

```

**Version of the framework**
Hoxton.SR5

**Expected behavior**
Reactive style should work as Imperative API for dynamic output destination

**Screenshots**

**Additional context**

**Comment by olegz** [comment]
This is not a bug, but the side-effect of using reactive API while maintaining the same set of assumptions as if it was imperative. 
I'll keep this issue open just as a reminder that we need to do a better job with documenting it, but here is the gist of it.

With imperative API the unit of work per function invocation is a single message. So the function is invoked per each message and if there is a failure the control is passed back to the error/retry handling mechanism. This is because the framework maintains full control of both the incoming messages and invocation of handlers (functions).

With reactive approach, the unit of processing is the entire stream. Your function gets invoked only once with the stream bound to (adapted) to a message listener container. This means that the entire control for retries, error handing etc is passed  to the reactive API, so assuming that the same logic you use in imperative method could render the same results inside of `map` or `flatMap` is wrong since control is never passed back to the framework. 

Yes reactive API does provide you with a lot of power and benefits, but at a cost of understanding this impedance missmatch and how to deal with it.

**Comment by natraj09** [comment]
@olegz I am handling the error on my side and adding the `spring.cloud.stream.sendto.destination` to the header. I would expect the message  listener container to honor the message and send it to the right destination.  Is this supported ?

**Comment by natraj09** [comment]
Wrote an even simpler application to verify the dynamic header based routing is not working for reactive API?  

```
package reactive.kafka;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

@SpringBootApplication
public class OddEvenApplication {

    private AtomicBoolean semaphore = new AtomicBoolean(true);

    public static void main(String[] args) {
        SpringApplication.run(OddEvenApplication.class, args);
    }

    @Bean
    public Supplier<String> supplier() {
        return () -> this.semaphore.getAndSet(!this.semaphore.get()) ? "odd" : "even";
    }

    @Bean
    public Function<Flux<Message<String>>, Flux<Message<String>>> processor() {
        return messageFlux -> messageFlux.flatMap(stringMessage -> {
            if(stringMessage.getPayload().equalsIgnoreCase("odd")) {
                return Mono.just(MessageBuilder.fromMessage(stringMessage)
                        .setHeader("spring.cloud.stream.sendto.destination", "odd").build());
            } else {
                return  Mono.just(MessageBuilder.fromMessage(stringMessage)
                        .setHeader("spring.cloud.stream.sendto.destination", "odd").build());
            }
        });
    }
    

    @Bean
    public Consumer<String> odd() {
        return message -> System.out.println(message);
    }

    @Bean
    public Consumer<String> even() {
        return message -> System.out.println(message);
    }

}
```

**Application Yaml**
```
spring:
  cloud:
    stream:
      function:
        definition: supplier;processor;even;odd
        routing:
          enabled: true
      bindings:
        supplier-out-0:
          destination: even-odd
        processor-in-0:
          destination: even-odd
          group: even-odd-group
        even-in-0:
          destination: even
          group: even-group
        odd-in-0:
          destination: odd
          group: odd-group
```

**Comment by olegz** [comment]
@natraj09 I see your point. Indeed that should work. Will take a look

**Comment by olegz** [comment]
This will be included in the next Horsham release which we'll do some time next week, You'l still use Hoxton.SR5 for the spring-cloud, but will override the stream dependency with
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream</artifactId>
    <version>3.0.6.RELEASE</version>
</dependency>
```

... once available
