### ISSUE TITLE
Consummer<Flux<..>> (spring function bean) can't be subscribed more than once

### ISSUE THREAD

**Issue by jonenst** [spring-cloud/spring-cloud-stream#1982]
**Describe the issue**
using a consumer that subscribes more than once, only the first subscription does something.

**To Reproduce**
```java
@Component("MyComponent")
public class MyComponent {

    @Bean
    public Consumer<Flux<String>> consumeNotification() {
        return flux -> {
              //send a message, onNext should be logged twice
              flux.log().subscribe();
              flux.log().subscribe();
        };
    }

}
```
**Version of the framework**
3.0.5

**Expected behavior**
Subscribing multiple times should work

**Additional context**
A workaround is to publish: 
```java

    @Bean
    public Consumer<Flux<String>> consumeNotification() {
        return flux -> {
            ConnectableFlux<String> c = flux.publish();    
             c.connect();
             c.log().subscribe();
             c.log().subscribe();
        };
    }
```
This is a bit silly because internally spring cloud stream already has a hot flux and turns it into a cold flux with ```Flux.defer( () - > Emitter.create())```   (in  FunctionConfiguration.java through ```IntegrationReactiveUtils.messageChannelToFlux(inputChannel)``` )

**Comment by olegz** [comment]
As you described this is an issue for [Spring Integration](https://github.com/spring-projects/spring-integration) project. Please raise it there.
Also, I am wondering what benefit would it provide even if it did work? I mean sure to have it work from pure API perspective is some argument. . . but in the context of messaging I am missing what value would you get out of it.
Anyway, we can continue that discussion once you regile the issue.
