### ISSUE TITLE
TestSupportBinder doesn't subscribe to user function producer

### ISSUE THREAD

**Issue by jonenst** [spring-cloud/spring-cloud-stream#1987]
🙅 "Please DO NOT Raise an Issue" Cases

**Describe the issue**
Use TestSupportBinder to make a unit test as per https://spring.io/blog/2017/10/24/how-to-test-spring-cloud-stream-applications-part-i

call your method that emits event on returned flux of the spring function bean.

The MessageCollector stays always empty.

Looking at the code, I see that a delaySubscription() is used and waiting for BindingCreatedEvent to be sent, but I don't see this in the testBinder (maybe because it's newer ??)

**Version of the framework** spring-cloud-stream-test-support:jar:3.0.3.RELEASE:test
[INFO] +- org.springframework.cloud:spring-cloud-stream:jar:3.0.3.RELEASE:compile

**Expected behavior**
**Screenshots**

**Additional context**

**Comment by sabbyanandan** [comment]
@jonenst: The `MessageCollector` has been deprecated in favor   "Spring Integration Test Binder"; please refer to the docs/sample on this topic [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/current/reference/html/spring-cloud-stream.html#_test_binder_usage).

**Comment by jonenst** [comment]
So can you reproduce my issue ? If it's totally broken, maybe add a note in the docs because "deprecated" makes it sound like it still works for basic cases.
