### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.cloud.stream.binder.rabbit.properties.RabbitConsumerProperties

### ISSUE THREAD

**Issue by smonasco** [spring-cloud/spring-cloud-stream#1990]
**Describe the issue**
I am trying to create a partitioned queue but with extended rabbit properties. However, I get a `Failed to create consumer binding` caused by the exception in the title.

**To Reproduce**
config like the following

```
spring:
  cloud:
    function:
      definition: receive
    stream:
      instanceCount: 2
      instanceIndexList:
        - 0
      bindings:
        receive-in-0:
          destination: destination
          group: group
          consumer:
            partitioned: true
     rabbit:
       bindings:
         receive-in-0:
           consumer:
             acknowledgeMode: MANUAL
```

**Version of the framework**
Hoxton.SR4
spring-cloud-stream/3.0.4.RELEASE
spring-cloud-stream-binder-rabbit/3.0.4.RELEASE

**Expected behavior**
My binding works,
I get a queue named something like `destination.group-0` bound to exchange destination
I don't get a ClassCastException causing binding to fail

**Screenshots**

**Additional context**

It appears, that to hit this case, something must be in `spring.cloud.stream.bindings.<channel>.consumer` and in `spring.cloud.stream.rabbit.bindings.channel.consumer` and the binding must have an instance index list and the input channel must not be an instanceof PollableSource.

This makes us hit https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java#L144 where we set the extension to empty string. Then we go into the following stack:

```
doProvisionConsumerDestination:228, RabbitExchangeQueueProvisioner (org.springframework.cloud.stream.binder.rabbit.provisioning)
provisionConsumerDestination:183, RabbitExchangeQueueProvisioner (org.springframework.cloud.stream.binder.rabbit.provisioning)
provisionConsumerDestination:74, RabbitExchangeQueueProvisioner (org.springframework.cloud.stream.binder.rabbit.provisioning)
doBindConsumer:402, AbstractMessageChannelBinder (org.springframework.cloud.stream.binder)
doBindConsumer:90, AbstractMessageChannelBinder (org.springframework.cloud.stream.binder)
bindConsumer:143, AbstractBinder (org.springframework.cloud.stream.binder)
doBindConsumer:169, BindingService (org.springframework.cloud.stream.binding)
bindConsumer:145, BindingService (org.springframework.cloud.stream.binding)
createAndBindInputs:112, AbstractBindableProxyFactory (org.springframework.cloud.stream.binding)
doStartWithBindable:58, InputBindingLifecycle (org.springframework.cloud.stream.binding)
accept:-1, 1686179143 (org.springframework.cloud.stream.binding.AbstractBindingLifecycle$$Lambda$921)
forEach:608, LinkedHashMap$LinkedValues (java.util)
start:57, AbstractBindingLifecycle (org.springframework.cloud.stream.binding)
start:34, InputBindingLifecycle (org.springframework.cloud.stream.binding)
doStart:182, DefaultLifecycleProcessor (org.springframework.context.support)
access$200:53, DefaultLifecycleProcessor (org.springframework.context.support)
start:360, DefaultLifecycleProcessor$LifecycleGroup (org.springframework.context.support)
startBeans:158, DefaultLifecycleProcessor (org.springframework.context.support)
onRefresh:122, DefaultLifecycleProcessor (org.springframework.context.support)
finishRefresh:894, AbstractApplicationContext (org.springframework.context.support)
refresh:553, AbstractApplicationContext (org.springframework.context.support)
refresh:62, ReactiveWebServerApplicationContext (org.springframework.boot.web.reactive.context)
refresh:758, SpringApplication (org.springframework.boot)
refresh:750, SpringApplication (org.springframework.boot)
refreshContext:397, SpringApplication (org.springframework.boot)
run:315, SpringApplication (org.springframework.boot)
run:1237, SpringApplication (org.springframework.boot)
run:1226, SpringApplication (org.springframework.boot)
main:30, AssetIndexerApplicationKt (com.levelsbeyond.elasticsearch)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
run:49, RestartLauncher (org.springframework.boot.devtools.restart) 
```

doProvisionConsumerDestination:228, RabbitExchangeQueueProvisioner (org.springframework.cloud.stream.binder.rabbit.provisioning) then tries `properties.getExtension().isQueueNameGroupOnly()` and the extension is an empty string which can't answer that question.

I'm guessing at https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java#L144 we could make a copy of the extension instead of using empty string, but testing that fun edge case seems a bit deep.

**Comment by smonasco** [comment]
@olegz is there a plan or eta on this?

**Comment by olegz** [comment]
@smonasco I believe this is no longer an issue. Can you please upgrade to 3.0.8.RELEASE of Spring Cloud Stream?

**Comment by smonasco** [comment]
my apologies for taking so long. I'll schedule getting to this.

**Comment by olegz** [comment]
I am going to close this for now as there were several releases since the original issue has been filed. Feel free to open a new issue

**Comment by matthewjmason** [comment]
I am pretty sure this is still an issue in the latest version: https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java#L148

If I set the instanceIndexList property on my consumer, it fails the if check here: https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java#L133 and drops into the problematic else condition on line 142. When, on line 148, ExtendedConsumerProperties is instantiated with a String there is a mismatch in type of the extension fields of consumerProperties (extension type RabbitConsumerProperties) consumerPropertiesTemp (extension type String). 

I think the fix is to change line 148 from:

`ConsumerProperties consumerPropertiesTemp = new ExtendedConsumerProperties<>("");` to `ConsumerProperties consumerPropertiesTemp = new ExtendedConsumerProperties<>(new RabbitConsumerProperties());` or something along that line.
