### ISSUE TITLE
Add "current" and "current-snapshot" redirects for the ref. guide

### ISSUE THREAD

**Issue by FWinkler79** [spring-cloud/spring-cloud-stream#1995]
I am reading the docs of [SCS 3.0.6](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.6.RELEASE/reference/html/spring-cloud-stream.html#spring-cloud-stream-overview-binders) and all image links seem to be broken. 

Would be great, if they could be fixed, as the images really help in understanding the documentation better.
Thanks!

**Comment by sabbyanandan** [comment]
This is difference between both the image URIs:

https://raw.githubusercontent.com/spring-cloud/spring-cloud-stream/master/docs/src/main/asciidoc/images/producers-consumers.png

https://raw.githubusercontent.com/spring-cloud/spring-cloud-stream/1.0.x/docs/src/main/asciidoc/images/producers-consumers.png

**Comment by FWinkler79** [comment]
Thanks, that's good to know.
Then I would suggest to update the link on this page which I guess a lot of people use to jump into the topic (at least I did):

https://spring.io/projects/spring-cloud-stream#learn

If you follow the link to `Horsham.SR6 [3.0.6 RELEASE] CURRENT GA` you end up with a URL that contains the actual version and not `current` and the images are missing.

**Comment by sobychacko** [comment]
This issue has been addressed. https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/
