### ISSUE TITLE
StreamBridge should check if the value being passed is Message before converting

### ISSUE THREAD

**Issue by D3jank** [spring-cloud/spring-cloud-stream#2007]
StreamBridge does not allow us to pass our own Message class thus we can not send a key nor custom headers to our kafka topics. We have useNativeEncoding set because we are using avro. In the StreamBridge function it skips conversion but calls MessageBuilder.

```
Function<Object, Object> functionToInvoke = skipConversion ? v -> MessageBuilder.withPayload(v).build() :
            this.functionCatalog.lookup(STREAM_BRIDGE_FUNC_NAME, outputContentType.toString());
```

Reason we are using StreamBridge is because we can set dynamic topics. Is it possible to modify the code to allow us to send the Message object? As mentioned by Gary on Gitter,  "if skipConversion is true, it should check to see if v is already a message".

Thanks!

**Comment by ddulaney** [comment]
Hello @olegz! Until this is fixed, is there a preferred way to produce a message (including key) from a REST endpoint?
