### ISSUE TITLE
Jackson-module-kotlin is not used automatically to de-serialize  kotlin classes 

### ISSUE THREAD

**Issue by tobske** [spring-cloud/spring-cloud-stream#2008]
**Describe the issue**
If you have jackson-module-kotlin on your classpath it gets automatically registered as described in [spring framework documentation](https://docs.spring.io/spring/docs/5.2.7.RELEASE/spring-framework-reference/languages.html#kotlin-classes-interfaces). The ObjectMapper with the registered kotlin module should then be used by Spring Cloud Stream to de-serialize incoming JSON but another ObjectMapper seems to be used. The ObjectMapper that is used gets constructed in `MappingJackson2MessageConverter::initObjectMapper`. The result is that a kotlin data class without any additional annotations can't be de-serialized successfully.

**To Reproduce**
1. Write a kotlin data class without any annotations
`data class Message(val header: String)`
2. Write functional consumer bean using that data class
```
@Bean
    fun messageConsumer(): Consumer<Message> {
        return Consumer { msg -> println(msg) }
    }
```
3. Send some valid JSON in a test to that consumer
```
    InputDestination inputDestination = context.getBean(InputDestination.class);
    inputDestination.send(new GenericMessage<>(data));
```
4. Receiving following error
`Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.aviatar.ebas.acms.AcmsMessage` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
`

**Version of the framework**
Hoxton.SR5 and 2.3.1.RELEASE

**Expected behavior**
Data class gets de-serialized without any further configuration.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-function #567](https://github.com/spring-cloud/spring-cloud-function/issues/567) via [**ZenHub**](https://www.zenhub.com/)
