### ISSUE TITLE
Please stop altering Logging behaviour.

### ISSUE THREAD

**Issue by Xyaren** [spring-cloud/spring-cloud-stream#2011]
https://github.com/spring-cloud/spring-cloud-stream/blob/b5a64eac1406369d21ae2281519caf08404555b5/spring-cloud-stream-binder-test/src/main/java/org/springframework/cloud/stream/binder/BinderTestEnvironmentPostProcessor.java#L41

This is unneccecary, and causes confusion.
I searched an hour, why my tests stop logging on anything below warn.

What is the purpose of this ?

**Comment by olegz** [comment]
Sure, we'll fix it, but also keep in mind that the test binder you are using is rather old, outdated and actually doesn't test much from the standpoint of the framework. We have switched long time ago to a new test binder  - https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.6.RELEASE/reference/html/spring-cloud-stream.html#spring_integration_test_binder
