### ISSUE TITLE
Add support for "Incremental Messaging"

### ISSUE THREAD

**Issue by amirmv2006** [spring-cloud/spring-cloud-stream#2016]
**Describe the issue**
In some cases, we want to be able to receive a message, process the message, add something to it, and then send the "incremented message" to the next node in a pipeline of handlers. Usually in cases like this, it's best if the next destination is read from the incoming message headers. An example would be "findUserByUsername". This request can come from different modules towards us, they are always trying to get the User for a given username, but their "request" might be different. The request could be an Order, in which case the result would be Order+User. It could be for a Payment, in which case the request would be for a Payment, and the result would be Payment+User.

**Additional context**
I have a [blog post](https://medium.com/@amirmv2006/how-about-request-reply-api-calls-in-messaging-7933fc069e50) explaining more about this. I think to achieve this, maybe we could add an accumulator function to each binding which will transform (incoming message + the result of business function) into => an outgoing message. Maybe something like this:
```java
  @Bean
  public Function<ObjectNode, ObjectNode> fillUserFn(UserService userService) {
    return jsonNodes -> jsonNodes.set("user", userService.getUserByUsername(jsonNodes.get("username").asText()));
  }

  @Bean
  public BiFunction<Message<ObjectNode>, Message<ObjectNode>, Message<ObjectNode>> accumulatorFn() {
    return (incomingReq, calculatedMsg) -> MessageBuilder.fromMessage(calculatedMsg)
        .setHeader("destination", incomingReq.getHeaders().get("destination"))
        .build();
  }
```
And in the binder configuration:
```yaml
spring:
  cloud:
    stream:
      bindings:
        fillUserFn-in-0:
          destination: fillUserDetails
          accumulator: accumulatorFn
```

**Comment by amirmv2006** [comment]
I'm willing to contribute to solving this issue if it is approved for spring cloud streams.

**Comment by olegz** [comment]
I believe we are already supporting this with dynamic destinations. You can read more about it [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.6.RELEASE/reference/html/spring-cloud-stream.html#_sending_arbitrary_data_to_an_output_e_g_foreign_event_driven_sources)

**Comment by amirmv2006** [comment]
thanks @olegz and apologies for missing out that one. I was using bad keywords for my google search 😅
