### ISSUE TITLE
Functional consumer can't support manual acknowledge

### ISSUE THREAD

**Issue by kaimeng110091** [spring-cloud/spring-cloud-stream#2018]
**Describe the issue**
Functional consumer can't support manual acknowledge when I'm setting the property: "spring.cloud.stream.rabbit.bindings.log-in-0.consumer.acknowledge-mode=MANUAL"

**To Reproduce**
1. rabbit binder
2. set property: spring.cloud.stream.rabbit.default.consumer.acknowledge-mode=MANUAL
3. `@Bean` with  Consumer<Message<Person>>
4. I can't manual acknowledge. 

**Version of the framework**
spring-cloud-stream Hoxton.SR8

**Additional context**
Delaying Messages is support?

**Comment by garyrussell** [comment]
>I can't manual acknowledge.

Please explain why. The channel and delivery tags are in the `Message<?>` headers.

(You need to consume a spring-messaging `Message<?>` not a Spring AMQP `Message`).

**Comment by kaimeng110091** [comment]
Thank you very much for that ! emmm, can I ask an other question? how can I get the current acknowledge-mode ? I want to  ack dynamically...

**Comment by kaimeng110091** [comment]
thank you very much again!
