### ISSUE TITLE
Pulsar Support

### ISSUE THREAD

**Issue by jabrena** [spring-cloud/spring-cloud-stream#2024]
Hi,

I would like to know if exist any plan to add support for `Apache Pulsar`
https://pulsar.apache.org/

Many thanks in advance

Juan Antonio

**Comment by yangle94** [comment]
+1

**Comment by hdsuperman** [comment]
+1

**Comment by rolkhas2** [comment]
For those who are interested - there's a great project that helps with [supporting Project Reactor & Pulsar as a binder for Spring Cloud Stream](https://github.com/lhotari/pulsar-spring-cloud-stream-binder).

**Comment by artembilan** [comment]
@rolkhas2 ,

there is probably some misunderstanding, but that Pulsar Spring Cloud Stream binder is not reactive.
Its channel adapter implementation, though, could really be used as an inspiration for Spring Integration Pulsar module: https://github.com/spring-projects/spring-integration/issues/3771

**Comment by sobychacko** [comment]
We now have support for Apache Pulsar in the Spring portfolio.
Here is the core library: https://github.com/spring-projects/spring-pulsar
Spring Cloud Stream Pulsar binder: https://github.com/spring-cloud/spring-cloud-stream/tree/main/binders/pulsar-binder
Any feedback is appreciated. Thank you!
