### ISSUE TITLE
Kafka key is not populated when using kafka-binding with Flux

### ISSUE THREAD

**Issue by rgonciarz** [spring-cloud/spring-cloud-stream#2030]
**Describe the issue**
Kafka key is not populated when using kafka-binding with Flux

```
    @Bean
    fun topologyR() = Function<Flux<String>,Flux<String>> {
        it.doOnNext { v -> log.info("topologyR: {}", v) }
    }
```

Setup:
topic1 -> topologyA (kafka streams binding) -> topic2 
topic2 -> topologyR (kafka flux binding) -> topic3
topic3 -> topologyB (kafka streams binding)

**To Reproduce**
I created a small project that may help to reproduce the issue:
https://github.com/rgonciarz/reactive-topology-chain/tree/reactive-function-no-avro](https://github.com/rgonciarz/reactive-topology-chain/tree/reactive-function-no-avro)

1. Run application, and either send a message on topic1 (String,String serialization) or use ApplicationKtTest 

Result:
```
2020-10-08 19:20:02.221  INFO 14232 --- [-StreamThread-1] wr.reactive.TopologyConfig               : topologyA: 9307f81e-7148-459e-a49a-e5aeb07cacac, 9307f81e-7148-459e-a49a-e5aeb07cacac
2020-10-08 19:20:02.324  INFO 14232 --- [container-0-C-1] wr.reactive.TopologyConfig               : topologyR: 9307f81e-7148-459e-a49a-e5aeb07cacac
2020-10-08 19:20:02.326  INFO 14232 --- [-StreamThread-1] wr.reactive.TopologyConfig               : topologyB: null, 9307f81e-7148-459e-a49a-e5aeb07cacac
```
We loose information about Kafka key. To workaround the problem we need to use Message abstraction and manually copy header from KafkaHeaders.RECEIVED_MESSAGE_KEY to KafkaHeaders.MESSAGE_KEY.

Affected version: Spring boot 2.3.3

**Comment by garyrussell** [comment]
The framework cannot make any assumption that the inbound key should be propagated to the outbound key.

Perhaps an option could be added, but your work around is the correct way to handle this currently.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-binder-kafka #972](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/972) via [**ZenHub**](https://www.zenhub.com/)
