### ISSUE TITLE
Spring Cloud Stream 3.0.0 not found consumers when is added SpringFox dependency

### ISSUE THREAD

**Issue by SrMouraSilva** [spring-cloud/spring-cloud-stream#2032]
**Describe the issue**

If I add SpringFox dependency in the project, Spring Cloud Stream not found the consumers (tested only with functional way, not with annotations). Sending messages work, but consuming, not. I don't know if this is a problem to the SpringFox team or the Spring Cloud Stream team. I added a issue in SpringFox project (https://github.com/springfox/springfox/issues/3591), but maybe the possibility that this lib is affected by other is an issue.

**To Reproduce**

1. Create a project with Spring boot, Spring Cloud Stream with Hoxton SR8 and `spring-cloud-stream-binder-rabbit`
2. Add some Consumer function
3. Start the server. You will see in the log that the consumer is configured
4. Now add `io.springfox:springfox-boot-starter:3.0.0` dependency
5. Start the server. You will see in the log that the consumer is not configured! Then it not receive messages :(

I prepared a test environment, you can see the in https://github.com/springfox/springfox/issues/3591 (section "Instructions")

**Version of the framework**
* Spring Cloud Stream: 3.0.0 (Hoxton.SR8)
* Spring Boot: 2.3.3 (Hoxton.SR8)
* SpringFox: 3.0.0

**Expected behavior**
That the Spring Cloud configure the consumers independently a buggy dependency

**Screenshots**

**Additional context**

**Comment by garyrussell** [comment]
This is because springfox registers a `Supplier` `@Bean`:

    inMemorySwaggerResourcesProvider=springfox.documentation.swagger.web.InMemorySwaggerResourcesProvider@4cad79bc

spring-cloud-stream can only work without configuration if exactly one `Function<?>`, `Consumer<?>` or `Supplier<?>` bean exists.

Since it can't disambiguate, no binding is implied.

You have to add the property `spring.cloud.function.definition=consumerMethodName`.

**Comment by SrMouraSilva** [comment]
Hello, @garyrussell. Thanks for the answer. 
When I define `spring.cloud.function.definition=consumerMethodName`, the project works.

Since in this type of situation there is no possibility of automatically discovering Consumers, would you have any recommendation when I have a project A that defines some consumers in its `application.yml` and a project B that extends A, but there will be other Consumers and it has its `application.yml` itself. How would it be possible to add Consumers by `spring.cloud.function.definition` in B without overwriting (and losing) those in A?

**Comment by olegz** [comment]
Given that Yaml or properties files meant to address configuration externalization if one project extends another i would strongly recommend agains some type of hierarchy of configuration files as it will cause more confusion with many other configuration properties. Keep a single configuration for a deployed project.
With regard to multiple functions you can use `;` delimiter in `definition` property. For example `spring.cloud.function.definition=foo;bar`

**Comment by siaron** [comment]
If you only use StreamBridge to produce data. How to configure?
