### ISSUE TITLE
Promote TestBinder as a standalone binder dependency

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#2039]
Currently, Spring Initializr is bootstrapping SCSt app with MessageCollector, and we don't want that to be the default since it is deprecated.

**Comment by olegz** [comment]
It appears that Spring Initializr have accepted our current approach - https://github.com/spring-io/start.spring.io/issues/385#event-3988597942. So I just need to double check and update documentation to completely remove references to an old binder

**Comment by olegz** [comment]
been done
