### ISSUE TITLE
Runtime error when upgrading to spring-boot 2.3.0 and spring-cloud to Hoxton.SR5

### ISSUE THREAD

**Issue by tambre** [spring-cloud/spring-cloud-stream#2044]
No issues during compilation. But during runtime getting the following error
***********************************
APPLICATION FAILED TO START
***********************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location: 
org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsBinderUtils.prepareConsumerBindings(KafkaStreamsBinderUtils.java:108)

the following method did not exist:

org.springframework.kafka.listener.DeadLetterPublishingRecoverer.i<init>(Lorg/springframework/kafka/core/KafkaTemplate;Ljava/util/function/BiFunction;)V

DeadLetterPublishingRecoverer is getting loaded from spring-kafka-2.5.0.RELEASE.jar

---------------
I think the spring-cloud-stream-binder-kafka-streams version is 3.0.5.RELEASE

**Comment by garyrussell** [comment]
This was fixed in Spring Kafka 2.5.1; the current Spring Boot 2.3.x version is 2.3.5.

**Comment by tambre** [comment]
Thanks @garyrussell - will check and update the issue.

**Comment by tambre** [comment]
It works. We can close this issue. Thanks.
