### ISSUE TITLE
Incompatibility spring boot 2.2.x and spring cloud Hoxton.SR9

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream#2047]
**Version of the framework**
Spring Boot 2.2.10.RELEASE
Spring Cloud Hoxton.SR9

**Describe the issue**
When starting a spring cloud stream application with Kafka it gives the following error:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
    org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.<init>(KafkaProducerMessageHandler.java:179)
The following method did not exist:
    'boolean org.springframework.kafka.core.KafkaTemplate.isAllowNonTransactional()'
The method's class, org.springframework.kafka.core.KafkaTemplate, is available from the following locations:
    jar:file:/C:/repositorios/org/springframework/kafka/spring-kafka/2.3.11.RELEASE/spring-kafka-2.3.11.RELEASE.jar!/org/springframework/kafka/core/KafkaTemplate.class
It was loaded from the following location:
    file:/C:/repositorios/org/springframework/kafka/spring-kafka/2.3.11.RELEASE/spring-kafka-2.3.11.RELEASE.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of org.springframework.kafka.core.KafkaTemplate
```
```
Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.NoSuchMethodError: 'boolean org.springframework.kafka.core.KafkaTemplate.isAllowNonTransactional()'
```

which version of spring-kafka is supported?

Attached demo application to reproduce the error.
[demo-stream-kafka.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5517171/demo-stream-kafka.zip)

**Comment by garyrussell** [comment]
To use this with Boot 2.2, you need to override boot's prescribed version of spring-kafka to 2.4.10 - see the [spring-kafka documentation](https://docs.spring.io/spring-kafka/docs/2.4.10.RELEASE/reference/html/#deps-for-24x).

**Comment by ferblaca** [comment]
Hi @garyrussell , thanks for responding so quickly.

I have configured the same project with spring kafka version 2.4.10.RELEASE and I still have the same problem...

### Config:
```
    <properties>
        <spring-cloud.version>Hoxton.SR9</spring-cloud.version>
        <spring-kafka.version>2.4.10.RELEASE</spring-kafka.version>
    </properties>
```

### Error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.determineSendTimeout(KafkaProducerMessageHandler.java:191)

The following method did not exist:

    'java.util.Map org.springframework.kafka.core.ProducerFactory.getConfigurationProperties()'

The method's class, org.springframework.kafka.core.ProducerFactory, is available from the following locations:

    jar:file:/C:/repositorios/org/springframework/kafka/spring-kafka/2.4.10.RELEASE/spring-kafka-2.4.10.RELEASE.jar!/org/springframework/kafka/core/ProducerFactory.class

It was loaded from the following location:

    file:/C:/repositorios/org/springframework/kafka/spring-kafka/2.4.10.RELEASE/spring-kafka-2.4.10.RELEASE.jar
```

**Comment by garyrussell** [comment]
Oops; sorry about that; that method was added in spring-kafka 2.5; unfortunately, Boot 2.2 is not compatible with that version.

I'll see if back-porting that method to 2.4.11 will solve it.

**Comment by garyrussell** [comment]
Please try with the 2.4.11.BUILD-SNAPSHOT.

I have tested it with a simple consumer/producer function and it worked after I back ported a couple of API changes used by spring-integration-kafka 3.3.x.

But, it would be good if you could test the snapshot in your app, before I build the 2.4.11.RELEASE tomorrow.

Thanks in advance.

```xml
<dependency>
	<groupId>org.springframework.kafka</groupId>
	<artifactId>spring-kafka</artifactId>
	<version>2.4.11.BUILD-SNAPSHOT</version>
</dependency>
<dependency>
	<groupId>org.apache.kafka</groupId>
	<artifactId>kafka-clients</artifactId>
	<version>2.4.1</version>
</dependency>

...

	<repositories>
		<repository>
			<id>spring-snaps</id>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```

**Comment by garyrussell** [comment]
I have also back-ported the API changes to 2.3.13.BUILD-SNAPSHOT, so no overrides will be required with the next Boot 2.2.x release (2.2.12, Dec 10th).

**Comment by ferblaca** [comment]
Hello @garyrussell ! I have tested the configuration with the demo application that you indicate and it works correctly.

we are waiting for version 2.4.11.RELEASE ;)

Thank you very much for everything.

**Comment by garyrussell** [comment]
@ferblaca spring-kafka 2.4.11.RELEASE is now in maven central.

**Comment by olegz** [comment]
I believe this issue is resolved and can be closed. Feel free to reopen it if needed
