### ISSUE TITLE
Documentation for schema evolution missing (in 3.0.8.RELEASE and 3.1.0-M4)

### ISSUE THREAD

**Issue by samragu** [spring-cloud/spring-cloud-stream#2049]
https://docs.spring.io/spring-cloud-stream/docs/3.0.8.RELEASE/reference/html/spring-cloud-stream.html#schema-evolution
is missing

**Comment by sabbyanandan** [comment]
Thanks. We will address it in 3.1 RC1 shipping next week.

**Comment by olegz** [comment]
This is an old issue and should probably be addressed in spring-cloud-schema-registry project
