### ISSUE TITLE
multiple binder with the same topic start failed

### ISSUE THREAD

**Issue by RobertoHuang** [spring-cloud/spring-cloud-stream#2058]
when I try using spring cloud stream connected two mq cluster, and They have the same topic name

so， I configured two binders，and they have the same destination。i got error

![image](https://user-images.githubusercontent.com/20842825/100197501-5c1b5780-2f35-11eb-9cba-91ab8fe026e4.png)

I don't know how to solve this problem, can you help me

**Comment by RobertoHuang** [comment]
the problem  cause by errorBridgeHandlerName has the same name

I think errorBridgeHandlerName can add prefix with bindername，But I cannot modify it 。

![image](https://user-images.githubusercontent.com/20842825/100210695-3cd8f600-2f46-11eb-84b6-de5d7d5be661.png)

**Comment by olegz** [comment]
Actually, can you share your configuration? There is most likely a better way of addressing it.

**Comment by olegz** [comment]
@RobertoHuang please provide your configuration and relevant code (your code) is applicable. I just tried to reproduce it based on your explanation and everything works as expected. In other words I do not get any error.

**Comment by RobertoHuang** [comment]
spring.cloud.stream.binders.binder1.type=rocketmq
spring.cloud.stream.binders.binder1.environment.spring.cloud.stream.rocketmq.binder.name-server=localhost:9876
spring.cloud.stream.binders.binder1.environment.spring.cloud.stream.rocketmq.binder.access-key=akxxx
spring.cloud.stream.binders.binder1.environment.spring.cloud.stream.rocketmq.binder.secret-key=skxxx

spring.cloud.stream.binders.binder2.type=rocketmq
spring.cloud.stream.binders.binder2.environment.spring.cloud.stream.rocketmq.binder.name-server=localhost:9886
spring.cloud.stream.binders.binder2.environment.spring.cloud.stream.rocketmq.binder.access-key=akxxx
spring.cloud.stream.binders.binder2.environment.spring.cloud.stream.rocketmq.binder.secret-key=skxxx

spring.cloud.stream.bindings.binder1.binder=binder1
spring.cloud.stream.bindings.binder1.group=binder1
spring.cloud.stream.bindings.binder1.destination=task
spring.cloud.stream.bindings.binder1.consumer.auto-startup=false
spring.cloud.stream.bindings.binder1.producer.error-channel-enabled=true

spring.cloud.stream.bindings.binder2.binder=binder2
spring.cloud.stream.bindings.binder2.group=binder2
spring.cloud.stream.bindings.binder2.destination=task
spring.cloud.stream.bindings.binder2.consumer.auto-startup=false
spring.cloud.stream.bindings.binder2.producer.error-channel-enabled=true

**Comment by RobertoHuang** [comment]
The main reason for the problem is "error-channel"

**Comment by olegz** [comment]
I am not sure about these configurations
```
spring.cloud.stream.bindings.binder1.binder=binder1
spring.cloud.stream.bindings.binder1.group=binder1
spring.cloud.stream.bindings.binder1.destination=task
spring.cloud.stream.bindings.binder1.consumer.auto-startup=false
spring.cloud.stream.bindings.binder1.producer.error-channel-enabled=true

```
Is `binder1` also the name of your binding? That doesn't look right. It should be `spring.cloud.stream.bindings.<binding-name>.group=destinatioin-name`

Now I understand why I can't reproduce it

**Comment by olegz** [comment]
Any feedback on the last set of questions?

**Comment by RobertoHuang** [comment]
spring.cloud.stream.binders.binder1.type=rocketmq
spring.cloud.stream.binders.binder1.environment.spring.cloud.stream.rocketmq.binder.name-server=localhost:9876
spring.cloud.stream.binders.binder1.environment.spring.cloud.stream.rocketmq.binder.access-key=akxxx
spring.cloud.stream.binders.binder1.environment.spring.cloud.stream.rocketmq.binder.secret-key=skxxx

spring.cloud.stream.binders.binder2.type=rocketmq
spring.cloud.stream.binders.binder2.environment.spring.cloud.stream.rocketmq.binder.name-server=localhost:9886
spring.cloud.stream.binders.binder2.environment.spring.cloud.stream.rocketmq.binder.access-key=akxxx
spring.cloud.stream.binders.binder2.environment.spring.cloud.stream.rocketmq.binder.secret-key=skxxx

spring.cloud.stream.bindings.bindings1.binder=binder1
spring.cloud.stream.bindings.bindings1.group=binder1
spring.cloud.stream.bindings.bindings1.destination=task
spring.cloud.stream.bindings.bindings1.consumer.auto-startup=false
spring.cloud.stream.bindings.bindings1.producer.error-channel-enabled=true

spring.cloud.stream.bindings.bindings2.binder=binder2
spring.cloud.stream.bindings.bindings2.group=binder2
spring.cloud.stream.bindings.bindings2.destination=task
spring.cloud.stream.bindings.bindings2.consumer.auto-startup=false
spring.cloud.stream.bindings.bindings2.producer.error-channel-enabled=true

The above configuration will still report an error.

Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'task.errors.bridge' defined in null: Cannot register bean definition [Root bean: class [org.springframework.integration.handler.BridgeHandler]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'task.errors.bridge': There is already [Root bean: class [org.springframework.integration.handler.BridgeHandler]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
