### ISSUE TITLE
ArrayIndexOutOfBoundsException if number of outputs greater than number of inputs

### ISSUE THREAD

**Issue by chringwer** [spring-cloud/spring-cloud-stream#2059]
The assert on line 596 should use `getOutputType` rather than `getInputType`.

https://github.com/spring-cloud/spring-cloud-stream/blob/ac0bc4595a85fab5404cce25ffbb92df3c8c433d/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L594-L600

I guess, this has been refactored on the main branch but it would be great to have this fixed on 3.0.x as well.

**Comment by olegz** [comment]
Resolved with https://github.com/olegz/spring-cloud-stream/commit/b53f2ccbea13dec78978c6fc405fe35c41efe5aa
