### ISSUE TITLE
onError signal makes reactive publisher fail silently

### ISSUE THREAD

**Issue by UgiR** [spring-cloud/spring-cloud-stream#2062]
I understand the framework no longer attempts to handle errors for reactive publishers, but I think it should still log any errors (unhandled by the user) that propagated to the subscriber. Currently, if an error propagates to the framework's subscriber, it will simply disappear and the publisher will terminate with no output.

Currently, [subscribe()](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L487) does not define any behavior for an onError signal.

Request: add a log in the form of `doOnError` or `doOnTerminate` to the subscriber, so there is feedback if an error was unhandled or a publisher has terminated.

**Comment by olegz** [comment]
FWIW, I just noticed that the stack trace is already logged on the master, so perhaps some improvements in Spring Integration mad it happen, but I was able to reproduce it on 3.0.x branch and should push the fix shortly
