### ISSUE TITLE
Tracing problem with event routing from consumer

### ISSUE THREAD

**Issue by henriquels25** [spring-cloud/spring-cloud-stream#2063]
I have a problem with tracing when I send messages to specific destinations using the [spring.cloud.stream.sendto.destination](https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream.html#_spring_cloud_stream_sendto_destination) header or [StreamBridge](https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream.html#_using_streambridge). With these, I only see the incoming message in Jaeger, not the outgoing one.

When I use the deprecated [BinderAwareChannelResolver](https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream.html#_binderawarechannelresolver), it works fine.

The functionality of sending messages to the destination topics is working fine in all cases.

**To Reproduce**
I set up a simple project in https://github.com/henriquels25/tracing-problem-demo. In the README, there are instructions to reproduce the problem

**Version of the framework**
Spring Boot 2.3.6.RELEASE
Spring Cloud Hoxton.SR9

**Expected behavior**
The outgoing messages should be presented in Jaeger using the `spring.cloud.stream.sendto.destination` header
or `StreamBridge`.

**Screenshots**
Below are the images of Jaeger when using each of the alternatives:

`BinderAwareChannelResolver`
![americans_tracing](https://user-images.githubusercontent.com/4086440/101256926-4a3c7000-36fe-11eb-8268-53e7f3fe218b.png)

`spring.cloud.stream.sendto.destination`
![brazilians_tracing](https://user-images.githubusercontent.com/4086440/101257125-63ddb780-36fe-11eb-973c-b35a63b4cd66.png)

`StreamBridge`
![germans_tracing](https://user-images.githubusercontent.com/4086440/101257313-70faa680-36fe-11eb-82bf-c6b789c3a196.png)

**Additional context**
I had the same problem using [Spring Cloud Sleuth](https://spring.io/projects/spring-cloud-sleuth) and [Zipkin](https://zipkin.io/).

**Comment by serginhosis** [comment]
I also have this problem, and I believe it is a critical issue, after all, there is no non-deprecated resource for tracing with dynamic destinations.

**Comment by olegz** [comment]
@henriquels25 Struggling a bit to understand what is the issue as we don't do anything specific to tracing in `BinderAwareChannelResolver` or anywhere else in s-c-stream. I'll dig more tomorrow but if you have any additional context, please share

**Comment by marcingrzejszczak** [comment]
@serginhosis can you check if the same problem persists in latest `2020.0.0-SNAPSHOT` release train with `spring-cloud-starter-sleuth` and `spring-cloud-sleuth-zipkin` on the classpath?

**Comment by serginhosis** [comment]
@marcingrzejszczak nothing change bro.

**Comment by olegz** [comment]
I am resolving this issue as "won't fix", since there was no substantive feedback from the reporters

**Comment by serginhosis** [comment]
@olegz what more information you need?

**Comment by olegz** [comment]
@serginhosis see my comment https://github.com/spring-cloud/spring-cloud-stream/issues/2063#issuecomment-739526537

**Comment by henriquels25** [comment]
Sorry @olegz, I didn't understand that as a question. 

I didn't have any additional context on the problem and I tried to describe all the context in the issue description and in the sample project [tracing-problem-demo](https://github.com/henriquels25/tracing-problem-demo).

I believe it would be important to solve this problem but I couldn't find the root cause in Spring Cloud Stream or the [java-spring-jaeger](https://github.com/opentracing-contrib/java-spring-jaeger).

**Comment by olegz** [comment]
As I stated before, we don't do any tracing in s-c-stream, so I can't comment much further then that, hence I was asking for some additional context, otherwise I am not sure what I can do.

**Comment by henriquels25** [comment]
I understand, thanks for the feedback. I will try to dig some more to see if I find anything and maybe create an issue in [java-spring-jaeger](https://github.com/opentracing-contrib/java-spring-jaeger) to check if they have an idea on the root cause.

**Comment by henriquels25** [comment]
@olegz, I found that the [resolveDestination](https://github.com/spring-cloud/spring-cloud-stream/blob/66aef62e49a852b4d6463c259932489ab8b50565/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L183) method in `StreamBridge`  creates an instance of `DirectWithAttributesChannel` that has an empty list of interceptors. This method is also called from `FunctionConfiguration` for messages with the header "spring.cloud.stream.sendto.destination" in lines [235](https://github.com/spring-cloud/spring-cloud-stream/blob/66aef62e49a852b4d6463c259932489ab8b50565/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L235) and [252](https://github.com/spring-cloud/spring-cloud-stream/blob/66aef62e49a852b4d6463c259932489ab8b50565/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L252).

On the other hand, the [resolveDestination](https://github.com/spring-cloud/spring-cloud-stream/blob/66aef62e49a852b4d6463c259932489ab8b50565/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BinderAwareChannelResolver.java#L94method) method on `BinderAwareChannelResolver` uses a factory to create the channel and call the method `beanFactory.initializeBean` on line [122](https://github.com/spring-cloud/spring-cloud-stream/blob/66aef62e49a852b4d6463c259932489ab8b50565/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BinderAwareChannelResolver.java#L122). After the `initializeBean` method is called, the `OpenTracingChannelInterceptor` is added to the list of interceptors. 

I believe the root cause for this tracing issue is that the channel created on `StreamBridge` has no interceptors so the tracing does not work properly. 

Does it make sense?
