### ISSUE TITLE
Documentation - Test Binder configuration and Gradle dependency

### ISSUE THREAD

**Issue by henriquels25** [spring-cloud/spring-cloud-stream#2064]
In the [Test Binder Configuration](https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream.html#_test_binder_configuration) section, there are instructions to import the dependencies using maven and it says that it is easy to retrofit it into Gradle.

I had some problems trying to do this in Gradle, and even [Spring Initilizr](https://start.spring.io/) is not doing it right, as it can be seen in [#1159](https://github.com/spring-io/initializr/issues/1159) and [#591](https://github.com/spring-io/start.spring.io/issues/591).

I suggest adding instructions showing how to import the test dependency in Gradle because it is not as straightforward as other dependencies.

If it would be ok to do this, I'd be willing to create a PR.

**Comment by olegz** [comment]
Actually this has been resolved (documented) on the master with https://github.com/spring-cloud/spring-cloud-stream/pull/2055/files
I'll back port it to Horsham and resolve the isue

**Comment by olegz** [comment]
Back ported to 3.0.x branch https://github.com/spring-cloud/spring-cloud-stream/commit/6f867ad87f4f8fc0fa19dd98ba13f5bb43e1323a
