### ISSUE TITLE
Deserialization error when using with multiple reactive input/outputs

### ISSUE THREAD

**Issue by chringwer** [spring-cloud/spring-cloud-stream#2065]
**Describe the issue**
Using the latest milestone release a function with the following signature will yield a `java.lang.ClassCastException: class java.lang.String cannot be cast to class org.springframework.messaging.Message` expection:

```
@Bean
public Function<Tuple2<Flux<Message<String>>, Flux<Message<String>>>, Tuple2<Flux<Message<String>>, Flux<Message<String>>>> handler()
{
    return input ->
    {
        final Flux<Message<String>> out1 =
            input.getT1().map(m -> MessageBuilder.withPayload(m.getPayload().toUpperCase()).build());

        final Flux<Message<String>> out2 =
            input.getT2().map(m -> MessageBuilder.withPayload(m.getPayload().toLowerCase()).build());

        return Tuples.of(out1, out2);
    };
}
```

**To Reproduce**
Here is an example project reproducing the issue. Tests are green if you revert to spring boot 2.3.6 and Hoxton.SR9:
https://github.com/chringwer/spring-cloud-stream-bug

**Comment by olegz** [comment]
So the actual fix is [here](https://github.com/spring-cloud/spring-cloud-function/commit/7403a51464d6f7318b3b41d50c2fbebdb05dbcc0)
I'll push a test that validates it but I also tested with your app which was failing before.
