### ISSUE TITLE
BindingsEndpointAutoConfiguration issue - BindingsEndpoint bean not available in context

### ISSUE THREAD

**Issue by kawaleamol2020** [spring-cloud/spring-cloud-stream#2071]
We have recently upgraded spring boot from 2.1.0 to 2.3.5 version and facing the below issue.

Exception in thread "main" org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.stream.endpoint.BindingsEndpoint' available

bindingsEndpoint bean creation is conditional after 3.0.1 so it is creating this issue.

Can some one help us on this isuse.

**Comment by olegz** [comment]
It is impossible for me to diagnose this issue without more information or way to reproduce it.

Please refer to [this section of reference manual](https://docs.spring.io/spring-cloud-stream/docs/3.1.3/reference/html/spring-cloud-stream.html#binding_visualization_control) for how to enable Binding visualization and control.

Also, if you still believe there is an issue, please provide a small project that reproduces it so we can look
