### ISSUE TITLE
JSON de-serialization not working - Reactive approach using Spring cloud function

### ISSUE THREAD

**Issue by karthikairam** [spring-cloud/spring-cloud-stream#2072]
Issue Description:
In spring cloud stream, json is not getting de-serialized into POJOs when the function receives it. No exception but fields are with null values. I am using solace binder.

	Issue occurs when:
		Dependencies and version details as follows:
			spring-cloud-starter-stream-solace:2.1.1
			spring-cloud-stream: 3.0.9.RELEASE
			spring-cloud-starter-config: 2.2.6.RELEASE
			spring-boot-starter-actuator: 2.3.7.RELEASE
			spring-boot-starter-webflux: 2.3.7.RELEASE

	Issue not happening when:
		Dependencies and version details as follows:
			spring-cloud-starter-stream-solace:2.1.1
			spring-cloud-stream: 3.0.9.RELEASE

	Issue not happening when:
		Dependencies and version details as follows:
			spring-cloud-starter-stream-solace:2.1.1
			spring-cloud-stream: 3.0.6.RELEASE
			spring-cloud-starter-config: 2.2.3.RELEASE
			spring-boot-starter-actuator: 2.3.2.RELEASE
			spring-boot-starter-webflux: 2.3.2.RELEASE

Some more findings: 
	Issue occurs only when I have this version of dependency spring-cloud-function-context:3.0.11.RELEASE. And same works fine with spring-cloud-function-context:3.0.10.RELEASE. But, I can't downgrade the function context dependency as some properties related to error handling doesn't work without latest.
	
	Suspected Class is: SimpleFunctionRegistry.java in line number: 833 in spring-cloud-function-context:3.0.11.RELEASE
	
I need to have the spring cloud config client and actuator endpoint exposed using webflux. Please help me to resolve the same.

**Comment by olegz** [comment]
Given that `application/json` is the default content type, there are hundreds of tests serializing and deserializing to/from JSON. Basically what I am saying is that we can't reproduce it, so you need to provide a test case or sample project that we can run and reproduce the issue.

**Comment by olegz** [comment]
Any feedback or follow up on this? As I mentioned, I can't reproduce it so please provide a small project wit bare minimum which demonstrates the issue

**Comment by karthikaiselvan** [comment]
Hi @olegz , Apologies for coming back to bit late as I was bit tided-up. I will try to create a sample project to reproduce the same, as quick as possible.
Thanks!

**Comment by olegz** [comment]
@karthikaiselvan are you still planning to provide a sample to reproduce?

**Comment by karthikaiselvan** [comment]
Hi @olegz, I had created one and I couldn't upload the same due to company policy. I have to create it again using my own PC, which I will try to create in the coming weeks. Since I am preparing for few tech exams, ETA is mostly likely the end of April.

**Comment by karthikairam** [comment]
I am not able to reproduce the same in the latest versions. So, it item can be closed.
Thanks!
