### ISSUE TITLE
Fix documentation with regard to retry behavior and recommendations for reactive functions

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream#2073]

**Comment by Mrc0113** [comment]
Thanks for opening this issue @olegz. We recently had this question pop up from a developer in the Solace Community [here](https://solace.community/discussion/538/how-can-we-achieve-exception-handling-in-spring-cloud-stream-using-solace-binder#latest)

Ideally it would be great to have the Cloud Stream reference guide updated to: 
* Remove the parts that discuss `retryBackoff` for reactive functions. 
* Add clarification that retries must be handled on the Flux using capabilities provided by project reactor
* Link(s) to the project reactor retry docs
* A link to a sample showing basic retry capabilities on a per message basis
* [Nice to have] A link to a sample showing retries on a window of messages

Thanks for your continued enhancements to this project and overall support to the Spring community! We are seeing more and more organizations using the Cloud Stream project with the Solace Binder and it has become a favorite of developers new to creating event-driven apps.

**Comment by olegz** [comment]
@Mrc0113 i think I covered all that you have asked, but please let me know if I missed anything

**Comment by Mrc0113** [comment]
Thanks @olegz. Looks like you covered everything I expected. I know this is just small documentation updates but I think it will help avoid a lot of confusion. I've already had multiple developers run into this issue when using Cloud Stream with Solace so I appreciate you adding this clarification.
