### ISSUE TITLE
Module Launcher missing features/enhancements 

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#208]
As discussed with @jvalkeal, the module launcher has the following limitations which manifest themselves in the YARN deployer:

- exceptions thrown during launch are not visible to the caller, due to the launch happening in a separate thread;
- no easy way to gracefully shut down a module launched via module launcher (see https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-admin-local/src/main/java/org/springframework/cloud/dataflow/admin/spi/local/LocalModuleDeployer.java#L100 for possible workaround);
- no ability to manage the threads being used at launch;
- generally speaking, a suggested approach would be to get hold of a Future that could be used for canceling the running process, if necessary.

**Comment by sabbyanandan** [comment]
This is already in scope for the generic cloud deployer w-i-p.
