### ISSUE TITLE
Set requireSubscribers on the binding error channel

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2082]
See https://github.com/spring-projects/spring-integration/pull/3459 and https://stackoverflow.com/questions/65711701/spring-cloud-stream-unexpected-shutdown-is-not-covered-by-dlq/65722866#65722866

Change `BinderErrorChannel` to set `requireSubscribers` so an exception is thrown if an error occurs after the consumer has unsubscribed.

**Comment by olegz** [comment]
Unfortunately this one can't be backported since it depends on the latest change in SI
