### ISSUE TITLE
When content-type with wildcards are sent via StreamBridge all the MessageConverters match even when they should not

### ISSUE THREAD

**Issue by JordiMartinezVicent** [spring-cloud/spring-cloud-stream#2090]
**Describe the issue**

Given a custom MessageConverter, when a message is sent via StreamBridge with a generic mime type, the message converter is always called, even though the MessageConverter does not supports the mime type. 

For example if the MessageConverter supports messages for application/bar. If a message is sent with the content-type application/*+json, the converter is called when it should not. 

**To Reproduce**

Execute the following test: 

```
@SpringBootTest(classes = MessageConverterTestConfig.class)
@EnableAutoConfiguration
class MessageConverterTest {

	@Autowired
	private StreamBridge streamBridge;

	@SpyBean
	private TestMessageConverter testMessageConverter;

	@Test
	void genericJsonMimeTypeShouldNotCallTestConverter() {
		streamBridge.send("output-out-0", "text-message", new MimeType("application", "*+json"));

		Mockito.verify(testMessageConverter, Mockito.never()).convertToInternal(Mockito.any(), Mockito.any(),
				Mockito.any());
	}


	@Configuration(proxyBeanMethods = false)
	@Import(TestChannelBinderConfiguration.class)
	static class MessageConverterTestConfig {

		@Bean
		public TestMessageConverter testMessageConverter() {
			return new TestMessageConverter();
		}

	}

	public static class TestMessageConverter extends AbstractMessageConverter {

		private static final MimeType DEFAULT_MIME_TYPE = new MimeType("application", "bar");

		public TestMessageConverter() {
			super(DEFAULT_MIME_TYPE);
		}


		@Override
		public Object convertFromInternal(Message<?> message, Class<?> targetClass,
				@Nullable Object conversionHint) {

			return message.getPayload().toString();
		}

		@Override
		public Object convertToInternal(Object payload, @Nullable MessageHeaders headers,
				@Nullable Object conversionHint) {

			Object ret = null;
			
			if(payload != null) {
				ret = payload.toString();
			}
			
			return ret;
		}

		/**
		 * {@inheritDoc}
		 */
		@Override
		protected boolean supports(Class<?> clazz) {
			return true;
		}

	}
}
```

**Version of the framework**

Spring Cloud Stream version: 3.1.0

**Additional context**

Note that in the the legacy annotation-based support it worked as expected.  
I used this feature with **org.springframework.cloud.schema.registry.avro.AvroSchemaRegistryClientMessageConverter**. With this converter, the output content-type was set as `application/*+avro` and the converter changed the countent-type headers with the specific avro schema.

**Comment by olegz** [comment]
Did you notice that you set 'supports' to `true`?
```
protected boolean supports(Class<?> clazz) {
	return true;
}
```

**Comment by JordiMartinezVicent** [comment]
Yes, it is made on purpose in order to accept all the types. Note that `org.springframework.cloud.schema.registry.avro.AvroSchemaRegistryClientMessageConverter` does the same:

```
@Override
protected boolean supports(Class<?> clazz) {
    //we support all types
   return true;
}
```

About the methods you mentioned, I think the default implementations is correct for this use case: 

```
protected boolean canConvertFrom(Message<?> message, Class<?> targetClass) {
    return (supports(targetClass) && supportsMimeType(message.getHeaders()));
}

protected boolean canConvertTo(Object payload, @Nullable MessageHeaders headers) {
    return (supports(payload.getClass()) && supportsMimeType(headers));
}
```
as they check whether the converter supports the mime type included as a header, (which should be false). 

Investigating a bit more, I saw that when the mime type of the output message is not concrete, the class `org.springframework.cloud.function.context.config.SmartCompositeMessageConverter` is changing the header content-type for the one supported by the converter: 

```
 @Override
@Nullable
public Message<?> toMessage(Object payload, @Nullable MessageHeaders headers) {
for (MessageConverter converter : getConverters()) {
	Object value = headers.get(MessageHeaders.CONTENT_TYPE).toString();
	String[] contentTypes = StringUtils.delimitedListToStringArray((String) value, ",");
	for (String contentType : contentTypes) {
		if (!MimeType.valueOf(contentType).isConcrete()) {
			List<MimeType> supportedMimeTypes = ((AbstractMessageConverter) converter).getSupportedMimeTypes();
			for (MimeType supportedMimeType : supportedMimeTypes) {
				MessageHeaderAccessor h = new MessageHeaderAccessor();
				h.copyHeaders(headers);
				h.setHeader(MessageHeaders.CONTENT_TYPE, supportedMimeType);
				Message<?> result = converter.toMessage(payload, h.getMessageHeaders());
				if (result != null) {
					return result;
				}
			}
		}
		else {
			(...) 
		}
	}
}
return null;
}
```

The key lines are the following:
```
List<MimeType> supportedMimeTypes = ((AbstractMessageConverter) converter).getSupportedMimeTypes();
h.setHeader(MessageHeaders.CONTENT_TYPE, supportedMimeType);
```

It gets the converter supported mime types and sets them to the headers. That is why the converter ALWAYS supports the mime type, even when it should not.

**Comment by olegz** [comment]
Correct, and that is on purpose as well. Basically the idea is, if content type is set to something like `*/*` or `application/*` etc., then we try with any converter that says "yes". Now, the converter that said "yes" may still not be able to convert it, so we continue to iterate. Once a particular converter was able to convert, we stop iterating and use the content type of that converter as an output content type. 
So, basically what I am trying to say is that the MessageConverter API accounts for various filtering method that would allow you to determine if this converter should even attempt to convert it. The `supports` method is really primitive way of saying yes/no, hence those other methods that I have suggested.

That said, I am going to assume that you still have an issue that I may not fully understand , so let me try something different.
You implemented custom converter. It was added at the top of the stack of existing MessageConverters, so it get's tested first. What do you want to accomplish given that you said _. . .Yes, it is made on purpose in order to accept all the types._?

**Comment by JordiMartinezVicent** [comment]
The issue arose when migrating an application from the legacy to functions. With the legacy mode it worked fine. 

Basically we had two custom MessageConverter. They are similar to AvroSchemaRegistryClientMessageConverter but added some custom logic. An example of binding configuration is: 

```
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: topic1
          content-type: application/*+avro          
        output2:
          destination: topic2
          content-type: application/*+non-registered-avro
```

So when a message is sent via `output`,  the content-type of the message would be `application/*+avro`, and when the message is sent via `output2` the content-type would be `application/*+non-registered-avro`.  What cause that depending on the content-type of the message, one converter or the other is executed. 

With functions, as we mentioned before, if the content type of the message contains a `*` the converter always says "yes", so the first converter is always executed although the content-type of the message does not match with the converter's supported mime types.

**Comment by JoseLora** [comment]
Hi @olegz.

I agree with @JordiMartinezVicent. If you modify the content-type header before calling `converter.toMessage`, the converter gets that modified content-type and always "say yes".

Maybe the fix is just to modify the content-type header **only after** the converter really converted the message?

We're waiting for this fix too. Any plans on this?

Thanks in advance!

**Comment by olegz** [comment]
So, this one is being fixed in two places - https://github.com/spring-cloud/spring-cloud-function/issues/773
Will push stream fix shortly

**Comment by olegz** [comment]
Snapshots for 3.2 and 3.1.6 are available
