### ISSUE TITLE
Add ability to programmatically shut down stream-processing app after current message

### ISSUE THREAD

**Issue by yonigibbs** [spring-cloud/spring-cloud-stream#2096]
We have a scenario where a message is received which is similar to a "poison pill", except it's not a deserialization issue: it's more that while processing that message an unrecoverable error is encountered which leaves the stream processing app in an unstable condition. We now need two things to happen:
1. Respond to Kafka in some way to let it know that this message has been processed, to ensure the message doesn't get sent to another instance of the stream processing app. Possibly a DLQ could be used here?
2. Shut down the app, as it's now in an unstable condition. (At this point we'd expect Kubernetes or whatever to bring up a new instance to take over subsequent messages.)

For more background, see this question (and discussion with @olegz): https://stackoverflow.com/questions/65897973/how-to-shut-down-spring-boot-kafka-stream-processing-app-after-current-message/

**Comment by olegz** [comment]
This has already been addressed with [this commit](https://github.com/spring-cloud/spring-cloud-stream/commit/5cd14e4a8d3473b44a02fb55b64a85185c3b8286)

Basically you need to inject `BindingsLifecycleController` and execute any of the required lifecycle methods
For example,
```
BindingsLifecycleController bindingsController = context.getBean(BindingsLifecycleController.class);
bindingsController.stop("echo-in-0")
```

**Comment by yonigibbs** [comment]
Thanks @olegz. When exactly should that be done though? Presumably if we call that code while processing the current request (the "poison pill") then the response for that message will not be sent to Kafka as we've already called `stop`. But if we wait till after we respond from our function, when would we call the `stop` method to ensure that we are not sent any more messages to handle?
