### ISSUE TITLE
Documentation recommends use of EmitterProcessor#onNext

### ISSUE THREAD

**Issue by UgiR** [spring-cloud/spring-cloud-stream#2099]
In the [documentation](https://docs.spring.io/spring-cloud-stream/docs/3.1.0/reference/html/spring-cloud-stream.html#_using_reactor_api), the example shows the use of `EmitterProcessor#onNext` to publish from foreign sources. In a project, I noticed this leading to data loss.

The Reactor [documentation](https://projectreactor.io/docs/core/3.3.11.RELEASE/reference/#_safely_produce_from_multiple_threads_by_using_the_sink_facade) states:

> Rather than directly using Reactor Processors, it is a good practice to obtain a Sink for the Processor by calling sink() once.
> 
> FluxProcessor sinks safely gate multi-threaded producers and can be used by applications that generate data from multiple threads concurrently. 

Reproducing data loss with EmitterProcessor:

```
@Test
public void processorDataLossRepro() {
    EmitterProcessor<Integer> emitterProcessor = EmitterProcessor.create();
    FluxSink<Integer> sink = emitterProcessor.sink();
    Flux.range(1, 10_000)
            .parallel()
            .runOn(Schedulers.parallel())
            //.doOnNext(sink::next)
            .doOnNext(emitterProcessor::onNext)
            .sequential()
            .doFinally(__ -> emitterProcessor.onComplete())
            .subscribe();

    StepVerifier.create(emitterProcessor)
            .expectNextCount(10_000)
            .verifyComplete();
}
```

Suggestion: Update documentation to use `FluxSink` instead of `EmitterProcessor` directly to avoid hard-to-find bugs while using Spring Cloud Stream.

**Comment by olegz** [comment]
We no longer recommend EmitterProcessor and instead rely on StreamBridge. The documentation has already been updated and back ported https://github.com/spring-cloud/spring-cloud-stream/commit/73ca65da5d9ac3a822933d9d43c17b790bd33540
