### ISSUE TITLE
Clear queues in tests

### ISSUE THREAD

**Issue by mdii** [spring-cloud/spring-cloud-stream#2100]
Hello, while migrating to spring-cloud-stream 3.1.0 we noticed that there is no easy way to clear message queues in tests. There are two `clear()` methods in `OutputDestination` but both of them completely remove the queues.
In our tests we don't reinitialze the context before each test, so the queues won't be created again if we use those methods.
In addition `clear(String destinationName)` seems to be wrong because it takes the destination name but it removed all the queues. Is this intentional?

**Comment by olegz** [comment]
Actually this has just been addressed with https://github.com/spring-cloud/spring-cloud-stream/issues/2112
It was also back-ported and will be available with the next version of Horsham which as of this writing will be tomorrow.
