### ISSUE TITLE
Exception when using StreamBridge to send partition message with nativeEncoding  

### ISSUE THREAD

**Issue by taikhuu** [spring-cloud/spring-cloud-stream#2101]
**Describe the issue**
When using StreamBridge to send a partitioned message with nativeEncoding, StreamBridge will throw a type cast exception. 

**To Reproduce**

1. useNativeEncoding set to true
2. Send Message with partition header

**Version of the framework**
3.0.10.RELEASE

**Expected behavior**
Message is sent correctly

**Screenshots**
```
java.lang.ClassCastException: org.springframework.cloud.stream.function.StreamBridge$$Lambda$1350/1117349678 cannot be cast to org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:153)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:124)
```

**Additional context**
I take a look at the code of StreamBridge and this issue was caused by this line
```
		Function<Object, Object> functionToInvoke = skipConversion
				? v -> v instanceof Message ? v :  MessageBuilder.withPayload(v).build()
						: this.functionCatalog.lookup(STREAM_BRIDGE_FUNC_NAME, outputContentType.toString());
		if (producerProperties != null && producerProperties.isPartitioned()) {
			functionToInvoke = new PartitionAwareFunctionWrapper((FunctionInvocationWrapper) functionToInvoke, this.applicationContext, producerProperties);
		}
```
So in the case of skipConversion and partitioned message, a Function object will be cast to FunctionInvocationWrapper

**Comment by taikhuu** [comment]
I switched to use Spring Kafka instead of Spring Cloud Stream already, but I still want to know if this bug is really a bug or just my mistake :(

**Comment by olegz** [comment]
No, you are correct. Fixing it shortly

**Comment by VincenzoMalagrino** [comment]
Hi, I'm experiencing the same issue. Is there a workaround to make this work with version 3.1.3.

**Comment by bonndan** [comment]
We are desperate and now trying to workaround this issue using jitpack.io. However, a different solution would be very appreciated. Is a release in sight?

**Comment by olegz** [comment]
@bonndan Sorry about the delay. The next Spring Cloud release which will pick up 3.1.4 of stream is set for September 21.
I just updated the Milestone
