### ISSUE TITLE
Document that legacy bindings are safe to use and they are not deprecated

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-cloud/spring-cloud-stream#2102]
This is a follow-up on https://github.com/spring-cloud/spring-cloud-sleuth/issues/1822
It seems that the documentation of legacy bindings could be misleading. Users using the `MessageChannel` or `StreamBridge` could unnecessarily move away from them and use the functional approach (`Supplier`): https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_annotation_based_binding_names_legacy

See this comment: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1822#issuecomment-760024504

**Comment by olegz** [comment]
I am actually going to remove that whole section. We've been on functional approach for several years now and have been gradually removing documentation that points to annotation-based legacy configuration. Judging by our community responses most have already switched to functional, so hopefully the rest will follow.

**Comment by olegz** [comment]
Resolved with https://github.com/olegz/spring-cloud-stream/commit/a550d61af60ae68cc64e25a8cea7852703a9b3c6
On master the documentation has already been removed
