### ISSUE TITLE
Document tracing support

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-cloud/spring-cloud-stream#2103]
The current documentation does not contain information about what bindings support (`StreamBridge`, `MessageChannel`) distributed tracing using and what bindings does not (Functional/`Supplier`): https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/

Connected issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1822

**Comment by patpatpat123** [comment]
Hello team,

Many thanks for this, it is very helpful.
Is it possible to document that as of SpringBoot 3.0.2 + Spring Cloud 2022.0.1 (latest as of this writing), tracing is not supported for reactor / reactive Spring Cloud Stream please?

Thank you @olegz @jonatan-ivanov
