### ISSUE TITLE
Support distributed tracing for Functional Binders

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-cloud/spring-cloud-stream#2104]
Right now distributed tracing is not supported if you want to use the functional way of sending messages using a `Supplier` and a `BlockingQueue`, see the sample: [schema-registry-vanilla-rabbit-binder](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/schema-registry-samples/schema-registry-vanilla-rabbit-binder/schema-registry-vanilla-producer1-rabbit/src/main/java/sample/producer1/Producer1ApplicationRabbit.java) and this issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1822

Since Tracing can be tricky, this issue is for discussion/documenting decisions.
This is also connected: https://github.com/spring-cloud/spring-cloud-stream/issues/2105

/cc @marcingrzejszczak @olegz

**Comment by olegz** [comment]
After thinking about it some more I am reluctant to do anything about it, since we have a first class mechanism for the user to send messages using the current thread - `StreamBridge` and based on on and off discussion @marcingrzejszczak and I had i believe it is sufficient.

Thoughts  ?

**Comment by olegz** [comment]
. . . and documenting it with https://github.com/spring-cloud/spring-cloud-stream/issues/2103 should eliminate the confusion

**Comment by olegz** [comment]
I believe based on the discussion three of us just had, no further action is required on this issue, so I'll close it, Feel free to reopen it if you think we should do something.

**Comment by patpatpat123** [comment]
Hello team,

Many thanks for this, it is very helpful.
As of SpringBoot 3.0.2 + Spring Cloud 2022.0.1, if the Functional binder is reactive (for example ```Consumer<Flux<Message<String>>>``` the tracing is not propagating correctly, even with tap() or handle()
