### ISSUE TITLE
Call to method clear() of OutputDestination bean between tests irreversibly breaks the bean

### ISSUE THREAD

**Issue by zinchin** [spring-cloud/spring-cloud-stream#2112]
The source code of org.springframework.cloud.stream.binder.test.OutputDestination has the following issues:
1) Never recreates BlockingQueue for specific binding name after clear() was called
2) In clear(String destinationName):
   - never finds bindingName, because supposes usage of destinationName with already added ".destination" suffix
   - even if destinationName is found, the method clears whole map instead clearing of specific BlockingQueue
3) As result, the following scenario occurs:
   - when some Test sends (though InputDestination) first message to specific binding name, the corresponded BlockingQueue is created in OutputDestination
   - then if outputDestination.clear() is called, the BlockingQueue is removed
   - when some next Test sends second message to the same bindingName, the BlockingQueue is never recreated
   - as result NullPointer exception occurs in code of upcoming OutputDestination.receive()

**Comment by olegz** [comment]
Thank you for clearly reporting this issue. It is fixed and back-ported to .3.0.x which we'll be releasing tomorrow. So perfect timing.

**Comment by zinchin** [comment]
Thanks for such a quick fix!

Regards,
Daniel
