### ISSUE TITLE
Documentation refers to deprecated class EmitterProcessor

### ISSUE THREAD

**Issue by ramiloif** [spring-cloud/spring-cloud-stream#2117]
**Describe the issue**
Documentation refers to deprecated class.
In https://github.com/spring-cloud/spring-cloud-stream/blob/master/docs/src/main/asciidoc/spring-cloud-stream.adoc
Added suggestion to use 
`reactor.core.publisher.EmitterProcessor ` which is deprecated since reactor-core version 3.4.2.

**Comment by olegz** [comment]
Resolved with https://github.com/spring-cloud/spring-cloud-stream/commit/73ca65da5d9ac3a822933d9d43c17b790bd33540
