### ISSUE TITLE
Allow binding lifecycle control outside of actuator

### ISSUE THREAD

**Issue by Mrc0113** [spring-cloud/spring-cloud-stream#2119]
Hi, 

It would be ideal if the Cloud Stream framework would allow for binding lifecycle control outside of actuator. This could allow developers to start/stop/pause/resume bindings without the need to include the actuator/web dependencies. 

**This is an enhancement request**

**Comment by garyrussell** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-stream/issues/1907

I copied your text there.

**Comment by Mrc0113** [comment]
Thanks @garyrussell. Sorry I missed that one!

**Comment by olegz** [comment]
Actually, it's my fault since I did remember almost after we finished our call that we already had something open. In any event, this should be easy to address.
