### ISSUE TITLE
TestChannelBinderConfiguration drops half the messages, OutputDestination does not work when a consumer is enabled

### ISSUE THREAD

**Issue by titosatlinkener** [spring-cloud/spring-cloud-stream#2125]
Hi spring-cloud-stream team, I wrote two tests that may point to a possible bug.  I have created a repository with a very simple application and the two tests that illustrate the problems.

the repository is https://github.com/linkener/spring-cloud-stream-test-issues.git

1) When using the TestChannelBinderConfiguration in a SpringBootTest and send multiple messages to the queue, only half the messages are processed, the rest are lost.  

This can be reproduced using the SpringCloudStreamDemoApplicationWithConsumerOnTest.java file.

2) When a consumer is running, calling the OutputDestination's receive method returns null.  If the consumer is disabled then the OutputDestination works as expected.

This can be reproduced using the SpringCloudStreamDemoApplicationWithConsumerOffTest.java file.

To reproduce both errors use mvn clean test

The versions used are
spring-boot 2.4.3
spring-cloud-stream 3.1.1

**Comment by olegz** [comment]
Hey, thanks for reporting it but it was already [reported and addressed](https://github.com/spring-cloud/spring-cloud-stream/issues/2106) and available in the next release. It was also back-ported to a Horsham/Hoxton line

**Comment by titosatlinkener** [comment]
Thank you Oleg, it certainly looks like the same issue.
