### ISSUE TITLE
Exclude Named Functions from Registering with Property

### ISSUE THREAD

**Issue by kevinrlewis** [spring-cloud/spring-cloud-stream#2139]
**Is your feature request related to a problem? Please describe.**
I hit an issue when using spring cloud streams, Kafka binder, and jasypt-spring-boot. Jasypt spring boot auto configures a supplier function that auto creates a topic and started throwing errors attempting to produce configuration messages as avro. 

For reference:
[https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/jasypt-spring-boot/src/main/java/com/ulisesbocchio/jasyptspringboot/configuration/EncryptablePropertyResolverConfiguration.java#L91](EncryptablePropertyResolverConfiguration)
[https://github.com/ulisesbocchio/jasypt-spring-boot/blob/master/jasypt-spring-boot/src/main/java/com/ulisesbocchio/jasyptspringboot/util/Singleton.java#L13](Singleton)

**Describe the solution you'd like**
I would like to be able to exclude a library's defined function based off of a property.

**Describe alternatives you've considered**
Since the library defines the Singleton class as final I am unable to change the class.

To hack a workaround I had to create a no-op function and specify that function under the cloud function definition property. Since I am only using jasypt in my local environment under the local profile, I then just conditionally load the JasyptSpringBootAutoConfiguration based off of the profile. The no-op function still auto creates a kafka topic and polls for messages unnecessarily while my application is running.

**Additional context**
Code to reproduce: [Sample Service](https://github.com/kevinrlewis/sample-service)

**Comment by olegz** [comment]
This did indeed came up before and there are several current workarounds.
1. You can use function auto-configuration exclusion `@SpringBootApplication(exclude = ContextFunctionCatalogAutoConfiguration.class)`
2. You can set `spring.cloud.function.definition=blahblah`, basically to a name that doesn't exist
That said, i believe we should address it in a more formal way; Something like `spring.cloud.stream.function.autodetect=false`.

**Comment by kevinrlewis** [comment]
Yeah there are some workarounds, I have one currently working, but the two you described would ideally be better. Although, I gave those two you listed a shot and both returned errors, which I believe is just from the requirements of my application.

1. `ContextFunctionCatalogAutoConfiguration` exclusion throws an error because `StreamBridge` is based off of that auto configuration.
2. Defining a non-existent function also throws an error during auto configuration as it is looking for a non-existent bean. Is there a soft throw property I'm missing where that should warn instead of throwing an exception?

Thank you for your help! I do like the idea of the autodetect property.

**Comment by olegz** [comment]
I now believe it is is duplicate to https://github.com/spring-cloud/spring-cloud-stream/issues/2035, so will address it there
