### ISSUE TITLE
Docs: information about schema evolution and schema registry missing/broken

### ISSUE THREAD

**Issue by yonigibbs** [spring-cloud/spring-cloud-stream#2140]
I was looking for information about the usage of Spring Cloud Stream with the Kafka Schema Registry and couldn't find any. There seems to be a broken link in the docs, and also what looks like a header section where the markdown isn't quite right. See screenshot below.

I was looking here: https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#spring-cloud-stream-overview-user-defined-message-converters (scroll down a bit to the bottom of that section).

![schema-evolution-and-registry](https://user-images.githubusercontent.com/39593145/111808612-14e21980-88cc-11eb-830f-6be7ea7cbe52.png)

Thanks!

**Comment by yonigibbs** [comment]
Also, I eventually found this: https://spring.io/projects/spring-cloud-schema-registry#learn, but the **Reference Doc** and **API Doc** links there are both broken too. It's not really clear to me if that project is still alive or not.

**Comment by sobychacko** [comment]
@yonigibbs There are some issues currently with the way that docs are rendered. We will try to fix it. You can go here directly to read the current status of the docs: https://github.com/spring-cloud/spring-cloud-schema-registry/blob/master/docs/src/main/asciidoc/spring-cloud-schema-registry.adoc

**Comment by sobychacko** [comment]
@yonigibbs https://spring.io/projects/spring-cloud-schema-registry#learn is updated to reflect the latest snapshot docs. Starting with the next releases, it will update with docs for those releases too.

**Comment by olegz** [comment]
So can we close this?

**Comment by yonigibbs** [comment]
Thanks very much for those links, @sobychacko, that's perfect: exactly what I was looking for.

@olegz: wasn't sure if that question was aimed at me or Soby, but from my point of view, yes, totally, this can be closed now.

Thanks again, folks!
