### ISSUE TITLE
Change in the order of the propertySources in the binderEnvironment

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream#2141]
Spring cloud 2020.0.1.

We have observed a behaviour that we think is not correct and could even lead to some problems... 

When the DefaultBinderFactory creates the binder context from the environment of the main context, the properySources of the binderEnvironment are in a different order than in the main context, with the propertySources application.yml, application.properties and configured profiles properties having lower priority.

For example, if our application has an application.yml and an application-profile1.yml configured, if we look at the propertySources in the binderEnvironment before executing the line https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java#L337 the propertySources are as follows in this order: 

```
propertySourceList = {CopyOnWriteArrayList@11113}  size = 10
 0 = {MapPropertySource@11086} "MapPropertySource {name='defaultBinderFactoryProperties'}"
 1 = {PropertiesPropertySource@11087} "PropertiesPropertySource {name='systemProperties'}"
 2 = {SystemEnvironmentPropertySource@11088} "SystemEnvironmentPropertySource {name='systemEnvironment'}"
 3 = {PropertySource$StubPropertySource@11118} "StubPropertySource@1964545881 {name='servletConfigInitParams', properties=java.lang.Object@3eed3beb}"
 4 = {ServletContextPropertySource@11119} "ServletContextPropertySource@9443599 {name='servletContextInitParams', properties=org.apache.catalina.core.ApplicationContextFacade@1e2314a1}"
 5 = {RandomValuePropertySource@11120} "RandomValuePropertySource@2022545513 {name='random', properties=java.util.Random@7e8d1dc5}"
 6 = {OriginTrackedMapPropertySource@11121} "OriginTrackedMapPropertySource@1455854485 {name='Config resource 'class path resource [application-profile1.yml]' via location 'optional:classpath:/''}"
 7 = {OriginTrackedMapPropertySource@11122} "OriginTrackedMapPropertySource@62319110 {name='Config resource 'class path resource [application.yml]' via location 'optional:classpath:/''}"
 9 = {ManagementContextAutoConfiguration$SameManagementContextConfiguration$1@11124} "@1663123801 {name='Management Server', properties=java.lang.Object@577361e1}"
```

and after executing it the propertySources of the binderEnvironment are:

```
propertySourceList = {CopyOnWriteArrayList@11113}  size = 12
 0 = {ConfigurationPropertySourcesPropertySource@11383} "ConfigurationPropertySourcesPropertySource {name='configurationProperties'}"
 1 = {SimpleCommandLinePropertySource@11384} "SimpleCommandLinePropertySource {name='commandLineArgs'}"
 2 = {MapPropertySource@11084} "MapPropertySource {name='defaultBinderFactoryProperties'}"
 3 = {PropertiesPropertySource@11085} "PropertiesPropertySource {name='systemProperties'}"
 4 = {SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource@11385} "OriginAwareSystemEnvironmentPropertySource {name='systemEnvironment'}"
 5 = {PropertySource$StubPropertySource@11087} "StubPropertySource {name='servletConfigInitParams'}"
 6 = {ServletContextPropertySource@11088} "ServletContextPropertySource {name='servletContextInitParams'}"
 7 = {RandomValuePropertySource@11089} "RandomValuePropertySource {name='random'}"
 8 = {MapPropertySource@11091} "MapPropertySource {name='kafkaBinderDefaultProperties'}"
 9 = {ManagementContextAutoConfiguration$SameManagementContextConfiguration$1@11092} " {name='Management Server'}"
 10 = {OriginTrackedMapPropertySource@11432} "OriginTrackedMapPropertySource@132041546 {name='Config resource 'class path resource [application-profile1.yml]' via location 'optional:classpath:/''}"
 11 = {OriginTrackedMapPropertySource@11433} "OriginTrackedMapPropertySource@1192645418 {name='Config resource 'class path resource [application.yml]' via location 'optional:classpath:/''}"
```

 where application-profile1.yml and application.yml have lower priority.

 Is this the expected behaviour?

**Comment by olegz** [comment]
Not sure what to say here. .  as you can see form the code we don't have any influence on property sources as they come from boot

**Comment by ferblaca** [comment]
Hi @olegz!!

Maybe the example I have given is not the best, but if the application drags more propertySources from other dependencies in a transitive way and in the main context of the application, the propertySources "application.yml" and "application-profile1.yml" have more priority than these, when the subcontext binder is created (in a multibinder context), in binderEnvironment does not have the propertySources in the same order, being the application.yml and application-profile.yml with less priority.

In our opinion, the fact that the main application context and the binder subcontext do not have the same priority order of propertySources could lead to potential errors in property value resolution.

On the other hand, not is a spring-cloud-stream malfunction, since the whole thing happens in "org.springframework.boot.builder.SpringApplicationBuilder", but we think it is possible that it could directly affect spring-cloud-stream operation.

If you don't see any problem with this, feel free to close the issue :)

**Comment by olegz** [comment]
Thanks @ferblaca 
Thinking about it some more, this indeed could be an issue for us even though we are not directly involved in it. So i'll keep this open for now and will reach out to boot team to discuss.

**Comment by olegz** [comment]
Actually i believe it was indirectly fixed by https://github.com/spring-cloud/spring-cloud-stream/commit/7c384e7c091042dc725705a6b52ce615b37f7c79 since the logic of how binder specific context is created has been changed and it is now using the same property sources as parent with the addition of binder specific.

Please feel free to reopen it if the issue persist.
