### ISSUE TITLE
Documentation for resetoffsets is not clear

### ISSUE THREAD

**Issue by ToffeeLu** [spring-cloud/spring-cloud-stream#2149]
In latest version of [documentation](https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html), the description for **resetoffset** is:

> Whether to reset offsets on the consumer to the value provided by startOffset. Must be false if a KafkaRebalanceListener is provided; see Using a KafkaRebalanceListener.
> Default: false.

But according to answers in below two questions:
1. https://stackoverflow.com/questions/53467918/spring-cloud-stream-2-0-and-startoffset-latest
2. https://stackoverflow.com/questions/55029402/will-spring-cloud-stream-kafka-consumer-not-consume-messages-that-were-sent-when

It's obvious that user should not set `resetoffsets=true`, otherwise when service restart or down, the un-consumed Kafka message will be missed.

From what I understand, `startOffset` is only designed for new groups, but some how magic happens if  `resetoffsets=true`

So I suggest to **at least add a warning to indicate if you set `resetoffsets`, it will has impact when service restart**.

**Comment by garyrussell** [comment]
That is not the latest documentation; see https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.1.3-SNAPSHOT/reference/html/spring-cloud-stream-binder-kafka.html#reset-offsets

**Comment by ToffeeLu** [comment]
@garyrussell Thanks, glad to see it's updated in SNAPSHOT document.
Somehow this paragraph indicates:
> When resetOffsets is true, the binder applies similar semantics to those that apply when there is no committed offset on the broker, as if this binding has never consumed from the topic; i.e. **any current committed offset is ignored**.

Can I also understand as in common use cases, for an **existing** consumer group, I should set `resetOffsets=false` to not miss any message and `startOffset` only effects if it's a new consumer group?

**Comment by garyrussell** [comment]
Yes; the most common use case is to leave it at its default `false`; there is no need to explicitly set it so.

**Comment by ToffeeLu** [comment]
Thanks @garyrussell , I think the new document it good.
