### ISSUE TITLE
Test Binder OutputDestination queue populated only on StreamBridge interaction

### ISSUE THREAD

**Issue by poznachowski** [spring-cloud/spring-cloud-stream#2152]
Hi, the case I have is as below:

1. Application is listening for incoming messages (with `Consumer` bean)
2. Message data is then stored and processed asynchronously (with `@Scheduled`).
3. When a specific condition is met (during processing) a message is published using `StreamBridge` concept.

Now I'm testing it with the test binder approach. It's as simple as:

```
input.send(incomingMessage(), "incoming-destination-name");
var publishedMessage = output.receive(5000, "binding-name");
```
However it throws NPE (or array out of bound if I use output.receive(5000) without the binding).
From my understanding the `messageQueue` in `OutputDestination` is added only when `StreamBridge` tries to send out the message. With the timeout property I was rather expecting that it could wait until everything (test infra and message) is ready.

My current workaround is to use awaitility and ignore NPEs:

```
var message = await()
                .ignoreException(NullPointerException.class)
                .atMost(5, TimeUnit.SECONDS)
                .until(() -> output.receive(
                        0,
                        "binding-name"
                ), Objects::nonNull);
```
 
Is it possible to change the behavior, so the queues are prepared beforehand in StreamBridge situation or the timeout provided would effectively wait and won't be interrupted by test infra not being ready yet?
Is it possible to publish source jar for the test-binder?
 
Spring Boot 2.5.0-RC1
Spring Cloud Stream 3.1.2

**Comment by olegz** [comment]
Interesting case. Didn't think of that. . .
