### ISSUE TITLE
Blog titles are inverted in Spring Cloud Stream main page

### ISSUE THREAD

**Issue by hzendejas** [spring-cloud/spring-cloud-stream#2163]
Here are blog titles:

Event-driven microservices with Spring Cloud Stream (June 5, 2020 - Piotr Minkowski)

Event-driven applications with Spring Cloud Stream(June 24, 2020 - Anshul Mishra)

Check articles content, and you'll see.

**Comment by sabbyanandan** [comment]
Thanks for reporting. @olegz is on it.
