### ISSUE TITLE
Remove Obsolete Docs  (i.e., Pollable Consumers, BinderAwareChannelResolver etc)

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2164]
https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#_functional_binding_names

Scroll down to `Pollable Destination Binding`.

New docs here: https://docs.spring.io/spring-cloud-stream/docs/3.1.2/reference/html/spring-cloud-stream.html#spring-cloud-streams-overview-using-polled-consumers

**Comment by olegz** [comment]
Basically use this issue to go over the docs and clean what's no longer applicable and/or deprecated
