### ISSUE TITLE
Add Option to Not Create an Output Binding for the RoutingFunction

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2168]
See https://stackoverflow.com/questions/67419839/spring-cloud-stream-functionrouter-output-attempts-to-bind-to-kafka-topic

Verified when destination functions are all `Consumer`s.

```java
@SpringBootApplication
public class So67419839Application {

	public static void main(String[] args) {
		SpringApplication.run(So67419839Application.class, args);
	}

	@Bean
	MessageRoutingCallback route() {
		return msg -> new String((byte[]) msg.getPayload()).equals("foo") ? "foo" : "bar";
	}

	@Bean
	Consumer<Message<?>> foo() {
		return msg -> System.out.println("foo: " + msg);
	}

	@Bean
	Consumer<Message<?>> bar() {
		return msg -> System.out.println("bar: " + msg);
	}

}
```
```properties
spring.cloud.function.definition=functionRouter
spring.cloud.stream.bindings.functionRouter-in-0.destination=so67419839
spring.cloud.stream.bindings.functionRouter-in-0.group=so67419839
```
```
$ kafka-topics --bootstrap-server localhost:9092 --list
__consumer_offsets
functionRouter-out-0
so67419839
```

**Comment by garyrussell** [comment]
But I see that it is needed if at least one of the delegates is a function:

```java
	@Bean
	Function<Message<?>, String> foo() {
		return msg -> {
			System.out.println("foo: " + msg);
			return "FOO";
		};
	}
```

So we probably need a new property to suppress it, I don't see how we could deterministically determine that all delegates are `Consumer`s.

**Comment by garyrussell** [comment]
As a work around simply point it to the same destination

```poperties
spring.cloud.function.definition=functionRouter
spring.cloud.stream.bindings.functionRouter-in-0.destination=so67419839
spring.cloud.stream.bindings.functionRouter-out-0.destination=so67419839
spring.cloud.stream.bindings.functionRouter-in-0.group=so67419839
spring.cloud.stream.function.routing.enabled=true
```

Since the delegates are all `Consumer`s we'll never actually send anything.

**Comment by olegz** [comment]
So if I understand correctly. . .
First, I just added a test to validate the routing itself and it works
```
@Test
public void testRoutingToConsumers() {
	try (ConfigurableApplicationContext context = new SpringApplicationBuilder(
			TestChannelBinderConfiguration.getCompleteConfiguration(
					RoutingConsumerConfiguration.class))
						.web(WebApplicationType.NONE)
						.run("--spring.jmx.enabled=false",
						"--spring.cloud.function.routing-expression=headers['func_name']")) {

		InputDestination inputDestination = context.getBean(InputDestination.class);
		Message<byte[]> inputMessage = MessageBuilder
					.withPayload("foo".getBytes())
					.setHeader("func_name", "foo")
					.build();
			inputDestination.send(inputMessage);
	}
}

@EnableAutoConfiguration
public static class RoutingConsumerConfiguration  {
		@Bean
		public Consumer<String> foo() {
			return System.out::println;
		}
		@Bean
		public Consumer<String> bar() {
			return System.out::println;
		}
}
```

However, and that is what I believe you're saying is that the fact that RoutingFunction is a function it automatically creates an output binding even though there will never be an output.
Correct?

**Comment by garyrussell** [comment]
Exactly, yes. 

I don't see how we can programmatically detect that the function never routes to another function (only `Consumer`s), I think we need a property, something like:

    spring.cloud.stream.function.routing.consume-only=true

By the way, the docs talk about `spring.cloud.stream.function.routing.enabled=true` which doesn't seem to be needed.

**Comment by olegz** [comment]
Ok, it appears that it can work. Just spiked it up and all tests are passing

Basically the idea is to never create output binding for `RoutingFunction`, only input. In the event the routing is to the Consumer, we're good and if it is to Function, then StreamBridge is going to be used to effectively create an output binding on demand.

Will sleep on it and merge tomorrow
