### ISSUE TITLE
ChannelInterceptors are added automatically to all channels dyanmically created by StreamBridge class

### ISSUE THREAD

**Issue by ghilainm** [spring-cloud/spring-cloud-stream#2172]
**Describe the issue**
I have created a channel interceptor implementing 'org.springframework.messaging.support.ChannelInterceptor' and annotated it with @Component. 

The interceptor is automatically added to all the SpringCloudStream created channels.

I would have expected it to be attached to none of the channels.

Seems to be a related issue: using @GlobalChannelInterceptor with pattern does not work either, the pattern is ignored.

**Version of the framework**
org.springframework.cloud:spring-cloud-stream-binder-kafka-core:3.0.12.RELEASE=compileClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
org.springframework.cloud:spring-cloud-stream-binder-kafka:3.0.12.RELEASE=compileClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
org.springframework.cloud:spring-cloud-stream:3.0.12.RELEASE=compileClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath

**Additional context**
This part of the code in StreamBridge class seems to be the culprit!

```
private void addInterceptors(AbstractMessageChannel messageChannel) {
		String[] interceptorNames = this.applicationContext.getBeanNamesForType(ChannelInterceptor.class);
		List<ChannelInterceptor> interceptors = messageChannel.getInterceptors();
		for (String interceptorName : interceptorNames) {
			ChannelInterceptor interceptor = this.applicationContext.getBean(interceptorName, ChannelInterceptor.class);
			if (!CollectionUtils.containsInstance(interceptors, interceptor)) {
				messageChannel.addInterceptor(interceptor);
			}
		}
	}
```

**Comment by olegz** [comment]
Can you please explain the reason for the channel interceptor so we can possibly suggest a better approach. 

The main issue is that channels in the context of s-c-stream is the internal implementation detail. Should never have been exposed. In addition, not every binder is channel based, hence the interceptor approach is not consistent

**Comment by ghilainm** [comment]
@olegz I want to filter messages based on a Kafka Header. Only messages with a header having some value should be processed by the application.

**Comment by olegz** [comment]
what about the other messages? dropped? rerouted?

**Comment by ghilainm** [comment]
Problem is when using routing function, this is quite high lvl API. I would like to drop the message as fast as possible.

I have asked a question on stackoverflow about this -> https://stackoverflow.com/questions/26485329/kafka-high-level-vs-low-level-consumer

**Comment by olegz** [comment]
I am not sure what you mean by `quite high lvl API` and why do you think interceptor approach would be faster given that it involves under the hood a bit more then RoutingFunction.

Another approach is to use function composition which will accomplish the same as interceptor (less channel and dispatcher)

**Comment by ghilainm** [comment]
I wasn’t sure. Just a feeling.

Another approach would be as mentioned on stackoverflow a RecordInterceptor added on KafkaContainerListener.

Wouldn’t that one be faster ?

**Comment by olegz** [comment]
I don't know what `faster` means.

**Comment by olegz** [comment]
Closing it due to lack of follow up form the original reporter

**Comment by FancyFennec** [comment]
I had this exact issue when using Spring Integration together with Spring Cloud Stream. The LoggingHandler from an IntegrationFlow get added when the StreamBridge calls the send method. Then every LoggingHandler will get called that was added in an IntegrationFlow.

**Comment by olegz** [comment]
First, please do not comment on closed issues. It's better to open a new one.

Also, you should stop using interceptors all together since a) they imply awareness about channels that may not be present in every binder; b) there is a better way of applying cross cutting functionality via [function composition](https://docs.spring.io/spring-cloud-stream/docs/3.1.3/reference/html/spring-cloud-stream.html#_functional_composition). 

The last point implies that you are no longer using annotation-based programming model (e.g., `@StreamListener`) and instead using [functional programming model](https://docs.spring.io/spring-cloud-stream/docs/3.1.3/reference/html/spring-cloud-stream.html#spring_cloud_function). If you do be aware that it has been long deprecated and will not be supported in the future.
