### ISSUE TITLE
Spring Integration LoggingHandlers are called when StreamBridge sends

### ISSUE THREAD

**Issue by FancyFennec** [spring-cloud/spring-cloud-stream#2180]
Hi there, this is the first time I am reporting an issue. I hope this is the correct place for it.
I have found a strange behaviour today when using a StreamBridge together with Spring Integration. 
If a LoggingHandler is defined in an IntegrationFlow, then any LoggingHandler defined in any flow will get called by a StreamBridge when the send method is called.
Here are the dependencies:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.6</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<solace-spring-cloud.version>2.0.0</solace-spring-cloud.version>
		<spring-cloud.version>2020.0.2</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.solace.spring.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-solace</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
			<scope>test</scope>
			<classifier>test-binder</classifier>
			<type>test-jar</type>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.solace.spring.cloud</groupId>
				<artifactId>solace-spring-cloud-bom</artifactId>
				<version>${solace-spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```
The application.yml
```
server:
  port : 8081
spring:
  cloud:
    stream:
      bindings:
        outgoing-out-0:
          destination: topic
          binder: solace-broker
      binders:
        solace-broker:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: admin
                clientPassword: admin
```
And the actual code:
```
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@Bean
	MessageChannel inputChannel() {
		return new DirectChannel();
	}

	@Bean
	MessageChannel otherInputChannel() {
		return new DirectChannel();
	}

	@Bean
	public IntegrationFlow someFlow(MessageHandler sendMessage) {
		return IntegrationFlows.from(inputChannel())
				.log(LoggingHandler.Level.INFO, (m) -> "Going through the first flow: " + m.getPayload())
				.handle(sendMessage)
				.get();
	}

	@Bean
	public IntegrationFlow someOtherFlow(MessageHandler sendMessage) {
		return IntegrationFlows.from(otherInputChannel())
				.log(LoggingHandler.Level.INFO, (m) -> "Going through the second flow: " + m.getPayload())
				.handle(sendMessage)
				.get();
	}

	@Bean
	public MessageHandler sendMessage(StreamBridge streamBridge) {
		return message -> {
			streamBridge.send("outgoing-out-0", message);
		};
	}
}
```
If the flow "someFlow" gets executed it will also call the LoggingHandler in the other flow when the StreamBridge sends the message.
```
2021-05-28 23:18:58.156  INFO 9764 --- [nio-8081-exec-3] o.s.integration.handler.LoggingHandler   : Going through the first flow: test
2021-05-28 23:18:58.157  INFO 9764 --- [nio-8081-exec-3] o.s.integration.handler.LoggingHandler   : Going through the first flow: [B@26cd581d
2021-05-28 23:18:58.157  INFO 9764 --- [nio-8081-exec-3] o.s.integration.handler.LoggingHandler   : Going through the second flow: [B@26cd581d
```
I am not sure if this behaviour is intentional.

**Comment by sobychacko** [comment]
@FancyFennec Yes, this is the right place for this. Are you sure that nothing gets triggered through the `otherInputChannel`? That is the only way that I can see that flow gets initiated.

**Comment by FancyFennec** [comment]
@sobychacko Thanks for the reply... I called the input channel directly.
`@PostMapping("/test")
    public void process(@RequestBody String payload) {
        inputChannel.send(MessageBuilder.withPayload(payload).build());
    }`
The other input channel doesn't get called. It seems to be just the LoggingHandler. This also happens if I just call the send method of the StreameBridge. It will then loop through all the logging handlers and call them.

**Comment by kosmos955** [comment]
Hello, previously interceptor was checked for the fact that it is already bound to the channel, but now globalChannelInterceptorProcessor doesn't do this. Why is it done like this?

**Comment by olegz** [comment]
I am not sure I follow your comment. This issue has been addressed and closed. If you believe there is another issue, please provide a way to reproduce it and raise a new ticket.

**Comment by kosmos955** [comment]
I'm trying to understand, why you removed the code, that did the check, I mentioned above

**Comment by olegz** [comment]
please be more specific. I am not sure what code you are referring to

**Comment by kosmos955** [comment]
`private void addInterceptors(AbstractMessageChannel messageChannel) {
		String[] interceptorNames = this.applicationContext.getBeanNamesForType(ChannelInterceptor.class);
		List<ChannelInterceptor> interceptors = messageChannel.getInterceptors();
		for (String interceptorName : interceptorNames) {
			ChannelInterceptor interceptor = this.applicationContext.getBean(interceptorName, ChannelInterceptor.class);
			if (!CollectionUtils.containsInstance(interceptors, interceptor)) {
				messageChannel.addInterceptor(interceptor);
			}
		}`

that part

**Comment by olegz** [comment]
Nothing is removed, some code has been restructured and delegated to `globalChannelInterceptorProcessor` - https://github.com/spring-cloud/spring-cloud-stream/pull/2186/files#diff-b7f50cd87cb612e86928aac0827858988ee0a8d2463362064f21e538b5ca3cc4R263

**Comment by kosmos955** [comment]
But globalChannelInterceptorProcessor doesn't contain interceptors reference check

**Comment by olegz** [comment]
I must be missing something still, so can you please provide me with the test case that demonstrates the problem you are trying to point out?
