### ISSUE TITLE
BinderErrorChannel contrustor error?

### ISSUE THREAD

**Issue by CrazySabri** [spring-cloud/spring-cloud-stream#2188]
class BinderErrorChannel extends PublishSubscribeChannel
		implements LastSubscriberAwareChannel {

        ......

	BinderErrorChannel() {
		super(true);
	}
}

public class PublishSubscribeChannel extends AbstractExecutorChannel implements BroadcastCapableChannel {

	public PublishSubscribeChannel() {
		this(null);
	}

	public PublishSubscribeChannel(@Nullable Executor executor) {
		super(executor);
		this.dispatcher = new BroadcastingDispatcher(executor);
	}
}

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.cloud.stream.binder.BinderErrorChannel.<init>(BinderErrorChannel.java:41)

The following method did not exist:

    org.springframework.integration.channel.PublishSubscribeChannel.<init>(Z)V

The method's class, org.springframework.integration.channel.PublishSubscribeChannel, is available from the following locations:

    jar:file:/D:/maven/repository/org/springframework/integration/spring-integration-core/5.4.2/spring-integration-core-5.4.2.jar!/org/springframework/integration/channel/PublishSubscribeChannel.class

The class hierarchy was loaded from the following locations:

    org.springframework.integration.channel.PublishSubscribeChannel: file:/D:/maven/repository/org/springframework/integration/spring-integration-core/5.4.2/spring-integration-core-5.4.2.jar
    org.springframework.integration.channel.AbstractExecutorChannel: file:/D:/maven/repository/org/springframework/integration/spring-integration-core/5.4.2/spring-integration-core-5.4.2.jar
    org.springframework.integration.channel.AbstractSubscribableChannel: file:/D:/maven/repository/org/springframework/integration/spring-integration-core/5.4.2/spring-integration-core-5.4.2.jar
    org.springframework.integration.channel.AbstractMessageChannel: file:/D:/maven/repository/org/springframework/integration/spring-integration-core/5.4.2/spring-integration-core-5.4.2.jar
    org.springframework.integration.context.IntegrationObjectSupport: file:/D:/maven/repository/org/springframework/integration/spring-integration-core/5.4.2/spring-integration-core-5.4.2.jar

**Comment by CrazySabri** [comment]
spring-cloud-starter-stream-rabbit:3.1.2

**Comment by CrazySabri** [comment]
<dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-core</artifactId>
            <version>5.5.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
            <version>3.1.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.integration</groupId>
                    <artifactId>spring-integration-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

then work well

**Comment by olegz** [comment]
Part of the issue is that you are managing your dependency manually instead of letting BOM manage it for you which is how it was intended. And because of that you are using older version of Spring Integration than the one expected by spring cloud stream.
