### ISSUE TITLE
Content Type Header is no longer set by default

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-stream#2190]
The current version of spring cloud stream behaves differently with respect to setting `MessageHeaders.CONTENT_TYPE` header in the output message. Previous versions did provide the header, as illustrated in this [test](https://github.com/dturanski/stream-applications/blob/migrate-integration-tests/applications/stream-applications-integration-tests/src/test/java/org/springframework/cloud/stream/app/integration/test/processor/httprequest/HttpRequestProcessorTests.java#L85).  Not critical but submitting this in case it is considered a regression.

**Comment by dturanski** [comment]
Long story why I was checking for content type header in the first place, it's not relevant to the test. So I discovered this issue by accident.

**Comment by olegz** [comment]
I know what the issue is/was and it was addressed as part of another issue
