### ISSUE TITLE
No converter found capable of converting from type [java.lang.String] to type [org.springframework.expression.Expression]

### ISSUE THREAD

**Issue by samragu** [spring-cloud/spring-cloud-stream#2194]
The issue raised in #1979 is back in spring-cloud 2020.0.3 which includes spring-cloud-stream:Horsham.SR13. This worked fine up to spring-cloud:2020.0.2. Tried with spring-boot 2.5.2 as well as 2.5.0

**Comment by samragu** [comment]
[spring-cloud-stream-issue-2194.zip](https://github.com/spring-cloud/spring-cloud-stream/files/6825349/spring-cloud-stream-issue-2194.zip)
Adding a modified sample from issue #1979 to reproduce the issue with spring-boot 2.5.2 and spring-cloud:2020.0.3

**Comment by mmaeller** [comment]
Hi @samragu , see https://github.com/spring-cloud/spring-cloud-stream/issues/2189
Will be fixed with next release.

**Comment by olegz** [comment]
Yes indeed, so I am going to close it as it has already been resolved

**Comment by raszkiewicz** [comment]
I have the same problem. Which release it was fixed?
