### ISSUE TITLE
StreamBridge works incorrect, if producer is partitioned 

### ISSUE THREAD

**Issue by LazyEntity** [spring-cloud/spring-cloud-stream#2196]
StreamBridge cant work with more than one producer correctly.
when service has more than one producer, and any of them has filled partitionKeyExpression property or partitionKeyExtractorName property, then this configuration properties used by another producers too. 
Also StreamBridge not thread safe right now.

<img width="1374" alt="Screenshot 2021-07-14 at 17 30 35" src="https://user-images.githubusercontent.com/50443844/125640099-4fcc1ec8-9ce3-4c13-b708-7e15469c06ba.png">

As you can see on this picture (step 1) streamBridge get function for invocation from fuctionCatalog, and this function used for all producers.
step 2 if producer is partitioned, then function got wrapped.
step 3 function invoked. 

<img width="1227" alt="Screenshot 2021-07-14 at 16 42 42" src="https://user-images.githubusercontent.com/50443844/125640786-442969e0-266a-4112-bc9c-190487997e06.png">

Here we can see logic of wrapper.
step 1. initializing of enricher that has partition logic. function here is streamBridge function from fuctionCatalog.
step 2 . before function got invoked, wrapper set enhancer to this function.
step 3. setting enhancer field in streamBridge function. 
Last step is a problem step. Because streamBridge function one for all producers, this enhancer used by every one of producers, what means that producer without partitioned settings will be partitioned, but with settings of another producer.
And if streamBridge send messages to two different partitioned producers in multiple threads, will lead to race condition. 

version 3.1.3
Expected behavior: settings for different producers  work separately.

**Comment by olegz** [comment]
So the logic you are referring to has changed recently due to a fix for an unrelated issue. I've modified the test to ensure it validates multiple producers with different partition configurations
