### ISSUE TITLE
Application fail to start after upgrading to spring boot version 2.5.3

### ISSUE THREAD

**Issue by pitinga** [spring-cloud/spring-cloud-stream#2211]
My application fail to start after upgrading to spring boot version 2.5.3.

It is a simple application created using "Spring Initializr":
- Gradle 7.1.1
- JDK 11
- Spring Boot 2.5.3
- Spring Cloud 2020.0.3
- Dependecy: spring-cloud-starter-bus-amqp

Using Spring Boot 2.5.2 works fine. After migrating to Spring Boot 2.5.3 the Spring Cloud Bus stop working. Are they compatible? 

Attached exemplo requires RabbitMQ at localhost:5672. There are two very simples projects with only "spring-cloud-starter-bus-amqp". One using Spring Boot 2.5.2 and the other 2.5.3.

[spring-cloud-bus.zip](https://github.com/spring-cloud/spring-cloud-bus/files/6977129/spring-cloud-bus.zip)

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createConsumerEndpoint(RabbitMessageChannelBinder.java:517)

The following method did not exist:

    org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.<init>(Lorg/springframework/amqp/rabbit/listener/AbstractMessageListenerContainer;)V

The method's class, org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter, is available from the following locations:

    jar:file:/C:/Users/abnerp/.gradle/caches/modules-2/files-2.1/org.springframework.integration/spring-integration-amqp/5.5.2/7195ed265b0f6c24e52c3ed84253f7974b2d5014/spring-integration-amqp-5.5.2.jar!/org/springframework/integration/amqp/inbound/AmqpInboundChannelAdapter.class

The class hierarchy was loaded from the following locations:

    org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter: file:/.gradle/caches/modules-2/files-2.1/org.springframework.integration/spring-integration-amqp/5.5.2/7195ed265b0f6c24e52c3ed84253f7974b2d5014/spring-integration-amqp-5.5.2.jar
    org.springframework.integration.endpoint.MessageProducerSupport: file:/.gradle/caches/modules-2/files-2.1/org.springframework.integration/spring-integration-core/5.5.2/d6822cb2d758d2a5d821879778c31120b4a3c86c/spring-integration-core-5.5.2.jar
    org.springframework.integration.endpoint.AbstractEndpoint: file:/.gradle/caches/modules-2/files-2.1/org.springframework.integration/spring-integration-core/5.5.2/d6822cb2d758d2a5d821879778c31120b4a3c86c/spring-integration-core-5.5.2.jar
    org.springframework.integration.context.IntegrationObjectSupport: file:/.gradle/caches/modules-2/files-2.1/org.springframework.integration/spring-integration-core/5.5.2/d6822cb2d758d2a5d821879778c31120b4a3c86c/spring-integration-core-5.5.2.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter

**Comment by artembilan** [comment]
Known issue: https://github.com/spring-projects/spring-integration/issues/3606. Or do workaround, or wait for releases this week.

thanks for understanding !
