### ISSUE TITLE
Use ObjectMapper from Application context instead of creating one

### ISSUE THREAD

**Issue by erizzo** [spring-cloud/spring-cloud-stream#2215]
Reference SO discussion: https://stackoverflow.com/q/68910090/639520

There are some places in the binding code where the Jackson `ObjectMapper` from the application context (DI container) is not being used, they are creating new instances directly. This results in application-wide `ObjectMapper` configuration to not be applied in those places.
According to @olegz at least the following places should get `ObjectMapper` from context:

- AbstractMessageChannelBinder
- BindingService
- BindingsLifecycleController

I also suspect that there may be some classes in the Kafka Binder implementation that also ignore the context `ObjectMapper`, but I'm not sure if that should be reported here or elsewhere (or even if that is true).

**Comment by felixgborrego** [comment]
Leaving my 2 cents, we faced a very similar issue with Kafka and I think we found a workaround.

There is an [undocumented way ](https://github.com/spring-cloud/spring-cloud-stream/blob/main/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ContentTypeConfiguration.java#L45)to provide a custom `ObjectMapper`.

```java
  @Bean
  @Primary
  public ObjectMapper objectMapperObjectProvider() {
    var mapper = new ObjectMapper();
    mapper.findAndRegisterModules();
    return mapper;
  }
```

**Comment by maxxis95** [comment]
@olegz sorry for bothering you, did I catch it right? you revert commit which solved that bug cuz new reported bug from: 
Calling the actuator bindings endpoint causes infinite recursion #2253?
if that's true, pls tell me how I can solve that problem?

**Comment by olegz** [comment]
What problem? The recursion was fixed. Are you still having an issue?

**Comment by maxxis95** [comment]
> What problem? The recursion was fixed. Are you still having an issue?

Yes, I'm still having a problem of useage new object mapper during deserialization instead custom configured object mapper bean

**Comment by olegz** [comment]
Please be more specific. I don't know your app or what versions of what you are using. . I have no idea what problem you are referring to, nor do i have a way to reproduce it. 
Can you create a small project and link to it so i can tale a look?
