### ISSUE TITLE
StreamBridge is injecting unrelated interceptors on dynamically created channels

### ISSUE THREAD

**Issue by lkonstantinov** [spring-cloud/spring-cloud-stream#2219]
I have an application that uses Spring Cloud Streams to publish data on dynamic topics using the `spring.cloud.stream.sendto.destination` header. 

At the same time, the application uses sprint-security-messaging and thus I have some security interceptors autoconfigured. One of those is ChanneSecurityInterceptor which extends AbstractSecurityInterceptor (https://github.com/spring-projects/spring-security/blob/main/core/src/main/java/org/springframework/security/access/intercept/AbstractSecurityInterceptor.java) 

When StreamBridge creates a dynamic channel it attaches all available ChannelInterceptor's hence triggering  the AbstractSecurityInterceptor. Unfortunately, the it requires an authentication object attached to the security context, which is (of course) missing. This throws an exception and nothing is being sent.

Looking at the channels that are created via configuration, there are no interceptors attached, so I am not sure why StreamBridge has this behaviour.

Can you please provide some mechanism, so this is configurable? 

Meanwhile I've worked around this by manually modifying the security context before sending the message, but this is very clunky and doesnt work with reactive suppliers as the Flux/Mono is polled on another thread.

Spring Cloud Streams version is 3.1.3 and Spring Security Messaging version is 5.5.0

**Comment by sobychacko** [comment]
@lkonstantinov We made some changes for `StreamBridge` around channel interceptors in the `3.1.4` release. Could you upgrade your Spring Cloud Stream version to `3.1.4` and try this again? Here are the corresponding [docs](https://docs.spring.io/spring-cloud-stream/docs/3.1.4/reference/html/spring-cloud-stream.html#_using_channel_interceptors_with_streambridge).
