### ISSUE TITLE
Exceptions thrown from a consumer are logged since 1.3.3+ instead of rethrown when using the test binder's inputDestination

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-stream#2248]
With Spring Cloud Stream 3.1.2 the following the following code would properly verify that an expected exception was thrown in a consumer : 
```java
    @Test
    void test() {
        MessagingException e = assertThrows(MessagingException.class, //
                () -> inputDestination.send(MessageBuilder.withPayload("dummy").build()));
        assertThat(e.getCause().getMessage()).isEqualTo("something");
    }
```

this does not work since version 3.1.3 anymore. I see the exception is logged by LoggingHandler, but inputDestination.send does not throw an exception anymore.

I have a repro here : https://github.com/snussbaumer/repro-input-destination-with-exception/blob/master/src/test/java/com/example/reproinputdestinationwithexception/ReproInputDestinationWithExceptionApplicationTests.java

You can just force the version to 3.1.2 in pom.xml and the test will pass.

**Comment by olegz** [comment]
Actually, the behavior you observed in 3.1.2 was a bug given the async nature of relationship between the binder and sender where `InputDestination` simply represents a way top emulate user posting a Message to a queue.
So the current behavior is correct - no exception should ever be thrown from the `send` method.
If you want to check for errors, you can use `TestChannelBinder.getLastError()` method

**Comment by snussbaumer** [comment]
Thanks for the response. 

But TestChannelBinder.getLastError() returns a message, not an exception. Is there a way to get the actual exception that was thrown ?

**Comment by olegz** [comment]
Yes, the `getLastError() ` returns `ErrorMessage` with payload of type `Throwable` which is the actual exception that occurred. Additionally you there is `getOriginalMessage` method that will give you the actual 'original' message that triggered the exception.
