### ISSUE TITLE
When no partition-key-expression is defined for a producer, a partition-key-expression from another producer may be picked

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-stream#2249]
This leads unsurprisingly to "Partition key cannot be null" exceptions, and anyways it's quite a random behaviour.

A workaround is to force a partition-key-expression on something (payload for instance), but this should not be necessary.

I have a simple repro here : https://github.com/snussbaumer/repro-partition-key-expression-dj/blob/master/src/test/java/com/example/reproinputdestinationwithexception/ReproPartitionKeyExpressionDJ.java

**Comment by olegz** [comment]
@snussbaumer Thank you for the test that reproduces the issue. Next time if it's easier you can submit a failing test as a PR as it will cut down some time on fixing it ;)
