### ISSUE TITLE
Partition header not set for data sent to pre-created output bindings with native encoding enabled

### ISSUE THREAD

**Issue by skomarica** [spring-cloud/spring-cloud-stream#2263]
If we:

1. declare a source via `spring.cloud.stream.source` so that the output binding gets pre-created
2. set `partition-key-expression`
3. enable `use-native-encoding` for a producer
4. send a message to the output binding via StreamBridge,

the partition header won't be populated.

I understand the framework [skips output conversion](https://github.com/spring-cloud/spring-cloud-stream/blob/a1741794edc1197ff4e9967d4c928c77b974a854/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L232) if native encoding is enabled, but I'm not sure if the intention was to skip setting a partition key as well, since these two things worked independently with the "old" style.

Also, the partition key is correctly set if we don't declare source in the configuration upfront (dynamic destinations), since the message channels that are not found in the pre-created `channelCache` get [properly initialised](https://github.com/spring-cloud/spring-cloud-stream/blob/a1741794edc1197ff4e9967d4c928c77b974a854/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/StreamBridge.java#L279) within the StreamBridge.resolveDestination method.

I don't have enough context to provide a solution, but I hope this failing test may cut down some fixing time: https://github.com/skomarica/spring-cloud-stream/commit/0302514645f2bc11747d180025470da4db3499bd

Thank you for the great work and support, guys!

**Comment by sobychacko** [comment]
This has been addressed in `StreamBridge` since this issue was reported. Closing the issue. Please feel free to re-open if you encounter further issues (or create a new GH issue).
