### ISSUE TITLE
Create explicit way to define input/output binding for cases when there is no implicit trigger (i.e., Function, Consumer etc)

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream#2265]
Technically it could be an equivalent for what we had before with `@Input` and `@Output` of annotation-based model.
The Spring Cloud Stream should bind those by just properties and just expose `MessageChannel` beans, like it does for functions at the moment anyway.
End-user will decide what to do with those channels in target microservice logic.
Basically the goal is still to be able to leverage Spring Integration features especially when there is no straightforward alignment with functional model.

**Comment by olegz** [comment]
Pushed and back-ported to 3.1.x

**Comment by artembilan** [comment]
It doesn’t work if I have functional binding and this one in the mix.
Thanks
