### ISSUE TITLE
StreamBridge unable to work with nullChannel

### ISSUE THREAD

**Issue by tszmytka** [spring-cloud/spring-cloud-stream#2268]
**Describe the issue**
Using functional approach, sending messages to "nullChannel" results in:
```
org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'nullChannel' is expected to be of type 'org.springframework.messaging.SubscribableChannel' but was actually of type 'org.springframework.integration.channel.NullChannel'
```

This is because 
```
org.springframework.cloud.stream.function.StreamBridge#resolveDestination
```
works exclusively with `SubscribableChannel` channels. `org.springframework.integration.channel.NullChannel` doesn't implement that interface.

**To Reproduce**
In its simplest form the following line is enough to reproduce the issue:
```
streamBridge.send("nullChannel", "abcd");
```

In a more real world scenario I have a SCSt application with a function that processes and sends messages downstream. It sets the destination binding dynamically based on some business requirements:
```
@Bean
public Function<Incoming, Message<Outgoing>> functionRouter() {
    return incoming -> {
        // business logic
        final String destination = "dynamicallyDeterminedDestination";
        return MessageBuilder.withPayload(incoming).setHeader("spring.cloud.stream.sendto.destination", destination).build();
    };
}
```
From time to time the incoming message gets evaluated as "invalid" and doesn't need to be sent further.
In the past (with annotations) I was using "nullChannel" for that purpose with no issues. With functional approach this doesn't seem to be possible.

**Version of the framework**
spring-boot:2.6.0
spring-cloud-stream:3.2.1
spring-integration-core:5.5.6

**Expected behavior**
It is possible to use "nullChannel" (or any other valid binding that gets mapped to a channel) together with ScSt functional infrastructure.

**Additional context**
If you confirm this is an unwanted behavior I would like to take aim at contributing a fix for this myself.
I figure `StreamBridge` should be able to work with any `org.springframework.messaging.MessageChannel` channels.

**Comment by olegz** [comment]
Question, what is the motivation to use StreamBridge to send to null channel?

**Comment by tszmytka** [comment]
> what is the motivation to use StreamBridge to send to null channel?

I understand that doing this willingly wouldn't be too bright. The thing is I am **not** using StreamBridge directly. I brought up the one-line example only to demonstrate the simplest way of reproducing the error I'm getting.

My real use case is more similar to the `functionRouter` bean mentioned earlier: A function that processes an incoming message and sets the `spring.cloud.stream.sendto.destination` header to direct the resulting message to dynamic destinations - if need be the header is filled with `nullChannel` in order to discard the message.

It is SCSt functional that uses the StreamBridge - in the `handler` created inside `org.springframework.cloud.stream.function.FunctionConfiguration.FunctionToDestinationBinder#createFunctionHandler`
Here's a more detailed part of the stack trace that I'm getting:
```
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'nullChannel' is expected to be of type 'org.springframework.messaging.SubscribableChannel' but was actually of type 'org.springframework.integration.channel.NullChannel'
	at org.springframework.beans.factory.support.AbstractBeanFactory.adaptBeanInstance(AbstractBeanFactory.java:417)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:398)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1160)
	at org.springframework.cloud.stream.function.StreamBridge.resolveDestination(StreamBridge.java:258)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.doSendMessage(FunctionConfiguration.java:604)
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1.handleMessageInternal(FunctionConfiguration.java:597)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:56)
```


> Tomorrow we can change the backing implementation for the bindings to something else 

Sure, but today's StreamBridge implementation already works (internally) with `SubscribableChannel` objects. Allowing it to work with a broader interface (`MessageChannel`) would only improve its flexibility - especially since there currently is no technical reason for it to be restricted to `SubscribableChannel` - maybe there was one in the past.

> So my point is there is no concept of a null binding and with StreamBridge you send messages to a binding (not channels).

As mentioned before, I am not calling StreamBridge on my own but rather setting a "destination" using the `spring.cloud.stream.sendto.destination` header. 
In ScSt both destinations and bindings get mapped to some subclass of `MessageChannel` on numerous occasions so while I might have been not precise enough in naming I still think that my use case is valid and an adjustment would be of benefit.

**Comment by olegz** [comment]
Makes sense.

**Comment by tszmytka** [comment]
Aw, shucks man. Wish you would have left the implementation to me (I did point this out from the beginning). Seemed like an ideal first-time contribution.

**Comment by olegz** [comment]
@tszmytka My apology, I have missed your comment about the contribution. 
That said, I would not want to to get discouraged from contributing if you wish. In fact I can suggest couple of issues in both s-c-stream and s-c-function. Please let me know
