### ISSUE TITLE
Official sample does not work while unit/integration testing pausable

### ISSUE THREAD

**Issue by semangard** [spring-cloud/spring-cloud-stream#2285]
**Describe the issue**
Based on https://docs.spring.io/spring-cloud-stream/docs/3.2.1/reference/html/spring-cloud-stream.html#_programmatic_way
A piece of code is indicated to control programmatically the lifecycle of bindings;
I wanted to use it to controle PAUSE / RESUME states.

I tried to unit/integration test it with _TestChannelBinderConfiguration_
But :
1) the piece of code not work and returns class cast exceptions
2) pausable characteristic seem to the not taken into account

Example of bindings configured for a test:
```
new SpringApplicationBuilder(TestChannelBinderConfiguration.getCompleteConfiguration(CONFIGS)).run(
				"--spring.cloud.function.definition=" + String.join(";", functions),
				"--spring.cloud.stream.bindings.personCreated-in-0.pausable=true",
				"--spring.cloud.stream.bindings.personUpdated-in-0.pausable=true",
				"--spring.cloud.stream.bindings.personMerged-in-0.pausable=true",
				"--spring.cloud.stream.bindings.personDeleted-in-0.pausable=true"
```

Piece of code we modified to me it work with _TestChannelBinderConfiguration_
```
@Configuration
@RefreshScope
@Slf4j
public class StreamPauseConfiguration {

	@Autowired
	ConfigurableApplicationContext context;

	@Value("${application.consumers.pause}")
	public boolean pauseConsumers;


	// https://docs.spring.io/spring-cloud-stream/docs/3.2.1/reference/html/spring-cloud-stream.html#_programmatic_way
	public void pauseBindingsIfConfigured() {

               // implementation to fix class cast issues
		LOG.info("Pause consumers config : {}", String.valueOf(this.pauseConsumers));
		BindingsLifecycleController bindingsController = this.context.getBean(BindingsLifecycleController.class);
		List bindings = bindingsController.queryStates();
		if (bindings.size() == 0) {
			LOG.info("No binding to pause");
		}
		for (Iterator<LinkedHashMap> iterator = bindings.iterator(); iterator.hasNext();) {
			LinkedHashMap binding = iterator.next();
			String bindingName = (String) binding.get("bindingName");
			LOG.info("Pausing binding [{}]", bindingName);
			if (this.pauseConsumers) {
				bindingsController.changeState(bindingName, State.PAUSED);
			}
		}

		// the recommanded code which does not work with TestChannelBinderConfiguration... => class cast exception
		//@formatter:off
//		List<Binding<?>> bindings = bindingsController.queryStates();
//		for (Iterator<Binding<?>> iterator = bindings.iterator(); iterator.hasNext();) {
//			Binding<?> binding = iterator.next();
//			LOG.info("Pausing binding [{}]", binding.getName());
//			if (this.pauseConsumers) {
//				bindingsController.changeState(binding.getName(), State.PAUSED);
//			}
//		}
		//@formatter:on
	}
```

**Version of the framework**
Latest version 2.5.x of Spring Cloud components

**Expected behavior**
We would like to be able to test pausable bindings.

**Screenshots**
At runtime during tests : 
- class returned by _bindingsController.queryStates()_
- pausable config of bindings
![image](https://user-images.githubusercontent.com/57065741/154962514-e194d6d9-7e72-47b0-915b-6ca9fe498ed8.png)

**Comment by olegz** [comment]
You can not set `pausable`. That is not something that is exposed to the user. We do not have `pausable` property nor do we show anything like what you are trying to do in any of the documentation. Pausable is a functionality specific to a particular binder and that in turn is specific to the underlying system's feature. So, only Kafka binder supports pausing consumers which is different than stopping consumers (has to do with rebalancing consumers)

I am closing it as invalid
