### ISSUE TITLE
init not finish this is nul next get this get a null

### ISSUE THREAD

**Issue by kj-osc** [spring-cloud/spring-cloud-stream#2288]
` private synchronized FunctionInvocationWrapper getStreamBridgeFunction(String outputContentType, ProducerProperties producerProperties) {
        if (StringUtils.hasText(outputContentType) && this.streamBridgeFunctionCache.containsKey(outputContentType)) {
            return (FunctionInvocationWrapper)this.streamBridgeFunctionCache.get(outputContentType);
        } else {

1.             FunctionInvocationWrapper functionToInvoke = (FunctionInvocationWrapper)this.functionCatalog.lookup(STREAM_BRIDGE_FUNC_NAME, new String[]{outputContentType.toString()});
2. 
3.            this.streamBridgeFunctionCache.put(outputContentType, functionToInvoke);
4. 
5.             functionToInvoke.setSkipOutputConversion(producerProperties.isUseNativeEncoding());

            return functionToInvoke;
        }
    }`

Enter this method for the first time The first line gets a null,Third line put a null in this map
next into this way retun a null  
this is a problem

**Comment by olegz** [comment]
There is no problem since line 1 can never return null given that `streamBridge` function is registered always during the initialization time
