### ISSUE TITLE
Spring Cloud Stream Kafka - 4.0.0-M1 Error creating bean occurs when using supplier to start

### ISSUE THREAD

**Issue by livk-cloud** [spring-cloud/spring-cloud-stream#2289]
![image](https://user-images.githubusercontent.com/50291874/157387077-350055d7-2db6-480b-8ce8-8a821315ba08.png)
But with version 3.x this problem does not occur
Hope to fix it soon, thanks
code i put [code](https://github.com/livk-cloud/Spring-Cloud-Demo/tree/main/spring-cloud-stream-demo)

**Comment by sobychacko** [comment]
@livk-cloud What should we run in your sample repo to reproduce this error?

**Comment by livk-cloud** [comment]
@sobychacko I just provided the code where I made the error so that I could reproduce the error，Of course, you can also view it in other ways

**Comment by livk-cloud** [comment]
@sobychacko [code](https://github.com/livk-cloud/Spring-Cloud-Demo/blob/main/spring-cloud-stream-demo/kafka-provider/src/main/java/com/livk/provider/KafkaProvider.java)
Sorry, I misunderstood what you meant, I provided the main method of springboot, you can go to [build.gradle](https://github.com/livk-cloud/Spring-Cloud-Demo/blob/main/build.gradle) below to modify the version

**Comment by sobychacko** [comment]
@livk-cloud Did you check the latest `4.0.0-SNAPSHOT` and verify that the problem still persists?  If so, I suggest you create a very small sample application (not the one you shared with other components) and share it with us. Maybe you can carve out the problematic code from your larger repo and put it as part of a small Spring Boot application?

**Comment by livk-cloud** [comment]
> @sobychacko When I use **4.0.0-SNAPSHOT**, it doesn't happen any error，Thank you for your answer
