### ISSUE TITLE
RabbitMessageChannelBinderConfiguration no longer using externally defined ConnectionFactory

### ISSUE THREAD

**Issue by TabberGit** [spring-cloud/spring-cloud-stream#229]
In the Autowire of the `ConnectionFactory rabbitConnectionFactory` an externally defined ConnectionFactory is no longer used.  Only the internally created ConnectionFactory is considered.

**Comment by TabberGit** [comment]
Currently using

* stream-binder-rabbit SNAPSHOT - 1.0.0.BUILD-20151210.184943-175 
* stream SNAPSHOT 1.0.0.BUILD-20151210.184943-192

Carry-over from issue #227

**Comment by TabberGit** [comment]
still experiencing the same issue with snapshot 194

**Comment by mbogoevici** [comment]
Hi, this is not merged yet, so deployed snapshots will not see the issue fixed.
