### ISSUE TITLE
Add RabbitMessageChannelBinder#connectionFactory getter

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#2327]
@tzolov commented on [Tue Mar 29 2022](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/358)

The `RabbitMessageChannelBinder` has an opinionated view about the `connectionFactory` lifecycle. 
For some use-cases a user might want to reset the connection; let's say the primary broker failed and we switched automatically to a secondary broker; later, when the primary broker is available, the user might want to (manually) switch back by resetting the connection to the secondary broker. (Kudos to @garyrussell)

**Comment by olegz** [comment]
It appears to be duplicate and is resolved so I'll close it
