### ISSUE TITLE
Health indicator does not reflect actual connection status

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#233]
Spring Cloud Stream probably should start adding new health indicators for its middleware connections, otherwise the user will think that the app is UP, when it might be DOWN. None of the configuration in the binder factories shows up in the actuator endpoints, so you can't really tell what's broken when it is.

**Comment by mbogoevici** [comment]
Need to do some thinking around this, but how about we expose a `/binders` endpoint with that kind of info?

Perhaps hierarchical, as in `/binders/<binderName>`.

**Comment by dsyer** [comment]
/binders would be great. I think a health indicator would be essential too though (otherwise the app can be down, but /health says UP)

**Comment by mbogoevici** [comment]
Ah, sorry. Yes. That would be a must.

**Comment by ezraroi** [comment]
Is this is related to this issue #271 ?

Looks like it is reflecting but with wrong status

**Comment by dsyer** [comment]
Probably a duplicate, yes.
