### ISSUE TITLE
ClassCastException with Batch Listener and republishToDlq

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#2332]
@garyrussell commented on [Wed Oct 27 2021](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/348)

See https://stackoverflow.com/questions/69740749/spring-cloud-stream-rabbit-binder-error-sending-batch-messages-to-dlq/69741806#69741806

ClassCastException here:

	Message amqpMessage = StaticMessageHeaderAccessor.getSourceData(message);	Message amqpMessage = StaticMessageHeaderAccessor.getSourceData(message);

because the source data is a `List<Message>` for a batch listener.
Consider:

1. Set `republishToDlq` to false by default for a batch listener.
2. Disallow `republishToDlq` for a batch listener.
3. Publish the entire batch to the DLQ (but I doubt this is right for all use cases).

**Comment by kim-ae** [comment]
I had the same issue.
I took the liberty to make a pull request with a fix proposal. 
https://github.com/spring-cloud/spring-cloud-stream/pull/2567
Hopefully it's accordingly with all the rules and guides and it will help.
