### ISSUE TITLE
Classes that are not auto-configuration classes should not be named …AutoConfiguration

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#2335]
@wilkinsona commented on [Fri Oct 19 2018](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/188)

It [appears that](
https://github.com/spring-projects/spring-boot/issues/14906#issuecomment-431330846) `RabbitServiceAutoConfiguration` isn't actually an auto-configuration class. This is causing confusion and means that an attempt to exclude it using `SpringBootApplication(exclude=RabbitServiceAutoConfiguration.class)` fails.

To avoid this confusion, can you please avoid naming classes `…AutoConfiguration` unless they are an auto-configuration class that is registered using the `org.springframework.boot.autoconfigure.EnableAutoConfiguration` key in `spring.factories`.

**Comment by olegz** [comment]
Closing it as duplicate as well
