### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to org.springframework.cloud.stream.binder.rabbit.properties.RabbitConsumerProperties

### ISSUE THREAD

**Issue by matthewjmason** [spring-cloud/spring-cloud-stream#2340]
I commented in https://github.com/spring-cloud/spring-cloud-stream/issues/1990 but it is closed so I am creating a new issue to resurface. Not sure if that should be reopened or use the new issue.

My comment:

I am pretty sure this is still an issue in the latest version: https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java#L148

If I set the instanceIndexList property on my consumer, it fails the if check here: https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingService.java#L133 and drops into the problematic else condition on line 142. When, on line 148, ExtendedConsumerProperties is instantiated with a String there is a mismatch in type of the extension fields of consumerProperties (extension type RabbitConsumerProperties) consumerPropertiesTemp (extension type String). 

I think the fix is to change line 148 from:

`ConsumerProperties consumerPropertiesTemp = new ExtendedConsumerProperties<>("");` to `ConsumerProperties consumerPropertiesTemp = new ExtendedConsumerProperties<>(new RabbitConsumerProperties());` or something along that line.

_Originally posted by @matthewjmason in https://github.com/spring-cloud/spring-cloud-stream/issues/1990#issuecomment-1084919388_

**Comment by matthewjmason** [comment]
I confirmed in my local debugger changing line 148 from:

`ConsumerProperties consumerPropertiesTemp = new ExtendedConsumerProperties<>("");` to `ConsumerProperties consumerPropertiesTemp = new ExtendedConsumerProperties<>(new RabbitConsumerProperties());` 

produces the results that I would expect but I am not familiar with the project and original intent to know if there are unintended consequences.

**Comment by olegz** [comment]
Indeed that code is very wrong, but it appears that the fix is simple
