### ISSUE TITLE
Consumer<Flux<..>> bean breaks streambridge output using declared sources 

### ISSUE THREAD

**Issue by jonenst** [spring-cloud/spring-cloud-stream#2347]
**Describe the issue**
Hi, with spring cloud stream 2021.0.1,  having a  Consumer<Flux<..>> bean in the context crashes when using declared sources with stream bridge. It works in 2021.0.0.

```
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionInitializer' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: null or too small array, need between 2 and 8 values
Caused by: java.lang.IllegalArgumentException: null or too small array, need between 2 and 8 values
```

**To Reproduce**
use for exemple
```
--spring.cloud.stream.bindings.toStream-out-0.destination=foo
--spring.cloud.stream.source=toStream
```
and have somewhere in your source code (even though it looks unrelated):
```java
        @Bean
        public Consumer<Flux<Message<String>>> consumeNotification() {
            return f -> {};
        }
```

a maven project to reproduce the problem:
[bo.zip](https://github.com/spring-cloud/spring-cloud-stream/files/8442944/bo.zip)

```
$ unzip bo.zip
$ cd bo
$ mvn test -Dspring-cloud.version=2021.0.1
FAILURE
$ mvn test -Dspring-cloud.version=2021.0.0
SUCCESS
```

**Version of the framework** 2021.0.1
**Expected behavior** works
**Additional context**
worked on 2021.0.0

**Comment by olegz** [comment]
Have you subscribed inside the consumer as described here - https://docs.spring.io/spring-cloud-stream/docs/3.2.2/reference/html/spring-cloud-stream.html#_consumer_reactive?

**Comment by jonenst** [comment]
Hi,
thank you for your time. Yes I had a subscribe() when using Consumer. You can see the realworld code here: https://github.com/gridsuite/merge-orchestrator-server/commit/4c864713086476b1508baced01758c87af72f7d8 where I change to using Function as a workaround.
I didn't include the subscribe() in the repro because the main problem is about streambridge I think.
Happy to work more on this.

**Comment by olegz** [comment]
And it's only for reactive Consumer

**Comment by olegz** [comment]
Fixed, and I will back-port it. Also, I will be updating documentation, but `.source` is deprecated and we now have `spring.cloud.stream.output-bindings` and `spring.cloud.stream.input-bindings`, so consider using `spring.cloud.stream.output-bindings=toStream`
