### ISSUE TITLE
shard iterator type defaults to latest instead of trim-horizon when using kcl with a group

### ISSUE THREAD

**Issue by sixcorners** [spring-cloud/spring-cloud-stream#2359]
When you specify a group the binder will default to using trim-horizon normally. If you turn on the kcl, consumers with a group will default to latest instead. If this isn't a bug could it be documented please? Thanks

**Comment by sixcorners** [comment]
Is it a backwards incompatible change to fix this? : \

**Comment by artembilan** [comment]
@sixcorners ,

you can find the fix here: https://github.com/spring-cloud/spring-cloud-stream/pull/2365.

Pay attention to that `KinesisClientLibConfiguration` instance. That's probably would be a starting point how to apply a workaround for existing version when you provide an external configuration.
