### ISSUE TITLE
Junit5 cleanup / best practices

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-stream#2371]
There are several places in the SCS repo that have older Junit4 usage and can be refreshed to Junit5 usage/best practices:

- [x] remove `@ExtendWith(SpringExtension.class)` from all `@SpringBootTest` as SBT includes that annotation.([comment](https://github.com/spring-cloud/spring-cloud-stream/pull/2362#discussion_r857916089))

- [x] leverage package-protected test classes and test methods ([comment](https://github.com/spring-cloud/spring-cloud-stream/pull/2362#discussion_r857926243))

- [x] **{optional):** remove 'test' method name prefix

**Comment by sobychacko** [comment]
These tasks have now been completed. A few tests remain with the `test` prefix due to some cross-test interaction. We will tackle those separately later.
