### ISSUE TITLE
Spring cloud stream 3.2.3 FunctionInvocationHelper throw NPE

### ISSUE THREAD

**Issue by guerlab** [spring-cloud/spring-cloud-stream#2384]
**Describe the issue**
when used Spring cloud stream 3.2.3 and Spring cloud function 3.2.3, CloudEventsFunctionInvocationHelper is a primary integration bridge, postProcessResult method's param "input" cannot be null, but the 'send' method of 'streambridge' calls the 'postprocessresult' method with the '(resultmessage, null) "parameter.

**Version of the framework**
Spring cloud stream 3.2.3 
Spring cloud function 3.2.3

**Expected behavior**
Don't throw npe

**Additional context**
<img width="920" alt="image" src="https://user-images.githubusercontent.com/34049111/167557114-2e9094dd-0045-4fd3-a639-f22894c99d13.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/34049111/167557155-a382a4e9-3f1c-4a5f-ad3f-d7d89f48da60.png">

**Comment by guerlab** [comment]
fixd in spring-cloud-function-context 3.2.4

**Comment by originyy** [comment]
3.2.4还有

**Comment by originyy** [comment]
ok, I get it
