### ISSUE TITLE
OutputDestination don't subscribe if destination is used in producer binding

### ISSUE THREAD

**Issue by joantorrens** [spring-cloud/spring-cloud-stream#2386]
When same destination is used in different bindings one for consume and other for produce the OutputDestination doesn't subscribe to SubscribableChannel.
From what I have seen the outputDestination doesn't subscribe to subscribableChannel because subscriber count is 1.
The subscribableChannel was previously subscribed to in the TestChannelBinder in the createConsumerEndpoint function.

**To Reproduce**

Steps to reproduce the behavior in test with OutputDestination:
1. Set two bindinds in and out with same destination.
spring:
  cloud:
    function:
        definition: message-binding
    stream:      
      bindings:
        message-binding-in-0:
          destination: retry-topic
          group: appGroup
        message-binding-out-0:
          destination: retry-topic
          content-type: application/*+avro
2. Create springBootTest in wich a message is sent with streamBridge to out binding: message-binding-out-0.
3. Call OutputDestination to receive out binding. 

**Version of the framework** spring-cloud-stream test-jar 3.2.2
**Expected behavior**
OutputDestination must receive message send to streamBridge.

**Comment by olegz** [comment]
Closing it due to lack of follow up from the reporter
