### ISSUE TITLE
spring-kafka-test added with default/compile scope in spring-cloud-stream-binder-kafka-streams pom.xml

### ISSUE THREAD

**Issue by thegiffted1** [spring-cloud/spring-cloud-stream#2387]
This dependency should use test scope:

		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka-test</artifactId>
		</dependency>

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/main/spring-cloud-stream-binder-kafka-streams/pom.xml

**Comment by sobychacko** [comment]
@thegiffted1 I just want to confirm the binder version where you observe this - `4.0.0-SNAPSHOT`?
I moved the issue over here as this is the new home for the Kafka binders.
