### ISSUE TITLE
Spring cloud stream kafka binder: cannot set subBatchPerPartition

### ISSUE THREAD

**Issue by sergiupantiru** [spring-cloud/spring-cloud-stream#2399]
**Describe the issue**
I'm trying to use Kafka Transactions in batch mode. Since, in batch mode, messages can come from multiple partitions, it looks like   the "zombie" fencing is not used. A way to set the `subBatchPerPartition` property would resolve this issue.

**To Reproduce**
1. Create a topic with multiple partitions
2. Start a Processor, batch mode

The `transactionalId` will be `prefix+number` instead of `prefix+consumerGroupId+topic+partition`

**Version of the framework**
2021.0.0
**Expected behavior**
A way to configure `subBatchPerPartition`
**Screenshots**

**Additional context**

**Comment by garyrussell** [comment]
What is your broker version? 2021.0.2 (latest version) uses spring-kafka 2.8.5, which uses EOSMode.V2 (aka BETA); if your broker is 2.5 or later, you don't need `subBatchPerPartition`.

If your broker is older, then the clients will fall back to V1 (ALPHA), in which case you do need it.

Simply add a `ListenerContainerCustomizer` bean to the application and then `container.getContainerProperties.setSubBatchPerPartition(true)`.

Or, set the EOSMode to `V1` and the container will automatically use a sub batch per partition.

**Comment by garyrussell** [comment]
Thanks for reporting back.
