### ISSUE TITLE
Kinesis Binder, Does it have error channel behaviour

### ISSUE THREAD

**Issue by Sutty100** [spring-cloud/spring-cloud-stream#2400]
I'm a little unclear from the docs if the Kinesis binder does or does not support sending errors to an error channel. The Kinesis binder docs seem to imply that we should use the Spring Cloud Stream library to manage this but the SCS Lib docs say that this is now specific to the binder and to look there for how to configure. Am I correct to assume that currently the Kinesis binder does not have a mechanism to handle errors and push them to a named error channel? If that is the case is there a plan to implement this?

**Comment by artembilan** [comment]
The AWS Kinesis binder is like this:
```
KinesisMessageChannelBinder extends
		AbstractMessageChannelBinder<ExtendedConsumerProperties<KinesisConsumerProperties>
```
Where its `createConsumerEndpoint()` does this in the end:
```
ErrorInfrastructure errorInfrastructure = registerErrorInfrastructure(destination,
				consumerGroup, properties);
		adapter.setErrorMessageStrategy(ERROR_MESSAGE_STRATEGY);
		adapter.setErrorChannel(errorInfrastructure.getErrorChannel());
		adapter.setBindSourceRecord(true);
		return adapter;
```

So, this binder has the same error handling capabilities to send to named destination error channel as it is done with other binders.

**Comment by olegz** [comment]
Closing it since the question has been answered
