### ISSUE TITLE
Unclear deprecation

### ISSUE THREAD

**Issue by strowk** [spring-cloud/spring-cloud-stream#2402]
**Describe the issue**
Classes 
org.springframework.cloud.stream.annotation.Output
org.springframework.cloud.stream.annotation.StreamListener
and others are deprecated with note "in favor of functional programming model", however current documentation 
https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html
does not describe any method other than using StreamListener. 

Please either remove deprecation from classes, or change documentation to the new recommended way of doing things. 
If there is a guide to migrate to new way, it should be included in javadoc.

**To Reproduce**
1. Go to ['official docs'](https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html)
2. Use one of examples
3. Example would show use of deprecated classes 

**Version of the framework**: spring-cloud-dependencies:2021.0.2
**Expected behavior**: no deprecated classes
**Screenshots**

**Additional context**
Current situation is confusing for anyone starting using this library. The official docs recommend to use something that the code itself does not recommend to use referencing some "functional programming model", which in documentation is not highlighted anywhere.

**Comment by strowk** [comment]
@sobychacko  , sorry I guess it would be better to give different link
I see same doc here: 
https://github.com/spring-cloud/spring-cloud-stream/blob/main/docs/src/main/asciidoc/kafka/kafka_overview.adoc

It seems to be more or less same as in suggests to use StreamListener and I understand this is up-to-date (HEAD on master). 

I can elaborate mismatch. For example if I use code from "Tombstone Records":
```
StreamListener(Sink.INPUT)
public void in(@Header(KafkaHeaders.RECEIVED_MESSAGE_KEY) byte[] key,
               @Payload(required = false) Customer customer) {
    // customer is null if a tombstone record
    ...
}
```
, then I will see that StreamListener is deprecated.

Now I guess I can get to that doc following the link you have provided like this:
from https://spring.io/projects/spring-cloud-stream#learn I click Reference doc on Current version, I get here:
https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/
click [Apache Kafka Binder](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_apache_kafka_binder)
get here:
https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_apache_kafka_binder
scroll down to [Usage examples](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_usage_examples)
we see 
```
 @StreamListener(Sink.INPUT)
 public void process(Message<?> message) {
 ```
 
, while if I go back to one level up and search for StreamListener, I can find here
https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#spring-cloud-stream-reference

> Annotation-based programming model. Basically the @EnableBInding, @StreamListener and all related annotations are now deprecated in favor of the functional programming model. See [Spring Cloud Function support](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#spring_cloud_function) for more details.

This looks like mismatch to me. I think I could kindof guess how to use Kafka with this new way at least how to get payloads. But I am not sure how to properly listen for tombstones. 
That doc gives here
https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#kafka-tombstones
only that what I mentioned before - use of deprecated `StreamListener(Sink.INPUT)` , rather than example with this new functional programming model. 
It would be great if there was an example of the new stuff, rather than deprecated old. I even tried to find one in samples, but no luck.

**Comment by sobychacko** [comment]
@strowk Thanks! Point taken on the need to clarify the docs. Sorry that it gave you trouble; we will try to improve the docs (PRs are always welcome!). Regarding your question about handling tombstone records with the new functional style, look at this [test](https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/ImplicitFunctionBindingTests.java#L208) for some suggestions. Here are the [functions](https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/function/ImplicitFunctionBindingTests.java#L1249) used in that test. Essentially, when you send a null record, Spring Cloud Stream will convert that to a  [KafkaNull](https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/support/KafkaNull.java) and provide it to your consumer or function.

**Comment by strowk** [comment]
@sobychacko , I see, thanks for the links. I cannot unfortunately use `Function<Person, String>` approach, because this does not allow to get identifier (key) of deleted item (I work with log compacted topic, tombstone is basically something removed). There is just null payload, but no way to get headers with this way AFAIU. Am I wrong?

Approach `Function<Message<Person>, String> funcMessage()` looks better at first glance, because I can get key from message.headers. But the thing is that in case of removal, instead of just giving null in place of payload (which I would expect) there is this KafkaNull object, which does break type system. Basically I have to do something like `if (message.payload is Person)` (I am using Kotlin BTW) for usual case and `else` would be for situation with KafkaNull, however that check is highlighted by static code analysis, which warns that it does not make sense. If library would just give nulls, I could express this with Kotlin type system using nullable type `Person?` (probably) and then Kotlin would force to check for null case.
Is this KafkaNull thing done on purpose? Is it really required? Am I doing something wrong? If doc would have an ideomatic example of how to receive message and also process case of when it was tombstone (and process key too), that'd be great.

I am doing something pretty standard here: I need to project subset of log-compacted topic on our database table, where some indexes are configured helping to work with that projection. 
To keep projection up to date, I need to process tombstones correctly, otherwise table would contain items, which were removed from the system. 

At the moment I have created a super class: 
```
@JsonDeserialize(`as` = Person::class)
interface KafkaPersonMessage {
    // we need to use inheritance to allow representing
    // null entries from kafka as well (KafkaNull class)
}
```
, which allows to add one more level of inheritance of the model. Now, KafkaNull does not implement this interface of course, so I still risk getting class cast exception if I do not explicitly check for the type, but this bypasses static code analysis, which now cannot define that the check is irrelevant. 
I suppose I could also actively suppress that thing. Both ways seem ugly to me and I don't understand why library is forcing me to do it like this. Maybe I am missing something in the design?

**Comment by sobychacko** [comment]
@strowk See Gary's comments above. We should brainstorm around it and see what we can come up with. In the meantime, we suggest you stick with your workarounds.

**Comment by olegz** [comment]
We already support tombstone records with recent addition of support for BiFunction

`BiFunction<?, Map>` - where `?` could be anything as it represents payload and `Map` is headers
Basically the equivalent of your earlier mentioned `@Payload(required = false) Customer customer` you would have `BiFunction<Consumer, Map>`

**Comment by skomarica** [comment]
Hi @olegz @sobychacko - apologies for writing on a closed issue, but the context is very similar and I hoped you might be able to give me some guidance quickly. 

In 3.x we were able to use `Consumer<Message<?>>`, and then access the payload and headers. This worked well for "regular" and tombstone records. With [this change](https://github.com/spring-cloud/spring-cloud-function/pull/981/files#diff-f402dc47373cf433cb40bdebb95a4012ab40017839e9b0af6124349a71a038b0R964), in case of a tombstone record, the Message object is `null` and we can't access the headers anymore, which are critical for further processing on the consumer side.

I wasn't able to find it in the docs, but skimmed through the code and issues, and stumbled upon this PR. It looks like that there is support for `BiConsumer<?, MessageHeaders>`, where one can get a payload and headers directly, without using `Message`. In case of a tombstone record, the payload would be `null`, but we'd be able to access the headers which is all we need.

The problem is that `BiConsumer` gets wrapped and registered as a `Function` [here](https://github.com/spring-cloud/spring-cloud-function/blob/d2ef5024bd7f2477dc5814b466d1a6db145b52c8/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/BeanFactoryAwareFunctionRegistry.java#L214) and now we're kinda forced to have an output binding `xyzEventHandler-out-0` even though we only have a need for a simple consumer without output.

The configuration is simple:

```
spring.cloud.function.definition: "xyzEventHandler"

spring.cloud.stream.bindings:
  xyzEventHandler-in-0:
    destination: xyz-event
```

I'm sure there's a way to use a consumer and access headers of a tombstone record, but I can't figure it out myself. Thank you for advising me how to move on.
