### ISSUE TITLE
Un-@Ignore ModuleAggregationTest

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#241]
Need a Mock Binder

See https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream/src/test/java/org/springframework/cloud/stream/aggregation/ModuleAggregationTest.java#L38

**Comment by mbogoevici** [comment]
Solved.
