### ISSUE TITLE
Specify arn name for DynamoDb tables and Kinesis Stream

### ISSUE THREAD

**Issue by petrangeli** [spring-cloud/spring-cloud-stream#2415]
**Describe the issue**
I have an aws role that has the all necessary permissions to use the DynamoDb tables and Kinesis Data Stream that resides on a different account than where the two services mentioned above are located. 
Therefore, the role will belong to a certain account id (e.g. 0000000000) while the arn of DynamoDb tables and Kinesis Data Stream will contain the id of a different account (e.g. 1111111111). 
The library allows me to rename the Dynamo tables with the following properties.
```
spring.cloud.stream.kinesis.binder.locks.table = locks_table_name 
spring.cloud.stream.kinesis.binder.checkpoint.table = checkpoint_table_name
```
and specify the kinesis stream data from which to consume records with the following property
`spring.cloud.stream.bindings.input.destination = kinesis_name`
In this way, the application will attempt to connect to the two services using as arn 
`arn:aws:dynamodb:eu-central-1:0000000000:table/locks_table_name`
instead of 
`arn:aws:dynamodb:eu-central-1:1111111111:table/locks_table_name`
The same applies to the Checkpoint table and Kinesis Data Stream.
I was wondering if it would be possible to specify the arn of the tables and kinesis data stream instead of their respective names. 

**Version of the framework**
2.0.2.RELEASE

**Expected behavior**
Access to resource by arn instead name

**Comment by olegz** [comment]
Closing it due to lack of follow up form the original reporter
