### ISSUE TITLE
[Feature Request] Allow to accept a list of customizers instead of a unique one for KafkaMessageChannelBinder

### ISSUE THREAD

**Issue by yiliuTo** [spring-cloud/spring-cloud-stream#2423]
**Describe the issue**
Currently for [KafkaMessageChannelBinder](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/e848ec8051fd17b78ba77b409ccd0853066cdb77/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L163), it can only accept a single instance for [ClientFactoryCustomizer](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/e848ec8051fd17b78ba77b409ccd0853066cdb77/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L236), [ProducerConfigCustomizer](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/e848ec8051fd17b78ba77b409ccd0853066cdb77/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L238) and [ConsumerConfigCustomizer](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/e848ec8051fd17b78ba77b409ccd0853066cdb77/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L240) each. While this might be a block when there is need to carrry out secondary development on the binder configs/factories by using those customziers in a another library. Because in this way if both the library and users provide their own customziers, then neither of them can take effects.

**Version of the framework**
Library: org.springframework.cloud:spring-cloud-stream-binder-kafka

**Expected behavior**
For [KafkaMessageChannelBinder](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/e848ec8051fd17b78ba77b409ccd0853066cdb77/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L163), hope it can hold a list of those customizers instead of a single one. And then for the [KafkaBinderConfiguration](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/da9bc354e443a71a9bfc077b8ebd1876c59839d2/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L129), it doesn't need to get the unique one, but can use the similar way of [Spring Boot Kakfa Autoconfiguration](https://github.com/spring-projects/spring-boot/blob/8413002bcb6bc645f6d9e3b705ac82e051606389/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.java#L99) to add all of them to the binder.

**Additional context**
Copy the issue in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1217 in case that's not the repo to raise issues for kafka binder.

**Comment by sobychacko** [comment]
@yiliuTo What you are proposing makes complete sense to me. Do you want to work on a patch and send us a PR? But we can certainly look at this if you can't get to it. Let us know either way. Thank you!

**Comment by yiliuTo** [comment]
@sobychacko thanks for the quick feedback! Also of course I would like to create a pr for that! I will link to this issue when I create the PR

**Comment by yiliuTo** [comment]
Hi @sobychacko , I created a [PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/1220) for this issue, please help to take a look and review when you are available, thanks!
