### ISSUE TITLE
[Feature-Request] Apache Pulsar binder addition

### ISSUE THREAD

**Issue by markusherbert** [spring-cloud/spring-cloud-stream#2431]
I'd like the framework to include support for consuming and producing messages with Apache Pulsar. Apache pulsar is a popular technology for many years now, and its usage becomes wider and wider.

In my opinion, Spring cloud stream, as a streaming framework, **has** to support Apache pulsar - one of the most popular and promising streaming technologies out there.

I do aware that it can be easier if it would be implemented first as a Spring Integration channel adapter, and [there's also an issue for this](https://github.com/spring-projects/spring-integration/issues/3771). In general, the Spring framework has very low support for Apache Pulsar (compared to the support for Pulsar in other streaming technologies like [Flink ](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/datastream/pulsar/)/ [Akka](https://doc.akka.io/docs/alpakka/current/external/pulsar.html)/ [Spark ](https://pulsar.apache.org/docs/adaptors-spark/)/ [Camel](https://camel.apache.org/components/3.17.x/pulsar-component.html)).

**Comment by dajemet379** [comment]
Indeed a wanted one. These two projects have started implementing such solutions, but this ain't official and doesn't seem trusted yet:

https://github.com/lhotari/pulsar-spring-cloud-stream-binder
https://github.com/miteshukate/spring-cloud-stream-binder-apache-pulsar

**Comment by eddumelendez** [comment]
there is an experimental project for [spring pulsar](https://github.com/spring-projects-experimental/spring-pulsar)

**Comment by sobychacko** [comment]
[Pulsar binder](https://github.com/spring-cloud/spring-cloud-stream/tree/main/binders/pulsar-binder) is now part of the official Spring Cloud Stream binders. Closing the issue. @markusherbert We would greatly appreciate if you have any feedback on this. Thank you!
cc @onobc @dajemet379 @eddumelendez
