### ISSUE TITLE
Revisit if KafkaTestBinder.TupleRegistrar is still needed

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#244]
Assert if KafkaTestBinder.TupleRegistrar is still needed. see also MessageChannelBinderSupportTests

See https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaTestBinder.java#L82

and 

https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-binders/spring-cloud-stream-binder-test/src/test/java/org/springframework/cloud/stream/binder/MessageChannelBinderSupportTests.java#L300

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#62
