### ISSUE TITLE
KafkaNull parsed as null instead of KafkaNull.INSTANCE, batch consumer

### ISSUE THREAD

**Issue by sbernardo** [spring-cloud/spring-cloud-stream#2441]
After closing this issue https://github.com/spring-cloud/spring-cloud-function/issues/884 the fix done for this https://github.com/spring-cloud/spring-cloud-stream/issues/2355 stopped working.

The exception is not thrown anymore but KafkaNull is not parsed but null is returned.

Versions:
- Spring Cloud Stream 3.2.5-SNAPSHOT
- Spring Cloud Function 3.2.6-SNAPSHOT

The example:

```properties

spring.cloud.function.definition=recordConsumer;batchConsumer

spring.cloud.stream.bindings.recordConsumer-in-0.destination=test
spring.cloud.stream.bindings.recordConsumer-in-0.group=recordConsumer

spring.cloud.stream.bindings.batchConsumer-in-0.destination=test
spring.cloud.stream.bindings.batchConsumer-in-0.group=batchConsumer
spring.cloud.stream.bindings.batchConsumer-in-0.consumer.batch-mode=true
```

```java
@SpringBootApplication
public class SampleApplication {

    public static void main(String[] args) {
        SpringApplication.run(SampleApplication.class, args);
    }

    @Bean
    public ApplicationRunner runner(StreamBridge streamBridge) {
        return args -> {
            streamBridge.send("test", new MyClass(1, 10));
            streamBridge.send("test", new MyClass(2, 20));
            streamBridge.send("test", KafkaNull.INSTANCE);
        };
    }

    @Bean
    Consumer<Message<List<MyClass>>> batchConsumer() {
        return message -> {
            List payload = message.getPayload();
            payload.forEach(s -> System.out.println("Batch - " + s));
        };
    }

    @Bean
    Consumer<Message<MyClass>> recordConsumer() {
        return s -> System.out.println("Record - " + s);
    }
}

record MyClass(int min, int max) {
}
```

The behavior is different from batch mode and not. In batch, payload is parsed as null. Single record is parsed as KafkaNull.INSTANCE instead.

I commented here https://github.com/spring-cloud/spring-cloud-function/issues/884#issuecomment-1157405945 the possible problematic line of code. I tried to change and add `item` to list instead of null and the same example on top works as expected.

**Comment by olegz** [comment]
Actually, the fix and what you are observing is exactly what we intended. Let me explain.  .  .

`KafkaNull` type was specifically designed to be included in the `Message` to represent tombstone records. The main reason is that Spring `Message` does not allow null payload, so we needed something to represent what is effectively `null`.
That said, this is really a boilerplate/infrastructure detail that we would rather you not bother. In previous versions of spring-cloud-stream you could use `@Payload`, `@Headers` annotations in your `StreamListener` method. 
In functional model we did not have such support until recently so `Consumer<Message<MyClass>>` given that it's a `Message` would end up with `KafkaNull` as its payload.  The difference in `Consumer<Message<List<MyClass>>>` has nothing to do with batch, rather the fact that the `Message` payload is a `List` (so not null), but such list has null entries. And. that is the intended behavior.
So to make it consistent with a non-batch function and avoid dealing with `KafkaNull` all you need to do is change your 
```
@Bean
 Consumer<Message<MyClass>> recordConsumer() {
        return s -> System.out.println("Record - " + s);
 }
```

to 
```
@Bean
 BiConsumer<MyClass, Map> recordConsumer() {
        return (p,h) -> {
        	System.out.println("Record - " + p);
        };
 }
```

In this case the printed record will be `null` and the behavior will be consistent with batch mode as well as what we had there before

**Comment by smlgbl** [comment]
@olegz Sorry to post in a closed issue, but why is this change not in the docs? Or rather: where can I find this in the docs? A KafkaNull-Message on a log-compacted topic is useless for the consumer without the key...
