### ISSUE TITLE
InteractiveQueryService throwing exceptions on Kafka Streams 3.1 with multiple Kafka Streams applications

### ISSUE THREAD

**Issue by Xrixcis** [spring-cloud/spring-cloud-stream#2445]
**Describe the issue**

When upgrading to Spring Boot 2.7.0 with Kafka 3.1.1 I came across an issue with `InteractiveQueryService`. Our application uses functional binding with multiple Kafka Streams applications, each with it's own state store defined as a `StoreBuilder` bean. When trying to query the stores, the `ReadOnlyKeyValueStore.get(key)` started to throw 

```
org.apache.kafka.streams.errors.InvalidStateStoreException: The state store, <store>, may have migrated to another instance.
```

The issue appears to be caused by a slight behavior change of `org.apache.kafka.streams.KafkaStreams#store(StoreQueryParameters<T>...)` called by `InteractiveQueryService` - instead of returning just the stores actually used in the one topology, it checks all stores in the topology. This, in combination with Spring Cloud Stream `AbstractKafkaStreamsBinderProcessor` adding all the `StoreBuilder` beans in context to every `StreamsBuilder`, is causing the `KafkaStreams#store(StoreQueryParameters<T>...)` method to always return a store no matter the Kafka Streams instance, but one that cannot be used, unless the right Kafka Streams instance happens to be the first one checked.

I'm not sure if this is more of an SCS or Kafka Streams issue, but in Kafka Streams does exactly as specified in the method documentation

> Throws:
>   UnknownStateStoreException – If the specified store name does not exist in the topology.

**To Reproduce**

See the repository at https://github.com/Xrixcis/kstreams-error-demo

**Version of the framework**

Spring Boot 2.7.0 / Kafka Streams 3.1.1
Spring Cloud Stream 2021.0.3
Spring Cloud Stream Kafka Streams Binder 3.2.4

**Expected behavior**

Stores can be queried without exceptions as on Kafka Streams 3.0

**Comment by marcmesh** [comment]
Hi,
this hit us pretty hard during our migration to Springboot 2.7 and Kafka Streams 3. As described in the issue, we use multiple Stream Binder apps with their own state stores, access via InteractiveQueryService only works randomly.

But I'm glad to see that the bug has already been fixed. I'm currently trying to identify the smallest possible downgrade I need to make until there is a new release with the fix. Can you guys help me?
Cheers

**Comment by marcmesh** [comment]
Thank you very much @sobychacko, this is exactly what we did, all tests back to green! Thanks again
