### ISSUE TITLE
The link to documentation on error channel handling seems to be broken

### ISSUE THREAD

**Issue by fullerrc** [spring-cloud/spring-cloud-stream#2449]
**Describe the issue**
The link in the repo's README to documentation on error channel handling (https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/#_spring_integration_error_channel_support) does not link to what it describes -- it appears to be broken.

**To Reproduce**
1. Go to '[spring-cloud-stream-binder-aws-kinesis](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/main/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc)'
2. Scroll down to '[Error Channels](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/main/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc#error-channels)'
3. Click on '[the section on Spring Cloud error channel support](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_spring_integration_error_channel_support)'
4. See nothing relevant

**Version of the framework**
**Expected behavior**
**Screenshots**

**Additional context**

**Comment by olegz** [comment]
Fixed!
