### ISSUE TITLE
Reactive Pulsar support

### ISSUE THREAD

**Issue by rolkhas2** [spring-cloud/spring-cloud-stream#2458]
I'd like to request support for Apache Pulsar in a reactive way. [This project can help](https://github.com/datastax/reactive-pulsar) with the interactions, what's left is only to write a binder.

This can turn this framework into a much more usable and wider framework.

Currently, when a user wants to write (an async of course) data pipeline with Spring Cloud Stream, there's no technology which the framework offers an out-of-the-box interaction with (only potentially with Kafka). I think a reactive Pulsar binder can turn this framework into a much more relevant one.

**Comment by sobychacko** [comment]
@rolkhas2 Closing this issue in favor of the Spring for Apache Pulsar repository at https://github.com/spring-projects-experimental/spring-pulsar.
