### ISSUE TITLE
Revisit ConnectionFactorySettings.rabbitConnectionFactory

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#246]
Assert if `ConnectionFactorySettings.rabbitConnectionFactory` is still needed, and if not supported by boot, propose as a Boot PR

see https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/ConnectionFactorySettings.java#L46

**Comment by sabbyanandan** [comment]
This may not be relevant anymore; closing this for now.
