### ISSUE TITLE
[pubsub]  subscription created too many

### ISSUE THREAD

**Issue by zouzhangqing** [spring-cloud/spring-cloud-stream#2460]
![image](https://user-images.githubusercontent.com/9544918/179944558-43a64b3a-8313-42bb-860e-09a0524813d2.png)

**Comment by olegz** [comment]
I am closing this issue as it provides no details or explanation of a problem

**Comment by zouzhangqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zouzhangqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
