### ISSUE TITLE
Enable ignored tests in RedisBinderTests

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#247]
Support `RedisBinderTests.createInboundPubSubBeforeOutboundPubSub` & `testSendAndReceivePubSub` or better document why it's `@Ignore`'d

see
https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-binders/spring-cloud-stream-binder-redis/src/test/java/org/springframework/cloud/stream/binder/redis/RedisBinderTests.java#L91

and 

https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-binders/spring-cloud-stream-binder-redis/src/test/java/org/springframework/cloud/stream/binder/redis/RedisBinderTests.java#L355

**Comment by mbogoevici** [comment]
Obsolete.
