### ISSUE TITLE
Streambridge  get wrong producer properties when sending partition message and non partition message

### ISSUE THREAD

**Issue by parkhaianh** [spring-cloud/spring-cloud-stream#2476]
Hello, I am using Spring cloud stream kafka binder in my project( ver 3.1.4)
I use StreamBridge for sending messages to multiple binding names. Some got partition key expression, others not.
Problem occurs when i send 1st message to topic that got partition key expression, then sending to the other. But StreamBridge still keep the producer properties. Debuging i found 
`Message<byte[]> resultMessage = (Message)((Function)functionToInvoke).apply(data);`
then jump to : 
 ```
 this.outputMessageEnricher = (output) -> {
                if (!(output instanceof Message)) {
                    output = MessageBuilder.withPayload(output).build();
                }

                int partitionId = partitionHandler.determinePartition((Message)output);
                return MessageBuilder.fromMessage((Message)output).setHeader("scst_partition", partitionId).build();
            };
```
This completely wrong because this object still keep partition key expression binding properties. It should return null for `outputMessageEnricher`
Am I missing anything? Thank for helping me

**Comment by olegz** [comment]
Can you please upgrade to the latest 3.2.4. There were quite a number of upgrades, fixes and modification to StreamBridge behavior. Also, the 3.1.x is out of support and no longer maintained.
If the issue still there please raise a new issue
