### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by T-TK-Wan** [spring-cloud/spring-cloud-stream#2478]
### Issue Description
There is a typo in the documentation for Kafka Stream Binders, specifically the **Functional Style** section of the latest documentation.

In the following line, **_suppports_** has an extra _**p**_.

`If the applications choose to define the functional beans using Spring’s Component annotation, the binder also suppports that model. The above functional bean could be rewritten as below.`

### Link to Issue
https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_functional_style

**Comment by sobychacko** [comment]
Thanks for the report. This is fixed.
