### ISSUE TITLE
Better jar de-deplication in ModuleLauncher

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#248]
In ModuleLauncher aggregating individual jars, do better jar de-duplication. Based on maven metadata rather than jar file name.

See https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-module-launcher/src/main/java/org/springframework/cloud/stream/module/launcher/ModuleLauncher.java#L148

**Comment by mbogoevici** [comment]
It's the other way around. On 'include' or 'exclude', the Maven metadata is taken into consideration, and Aether produces a list of unique artifacts. This affects specifically aggregation of individual jars.

**Comment by ericbottard** [comment]
My bad. Clarified

**Comment by sabbyanandan** [comment]
This is already in scope for the generic cloud deployer w-i-p.
