### ISSUE TITLE
Move some ModuleLauncher functionality in boot

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#249]
Ask Spring Boot team to widen visibility of `Launcher.launch(String[] args)`

**Comment by mbogoevici** [comment]
Just a note that this refers to the call within `ModuleJarLauncher`.

**Comment by ericbottard** [comment]
https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-module-launcher/src/main/java/org/springframework/cloud/stream/module/launcher/MultiArchiveLauncher.java#L68

and 

https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-module-launcher/src/main/java/org/springframework/cloud/stream/module/launcher/ModuleJarLauncher.java#L46

**Comment by sabbyanandan** [comment]
This is already in scope for the generic cloud deployer w-i-p.
