### ISSUE TITLE
ClassCastException: java.util.function.Supplier<reactor.netty.http.client.WebsocketClientSpec$Builder> can't be cast to (Class<?>)

### ISSUE THREAD

**Issue by AnnKont** [spring-cloud/spring-cloud-stream#2490]
Hello!

I have an error when add the dependency:
```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
</dependency>
```
Error:
```
org.springframework.beans.factory.BeanCreationException:
Error creating bean with name 'functionBindingRegistrar' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]:
Invocation of init method failed; nested exception is java.lang.ClassCastException:
class net.jodah.typetools.ReifiedParameterizedType cannot be cast to class java.lang.Class (net.jodah.typetools.ReifiedParameterizedType is in unnamed module of loader 'app';
java.lang.Class is in module java.base of loader 'bootstrap')
```

I use debug and understood that when spring try create bean `functionBindingRegistrar`, it try cast `java.util.function.Supplier<reactor.netty.http.client.WebsocketClientSpec$Builder>` to `(Class<?>)` and have an error.

![StackTrace](https://user-images.githubusercontent.com/35913355/185994680-7eab6f3d-ef5f-4f41-a1a7-db992101bf80.png)

Version: **3.2.3** (I tried 3.2.4 but still have this error)

**Comment by sobychacko** [comment]
@AnnKont Could you create a small reproducible sample for this issue? Thanks!
