### ISSUE TITLE
TODO in RabbitBindingCleaner

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#250]
see https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitBindingCleaner.java#L59

**Comment by sabbyanandan** [comment]
This is obsolete since the rabbit-binder is moved to a different repo altogether.
