### ISSUE TITLE
TODO in DefaultTupleTestForBatch

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#251]
see https://github.com/spring-cloud/spring-cloud-stream/blob/9dfa9c92186deab9861b6069c3caa264e41cc2cc/spring-cloud-stream-tuple/src/test/java/org/springframework/cloud/stream/tuple/DefaultTupleTestForBatch.java#L335

**Comment by sabbyanandan** [comment]
This is moved to `spring-projects/spring-tuple`.
