### ISSUE TITLE
When a reactive consumer throws an exception, the consumer stops reading messages

### ISSUE THREAD

**Issue by JordiMartinezVicent** [spring-cloud/spring-cloud-stream#2514]
**Describe the issue**

Consider a reactive consumer which for some unexpected reason any operator on the reactive chain throws an unexpected exception. 
When it happens the consumer stops reading the following messages and throws the following exception: 

```
ERROR 22728 --- [           main] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.consumer-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=org.jordi.springcloudstream.model.Person@10cb050, headers={id=7177a568-bcf9-8d73-82e9-713addda2c41, contentType=application/json, timestamp=1664288183033}], failedMessage=GenericMessage [payload=org.jordi.springcloudstream.model.Person@10cb050, headers={id=7177a568-bcf9-8d73-82e9-713addda2c41, contentType=application/json, timestamp=1664288183033}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317)
```

Furthermore, at least with kafka, the offset advances and the message will not be read any more. 

**To Reproduce**

Consider the following reactive consumer: 

```java 
public class ReactivePersonConsumer implements Function<Flux<Person>, Mono<Void>> {
  
@Autowired
  private Trasnformer transformer;

  @Override
  public Mono<Void> apply(final Flux<Person> flux) {
    return flux.map(this.transformer::transform)
        .then();
  }
}
```

If `transformer::transform` throws any exception. The consumer stops reading the following messages. 

In order to check the behaviour, you can run the following test: 

```java 

@SpringBootTest(properties = "spring.cloud.function.definition=consumer")
class ReactiveTest {

  @Autowired
  private InputDestination input;

  @SpyBean
  private Trasnformer transformer;

  @Test
  void exceptionInReactiveConsumerStopsConsumption() {

    Mockito.doThrow(new IllegalArgumentException("oh oh!"))
        .when(this.transformer).transform(Mockito.any());

    // First attempt
    this.input.send(MessageBuilder.withPayload(new Person("Doe")).build(), "consumer-in-0");

    // Although the consumer throws an exception, the assertion does not fail because it has been called
    Mockito.verify(this.transformer).transform(Mockito.any());

    Mockito.reset(this.transformer);

    // Second attempt
    this.input.send(MessageBuilder.withPayload(new Person("Doe")).build(), "consumer-in-0");

    // Fails!! MessageDispatchingException: Dispatcher has no subscribers
    Mockito.verify(this.transformer).transform(Mockito.any());

  }

  @SpringBootApplication
  @Import(TestChannelBinderConfiguration.class)
  static class SampleConfiguration {

  }
}
```

I have attached a project with the test. 

The behavior also can be observed running the project (which uses the kafka binder) and sending a couple of request to http://localhost:8080/send, which sends a message to the failing consumer. 

**Version of the framework**
Spring Boot version: 2.7.4
Spring cloud version: 2021.0.4

**Expected behavior**
The expected behavior would be that the following messages received after the failed message, will be read with normality. 

**Additional context**
It seems that this behavior is due to that the terminal signal produced at the reactor chain is propagated to the upstream, that is the flux where the message from the binder are injected. 

I guess that one way to solve the issue would be not propagating the terminal sign to the upstream. For example, in the consumer shown above, one possible solution would be something like: 

```java 
return flux
        .flatMap(p -> Flux.just(p)
            .map(this.transformer::transform)
            .onErrorContinue((t, o) -> {
              //Treat the exception here
            }))

        .then();
```

But from my point of view, I think that would be the best that Spring Cloud Stream would avoid the terminal signal propagation to the original flux. 

[spring-cloud-stream.zip](https://github.com/spring-cloud/spring-cloud-stream/files/9657003/spring-cloud-stream.zip)

**Comment by olegz** [comment]
Yes, that is exactly what is expected from user and is a known concern. 
I agree, it would be best for SCSt to handle it, but unfortunately we have absolutely no view into reactive implementation of such function. 

There is a fundamental difference between reactive and imperative function. 
**Imperative** function is a _message handler_ that is invoked by the framework on each message it receives. So for N messages there will be N invocations and because of that we can wrap and add additional functionality such as error handling, retries etc.
**Reactive** function is _initialization_ function. It is invoked only once to get a reference to a Flux/Mono provided by the user to be connected with the one provided by the framework. After that we have absolutely no visibility nor control. In other words in theory you can disconnect the entire SCSt framework from the process as at that time it plays no role at all. 

So, i'll close it as there is nothing to do. 
In the event you do have some ideas/suggestions please submit a PR so we can review
