### ISSUE TITLE
Binding-specific autoStartup property has no effect (kafka bindings)

### ISSUE THREAD

**Issue by dinosaur-guy** [spring-cloud/spring-cloud-stream#2519]
Setting the `autoStartup=false` property on specific bindings has no effect. The Kafka consumers still start. 

Setting `spring.cloud.stream.default.consumer.autoStartup=false` all bindings are stopped, but cannot be activated individually (e.g. setting `spring.cloud.stream.kafka.bindings.my-binding.autoStartup=true` or `spring.cloud.stream.bindings.my-binding.autoStartup=true`).

I also raised a question on StackOverflow: https://stackoverflow.com/questions/73468885/start-binding-in-paused-state since I am not sure if I am just using it wrong. But following the documentation, I don't see what I am doing wrong. 

I am using SpringBoot `2.7.4` with `org.springframework.cloud:spring-cloud-dependencies:2021.0.4`

**Comment by sobychacko** [comment]
@dinosaur-guy Just updated the SO thread with [an answer](https://stackoverflow.com/a/74033057/2070861) - sorry for not replying earlier. 

https://stackoverflow.com/questions/62577223/how-do-i-start-spring-cloud-stream-binders-manually-if-autostartup-is-set-to-fal

https://stackoverflow.com/questions/58795176/stop-consume-message-for-stream-listener

Basically, you need to use `spring.cloud.stream.bindings.<binding-name>.consumer.autoStartup` and set it to `false` or `true` to individually control it. 

If you set that to `false`, then you need to use the `BindingsEndpoint` mechanism described in the above threads to start the binding.

**Comment by dinosaur-guy** [comment]
Thank you. With those deeply nested configurations it is sometimes not easy to place the property at the correct place. This is working now.

**Comment by sobychacko** [comment]
Thanks for the feedback. Closing the issue since it is now working for you.
