### ISSUE TITLE
Sometimes StreamBridge is null using spring-cloud-stream 3.2.4 

### ISSUE THREAD

**Issue by samiran9sp6** [spring-cloud/spring-cloud-stream#2526]
sometimes everything is working smoothly but sometimes streamBridge is null.
I am using this dependencies:
                // RabbitMQ
		[ "org.springframework.boot:spring-boot-starter-amqp" ],
		[ "org.springframework.cloud:spring-cloud-stream:3.2.4" ],
		[ "org.springframework.cloud:spring-cloud-stream-binder-rabbit" ],
		[ "com.google.oauth-client:google-oauth-client:1.33.3" ],
		[ "org.springframework.cloud:spring-cloud-function-context:3.2.4" ],

@RequiredArgsConstructor
public class QueueService {

	private final StreamBridge streamBridge;
	
	@Trace
	@Retryable(value = Exception.class, maxAttempts = 3, backoff = @Backoff(delay = 1000))
	public void sendMessageToQueue(Message<Message> message) {
		boolean sent = streamBridge.send(Constants.BINDING_NAME, message);
		if(!sent) {
			throw new MessagingException(message);
		}
	}
}

I am not able to understand the reason, any thoughts how I can resolve it?

**Comment by gustavovieirasouza78** [comment]
I have it to publish messages on RabbitMQ, it works on several environments/nodes, which lead me to understand the code/ config is fine but in one it fails. 

The issue looks on getStreamBridgeFunction, for some reason the lookup is returning null, so the null value is added to streamBridgeFunctionCache and so null will be returned from this function every time.

I'm just not sure why the lookup is failing only here.

`	private synchronized FunctionInvocationWrapper getStreamBridgeFunction(String outputContentType, ProducerProperties producerProperties) {
		if (StringUtils.hasText(outputContentType) && this.streamBridgeFunctionCache.containsKey(outputContentType)) {
			return this.streamBridgeFunctionCache.get(outputContentType);
		}
		else {
			FunctionInvocationWrapper functionToInvoke = this.functionCatalog.lookup(STREAM_BRIDGE_FUNC_NAME, outputContentType.toString());
			this.streamBridgeFunctionCache.put(outputContentType, functionToInvoke);
			functionToInvoke.setSkipOutputConversion(producerProperties.isUseNativeEncoding());
			return functionToInvoke;
		}
	}`

**Comment by sobychacko** [comment]
Closing this issue. Feel free to re-open if you are still experiencing issues with this.
