### ISSUE TITLE
Definition of @ServiceActivator([destination].[group].errors) disables BinderErrorChannel

### ISSUE THREAD

**Issue by yoshikawaa** [spring-cloud/spring-cloud-stream#2539]
### versions
* Spring Boot: 2.7.3
* Spring Cloud: 2021.0.4

### Problem
```java
@Bean
public Consumer<Payload> consume() {
  return payload -> throw new RuntimeException("error");
}

@ServiceActivator(inputChannel = "destination.group.errors")
public void errorChannel(MessagingException e) {
  ...
}
```

Registering a `ServiceActivator` for "destination.group.errors" channel will break `MessageHandler` of the binder.

* When `ServiceActivator` is not registered, `BinderErrorChannel` bean is registered.
* When `ServiceActivator` is registered, `DirectWithAttributesChannel` bean is registered

If "destination.group.errors" bean is registered as `DirectChannel`, `AbstractMessageChannelBinder#isSubscribable` becomes `false`, so it does not subscribe to `Consumer<ErrorMessage>` and `MessageHandler` of the binder.

* https://github.com/spring-cloud/spring-cloud-stream/blob/v3.2.5/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L710-L712
* https://github.com/spring-cloud/spring-cloud-stream/blob/v3.2.5/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L764-L779

### Cause
"destination.group.errors" bean is registered as `DirectWithAttributesChannel` because [MessagingAnnotationPostProcessor>ServiceActivatorAnnotationPostProcessor>SubscribableChannelBindingTargetFactory] runs before [BindableFunctionProxyFactory>BindingService>Binder(RabbitMessageChannelBinder)].

* https://github.com/spring-cloud/spring-cloud-stream/blob/v3.2.5/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/SubscribableChannelBindingTargetFactory.java#L49-L76
* https://github.com/spring-cloud/spring-cloud-stream/blob/v3.2.5/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractMessageChannelBinder.java#L715-L721

Is this behavior expected?

**Comment by olegz** [comment]
Given that error-handling has been [completely revamped](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#spring-cloud-stream-overview-error-handling) I am closing this issue as there is nothing to do.

**Comment by yoshikawaa** [comment]
@olegz 
> error-handling has been completely revamped

Does that mean that ServiceActivator should already not be used in the functional programming model?
ServiceActivator is certainly available even now and is mentioned in the reference.
* https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#polled-errors

**Comment by yoshikawaa** [comment]
### Workaround for this issue

Define a bean in advance so that the "destination.group.errors" bean is not registered as a `DirectChannel`.

```java
@Bean
public Consumer<Payload> consume() {
  return payload -> throw new RuntimeException("error");
}

@Bean("destination.group.errors")
public SubscribableChannel destinationGroupErrorsChannel() {
  BinderErrorChannelWrapper channel = new BinderErrorChannelWrapper();
  channel.setComponentName("destination.group.errors");
  return channel;
}

@ServiceActivator(inputChannel = "destination.group.errors")
public void subscribeErrorChannel(MessagingException e) {
  ...
}
```
`org.springframework.cloud.stream.binder.BinderErrorChannel` used by the binder by default are package-private, so you'll need to extend this class to fully reproduce the behavior.

```java
public class BinderErrorChannelWrapper extends BinderErrorChannel {    
}
```
