### ISSUE TITLE
Partition properties needs to be set as producer properties only

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#254]
Currently, the partition properties are set as `BindingProperties`. Given the partition properties are only used as `producer` properties in `ChannelBindingServiceProperties`, it might make sense to retrieve the partition properties out of producer properties.

This would also ease the way we set the partition properties via dataflow as the partition properties are always set via `producer.*` prefix.

**Comment by markfisher** [comment]
But don't the partition properties need to be per-binding? (e.g. you might be sending messages to 2 different channels, using 2 different partition keys)

**Comment by ilayaperumalg** [comment]
Closing this as the partition properties need to be per-binding properties. Also, created https://github.com/spring-cloud/spring-cloud-stream/issues/256 to have producer/consumer properties per-binding level.

**Comment by mbogoevici** [comment]
Partition properties *are* per-binding: https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingProperties.java#L42

**Comment by mbogoevici** [comment]
We need to do away with the `producerProperties`/`consumerProperties` at `ChannelBindingServiceProperties` level, since we aren't actually using them at all (I would hope).

**Comment by ilayaperumalg** [comment]
I agree partition properties are per-binding, that's why closed this issue and created an issue to move producer/consumer properties into per-binding #256 .

Also, we actually use producer/consumer properties when the binder's producer/consumer properties need to be set when binding (like concurrency, next module count etc.,). From the dataflow side, we heavily rely on the producer/consumer properties that are passed via DSL.

**Comment by ilayaperumalg** [comment]
This [commit] (https://github.com/spring-cloud/spring-cloud-dataflow/commit/fd5f37594c4a2dad5a85d680a9a42fc7351c0ecf) addresses the issue related to passing producer/consumer properties via dataflow DSL:
