### ISSUE TITLE
[Bug] The 4.0.0-M5 reference doc of Handling Errors is not updated synchronously

### ISSUE THREAD

**Issue by moarychan** [spring-cloud/spring-cloud-stream#2545]
The [new changes to handle error messages](https://github.com/spring-cloud/spring-cloud-stream/issues/2507) have already been merged in the 4.0 milestone version, the [reference doc of Handling Errors](https://docs.spring.io/spring-cloud-stream/docs/4.0.0-M5/reference/html/spring-cloud-stream.html#polled-errors)(4.0.0-M5) is out of date. 

a new `Consumer` bean is required to consume the error message when consuming message exception,

```java
@Bean
Consumer<ErrorMessage> consumeError() {
    return exception -> {
        // xxx
    };
}
```
it does not work for consuming error messages when producing messages exception using the same way, the producing error message can be consumed in the channel `errorChannel` with `@ServiceActivator`.
```java
@ServiceActivator(inputChannel = "errorChannel")
public void processError(Message sendFailedMsg) {
    // xxx
}
```

I'm a bit confused, hoping to get instructions from the official documentation. Many thanks!

**Comment by olegz** [comment]
This has been addressed with https://github.com/spring-cloud/spring-cloud-stream/commit/58ef5b04790a1fd174c8514a09ca712af32a1f56.
