### ISSUE TITLE
Stream Binder Kafka adds kafka_2.13 dependency to compile scope

### ISSUE THREAD

**Issue by nlr234** [spring-cloud/spring-cloud-stream#2546]
Hi, 

In [3.2.4](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-stream-binder-kafka/3.2.4) vs [3.2.5](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-stream-binder-kafka/3.2.5) compile dependencies, it seems some of the test dependencies from 3.2.4 were added as compile dependencies in 3.2.5.

Besides that they're reported as double dependencies, with `kafka_2.13` it additionally adds all their transitive dependencies (like Scala) on your classpath which can give you unexpected results now.

Was this done intentionally?

**Comment by sobychacko** [comment]
@nlr234 Nothing has changed in terms of dependencies from 3.2.4 --> 3.2.5, but we will investigate why you are seeing this discrepancy. Thanks!

**Comment by sobychacko** [comment]
@nlr234 This was indeed caused by a change that we introduced. Apologies for the confusion. We will release `3.2.6` next week and this change will be included in that. In the meantime, if you could test the changes on `3.2.6-SNAPSHOT` and verify, that would be greatly appreciated.

**Comment by nlr234** [comment]
@sobychacko Thanks for this! The dependency is indeed gone now.

One minor thing, but I see:
```
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
		</dependency>
```
I think this is not really needed, as you already have:
```
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
		</dependency>
```
which has a dependency on `kafka-clients` already.

**Comment by sobychacko** [comment]
Good point. We will clean that up.
