### ISSUE TITLE
Upgrade to spring cloud aws 3.x

### ISSUE THREAD

**Issue by rajadilipkolli** [spring-cloud/spring-cloud-stream#2547]
Current spring-cloud-aws version used in `spring-cloud-stream-binder-kinesis` is 2.4.0. However, spring-cloud-aws has released 3.0.0-M3 which is internally using AWS SDKV2 instead of current AWS SDK v1 and improves performance

As spring cloud steam is moving towards Next Major version (4.x), it would be the better time to introduce AWS SDKV2. Do we have any plan to upgrade to the spring-cloud-aws 3.x?

**Comment by artembilan** [comment]
Closed in favor of #2390. 
We cannot move Kinesis Binder to AWS SDK v2 until all its upstream dependencies have migrated.
Especially I worry more about these two which looks like a part of AWS support by themselves:

https://github.com/awslabs/amazon-dynamodb-lock-client/issues/48
https://github.com/awslabs/amazon-kinesis-producer/issues/296
