### ISSUE TITLE
Rabbit Binder Non Blocking Retry Docs Still References @StreamListener

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2553]
https://docs.spring.io/spring-cloud-stream/docs/4.0.0-SNAPSHOT/reference/html/spring-cloud-stream-binder-rabbit.html#_retry_with_the_rabbitmq_binder

**Comment by olegz** [comment]
@garyrussell I don't see it. In fact the only thing i see is 2 references to [StreamListenerContainer](https://docs.spring.io/spring-cloud-stream/docs/4.0.0-SNAPSHOT/reference/html/spring-cloud-stream-binder-rabbit.html#_retry_with_the_rabbitmq_binder). Can you please take a look and see if this is still necessary?

**Comment by garyrussell** [comment]
Recently fixed by https://github.com/spring-cloud/spring-cloud-stream/commit/1edbd4abba8612bc3bf3de73a32c5f0d601fb860

>**Docs cleanup**
>Remove all references to EnableBinding/StreamListener from the docs
