### ISSUE TITLE
RabbitMQ Binder Table of Contents is Missing Entries

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#2554]
https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-rabbit.html#rabbitmq-stream-producer

Then scroll down - several missing sections.

**Comment by olegz** [comment]
Fixed with https://github.com/spring-cloud/spring-cloud-stream/commit/ec49293c488d0d67adb04bdf66fb8cc9e9c9231f
