### ISSUE TITLE
Migrating from BinderAwareChannelResolver to StreamBridge results in excessive metrics, swamping Prometheus

### ISSUE THREAD

**Issue by ae-govau** [spring-cloud/spring-cloud-stream#2556]
**Describe the issue**

Recently we bumped spring-cloud-dependencies from 2021.0.3 to 2021.0.4 and with that, we had to change code that used `BinderAwareChannelResolver` to use `StreamBridge` as per documentation.

Old code:

```java
// Autowired: BinderAwareChannelResolver bacr
final MessageChannel outputChannel = bacr.resolveDestination(someProperty.getBindingName());

// now use this to create and register an IntegrationFlow
```

New code:

```java
// Autowired: StreamBridge sb
final MessageChannel outputChannel = (message, timeout) -> sb.send(someProperty.getBindingName(), message);

// now use this to create and register an IntegrationFlow
```

We create maybe 40 such integration flows at startup.

This worked, but when we were close to deploying to production, we noticed it used a huge number of threads. We found this: https://stackoverflow.com/questions/73408817/kafka-version-3-0-1-kafka-admin-clients-created-repeatedly-memory-leak and figured we needed to bump `spring.cloud.stream.dynamic-destination-cache-size` to `100` (which is more than the number of destination topics we need).

This now worked much better - we stopped seeing the huge number of threads being used, however this time once we did get to production, we noticed that our Prometheus, which scrapes an Influx which gets metrics pushed to it by our Spring apps, was overwhelmed with high cardinality metrics.

When we dug into it it, we found that the number of Kafka time series metrics was growing at a steady rate, until our Prometheus was overwhelmed.

We noticed that many of the Kafka metrics included a `spring_id` and `client_id`, that each refer to a `producer-NNN` where NNN seemed to simply keep incrementing. e.g. `spring_id="<topic_name>.producer.producer-999"`

This seems new, since the Cloud Stream update and the switch to StreamBridge.

Is this high rate of producer churn expected and can it be remediated?

**Comment by olegz** [comment]
First thank you for all the details. . .

But , I can't seem to wrap my head around how can StreamBridge cause that which would make it nearly impossible for us to diagnose. 
Are you saying that going back to `BinderAwareChannelResolver` fixes the issue?
In other words I read two upgrades in your explanation; One is from 2021.0.3 to 2021.0.4 and another one is from `BinderAwareChannelResolver` to `StreamBridge`.
Can you clarify a bit more?

**Comment by ae-govau** [comment]
Hey @olegz , I'm pretty certain that `BinderAwareChannelResolver` was removed entirely from `2021.0.4`, which is the only reason we changed that code to use `StreamBridge`, and we did at the same time as part of that update.

Thus we are not able to test using `BinderAwareChannelResolver` with `2021.0.4`.  I guess in theory we could try using `StreamBridge` with `2021.0.3`, and perhaps we would have tried a few combinations like that if we noticed the issue earlier - unfortunately due to it being a non-functional issue (ie it works, it just has a side-effect of creating a lot more metrics) we didn't notice until we'd gone through a number of testing environments into production, where a larger mix and volume of data surfaced the issue.

I'm not keen to go back and try to roll back the `2020.0.3` update - this is a small part of a larger project for us. For now we've disabled export to infux entirely for the application that was causing us issues, but that's not a good spot for our app to be in.

**Comment by sobychacko** [comment]
@ae-govau Could you tell us how we can reproduce the issue on our end? If you can share a small sample app, that would be great. Please let us know how you want us to proceed.

**Comment by garyrussell** [comment]
@ae-govau 

Just for clarification; this works as expected with Boot 3/2022.0.0, Boot 2.7.7/2021.0.5 (and ...04); we only get 3 producers, as expected...

```java
	@Bean
	ApplicationRunner runner(StreamBridge bridge) {
		return args -> {
			MessageChannel foo = (msg, to) -> bridge.send("foo", msg);
			MessageChannel bar = (msg, to) -> bridge.send("bar", msg);
			MessageChannel baz = (msg, to) -> bridge.send("baz", msg);
			foo.send(new GenericMessage<>("foo"));
			bar.send(new GenericMessage<>("bar"));
			baz.send(new GenericMessage<>("baz"));
			foo.send(new GenericMessage<>("foo"));
			bar.send(new GenericMessage<>("bar"));
			baz.send(new GenericMessage<>("baz"));
		};
	}
```

If you can't provide a similar, small, example that exhibits the behavior you are seeing, I suggest you use a debugger in `DefaultKafkaProducerFactory.createProducer()` to see where/why the additional producers are being created.

You could also add this, to get a stack trace for each producer that is created...

```java
	@Bean
	ClientFactoryCustomizer cust() {
		return new ClientFactoryCustomizer() {

			@SuppressWarnings("unchecked")
			@Override
			public void configure(ProducerFactory<?, ?> pf) {
				pf.addListener(new Listener() {

					@Override
					public void producerAdded(String id, Producer producer) {
						System.out.println("client.id: " + id);
						new RuntimeException("producerCreated").printStackTrace();
					}

				});
			}

		};
	}
```

There should be one producer factory/producer for each binding, with stack traces like this...
```
client.id: baz.producer.producer-3
java.lang.RuntimeException: producerCreated
	at com.example.demo.Kbgh2556Application$1$1.producerAdded(Kbgh2556Application.java:51)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory.lambda$doCreateProducer$17(DefaultKafkaProducerFactory.java:749)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory.doCreateProducer(DefaultKafkaProducerFactory.java:749)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory.createProducer(DefaultKafkaProducerFactory.java:727)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory.createProducer(DefaultKafkaProducerFactory.java:721)
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.lambda$createProducerMessageHandler$0(KafkaMessageChannelBinder.java:412)
    ...
```

**Comment by sobychacko** [comment]
Closing this issue based on Gary's comments above and no new activity lately. Please feel free to re-open if you are still experiencing issues with this.
