### ISSUE TITLE
cloud.stream.output-bindings doesn't work if there is no consumer

### ISSUE THREAD

**Issue by Toxa45** [spring-cloud/spring-cloud-stream#2558]
Good afternoon.
I noticed that cloud.stream.output-bindings does not work if there is no user.
That is, when the application starts, the MessageChannel specified in the output-bindings is not registered, and as a result, the spring-integration metrics do not work.
If there are consumers, then everything works as it should.

I think the error is here
https://github.com/spring-cloud/spring-cloud-stream/blob/c70f7d49497ecb0da945be2d30c3f5d46d87046a/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/function/FunctionConfiguration.java#L933

https://github.com/spring-cloud/spring-cloud-function/blob/a288810f3dca753405d8915f2d588d3d26220a23/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L247

The list of eligibleFunction always has 1 element = "traceFunctionAroundWrapper" and as a result the values ​​from cloud.stream.output-bindings are ignored.

Example from application.yml
spring:
   cloud:
     stream:
       output-bindings: output
       bindings:
         output-out-0:
           destination: CRM

After looking at the code, I noticed that this can be bypassed by adding a ' | ' symbol at the end of the name.
output-bindings: output|
and for multiple values
output-bindings: output1|;output2|

Can you advise something?

**Comment by Toxa45** [comment]
spring cloud version 2021.0.4

**Comment by poznachowski** [comment]
I can second that. That is what happened to me just now. One of my services was working just fine: consumer(s) + producer(s) using StreamBridge. I had to remove consumer leaving just producers and hell broke lose.
It may be also connected to the fact of using spring-cloud-sleuth. When I disabled it was fine. @Toxa45 can you try disabling Sleuth and check ? I assume you have it as `traceFunctionAroundWrapper` is Sleuth's codebase.

I confirm that 'hack' of adding `|` helped.
SB: 2.7.5
SC: 2021.0.4

**Comment by Toxa45** [comment]
> Я могу подтвердить это. Это то, что случилось со мной только что. Один из моих сервисов работал нормально: потребитель(и) + производитель(и) с использованием StreamBridge. Мне пришлось удалить потребителя, оставив только производителей, и ад сломался. Это также может быть связано с использованием spring-cloud-sleuth. Когда я отключил, все было в порядке.@Toxa45Вы можете попробовать отключить Sleuth и проверить? Я предполагаю, что у вас есть `traceFunctionAroundWrapper`кодовая база Сыщика.
> 
> Подтверждаю, "хак" добавления `|`помог. ШБ: 2.7.5 СК: 2021.0.4

Да, если отключить spring-cloud-sleuth то ошибка пропадает, я это тоже заметил. Но в моем случае нельзя отказаться от него.

**Comment by poznachowski** [comment]
It seems that using `|` is not enough as the `BindingService` tried to bind `traceFunctionAroundWrapper` to underlying GCP Pub/Sub binder which obviously failed.
I was able to workaround this by exluding the Sleuth's wrapper:
```
spring:
  cloud:
    function:
      ineligible-definitions:
        - "traceFunctionAroundWrapper"
```

**Comment by olegz** [comment]
Can you please upgrade to 2021.0.5 since  `traceFunctionAroundWrappe`r was excluded from lookup

**Comment by olegz** [comment]
Closing it due to inactivity from the reporter
