### ISSUE TITLE
Exception 'Dispatcher has no subscribers for channel' thrown when RefreshScope is in a bean with StreamListener

### ISSUE THREAD

**Issue by KevinYangYYz** [spring-cloud/spring-cloud-stream#2561]
@Component
@Log4j2
@RefreshScope
public class MQMessageListener {

    @Resource
    TDengineDao tdEngineDao;

    @Resource
    EquipmentDao equipmentDao;

    @Autowired
    DevMsgPipeline pipeline;

    @Value("${log.enable}")
    int logEnable;

    @StreamListener(value = "errorChannel")
    public void handleMQException(ErrorMessage errorMsg) {

        log.error("【handleMQException】MQ消费消息出现异常，消息内容：{}, 异常信息：{}", JSONObject.toJSONString(errorMsg.getOriginalMessage()), errorMsg.getPayload().getLocalizedMessage());
    }

    @StreamListener(value = MQConsumerFactory.MSG_TO_TDENGINE_CHANNEL, condition = "headers['rocketmq_TAGS'] == 'DEVICE_MESSAGE_TO_TDENGINE'")
    public void dealWithMsgToTDengine(Message message) {

        SubTableValue sub = JSONObject.parseObject(message.getPayload().toString(), SubTableValue.class);
        insertDeviceData(Collections.singletonList(sub));
    }
}

**Comment by sobychacko** [comment]
@KevinYangYYz `StreamListener` has been deprecated for a long time and completely removed in the upcoming `4.0.0` release. Please update your code to use the new functional style and see if the problem persists.

**Comment by KevinYangYYz** [comment]
Ok, thanks. I'll try again

**Comment by olegz** [comment]
I am going to close it since anything related `StreamListener` is no longer supported
