### ISSUE TITLE
Is it possible to disable target-protocol in headers

### ISSUE THREAD

**Issue by Toxa45** [spring-cloud/spring-cloud-stream#2564]
Good afternoon. 
Is it possible to disable target-protocol in headers?
spring boot 2.7.5, cloud 2021.0.4

**Comment by olegz** [comment]
Any reason why you would want it to be disabled? It's an undocumented header (used internally) so user should not be concerned with that

**Comment by olegz** [comment]
Closing due to lack of follow up from the original reporter. Please feel free to reopen or open new one when requested details are available

**Comment by Toxa45** [comment]
Добрый день.
Выяснилось, что внешняя система не может обрабатывать заголовки в которых есть символ '-'. Как итог после обновления на нашей стороне, обмен перестал работать
