### ISSUE TITLE
Use of spring.cloud.stream.defaultBinder cause natively compiled Spring Boot 3 applications to fail during startup

### ISSUE THREAD

**Issue by magnus-larsson** [spring-cloud/spring-cloud-stream#2569]
**Describe the issue**

Setting the property `spring.cloud.stream.defaultBinder` cause natively compiled applications using Spring Boot 3 to fail during startup with one of the error messages:

```
Caused by: java.lang.IllegalStateException: Can't determine which binder to use: rabbit/1
Caused by: java.lang.IllegalStateException: Can't determine which binder to use: kafka/1
```

Depending on if the property is set to either `rabbit` or `kafka`.

**To Reproduce**

1. Use the `cloud-stream-rabbit` project in the `spring-aot-smoke-tests` GitHub-repo:

       git clone git@github.com:spring-projects/spring-aot-smoke-tests.git
       cd spring-aot-smoke-tests/cloud/cloud-stream-rabbit

1. Add `spring.cloud.stream.defaultBinder: rabbit` to the file `src/main/resources/application.yml`

1. Native compile:

       ../../gradlew nativeCompile

1. Run the natively compiled application

       ./build/native/nativeCompile/cloud-stream-rabbit

1. It will fail during startup with the root cause error:

       Caused by: java.lang.IllegalStateException: Can't determine which binder to use: rabbit/1

**Note:** The same problem can be observed in the project `cloud-stream-kafk` if the property is set to `kafka`.

**Version of the framework**

Spring Framework: 6.0.1
Spring Boot: 3.0.0-SNAPSHOT
Spring Cloud Stream: 4.0.0-SNAPSHOT

**Expected behavior**

That the application starts with no errors, as when the property `spring.cloud.stream.defaultBinder` is not set.

**Screenshots**

No

**Additional context**

No

**Comment by Dam14n** [comment]
Hi guys, 

I'm facing the same issue in a project that I'm working on. It is working on non-AOT mode but with native enabled it is failing due to:

```
Caused by: java.lang.IllegalStateException: Can't determine which binder to use: rabbit/1
```

**Comment by magnus-larsson** [comment]
Hello @sobychacko, thanks for helping us out!

Yes, with 4.0.0-SNAPSHOT, native compile works using the `spring.cloud.stream.defaultBinder` property!

But when adding a dependency to both the rabbit and kafka binder, the error comes back.
(the reason for using the `spring.cloud.stream.defaultBinder` property is to have both dependencies on the classpath)

Like:

```
implementation("org.springframework.cloud:spring-cloud-stream-binder-rabbit")
implementation("org.springframework.cloud:spring-cloud-stream-binder-kafka")
```

This results in a similar error message ("/1" replaced with "/2"):

```
Caused by: java.lang.IllegalStateException: Can't determine which binder to use: rabbit/2
```

Do you want me to open a new issue for this, or can we reopen this one and continue here?
