### ISSUE TITLE
Composition of source, processor and sink in single JVM fails

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#257]
As a developer, I'd like to troubleshoot the anomaly when we compose source, processor and sink in a single JVM. 

**Acceptance:**
All the [tests](https://github.com/ilayaperumalg/spring-cloud-stream/commit/40c6c3504fc7a0251ce137130ee6e18b2dce63b2#diff-b7a90e11abc7f08eb2403bd3fb1a0ef3L72) from `MessageChannelConfigurerTests` successfully runs with `source`, `processor` and `sink` channels.

**Comment by sabbyanandan** [comment]
Since this could be an anomaly with current binder design, this will be addressed based on #263 strategy.

**Comment by mbogoevici** [comment]
Hi @sabbyanandan,
Can you describe the test scenario/outcome a little bit? How to reproduce this?

Cheers,
Marius

**Comment by sabbyanandan** [comment]
Welcome back @mbogoevici!

The easiest is to bring back these [tests](https://github.com/ilayaperumalg/spring-cloud-stream/commit/40c6c3504fc7a0251ce137130ee6e18b2dce63b2#diff-b7a90e11abc7f08eb2403bd3fb1a0ef3L72), run them, and observer the behavior.

**Comment by mbogoevici** [comment]
Alright, thanks @sabbyanandan. Probably this type of scenario belongs in the aggregation bucket, e.g. 
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-samples/double/src/main/java/demo/DoubleApplication.java, but I agree this still requires some investigation.

**Comment by mbogoevici** [comment]
Actually, we do not support having the same channel name declared twice for separate interface (and processor overlaps with both sink and source). Closing this and perhaps we should have a better story for embedding in 1.1.
