### ISSUE TITLE
Adding dependencies to both RabbitMQ and Kafka binders cause natively compiled Spring Boot 3 applications to fail during startup

### ISSUE THREAD

**Issue by magnus-larsson** [spring-cloud/spring-cloud-stream#2584]
**Describe the issue**

**Note:** This is a followup on #2569.

Adding dependencies to both RabbitMQ and Kafka binders:

```
implementation 'org.springframework.cloud:spring-cloud-starter-stream-rabbit'
implementation 'org.springframework.cloud:spring-cloud-starter-stream-kafka'
```

...and setting the property `spring.cloud.stream.defaultBinder` cause natively compiled applications using Spring Boot 3 to fail during startup with one of the error messages:

```
Caused by: java.lang.IllegalStateException: Can't determine which binder to use: rabbit/2
Caused by: java.lang.IllegalStateException: Can't determine which binder to use: kafka/2
```

Depending on if the property is set to either `rabbit` or `kafka`.

**To Reproduce**

1. Use the `cloud-stream-rabbit` project in the `spring-aot-smoke-tests` GitHub-repo:

       git clone git@github.com:spring-projects/spring-aot-smoke-tests.git
       cd spring-aot-smoke-tests/cloud/cloud-stream-rabbit

1. Add `spring.cloud.stream.defaultBinder: rabbit` to the file `src/main/resources/application.yml`

1. Add `implementation("org.springframework.cloud:spring-cloud-stream-binder-kafka")` to the file `build.gradle`

1. Native compile:

       ../../gradlew nativeCompile

1. Run the natively compiled application

       ./build/native/nativeCompile/cloud-stream-rabbit

1. It will fail during startup with the root cause error:

       Caused by: java.lang.IllegalStateException: Can't determine which binder to use: rabbit/2

**Note:** The same problem can be observed in the project `cloud-stream-kafka` if the property is set to `kafka` and the dependency `implementation 'org.springframework.cloud:spring-cloud-starter-stream-kafka'` is added.

**Version of the framework**

Spring Framework: 6.0.2
Spring Boot: 3.0.0-SNAPSHOT
Spring Cloud Stream: 4.0.0-SNAPSHOT

**Expected behavior**

That the application starts with no errors, as when only one dependency to either the RabbitMQ or the Kafka binder is used.

**Screenshots**

No

**Additional context**

No

**Comment by sobychacko** [comment]
@magnus-larsson We addressed this issue through the commit mentioned above. Could you try the app and verify now?

**Comment by magnus-larsson** [comment]
Thanks, works fine now!
