### ISSUE TITLE
Version for org.springframework.cloud:spring-cloud-stream:test-jar:test-binder is missing

### ISSUE THREAD

**Issue by ivangfr** [spring-cloud/spring-cloud-stream#2598]
Hi, I've generated a simple **Spring Boot 3.0.0** project using **start.spring.io** and added just the "**Cloud Stream**" dependency.

After unzipping the project, I've run `./mvnw dependency:tree` inside the project folder.

However, it's complaining that the version for the dependency `org.springframework.cloud:spring-cloud-stream:test-jar:test-binder` is missing.
```
$ ./mvnw dependency:tree
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-stream:test-jar:test-binder is missing. @ line 31, column 15
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.example:demo:0.0.1-SNAPSHOT (/Users/ivan.franchin/Downloads/demo/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-stream:test-jar:test-binder is missing. @ line 31, column 15
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
``` 
Thanks!

**Comment by kschlesselmann** [comment]
I've just run into the same issue on my project during an update:
```
Could not find spring-cloud-stream-4.0.0-test-binder.jar (org.springframework.cloud:spring-cloud-stream:4.0.0).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-stream/4.0.0/spring-cloud-stream-4.0.0-test-binder.jar
```
even though we have configured the test binder according to the [documentation](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_test_binder_configuration).

**Comment by vvalencia-cl** [comment]
It seems that the Test Binder was extracted to its own artifact:
org.springframework.cloud:spring-cloud-stream-test-binder

But the documentation and the changelog don't mention it

**Comment by sobychacko** [comment]
@ivangfr @kschlesselmann As mentioned by @vvalencia-cl above, the test binder has now been moved into a dedicated artifact. You must add the following dependency instead of using the `test-binder` classifier approach. Please remove it from your build configuration and add the following. 
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-test-binder</artifactId>
	<scope>test</scope>
</dependency>
```

We will fix it on the initializr side and cleanup the docs. Thanks for pointing these out. 

This [release blog ](https://spring.io/blog/2022/12/02/spring-cloud-2022-0-0-release-candidate-3-codename-kilburn-has-been-released) for Spring Cloud `2020.0.0` RC3 mentions about these changes under the Spring Cloud Stream section.

**Comment by sobychacko** [comment]
@ivangfr @kschlesselmann, Could you try generating the app from `start.spring.io` again? It is populating the proper test-binder dependency.

**Comment by ivangfr** [comment]
@sobychacko yes, using version `3.0.1` works. Thanks!
