### ISSUE TITLE
Map of PollableMessageSource bean not injected in 4.0.0

### ISSUE THREAD

**Issue by apetrelli** [spring-cloud/spring-cloud-stream#2602]
When using Spring boot 3.0.0 and Spring cloud stream 2022.0.0 (thus 4.0.0), a Map of all beans implementing PollableMessageSource is not injected correctly.

Everything works with Spring Boot 2.7.6 and Spring Cloud Stream 2021.0.5.

To reproduce the bug:

1. Launch a RabbitMQ instance:

```
sudo docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.11-management
```

2. Uncompress the attached project and launch:

```
mvn spring-boot:run
```

It logs every second the fact that the map of all PollableMessageSource is empty.

If you switch to 2.7.6 and 2021.0.5
 it logs the polling correctly.

[poller-bug.zip](https://github.com/spring-cloud/spring-cloud-stream/files/10294004/poller-bug.zip)

**Comment by apetrelli** [comment]
From my experiments it seems that the PollableMessageSource beans are created after the map is injected (in 2021.0.5 it is the opposite).

**Comment by olegz** [comment]
You were correct, there was a lifecycle issue related to a change triggered by AOT/Native effort. Anyway, I made it ApplicationContextInitializer so it would be initialised rather early.

**Comment by apetrelli** [comment]
Thanks! Waiting for 4.0.1 version then.
