### ISSUE TITLE
Add some new features of jdk to the main branch to optimize the code

### ISSUE THREAD

**Issue by oswardlx** [spring-cloud/spring-cloud-stream#2605]
like "switch"
![image](https://user-images.githubusercontent.com/33048303/210335127-e5b63275-523d-475a-97e6-c59b49eec2fe.png)
to simplified code
![image](https://user-images.githubusercontent.com/33048303/210335155-7ece92fa-9ae1-42de-9bf4-771aa72feb0d.png)

like "instanceof"
![image](https://user-images.githubusercontent.com/33048303/210335182-b653a741-7a1f-4d1b-b334-654bba1e56ef.png)
to simplified code
![image](https://user-images.githubusercontent.com/33048303/210335220-ac557f33-3e39-4095-b71a-1878b4ccdb94.png)

**Comment by olegz** [comment]
Resolved with https://github.com/spring-cloud/spring-cloud-stream/pull/2606
