### ISSUE TITLE
AdminClientConfig bootstraps twice when enable-observation=true 

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-stream#2616]
**Describe the issue**
In Spring Cloud 2022.0.0 when setting _spring.cloud.stream.kafka.binder.enable-observation=true_ you get a double bootstrap of AdminClientConfig.  The first bootstrap respects all the spring env settings however the second defaults to localhost so it's a strange one.  I noticed this in our test environment as streams was trying to connect to localhost.

I have an example here: https://github.com/davidmelia/spring-cloud-function-zipkin/blob/observation_bug/src/test/java/example/SendKafkaMessageTest.java 

If you run the test

```
@SpringBootApplication
@SpringBootTest
@TestPropertySource(properties = {
    "spring.cloud.stream.bindings.test-out-0.destination=test"
    ,"spring.cloud.stream.kafka.bindings.test-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer"
    ,"spring.cloud.stream.kafka.bindings.test-out-0.producer.configuration.value.serializer=org.springframework.kafka.support.serializer.JsonSerializer"
    ,"spring.cloud.stream.kafka.binder.configuration.ssl.protocol=TLSv1.2"
    ,"spring.cloud.stream.kafka.binder.enable-observation=true"
      
})
public class SendKafkaMessageTest {
  
  @Autowired
  private StreamBridge streamBridge;

  @Test
  void testName() throws Exception {
    Object kafkaEvent = MessageBuilder
        .withPayload(Map.of("Key", String.format("Value @ %s", ZonedDateTime.now(ZoneOffset.UTC))))
        .setHeaderIfAbsent(KafkaHeaders.KEY, UUID.randomUUID().toString())
        .build();
    boolean result = streamBridge.send("test-out-0", kafkaEvent);
    Assert.isTrue(result);
  }
  
}
```

Then you will notice o.a.k.clients.admin.AdminClientConfig bootstraps twice.  The first one respects my property _spring.cloud.stream.kafka.binder.configuration.ssl.protocol_ but the second one ignores any settings.  

Further to this the test does **not** send the kafka message.

Setting _spring.cloud.stream.kafka.binder.enable-observation=false_ solves the problem and only one AdminClientConfig is bootstrapped with the correct setting of TLSv1.2

Thanks

**Comment by garyrussell** [comment]
Possibly a dup. - see https://github.com/spring-cloud/spring-cloud-stream/issues/2576#issuecomment-1348666138

The work around is to use `spring.kafka.bootstrap-servers` instead of the binder property.
