### ISSUE TITLE
InteractiveQueryService using KafkaStreams deprecated API

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-stream#2619]
Based on [this discussion](https://github.com/spring-cloud/spring-cloud-stream/pull/2618#discussion_r1066404442) we should replace the deprecated call w/ the newer API in KafkaStreams. 

When we do make the change, ensure this will not cause any issues w/ versions of kafka-streams `< 3.3.1`.

**Comment by sobychacko** [comment]
Resolved via https://github.com/spring-cloud/spring-cloud-stream/commit/d650f9e1e89a3d70291b22e102bf4d3af3dbf101
