### ISSUE TITLE
Explore options to support only pub/sub for binders

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#263]
As a developer, I'd like to investigate how to only support `pub/sub` (vs. `queue`) semantics at the binder level. With this spike, we would also want to address the following.

- would the `pub/sub` semantics apply to producer, consumer, or both sides?
- what happens to `redis` as a binder if we do not support `queue:` semantics?
- perhaps drop the notion of `request` and `reply` at the binder level

**Comment by markfisher** [comment]
The (review only) PR #276 shows the results of this spike. In the next sprint, that will be ready for merging, and it addresses all current `Binder` implementations.
