### ISSUE TITLE
Enhance StreamBridge for custom binders

### ISSUE THREAD

**Issue by Netyyyy** [spring-cloud/spring-cloud-stream#2638]
**Describe the issue**
When send and receive messages from EventHubs, if I send message with `StreamBridge#send`, It will create a new header `target-protocol=kafka`, and finally return a header `source-type=kafka`.

**To Reproduce**
1. Run this sample [eventhubs-binder](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/spring-cloud-azure-stream-binder-eventhubs/eventhubs-binder) with `manual` profile.
2. curl -X POST http://localhost:8080/messages/imperative?message=hello

**Version of the framework**
Frameworks: Spring Boot 2.7.7
Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-eventhubs:4.5.0
Java version: 17

**Expected behavior**
The header `target-protocol/source-type` could be more flexible, if the binder doesn't startwith `Rabbit`, it may not be `kafka` either.
![image](https://user-images.githubusercontent.com/92105726/215443780-ebe2ef3b-9105-4d8a-97b2-c469bfb7aa10.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/92105726/215444207-77ae00e8-eac8-424a-9d64-86ad12478a8c.png)

**Comment by olegz** [comment]
So the `target-protocol` header is an internal non-documented header. While it may not make sense in what you are describing, the fact that it is internal (for internal use only) should not be affecting you. If it does, that we would like to know what that is. . So what exactly are you asking for with this issue?
