### ISSUE TITLE
Spring Cloud connectors should not be required to run in Cloud Foundry

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#264]
With 1.0.0.M2 I could run an app with spring-cloud-stream-binder-rabbit and it would connect to the default `ConnectionFactory` created by the build pack. With 1.0.0.M3 I have to add spring-boot-starter-cloud-connectors.

**Comment by ilayaperumalg** [comment]
@dsyer When I tried to push the app to CF using buildpack,

```
cf push <APP-NAME> -p <ARTIFACT> -b https://github.com/cloudfoundry/java-buildpack.git
```

I see the associated `ConnectionFactory` (created by the buildpack via its cloud connectors) is used. Note that I tried this via `redis` service as I have some trouble running `rabbitmq` service in general on CF.

**Comment by dsyer** [comment]
Which app? And what do you mean by "the associated `ConnectionFactory`"? To clarify: this issue is about a regression. You shouldn't need connectors (and you may have to exclude them from `s-c-stream-*` to see the failure).

If you can't use rabbit in PWS that is a problem as well. Redis has problems in CF for me (connections keep getting dropped).

**Comment by ilayaperumalg** [comment]
The app I had is a source module from SCSM that has `spring-cloud-stream-binder-redis` dependency and I have also **excluded** the connectors dependencies from SCSM modules parent with the intention to see the failure.

I tried this on PEZ environment.

**Comment by dsyer** [comment]
I can't reproduce this problem on master. Assume fixed.
