### ISSUE TITLE
Spring Cloud Stream Kafka: message consumption always on one thread no matter the number of CPU from machine

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-stream#2645]
Hello Spring Cloud Stream team,

I would like to report a small issue regarding threading please, hope not to trouble.

I have a very simple Spring Cloud Stream Kafka + reactive functions project, as follow:

```
package com.example.micrometer;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.function.Consumer;

@SpringBootApplication
public class StreamReactiveConsumerApplication implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(StreamReactiveConsumerApplication.class);
    
    public static void main(String... args) {
        new SpringApplicationBuilder(StreamReactiveConsumerApplication.class).run(args);
    }

    @Override
    public void run(String... args) {
    }

    @Bean
    Consumer<Flux<Message<String>>> consume() {
        return flux -> flux
                .flatMap(one -> myHandle(one) )
                .subscribe();
    }

    private Mono<String> myHandle(Message<String> one) {
        log.info("<==== look at this thread, it is always the same!" + "\u001B[32m" + one.getPayload() + "\u001B[0m");
        String payload = one.getPayload();
        String decryptedPayload = complexInMemoryDecryption(payload); //this is NON blocking, takes 1 second
        String complexMatrix = convertDecryptedPayloadToGiantMatrix(decryptedPayload);  //this is NON blocking, takes 1 second
        String newMatrix = matrixComputation(complexMatrix); //this is NON blocking, takes 1 second
        return myNonBlockingReactiveRepository.save(complexMatrix);
    }

}

```

pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>streamreactiveconsumer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.2</version>
        <relativePath/>
    </parent>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2022.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

I am consuming from a topic with 1 partition. The rate of the messages sent is one message per second.

The consumption and the processing of the message takes 3ish seconds second per message.

Important: please note the processing does not contain any blocking operation. It is a giant in memory decryption + giant matrix computation. It is BlockHound tested NON blocking.

Actual: When I consume the messages with project Spring Cloud Stream Kafka, the whole consumption + processing, message handling happens on one thread only. Everything happens on container-0-C-1

Everything will happen on container-0-C-1, tested with hardware with 2 CPUs, 4 CPUs, 8 CPUs

```
2023-02-06 10:42:59 8384 INFO  --- [KafkaConsumerDestination{consumerDestinationName='prod_audit_hdfs', partitions=3, dlqName='null'}.container-0-C-1] [stream-reactive-consumer,,] c.e.m.StreamReactiveConsumerApplication :
2023-02-06 10:42:59 8384 INFO  --- [KafkaConsumerDestination{consumerDestinationName='prod_audit_hdfs', partitions=3, dlqName='null'}.container-0-C-1] [stream-reactive-consumer,,] c.e.m.StreamReactiveConsumerApplication :
2023-02-06 10:42:59 8384 INFO  --- [KafkaConsumerDestination{consumerDestinationName='prod_audit_hdfs', partitions=3, dlqName='null'}.container-0-C-1] [stream-reactive-consumer,,] c.e.m.StreamReactiveConsumerApplication :
```

**Expected**:
We migrated from http webflux based to Kafka consumption based. The business logic did not change one bit.

On the Reactor Netty Spring webflux application, we could see processing happening from multiple thread, corresponding to the reactor cores. On a machine with many cores, this could keep up easily.

```
[or-http-epoll-1] [or-http-epoll-2] [or-http-epoll-3] [or-http-epoll-4]
```

The processing would just switch between any of those ```reactor-http-epoll-N```.
I could see when reactor-http-epoll-1 is handling the complex in memory computation for the first message, reactor-http-epoll-3 would handle the computation for the second message, etc... The parallelism is clear.

I understand there are way to "scale" this application, but this a question in terms of Spring Cloud Stream Kafka with reactive functions itself.

I expect the messages would be handled in parallel. Some kind of ```container-0-C-1``` for the first message, ```container-0-C-2``` for the second message, etc...

How can I achieve that please?
What am I missing?

Thank you

**Comment by garyrussell** [comment]
Each partition of a topic can only be consumed on one thread so if the topic only has one partition, there will only be one consumer, regardless of the `...consumer.concurrency` property. If there are multiple partitions, they will be distributed across multiple consumers, according to the `concurrency`.

**Comment by patpatpat123** [comment]
Thank you for your answer @garyrussell,

I tried the same code on a topic with multiple partitions (2, 3, 8, 1000) and if the concurrency is set to 1, the app would still consume 2, 3, 8, 1000 on only one thread ```container-0-C-1```.

Please let me know if my expectation is incorrect, as I am coming from Reactor Netty world, if the number of requests gets higher, while one thread is processing the http request, if the machine has multiple CPUs, i.e. multiple reactor cores, the framework will just let another thread, another reactor-http-epoll-N take care of the next request.

Here, in Spring Cloud Stream, even if I use reactive programming, due to the yet NON blocking but long processing of the message + that everything happens on one thread, I am quickly falling behind.

Is there a way to let the framework "switch thread" similar to Reactor Netty, when the processing of the message, even NON blocking, is lengthy please?

Thank you in advanced for your answer.

**Comment by garyrussell** [comment]
Your expectation is incorrect; the standard Kafka (message channel) binder is not reactive - it has one thread per consumer. The problem is that Kafka only maintains a pointer (last committed offset) into the partition. Individual records in the partition cannot be acknowledged.

The binder is not really designed for reactive workloads.

However, it does support multi-threading (at the application level), if you set the listener container property `asyncAcks`, it can support out of order commits, by deferring the commits for later offsets until the gaps are filled, but you have to manually acknowledge each record.

There is a newer Kafka binder, based on the `reactor-kafka` project, which can natively support reactive workloads.

https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_reactive_kafka_binder

It is quite basic at the moment; the next patch release will allow much more control over the consumer configuration.

https://github.com/spring-cloud/spring-cloud-stream/pull/2637

**Comment by patpatpat123** [comment]
Very clear answer, and I am getting excited about the reactor binder as we speak!

I gave it a go with this same example using Reactor Kafka only (no Spring Cloud Stream) and can observe the same issue.

Please let me gather more data and some test cases with both Reactor Kafka, and Spring Cloud Stream reactive Kafka binder and will update the issue

**Comment by garyrussell** [comment]
The KafkaConsumer is not thread safe; therefore, reactor-kafka has an event loop where all operations on the consumer are done on a single thread including emitting them to the sink. You need to add a `publishOn()` to the flux to go multi-threaded; but it, too, suffers from the out of order commit problems. To avoid that, you have to set the `ReceiverOptions.maxDeferredCommits` property to enable commit deferrals in the same manner that I described above. See the reactor-kafka docs.

**Comment by patpatpat123** [comment]
As always, very clear, many thanks @garyrussell
