### ISSUE TITLE
Spring Cloud Brixton.M4 fails due to dependency

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-stream#265]
I tried Spring Cloud Brixton.M4 with ```spring-cloud-starter-bus-amqp```

It is failing since ```spring-cloud-starter-stream-rabbit:1.0.0.M3``` is still in staging and not deployed yet.

**Comment by markpollack** [comment]
They are now in the milestone repo, had to manually promote for this release and missed those artifacts.  Try it now.

http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-starter-stream-rabbit/1.0.0.M3/

**Comment by sourabhhsharma** [comment]
Thanks for promoting to milestone repo.

I would also check and let you know if any question.

**Comment by ccit-spence** [comment]
@markpollack Great thanks,  Works perfectly.
