### ISSUE TITLE
Absence of metrics and traces in spring-cloud-stream-binder-kafka-reactive

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-stream#2650]
**Describe the issue**
Absence of metrics and traces in spring-cloud-stream-binder-kafka-reactive

**To Reproduce**
Create a simple spring cloud stream **reactive** kafka producer and consumer
Start producing and consuming messages.
Even with the actuator and micrometer configured, no Kafka related metrics observed.
https://github.com/reactor/reactor-kafka/pull/262
Ditto for traces

**version**
4.0.2-SNAPSHOT

**Expected behavior**
Similar to spring-cloud-stream-binder-kafka which supports both metrics and traces, kafka-**reactive** counterpart does not support any of the two.

Starting an issue here tracking this.

Thank you for the amazing work Spring Cloud Stream team for the reactive support.
Having metrics and traces for spring-cloud-stream-binder-kafka-reactive would allow it to be in production for companies which requires metrics and logs as part of production launch of a business flow based on this framework.

**Comment by kschlesselmann** [comment]
We are missing the offset lag metric too. Any workarounds available to get at least those basic metrics?

**Comment by sobychacko** [comment]
@kschlesselmann We will take a look at this and see how we can support metrics in the reactive binder.

**Comment by garyrussell** [comment]
reactor-kafka now supports adding Micrometer listeners to instrument the producers and consumers (since 1.3.17).

https://projectreactor.io/docs/kafka/release/reference/#_micrometer_metrics

https://github.com/reactor/reactor-kafka/pull/323

**Comment by patpatpat123** [comment]
Indeed, big thanks @garyrussell for the metrics support.
Amy ETA for the tracing support please?

**Comment by kschlesselmann** [comment]
@garyrussell I enabled reactor kafka metrics like
```kotlin
@Configuration(proxyBeanMethods = false)
class ReactorKafkaConfiguration {

    @Bean
    fun receiverOptionsCustomizer(meterRegistry: MeterRegistry): ReceiverOptionsCustomizer<Any, Any> =
        ReceiverOptionsCustomizer { _, receiverOptions ->
            receiverOptions.consumerListener(MicrometerConsumerListener(meterRegistry))
        }
}
```
and while it seems to work fine there are _a lot_ of metrics/tags now. Any way to reduce those metrics? I tried something like
```kotlin
@Bean
fun kafkaMetricsMeterFilter(): MeterFilter = object : MeterFilter {

    private val tagsToRemove = setOf(
        "client.id",
        "reactor-kafka.id",
        "kafka.version",
        "node.id",
    )

    override fun map(id: Meter.Id): Meter.Id = if (id.name.startsWith("kafka.")) {
        id.tags
            .filter { it.key !in tagsToRemove }
            .let { id.replaceTags(it) }
    } else {
        id
    }
}
```
but this doesn't seem to work. Any suggestions?

**Comment by garyrussell** [comment]
I would expect a filter to work; if you can't figure it out, I suggest you reach out to the Micrometer folks.

We don't support Micrometer internals here.

**Comment by garyrussell** [comment]
Probably the first place to start is debug the `MeterRegistryPostProcessor` bean in Boot's `MetricsAutoConfiguration` - it looks like it should apply all filter bean instances.

**Comment by patpatpat123** [comment]
Hello team,

Just checking on this issue.
As mentioned in the title, there are two elements missing in spring cloud stream binder kafka reactive.
The two items are:

1 - metrics
2 - traces

For item number 1, metrics, I believe this issue is now resolved with the help of this PR:
https://github.com/reactor/reactor-kafka/pull/323
I believe it has been properly integrated into spring cloud stream.

If not anything else, thank you for the help provided.
If it is confirmed metrics are now available, I am more than happy to rename the title (or someone else) in order to properly reflect the accuracy of the issue.

With that said, I believe that as of today, November 2023, traces are yet to be available in spring cloud stream.
Reator kafka just released GH-321 PR-325
Please correct me if I am wrong, but I do not believe that as of today, traces are integrated into spring cloud stream.
May I ask if I am correct?
And if yes, may I also ask for help to make this happen?

Thank you for your time.

**Comment by patpatpat123** [comment]
Hello team,

A year since I opened this issue, and a talk on SpringOne2024 (please see screenshot) where Observability is mentioned, I think the issue is still not yet resolved.
![Screenshot 2024-09-10 192658](https://github.com/user-attachments/assets/90ef7d22-8956-420e-b739-f55aae5370e1)

Using the latest 4.1, while metrics are there, there are still no traces for reactive.

Could you please help?

**Comment by sobychacko** [comment]
@patpatpat123 We will have an update on it soon. Stay tuned. Thanks for bringing this to our attention.

**Comment by sobychacko** [comment]
@patpatpat123 We added some changes to address this issue on the `4.2.0-SNAPSHOT` version. Could you take it for a spin and let us know what you think? If you still have issues, we can iteratively improve this feature. Thanks!
