### ISSUE TITLE
NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.stream.function.StreamBridge' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

### ISSUE THREAD

**Issue by originyy** [spring-cloud/spring-cloud-stream#2652]
version：4.0.1

NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.stream.function.StreamBridge' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Comment by olegz** [comment]
It doesn't appear to be an issue as no problem has been described. . . just some random stack trace fragment without any context

**Comment by atilla8huno** [comment]
@originyy have you found the solution for your problem?
