### ISSUE TITLE
AOT support for multiple binders

### ISSUE THREAD

**Issue by kartik-kaushik** [spring-cloud/spring-cloud-stream#2655]
I am trying to run a springboot3 native app with spring-cloud-stream-binder-rabbit dependency. Our application has multiple binders (e.g. usersevent, emailevent). 
The normal application is working fine as expected but in native or aot-mode I am facing following issue.
When I tried with spring boot 3.0.0 and 3.0.2. the application is always taking the binder name as rabbit and connecting to localhost and not connecting to the url or binders defined in my property file
When I tried with spring boot 3.0.3-SNAPSHOT. The build failed with error

Pre-creating binder child context (AOT) for rabbit
Exception in thread "main" java.lang.IllegalArgumentException: Code generation is not supported for bean definitions declaring an instance supplier callback : Root bean: class [org.springframework.integration.config.MessagingAnnotationPostProcessor]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.<init>(BeanDefinitionMethodGenerator.java:82)

Can someone please help in this regards.
Thanks

**Comment by magnus-larsson** [comment]
I think this problem also applies when only one binder is used.
To reproduce the error with 3.0.3-SNAPSHOT:

```
git clone https://github.com/spring-projects/spring-aot-smoke-tests.git
cd spring-aot-smoke-tests
./gradlew :cloud:cloud-stream-kafka:build
./gradlew :cloud:cloud-stream-rabbit:build
```

Both build commands will fail with the above error.

Changing to 3.0.3 in `gradle.properties` does not help.

Build status of spring-aot-smoke-tests can be monitored here: https://github.com/spring-projects/spring-aot-smoke-tests/blob/main/STATUS.adoc#cloud

**Comment by olegz** [comment]
@onobc referring to you as an AOT expert in streams. . . can you please take a look at that

**Comment by onobc** [comment]
- Failures started 2023-02-15
- Quick peek at calendar.spring.io reveals SF6.0.5 released that day
- Quick scan of its release notes (search "AOT") reveals https://github.com/spring-projects/spring-framework/issues/29556

Digging...

**Comment by onobc** [comment]
#### Some facts
- In the AOT world - bean definitions that use instance suppliers are no longer allowed
- In the pre-AOT world - bean definitions that use instance suppliers can give a performance improvement by avoiding the reflection otherwise necessary to construct the instance for the bean/definition.
- Spring Integration makes **heavy** use of the 2nd point above.
- The same failures can be seen in https://ci.spring.io/teams/spring-aot-smoke-tests/pipelines/spring-aot-smoke-tests-1.0.x/jobs/integration-app-test 

#### The fix...
- is to remove the instance suppliers from SI. 
- is in progress and should be in for a PR in the next 24hrs.
- will be officially available in the [6.1.0-M2](https://github.com/spring-projects/spring-integration/milestone/292) release on 2023-03-22
- will be available in a snapshot in the next 24-48hrs

**Comment by artembilan** [comment]
... and Spring Integration [6.0.4](https://github.com/spring-projects/spring-integration/milestone/293) same date.

**Comment by patpatpat123** [comment]
adding myself here

**Comment by magnus-larsson** [comment]
It seems like the problem is resolved now, using Spring Boot 3.0.5-SNAPSHOT. Both https://github.com/spring-projects/spring-aot-smoke-tests/blob/main/STATUS.adoc#cloud and https://ci.spring.io/teams/spring-aot-smoke-tests/pipelines/spring-aot-smoke-tests-1.0.x/jobs/integration-app-test are green now!

**Comment by kartik-kaushik** [comment]
Using versions as below:
springboot:3.0.5-SNAPSHOT
cloud:2022.0.1
java:17
spring-cloud-stream-binder-rabbit:4.0.1
spring-cloud-stream:4.0.1

**Main Class:**
@SpringBootApplication
public class SpringStreamApplication {   public static void main(String[] args) {
    SpringApplication.run(SpringStreamApplication.class, args);
  }   @Bean
  public Function<String, String> service() {
    return v -> v;
  } }
  
**application.yaml**
server:
  port: 8090
management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: "*"
spring:
  cloud:
    stream:
      rabbit:
        bindings:
          emailevent:
            producer:
              routingKeyExpression: events.in
              exchangeType: direct
              use-confirm-header: true
          audit:
            producer:
              exchangeType: fanout
              use-confirm-header: true
      default-binder: emaileventrmq
      binders:
        userrmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: vents
                host: dev.com
                port: 5672
                username: user
                password: pass
                ssl:
                  enabled: false
                publisher-confirms: true
                publisher-returns: true
                publisher-confirm-type: correlated
                template:
                  retry:
                    max-attempts: 4
                    maxInterval: 600000
                    initialInterval: 120000
        emaileventrmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                virtual-host: sdp
                host: dev.com
                port: 5672
                username: user
                password: pass
                ssl:
                  enabled: false
                publisher-confirms: true
                publisher-returns: true
                publisher-confirm-type: correlated
                template:
                  retry:
                    max-attempts: 4
                    maxInterval: 600000
                    initialInterval: 120000
      bindings:
        audit:
          producer:
            error-channel-enabled: true
          binder: userrmq
          destination: e.user.events
        emailevent:
          binder: emaileventrmq
          destination: e.events
          
          
We are still getting the binder name as default rabbit and not the one provided in the application.yml file. The same is working fine as non-native but still natively the issue persists. Please highlight if we are missing something.
Thanks!

**Comment by kartik-kaushik** [comment]
@onobc any update on the above?

**Comment by onobc** [comment]
@kartik-kaushik I have not had a chance to look at this since your report. I will try to get to it today though.

**Comment by onobc** [comment]
@kartik-kaushik do. you mind bumping up to the following and trying again:

- springboot: `3.0.5`
- cloud: `2022.0.2`
- spring-cloud-stream-binder-rabbit: `4.0.2`
- spring-cloud-stream: `4.0.2`

A few questions as well:

- Are you using [buildpacks or GraalVM build tools](https://docs.spring.io/spring-boot/docs/3.0.5/reference/htmlsingle/#native-image.developing-your-first-application) to build the native image? 
- If build tools, what version of GraalVM are you using? 
- Are you using Gradle or Maven? If you can give me the steps you are using to build that may be helpful. 

Thanks

**Comment by kartik-kaushik** [comment]
@onobc it didn't worked with the above as well.
Below are the response for your need:

Are you using buildpacks or GraalVM build tools to build the native image?
-> GraalVM build tools 

If build tools, what version of GraalVM are you using?
-> graalvm-ce-java17-22.3.0

Are you using Gradle or Maven? If you can give me the steps you are using to build that may be helpful.
-> Maven. 
Building native image using command  
mvn -Pnative native:compile

**Comment by onobc** [comment]
I have reproduced the issue locally (using Kafka and multiple binders). I will now try to figure out the cause @kartik-kaushik . I should have some info by the end of the weekend.

**Comment by onobc** [comment]
PR submitted - here is the **cause** summarized:

The underlying cause of this issue was two-fold.

1. At AOT-build time: The generated binder child contexts were not taking the user-declared binder configs into consideration: https://github.com/spring-cloud/spring-cloud-stream/pull/2689#discussion_r1156309185

2. At AOT/native run time: The initialized child contexts were not taking the user-declared binder configs into consideration: https://github.com/spring-cloud/spring-cloud-stream/pull/2689#discussion_r1156320394
