### ISSUE TITLE
It is not possible to pause/resume correctly a binding with multiple destinations by actuator endpoint

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream#2658]
**Describe the issue**
When setting up a binding with multiple destinations as shown below:
```
spring:
  cloud:
    function:
      definition: foo
    stream:
      bindings:
        foo-in-0:
          group: my-group
          destination: topic1,topic2,topic3
```
Spring Cloud Stream creates a binding with the same name for each destination correctly.

The problem is that through the actuator endpoint, when making a POST request to stop/resume the binding in question, only the first binding it encounters, does so as indicated in the following [line ](https://github.com/spring-cloud/spring-cloud-stream/blob/af2df8ba0eff2e81c3a8fce358a09a54abb3a974/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BindingsLifecycleController.java#L181) of the `BindingsLifecycleController.java` class, is paused/resumed.

**To Reproduce**
1. Start the attached demo application ([demoscskafka.zip](https://github.com/spring-cloud/spring-cloud-stream/files/10824773/demoscskafka.zip))
2. Access the endpoint http://localhost:8080/demo-scs-kafka/actuator/bindings and check that there are three bindings with `status: running`.
3. Execute the `foo-in-0` binding pause: `curl --location 'http://localhost:8080/demo-scs-kafka/actuator/bindings/foo-in-0' --header 'Content-Type: application/json' --data '{"state": "PAUSED"}'`
4. Access the endpoint http://localhost:8080/demo-scs-kafka/actuator/bindings and check that only the first binding has the `status: paused`.

**Version of the framework**
Spring Boot 3.0.2
Spring Cloud 2022.0.1

**Expected behavior**
All bindings are paused/resumed.

**Comment by ferblaca** [comment]
If you see that this is a behaviour that needs to be corrected, I could contribute to it.

**Comment by sobychacko** [comment]
@ferblaca Looks like that is a bug. Feel free to send us a patch PR to fix this.

**Comment by ferblaca** [comment]
@sobychacko This fix will be backported to Spring Cloud Stream line 3.2.x?
