### ISSUE TITLE
Support pub/sub only semantics for Redis binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#266]
As a developer, I'd like to support only `pub/sub` semantics for `redis` binder.

*Acceptance:*
`queue` semantics are not supported
`pub/sub` specs are supported and documented with samples

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/commit/c3758b9dc0d0ccebbf162a7f75affb84a1b08ff0
