### ISSUE TITLE
Kafka ProducerListener does not work with custom spring cloud stream binders

### ISSUE THREAD

**Issue by KarthikRIyer** [spring-cloud/spring-cloud-stream#2665]
**Describe the issue**
I have a springboot app using spring cloud stream kafka binders. 
There's a custom implementation of ProducerListener, and the callbacks work with the default kafka binder.
As soon as I create a custom binder, I do not get any callbacks.

**To Reproduce**
1. Create a springboot app with `spring-cloud-stream-binder-kafka`
2. Use the following properties:
```properties
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.bindings.testInput.destination=test-topic
spring.cloud.stream.bindings.testInput.group=test-group
spring.cloud.stream.bindings.testOutput.destination=test-topic
spring.cloud.stream.kafka.binder.auto-create-topics=true

spring.cloud.stream.default-binder=secondaryKafka
spring.cloud.stream.binders.secondaryKafka.type=kafka
spring.cloud.stream.binders.secondaryKafka.environment.spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.binders.secondaryKafka.environment.spring.cloud.stream.kafka.binder.auto-create-topics=true
```
3. Define a custom implementation for `ProducerListener`
```java
@Component
public class KafkaProducerListener implements ProducerListener {

    private static final Logger logger = LoggerFactory.getLogger(KafkaProducerListener.class);

    private static final StringDeserializer stringDeserializer = new StringDeserializer();

    @Override
    public void onSuccess(ProducerRecord record, RecordMetadata metadata) {
        logger.info("onSuccess: {}", stringDeserializer.deserialize(record.topic(), (byte[]) record.value()));
    }

    @Override
    public void onError(ProducerRecord record, RecordMetadata metadata, Exception e) {
        logger.info("onError: {}", stringDeserializer.deserialize(record.topic(), (byte[]) record.value()));
    }

}
```
4. Publish a Kafka message.
5. You won't see the `onSuccess: ` log
6. Now, instead use the below properties file:
```properties
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.bindings.testInput.destination=test-topic
spring.cloud.stream.bindings.testInput.group=test-group
spring.cloud.stream.bindings.testOutput.destination=test-topic
spring.cloud.stream.kafka.binder.auto-create-topics=true

spring.cloud.stream.default-binder=kafka
```
7. Publish a Kafka message
8. You will see the `onSuccess: ` log

**Version of the framework**
```xml
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.13</version>
		<relativePath/> <!-- lookup parent from repository -->
</parent>
<properties>
		<java.version>8</java.version>
		<spring-cloud.version>2020.0.5</spring-cloud.version>
		<spring-framework.version>5.3.23</spring-framework.version>
</properties>
<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
</dependencies>
```

**Expected behavior**
The `ProducerListener` callbacks work for both the default binder, and the custom binder.

**Screenshots**
With the default binder:
![image](https://user-images.githubusercontent.com/35020024/222737337-4485b0a2-2bbc-423d-9608-2d793d9c0328.png)

With the custom binder:
![image](https://user-images.githubusercontent.com/35020024/222737522-37e8caa2-0224-444f-a028-fdaa43934ebb.png)

**Additional context**
Here's the sample application I'm using: [https://github.com/KarthikRIyer/spring-cloud-stream-test](https://github.com/KarthikRIyer/spring-cloud-stream-test)

**Comment by garyrussell** [comment]
When using multiple (or any named) binders, you need to use a binder customizer instead of just declaring the listener bean.

https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#binder-customizer

**Comment by KarthikRIyer** [comment]
This works! Thank you.

**Comment by KarthikRIyer** [comment]
Is there a way to customize binders with Spring Cloud version Hoxton.SR12?
Hoxton.SR12 uses spring-cloud-stram:3.0.13.RELEASE which does not have BinderCustomizer.
