### ISSUE TITLE
Binding with BiConsumer creates producer-binding

### ISSUE THREAD

**Issue by LeovR** [spring-cloud/spring-cloud-stream#2670]
**Describe the issue**
We are using the `BiConsumer` in our application to be able to handle `KafkaNull` while also getting the headers as a map.
When doing so Spring Cloud Function wraps the `BiConsumer` inside a wrapper `Function`.

But this results in Spring Cloud Stream trying to create a producer binding for a binding which is only meant for input.

Our Kafka is configured with `auto.create.topics.enable=false` and we configured the Kafka-binder with `auto-create-topics=false`.
This results in errors since thie Topic `Binding-out-0` is not a known topic.

**To Reproduce**
* Configure Kafka with `auto.create.topics.enable=false`
* Use [demo-repository](https://github.com/LeovR/spring-cloud-stream-biconsumer)
* Log outputs:

```
KafkaTopicProvisioner      : Using kafka topic for outbound: messageConsumer-out-0
...
org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Error while fetching metadata with correlation id 1 : {messageConsumer-out-0=UNKNOWN_TOPIC_OR_PARTITION}
```

**Workaround**
Our current workaround is to use `auto-create-topics=true`.

**Version of the framework**
Spring Cloud Stream 4.0.1

**Expected behavior**
No producer binding / topic `...-out-0` is created or required.

**Comment by sobychacko** [comment]
@LeovR Thanks for reporting this issue. It is now addressed in Spring Cloud Function and Stream (see the commits above). The fix should be available on `4.0.2-SNAPSHOT` on SCFn and SCSt.
