### ISSUE TITLE
SCSKafka + Actuator + enable-observation creates a 2nd AdminClientConfig which doesn't copy config across

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-stream#2673]
Hi, 

I have an issue when deploying to our test environment where SCSKafka with  enable-observation=true starts a second AdminClientConfig but doesn't copy over the configuration security.protocol and therefore I get SSL errors (strangely the bootstrap server is copied OK!!)

https://github.com/davidmelia/spring-cloud-function-zipkin/blob/observation_bug2/src/test/java/example/SendKafkaMessageTest.java is a super simple test and I illustrate the issue by using the property _retry.backoff.ms_ which is not consistent:

```
@TestPropertySource(properties = {
....
    ,"spring.cloud.stream.kafka.binder.configuration.retry.backoff.ms=200"
....
})
public class SendKafkaMessageTest {
```

When you run SendKafkaMessageTest, In theory  you should see AdminClientConfig, ProducerConfig and the second AdminClientConfig boot up with retry.backoff.ms = 200 but in fact the second AdminClientConfig is the default retry.backoff.ms = 100 which is incorrect:

```

2023-03-16T19:57:24.791Z  INFO 31069 --- [           main] o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values: 
....	
	retry.backoff.ms = 200
....

2023-03-16T19:57:25.004Z  INFO 31069 --- [           main] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
...
	retry.backoff.ms = 200
....

2023-03-16T19:57:25.052Z  INFO 31069 --- [           main] o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values: 
....
	retry.backoff.ms = 100
....
```
^^ 100 is wrong

N.B I think this might be the root cause to https://github.com/spring-cloud/spring-cloud-stream/issues/2651  and also linked to my previous issue https://github.com/spring-cloud/spring-cloud-stream/issues/2616

**Comment by davidmelia** [comment]
I think it's something to do with this bit of code

<img width="805" alt="image" src="https://user-images.githubusercontent.com/8583712/225744987-80a5625a-659b-445c-83c7-57c3bffb7be8.png">

**Comment by garyrussell** [comment]
Yes, it's related to this https://github.com/spring-cloud/spring-cloud-stream/issues/2576#issuecomment-1348666138

We fixed the `KafkaTemplate` (and listener container) to use the correct brokers, but the template doesn't know anything about the binder's configuration.

https://github.com/spring-projects/spring-kafka/issues/2505

It now propagates the correct servers, but it doesn't copy over the SSL configs (because it doesn't know about them).

The work around is to configure the SSL globally for all Kafka (via the `spring.kafka` namespace).

The properties are merged in order global -> binder -> binding.

We probably need to change spring-kafka to allow the binder to inject its own admin config.

**Comment by patpatpat123** [comment]
encountering the same issue

**Comment by davidmelia** [comment]
Thanks @garyrussell  - adding the below solved the issue

```
spring:
  kafka:
    admin:
      security:
        protocol: SSL 
```

**Comment by garyrussell** [comment]
The `spring-kafka` releases containing the fix should go out today so we will be able to change the binder to inject its own admin.

**Comment by patpatpat123** [comment]
Hello there. I am currently using Spring Cloud Stream 4.0.3 snapshot + Reactor Kafka 1.3.17, and still observing this issue. Am I missing something, please?

**Comment by patpatpat123** [comment]
Hello there. I am currently using Spring Cloud Stream 4.0.3 snapshot + Reactor Kafka 1.3.17, and still observing this issue. Am I missing something, please?

**Comment by garyrussell** [comment]
>Am I missing something

It's not implemented yet; should have a PR today...
