### ISSUE TITLE
Spring Cloud Stream 4.0.3-SNAPSHOT still using Reactor Kafka 1.3.16 -> [Enhancement Request] to use Reactor kafka 1.3.17 (which is released)

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-stream#2678]
Hello Team,

I would like to raise an enhancement request if you allow me.

Currently, as of this writing, the most recent snapshot version of spring cloud stream is 4.0.3-SNAPSHOT.
Looking at its dependencies, it uses Reactor Kafka 1.3.16.
https://github.com/spring-cloud/spring-cloud-stream/blob/main/binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/pom.xml#L51

As per official Reactor Kafka releases, the latest released version of Reactor Kafka is 1.3.17. It is already there.
May I ask if it is possible to enhance Spring Cloud Stream by making a PR here, bumping https://github.com/spring-cloud/spring-cloud-stream/blob/main/binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/pom.xml#L51 from 1.3.16 to 1.3.17 please?

Justification: 1.3.17 of Reactor Kafka contains a very requested feature (micrometer integration). 
It will be great to allow developers to test the snapshot of 4.0.3 with Reactor 1.3.17 (without having to manually overriding things here and there)

If you believe this enhancement does not make sense, please feel free to close it (but would be great to have an ETA on when Spring Cloud Stream with Reactor Kafka 1.3.17 will be available)

Thank you

**Comment by sobychacko** [comment]
@patpatpat123 Updated to `1.3.17`.

**Comment by patpatpat123** [comment]
Many thanks @sobychacko, much appreciated
