### ISSUE TITLE
Spring-Cloud application not connecting to Kafka during IT

### ISSUE THREAD

**Issue by ivangfr** [spring-cloud/spring-cloud-stream#2684]
Hi, I have this application [`spring-cloud-stream-event-sourcing-testcontainers`](https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers) that I've recently upgraded to **spring-boot 3.0.x** and **spring-cloud 2022.0.x**. However, since then, the integration tests started to fail.

In short, it's a `producer-consumer` application. `user-service` pushes events to `Kafka` topic and `event-service` consumes them.

I am using `Testcontainers` to spin up do Docker containers during the integration tests.

For instance, when using **spring-boot 2.7.6** and **spring-cloud 2021.0.5**, the integration tests work, [this commit](https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers/commit/6e210f6f9595e0620ff684f81315bc79d7b91b6f). However, after migrating to **spring-boot 3.0.1** and **spring-cloud 2022.0.0**, [this commit](https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers/commit/62364eac7bea8f17d5c8d714f29bab7e7a08dad6), the integration tests started to fail. It looks like during the tests, the app is not connecting to Kafka, even providing correctly the Kafka broker URL.

Here is t[he difference](https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers/commit/62364eac7bea8f17d5c8d714f29bab7e7a08dad6) between the 2 commits.

- Logs of the IT `testCreateUser` using **spring-boot 2.7.6** and **spring-cloud 2021.0.5**: [log-spring-boot-2.7.6.txt](https://github.com/spring-cloud/spring-cloud-stream/files/11129832/log-spring-boot-2.7.6.txt)
- Logs of the IT `testCreateUser` using **spring-boot 3.0.1** and **spring-cloud 2022.0.0**: [log-spring-boot-3.0.1.txt](https://github.com/spring-cloud/spring-cloud-stream/files/11129835/log-spring-boot-3.0.1.txt)

**To Reproduce**
- git clone https://github.com/ivangfr/spring-cloud-stream-event-sourcing-testcontainers.git
- cd spring-cloud-stream-event-sourcing-testcontainers
- Build `event-service` Docker image as it will be used during the IT
   ```
   ./mvnw clean compile jib:dockerBuild --projects event-service
   ```
- Git checkout to spring-boot version 2.7.6
  ```
   git checkout 6e210f6f9595e0620ff684f81315bc79d7b91b6f
   ```
- Run user-service Unit and Integration Tests
  ```
   ./mvnw clean verify --projects user-service -DargLine="-Dspring.profiles.active=test"
  ```
- Git checkout to spring-boot version 3.0.1
  ```
   git checkout 62364eac7bea8f17d5c8d714f29bab7e7a08dad6
   ```
- Run user-service Unit and Integration Tests
  ```
   ./mvnw clean verify --projects user-service -DargLine="-Dspring.profiles.active=test"
  ```

**Comment by garyrussell** [comment]
For team info: 

This is where the log diverts...

```
2023-04-01 10:36:40.984  INFO [user-service,,] 584 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2023-04-01 10:36:41.350  INFO [user-service,,] 584 --- [           main] o.s.c.s.b.k.p.KafkaTopicProvisioner      : Using kafka topic for outbound: com.ivanfranchin.userservice.user
2023-04-01 10:36:41.354  INFO [user-service,,] 584 --- [           main] o.a.k.clients.admin.AdminClientConfig    : AdminClientConfig values: 
	bootstrap.servers = [PLAINTEXT://localhost:59637]
...
```
and

```
2023-04-01T10:53:58.241+02:00  INFO [user-service,,] 1796 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2023-04-01T10:53:58.242+02:00  INFO [user-service,,] 1796 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Creating binder: integration
2023-04-01T10:53:58.242+02:00  INFO [user-service,,] 1796 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Constructing binder child context for integration
2023-04-01T10:53:58.307+02:00  INFO [user-service,,] 1796 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Caching the binder: integration
...
```

Looks like the binding is not created for some reason (even lazily). 

I also noticed that `s.c.s.source` (used in the app) is deprecated, but the deprecation message makes no mention of any replacement to early bind `StreamBridge` output bindings.

cc/ @olegz @sobychacko 

@ivangfr From your README: `>Differently from before, the traceId does not propagate ...`

Boot 3 switched to Micrometer Observation, `spring-kafka` disables it by default, to avoid the overhead for those that don't want it; to enable trace propagation, you need to set the `enable-observation` binder property.

**Comment by sobychacko** [comment]
@ivangfr Did that change to `output-bindings` make any difference? I would think that even though `spring.cloud.stream.source` is deprecated, it may have still worked in that version. If things are still not working, could you create a simple project with only minimum components - a simple application connecting to Kafka? Please eliminate all other components like schema registry, database, etc. That way, we can pinpoint where the issue occurs. In all likelihood, this definitely looks like a regression, and we need to fix it. I have a simple app that works with both properties, so I want to see where it falls off. Thanks!

**Comment by ivangfr** [comment]
Hi @sobychacko the change to `output-bindings` didn't fix the issue (I had in mind it, it was just to update the code).

Ok, I will create a simple project and try to reproduce it. As soon as I have it, I will share. Thanks!

**Comment by ivangfr** [comment]
Hi @sobychacko here is a simple project to reproduce the issue.

- [springboot-kafka-testcontainers-2.7.10.zip](https://github.com/spring-cloud/spring-cloud-stream/files/11171231/springboot-kafka-testcontainers-2.7.10.zip)
- [springboot-kafka-testcontainers-3.0.5.zip](https://github.com/spring-cloud/spring-cloud-stream/files/11171233/springboot-kafka-testcontainers-3.0.5.zip)

The code is the same. The only difference is the spring-boot and spring-cloud versions. spring-boot version is set to the filenames.

In order to run, just unzip the files and, inside the folder of each one, run
```
./mvnw clean verify
```

When using the Spring-Boot version `3.0.5` it does not connect to Kafka. On the other hand, for the version 2.7.10, it connects. You can see in the logs.

**Comment by sobychacko** [comment]
@ivangfr Thanks for these small samples. Here is the problem you are running into. In your app that is based on Boot `2.7.x`, you do not have the `spring-cloud-stream-test-binder` dependency. Without this, your tests connect to Kafka normally. You have the test-binder dependency in your app, which is based on Boot `3.0.x`. When that is present, and you run a test, this binder takes precedence, which is an in-memory Spring Integration-based channel binder. This is the reason why you are not connecting to the Kafka cluster. Could you try removing the dependency and rerunning the test? I was able to connect to the Kafka broker when I did that. With that said, this is a problem we need to fix on the framework side since it is not obvious why or how the test binder can obscure things.

**Comment by ivangfr** [comment]
Yes, exactly @sobychacko If I remove the dependency `spring-cloud-stream-test-binder` from the `spring-boot 3.0.x`, the test case connects to the Kafka cluster.
