### ISSUE TITLE
Make SenderOptions/ReceiverOptions customizer generic

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-stream#2685]
Try to add this. We get compile time error as it is not generic and it expects **_SenderOptions<Object, Object>_**. 

```
    @Bean
    public SenderOptionsCustomizer customizer(){
        return (a, b) -> b.withKeySerializer(new StringSerializer());
    }
```
even this will not fix.

```
    @Bean
    public SenderOptionsCustomizer customizer(){
        return (a, b) -> b.withKeySerializer(((Serializer<Object>) new StringSerializer()));
    }

```

**Comment by garyrussell** [comment]
@kitkars We've changed the interfaces but please note that the serializers/deserializers can also be set in the `application.properties/yml` (boot, binder and/or binding configuration in that order).
