### ISSUE TITLE
receiveAutoAck - acknowledges the message before application processes

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-stream#2686]
Hi,

This implementation does NOT seem to be correct. We **_ack_** the messages even before application processes.

https://github.com/spring-cloud/spring-cloud-stream/pull/2656/commits/cbbf43dd2ebb7c5468ea75aea3b75ad0d421d2ef#diff-3b3c32debcdf3645030012136ddc729fe40c5e70f057f96299c98f9c870389dcR215

Because the **_concatMap_** converts `Flux<Flux<T>>` to `Flux<T>`. The **_reactive-kafka_** assumes the inner flux will be processed by the application. So it makes sense to add the acknowledgement as part of **_doAfterTerminate_** [here](https://github.com/reactor/reactor-kafka/blob/8f23e7773b986ed2a3ac08f9b412fbfc47b172d4/src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java#L77).  

But in the Spring-cloud-stream project, the library does the **_concatMap_** itself. So, when the inner flux is flattened, we ack the message and then pass the messages to the application. This behavior becomes like **_atMostOnce_**.  This is wrong.  This issue is NOT present in reactive-kafka. It is introduced as part of spring cloud sream kafka reactive binder.

Ideally if the application enables reactiveAutoCommit, our bean should be like this.

```
@Bean
public Consumer<Flux<Flux<T>>> consumer(){
 ....
}
```

**Comment by kitkars** [comment]
@garyrussell, Not sure if I have confused you. The problem is in the acknowledgement which happens before processing.
 
Lets use your same example. 

- simulate the processing delay as shown here. 
- Once the consumer is also connected to the kafka cluster, stop the application. (that is we stop even before we see a value getting printed)
- Now check the kafka consumer group's LAG. it will be 0. because we already acknowledged. 

```
	@Bean
	public Consumer<Flux<String>> input() {
		return flux -> flux
				.log()
				.delayElements(Duration.ofSeconds(60)) // processing takes time.. so simulate that
				.doOnNext(val -> System.out.println(val))
				.subscribe();
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<byte[], byte[]> template) {
		return args -> {
			template.send("input-in-0", "foo".getBytes());
			template.send("input-in-0", "bar".getBytes());
			template.send("input-in-0", "baz".getBytes());
			template.send("input-in-0", "qux".getBytes());
			System.out.println("********** produced. stop the application once the consumer is connected to the kafka broker.************");
		};
	}
```

**Comment by kitkars** [comment]
You can try this same behavior with reactor-kafka. This issue will not happen there.

**Comment by garyrussell** [comment]
I was not "confused"; you said

>we ack the message and then pass the messages to the application

Whereas that is not the case, the acks are performed when the inner flux terminates, which normally happens when the application finishes processing it (as I stated). However, it also terminates when the application is stopped, possibly before the app has processed all the records from that batch.

If I stop my app above (with max.poll.records=2) while processing the first record, both the records from the first flux are ack'd.

Can you show how you consume the `Flux<Flux>` with the native code so I can see what happens there?

**Comment by kitkars** [comment]
" the acks are performed when the inner flux terminates" - This is exactly what I am saying. 
The innerflux is terminated first [here](https://github.com/spring-cloud/spring-cloud-stream/commit/cbbf43dd2ebb7c5468ea75aea3b75ad0d421d2ef#diff-3b3c32debcdf3645030012136ddc729fe40c5e70f057f96299c98f9c870389dcR215) and the applicaiton receives the message. Hence acknowledging first before processing.  receiveAutoAck is NOT same as atMostOnce.

**Comment by kitkars** [comment]
`However, it also terminates when the application is stopped, possibly before the app has processed all the records from that batch.`. This statement is wrong. Take a look at this example. **_doAfterTerminate_** will execute only after all the items are emitted.

```
		var innerFlux= Flux.just(1, 2, 3)
			.delayElements(Duration.ofSeconds(1))
			.doAfterTerminate(() -> System.out.println("Terminating"));


		var outerFlux = Flux.just(innerFlux);


		// here it will NOT print "Terminating"
		outerFlux
				.concatMap(Function.identity())
				.take(2)
				.doOnNext(System.out::println)
				.subscribe();


		Thread.sleep(4_000);
		// here it will print "Terminating" because the inner flux terminates
		outerFlux
				.concatMap(Function.identity())
				.doOnNext(System.out::println)
				.subscribe();


		Thread.sleep(4_000);
```

**Comment by garyrussell** [comment]
Sorry; you are correct. I was thrown by the debugger.

When I added logging to the commits, I see they are committed first.

**Comment by garyrussell** [comment]
>You can try this same steps with reactor-kafka (w/o spring-cloud-stream). This issue will not happen there.

I would still like to know how you process without concatenating in that case (so I can write a test).

**Comment by garyrussell** [comment]
```java
@Bean
public Consumer<Flux<Flux<T>>> consumer(){
 ....
}
```

I will have to consult with the team, but I don't think that will be possible, given the constraints of the framework.

In the meantime, I suggest you don't use autoCommit.

**Comment by garyrussell** [comment]
With some supporting changes in `reactor-kafka`, I was able to get this working...

```java
@SpringBootApplication
public class Scstgh2686Application {

	private static final Logger log = LoggerFactory.getLogger(Scstgh2686Application.class);

	public static void main(String[] args) {
		SpringApplication.run(Scstgh2686Application.class, args); //.close();
	}

	@Bean
	Consumer<Flux<Flux<ConsumerRecord<?, ?>>>> input() {
		return flux -> flux
				.doOnNext(inner -> inner
					.doOnNext(val -> {
						log.info(val.value().toString());
					})
					.subscribe())
				.subscribe();
	}

	@Bean
	ApplicationRunner runner(KafkaTemplate<byte[], byte[]> template) {
		return args -> {
			template.send("input-in-0", "foo".getBytes());
			template.send("input-in-0", "bar".getBytes());
			template.send("input-in-0", "baz".getBytes());
			template.send("input-in-0", "qux".getBytes());
			Thread.sleep(5000);
		};
	}

}
```
```
foo
bar
Committing: 80
Committing: 81
baz
qux
Committing: 82
Committing: 83
```

(With no commits if app stopped while processing).

The tricky part (and not supported) is applying the conversion service to the contents of the inner `Flux`; that may never be supported, but I'll leave that to wiser minds.

In the meantime, it can be mitigated by using native decoding (in this case I configured a `StringDeserializer`.

If this solution works for you, I'll prepare PRs.

**Comment by kitkars** [comment]
This is exactly what I was expecting. Great!!

```
@Bean
	Consumer<Flux<Flux<ConsumerRecord<?, ?>>>> input() {
		return flux -> flux
				.doOnNext(inner -> inner
					.doOnNext(val -> {
						log.info(val.value().toString());
					})
					.subscribe())
				.subscribe();
	}

```

**Comment by yangwudong** [comment]
> This is exactly what I was expecting. Great!! Ideally, the users want **_receiveAutoAck_**, so then users should do the **_concatMap_**
> 
> ```
> @Bean
> 	Consumer<Flux<Flux<ConsumerRecord<?, ?>>>> input() {
> 		return flux -> flux
> 				.doOnNext(inner -> inner
> 					.doOnNext(val -> {
> 						log.info(val.value().toString());
> 					})
> 					.subscribe())
> 				.subscribe();
> 	}
> ```

Hi @kitkars @garyrussell 

I am a beginner of Reactive and please feel free to correct me if I am wrong.

I have some questions about this changing:

1. After the changes for receiveAutoAck, the auto ack mode can only use Consumer<Flux<Flux<ConsumerRecord<?, ?>>>>, Function<Flux<XXX>, Flux<YYY>> is not supported anymore?

2. Inside of this consumer, if I need to consume a topic and make some changes, then publish to another topic, it requires to use StreamBridge to produce manually?

3. Even using Consumer<Flux<Flux<ConsumerRecord<?, ?>>>> pattern, if I perform a concatMap/flatMap/flatMapSequential, the acknowledge could still be executed after all ConsumerRecords in Flux published to new Flux/Mono when using concatMap/flatMap, but not the new stream terminated, because Flux<ConsumerRecord<?, ?> is terminated by concatMap/flatMap, is it a "trap" for the framework user if they use concatMap/flatMap?

4. Without the pattern - Function<Flux<XXX>, Flux<YYY>> and to use the auto ack mode, I can't find the advantages to use Spring Cloud Stream Reactive. Is using Spring Cloud Kafka Reactive to build a consumer much clearly?

Please forgive me if my questions are offensive. Thanks

**Comment by garyrussell** [comment]
1. Correct
2. Yes, or you can use a `Function<Flux<...>>. Flux<Flux<ConsumerRecord<?, ?>>>>`
3. Right, you must not concatenate the fluxes
4. ?
5. See 2

**Comment by garyrussell** [comment]
1. Correct
2. Yes, or you can use a `Flux<Flux<ConsumerRecord<?, ?>>>, Function<Flux<...>>>`
3. Right, you must not concatenate the fluxes
4. ?
5. Use `Function<ReceiverRecord<Flux<byte[], byte[]>, Flux<String>>` (with the default deserializers) or `Function<ReceiverRecord<Flux<byte[], byte[]>, Flux<String>>` with `StringDeserializers`.

**Comment by yangwudong** [comment]
> 1. Correct
> 2. Yes, or you can use a `Flux<Flux<ConsumerRecord<?, ?>>>, Function<Flux<...>>>`
> 3. Right, you must not concatenate the fluxes
> 4. ?
> 5. Use `Function<ReceiverRecord<Flux<String, String>, Flux<String>>` (with the default deserializers) or `Function<ReceiverRecord<Flux<byte[], byte[]>, Flux<String>>` with `StringDeserializers`.

Get it, thanks for your clarification.
