### ISSUE TITLE
BindingServiceProperties.getBindingDestination(String bindingName) not returning topic name

### ISSUE THREAD

**Issue by devcharlie** [spring-cloud/spring-cloud-stream#2699]
BindingServiceProperties.getBindingDestination(String bindingName) is expected to return the topic name which is bound with the bindingName veriable. However it returns the binding name not the topic name

**Comment by sobychacko** [comment]
@devcharlie I see it is working as expected and returns the destination name (aka the topic). Could you elaborate on where you see the issue and under what circumstances?

**Comment by devcharlie** [comment]
If a period is used in the binding name, the BindingServiceProperties assumes this to be the topic name. With the config below the destination returned by `bindingServiceProperties.getBindingDestination(bindingName)` will be "my.binding.topic-out" instead of "dev.integration.topic". It appears to be the periods in the binding name that cause this as hyphens work fine.
`spring:
  cloud:
    stream:
      bindings:
        my.binding.topic-out:
          destination: dev.integration.topic
`

**Comment by sobychacko** [comment]
@devcharlie You need to use brackets around the binding key and put them in quotes. In your case, this becomes `"[my.binding.topic-out]"`. See the relevant boot docs for the matter - https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding.maps

**Comment by devcharlie** [comment]
Great, thanks
