### ISSUE TITLE
Adding headers to a dlq kafka message

### ISSUE THREAD

**Issue by DLPaolo** [spring-cloud/spring-cloud-stream#2700]
I hope someone can help me.
Problem:
A consumer goes wrong, the message destined for dlq must have customized headers.

```
        @Bean
	public Consumer<Message<String>> test() {
				
		return (m) -> handleMessage(m);
	}

	private void handleMessage(Message<String> obj) {

		LOGGER.info("handleMessage <----------------------------->");
		
		throw new ArithmeticException();

	}
```
The consumer fails as expected, and on the error queue (DLQ) set via yaml I find the message.

To add more headers I tried to use this :
```

@Bean
	public DeadLetterPublishingRecoverer publisher(KafkaOperations<?, ?>  operations) {
	   		var v = new DeadLetterPublishingRecoverer(operations);
		
		v.setHeadersFunction( (c,e) ->{
						
			Headers add = new RecordHeaders()
				.add("test", "test".getBytes(StandardCharsets.UTF_8));
			
			return add;
		});
		
	    return v;
	}
```

Unfortunately it doesn't add me the new header.
In this experiment Headers doesn't depend on the captured error, but in real context I have to use the error to generate right header.

How can I do ?

Thanks in advance to anyone who will help me

**Comment by garyrussell** [comment]
Just adding a `DeadLetterPublishingRecoverer` will do nothing, you need to add a `ListenerContainerCustomizer` bean to set an appropriately configured `DefaultErrorHandler` (with the publisher as its recoverer). You should also disable DLQ configuration in the binding.

**Comment by sobychacko** [comment]
We also have some relevant information in the [tips and tricks](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_tips_tricks_and_recipes) section in the reference docs. 

Closing the issue. Feel free to re-open if you are still facing any issues.
