### ISSUE TITLE
Reactive Binder - RecordMessageConverter

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-stream#2701]
@garyrussell (I apologize for tagging. I felt we could fix this right away)

I am thinking we could make [this](https://github.com/spring-cloud/spring-cloud-stream/pull/2697/files#diff-3b3c32debcdf3645030012136ddc729fe40c5e70f057f96299c98f9c870389dcR230) better by doing the message conversion by using "map" (not **_flatMap_** / not **_concatMap_** which was the culprit in the original issue) with **_RecordMessageConverter_**.

This is a simple example which could demo the behavior.

- reactor kafka binder

```
Flux<Integer> innerFlux = Flux.just(1, 2, 3).delayElements(Duration.ofSeconds(1)).doAfterTerminate(() -> System.out.println("acknowledging the message"));

// we convert the message to the appropriate type RecordMessageConverter
Flux<Flux<String>> outerFlux = Flux.just(innerFlux).map(f -> f.map(v -> v + "-msg-converted"));
```

- application receives converted message and messages are automatically acknowledged after processing

```
outerFlux
    .concatMap(f -> f.doOnNext(v -> System.out.println("Processing : " + v)))
    .subscribe();
```
-----

By using the above example, if we could re do the [below block](https://github.com/garyrussell/spring-cloud-stream/blob/4c84b685208771541a990421cc76e937f98d2724/binders/kafka-binder/spring-cloud-stream-binder-kafka-reactive/src/main/java/org/springframework/cloud/stream/binder/reactorkafka/ReactorKafkaBinder.java#L228-L230)

```
fluxes.add(kafkaReceiver
	.receiveAutoAck()
	.map(inner -> new GenericMessage<>(inner)));
```

like this, then the app can receive the actual expected type instead of consumer record. 
```
fluxes.add(kafkaReceiver
	 .receiveAutoAck()
	 .map(inner -> inner.map(this::toMessage));

private Message<Object> toMessage(Object record){
	return (Message<Object>) ((RecordMessageConverter) converter)
		.toMessage(record, null, null, null);
}
```

**Comment by garyrussell** [comment]
@kitkars That doesn't really make much sense because the consumer would then have to be 

`Consumer<Flux<Flux<Message<Foo>>>>`.

As I said in the docs, Spring cannot access the inner flux to perform signature mapping or applying the conversion service to the message payload, so `Consumer<Flux<Flux<Foo>>>` is not possible.

**Comment by kitkars** [comment]
It was my mistake. I cloned this repo and tried to do what I was saying then realized that it was not possible. :(
