### ISSUE TITLE
Provide the support to decode to abstract type when the header contains specific type info

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-stream#2711]
I use Spring Cloud stream with reactive Kafka binder. 

I have an interface **_Pet_**. I have 2 implementations.

```
Cat
Dog
```

**_Producer_**:

The Spring cloud stream producer produces Cat or Dog messages as Message<Pet>. I use **_CloudEventMessageBuilder_** to build the messages. I also notice that Message has the headers to indicate that what type of message is that. That is, every message contains the type info com.mypkg.Pet$Cat, com.mypkg.Pet$Dog

**_Consumer:_**

I set this

`spring.cloud.stream.kafka.binder.consumer-properties.spring.json.trusted.packages=*`

I get this exception.

`java.lang.ClassCastException: class [B cannot be cast to class com.mypkg.Pet  ([B is in module java.base of loader 'bootstrap';`

**_Steps to replicate:_**

Check [this repo](https://github.com/kitkars/spring-cloud-stream-decoding-issue).

**Comment by kitkars** [comment]
spring-kafka works fine though. It seems to be specific to spring-cloud-stream

**Comment by garyrussell** [comment]
`spring.cloud.stream.kafka.binder.consumer-properties.spring.json.trusted.packages=*`

Is meaningless in this context - Spring Cloud Stream uses `ByteArrayDeserializer` by default, that property is for the `JsonDeserializer`.

You need to use native decoding, by specifying the `JsonDeserializer`.

See https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_consumer_properties `useNativeDecoding`.

The property is not actually needed for Kafka consumers if you simply specify a deserializer; you can set it using `spring.kafka.consumer.value-deserializer` and it will be applied to all bindings, or you can specify it as a configuration property at the binder or binding level.

**Comment by kitkars** [comment]
I understand Gary. It works with native decoding. I thought we would not have to do that as we already have the type info in the header. Please close this my request does not make sense. I will be fine with native decoding.

**Comment by olegz** [comment]
There was a fix pushed recently where you can communicate type information with content type parameters. 
For example `content-type=application/json;type=org.acme.Cat`. 
Is that what you are looking for?
