### ISSUE TITLE
Display binder name in bindings actuator endpoint broke multiple binders support

### ISSUE THREAD

**Issue by vkochnev** [spring-cloud/spring-cloud-stream#2716]
Fix of https://github.com/spring-cloud/spring-cloud-stream/issues/2664 introduced two issues:.
1. Function `resolveFromDefaultBinder` ignores the fact that default binder can be also specified using the `spring.cloud.stream.defaultBinder` property (both custom and as binder type).
2. Function `resolveBinderType` expects binder to be explicitly declared in `binders` properties, which is not always required, as binder can be specified directly as binder type, so `bindingServiceProperties.getBinders().get(binder).getType()` call may result in NPE.

The aforementioned issues result in broken actuator bindings endpoint. E.g. you can encounter this in tests if you use test binder.

Workaround is to explicitly specify binder for every binding and explicitly specify binder along with it's type in case you have multiple enabled binders.

**Comment by sobychacko** [comment]
@vkochnev Thanks for reporting this. It is now addressed through the commits mentioned above.
