### ISSUE TITLE
Reactive Kafka Binder errors when concurrency > 1

### ISSUE THREAD

**Issue by adamsmith118** [spring-cloud/spring-cloud-stream#2726]
**Describe the issue**

The [Reactive Kafka Binder documentation](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_concurrency) suggests it should be possible to set consumer concurrency above 1.  
The binder should then create the correct number of `KafkaReceiver(s)` as per this value.

Given this config:

```yaml
    stream:
      bindings:
        test-in-0:
          destination: test
          binder: reactorKafka
          consumer:
            concurrency: 2
```

An error is thrown:

```Concurrency > 1 is not supported by reactive consumer, given that project reactor maintains its own concurrency mechanism. Was '...test-in-0.consumer.concurrency=2'```

**To Reproduce**

1. Clone this repo: https://github.com/adamsmith118/scs-reactive-kafka-concurrency-issue
2. Create a topic on a local broker called "test"
3. Run DemoApplication

**Version of the framework**

Java: 17
Boot: 3.0.6
SCS: 4.0.2

**Expected behavior**

The binder should then create the correct number of `KafkaReceiver(s)` as per this value.

**Additional context**

The FunctionConfiguration class still contains this check, which doesn't seem appropriate if the binder is the new Reactive one?

```java

    if (consumerProperties != null) {
        function.setSkipInputConversion(consumerProperties.isUseNativeDecoding());
        Assert.isTrue(consumerProperties.getConcurrency() <= 1, "Concurrency > 1 is not supported by reactive "
                + "consumer, given that project reactor maintains its own concurrency mechanism. Was '..."
                + inputBindingName + ".consumer.concurrency=" + consumerProperties.getConcurrency() + "'");
    }
```
If the check is removed then everything seems to work as expected with a new KafkaReceiver created as per the concurrency setting.

**Comment by garyrussell** [comment]
We are missing a full integration test. 

It is rather surprising that it has taken a year for somebody to find this; that code predates this PR https://github.com/spring-cloud/spring-cloud-stream/pull/2396

Unfortunately, that check is needed when using reactive code with other binders.

I will need to defer to @olegz for the correct way to deal with this.

**Comment by adamsmith118** [comment]
Brill, thanks for that @garyrussell.

Shout if there's anything I can do to help...

**Comment by sobychacko** [comment]
We might be able to bypass that check if the binder used is a reactive Kafka binder. We do similar checks for Kafka Streams binder but in different contexts.

**Comment by garyrussell** [comment]
As a work around, add a `ListenerContainerCustomizer` bean, cast the container to a `ConcurrentMessageListenerContainer` and set the `concurrency` on it.

**Comment by garyrussell** [comment]
@olegz Any suggestions for a fix before the next release?
