### ISSUE TITLE
The DefaultBinderFactory.propagateSharedBeans() is looking for shared bean in wrong context

### ISSUE THREAD

**Issue by mayur-solace** [spring-cloud/spring-cloud-stream#2728]
The call to the this.propagateSharedBeans(...) is passing the fromContext and toContext contexts in wrong order. The binderProducingContext should be toContext. 

Also calling the binderProducingContext.refresh() before call to this.propagateSharedBeans(..) creates new beans (that depends on shared beans) before shared beans are available for auto-wiring. 

Code snippet from `org.springframework.cloud.stream.binder.DefaultBinderFactory`

```
 if (refresh) {
	binderProducingContext.refresh();
	if (!useApplicationContextAsParent || "integration".equals(binderType.getDefaultName())) {
		this.propagateSharedBeans((GenericApplicationContext) this.context, binderProducingContext);
	}
}
```

should the call be instead....
```
if (refresh) {
	if (!useApplicationContextAsParent || "integration".equals(binderType.getDefaultName())) {
		this.propagateSharedBeans(binderProducingContext, (GenericApplicationContext) this.context);
	}
        binderProducingContext.refresh();
}
```

is there a tests that covers shared bean propagation ?

https://github.com/spring-cloud/spring-cloud-stream/blob/29c3cd7cddf9b853c57fca2b2118f1b64e5dde30/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/DefaultBinderFactory.java#L484

**Comment by Nephery** [comment]
For context, we're getting this issue while trying to upgrade the Solace binder to Spring Cloud `2022.x` since [this binder needs to use shared.beans](https://github.com/SolaceProducts/solace-spring-cloud/blob/master/solace-spring-cloud-stream-binder/solace-spring-cloud-stream-binder/src/main/resources/META-INF/shared.beans) to share some beans from the parent context to binder contexts for the [multiple systems setup](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#multiple-systems).

**Comment by sobychacko** [comment]
cc @olegz

**Comment by mayur-solace** [comment]
@olegz 

Look at the call to the method and definition of the method.  

`this.propagateSharedBeans((GenericApplicationContext) this.context, binderProducingContext);`

and 

`private void propagateSharedBeans(GenericApplicationContext toContext, GenericApplicationContext fromContext) { }`


Here, 
`this.context` - as per my understanding is the parent context and it is passed as `toContext`
`binderProducingContext` - is the child one (binder context) which is passed as `fromContext`

method `propagateSharedBeans(toContext, fromContext)` is trying to find the shared bean in `binderProducingContext`(i.e. fromContext) and inject it `this.context` (i.e. toContext). I think shared bean won't found in `binderProducingContext`

Let me know if my understanding is in correct.

**Comment by Nephery** [comment]
> Can you guys elaborate a bit more on this? Beans are propagated from parent context to child one (binder context) to ensure that certain beans are available to the binder context. So doing it the other way around is definitely wrong especially in the cases where you have multiple binders of the same type (i.e., two Solace binders connected to different solace clusters)

@olegz the issue that we were facing was that `shared.beans` wasn't propagating beans from parent context to the child contexts. We aren't doing it the other way around.

**Comment by Nephery** [comment]
@olegz this doesn't look like it works.

As @mayur-solace mentioned, we think this might be because `binderProducingContext.refresh();` is being called before `propagateSharedBeans()` is invoked. The context might need to be refreshed after `propagateSharedBeans()` instead of before.

**Comment by olegz** [comment]
@Nephery Can you please try with the latest snapshot?

**Comment by Nephery** [comment]
@olegz Looks like this works now. Thanks for the fix!
