### ISSUE TITLE
Add @EnableSparkStreamingProcessor contract

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#273]
As a developer, I'd like to explore options to support `@EnableSparkStreamingProcessor` as a native SCS contract, so I can use this opinion to implement `SparkStreamingProcessor` and process messages using Spark Streaming APIs from the message bus.

**Acceptance:**
* `SparkStreamingProcessor` and `EnableSparkStreamingProcessor` interfaces are available to implement SCS compatible custom `processor` modules
* Sample reference application is included
* Documentation and unit tests included

**Comment by mbogoevici** [comment]
Closing. The intent is to support Spark Streaming integration via common middleware - e.g. Kafka.
