### ISSUE TITLE
FunctionDetectorCondition no longer detects function beans defined in a parent class of a configuration file

### ISSUE THREAD

**Issue by j-n-white** [spring-cloud/spring-cloud-stream#2737]
**Describe the issue**
We are in the process of upgrading from 3.2.6 to 4.02 and have found that `org.springframework.cloud.stream.binder.kafka.streams.function.FunctionDetectorCondition` no longer detects beans unless they are defined directly in the configuration file. Any beans defined in parent classes are not detected.

**To Reproduce**
1. Create an app with configuration similar to this

```java
@Configuration
public class AppConfig extends BaseConfig {
}
```
```java
public abstract class BaseConfig {
    @Bean
    public Consumer<KStream<Foo, Bar>> myStreamFunction() {
        // create stream function
    }
}
```
2. Start the application
3. Kafka topic will not be consumed by the application

**Version of the framework**
4.0.2

**Expected behavior**
Stream function beans defined in parent classes will be detected and application consumes from Kafka topic

**Additional context**
This looks to be where the issue was introduced: https://github.com/spring-cloud/spring-cloud-stream/commit/b85ee57d80835956541c182521d0dffd0ef2ce4a

**Comment by sobychacko** [comment]
@j-n-white Thanks for reporting this issue. We will address it soon.

**Comment by j-n-white** [comment]
Thanks for fixing that so quickly. What is the timescale now for when this will be available in a release?

**Comment by sobychacko** [comment]
It will be available on the May 23rd release of Spring Cloud: https://calendar.spring.io/

**Comment by j-n-white** [comment]
That's awesome thanks again.
