### ISSUE TITLE
 spring-cloud-stream-binder-test v4.0.2 missing in maven?

### ISSUE THREAD

**Issue by martinformi** [spring-cloud/spring-cloud-stream#2741]
I see there is release with v4.0.2, however I cannot find  spring-cloud-stream-binder-test with this version number in maven. Is there any planned ETA when this could be available? Thank you.

**Comment by sobychacko** [comment]
The module `spring-cloud-stream-binder-test` is removed in `4.0.x`, and all its components have been migrated to `spring-cloud-stream-test-support.` Please take a look there and see if that module satisfies your requirements.

**Comment by martinformi** [comment]
Ok thank you. I understand it is not in the scope of the issue tracker, but I am trying to rewrite my tests to use 4.0.2 and I am not sure how I could autowire Sink object in tests. https://stackoverflow.com/questions/76307654/how-to-correctly-migrate-to-spring-cloud-stream-v4

**Comment by sobychacko** [comment]
I updated that SO thread with that answer. See if that is sufficient. Please feel free to close this issue if you are okay with that.

**Comment by martinformi** [comment]
Ok, I am including `spring-cloud-stream-test-binder` anyways, because all the missing classes are there.
