### ISSUE TITLE
Provide KafkaBinderHealthIndicator for ReactorKafkaBinder

### ISSUE THREAD

**Issue by djohs** [spring-cloud/spring-cloud-stream#2752]
**Describe the issue**
We switched from spring-cloud-stream-binder-kafka to spring-cloud-stream-binder-kafka-reactive and encountered that it does not provide a HealthIndicator. Are there plans to add one ? Or is there another way how we can check the health of the ReactorKafkaBinder ?

**Version of the framework**
4.0.2

**Comment by sobychacko** [comment]
@djohs Health indicator for the reactor Kafka binder is now added as a new feature. The changes are upstream in the `main` branch (currently `4.1.0-SNAPSHOT`) and it has just been back-ported to the `4.0.x` branch as well. See the above commits for more details. Please take it for a spin and we would appreciate any feedback.
