### ISSUE TITLE
Metrics emitter not working?

### ISSUE THREAD

**Issue by kothapet** [spring-cloud/spring-cloud-stream#2758]
I have a simple spring cloud stream application demo application with kafka binder (code from https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#spring-cloud-stream-overview-introducing). 
I have added metrics configuration for actuator, however I am not getting any metrics into metrics topic, infact metrics topic is not even getting created.
I added the following to pom.xml

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
```

And added these to application.properties

```
#
management.health.binders.enabled=true
management.endpoint.health.show-details=ALWAYS
#
spring.cloud.stream.bindings.applicationMetrics.destination=metrics-topic
spring.cloud.stream.bindings.applicationMetrics.binder=kafka
#
```

I get actuator health thru http://localhost:8080/actuator and actuator/health Any thoughts on what am I missing?
Also in the latest documentation the Metrics Emitter section was missing.. Was it removed in the latest versions? I see the section here in the old documentation
https://cloud.spring.io/spring-cloud-stream/multi/multi_spring-cloud-stream-overview-metrics-emitter.html

**Comment by kothapet** [comment]
I found that it works fine in spring cloud stream Version 3.x, but doesn't work on Version 4.x. Is this deprecated in V4?

**Comment by sobychacko** [comment]
@kothapet Those properties have been deprecated for a while and completely removed in Spring Cloud Stream 4.x. You need to use micrometer based metrics going forward. Basic idea is that you enable Micrometer by including it in the classpath and instruct Boot how you want to export the metrics (Promethus, wavefront etc.). Please refer to the Boot documentation for details on that. You can export all the previously available Spring Integration metrics via micrometer this way. In addition Kafka binder also provides, some binder specific Kafka metrics. See [this](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#kafka-metrics) for more details. Let us know if you have more questions.

**Comment by kothapet** [comment]
OK thanks @sobychacko. I am able to get the metrics thru micrometer to Prometheus and Graphana.

**Comment by kothapet** [comment]
OK thanks @sobychacko. I am able to get the metrics thru micrometer to Prometheus and Graphana.
