### ISSUE TITLE
StreamBridge error when using SpEL to extract partition key from payload 

### ISSUE THREAD

**Issue by djivko** [spring-cloud/spring-cloud-stream#2759]
When I configure `partitionKeyExpression=payload.<someProperty>` and use StreamBridge to send a message there is an error when extracting the partition key:

 ```EL1008E: Property or field 'partitionKey' cannot be found on object of type 'byte[]'```

While this issue has been raised multiple times: #2213 , #1877 , #1893 triggering different discussions a fix for that seems to be implement by this [commit](https://github.com/spring-cloud/spring-cloud-stream/commit/cce66f338a843fceffb5271ab357317ed1262479), which is also evident by SCS [tests](https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/ImplicitFunctionBindingTests.java#L867) 

**Addition Context**
The issue seems to happen because partition resolver is called twice - once from StreamBridge (where it correctly extracts the partition key) and once from AbstractMessageChannel (where it fail as the message is already converted to byte[]). The flow seems to be:
```
StreamBridge.send -> functionToInvoke.apply -> resolves partition and convert message to byte[] -> 
messageChannel.send -> AbstractMessageChannel.sendInternal -> 
interceptors list contains the DefaultPartitioningInterceptor, the SpEl expression for partition resolution is applied again. However this time the message payload is already converted to byte[] thus we are seeing the error. 
```

Attached is a simple project that reproduces the issue. 
[demo.zip](https://github.com/spring-cloud/spring-cloud-stream/files/11815318/demo.zip)

**Comment by sobychacko** [comment]
@djivko The issue is resolved now through the commit mentioned above. Backported to `4.0.x` as well. Please try the fix on the latest snapshots.

**Comment by djivko** [comment]
@sobychacko all seems to be working fine with latests 4.0.4-SNAPSHOT. Thanks for the super fast fix!
