### ISSUE TITLE
kafka.streams.binder.configuration.ssl.truststore.location property improvement

### ISSUE THREAD

**Issue by gynoro** [spring-cloud/spring-cloud-stream#2761]
You should define the property 

> kafka.streams.binder.configuration.ssl.truststore.location

 (the part ssl.truststore.location) as org.springframework.core.io.Resource and not as 

> private Map<String, String> configuration = new HashMap<>();

 in the property class org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties. Then we could define truststore location paths in more generic way e.g. with prefixes "classpath:", "file:", "http:", etc. It would be more consistent with Spring conventions and this method

 ```
private void moveCertsToFileSystemIfNecessary() {
		try {
			final String trustStoreLocation = this.configuration.get("ssl.truststore.location");
			if (trustStoreLocation != null && trustStoreLocation.startsWith("classpath:")) {
				final String fileSystemLocation = moveCertToFileSystem(trustStoreLocation, this.certificateStoreDirectory);
				// Overriding the value with absolute filesystem path.
				this.configuration.put("ssl.truststore.location", fileSystemLocation);
			}
			final String keyStoreLocation = this.configuration.get("ssl.keystore.location");
			if (keyStoreLocation != null && keyStoreLocation.startsWith("classpath:")) {
				final String fileSystemLocation = moveCertToFileSystem(keyStoreLocation, this.certificateStoreDirectory);
				// Overriding the value with absolute filesystem path.
				this.configuration.put("ssl.keystore.location", fileSystemLocation);
			}
		}
		catch (Exception e) {
			throw new IllegalStateException(e);
		}
	}
```
would be less redundant and flexible (you could define more types of resources).

**Comment by sobychacko** [comment]
What exactly is your use case? The method `moveCertsToFileSystemIfNecessary` was originally added in order to work around some file system restrictions on some particular environments such as the CloudFoundry. I see your argument for more accommodating resources such as HTTP, file etc. We can certainly do that if there is a valid use case for that. Also, if you are open to making this change and send us a PR, we will be happy to further review it. Please let us know what your thoughts are on this matter.

**Comment by sobychacko** [comment]
@gynoro Makes sense. Please issue the PR; we will review it.

**Comment by garyrussell** [comment]
Given that the trust store is read by the `kafka-clients`, I believe the only solution here would be to copy the store to the local file system, perhaps in the `main` method before initializing the application context.

Yes, Spring Boot supports using `classpath:`, but only if that class path resolves to a file on the file system; it cannot resolve to a file in the jar.

There is an open issue against Kafka to support reading from the class path: https://issues.apache.org/jira/browse/KAFKA-7685

Reading from a certificate server should probably be handled by the kafka-clients too.

**Comment by sobychacko** [comment]
The original change (mentioned in the original comment on this issue) was explicitly made to copy the certificate files from the jar to a temp location on the CloudFoundry instance the app was running and then override the cert properties to that location.

**Comment by gynoro** [comment]
Sorry for the delay. I issued the PR https://github.com/spring-cloud/spring-cloud-stream/pull/2775 please review it :)
