### ISSUE TITLE
Question: Clarify SCS error management

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream#2776]
Several days ago I posted the following [question](https://stackoverflow.com/questions/76620274/handling-errors-with-spring-cloud-stream-and-kafka) on stackOverflow but I didn't get an answer, so I've decided to post it here. Sorry if it is not appropriate.

In version [4.0.x of the Spring Cloud stream](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_handle_error_messages) with Spring Boot 3 it seems that the way in which errors can be handled has been changed compared to version [3.2.0 of SCS via the commonErrorHandlerBeanName](https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.2.0/reference/html/spring-cloud-stream-binder-kafka.html#kafka-consumer-properties) property in the binding.

However, with Spring Cloud Stream version 4.0.x, error handling using the commonErrorHandlerBeanName property in the Consumer properties still works correctly, although this form of error handling is no longer in the documentation for the latest version of SCS and [is no longer deprecated at the code level](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/4.x/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L791-L796)...

What is the appropriate way to handle errors in SCS for future versions, and what is the difference between the two?

**Comment by sobychacko** [comment]
@ferblaca Updated the SO thread with an [answer](https://stackoverflow.com/a/76707128/2070861). See if that makes sense. Please let us know if you have more questions or if something is unclear.

**Comment by ferblaca** [comment]
@sobychacko the answer is clear, thank you very much! The only thing is that the latter method if it is not deprecated, it would be nice if it is also reflected in the documentation for the Kafka binder.

**Comment by sobychacko** [comment]
It is documented, if you search for that property (`commonErrorHandlerBeanName`) in the Kafka binder docs. If you think that we need to make it more clear, we are open to that. You can also contribute a PR, adding the details.

**Comment by StevenPG** [comment]
Does this function when exceptions are thrown inside .transform, .processor, and .map methods?

Reproducible example is located here, none of these error handling components seem to work in this example. Or I'm misunderstanding.

https://github.com/StevenPG/scs-experimentation/tree/main/scs4-error-handling/error-handling

I plan on opening up a dedicated issue around error handling samples, but just looking to understand where this is applicable.

**Comment by sobychacko** [comment]
@StevenPG This issue concerns the general error handling mechanisms available in Spring Cloud Stream and the Kafka binder. You are using Kafka Streams binder, which uses different models for error handling. I think you already created an [issue](https://github.com/spring-cloud/spring-cloud-stream/issues/2779). Let's continue the discussion there.

**Comment by ferblaca** [comment]
thanks @sobychacko
