### ISSUE TITLE
Add binder SPI overview section to reference docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#278]
As a developer, I'd like to add overview section for binder SPIs, so it could be as reference for anyone ~~selecting and using the supported binders~~ interested in learning more about the Binders and the underpinning contracts. 

**Acceptance:**
* Overview section is available along with visuals to articulate core details
* All the available binder properties for override are included
* Binder properties for both SCS and SCDF developer experience are defined

**Comment by ericbottard** [comment]
Isn't that already covered here: http://docs.spring.io/spring-cloud-stream/docs/1.0.0.BUILD-SNAPSHOT/reference/html/spring-cloud-stream-overview.html#_binder_selection ?

**Comment by markfisher** [comment]
That existing doc doesn't cover anything about the `Binder` interface itself, nor the semantics for bound producers and consumers.

**Comment by ericbottard** [comment]
Hmm, I think I got mislead by 
> be as reference for anyone selecting and using the supported binders.

Is this supposed to be an "end-user reference" (how to select binders) or a "binder implementor reference" (how to write a new `Binder`)?

**Comment by markfisher** [comment]
I agree that particular bullet point sounds like it describes what is already documented. I don't think we're talking so much about a guide for implementors as an overview of the contract and description of the behavior.

**Comment by markfisher** [comment]
That said, we also should be including the documentation of how that contract is mapped to each of the existing implementations, and that is relevant for users since they need to know what actually occurs within their broker, for monitoring etc.

**Comment by mbogoevici** [comment]
Actually, I think we need to do even more than just the method contracts in terms of signatures. A significant amount of the Binder behaviour is captured in the Properties passed as arguments. We need to capture what changes between different implementations (if it does).

**Comment by sabbyanandan** [comment]
@ericbottard: My bad. I updated the description/acceptance to reflect the missing links.

**Comment by mbogoevici** [comment]
Also should document infrastructural things like health management infrastructure support (see https://github.com/spring-cloud/spring-cloud-stream/issues/233)

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream/issues/516
