### ISSUE TITLE
Header propagation issues

### ISSUE THREAD

**Issue by voodemsanthosh** [spring-cloud/spring-cloud-stream#2781]
@metalpalo Apologies for not getting back to you for a long time. We no longer need to set `embeddedHeaders` since Apache Kafka provides native headers support. This is intended for middleware systems that do not support native headers.

             @voodemsanthosh Closing the issue. Feel free to re-open (or create a new one) if you find any issues.

 _Originally posted by @sobychacko in https://github.com/spring-cloud/spring-cloud-stream/issues/2451#issuecomment-1650269986_

@sobychacko , Really appreciate your quick update. I am opening a new issue to continue for solutioning,

 I am implementing in same way for Functional programming.

Service 1
==================

It act as Consumer and Publisher.
```
@Bean
  public Function<Message<List<Users>>, List<Users>> process() {
      return request -> {
          List<Users> finalUserList = business.processBusinessLogic(request.getPayload());
          MessageBuilder.withPayload(finalUserList).setHeader("source", "shares").setHeader("client", "finance").build();
         return finalUserList;
}
```
Service 2
================

```
@Bean
  public Function<Message<List<Users>>, String> process() {
      return request -> {
          String data = null;
         //find the headers for message
          MessageHeaders headers = request.getHeaders();    // Missing custom headers(source and client) from Service 1
          data = business.processLogic(request.getPayload());
         return data;
}
```

Always getting default headers, still missing custom headers key and value. Please see my headers from offset explorer,

   
<img width="1143" alt="image" src="https://github.com/spring-cloud/spring-cloud-stream/assets/5786198/a58a62cf-04d0-498e-8d35-a1c86f801300">

Please let me know if need to have any configuration ?

**Comment by sobychacko** [comment]
How do you add custom headers? Can you create a small reproducible sample for us to debug?

**Comment by voodemsanthosh** [comment]
Sorry, I was little side tracked and missed to update my findings.

With given above code snippet started working and still my head around what I did to work after this issue created.

But I am sure not much changed at my code. We are good to close this issue now and I will share if I find any changes.

Thank you again for your support.
