### ISSUE TITLE
alltopicnames is not found

### ISSUE THREAD

**Issue by nabeelAtAlef** [spring-cloud/spring-cloud-stream#2785]
trying to reopen the closed ticket - https://github.com/spring-cloud/spring-cloud-stream/issues/2784

I tried with the suggested version - Spring Cloud 2022.x.x with Spring Boot 3.0.x Still the same issue.

`Caused by: java.lang.NoSuchMethodError: 'org.apache.kafka.common.KafkaFuture org.apache.kafka.clients.admin.DescribeTopicsResult.allTopicNames()' at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.lambda$retrieveTopicDescriptions$1(KafkaTopicProvisioner.java:275) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3] at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.1.jar!/:na] at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-1.3.1.jar!/:na] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.retrieveTopicDescriptions(KafkaTopicProvisioner.java:267) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:258) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:194) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.provisionProducerDestination(KafkaTopicProvisioner.java:91) ~[spring-cloud-stream-binder-kafka-core-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:286) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:102) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:153) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binding.BindingService.doBindProducer(BindingService.java:345) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:294) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.function.StreamBridge.resolveDestination(StreamBridge.java:257) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:161) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:147) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:142) ~[spring-cloud-stream-4.0.3.jar!/:4.0.3] at com.alefeducation.contentrepositoryservice.event.Publisher.publish(Publisher.kt:17) ~[classes!/:0.0.1-SNAPSHOT] at com.alefeducation.contentrepositoryservice.services.RepositoryService.createRepository(RepositoryService.kt:21) ~[classes!/:0.0.1-SNAPSHOT] at com.alefeducation.contentrepositoryservice.controller.RepositoryController.createRepository(RepositoryController.kt:22) ~[classes!/:0.0.1-SNAPSHOT] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]`

Also spring boot compatibility suggests that cloud 2022.x.x should work fine with boot 3.1.x - https://spring.io/projects/spring-cloud.

**Comment by olegz** [comment]
Please post your POM. You clearly have some dependency managed manually that is not inline with what's supported, but without seeing your POM it's impossible to say

**Comment by sobychacko** [comment]
Could you set up a small sample application where it is failing with the minimum setup? We would like to see it reproduced.
