### ISSUE TITLE
Lack of documentation: how to choose a function based on a header?

### ISSUE THREAD

**Issue by vprudnikov** [spring-cloud/spring-cloud-stream#2786]
**Documentation doesn't contain information about how to choose a function based on a condition**

The documentation like https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_event_routing and https://cloud.spring.io/spring-cloud-function/reference/html/spring-cloud-function.html#_function_routing says that routing is possible. 

There is only one simple example with 'odd'/'even' functions. 

It's not that useful enough since I believe that one of the most popular use cases is to choose ONE function (but not either) based on the filter.

For example, I have 2 functions that are supposed to be connected to the same Kafka topic:

```
    @Bean
    Consumer<BookCreatedEvent> consumeBookCreatedEvent() {
        return event -> ...
    }

    @Bean
    Consumer<OrderPlacedEvent> consumeOrderPlacedEvent() {
        return event -> ...
    }
```
 and configuration (which is, most probably, incorrect):

```
spring.cloud.function.definition=consumeBookCreatedEvent;consumeOrderPlacedEvent
spring.cloud.stream.function.bindings.consumeBookCreatedEvent-in-0=storeInput
spring.cloud.stream.function.bindings.consumeOrderPlacedEvent-in-0=storeInput
spring.cloud.stream.bindings.storeInput.destination=store
spring.cloud.function.routing-expression=headers['type']=='BookCreatedEvent' ? 'consumeBookCreatedEvent' : ''
spring.cloud.function.routing-expression=headers['type']=='OrderPlacedEvent' ? 'consumeOrderPlacedEvent' : ''
```

Whatever I change in the configuration (the binding name, the routing-expression), the application just starts without any problem, however, it ignores the `consumeOrderPlacedEvent` by always calling the `consumeBookCreatedEvent`.

My personal feeling is that the previous annotation-based model (i.e. `@StreamListener(target = ..., condition = "headers['type']=='OrderPlacedEvent'")`) worked much better. At least it worked :) 
As of now, I just see from the documentation that routing IS possible, however, not HOW.

I would like to ask you about adding more samples and a clear description.
Compare to this very nice documentation: https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.SR1/reference/htmlsingle/#_programming_model

**Comment by vprudnikov** [comment]
After hours of guessing and trying, I ended up with the configuration that works:
```
spring.cloud.function.definition=functionRouter;consumeBookCreatedEvent;consumeOrderPlacedEvent
spring.cloud.stream.function.bindings.functionRouter-in-0=storeInput
spring.cloud.stream.bindings.storeInput.destination=store
spring.cloud.function.routing-expression='consume' + headers['type']
```

However, the problem is the same: the current documentation quality is far from the documentation for the annotation-based approach.

**Comment by sobychacko** [comment]
@vprudnikov Point noted on the documentation. As part of the 4.1 release, we will focus more on improving the quality of the docs. In the meantime, if you have the bandwidth, why don't you submit a PR with these improvements? We will happily review it and make it part of the official docs. Thanks!

**Comment by sobychacko** [comment]
I am closing the issue. Please feel free to re-open if you find more issues.
