### ISSUE TITLE
Using Kafka Streams Branching as @Component Bean causes NPE

### ISSUE THREAD

**Issue by GFriedrich** [spring-cloud/spring-cloud-stream#2821]
**Description**
Next to the issue of https://github.com/spring-cloud/spring-cloud-stream/issues/2820 I've found another issue when using Kafka Streams branching mechanism, but in this case here when the branching function is registered as @Component bean.

**To Reproduce**
1. Get the example from https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/kafka-streams-samples/kafka-streams-branching
2. Rewrite the example to create a @Component bean instead of a function @Bean
3. When running the example, see that an NPE is being triggered like:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isAssignableFrom(java.lang.Class)" because the return value of "org.springframework.core.ResolvableType.getRawClass()" is null
	at org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsBindableProxyFactory.buildInputBindings(KafkaStreamsBindableProxyFactory.java:212)
	at org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsBindableProxyFactory.afterPropertiesSet(KafkaStreamsBindableProxyFactory.java:100)
```

**Suggested Fix**
The issue is that the code at the following place doesn't expect the type to miss the raw class:
https://github.com/spring-cloud/spring-cloud-stream/blob/ca2d3046b9bed5bb29b82a55044fe8fa809a760d/binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/function/KafkaStreamsBindableProxyFactory.java#L206-L212

As one can see in the original code before this is being checked on the regular types:
https://github.com/spring-cloud/spring-cloud-stream/blob/ca2d3046b9bed5bb29b82a55044fe8fa809a760d/binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/function/KafkaStreamsBindableProxyFactory.java#L200-L202

so I've adapted the path for `@Component` bean in the same way which fixed the issue for me, like:
```java
final ResolvableType returnType = ResolvableType.forMethodReturnType(method);
Object bean = beanFactory.containsBean(functionName) ? beanFactory.getBean(functionName) : null;

if (bean != null && (BiFunction.class.isAssignableFrom(bean.getClass()) || BiConsumer.class.isAssignableFrom(bean.getClass()))) {
  numberOfInputs = 2;
}
else if (returnType.getRawClass() != null && (returnType.getRawClass().isAssignableFrom(Function.class) || returnType.getRawClass().isAssignableFrom(Consumer.class))) {
```

**Version of the framework**
4.0.3

Let me know if you've any further questions.

**Comment by sobychacko** [comment]
@GFriedrich Thanks for the issue. This is fixed on the `main` branch and back-ported to `4.0.x`.

**Comment by GFriedrich** [comment]
Awesome - thats great to hear. Looking forward to the next release.
