### ISSUE TITLE
Kafka Streams Binder: some messages are routed to the wrong consumer when using event type based routing and consumers concurrency > 1

### ISSUE THREAD

**Issue by flemaitre** [spring-cloud/spring-cloud-stream#2823]
Beyond a certain number of messages in the topic (around 300 in the demo code), when using event type based routing (*) and the consumers concurrency is configured to a value higher than one (**), some messages are routed to the wrong consumer, resulting in java.lang.ClassCastException exceptions.

(*) https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_event_type_based_routing_in_kafka_streams_applications

(**) https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_concurrency

Kafka Streams Binder 4.0.4

**Comment by flemaitre** [comment]
Please find two demo apps (one for the Producer and one for the Consumer) here: https://github.com/flemaitre/scs-issue-2823-sample-app

**Comment by sobychacko** [comment]
@flemaitre Thanks for this report. It looks like there was a shared resource in the binder that was causing a race condition when the `concurrency > 1` setting was used. I issued a PR addressing this issue. We will get this merged tomorrow and backported to `4.0.x`. Thanks!

**Comment by flemaitre** [comment]
@sobychacko Thanks a lot for your reactivity !

**Comment by sobychacko** [comment]
@flemaitre np! Your sample applications helped us a lot in triaging the issue. The PR is merged upstream to `main` and backported to `4.0.x`. Please get the latest snapshots and verify that the fix works for you. Ping here if you see any issues. Thanks!
