### ISSUE TITLE
StreamsBuilderFactoryManager overwrites  StreamsUncaughtExceptionHandler set using a StreamsBuilderFactoryBeanConfigurer

### ISSUE THREAD

**Issue by bjeSSAdev** [spring-cloud/spring-cloud-stream#2836]
This issue was first noted by @jmebly70 on this closed issue https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1110. 

The StreamsBuilderFactoryManager class sets a StreamsUncaughtExceptionHandler that defaults to Shutdown the thread on any exception. This overwrites any custom StreamsUncaughtExceptionHandler configured by the application.  

**To Reproduce**
1. Set an StreamsUncaughtExceptionHandler using a StreamsBuilderFactoryBeanConfigurer

**Version of the framework=4.0.4**

![image](https://github.com/spring-cloud/spring-cloud-stream/assets/121501325/a9bc7ec8-d84d-4ffe-bffb-843f79619a4a)

**Comment by sobychacko** [comment]
@bjeSSAdev If you provide a `StreamBuilderFactoryBeanConfigurer` as a bean in your application, you can override the exception handler. Did you try that? Here is an example.
```
@Bean
public StreamsBuilderFactoryBeanConfigurer customizer() {
  return factoryBean -> {
	factoryBean.setKafkaStreamsCustomizer(
           kafkaStreams -> kafkaStreams.setUncaughtExceptionHandler(exception ->
		StreamsUncaughtExceptionHandler.StreamThreadExceptionResponse.REPLACE_THREAD));
  };
}

```

**Comment by bjeSSAdev** [comment]
Yes.  I didn't provide code but, in the steps, to reproduce the error, I mentioned.
**Set an StreamsUncaughtExceptionHandler using a StreamsBuilderFactoryBeanConfigurer**. I didn't include the part about making sure StreamsBuilderFactoryBeanConfigurer is a bean.
 
When I provide the StreamsBuilderFactoryBeanConfigurer as bean, using debug mode, I can confirm its being picked up. Also using debug mode I can confirm that my custom ExceptionHandlers are set before Line 96 in the StreamBuilderFactoryManager before they are overwritten. 

code.

`@Configuration
public class GlobalStreamsConfiguration {

    @Bean
    public StreamsBuilderFactoryBeanConfigurer streamsBuilderFactoryBeanConfigurer(@Value("${kafka.recoverable.exceptions}") List<String> recoverableExceptionClassList) {
        return new ExceptionConfigurer(recoverableExceptionClassList);
    }


}

class ExceptionConfigurer implements StreamsBuilderFactoryBeanConfigurer {

    private List<String> recoverableExceptionClassList;

    public ExceptionConfigurer(List<String> recoverableExceptionClassList) {
        this.recoverableExceptionClassList = recoverableExceptionClassList;
    }

    @Override
    public void configure(StreamsBuilderFactoryBean factoryBean) {
        String streamsApplicationId = factoryBean.getStreamsConfiguration().getProperty(StreamsConfig.APPLICATION_ID_CONFIG);
        StreamsExceptionHandler streamsExceptionHandler = new StreamsExceptionHandler(streamsApplicationId, recoverableExceptionClassList);
        factoryBean.setStreamsUncaughtExceptionHandler(streamsExceptionHandler);

    }

    @Override
    public int getOrder() {
        return Integer.MAX_VALUE;
    }
}
`

I'm having trouble confirming this, but I believe the framework will invoke the configure method of the provided StreamsBuilderFactoryBeanConfigurer before the StreamsBuilderFactoryManager runs.

**Comment by sobychacko** [comment]
You need to set the `StreamsUncaughtExceptionHandler` on the `KafkaStreamsCustomizer`. 

```
@Override
public void configure(StreamsBuilderFactoryBean factoryBean) {
    String streamsApplicationId = factoryBean.getStreamsConfiguration().getProperty(StreamsConfig.APPLICATION_ID_CONFIG);
    StreamsExceptionHandler streamsExceptionHandler = new StreamsExceptionHandler(streamsApplicationId, recoverableExceptionClassList);
    factoryBean.setKafkaStreamsCustomizer(kafkaStreams -> kafkaStreams.setUncaughtExceptionHandler(exception ->
						StreamsUncaughtExceptionHandler.StreamThreadExceptionResponse.SHUTDOWN_CLIENT));

}
```

**Comment by bjeSSAdev** [comment]
Ahh, I see my mistake and error. My apologies, thank you.
