### ISSUE TITLE
KStream array output type on Component beans doesn't apply automatic Serde detection

### ISSUE THREAD

**Issue by GFriedrich** [spring-cloud/spring-cloud-stream#2843]
**Describe the issue**
When using an array of KStream objects returned from a functional component bean, the automatic detection for possible Serdes doesn't work, so one is forced to set the Serdes explicitly for each binding via the properties.

**To Reproduce**
1. Get the example from https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/kafka-streams-samples/kafka-streams-branching
2. Rewrite the example to create a `@Component` bean instead of a function `@Bean`
3. Make the functional component bean to return a `KStream<String, String>[]`
4. Drop `default.key.serde` and `default.value.serde` configurations from the properties.
5. See that the `ByteArraySerde` instead of the `StringSerde` is used on initialization.

**Suggested Fix**
Even though the `KeyValueSerdeResolver` is able to handle the array of `KStream` objects for selecting the right Serde, the output type doesn't even reach this code path. This is because the `buildTypeMap` in the `KafkaStreamsFunctionProcessor` doesn't store the outbound type to the type map when an array is detected.
To make it work I've changed this:
https://github.com/spring-cloud/spring-cloud-stream/blob/9054367f674724f51faa93eb182f4914404334ac/binders/kafka-binder/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsFunctionProcessor.java#L173-L191
To rather look like this:
```java
private void traverseReturnTypeForComponentBeans(Map<String, ResolvableType> resolvableTypeMap, ResolvableType currentOutputGeneric,
												Set<String> inputs, Iterator<String> iterator) {
	final Class<?> outputRawclass = currentOutputGeneric.getRawClass();
	if (outputRawclass != null && !outputRawclass.equals(Void.TYPE) || currentOutputGeneric.isArray()) {
		ResolvableType iterableResType = currentOutputGeneric;
		int i = 1;
		// Traverse through the return signature.
		while (i < inputs.size() && iterator.hasNext()) {
			if (iterableResType.getRawClass() != null &&
					functionOrConsumerFound(iterableResType)) {
				populateResolvableTypeMap(iterableResType, resolvableTypeMap, iterator);
			}
			iterableResType = iterableResType.getGeneric(1);
			i++;
		}
		if (iterableResType.getRawClass() != null && KStream.class.isAssignableFrom(iterableResType.getRawClass())
			|| iterableResType.isArray() && iterableResType.getComponentType().getRawClass() != null
				&& KStream.class.isAssignableFrom(iterableResType.getComponentType().getRawClass())) {
			resolvableTypeMap.put(OUTBOUND, iterableResType);
		}
	}
}
```
Changes done:
* I've allowed the detection of the array in the first place
* And then simply placed the type to the map if it was matching a KStream array.
  * It is more or less the same what is done in the `KeyValueSerdeResolver`. (This by the way misses a check for the `getComponentType().getRawClass() != null` when checking for KStream arrays which looked a bit odd, but I guess it is a different story.)
* Little cleanup: I've removed the `outputRawclass` as parameter as the value is anyways available via the `currentOutputGeneric` parameter.

**Version of the framework**
4.0.3

Let me know if you have any questions.

**Comment by sobychacko** [comment]
@GFriedrich Since you were able to make it work, are you open to sending a PR fixing it in the binder?

**Comment by GFriedrich** [comment]
@sobychacko sure - will try to create something over the weekend.
