### ISSUE TITLE
Address remaining loose ends from binder refactoring

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#285]
As a follow-up to spring-cloud/spring-cloud-stream#276, we would like to address the remaining loose ends including the refactoring/simplification of `unbind(binding)` contract.

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/commit/c3758b9dc0d0ccebbf162a7f75affb84a1b08ff0
