### ISSUE TITLE
Messages get Duplicated when RabbitMQ Message Exeeds Maximum Body Size

### ISSUE THREAD

**Issue by GJohannes** [spring-cloud/spring-cloud-stream#2854]
Following up on https://stackoverflow.com/questions/77185001/spring-cloud-stream-with-rabbitmq-binder-throws-java-lang-illegalstateexception there are side effects to this behaviour. When there are multiple consumers in a SpringBoot Application and one tries to consume a Message that is to large to be consumed, all Consumers are restarted. 

As a result current Messages that are worked on get put back into the RabbitMQ Queue since RabbitMQ does not get an acknowledgement. Simultaniously the current thread that works on this Event is not interupted and the Transaction completes sucessfully. 

**Steps to reproduce the behavior:**

- Have 2 Queues. Queue one that has a Message with more than 64MB so that "java.lang.IllegalStateException: Message body is too large" is triggered
- Have a second Queue that has Multiple messages. Each Message generates a Database entry in a Simple CRUD Repository.  
  - Important: Have the second Queue configured first so that it beginns to run before the first Queue that contains the message that is to large `spring.cloud.function.definition: secondConsumer;firstConsumer # <-- swapping this order "resolves the Problem" ` 

- Start the application. The First Event will now be duplicated in the Database. (Depending on SQL Unique constraints or similar the follow up problems are even worse)

**Version of the framework**
Using SpringBoot 3.1.5, RabbitMQ 3.11.17 and Spring Cloud 2022.0.4

**Expected behavior**
Messages do not get duplicated. Overflowing of one Queues does not effect other Queues.

**Screenshots**
![RabbitMQ-Queues](https://github.com/spring-cloud/spring-cloud-stream/assets/12232357/64875404-776c-403b-82df-adce640d4a8f)
![RabbitMQ-MessageContent](https://github.com/spring-cloud/spring-cloud-stream/assets/12232357/b1781e10-9efe-49f4-930b-2cdaf86ca596)
![secondConsumer](https://github.com/spring-cloud/spring-cloud-stream/assets/12232357/74f4df2e-65bb-41a3-ac80-8b312e202c60)
![DatabaseState](https://github.com/spring-cloud/spring-cloud-stream/assets/12232357/ce7a8583-66de-4ba6-81bc-ea27a239200c)

**Comment by garyrussell** [comment]
Spring has no control over this, the `amqp-client` closes the connection when a message that is too large is received; this means that any other in-flight message(s) will also be requeued.

RabbitMQ makes no promise of "exactly once delivery" semantics, only "at least once"; there are many scenarios (such as this one, or any network glitch etc., etc.) that can cause duplicate deliveries; it is up to the application to detect duplicates and/or make updates idempotent.

**Comment by garyrussell** [comment]
You can avoid/work around the specific problem by setting the `CacheMode` on the `CachingConnectionFactory` to `CONNECTION` so that each consumer gets its own connection; however, you still need to handle duplicates for the reasons I stated.
