### ISSUE TITLE
Stackoverflow occurs when shutdown application when we have a multi binder configuration

### ISSUE THREAD

**Issue by pcavezzan** [spring-cloud/spring-cloud-stream#2870]
**Stack over flow on shutdown**

When we have a multi binder configuration (see [application.yaml](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/main/multi-binder-samples/multi-binder-two-kafka-clusters/src/main/resources/application.yml) example), it works correctly until we shutdown the application. When spring is closing it context, it seems like a stack over flow is thrown.
 Before spring boot 3.2 , spring cloud 2023.0.0 and spring cloud stream 4.1.0  ; it worked well. 
If we use default binder configuration, it works well as well.

**To Reproduce**

I made a sample project Steps to reproduce the behavior:
1. git clone https://github.com/pcavezzan/demo-spring-cloud-stream.git
2. cd demo-spring-cloud-stream
3. ./mvnw spring-boot:run
4. let few seconds by producing and consuming messages
5. stop the application by pressing Ctrl-C 
6. You should see the stackoverflow errors

**Version of the framework**

* spring boot 3.2 
* spring cloud 2023.0.0 
* spring cloud stream 4.1.0

**Expected behavior**

Spring application should close it context without any errors

**Screenshots**

* With multi binder configuration (when error occurs)
![image](https://github.com/spring-cloud/spring-cloud-stream/assets/3405916/ec5b669f-f538-4d48-ad84-f56a84f48123)

* With default binder configuration (expected behavior)
<img width="1461" alt="image" src="https://github.com/spring-cloud/spring-cloud-stream/assets/3405916/4d0c53bb-864e-4904-8be3-478d07c99937">

**Additional context**

On my [repository example](https://github.com/pcavezzan/demo-spring-cloud-stream), I made a [PR](https://github.com/pcavezzan/demo-spring-cloud-stream/pull/1) to show the modification I had to do for making it work.

I wish I could find the problem, unfortunately I do not understand why it does not work. The only thing I could investigate this weekend is it does not concern kafka binder (I reproduced the same thing with rabbit binder).

**Comment by sobychacko** [comment]
@pcavezzan This was a regression issue. I just pushed a change to address this in the main branch. Thanks for catching this.
