### ISSUE TITLE
StreamBridge caching a null function

### ISSUE THREAD

**Issue by peterdaub** [spring-cloud/spring-cloud-stream#2872]
At StreamBridge:249, if the functionToInvoke is null it will be cached anyway.  If a bean implementing SmartInitializingSingleton calls the StreamBridge.send method, the functionCatalog does not yet contain the functions - such as the stream bridge function for JSON mime type - and will just cache null.

1. Implement any component that extends SmartInitializingSingleton.
2. Call streamBridge.send with any event from the initialize method.
3. See null pointer thrown from StreamBridge.send method
4. Once the function is cached, it is stuck.

spring-cloud-dependencies: 2021.0.8
spring-cloud-stream-dependencies: 3.2.9

**Expected behavior**
Stream bridge function of Application-Json mime type should be available for SmartInitializingSingleton Beans.

Thanks!

**Comment by sobychacko** [comment]
@peterdaub Thanks for the report. What do you mean by your point `4` above being stuck? Also, it would help a lot, if you could provide a sample app where we could quickly reproduce the issue.

**Comment by peterdaub** [comment]
Hi @sobychacko, looks like I submitted this ticket a little early.  I was on release `spring-cloud-dependencies` version `2021.0.3` and `spring-cloud-stream-dependencies` version `3.2.9`.  When I upped spring cloud to `2021.0.8` the null function went away.  For the record here is the stack trace:

```
2023-12-13 13:53:33.928 -ERROR 1 --- [pool-5-thread-2] myproject.service.event.EventSender        : Unable to republish event: myProject.common.messaging.RabbitMessage@3f

java.lang.NullPointerException: Cannot invoke "java.util.function.Function.apply(Object)" because "functionToInvoke" is null
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:230)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:170)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:150)
```

Thanks for looking - but nothing to see here :-)
