### ISSUE TITLE
spring.cloud.stream.function.bindings property doesn't work as described in documentation

### ISSUE THREAD

**Issue by SimoneGiusso** [spring-cloud/spring-cloud-stream#2878]
In [Functional Composition](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html#functional-composition) section it is mentioned the following:

"_For example, if we want to give our `toUpperCase|wrapInQuotes` a more descriptive name we can do so with the following property `spring.cloud.stream.function.bindings.toUpperCase|wrapInQuotes-in-0=quotedUpperCaseInput`_"

However it seems that this property doesn't work. I have an example. This is the yaml [file](https://github.com/SimoneGiusso/spring-cloud-demo/blob/06ef08a1ed40b5cef6b383ad29baeae23d0d8b4a/src/main/resources/application.yml#L17). However when I try to use the name `uppercaseAndReverseInput` in this [test](https://github.com/SimoneGiusso/spring-cloud-demo/blob/06ef08a1ed40b5cef6b383ad29baeae23d0d8b4a/src/test/java/com/simonegiusso/stream/SeveralUseCasesTests.java#L49) it fails. 

I did different attempts but without positive results.

**Comment by sobychacko** [comment]
@SimoneGiusso It looks like you are adding the property under `spring.cloud.function.bindings...`, which is the incorrect level for that property. It should be under `spring.cloud.stream.function.bindings...` [here](https://github.com/SimoneGiusso/spring-cloud-demo/blob/06ef08a1ed40b5cef6b383ad29baeae23d0d8b4a/src/main/resources/application.yml#L11).
