### ISSUE TITLE
Authentication for module launcher remoteRepositories

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#288]
Module launcher supports `remoteRepositories` option as the comma separated values of remote maven repositories. If these repositories require authentication, then they need to be specified as option values.

One possible approach could be:

```
--remoteRepositories=repo1[url:<?>,username:<?>,password:<?>],repo2[...]
```
While `username` and `password` being the simplest authentication we can support initially.

**Comment by sabbyanandan** [comment]
Revisit this requirement once we have the core `spring-cloud-deployer` project in place.

**Comment by mbogoevici** [comment]
Obsolete - both fixed and module launcher moved.
