### ISSUE TITLE
Error creating bean with name 'errorChannel' because of ClassCastException occurred in BeanPostProcessor globalErrorChannelCustomizer

### ISSUE THREAD

**Issue by KirillMakrutin** [spring-cloud/spring-cloud-stream#2883]
If 'errorChannel' bean has a custom definition, for example of amqp PointToPointSubscribableAmqpChannel, then an application fails to start because of thrown java.lang.ClassCastException happens in BeanPostProcessor globalErrorChannelCustomizer in BindingServiceConfiguration auto-configuration.

**Actual behavior**: globalErrorChannelCustomizer doesn't verify if errorChannel bean is of PublishSubscribeChannel before casting object:
```
@Bean
public static BeanPostProcessor globalErrorChannelCustomizer() {
    return new BeanPostProcessor() {
        @Override
        public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
            if ("errorChannel".equals(beanName)) {
                ((PublishSubscribeChannel) bean).setIgnoreFailures(true);
            }
            return bean;
        }
    };
}
```

**Expected behavior**: errorChannel object type must be verified before doing any cast on it to avoid java.lang.ClassCastException on application startup. 

**Version of the framework**: tested on v.3.2.10, but this unsafe BeanPostProcessor declaration exist in main.

**Comment by sobychacko** [comment]
@KirillMakrutin Thanks for reporting this. It is now addressed on the `main` branch (`4.1.1-SNAPSHOT`) and backported to `4.0.x`.
