### ISSUE TITLE
Health indicators aren't working

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#289]
As a user, I'm trying to leverage `/health` endpoints exposed by stream (via Spring Boot), so I know when a binder or other components orchestrated by stream when it goes down; however, I'm unable to detect these scenarios with the exposed APIs.

**Comment by dsyer** [comment]
Sort of duplicate of #233

**Comment by sabbyanandan** [comment]
It is indeed. Closing this in favor of #233.
