### ISSUE TITLE
Delay in autoconfiguration of TestBinder

### ISSUE THREAD

**Issue by kutmk** [spring-cloud/spring-cloud-stream#2893]
With the update in #2566, it is no longer necessary to import `TestChannelBinderConfiguration` to use TestBinder.

However, if no message handler is registered (i.e., not defining Supplier/Consumer/Function), it seems that the autoconfiguration of `TestChannelBinderConfiguration` is delayed. In this case, the injection of `OutputDestination` fails. Therefore, it is still necessary to import it.
```java
@SpringBootTest
public class AppTest {
  @Autowired
  private OutputDestination outputDestination; // Injection failure
```
Log excerpt
```log
[ERROR] Errors:
[ERROR]   AppTest.test » UnsatisfiedDependency Error creating bean with name 'com.example.AppTest': Unsatisfied dependency expressed through field 'outputDestination': No qualifying bean of type 'org.springframework.cloud.stream.binder.test.OutputDestination' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```
Is this the intended behavior? Is it not possible to completely eliminate the import?

## Demo and workaround
[Demo and workaround](https://github.com/kutmk/spring-cloud-stream-test-binder-issue-demo): This demo intends to test an application that uses Test Binder, `StreamBridge`, and `OutputDestination` without registering a message handler.

## Environment
* Java 17
* Spring Boot 3.1.1
* Spring Cloud 2022.0.3
* Spring Cloud Stream 4.0.3

## Cause
The `TestChannelBinderConfiguration` is autoconfigured when `DefaultBinderFactory#initializeBinderContextSimple` is executed.

If a message handler is registered, this method is called before the injection of the test class's member variables due to `OutputBindingLifecycle` or `InputBindingLifecycle`.

However, if a message handler is not registered, this method is not called until during the application’s execution when a Binder is needed (such as during the execution of `StreamBridge#send`). As a result, the Bean is not created until then, and the injection fails.

**Comment by sobychacko** [comment]
@kutmk Your two workarounds are reasonable solutions when using `StreamBridge`. What is preventing you from going with those options? Ideally, you like to autoconfigure, but there are scenarios in which auto config may not work as in your case when using `StreamBridge`. A 3rd option is to use a fully self-contained test as many of [these tests](https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/StreamBridgeTests.java) do. We are open to suggestions if there is a valid use case to address this.

**Comment by kutmk** [comment]
@sobychacko 
Sorry for the late reply.  Thank you for suggesting the 3rd option.

Currently, the necessity for import is inconsistent and the conditions are complex.  I believe this could lead to confusion for users.
Therefore, if possible, I propose enabling the AutoConfiguration of the `TestChannelBinderConfiguration` class to ensure that the Bean is always created.

[Implementation of the proposal](https://github.com/kutmk/spring-cloud-stream/commit/4e5e0c9ba4470ba5336e9fde5e5283a20f5f874e)

**Comment by sobychacko** [comment]
Ok, that sounds good. Why don't you send that as a PR, and we will evaluate for any side effects?

**Comment by kutmk** [comment]
Of course, I will send a PR.

**Comment by sobychacko** [comment]
This has been addressed via https://github.com/spring-cloud/spring-cloud-stream/pull/2900.
