### ISSUE TITLE
Batched Stream Consumer contains KafkaNull objects inside a List

### ISSUE THREAD

**Issue by rishabh-agarwal792** [spring-cloud/spring-cloud-stream#2917]
**Description**
I am using version 3.2.3 of Spring Cloud Stream. I have created a batch consumer for a Kafka topic. The following Java code describes my consumer.

```
public Consumer<Message<List<Car>>> processCarStream() {
    return message -> {
      final List<Car> payload = message.getPayload();
      // ...
    };
  }
```
When a message with null payload is received, I get a KafkaNull object inside the payload list. As per my understanding, we should have never got a KafkaNull inside the payload List. 

Is this a bug with Spring Cloud Stream? 

**To Reproduce**
1. Create a batch consumer using spring cloud stream.
2. Send a single kafka message with null payload.
3. See KafkaNull objects in the payload list.

**Version of the framework**
Spring Cloud Stream : 3.2.3

**Expected behavior**
We should receive Nulls instead of KafkaNulls.

**Comment by sobychacko** [comment]
@rishabh-agarwal792 `3.2.3` is an older version that is out of regular OSS support. See the support timeline [here](https://spring.io/projects/spring-cloud-stream#support). 

We tried your issue with the latest version (`4.1.x`), and it works as expected. In batch mode, it correctly provides null elements for `KafkaNull` in the collection received on the consumer side. Similarly, it works for the type signature of `Consumer<List<Car>>`. Please try to upgrade to a later GA version and see if that takes care of the issue.
