### ISSUE TITLE
RabbitMQ: specifying a StreamBridge output-bindings entry fails when it is rabbit binding containing a routingKeyExpression

### ISSUE THREAD

**Issue by mjbingen** [spring-cloud/spring-cloud-stream#2921]
**Describe the issue**
When using `spring.cloud.stream.output-bindings` per [the documentation](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html#sending-arbitrary-data-to-an-output-e-g-foreign-event-driven-sources) to initialize the binding on startup, it works for all rabbitmq exchange types, until a `direct` or `topic` exchange type defines a routing key expression using `spring.cloud.stream.rabbit.bindings.<name>.producer.routingKeyExpression`.

When the routing key expression is defined, a `BeanCreationException` is thrown on startup:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'the-exchange_binding_out': Discovered 4 methods that would qualify as 'functional' - [public void org.springframework.cloud.stream.messaging.DirectWithAttributesChannel.setAttribute(java.lang.String,java.lang.Object), public java.lang.Object org.springframework.cloud.stream.messaging.DirectWithAttributesChannel.getAttribute(java.lang.String), public java.lang.String org.springframework.cloud.stream.messaging.DirectWithAttributesChannel.getBeanName(), public boolean org.springframework.cloud.stream.messaging.DirectWithAttributesChannel.subscribe(org.springframework.messaging.MessageHandler)].

**To Reproduce**
A simple reproducible example can be found here: https://github.com/mjbingen/spring-cloud-stream-sandbox

Example highlighting the problem:

application.yml
```
spring:
  cloud:
    stream:
      output-bindings: the-exchange
      rabbit:
        bindings:
          the-exchange:
            producer:
              exchangeType: direct
              routingKeyExpression: '''the.key'''
```

Simple code:
```
package com.mjb.spring.cloud;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.function.StreamBridge;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.time.OffsetDateTime;

@SpringBootApplication
@RestController
public class Main
{
    public static void main(String... args)
    {
        SpringApplication.run(Main.class, args);
    }

    @Autowired
    private StreamBridge streamBridge;

    @RequestMapping
    @ResponseStatus(HttpStatus.ACCEPTED)
    public String sendToBridge()
    {
        // Publish a timestamp
        final String now = OffsetDateTime.now().toString();
        streamBridge.send("the-exchange", now);
        return now;
    }
}
```

If either the `output-bindings` or `routingKeyExpression` entries are removed, the application will startup fine. However, the routing key must be defined in the file (especially for more complex topic exchanges) and it is preferred to create the bindings on startup and not the first time the StreamBridge is called.

**Version of the framework**
Spring Boot: 3.2.3
Spring Cloud Stream: 4.1.0
Spring Cloud Stream Binder Rabbit: 4.1.0

**Expected behavior**
Successful startup with bindings created on startup, prior to initial call to `StreamBridge.send` with the routing key properly formed by the routingKeyExpression.

**Additional context**
I searched through other bugs and tried things like `spring.cloud.stream.function.autodetect=false` but could not get passed the startup error when these two flags are used together.

**Comment by sobychacko** [comment]
@mjbingen Thanks for the sample app. We applied a fix for this issue. Please try it on the latest snapshot.

**Comment by mjbingen** [comment]
I tested with the latest 4.1.1-SNAPSHOT and confirmed the issue is fixed and the application is working as expected. Many thanks for the prompt action @sobychacko !
