### ISSUE TITLE
How to create consumers dynamically?

### ISSUE THREAD

**Issue by kqkdChen** [spring-cloud/spring-cloud-stream#2927]
I am developing a SaaS system. Each tenant has a different topic. When the tenant is created, I need to dynamically create the consumer corresponding to the tenant. How to achieve this?
The current usage is through functional programming, such as `Consumer` and `Function`. But these are all hardcoded, hardcoding obviously does not meet my needs

SpringCloud-Stream Version : 2020.0.3

**Comment by sobychacko** [comment]
@kqkdChen That's a very old version of Spring Cloud Stream that is out of OSS support. Have you considered using `StreamBridge` with the latest version of Spring Cloud Stream to achieve this use case? If you elaborate on your use case a bit more, we can consider coming up with some suggestions, but you need to upgrade to a supported version of Spring Cloud Stream. For the current support timelines, see [this](https://spring.io/projects/spring-cloud-stream#support).

**Comment by sobychacko** [comment]
@kqkdChen Closing the issue. If you are still looking for a solution, please feel free to re-open and add more context to your use case. Thanks!
