### ISSUE TITLE
Missing configuration metadata

### ISSUE THREAD

**Issue by jakub-bochenski** [spring-cloud/spring-cloud-stream#2930]
The following configuration properties are reported by IDEA as unresolved.
I can't find them in the metadata of relevant jar files.

```
spring.cloud.stream.default.binder
spring.cloud.stream.default.group
spring.cloud.stream.default.content-type
spring.cloud.stream.default.consumer.concurrency
```
spring-cloud-stream:3.2.9

**Comment by jakub-bochenski** [comment]
Also:
`spring.cloud.stream.function.definition`

**Comment by jakub-bochenski** [comment]
Still missing 
spring.cloud.stream.function.definition

**Comment by olegz** [comment]
The `spring.cloud.stream.function.definition` has been long deprecated. Use `spring.cloud.function.definition`
