### ISSUE TITLE
Docu for addGlobalStore is confusing (and isn't working for me)

### ISSUE THREAD

**Issue by Perry45** [spring-cloud/spring-cloud-stream#2933]
Hi everyone,

the first thing which is super strange is the deprecation in the docs:

In https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_kafka_streams_binder is stated:

> [3.14.1. Using Customizer to register a global state store](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_using_customizer_to_register_a_global_state_store)
> As mentioned above, the binder does not provide a first class way to register global state stores as a feature. For that, you need to use the customizer. Here is how that can be done.
> 
```
@Bean
public StreamsBuilderFactoryBeanCustomizer customizer() {
    return fb -> {
        try {
            final StreamsBuilder streamsBuilder = fb.getObject();
            streamsBuilder.addGlobalStore(...);
        }
        catch (Exception e) {

        }
    };
}
```
> 
> Again, if you have multiple processors, you want to attach the global state store to the right StreamsBuilder by filtering out the other StreamsBuilderFactoryBean objects using the application id as outlined above.
> 

But here https://docs.spring.io/spring-cloud-stream/reference/kafka/kafka-streams-binder/streamsbuilderfactorybean-customizer.html is stated:

> Using StreamsBuilderFactoryBeanConfigurer to register a global state store
> As mentioned above, the binder does not provide a first class way to register global state stores as a feature. For that, you need to use the customizer. Here is how that can be done.
> 
```
@Bean
public StreamsBuilderFactoryBeanConfigurer customizer() {
    return fb -> {
        try {
            final StreamsBuilder streamsBuilder = fb.getObject();
            streamsBuilder.addGlobalStore(...);
        }
        catch (Exception e) {

        }
    };
}
```
> Again, if you have multiple processors, you want to attach the global state store to the right StreamsBuilder by filtering out the other StreamsBuilderFactoryBean objects using the application id as outlined above.

Which Bean is now the correct one?

My problem is that I get an "org.springframework.beans.factory.FactoryBeanNotInitializedException: org.springframework.kafka.config.StreamsBuilderFactoryBean does not support circular references" when I use the BeanConfigurer, but the BeanCustomizer is not even invoked, so both ways are not functioning for me.

Actually, I could use:
@EnableKafka
@EnableKafkaStreams

Then the BeanCustomizer gets invoked, but then the KafkaStreamsDefaultConfiguration.DEFAULT_STREAMS_CONFIG_BEAN_NAME is used, and I have to override it. This means that I am actually using kafka-streams directly and not cloud-stream-binder-kafka-streams, if I understand that correctly. In other words, my application.yml config in the cloud-streams style is then not working.

My workaround is to use a BeanPostProcessor to register the store (https://github.com/spring-projects/spring-kafka/issues/981), but if this is indeed the correct way to do it, please state it clearly in the documentation.

Finally, I have to admit that I have only tested it with an EmbeddedKafka, so maybe it has to do with that. But in my opinion, it should function with it as well; otherwise, I have no chance to test it properly.

**To Reproduce**
Use spring-cloud-stream-binder-kafka, spring-cloud-stream-binder-kafka-streams, spring-kafka-test
Configure one Stream from A -> B
Try to register a GlobalStateStore for Topic B

**Version of the framework**
SpringBoot 3.2.4
spring-cloud-dependencies 2023.0.1
spring-kafka-test 3.1.3

**Expected behavior**
It should be possible to register a GlobalStateStore.

**Additional context**
Please tell me at least which of the beans should work, so that I can proceed and test in the correct way.

**Comment by sobychacko** [comment]
@Perry45 Thanks for the report. The second link is the correct one - `StreamsBuilderFactoryBeanConfigurer`. We had to deprecate and remove `StreamsBuilderFactoryBeanCustomizer` from Spring for Apache Kafka due to the existence of a similarly named class in Spring Boot. I'm not sure how you got to the first link. We no longer advertise that on the project page, so please use the second link. 

As to the issues you raised, do you have a small sample app where we could reproduce the issue? If not, please let us know, and we will go ahead and create one for testing. It would be quick if you could provide one. Thanks.

**Comment by Perry45** [comment]
@sobychacko 

Thanks for your quick response.

The incorrect link I reach through:

Google --> https://spring.io/projects/spring-cloud --(Sidemenu)--> https://spring.io/projects/spring-cloud-stream --(Learn)--> https://spring.io/projects/spring-cloud-stream#learn --RefDoc--> https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/ (4.0.5) --(Link)--> https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream-binder-kafka.html#_kafka_streams_binder

When I am accesing through the main menu from https://spring.io/projects/spring-cloud --> Learn it's correct, but the Learn link from  spring-cloud-stream is wrong.

Here is my small smple App:
[sample.zip](https://github.com/spring-cloud/spring-cloud-stream/files/14909676/sample.zip)

**Comment by sobychacko** [comment]
The `4.0.5` version will reference `StreamBuilderFactoryBeanCustomizer` as it was available in that version. As you noticed, we removed this reference in the latest versions. Thanks for the sample. I will take a look.

**Comment by sobychacko** [comment]
It turns out that invoking the `getObject()` from the `customize` method causes a circular dependency. You can use the `KafkaStreamsInfrastructureCustomizer` instead to set the global state store. I modified your code as below and the test passes then.
```
private static void registerGlobalStateStore(AsyncResultHandlerService asyncResultHandlerService, StreamsBuilderFactoryBean fb) {
      if (shouldAddGlobalStore(fb)) {
          try {
              var storeBuilder = Stores.keyValueStoreBuilder(
                      Stores.inMemoryKeyValueStore("global-store-name"),
                      Serdes.String(),
                      getDocumentDtoSerde()
              );

              fb.setInfrastructureCustomizer(new KafkaStreamsInfrastructureCustomizer() {
                  @Override
                  public void configureBuilder(StreamsBuilder builder) {
                      builder.addGlobalStore(
                              storeBuilder,
                              "result",
                              Consumed.with(Serdes.String(), getDocumentDtoSerde()),
                              () -> new GlobalStateStoreUpdater(asyncResultHandlerService)
                      );
                  }
              });

          } catch (Exception e) {
              throw new RuntimeException("Exception while setting up GlobalStateStore", e);
          }
      }
    }

    @Bean
    public StreamsBuilderFactoryBeanConfigurer customizer(AsyncResultHandlerService asyncResultHandlerService) {
        return fb -> registerGlobalStateStore(asyncResultHandlerService, fb);
    }

```

We definitely need to update those docs, but let us know if the above solution works for your scenario.

**Comment by Perry45** [comment]
@sobychacko 
Hey thanks again for your quick response, the solution you suggested is working fine for me.

**Comment by sobychacko** [comment]
@Perry45 Updated the docs to reflect the discussion above. Thanks for bringing this issue up.
