### ISSUE TITLE
Health Check for Binders Always Shows 'UNKNOWN' Status Due to Empty binderHealthContributors Map (Missing Bean Configuration for ReactorKafkaBinderHealthIndicator?)

### ISSUE THREAD

**Issue by hb12devtn** [spring-cloud/spring-cloud-stream#2948]
Hi, I encountered an issue while working with Spring Cloud Stream where the ReactorKafkaBinderHealthIndicator class is not being found. Upon further investigation, it appears that the health check for the binders is consistently showing "UNKNOWN" status. This is because the `binderHealthContributors` map within the `BindersHealthContributor` class is always empty, leading to the `obtainContributor` method returning the `UNKNOWN` health contributor. It seems that the binderHealthContributors map is not being populated with any health contributors, hence the health status remains "UNKNOWN" for the binders.

Here's the relevant code snippet from the `BindersHealthContributor` class:

```java
// Relevant code snippet from BindersHealthContributor class
private HealthContributor obtainContributor(Map<String, HealthContributor> binderHealthContributors) {
    if (binderHealthContributors.isEmpty()) {
        return UNKNOWN;
    }
    if (binderHealthContributors.size() == 1) {
        return binderHealthContributors.values().iterator().next();
    }
    return CompositeHealthContributor.fromMap(binderHealthContributors);
}
```

Steps to Reproduce:

1. Include Spring Cloud Stream and Reactor Kafka Binder dependencies.
2. Configure health checks for the binders.
3. Observe the health status for the binders.

Expected Behavior:

- The health check for the binders should accurately reflect the health status based on the availability of relevant health contributors.

Actual Behavior:

- The health status for the binders is consistently reported as "UNKNOWN" due to the binderHealthContributors map being empty.

Additional Information:

- Spring Cloud Stream version: 4.1.1
- Reactor Kafka Binder version: 4.1.1

**Comment by hb12devtn** [comment]
We can resolve this by adding a `ReactorKafkaBinderHealthIndicator` bean to  `ReactorKafkaBinderConfiguration`:

```java
@Bean
public ReactorKafkaBinderHealthIndicator reactorKafkaBinderHealthIndicator(ReactorKafkaBinder binder, ConsumerFactory<?, ?> cf) {
    return new ReactorKafkaBinderHealthIndicator(binder, cf);
}
```
Alternatively, we can create a separate configuration class, similar to KafkaBinderHealthIndicatorConfiguration, specifically for ReactorKafkaBinderHealthIndicator.

**Comment by sobychacko** [comment]
Thanks, @hb12devtn; we will look at this soon.
