### ISSUE TITLE
Deprecate `BindingServiceProperties#dynamicDestinations`

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#2955]
https://stackoverflow.com/questions/78561548/is-spring-cloud-stream-dynamicdestinations-still-a-valid-configuration-option

**Comment by olegz** [comment]
@sobychacko I think we should just remove it. If it is already not working what is the point of deprecating? We would have hear about it a while back, just like in the SO issue. wdyt?

**Comment by sobychacko** [comment]
Yes, thinking about it more, I think it makes sense to remove it altogether—no need to deprecate and wait.

**Comment by olegz** [comment]
I am keeping the `dynamicDestinationCacheSize` as it is still used by StreamBridge to maintain destination cache  map
