### ISSUE TITLE
Please rolldown the fix for 2796 to 4.0.x

### ISSUE THREAD

**Issue by avnersin** [spring-cloud/spring-cloud-stream#2963]
Please rolldown the fix for #2796 to a 4.0.x hotfix.
As far as we checked, the latest hotfix on this minor version (4.0.5) does not have this fix.
We need to provide this fix to a customer that cannot currently upgrade to 4.1.x.

**Comment by olegz** [comment]
4.0.x has been at  EOL (End-of-life) for a while now and in no longer supported as OSS. The latest version is actually 4.0.8 but is only available to commercial customers https://spring.io/projects/spring-cloud-stream#support. If your customer is a commercial Spring customer, have them issue a request thru proper channels.
