### ISSUE TITLE
Config property validation doesn't work for bindings that are only configured through default configs

### ISSUE THREAD

**Issue by Nephery** [spring-cloud/spring-cloud-stream#2974]
**Describe the issue**

If a binder has `@Validated` set on its `AbstractExtendedBindingProperties` implementation, then annotation-driven validation works as expected when bindings have **_at least one_** configs set through a binding-specific config option (i.e. `spring.cloud.stream.<binder-type>.bindings.<binding-name>.(consumer|producer).<property-name>`).

e.g.: Suppose `batch-max-size=0` in the following config is invalid (`@Min(1)`):

```shell
spring.cloud.stream.solace.bindings.my-input-binding.consumer.transacted=true
spring.cloud.stream.solace.default.consumer.batch-max-size=0
```

Then validation would successfully fail here, because there's at least one config explicitly referring to the binding, `my-input-binding`:

```java
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target com.solace.spring.cloud.stream.binder.properties.SolaceExtendedBindingProperties failed:

    Property: spring.cloud.stream.solace.bindings.my-input-binding.consumer.batchMaxSize
    Value: "0"
    Reason: must be greater than or equal to 1
```

But if the binding is configured **only** through default configs, then config validation doesn't work:

```shell
spring.cloud.stream.solace.default.consumer.transacted=true
spring.cloud.stream.solace.default.consumer.batch-max-size=0
```

In this config, `batch-max-size=0` isn't validated because there was no explicit configuration referring to `my-input-binding`.

**To Reproduce**
1. Add `@Validated` to a binder's `AbstractExtendedBindingProperties`, whose consumer or producer bindings has a constraint annotation like `@Min()`.
2. Configure the SCSt app's `application.yml` or `application.properties` to fail the constraint through a default binding config.
3. Notice that no validation error is thrown.

**Version of the framework**
Spring Boot: `3.3.1`
Spring Cloud: `2023.0.2`

**Expected behavior**
Expected validation to work when bindings are only configured through default values.

**Additional context**
Please tag as `[solace]`.

**Comment by olegz** [comment]
This is a bit tricky as it involves hierarchy of standard @ConfiguirationProperties and their extensions. The same problem is in Rabbit and Kafka, but I am close to figuring it out

**Comment by olegz** [comment]
Back-porting it to 4.1.x as well
