### ISSUE TITLE
StreamBridge is a singleton, and its send() method has performance issues.

### ISSUE THREAD

**Issue by imgoby** [spring-cloud/spring-cloud-stream#2976]
**Describe the issue**

During high concurrency, StreamBridge's send() calls are frequent, and the internal synchronization of send() prevents applications from fully utilizing the multi-core capabilities of the CPU.

**To Reproduce**
1. Run a application built Spring Cloud Stream and RocketMQ,Spring Cloud Stream Version:

```
   <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream</artifactId>
      <version>4.0.0</version>
    </dependency>
```

3. Message concurrency is 10000 messages per second
4. We can see : thread wait (blocked) in the StreamBridge's  send() method
![image](https://github.com/user-attachments/assets/d9d63fbc-bc6f-4483-a8ef-cece17c76cbc)

**Additional context**
I tried to increase the number of instances of StreamBridge through certain methods, and CPU usage began to rise. Concurrent performance improves.

So,I know :Default situation,StreamBridge is a singleton, and its send() method has performance issues.

Does spring cloud stream team know this issue? Can it be optimized?

**Comment by sobychacko** [comment]
@imgoby Thanks for the report. We will triage the issue and get back to you.

**Comment by olegz** [comment]
You can set it to async. `StreamBridge.setAsync()` and then your sends will be asynchronous

**Comment by olegz** [comment]
I am closing it as an answered question. If you still believe there is an issue please describe and more details and we'll reopen

**Comment by imgoby** [comment]
there is not setAsync() method in spring cloud 2022.

**Comment by olegz** [comment]
Please upgrade ;)

**Comment by imgoby** [comment]
OK,Thank you
