### ISSUE TITLE
Test Binder does not work with Spring Boot 3.3.2 any more

### ISSUE THREAD

**Issue by kschlesselmann** [spring-cloud/spring-cloud-stream#2988]
After upgrading to Spring Boot 3.3.2 it seems that the `OutputDestination` does not yield any messages but `null` any more. If I go back to SB 3.3.1 everything is fine again.

**Version of the framework**
 * Spring Boot 3.3.2
 * Spring Cloud 2023.0.3
 
**Additional context**
I found [this question on SO](https://stackoverflow.com/questions/78788350/failing-spring-boot-tests-with-testchannelbinderconfiguration-after-spring-boot) which seems to address the same issue.

**Comment by olegz** [comment]
Can you please provide a small sample? We have tests that are currently running so I am a bit surprised

**Comment by kschlesselmann** [comment]
@olegz Of course: https://github.com/kschlesselmann/spring-cloud-stream-2988

Just change the SB version to 3.3.1 to make the test pass.

**Comment by olegz** [comment]
Wondering if it is Kotlin specific. Just tried it with Java and all is good
