### ISSUE TITLE
SpEL Expressions in config does not handle non-string-like values

### ISSUE THREAD

**Issue by Nephery** [spring-cloud/spring-cloud-stream#2989]
**Describe the issue**
When the config has a SpEL expression which looks like a boolean or number (i.e. things that YAML doesn't automatically treat as a string), then applications will fail to startup with:

```java
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.stream.bindings.<binding-name>.producer.partition-key-expression' to org.springframework.expression.Expression:

    Property: spring.cloud.stream.bindings.producer.partition-key-expression
    Value: "true"
    Origin: class path resource [application.yml] - 84:18
    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Boolean] to type [org.springframework.expression.Expression]
```

**To Reproduce**
1. Use any config property declared with the type `Expression`, such as `spring.cloud.stream.bindings.<binding-name>.producer.partition-key-expression`.
    * Note: I'm using a yaml file for my config when I tested this.
    * Using `partition-key-expression` here just as a way to illustrate the problem. We're not actually using `partition-key-expression` to set number or boolean values, but a custom config property declared in the same way.
2. Set this config property with a boolean-like or number-like value, such as `true` or `5`. e.g.:
```yaml
spring:
  cloud:
    stream:
      bindings:
        <binding-name>:
          producer:
            partition-key-expression: 5  # must not be quoted in ""
```
3. Start app

**Version of the framework**
Spring boot: 3.3.2
Spring Cloud: 2023.0.3

**Expected behavior**
All values passed to expression-typed config options should automatically be treated as strings when converting them to `Expression`s.

My guess is that [SpelConverter](https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/SpelExpressionConverterConfiguration.java#L86) either needs to be updated to handle boolean and number types, or delegate to the `ConversionService` to convert any arbitrary value to a `String `before converting it to an `Expression`.

**Comment by olegz** [comment]
Well, by definition SPeL expression has to be expressed as string, so why did you expect it to work? I mean you can pass "true" and "5", right?

**Comment by Nephery** [comment]
You could, but other config options are coerced into strings if the config property's type was declared as a `String`. Without needing to wrap it in quotes. It'd be nice if properties declared as an `Expression` type were also coerced similarly.

**Comment by olegz** [comment]
Back-porting it to 4.1.x as well

**Comment by olegz** [comment]
@Nephery @Mrc0113 please test this with the latest snapshot 4.1 or 4.2 (as well as main) as i needed to refactor it a bit based on https://github.com/spring-cloud/spring-cloud-stream/pull/3081
All should work as you expect, and test proves it, but want to be extra careful

**Comment by Nephery** [comment]
Okay, I'll take it for a quick spin. Will let you know soon.

**Comment by Nephery** [comment]
@olegz confirmed that your fix still works. I tested it with the following values in an `application.yml`

* `"foo"`
  * Resolved from quoted String
* `foo`
  * Resolved from unquoted String
* `54`
  * Resolves from int
* `54.54`
  * Resolved from double
* `true`
  * Resolved from boolean
