### ISSUE TITLE
Discussion regarding the 'Fix the full names in shared.beans' pull request

### ISSUE THREAD

**Issue by omercelikceng** [spring-cloud/spring-cloud-stream#2992]
Hello,

I would like to discuss a few questions regarding this pull request. (https://github.com/spring-cloud/spring-cloud-stream/pull/2991)

1) The feature is present in version 3.2.x and continues to be available in the latest versions. (https://github.com/spring-cloud/spring-cloud-stream/commit/42a43af4c22674314a7b19dc6119232db1a10b13) However, the **paths** for the classes in **shared.beans** are **incorrect** for the **3.2.x** version. Will we make a development to fix this?
The versions where this issue exists are: **3.2.10, 3.2.9, 3.2.8, 3.2.7, 3.2.6**

2) I reviewed the related development to check for similar issues. This feature is present in the current **4.0.x, 4.1.x, and main** branches. The paths are correctly configured, so there are no issues. However, I could not find this feature in the **4.x** branch.  Should we add the related development to this branch as well?(**4.x**)

**Comment by SuperOranges** [comment]
Hello,
For the first point, i think we should make a development to fix it.
Based on the follwing reasons,
1. The feature was first released on the 3.2.6 version and it continues to now. This is a very convenient feature. I think it's very import to make this feature work normally in 3.2.x version.
2. In the 3.2.x version reference document,wo have explained the way to configure the config map used for consumer and producer properties. (https://docs.spring.io/spring-cloud-stream/docs/3.2.x/reference/html/spring-cloud-stream-binder-kafka.html#consumer-producer-config-customizer)
I think we should make the behaviour of the program consistent with the document.
3. In the 3.2.x version we can use jdk 1.8 but in the 4.0.x or 4.1.x version we need use jdk 17+. Although jdk 1.8 is no longer a long-term supported version,but there are still a lot of projects using it. 
If we can fix it,the maintainers of these projects（who still use jdk 1.8） can benefit from it and they don't have to develop a tool to realise this function.

**Comment by olegz** [comment]
Just an FYI, 3.2 is done. It is no longer a supported version - https://spring.io/projects/spring-cloud-stream#support so no more development or back-porting is planned for this outside of commercial efforts which are outside of scope of this discussion
