### ISSUE TITLE
stream bridge consumer class not consuming on 2023.0.3

### ISSUE THREAD

**Issue by SanzarRehman** [spring-cloud/spring-cloud-stream#2993]
**Describe the bug**
Serialization is not working on 2023.0.3 ,  same code working on 2023.0.2

**Sample**
Getting this error 

stream bridge consumer class [B cannot be cast to class com.b.notificatoin.client.SmsNotification ([B is in module java.base of loader 'bootstrap'; com.b.notificatoin.client.SmsNotification is in unnamed module of loader 'app')

` @Bean
  public Consumer<SmsNotification> sms() {
    return sms -> {
      log.debug("[SMS Consumer]: " + sms.getKey());
    };
  }`

**Comment by SanzarRehman** [comment]
similar issue found #2977 

`    @Bean
    public JsonMessageConverter customJsonMessageConverter(ObjectMapper objectMapper) {
        return new JsonMessageConverter(new JacksonMapper(objectMapper));
    }`  
    
    Working with this bean . There is nothing wrong with producer .

**Comment by olegz** [comment]
And if you read last comment on that issue,  that particular issue has been addressed and I am just waiting for the user to confirm so I can close it
That said, neither of the issues has anything to do with `StreamBridge`.
