### ISSUE TITLE
Null Payloads During Deserialization with Spring Cloud Stream Kafka

### ISSUE THREAD

**Issue by BernardoMatar** [spring-cloud/spring-cloud-stream#2994]
**Describe the bug**
Issue Description:

I am using Spring Cloud Stream with Kafka Stream functions and am encountering an issue where payloads are deserialized as null. I suspect this might be due to a configuration problem or an issue I have not yet identified. Here is the detailed behavior:
  
When processing messages through the Kafka stream function, I receive null payloads after deserialization.
Up until the SmartCompositeMessageConverter method fromMessage, the message attribute contains a GenericMessage with the complete payload according to the batch-size.
However, the conversion process fails, resulting in an empty list with no exceptions or error messages.
No exceptions are thrown during the deserialization process.

**Sample**
springBootVersion=2.7.18
org.springframework.cloud:spring-cloud-starter-stream-kafka:4.1.3'

![image](https://github.com/user-attachments/assets/20ce6db1-f0a2-4f00-81f1-1731cfb60578)

![image](https://github.com/user-attachments/assets/6bca3e48-3268-4e46-9bee-b7faaaad30c4)

![image](https://github.com/user-attachments/assets/66c15e30-328e-483e-8f09-4efaf3fbbd74)

![image](https://github.com/user-attachments/assets/7c089093-40a4-4a74-99a9-028bf89aa45e)

![image](https://github.com/user-attachments/assets/cf7fe6da-4f5b-4874-8aea-4c471e554ff5)

**Comment by BernardoMatar** [comment]
Additionally, when batch-mode=false, deserialization occurs as expected. Upon further debugging, I noticed that when batch-mode=false in the SmartCompositeMessageConverter class, within the method fromMessage(Message<?> message, Class<?> targetClass, @Nullable Object conversionHint), the code does not proceed through the iteration since the payload is not iterable. As a result, when it checks for any available converters, which also turns out not to be the case, the method ends up returning null.

However, when it does pass the if condition where the payload is recognized as iterable, it undergoes the same situation of searching for converters, and if none are found, the return value is different, becoming an empty list.

When control returns to the SimpleFunctionRegistry class in the convertInputIfNecessary method, it does not give ConversionService a chance because convertedInput is not null, but rather a list.size=0.

Outside of batch mode, the conversion is handled by the following code snippet, but in batch mode, this section is not executed. If, during batch mode, I force convertedInput to be null instead of an empty list, the expected result emerges.

if (convertedInput == null) { // give ConversionService a chance
    convertedInput = this.convertNonMessageInputIfNecessary(type, ((Message) input).getPayload(), false);
}


![image](https://github.com/user-attachments/assets/3945599b-d3f9-4d11-a1c8-90a3d39d207f)

**Comment by olegz** [comment]
Yes, this has been [reported already](https://github.com/spring-cloud/spring-cloud-function/issues/1174) and we have a solution, just need a bit more time to properly implement it as it will be a minor yet breaking change.
FWIW, the reason why conversion works differently when batch is set to false is because at that time the collection is converted as a whole instead of one message at a time which is also something we can probably improve on. . .
Stay tuned. . .

**Comment by olegz** [comment]
Related - https://github.com/spring-cloud/spring-cloud-stream/issues/2986

**Comment by olegz** [comment]
This was resolved via a series of commits ins spring-cloud-stream

5d881b2ad
29a355832
058fc660a
fac9eb1eb
14c10462f

As well as the commit in spring-cloud-function

https://github.com/spring-cloud/spring-cloud-function/commit/6dee668e3ec20710460b0384a8b6afe53d078633

It was alos back-ported to 4.1.x and will be available with the next release
