### ISSUE TITLE
How to create custom SCSM modules

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#301]
As a user, I'd like to refer to docs when developing custom `source`, `processor`, or `sink` applications, so I can develop by following the best practices.

**Acceptance:**
- reference guide include guidelines for each application type
- unit-testing section is included 
- troubleshooting techniques listed
- sample applications available for reference 

This could possibly evolve from [this](https://docs.google.com/document/d/1fAh4S-rN0i-lVwr0pIFE2L52CfQ2WZ7mKO-WiQ2VHtA/edit#heading=h.d68zgr59juff) document.

**Comment by mbogoevici** [comment]
I think we should move this to `spring-cloud-stream-app-starters`, as it is tightly coupled with that just now.

**Comment by mbogoevici** [comment]
@sabbyanandan - wdyt ?

**Comment by sabbyanandan** [comment]
Yep; makes sense. Moved it: spring-cloud/spring-cloud-stream-app-starters#16.
