### ISSUE TITLE
Allow setting TTL on Rabbit Queues

### ISSUE THREAD

**Issue by wwadge** [spring-cloud/spring-cloud-stream#302]
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java#L453

doesn't provide a way to set a TTL on queues to automatically expire messages; the RMQ key can be set as:
```
args.put("x-message-ttl", ttl);
```

though perhaps this can be cleaned up further to allow any additional map entry to be inserted?

**Comment by garyrussell** [comment]
@wwadge 

You can use a policy to set the TTL:

    $ rabbitmqctl set_policy scsttl "binder\..*" '{ "message-ttl" : 10000 }' --apply-to queues

**Comment by wwadge** [comment]
Thanks Gary, while that works it is an extra admin step that DevOps have to manage externally; we'd rather have everything property driven where necessary. It's also nice to be able to flip things for test profiles/debugging/etc (eg don't expire messages during debugging, expire them in production profile)

**Comment by garyrussell** [comment]
We could add a property to the binder but I think, to be completely useful, it would need to be overridable at the binding level - (in `spring-cloud-stream-dataflow` terms, as a deployment property).

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-rabbit#24
