### ISSUE TITLE
Kotlin compile dependency

### ISSUE THREAD

**Issue by PrzemyslawSwiderski** [spring-cloud/spring-cloud-stream#3020]
Hi, I am using `spring-cloud-stream` in Java project and noticed that since `3.2.5` it has Kotlin in compile dependencies. 
It is adding redundant Kotlin dependency to Java projects and can cause conflicts in Kotlin one. 

Is this proper behavior? I cant see Kotlin beeing used in this lib extensively. Shouldn't it have a test or optional scope?

**Comment by olegz** [comment]
You should not have it unless you are using it. Looking
