### ISSUE TITLE
Presence of Single Consumer is forcing other producers exposed under output-bindings property  to be treated as BindableFunctionProxyFactory bean with "functionExist" parameter set to TRUE, even when Streambridge is used instead of Supplier

### ISSUE THREAD

**Issue by Saumrit** [spring-cloud/spring-cloud-stream#3034]
In one of the microservice , i am having  one Producer, for which **StreamBridge** is used instead of Supplier and a consumer which is backed up by Consumer Functional interface. Because of the presence of only one consumer , i see the producer which is exposed under **spring.cloud.stream.output-bindings** application property , is registered as BindableFunctionProxyFactory bean with "functionExist" parameter set to TRUE .  [While debugging i see normalizeFunctionDefinition() from org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry is doing this explicitely when only one consumer is pressent]

- I was expecting this to be false since there is no Supplier backing it up for my producer. Now i am confused if its a BUG or any purpose is there behind it .
- What to do so that "functionExist" will set to FALSE for the producer in my case since i have only one consumer backed UP by Consumer interface and exposed under spring.cloud.function.definition property.
- Please let me know if in this scenario i should avoid output-bindings property.
- And what is the real use of output-bindings apart from pre-creating the bindings ? Is it mandatory to use when i go with Streambridge?

**Comment by corneil** [comment]
@Saumrit 
In this [project](https://github.com/spring-cloud/spring-cloud-dataflow-samples/blob/main/restaurant-stream-apps-3/README.adoc) we used named bindings and destinations only without output-bindings. If you are building a 'sink' then you have a consumer function that is bound to an input and it can use StreamBridge to send messages to multiple named bindings. This would be a type of router functionality.

So my questions are this: Are you building a source, processor or sink, that will bind to a producer, function or consumer?

**Comment by olegz** [comment]
We auto-detect function and create binding if there is only one, which seems to be the case for you. 
There are several ways to deal with that if that is not a desired behavior. The simplest one is to set `spring.cloud.stream.function.autodetect` property to false;

**Comment by Saumrit** [comment]
> We auto-detect function and create binding if there is only one, which seems to be the case for you. There are several ways to deal with that if that is not a desired behavior. The simplest one is to set `spring.cloud.stream.function.autodetect` property to false;

Actually in my case i have one Consumer[Backed by java.util.function.Consumer]  and several Producers [No Suppliers are here , i am using Streambridge instead] . Presence of this single consumer is forcing the auto provisioning of all these producer bindings and they are exposed under output-bindings property. 
During debug i found org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.normalizeFunctionDefinition() is responsible for this.  My question is in above scenario , i dont have my own Suppliers in class path , so why this is happening ?

**Comment by olegz** [comment]
Spring Cloud Function auto-discovered only one (single) bean of type `Consumer`, `Function` or `Supplier` in application context and gave it to s-c-stream

**Comment by Saumrit** [comment]
> Spring Cloud Function auto-discovered only one (single) bean of type `Consumer`, `Function` or `Supplier` in application context and gave it to s-c-stream
i have no Suppliers for those producer bindings , still this auto-provisioning is happening . I use Streambridge.

**Comment by olegz** [comment]
`Actually in my case i have one Consumer[Backed by java.util.function.Consumer]`. Is this not the case?

**Comment by Saumrit** [comment]
> `Actually in my case i have one Consumer[Backed by java.util.function.Consumer]`. Is this not the case?

yes , for  event consumer i have one java.util.function.Consumer and for Producers , i use
 streambridge.

**Comment by olegz** [comment]
So you have only one Consumer and because it's only one it is auto-discovered by s-c-function. StreamBridge has nothing to do with it as it is the artifact of s-c-stream

**Comment by Saumrit** [comment]
I am completely fine with the Consumer . My Problem is S-c-function is trying auto provisioning for those producer bindings which are exposed under output-bindings .

**Comment by olegz** [comment]
`auto provisioning for those producer bindings which are exposed under output-bindings ` - s-c function doesn't know what `binding` is, so I am lost as to what you are trying to say. 
Can you post some code or sample app to reproduce the issue you are repoprting?

**Comment by Saumrit** [comment]
My yml looks like this -:

Spring:
  cloud:
    function:
      definition: consumerinput
  stream:
    output-bindings: hardstopproducer
    bindings:
      consumerinput-in-0:
        group: team.queue.cit.user
        contentType: application/json
        binder: rabbit
      consumerretry:
        group: team.queue.cit.user
        destination: team.river.retry
        contentType: application/json
        binder: rabbit
      hardstopproducer:
        destination: team.river
        contentType: application/json
        binder: rabbit


issue i am getting -:
message":"Shutdown Signal: channel error; protocol method: #method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - configure access to exchange 'hardstopproducer' in vhost 'dev' refused for clinical 'hardstopproducer' In rabbitMQ user , access has been provides such that only this exchanges starting with "team" keyword will be allowed to created.

**Comment by olegz** [comment]
What is the issue? Why do you care about `BindableFunctionProxyFactory`? What exactly is not working for you?

**Comment by Saumrit** [comment]
I this my question needs to be reframed .
Meantime can you please let me  knw what this expression eligibleFunction.size() == 1 do in the 
org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.normalizeFunctionDefinition()
```
`String normalizeFunctionDefinition(String functionDefinition) {
        functionDefinition = StringUtils.hasText(functionDefinition) ? functionDefinition.replaceAll(",", "|") : System.getProperty("spring.cloud.function.definition", "");
        Set<String> names = this.getNames((Class)null);
        if (!names.contains(functionDefinition)) {
            List<String> eligibleFunction = (List)names.stream().filter((name) -> {
                return !"functionRouter".equals(name);
            }).filter((name) -> {
                return !"defaultMessageRoutingHandler".equals(name);
            }).collect(Collectors.toList());
            if (eligibleFunction.size() == 1 && !((String)eligibleFunction.get(0)).equals(functionDefinition) && !functionDefinition.contains("|") && !((String)eligibleFunction.get(0)).startsWith("&")) {
                functionDefinition = (String)eligibleFunction.get(0);
            }
        }

        return functionDefinition;
    }`
```

Because my issue comes in that if block whenever there is only one consumr.

**Comment by Saumrit** [comment]
@olegz  
Let me requote my issue -:
" I see the producer which is exposed under spring.cloud.stream.output-bindings application property , is registered as BindableFunctionProxyFactory bean with "functionExist" parameter set to TRUE .  I was expecting this to be false since there is no Supplier present in code , instead Streambridge i used."

Because of this in console i see this error eventhough this doesnot stop my app to function .
""Shutdown Signal: channel error; protocol method: #method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - configure access to exchange 'hardstopproducer' in vhost 'dev' refused for clinical 'hardstopproducer' In rabbitMQ user , access has been provides such that only this exchanges starting with "team" keyword will be allowed to created."

**Comment by olegz** [comment]
Please read [this section](https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html#sending-arbitrary-data-to-an-output-e-g-foreign-event-driven-sources). Specifically _However, if you want to pre-create an output binding at the initialization (startup) time you can benefit from spring.cloud.stream.output-bindings property_. That should answer your question about  why `is trying to create one exchange with the producer binding name i have provided under output-binding property .`
