### ISSUE TITLE
Publish source jars

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream#304]

**Comment by markpollack** [comment]
Check sct, scs-m sct-m also....

**Comment by dsyer** [comment]
Any project that inherits from spring-cloud-build will get sources (and javadocs) jars created automatically. The mvn deploy plugin also deploys them, but I guess if you aren't using that you might need to check. I can see they are in the milestone repo for this project at least.

**Comment by markpollack** [comment]
Yea, had an issue already, just didn't get to it.

**Comment by markpollack** [comment]
Maybe for snapshots. @nebhale mentioned they were missing

**Comment by nebhale** [comment]
As of `-149` (the one I was looking at on Feb 1) they weren't being published.  It appears that something changed with `-154` that they were.  [Repo listing](https://repo.spring.io/webapp/#/artifacts/browse//search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5Ijoic3ByaW5nLWNsb3VkLWRhdGFmbG93LW1vZHVsZS1kZXBsb3llci1zcGktMS4wLjAuQlVJTEQtMjAxNjAyKiIsInNlbGVjdGVkUmVwb3NpdG9yaWVzIjpbXX0=)

**Comment by dsyer** [comment]
Yeah looks like it got fixed to me. Maybe that PR that aligned all the poms with the other Cloud projects.
