### ISSUE TITLE
CloudEventMessageBuilder creates URI with surrounding quotes

### ISSUE THREAD

**Issue by kschlesselmann** [spring-cloud/spring-cloud-stream#3055]
Currently we're migrating some of our messages to Cloud Events. If we use
```kotlin
CloudEventMessageBuilder.withData(this)
        .setId(UUID.randomUUID().toString())
        .setSource("/my/source")
        .setSpecVersion("1.0")
        .setType("my.type")
        .setHeader(KafkaHeaders.KEY, myId)
        .build(CloudEventMessageUtils.KAFKA_ATTR_PREFIX)
```
the resulting message apparently has a header `ce_source="/my/source"` and other clients which validate the incoming messages fail with `"/my/source"` not being a valid URI.

If I just set the header myself using `.setHeader(CloudEventMessageUtils.SOURCE, "/my/source")` everything seems fine.

**Comment by olegz** [comment]
@kschlesselmann it is fixed. Please give it a shot and let me know before we do 4.2.1

**Comment by kschlesselmann** [comment]
@olegz Sure, which release should I try? Is the `BinderHeaderMapper` included in the reactive binder? I tried to upgrade to `org.springframework.cloud:spring-cloud-stream-binder-kafka-reactive:4.2.1-SNAPSHOT` but this doesn't seem to be enough.

**Comment by olegz** [comment]
You are too quick, since I believe the snapshot has not been generated yet. You can either build locally yourself OR wait few hours, but yes 4.2.1-SNAPSHOT would be what you are looking for

**Comment by olegz** [comment]
Actually I just noticed that the fix does not work with `spring-cloud-stream-binder-kafka-reactive` and looking at the code I am afraid that the header mapping and serialization is happening outside of the actual binder.
So I am reopening it and will dig some more to see if there is anything that can be done on our end

**Comment by olegz** [comment]
Good news, found the way to reuse the same `BinderHeaderMapper`, will push shortly

**Comment by kschlesselmann** [comment]
Awsome. Give me a ping and I'll build it on my machine :-)

**Comment by olegz** [comment]
@kschlesselmann give it a try. I tested with your app and it's working for me
