### ISSUE TITLE
Support function composition with Function, Consumer, and Supplier interfaces

### ISSUE THREAD

**Issue by x80486** [spring-cloud/spring-cloud-stream#3059]
## Description

I would like to propose an enhancement (if it could be called as such) to Spring Cloud Stream that will allow for function composition using classes that implement `Function`, `Consumer`, and `Supplier` interfaces, enabling a slightly more structured way to define pipelines/workflows.

Here is an example of what I'm trying to describe:

```java
@Component
public class InputSource implements Function<String, String> {
    @Override
    public String apply(final String message) {
        return message;
    }
}
```

```java
@Component
public class FilterFn implements Function<String, String> {
    @Override
    public String apply(final String message) {
        return message;
    }
}
```

```java
@Component
public class FlatMapFn implements Function<String, String> {
    @Override
    public String apply(final String message) {
        return message;
    }
}
```

```java
@Component
public class KafkaSink implements Consumer<String> {
    @Override
    public void accept(final String var1) {
        // Implement Sink behavior
    }
}
```

The pipeline/workflow will be composed with: `InputSource` > `FilterFn` > `FlatMapFn` > `KafkaSink`, similar to how `spring.cloud.function.definition` is currently used, but arguably more structured — or rather closely to how Apache Flink defines workloads.

**Comment by artembilan** [comment]
Would you mind to elaborate more how is this related to Spring Cloud Stream?
What you show is really just a core feature of Spring Cloud Function: https://docs.spring.io/spring-cloud-function/reference/spring-cloud-function/programming-model.html#function-composition.

If there is need in more than just functions in the workload, there is Spring Java DSL based on Spring Integration: https://docs.spring.io/spring-cloud-function/reference/spring-integration.html.
This also can be involved in the Spring Cloud Stream binding.

Recently we added a sample into Spring Functions Catalog which somehow reflects all the mentioned frameworks: https://github.com/spring-cloud/spring-functions-catalog/tree/main/samples/zip-split-rabbit-binder

Looking forward for more insight!
Thanks

**Comment by x80486** [comment]
I was under the impression that the composition was done with Cloud Stream.

I've recently begun learning Spring Cloud Stream, so I'm still getting familiar with the framework. Based on your comments, it seems this may be only relevant to Spring Cloud Function, as outlined in the documentation you shared.

The Spring Integration aspect is quite intriguing. Looks like a powerful way to handle more complex workflows, and somewhat resembles Apache Camel in its approach.

Thanks for your guidance! I will close the issue, and probably file it under Spring Cloud Function.

**Comment by olegz** [comment]
Spring Cloud Function is a programming model behind Spring Cloud Stream so, yes you can and encouraged to use function composition in spring-cloud-stream

```
spring.cloud.function.definition=foo|bar|baz
```

There you have just composed a single function from function `foo`, `bar` and `baz`
