### ISSUE TITLE
Add spring-cloud-stream-configuration-metadata to bom

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream#338]
Should be included as a dependency so it doesn't have to be added explicitly in dataflow (and I presume other consumers of stream).

Look for this issue name in https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-dependencies/pom.xml as an example.  

Related: https://github.com/spring-cloud/spring-cloud-dataflow/issues/384

**Comment by mbogoevici** [comment]
I am strongly in favour of including this into `spring-cloud-stream` core along with all the other autoconfiguration stuff, unless there are any strong objections around it. Or, alternatively, we should have a single place where we put all the additions that is required by SCDF modules.

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/commit/6691e63427177debed2ffa48391a6f07e85ff8db
