### ISSUE TITLE
Health indicator autowiring breaks existing apps

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#339]
This line in `DefaultBinderFactory` breaks existing apps (e.g. anyone using `@EnableDiscoveryClient`):

```
	@Autowired(required = false)
	public void setBindersHealthIndicator(CompositeHealthIndicator bindersHealthIndicator) {
		this.bindersHealthIndicator = bindersHealthIndicator;
	}
```

it is making a false assumption that the only bean of type `CompositeHealthIndicator` in the context is the one that belongs to the binders. I suggest maybe using a subclass instead, or a qualifier, to be more precise about the type.

**Comment by mbogoevici** [comment]
Probably a qualifier would be better.

**Comment by ilayaperumalg** [comment]
Actually, the setter method `setBindersHealthIndicator(CompositeHealthIndicator bindersHealthIndicator)` is sufficient enough to autowire the candidate bean with the **name** `bindersHealthIndicator` based on the method argument name as long as the bean of type `CompositeHealthIndicator` with the same name exists. This gets interesting when the health indicator is disabled via `management.health.binders.enabled` and thereby the `bindersHealthIndicator` bean is not instantiated. In this case, if there are any matching beans of the type `CompositeHealthIndicator` then those compete for the autowiring in the setter.

Also, the error from `spring-cloud-netflix` [issue] (https://github.com/spring-cloud/spring-cloud-netflix/issues/821) suggests the original `bindersHealthIndicator` bean is missing and that means the health indicator is `disabled`.  I assume that is the case in there as well. Please correct me if that is not the case.

Adding the qualifier does help when the health indicator is disabled and I have a test that demonstrates this in the PR shortly.

**Comment by chrisdadej** [comment]
@ilayaperumalg I posted 821 and can confirm that the health indicator is not disabled. Across my entire platform I use the out of the box management.health.* properties. If you can provide me with an RC1 build (if that's easy enough) I can easily test if this solves the problem although my guess is that if you added a Qualifier then everything should be fine.

**Comment by ilayaperumalg** [comment]
@chrisdadej yeah, thanks. I always thought the health indicator was disabled in that case (since the `bindersHealthIndicator` wasn't available as per your error log). Anyway, if it is possible you can test against the `snapshot` build as RC1 may take few days from now.

**Comment by chrisdadej** [comment]
Thanks @ilayaperumalg - happy to report that after switching both the Netflix and Cloud dependencies to the SNAPSHOT version this bug is now fixed. Thanks for both your and @dsyer 's help.

**Comment by ilayaperumalg** [comment]
Glad to know. Thank you for reporting and verifying as well :-)
