### ISSUE TITLE
TTL for messages from stream-cloud-binder-rabbit

### ISSUE THREAD

**Issue by herder** [spring-cloud/spring-cloud-stream#348]
`stream-cloud-binder-rabbit` seems to create queues which have no consumers, and with RabbitMQ this causes the broker to slow down and crash when the queue size grows too large. In my case, it's the `spring-cloud-starter-turbine-stream` which causes the massive queues, but the `springCloudBus` queues seem to have the same behaviour.

Without knowing too much about the implementation details, I think it would probably be a good idea to set a TTL on the messages which are streamed.

**Comment by garyrussell** [comment]
This is a known issue that will be resolved soon.

See https://github.com/spring-cloud/spring-cloud-stream/issues/317#issuecomment-182918369 for a workaround

**Comment by dsyer** [comment]
Thanks Gary

**Comment by herder** [comment]
Thanks!
