### ISSUE TITLE
Ignore the unsupported producer/consumer properties for the binder

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#355]
As a user, I would like to have the `ChannelBindingService` filters the unsupported producer/consumer properties that are passed along when binding the producer/consumer channel.

For instance, the `durableSubscription` consumer property is only supported for the `Rabbit` binder and when this property is set and the `Kafka` binder is used, then it needs to be filtered out.

**Comment by mbogoevici** [comment]
As discussed with @ilayaperumalg, I think we should have a class of properties that can be ignored safely by binders (e.g. `defaultConsumerGroups` or `durable` ).
