### ISSUE TITLE
Module launcher using excessive memory

### ISSUE THREAD

**Issue by bmann100** [spring-cloud/spring-cloud-stream#356]
I am unable to launch the time-source module with less than 512mb of memory.  When I run the module launcher locally launching the time-source module I see that the module launcher is allocating over 400mb.  We have written a bunch of custom modules, and are deploying them, but having to allocate 512mb to each of them is causing some scale issues.  Is this something that you have seen before?  I know on past versions I have run the time module on 128mb, but don't seem to be able to anymore.

**Comment by mbogoevici** [comment]
Hi,

What platform are you running the application on?

**Comment by bmann100** [comment]
We are running on kubernetes, but I am seeing the same behavior running locally from intellij

**Comment by bmann100** [comment]
I have a yourkit trace of the module launcher that I could send to you.

**Comment by markpollack** [comment]
The boot app itself for the time module should use minimal resources.  This small blog https://spring.io/blog/2015/12/10/spring-boot-memory-performance is a good read.  Will have to look into the module launcher a bit, but it will be going away (local deployer, CF, YARN) and being much thinner in what it does (only download an artifact if needed) k8s/marathon and provide a means to add (but not remove) a non transitive dependency (such as jdbc driver or jms client jar).   soon anyway so it might not be worth it... Too much classpath manipulation and hard to use in practice.  Eventually for docker based systems we will provide a docker image so there will be less intermediate layers and the arch will as close to 'running boot apps' as possible.

**Comment by markpollack** [comment]
Send away!

**Comment by bmann100** [comment]
It is pretty big, how would you like me to get it to you?  git will only allow up to 10mb.

How soon do you expect the launcher to be going away, and the new deployer/docker image to be available for testing?

**Comment by markpollack** [comment]
Launcher changes should be done via next release, so soon.  I think we will look into adding a mvn plugin to the OOTB modules/apps we provide once we get done with changes in https://github.com/spring-cloud/spring-cloud-stream-modules/issues/186 but not planning to start publishing those to dockerhub in the near term just yet as it was a fair bit of release/CI
overhead in our current setup ...

**Comment by markpollack** [comment]
I don't have any suggestions on where to upload it... Your own google drive/Dropbox account?  Will check around with folks on the support side.

**Comment by bmann100** [comment]
https://domo.box.com/s/ybhrqnq5qifaqgzm3lu3t6zjq0al8con

**Comment by markpollack** [comment]
Thanks

**Comment by bmann100** [comment]
<img width="764" alt="screen shot 2016-02-16 at 4 01 15 pm" src="https://cloud.githubusercontent.com/assets/8237096/13094216/95011388-d4c6-11e5-9daf-c5fbda30f62e.png">

**Comment by bmann100** [comment]
That trace that I sent you shows at one point the module launcher used 515mb of heap space.  Seems very high.
<img width="780" alt="screen shot 2016-02-16 at 4 42 31 pm" src="https://cloud.githubusercontent.com/assets/8237096/13095113/9395ec02-d4cc-11e5-80b0-ae60c27932e8.png">

**Comment by ilayaperumalg** [comment]
After some preliminary investigation, `ModuleLauncher` doesn't seem to have any issues. In fact, I see the same behaviour when launching the `time-source` exec as a standalone process.

I think the JVM requires some tuning. In this case, setting the `MaxHeapSize` to a optimal value seems to fix the issue and I believe the `MaxHeapSize` also impacts the heap size being used by the JVM.

On my local, in the following case,
```
java -jar target/time-source-1.0.0.BUILD-SNAPSHOT-exec.jar
```
the heap memory usage hits ~500MB but in this case, my `MaxHeapSize` is set to `~4GB`:
```
jinfo -flag MaxHeapSize <pid>
-XX:MaxHeapSize=4294967296
```
Similar behaviour when I run `time-source` via `ModuleLauncher` using the default `MaxHeapSize`.

After using a specific `MaxHeapSize` when starting the `time-source`:

```
java -Xmx32m -jar target/time-source-1.0.0.BUILD-SNAPSHOT-exec.jar
``` 
the heapsize hits ~28MB:
![screen shot 2016-02-17 at 3 43 07 pm](https://cloud.githubusercontent.com/assets/151690/13106259/461a2e68-d58d-11e5-82c9-d223573a049a.png)

For the module launcher:

```
java -Xmx64m -jar target/spring-cloud-stream-module-launcher-1.0.0.BUILD-SNAPSHOT.jar --modules=org.springframework.d.stream.module:time-source:jar:exec:1.0.0.BUILD-SNAPSHOT
```
the heapsize hits ~58MB

![screen shot 2016-02-17 at 3 46 21 pm](https://cloud.githubusercontent.com/assets/151690/13106329/a4d77e56-d58d-11e5-8605-5635bbdde5ad.png)

The [blog] (https://spring.io/blog/2015/12/10/spring-boot-memory-performance) Mark pointed out above has a lot more detail on turning/performance.

**Comment by sabbyanandan** [comment]
Hi @bmann100: Could you please verify @ilayaperumalg's analysis/recommendations and confirm your findings? We could then close this issue.

**Comment by bmann100** [comment]
Yes, that seems to resolve the issue running locally.  So we will likely need to modify the docker image for the module launcher to control the amount of memory that it is using in that environment.
