### ISSUE TITLE
Add support for command line args in AggregateBuilder

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#362]
Currenlty `AggregateApplication` has convenience methods accepting `String[]` arrays as module arguments. The API is a bit clumsy, and the builder is nicer, so it would be good to support it there, e.g. instead of

```
AggregateApplication.run(
	new Class<?>[] { TwitterStreamApplication.class, StreamTransformer.class },
	args, new String[][] { {"--language=en"}, {} });
```

we could write

```
new AggregateApplicationBuilder()
  .from(TwitterStreamApplication.class).args(new String[] {"--language=en"})
  .to(StreamTransformer.class)
  .run(args);
```

**Comment by mbogoevici** [comment]
Hi @dsyer,
Thanks for the suggestion - the API in the current form wasn't really meant to be final, so probably pre-RC1 is a good time to enhance.
