### ISSUE TITLE
Add 0.9 Kafka binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#373]
As a developer, I'd like to continue the work from #340, so I can adapt the existing SCSt-Kafka binder with 0.9 release of Apache Kafka.

**Acceptance:**
- SCSt-Kafka binder supports 0.9 release of Kafka
- 0.9 is the default version in [`pom.xml`](https://github.com/spring-cloud/spring-cloud-stream/blob/a854e986aa2fd3101bcc325f49376b131966d22f/spring-cloud-stream-binders/pom.xml#L18)
- I can build SCSM applications with SCSt-kafka as the binder 
- I can run `ticktock` stream with Kafka 0.9 running as messaging middleware 
- Unit tests included
- Docs updated

**Comment by mbogoevici** [comment]
Why can't we use the current Binder tests?

**Comment by mbogoevici** [comment]
We need to discuss backwards compatibility options for 0.8 too I believe.

**Comment by sabbyanandan** [comment]
Yeah, maybe we would be fine with existing tests, but chances are @garyrussell would want to add new tests, too. 

The backward compatibility is a whole different story though. Gary's thoughts below.

```
Gary Russell [9:47 AM] 
But I think Marius is planning to create the binder as a new project so there could be two binders; but I don’t know how long he would want to support that
Gary Russell [9:47 AM] 
The 0.9 client is sooooo much simpler, it makes no sense (from an SI perspective) to support both.
```

**Comment by mbogoevici** [comment]
Just to clarify: I do not feel we should support both in the same release. But there should be an option for users that are on 0.8 - even if that means moving out the 0.8 version post 1.1 (when it is the most likely we'll upgrade to 0.9).

**Comment by mbogoevici** [comment]
And for 1.0 we can provide a separate binder implementation that could be developed between the RC and GA timeline for 1.0 (also more lenient for dependencies, e.g using Mx releases of Spring Integration Kafka, which is typically a non-starter for RC releases).

**Comment by cdupuis** [comment]
@mbogoevici and @garyrussell what are the plans for this? Do you guys have any idea on timing on this?

Thanks, cd

**Comment by mbogoevici** [comment]
@cdupuis: Based on the current progress of Spring Kafka and Spring Integration Kafka 0.9, we will be able to provide a milestone that supports it in the next weeks with the goal of aligning Kafka 0.9 support in SCSt with the Spring Cloud Data Flow 1.0 release. 

Note that the current implementation still supports interacting with 0.9 brokers, but it uses the simple consumer API of 0.8.x (which is still compatible). The major goal of this is to get advantage of the new 0.9 client features, and especially of rebalancing and dynamic scaling of clients.

**Comment by mbogoevici** [comment]
To wit, the only blocker of some sorts is https://github.com/spring-projects/spring-kafka/issues/84 and we are positive that it will be solved soon.

**Comment by cdupuis** [comment]
Thanks @mbogoevici.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#2
