### ISSUE TITLE
Add IT tests for 0.9 SCSt-Kafka binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#374]
As a developer, I'd like to add IT tests for SCSt-Kafka binder, so I can evaluate the new simple consumer API (in Kafka 0.9) in the context of SCSt applications. 

This issue depends on spring-cloud/spring-cloud-stream#373

**Acceptance:**
- IT tests are available
- IT tests are included in CI test plans

**Comment by mbogoevici** [comment]
Can we clarify this? The current tests for the Kafka binder should apply to the upgraded version. If we introduce new features we should capture them as separate stories.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#3
