### ISSUE TITLE
Use TestBinder instead of real binder implementations in tests

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#380]
We need to rely on `TestBinder` for testing integration tests scenarios instead of using real binder implementations. For more info, see the discussion here:

https://github.com/spring-cloud/spring-cloud-stream/pull/371#discussion_r54257880

**Comment by ilayaperumalg** [comment]
It looks like `TestSupportBinder` may not be easier to use for the integration tests since the `TestSupportBinder` doesn't perform the **binding** of the consumer channels. For example, the existing integration test  `MessageConfigurerTests` requires the consumer binding to happen to test the type conversion at the consumer end. But, the `TestSupportBinder` doesn't bind the consumer channels. 

Does this mean we need to change the `TestSupportBinder` to perform binding of consumers as well?

Moreover, I think having some thing like a `Local`binder (the one we used to have) that extends `AbstractBinder` may be helpful.

**Comment by brvollino** [comment]
> Does this mean we need to change the TestSupportBinder to perform binding of consumers as well?
> Moreover, I think having some thing like a Localbinder (the one we used to have) that extends AbstractBinder may be helpful.

I was unable to create end-to-end tests for my app, because the TestSupportBinder doesn't register  consumers. Are there any plans to create something like a LocalBinder, as suggested by @sobychacko?

**Comment by mbogoevici** [comment]
@brvollino The `TestSupportBinder` supports sending messages to inbound channels so that it simulates the consumption of a message by a microservice. What would you like to test?

Please feel free to open a new issue with specific requirements.
