### ISSUE TITLE
CamelCase Vs. Hyphenated Properties

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#396]
In `spring-cloud-stream-binder-rabbit`, `META-INF/spring-configuration-metadata.json` contains:

    {
      "name": "spring.cloud.stream.binder.rabbit.default.auto-bind-dlq",
      "type": "java.lang.Boolean",
      "sourceType": "org.springframework.cloud.stream.binder.rabbit.config.RabbitBinderConfigurationProperties",
      "defaultValue": false
    },

But this property does not work, it has to be `spring.cloud.stream.binder.rabbit.default.autoBindDLQ`.

**Comment by mbogoevici** [comment]
Closed by changing property names.
