### ISSUE TITLE
Remove code in binders related to original use in Spring XD

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream#401]
In https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-binders/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/RabbitMessageChannelBinder.java#L469  there is code that creates a new classloader that was originally done to avoid errors such as https://jira.spring.io/browse/XD-2509

As there are not multiple classloaders in spring-cloud-stream's runtime, it is quite likely this code should be removed.

**Comment by mbogoevici** [comment]
Actually this is not necessary since it has been fixed in spring-amqp anyway.

**Comment by garyrussell** [comment]
I am going to remove this with #439
