### ISSUE TITLE
Allow binding properties for dynamic destinations

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#411]
Currently, any explicit `binding` properties specified for the dynamic destinations are not considered when binding the dynamic destination via BinderAwareChannelResolver.

**Comment by mbogoevici** [comment]
I suppose you mean we should use `BindableChannelFactory` here: https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/BinderAwareChannelResolver.java#L104 ?

**Comment by ilayaperumalg** [comment]
oh yeah, that is it :-) honestly, that didn't come to mind when I created the issue. thanks!

and, I hope all the binding properties are configured using the message channel configurers (via BindableChannelFactory) or handled appropriately (like the `group` property - though it doesn't belong here at least in this case where we are concerned about the producer).
