### ISSUE TITLE
Refactor core binder specifications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#412]
As a developer, I'd like to refactor code binder contracts, so it is better structured and easy to implement.

**Acceptance:**
- Improved test coverage for refactoring additions/changes
- Existing binder implementation tests run successfully

**Comment by mbogoevici** [comment]
Closed w/https://github.com/spring-cloud/spring-cloud-stream/commit/9b0c4bd627f7d122be60d11caf993b18799b3ae6
