### ISSUE TITLE
Is it possible to implement a one-to-many producer-consumer scenario

### ISSUE THREAD

**Issue by voor** [spring-cloud/spring-cloud-stream#429]
I've been following the project closely, since it compliments the Netflix aspect of Spring Cloud so nicely.  One of the things I was wondering is if there is a mechanism to publish the same message to multiple consumers following a more traditional event listener pattern.  What I was hoping to do is leverage the annotations in Spring Framework like `@JmsListener` except at the more scalable and configurable level of cloud-stream, also using services like Redis and Kafka instead of traditional JMS applications like ActiveMQ or Rabbit.  I realize Rabbit actually falls into that sweet spot where it's both JMS and featured in Cloud Stream, but then I lose Redis and Kafka -- so this is still a backup plan.

By default (correct me if I'm misunderstanding), when I have an `Input` only one of the `Output` will receive that event.  Is there a way to have one `Input` where every `Output` will still get the message?

**Comment by mbogoevici** [comment]
Hi @voor,

Thanks for the interest in the project!

Spring Cloud Stream applications are by default publish subscribe, with the option of participating in competing consumer scenarios via consumer group support, as described here: http://docs.spring.io/spring-cloud-stream/docs/1.0.0.M4/reference/htmlsingle/index.html#_consumer_group_support

(We'll do a better job of documenting this before RC).

Inputs and outputs are tied to external destinations, so you can have as many applications listening to the same external destination if you want to. One of the benefits of SCSt is that it decouples the application of the nature of the external provider, both in terms of logic, but also infrastructure (e.g. the actual Rabbit exchange being written to/listened to is configurable at runtime easily, and so on).

Hope this helps. Or do you have a use case that actually requires you writing to two different outputs from within the same application? Can you provide a bit more detail on that?

**Comment by voor** [comment]
Sure thing @mbogoevici and thanks for the quick response.

Here's a scenario:

1. An object is created in Service A, and we publish that to an Input (JSON message to object:created)
1. Service B receives JSON message object:created and stores that in an audit log
1. Service C receives JSON message object:created and notifies another service that indexes it for search
1. Service D receives JSON message object:created and performs some additiona business logic.

In the above scenario we have one producer (Service A) and many consumers (Service B, C, and D).  Each one of the services needs to get the message, and if only Service B got the message then C and D would fail to perform the necessary tasking.

In ActiveMQ, this would be considered a topic rather than a queue, but the definitions get a little mish-mashed in other implementations.

**Comment by voor** [comment]
I'm wondering if there's a solution that might leverage the service discovery found in Eureka to prevent the "byproduct" of this scenario, namely being that there may be dozens of instances of Service B, and you really only want one of those services to get the message.

Maybe if the `Input` was dynamically determined based on the number of "listeners" that were registered to Eureka in some sort of pattern (the most obvious one being the service has an ID that ends in listener).  Since if you reduce down the problem, it still needs to have Pub/Sub underneath it all.

**Comment by voor** [comment]
You know what, I just read https://spring.io/blog/2016/02/06/spring-cloud-stream-1-0-0-m4-is-now-available and I think that clarified my problem a little more.  So really, the scenario I described above is the **default** and if I wanted to implement multiple instances of Service B, I would need to declare them in a consumer group, as you pointed out is documented at http://docs.spring.io/spring-cloud-stream/docs/1.0.0.M4/reference/htmlsingle/index.html#_consumer_group_support

I'll get some sample code up, and play around with it.  It's all open source at https://github.com/SMARTRACTECHNOLOGY/smartcosmos-cluster at the moment.

I appreciate your help.
