### ISSUE TITLE
Support @StreamListener with PollableChannels

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#436]

**Comment by mbogoevici** [comment]
Based on the concerns raised on https://github.com/spring-cloud/spring-cloud-stream/pull/460#issuecomment-205041080 and discussing further with @garyrussell, it may not make sense to support this, along with the entire line of `PollableChannel` support for binding. The motivations are: a) risk of memory overuse and/or message loss; b) if the users need to buffer outgoing messages they can do it themselves inside the application; c) the main motivation around PollableChannel support is to allow applications to control the pace at which they consumer messages, we can do it much better with reactive support.

**Comment by mbogoevici** [comment]
Closed as we decided that this is a feature we do not want to support.

**Comment by nitishasgekar** [comment]
I am not sure this is the right place to bring up this issue . I was referring to the Spring Cloud Stream documentation http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_programming_model  and it says that it supports PollableChannel . You might want to correct the documentation.
