### ISSUE TITLE
JSON conversion on input channel doesn't work

### ISSUE THREAD

**Issue by MichalMichalak** [spring-cloud/spring-cloud-stream#443]
Hello. As per my question on stackoverflow, seems that JSON conversion does not work correctly. Could you please take a look and verify is there anything wrong with my example? Do I understood correctly how it should work and be configured?

http://stackoverflow.com/questions/36002199/spring-cloud-stream-message-json-conversion-is-not-working

Thank you
Mike

**Comment by ilayaperumalg** [comment]
Hi,

Are you using the latest master build snapshot? If so, you can try adding `StreamListener` annotation (that supports automatic argument mapping and type-conversion) in this case. More detail on this will be available in the doc soon.

For better understanding, you can refer [here] (https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/BindingListenerTests.java#L234)

**Comment by MichalMichalak** [comment]
Thank you, could you please check the link? It points to nowhere - 404.

**Comment by sabbyanandan** [comment]
@MichalMichalak: `BindingListenerTests` was recently renamed to `StreamListenerTests`. Here's an [example](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/config/StreamListenerTests.java#L234) for your reference.

**Comment by MichalMichalak** [comment]
I will look into it. Thank you.
