### ISSUE TITLE
Support embedding of OOTB applications

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#449]
As a developer, I want to be able to embed OOTB applications in my application, so that I can connect them together and enrich their behaviour.

NOTES: 
1. This can reuse the aggregation model for allowing developers to programmatically "push" channels to embedded modules. 
2. Investigate whether simply documenting the process with the current aggregation model is sufficient - e.g. can enrich by adding an additional `@Processor` to the application and creating an aggregate.

**Comment by PedroAlvarado** [comment]
An consideration during this work is to be able to have multiple "sources" in the aggregate application. 

Take for example the use-case of in-jvm data normalization. One can have two inputs(MessageChannels) each handled by a dedicated normalizer(MessageHandler) which in turn send the normalized messages to an output channel. 

AFAIK, currently, this use-case is satisfied by essentially defining **one custom app** with multiple input channels and one output channel. I'd be great to have these handlers be defined as standalone apps that user can choose to aggregate and run in-jvm("brokerless") or run them independently as standalone, clustered, and broker-based apps.

The whole idea of being able to define each discrete step in a "rich" pipeline as an app while being a able run them in an aggregate or distributed form is likely to be a major differentiator between SCS and, practically, the rest of the world(nifi, flume, etc).

**Comment by chrylis** [comment]
I'm in a startup, writing a modular message-driven application, and this is *exactly* the use case that would be killer for me.

**Comment by olegz** [comment]
This is something that I've done several times at clients and have a few ideas which I believe are at the code of this request

**Comment by olegz** [comment]
Closing it as we [can now do it with Spring Cloud Functions](https://spring.io/blog/2019/01/09/composed-function-support-in-spring-cloud-data-flow)
