### ISSUE TITLE
Default prefix property is not working anymore

### ISSUE THREAD

**Issue by MichalMichalak** [spring-cloud/spring-cloud-stream#455]
Very recently I noticed that default prefix is not working anymore.
I am using versions:

```
org.springframework.cloud:spring-cloud-stream:1.0.0.BUILD-SNAPSHOT
org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.BUILD-SNAPSHOT
```

Before when I set property `spring.cloud.stream.binder.rabbit.default.prefix=customprefix.` I could see in RabbitMQ exchange `customprefix.input` and queue `customprefix.input.default`. I haven't changed properties file but currently I see this names without prefix. Only `input` and `input.default`.

1. How do I set default prefix?
2. Can I override default prefix for one channel? How?

Thanks for any help
Mike

**Comment by ilayaperumalg** [comment]
Hi,

The default prefix is moved to be a `binding` specific producer/consumer property and hence it needs to be specified as `spring.cloud.stream.rabbit.bindings.<channelName>.consumer.prefix` or `spring.cloud.stream.rabbit.bindings.<channelName>.producer.prefix` based on whether the channel binding is for a producer or consumer.

This change is the result of major refactoring on introducing typesafe producer/consumer properties.
For more detail please refer the doc: https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc

Thanks

**Comment by MichalMichalak** [comment]
I double checked, it works nice. Thank you!
