### ISSUE TITLE
Make it clear that binding is only for SubscribableChannel (input) and MessageChannel (output)

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#469]
In initial versions of Spring Cloud Stream, we discussed about the possibility of supporting PollableChannels and kept the door open for it. This never materialized, as the binder implementations don't actually support it, but aggregation does. In the end, we do not intend to support PollableChannels directly (although SCSt users could bridge them to bound channels if necessary).

The intent of this would be to clean things up before 1.1.0.RC2.

**Comment by ilayaperumalg** [comment]
Given we only create a `DirectChannel` as the shared channel, we could drop the functionality that checks for `PollableChannel` from shared channel registry in AggregateApplication as well.

**Comment by ilayaperumalg** [comment]
Also, I think the title needs to change to `SubscribableChannel` for **output** and `MessageChannel` for **input** ?

**Comment by ilayaperumalg** [comment]
Also, I think the title needs to change to `SubscribableChannel` for **output** and `MessageChannel` for **input** ?
