### ISSUE TITLE
Add docs to guide with custom binder creation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#476]
As a user, I'd like to refer to docs while writing my own _binder_, so I can develop and test with a custom binder implementation based on best practices. 

**Acceptance:**
- step-by-step guide and best practices to create custom binder is available
- unit-testing infrastructure to test the binder implementation is included

**Comment by mbogoevici** [comment]
Providing a minimal explanation on how the Binder is structured for 1.0.0.GA, to follow up with a more detailed example in a future version.
