### ISSUE TITLE
Producer properties documentation is deprecated

### ISSUE THREAD

**Issue by urgelacko** [spring-cloud/spring-cloud-stream#477]
I have found that the "mode" property here is no longer working. Instead I had to use "headerMode" property to set raw headerMode.

http://docs.spring.io/spring-cloud-stream/docs/current-SNAPSHOT/reference/htmlsingle/#_producer_properties

**Comment by ilayaperumalg** [comment]
@urgelacko Thanks for reporting this. We recently changed the property name to `headerMode` and will update the documentation accordingly.
