### ISSUE TITLE
spring-cloud-starter-stream-kafka pulls log4j dependency

### ISSUE THREAD

**Issue by vkueffel** [spring-cloud/spring-cloud-stream#480]
I just started a spring-cloud-stream application and noticed that in 1.0.0.RC2 a dependency to log4j is being pulled, as a transitive dependency through zookeeper.

Here's my dependency tree:

```
[INFO] +- org.springframework.cloud:spring-cloud-starter-stream-kafka:jar:1.0.0.RC2:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-stream-binder-kafka:jar:1.0.0.RC2:compile
[INFO] |  |  +- org.apache.kafka:kafka_2.10:jar:0.8.2.2:compile
[INFO] |  |  |  +- org.apache.zookeeper:zookeeper:jar:3.4.6:compile
[INFO] |  |  |  |  +- log4j:log4j:jar:1.2.17:compile
```

Considering that spring-boot-starter-logging pulls log4j-over-slf4j that should probably be excluded.

**Comment by trisberg** [comment]
I noticed this too, added issue here -- https://github.com/spring-cloud/spring-cloud-stream-app-starters/issues/7

We might want to switch to slf4j/log4j instead of logback for the kafka starters.

**Comment by vkueffel** [comment]
Hm. The logging starter does a good job bridging all logging systems to a single one and decided on logback. Seems more consistent to not switch the kafka starters to log4j. I just added an exclusion to my POM and all works fine:

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
			<exclusions>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

Adding the exclusion directly in spring-cloud-starter-stream-kafka seems to be the simplest and most consistent option to me.

**Comment by trisberg** [comment]
I think you are right, simplest solution seems to be to exclude the log4j dependency. I thought the Zookeeper code would use log4j for its logging but I don't see any difference between logback and log4j logging.
