### ISSUE TITLE
MimeMessage and Kryo

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#488]
Track https://jira.spring.io/browse/INT-3994

See http://stackoverflow.com/questions/36663065/concurrentmodificationexception-while-using-spring-integration-dsl-mail/36664963#36664963

**Comment by mbogoevici** [comment]
@garyrussell Is there anything to do on the Spring Cloud Stream side for this?

**Comment by garyrussell** [comment]
Yes; we should update the mail source to use the new message mapping feature.

**Comment by mbogoevici** [comment]
I suppose we can move this to App Starters then.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-app-starters#258
