### ISSUE TITLE
Partitioning should be processed before serialization

### ISSUE THREAD

**Issue by gadams00** [spring-cloud/spring-cloud-stream#493]
I'm using s-c-s with kafka and have noticed that if you combine 
`s.c.s.bindings.<channel name>.content-type: application/json `
and 
`s.c.s.bindings.<channel name>.producer.partitionKeyExpression`
your partitionKeyExpression is applied after your pojo has already been transformed to json, so expressions like payload.getName() don't work. Is there a way to combine partitioning based on pojo expressions with the portability of json-encoded messages?

**Comment by mbogoevici** [comment]
Hi @gadams00,

Thanks for pointing that out. Ideally we should apply the partitioning logic before the conversion.

However, in your case  `partition.name` as an expression will work as of now (the expression is evaluated against the JSON). 

Cheers,
Marius

**Comment by gadams00** [comment]
You mean payload.name as s.c.s.bindings.\<channel name\>.producer.partitionKeyExpression? That seems to be working fine. Thanks.

**Comment by gadams00** [comment]
On second thought, I probably shouldn't have closed this, since mbogoevici indicated that it could be a potential enhancement at some point.

**Comment by mbogoevici** [comment]
Thanks @gadams00.

**Comment by mbogoevici** [comment]
One thing that we will want to do for 1.1.0.M1 is to ensure that the partitioning logic is applied before the final conversion - this will allow to use the partitioning logic on seralized POJOs (eg. Avro).

**Comment by ilayaperumalg** [comment]
This can be closed as the PR #589 addressed it.
