### ISSUE TITLE
Allow the registration of regular `MessageConverters` as beans

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#505]
Currently, all custom message converters must extend `AbstractFromMessageConverter` and must use the specific class of the bean or at least `AbstractFromMessageConverter` for being added to the configuration. This is inconvenient as it exposes too much implementation detail to the end user.

Proposed solution:

- allow the registration of ordinary `MessageConverter` beans and allow them to participate in the `StreamListener` argument conversion as well as bound message channel conversion (see below);
- introduce an extended interface e.g. `TargetTypeMessageConverter` to capture the additional contract of converters that can be added on the input and output channels, i.e. that they advertise specific target content-types and target classes - so only `MessageConverters` that are also `TargetTypeMessageConverters` can be used for setting up conversion on input and output channels;
- make `AbstractFromMessageConverter` a utility base implementation of `TargetTypeMessageConverter`;

**Comment by mbogoevici** [comment]
Reopening as this is a valid feature for 1.1.0.M1

**Comment by artembilan** [comment]
Pay attention to the `@IntegrationConverter` and the `IntegrationConverterInitializer` underneath on the matter. May be useful...

**Comment by mbogoevici** [comment]
Thanks :).
