### ISSUE TITLE
Support Spark and/or Storm?

### ISSUE THREAD

**Issue by abaculus** [spring-cloud/spring-cloud-stream#523]
Hi

Very interesting project indeed!

Is there any plan to support Spark or Storm?

BR, Andreas

**Comment by ilayaperumalg** [comment]
Hi,

We have an integration story with Spark (that is yet to be addressed): https://github.com/spring-cloud/spring-cloud-stream/issues/273 which will enable running the data transformation on Spark engine. This is similar to how Spring XD supports Spark.

Thanks!

**Comment by abaculus** [comment]
Nice!

What about Storm, any plans?

**Comment by mbogoevici** [comment]
Hi @abaculus,

Thanks for the interest! In what concerns Storm, we can interoperate with Storm applications but not necessarily integrate, as the functionalities are rather similar. Do you have anything in mind?

**Comment by abaculus** [comment]
Hi @mbogoevici,

Well, I'm a total newbie in this area so I guess my questions reflect that :-)

I'm asking since I've seen comparisons between Spark, Storm and Spring XD and since you're planning to support Spark, why not Storm?

But I guss that Storm and Spring Cloud Stream is more 1:1 than Spark and Spring Cloud Stream?

Would be nice to see a comparison between Spark, Storm, Flink, Samza, Spring Cloud Stream etc.

**Comment by sabbyanandan** [comment]
@abaculus: Storm and Spark do not directly compare with Spring Cloud Stream, but it does with Spring Cloud Data Flow in some capacity - see this [comparison](http://docs.spring.io/spring-cloud-dataflow/docs/1.1.0.M2/reference/htmlsingle/#arch-comparison) for more details. The general recommendation for users with this type of requirement is to integrate with external (storm/spark) clusters via a common messaging middleware such as Kafka.
