### ISSUE TITLE
Consumer group not working

### ISSUE THREAD

**Issue by wbauern** [spring-cloud/spring-cloud-stream#526]
I am trying out spring-cloud-stream and have created a simple producer and consumer apps on top of a locally running Kafka (v0.9.0.1).  Initially I was running two instance of my consumer app on two different ports without setting a group.  When my producer pushed a message to Kafka both instances of the consumer received the message successfully.  Now I am trying to run them in a single consumer group so only one instance processes each message.  I am setting the spring.cloud.stream.bindings.input.group property in the application.yml like the following:

`spring:
  cloud:
    stream:
      bindings: 
        input:
          destination: orders
          content-type: application/json
          group: shipping-group         
 `

However, both instances are still receiving a copy of each message.  I see the following in both instances' log files so it looks like the spring.cloud.stream.bindings.input.group property is being picked up correctly:

`2016-05-10 15:27:21.337  INFO 97540 --- [           main] o.s.c.s.b.k.KafkaMessageChannelBinder$7  : Adding {message-handler:inbound.orders.shipping-group} as a subscriber to the 'bridge.orders' channel
2016-05-10 15:27:21.338  INFO 97540 --- [           main] o.s.c.s.b.k.KafkaMessageChannelBinder$7  : started inbound.orders.shipping-group
`

I am checking the consumer groups in my Kafka like the following but don't see the consumer group "shipping-group" at all:

`kafka_2.11-0.9.0.1$ bin/kafka-consumer-groups.sh --zookeeper localhost:2181 --list
`

Am I missing anything to set this up correctly?

Thanks!

**Comment by mbogoevici** [comment]
Hi Bill,

You will need to set up the `instanceIndex` and `instanceCount` properties of the consumer application, as explained here:

http://docs.spring.io/spring-cloud-stream/docs/current-SNAPSHOT/reference/htmlsingle/#_instance_index_and_instance_count

(Also, you will need to have more than one partition on the topic). Version 1.0.0 of Spring Cloud Stream is using the 0.8.x client (with a Simple Consumer implementation) and requires additional information for the consumers to be able to split partitions correctly.

We will soon upgrade to the 0.9 client (http://docs.spring.io/spring-cloud-stream/docs/current-SNAPSHOT/reference/htmlsingle/#_instance_index_and_instance_count_) and that will provide automatic rebalancing.

**Comment by wbauern** [comment]
Thanks Marius that fixed my problem.  Looking forward to the 0.9 client support.

**Comment by mbogoevici** [comment]
Great, thanks for confirming. Will close this as it's not an issue per se.
