### ISSUE TITLE
Allow Binders to synchronize with a transaction manager

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#536]

**Comment by srnm** [comment]
#534 says to use @Transactional.

Perhaps allowing a user-defined PlatformTransactionManager should be discouraged / not supported?

**Comment by mbogoevici** [comment]
The goal is not to allow the injection in the container itself, as much as allowing some degree of synchronization with DB transactions at the binder level.

**Comment by mbogoevici** [comment]
The goal is to have one PlatformTransactionManager manage the transactions for all invocations (e.g. `@StreamListener` with conditional support).

**Comment by codependent** [comment]
Hi @mbogoevici, I just read that Spring Kafka 2.0.0 has gone GA and that it supports transactionallity and synchronization with a DataSourceTransactionManager. Are there any plans to support this in Spring Cloud Stream in the short run?

Regards

**Comment by artembilan** [comment]
There is a separate Kafka Binder build for the Apacha Kafka 0.11: https://spring.io/blog/2017/10/06/spring-cloud-stream-1-3-goes-ga#apache-kafka-0-11. This one is based on the Spring Kafka `1.3` and there is transactions support in that Binder already. See https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationProperties.java#L361 configuration properties.

**Comment by codependent** [comment]
Hi @artembilan , great to see it! I had already had a look at the [documentation](https://docs.spring.io/spring-cloud-stream/docs/Ditmars.RELEASE/reference/htmlsingle/) and since there isn't any reference to transaction configuration I thought it wasn't included.

My doubt is: with the new transaction support, can web have a method that writes in a database and sends a Message and rely on having both operations managed transactionally? Something like:

```
@Transactional
@SendTo(Source.OUTPUT)
public void createUser(User user){
   userRepository.save(user);
   return new UserCreatedEvent(user.getId())
}
```

**Comment by artembilan** [comment]
@codependent ,

Thank you for feedback!

Right, that should be. As far as your consumer and producer are Kafka Binder and transactions are enabled there. I still think you need `DataSourceTransactionManager`.

If something doesn't work, please, raise an issue in the [Kafka Binder](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka) project.

**Comment by codependent** [comment]
Thanks for your feedback! I've opened an issue suggesting an improvement in the documentation.

**Comment by olegz** [comment]
Closing it due to inactivity as well as it appears workarounds and improvements are suggested within dependent frameworks. In any event given that this issue is dated if anything it needs to be refreshed/reopened with the current context.
