### ISSUE TITLE
Kafka consumer binder gives error like "Failed to fetch consumer metadata from localhost:9092"

### ISSUE THREAD

**Issue by sandip0018** [spring-cloud/spring-cloud-stream#537]
Hi @sabbyanandan ,

When i try to use kafka binder for my sink module to get message from kafka i am facing below issue,
Failed to fetch consumer metadata from 
`kafka.client.ClientUtils$                : Failed to fetch consumer metadata from localhost:9092.`
I have done the all required configuration for this as i have debug i also found that error comes from below class `https://apache.googlesource.com/kafka/+/0.8.2/core/src/main/scala/kafka/client/ClientUtils.scala` line 160.

can you please see is there any specific configuration we have to do from spring side to avoid this issue?

Thanks

**Comment by mbogoevici** [comment]
hi @sandip0018,

Can you describe your configuration? 
What version of Kafka broker are you using?
 How is your application configured?
What version of Spring Cloud Stream?

**Comment by sandip0018** [comment]
Hi @mbogoevici ,

I have followed same configuration from below link
`https://blog.codecentric.de/en/2016/04/event-driven-microservices-spring-cloud-stream/`

kafka broker version 0.8.2.2
Spring cloud stream version is 1.0.0.RELEASE

Thanks,

**Comment by mbogoevici** [comment]
Looks like the broker is not accessible from the application. 

In the blog they use docker and have configured their brokers explicitly, but your error is referring to localhost, so I guess something is different. Do you have a broker running locally ? 

Could you post the configuration that you are using in the application?

**Comment by sandip0018** [comment]
`spring:
 cloud:
  stream:
   bindings:
    output:
     destination: mytopic
     content-type: application/json
    input:
     destination: mytopic
     content-type: application/json
   kafka:
    bindings:
     input:
      consumer:
       startOffset: latest
    binder:
     brokers: 'localhost9092'
     zkNodes: 'localhost:2181'
`

This is the configuration that i have done in application.yml file for kafka binder configuration.
Below is spring boot application java class from where i am executing code.

`@SpringBootApplication
@EnableBinding(KafkaInputOutPut.class)
public class KafkaSourceStreamApplication {

	private static Logger logger = LoggerFactory.getLogger(KafkaSourceStreamApplication.class);

	public static void main(String[] args) {
		SpringApplication.run(KafkaSourceStreamApplication.class, args);
	}

	@Bean
	@InboundChannelAdapter(value = KafkaInputOutPut.OUTPUT, poller = @Poller(fixedDelay = "10000", maxMessagesPerPoll = "1"))
	public MessageSource<TimeInfo> timerMessageSource() {
		logger.info("Producing Message");
		return () -> MessageBuilder.withPayload(new TimeInfo(new Date().getTime()+"","Label")).build();
	}

	@StreamListener(KafkaInputOutPut.INPUT)
	public void loggerSink(SinkTimeInfo sinkTimeInfo) {
		logger.info("Received: " + sinkTimeInfo.toString());
	}

	public static class TimeInfo {

		private String time;
		private String label;

		public TimeInfo(String time, String label) {
			super();
			this.time = time;
			this.label = label;
		}

		public String getTime() {
			return time;
		}

		public String getLabel() {
			return label;
		}

	}

	public static class SinkTimeInfo{

		private String time;
		private String label;

		public String getTime() {
			return time;
		}

		public void setTime(String time) {
			this.time = time;
		}

		public void setSinkLabel(String label) {
			this.label = label;
		}

		public String getLabel() {
			return label;
		}

		@Override
		public String toString() {
			return "SinkTimeInfo [time=" + time + ", label=" + label + "]";
		}

	}
}`

`main] kafka.client.ClientUtils$                : Failed to fetch consumer metadata from localhost:9092.`

Above is the error that i am facing.

**Comment by ilayaperumalg** [comment]
Hi @sandip0018 

Thanks for trying Spring Cloud Stream. Can you send your configuration properties with appropriate spaces (as in YAML) so that we can check if those look ok.

It looks like a host name resolution issue. I noticed that your property for `spring.cloud.stream.kafka.binder.brokers` points to `localhost9092` (without **colon**). Is that indeed your broker host name or a typo?

**Comment by sandip0018** [comment]
![application yml](https://cloud.githubusercontent.com/assets/7183797/15285293/dbb797fe-1b73-11e6-8700-fc99499fd3a6.PNG)

**Comment by sandip0018** [comment]
Hi @ilayaperumalg ,
i have come to know that it internally using `KafkaNativeOffsetManager` for offset management, can we configure different offset manager like `MetadataStoreOffsetManager` or `KafkaTopicOffsetManager` in spring cloud stream kafka binder?

**Comment by ilayaperumalg** [comment]
@sandip0018 yeah, the offset manager is not configurable with the Kafka binder. But you can change it to use a different offset manager by changing the offset manager on the existing `KafkaMessageChannelBinder` code and use that binder implementation. But, I think there were some reasons for sticking to the `native` offset manager and moving away from other offset managers. You might be interested in reading this thread: https://github.com/spring-projects/spring-integration-kafka/pull/58

**Comment by ilayaperumalg** [comment]
@sandip0018 For your configuration properties, what happens when you try the property values without `quotes`? In fact, you don't need to specify them as you are using the default values here.
```
spring:
  cloud:
    stream:
       kafka:
           binder:
              brokers: localhost:9092
              zkNodes: localhost:2181
```

**Comment by sandip0018** [comment]
I am able to post message to kafka, but just issue is with consuming message, that i think due to kafkaNativeOffsetManager, and also when i try to run kafka with 0.8.1.1 version, it give me error like `java.lang.NoSuchMethodError: kafka.client.ClientUtils$.channelToOffsetManager`

**Comment by ilayaperumalg** [comment]
ok, I am using `0.8.2.1` and am able to produce/consume messages to/from Kafka topics.

**Comment by sandip0018** [comment]
![kafka_version_on_server](https://cloud.githubusercontent.com/assets/7183797/15286765/7682e358-1b7c-11e6-8471-3b90579188ce.PNG)


on server we have above kafka version so which version i have to use from maven?, currently i am using 0.8.1.1

**Comment by sandip0018** [comment]
@ilayaperumalg is it possible like older version of kafka like 0.8.1.1 is not supported with kafka binder available in spring cloud stream ?

**Comment by ilayaperumalg** [comment]
@sandip0018 I see the issue when using `0.8.1.1` with the Kafka native offset manager. Given, with  `0.8.1.1` Kafka consumers commit their offsets into ZooKeeper instead of committing into a `Kafka topic`, there will ve problem supporting older version like `0.8.1.1` with the native offset manager. Now I see the reason why you asked for a `pluggable` offset manager in this case. @mbogoevici what do you think would be our options here?

**Comment by sandip0018** [comment]
i think version is the reason for getting "Failed to fetch consumer metadata from localhost:9092" exception.

**Comment by ilayaperumalg** [comment]
Yeah, I ran into the same issue after switching to `0.8.1.1`.

**Comment by mbogoevici** [comment]
Unfortunately, we do not intend to support `0.8.1.x` officially in general, but we could allow an option for providing your own offset manager in the future (not sure how much that would matter outside the context of 0.8.1.x)

**Comment by sandip0018** [comment]
@mbogoevici  is there any other way by which we can create stream in s-c-s which will read data from kafka?

**Comment by mbogoevici** [comment]
@sandip0018 Not sure I understand the question all too well, but you need a binder, and the current one is not compatible with `0.8.1.1`. One option would be to upgrade Kafka (which is probably not a bad idea, given the improvements of 0.8.2 and 0.9), or you could try using a different offset manager - would welcome a contribution for being able to switch the offset manager, actually (an option that we had for Spring XD, but we delauyed on as we moved forward). All I am saying is that if there are other issues due to incompatibilities with `0.8.1.1` besides saving offsets, it would be hard to retrofit - especially as we are moving forward.

**Comment by mbogoevici** [comment]
Closing as this is related to 0.8.1.1 (which we do not support).
