### ISSUE TITLE
Bindings should provide the option of sending exceptions directly to `errorChannel`

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#538]
Currently, the failover strategy is to republish failed messages to DLQ and potentially log the error message (or add it to the header). 

It would be more consistent if bindings had an option to publish exceptions thrown during message handling to the error channel. 

See http://stackoverflow.com/questions/37215072/spring-cloud-stream-serviceactivator-not-messaging-to-errorchannel-on-exception for a potential use case.

**Comment by PedroAlvarado** [comment]
@mbogoevici We have a use case where in the case of an exception we need to increase some metric counters that are dependent on the dynamic contents of the "dead" messages(e.g. message.dropped.[customKeyFromMessage]++). 

Can help us understand/point-to how we may be able to implement such a thing.

**Comment by dopeymac** [comment]
We would also like to send all thrown exceptions to the default error channel. Additionally, we'd like to be able to have an option to intercept that exception with the message and apply our own error handling business logic

**Comment by mbogoevici** [comment]
@PedroAlvarado @dopeymac Thanks for the input - we're currently evaluating options for including this as part of Chelsea.SR1 - we're going to update these issues shortly.

**Comment by PedroAlvarado** [comment]
@mbogoevici Thanks for the news. We'd be happy to provide feedback on any API changes and/or test out snapshot builds against our use-cases.

**Comment by mbogoevici** [comment]
Thanks @PedroAlvarado !

**Comment by mbogoevici** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-stream/issues/913
