### ISSUE TITLE
Kafka Binder Gives All Dispatcher Threads the Same Name

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#543]
http://stackoverflow.com/questions/37283637/spring-cloud-string-1-0-0release-and-threads

```java
	private static class DaemonThreadFactory implements ThreadFactory {

		@Override
		public Thread newThread(Runnable r) {
			Thread thread = new Thread(r, "kafka-binder-");
			thread.setDaemon(true);
			return thread;
		}
	}
```

**Comment by garyrussell** [comment]
@mbogoevici I think this should be fixed in 1.0.1 - without it, debugging will be nightmarish.

**Comment by mbogoevici** [comment]
Yeah, it will need to be cherry-picked :/ GitHub doesn't support multiple milestone tags.

**Comment by garyrussell** [comment]
Ah, sorry - did not know that.

**Comment by mbogoevici** [comment]
My fault though - we need to find a way to mark items for backporting though - maybe a special label.
