### ISSUE TITLE
Suggested change in documentation for 2.4 Consumer Groups

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream#551]
This is a suggestion based on my own awkward experience, my bad obviously:

I have started using Spring Cloud Stream recently and struggled to configure a consumer group following the (first chapters of the) documentation.

The point is that instead of using the standard Source and Input interfaces I defined my own:

	public interface LogSource{
		String OUTPUT = "logMessages";
		@Output(LogSource.OUTPUT)
		MessageChannel output();
	}

	public interface LogSink {
		String INPUT = "logMessages";
		@Input(LogSink.INPUT)
		SubscribableChannel input();
	}

The documentation states:

> Each consumer binding can use the `spring.cloud.stream.bindings.input.group` property to specify a group name.

I wanted to create a consumer group called `logProcessor`, so I set up:
```
spring:
  cloud:
    stream:
      bindings:
        input:
          group: logProcessor
```
The problem is that this way both instances of the consumer got the messages, that is to say, the group wasn't working.

After the initial "what the...?" stage I came up with the idea of replacing `input` with logMessages in my config and it solved it:

`spring.cloud.stream.bindings.logMessages.group=logProcessor`
instead of 
`spring.cloud.stream.bindings.input.group=logProcessor`

Later I found that in `5.2 Binding Properties` it is correctly defined how to use those properties. Maybe eager people like me wouldn't have a headache if 2.4 were like this: 

> Each consumer binding can use the `spring.cloud.stream.bindings.<channelName>.group` property to specify a group name.

Just a suggestion ;-)

**Comment by ilayaperumalg** [comment]
Hi @codependent 

Thank you for reporting. This is indeed a good suggestion!
Pushed the PR https://github.com/spring-cloud/spring-cloud-stream/pull/552 to fix this along with few other places to clarify channel names better.

**Comment by codependent** [comment]
Great! I'm glad it helped.

**Comment by mbogoevici** [comment]
Thanks for reporting the doc issue, @codependent! Looking forward for more contributions :)

(As a note, for issues that have PRs against, we typically close the issue when the PR is merged, so I will reopen this for now)
