### ISSUE TITLE
Align checkstyle rules with other Spring Cloud projects

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#565]
It would be good to have some agreement between Cloud projects about checkstyle. We already have some rules defined in spring-cloud-build-tools, and used, for instance in spring-cloud-sleuth. They look less strict than the ones used here. However when I tried to apply them I got build failures, so I'm wondering if the rules we have here are actually being applied.

There's also a problem with the configuration of checkstyle plugin using `src/main/...` as a config location: you can't build stream as part of a reactor build, nor can you build sub-projects on their own because the config files are not found (e.g. `$ (cd spring-cloud-stream; mvn install)` fails).

**Comment by dsyer** [comment]
PR #556 (do not merge - there are still 8 rule violations)

**Comment by mbogoevici** [comment]
The rules are definitely applied (if you try violating them). 

Before reformatting the project again: I'd prefer to keep the current rules, which are essentially based on Boot rules and wrap them into an artifact so that building can work.

**Comment by mbogoevici** [comment]
The differences between that you see are due to different versions of Puppycrawl being used (we're forcing 6.17 which we got from Boot which is by default more lenient around this and imports in JavaDoc). That's an easy fix.

**Comment by mbogoevici** [comment]
Actually, we might want to use a different version than `6.17` anyway, as it seems to have issues around static fields (i.e. setting `validateOnlyOverlapping` to `false` will report `this.CONSTANT` as required, which is bad). So, I'm ok with using the version the plugin provides.
