### ISSUE TITLE
Move Kafka binder to its own repo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#568]
As a developer, I'd like to move the Kafka binder project to `spring-cloud-stream-binder-kafka` repo.

**Comment by ericbottard** [comment]
Contents is to be taken from https://github.com/spring-cloud/spring-cloud-stream/pull/561

**Comment by sabbyanandan** [comment]
Depends on spring-cloud/spring-cloud-stream#546
