### ISSUE TITLE
http://docs.spring.io/spring-cloud-stream/docs/current/ points to 1.0.0.RC3

### ISSUE THREAD

**Issue by maxromanovsky** [spring-cloud/spring-cloud-stream#572]
http://docs.spring.io/spring-cloud-stream/docs/current/ points to `1.0.0.RC3`, not to the current stable release (`1.0.2.RELEASE` at time I've posted an issue)

**Comment by mbogoevici** [comment]
Thanks Max,

We'll correct this!

**Comment by mbogoevici** [comment]
Corrected now, thanks for bringing it up!
