### ISSUE TITLE
Manual Acknowledgement of messages in Kafka using Spring cloud stream

### ISSUE THREAD

**Issue by vsrahul82** [spring-cloud/spring-cloud-stream#575]
The scenario i want to implement is consume a message from Kafka , process it, if some condition fails i do not wish to acknowledge the message. For this i found in the spring cloud stream reference documentation,

autoCommitOffset Whether to autocommit offsets when a message has been processed. If set to false, an Acknowledgment header will be available in the message headers for late acknowledgment.

Default: true.

My question is after setting autoCommitOffset to false, how can i acknowledge a message? A Code example would be hugely appreciated.

**Comment by mbogoevici** [comment]
Thanks for asking the question - will add an example for that shortly.

**Comment by mbogoevici** [comment]
You can take a Sink example and add:

```
spring.cloud.stream.kafka.bindings.input.consumer.autoCommitOffset=false
```

Then in the code:

```
@SpringBootApplication
@EnableBinding(Sink.class)
public class ManuallyAcknowdledgingConsumer {

	public static void main(String[] args) {
		SpringApplication.run(ManuallyAcknowdledgingConsumer.class, args);
	}

	@StreamListener(Sink.INPUT)
	public void process(Message<?> message) {
		System.out.println(message.getPayload());
		Acknowledgment acknowledgment = message.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class);
		if (acknowledgment != null) {
			System.out.println("Acknowledgment provided");
			acknowledgment.acknowledge();
		}
	}
}
```
(And different variations using `@ServiceActivator` or `@Payload` for example). The idea is that the ack is provided as part of the message header.

Do note that Kafka does not provide individual message acking, which means that acknowledgment translates into updating the latest consumed offset to the offset of the acked message (per topic/partition). That means that if you're acking messages from the same topic partition out of order, a message can 'ack' all the messages before it.

**Comment by vsrahul82** [comment]
That example will solve my problem. Once again Marius u saved my soul. Dont know how to thank you. Appreciate it bro..

**Comment by vsrahul82** [comment]
Marius. please share the import statements to know the API of the acknowledgement class. Wanted to see if there is a method for not acknowleding a message

**Comment by mbogoevici** [comment]
The fully qualified name of `Acknowledgment` is `org.springframework.integration.kafka.listener.Acknowledgment`.

There is no method for rejecting (not acknowledging) a message. If you're disabling automatic acknowledgment and you're not acknowledging messages, the consumer will not update the consumed offset . See my comment above about the semantics of acknowledgment.

**Comment by mbogoevici** [comment]
Closing this as there's no actionable item.

**Comment by cernerpradeep** [comment]
How should we do if we writing to kafka instead of reading. For instance:
processor.output().send(message);
How to get ack for writes to kafka.

**Comment by olegz** [comment]
@cernerpradeep please do not ask questions using this issue (especially on closed/resolved issues) tracker which is only for issues.
