### ISSUE TITLE
Clarify that when multiple binders are used, autoconfiguration needs to be disabled

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#584]
This applies to the Rabbit example, where we use two separate binders. If not disabled, Rabbit autoconfiguration will be triggered since Rabbit is on the classpath - so we just need to add a clarifying warning.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-rabbit#16
