### ISSUE TITLE
spring-cloud-stream with RabbitMq and STOMP

### ISSUE THREAD

**Issue by lex-em** [spring-cloud/spring-cloud-stream#585]
Hi!

Does it posible to use STOMP over RabbitMq with spring-cloud-stream?

If it doesn't possible, are there any ways to declare different listeners for different types of objects within one Sink? Maybe via Jackson's inheritance? I'd like something like this:

```
@EnableBinding(Sink.class)
public class EventHandler {

    @StreamListener(Sink.INPUT)
    public void handle1(Event1 event){
        System.out.println(String.format("Id: %s, model: %s", event.getId(), event.getModel()));
    }

    @StreamListener(Sink.INPUT)
    public void handle2(Event2 event){
        System.out.println(String.format("AuthorId: %s, userId: %s", event.getAuthorId(), event.getUserId()));
    }
}
```

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-rabbit#25
