### ISSUE TITLE
Confusing example code in the reference doc

### ISSUE THREAD

**Issue by kdvolder** [spring-cloud/spring-cloud-stream#586]
In here: http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_introducing_spring_cloud_stream

This code example:

```
@SpringBootApplication
public class StreamApplication {

  public static void main(String[] args) {
    SpringApplication.run(StreamApplication.class, args);
  }
}

@EnableBinding(Sink.class)
public class TimerSource {

  ...

  @StreamListener(Sink.INPUT)
  public void processVote(Vote vote) {
      votingService.recordVote(vote);
  }
}
```

So what is this? Is it a source? It's name is `TimerSource` which suggests it is some kind of source of time data. But.... its annotated with `@EnableBinding(Sink.class)` suggesting instead it is a sink. And then it has a method there for processing votes. I'm left wondering... what has this to do with either a source or a sink of time data?

That is all really very confusing to someone reading the docs for the very first time.

**Comment by kdvolder** [comment]
The confusion between source / sink continues in the next paragraph.

> The following is the definition of the Source interface:

Then its followed by the **Sink** interface code.

**Comment by markfisher** [comment]
That looks like `TimerSource` was copy-pasted whereas something more appropriate would have been `VoteRecordingSink` or similar. It's definitely not a *source*.
