### ISSUE TITLE
Prevent auto-connect to Kafka server at application startup time

### ISSUE THREAD

**Issue by vsrahul82** [spring-cloud/spring-cloud-stream#590]
Our spring boot apps try to connect to the Kafka servers at the time of application startup. If the Kafka server is down or  name is wrongly spelled, the application does not startup. Is there a way to prevent the spring boot app from trying to connect to Kafka server so that  application starts up successfully?

**Comment by mbogoevici** [comment]
Moved to spring-cloud/spring-cloud-stream-binder-kafka
