### ISSUE TITLE
REST API for spring cloud stream consumer of Kafka Topic

### ISSUE THREAD

**Issue by vsrahul82** [spring-cloud/spring-cloud-stream#591]
The consumer example in documentation polls the Kafka topic and returns  instantly when a message arrives on the topic. If i wanted the message to be read from queue only when i invoke the consume method, kind of like provide a REST API that will return a message from Kafka topic  when invoked how can i do that?  Please provide code example.

**Comment by mbogoevici** [comment]
Spring Cloud Stream is currently entirely message-driven. We do not currently support pollable bindings. Can you describe your use case and we could perhaps introduce a new feature.

**Comment by sabbyanandan** [comment]
@vsrahul82: Thoughts?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#64
