### ISSUE TITLE
Fake Message Broker for integration / end to end tests

### ISSUE THREAD

**Issue by butzopower** [spring-cloud/spring-cloud-stream#592]
Currently, we have been unable to find a way to write end to end tests for our Spring Cloud Stream applications that cover the full range of behaviors we are getting from the library.  We are able to inject binders into an integration test to test the flow of Messages in and out of our application, but this misses quite a lot of the external configuration as well as the de/serialization from the broker to Message payload/headers.

An idea we had would be to inject a fake message broker in our tests that would get automatically (or through additional test configuration) bound to our application's binders.  We could then send messages to the this broker to activate the application and receive messages off the broker to confirm whatever the application is doing.

Here's an example of what a test using a fake message broker might look like:

``` java
// example application.properties

// spring.cloud.stream.bindings.input.destination=unenriched
// spring.cloud.stream.bindings.input.group=default

// spring.cloud.stream.bindings.output.destination=enriched
// spring.cloud.stream.bindings.output.group=default
// spring.cloud.stream.bindings.output.content-type=application/json


@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = com.example.EnricherApplication.class)
@IntegrationTest
public class EnricherTest {
    @Autowired
    TestMessageBroker testMessageBroker;

    @Before
    public void setUp() throws Exception {
        testMessageBroker.purgeAll();
    }

    @Test
    public void messageGetsEnrichedWithMyCoolField() throws Exception {
        testMessageBroker.forTopic("unenriched.default").send("{\"foo\":\"bar\"}");

        String result = testMessageBroker.forTopic("enriched.default").poll();
        assertEquals(result, "{\"foo\":\"bar\",\"myCoolField\":12345}");
    }
}
```

**Comment by chrylis** [comment]
I think this feature is what I'm looking for. I want to make sure that when a method on `MessageGeneratingComponent` is called, it's processed through `MessageResponder` and a mock interface injected into `MessageResponder` has a method called. (This is to test, among other things, my Spring Boot autoconfiguration for the responder.)

Using the test binder, however, messages are never delivered anywhere but the "dead letter queue", so I can't verify that the message routing is specified correctly.

**Comment by mbogoevici** [comment]
One way of testing this is using a binder with embedded broker support (e.g. Kafka or upcoming ActiveMQ). We need to document the procedure. See https://github.com/spring-cloud/spring-cloud-stream-samples/pull/36

**Comment by sabbyanandan** [comment]
This is being addressed via: https://github.com/spring-cloud/spring-cloud-stream-samples/pull/36.

**Comment by viniciusccarvalho** [comment]
The referenced samples have been merged on the main repo, closing the issue
