### ISSUE TITLE
Allow for disabling `TestSupportBinderAutoConfiguration`

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#593]
This would follow the normal patterns of any `AutoConfiguration`.

**Comment by sakemal** [comment]
I  disabled TestSupportBinderAutoConfiguration by adding 

spring.autoconfigure.exclude= org.springframework.cloud.stream.test.binder.TestSupportBinderAutoConfiguration 
in applicaiton.properties but it resulted in the error
"Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.IllegalStateException: A default binder has been requested, but there is more than one binder available: test,kafka, and no default binder has been set."

So even with disabling TestSupportBinderAutoConfiguration test binder is still getting initialized . Am I missing something ?

I am using 1.0.2.RELEASE of spring-cloud-stream-test-support

**Comment by mbogoevici** [comment]
@sakemal Yes, this is a known issue at the moment (that is the issue, in fact) - you can do 
`spring.cloud.stream.default.binder=test` as a workaround.

**Comment by sakemal** [comment]
@mbogoevici 
I tried adding it in application.yml 

""spring:
  cloud:
    stream:
      default:
        binder: test
"""
but it still fails with the same error.

**Comment by sakemal** [comment]
got it is 
spring.cloud.stream.default-binder=test
Thanks for the help

**Comment by mbogoevici** [comment]
Relates to #573

**Comment by mbogoevici** [comment]
Duplicates #827
