### ISSUE TITLE
Allow configuring metadata fetch timeouts

### ISSUE THREAD

**Issue by Chandra-TechPassionate** [spring-cloud/spring-cloud-stream#594]
Hi Marius,
Here is the issue description.

**Scenario 1: Asynchronous**
The MessageChannel.send() method is returning true, even if Kafka server(s) or Zookeeper is down. Hope this is an expected behavior, as it is asynchronous.

**Scenario 2: Synchronous**
added spring.cloud.stream.kafka.bindings.<channelName>.producer.sync=true property in application.properties file.

The MessageChannel.send() method is returning NULL after some time, if Kafka server(s) or Zookeeper is down.

The expectation is :
1. To return "true", if the message posted successfully to the kafka topic. This is working as expected.
2. To return "false with Exception", when the server is down. This is not happening.

Thank you.

**Comment by mbogoevici** [comment]
Hi Chandra,

We'd need more detail than that. `send` returns true if you are sending messages asynchronously.

You can set the producer to be asynchronous. See the available Kafka producer options here: http://docs.spring.io/spring-cloud-stream/docs/1.0.2.RELEASE/reference/htmlsingle/index.html#_kafka_producer_properties (in particular the `sync` option). 

Thank you,
Marius

**Comment by Chandra-TechPassionate** [comment]
Updated the issue description with more details.

**Comment by Chandra-TechPassionate** [comment]
As a workaround, I have directly used the Kafka producer API to create the KafkaProducer instance to invoke send method with the below properties.

**packages to import:**
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;

**kafka producer properties setup**
Properties props = new Properties();
props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "list all the kafka brokers here");
props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
props.put("producer.type", sync);
props.put("acks", all);
props.put("metadata.fetch.timeout.ms", 2);

**kafka producer instance creation with the above properties.**
KafkaProducer<String, String> producer = new KafkaProducer<String, String>(props);

**create a producer record**
ProducerRecord<String, String> producerRecord = new ProducerRecord<String, String>(topic, partition, key, msg);

**invoke send method. This will return an exceptin, if the kafka server(s) is down.**
producer.send(producerRecord).get();

**Comment by mbogoevici** [comment]
Necessary changes captured via https://github.com/spring-cloud/spring-cloud-stream/issues/613
