### ISSUE TITLE
--inputType should allow override

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-stream#599]
I'll speak with Dataflow DSL as this gives more concise examples, but this applies to SCS.
This follows a lengthy discussion with @mbogoevici 

When you have `foo | bar --inputType=xxx` and the message emitted by `foo` already has a contentType header, then `--inputType=xxx` set on `bar` has no effect.
One could argue this makes sense, because if the content type emitted by `foo` is say, `application/xml`, then there is no way you can interpret it to, let's say `application/json`.

While this seems sensible, we think it has two issues:
- real life check: sometimes, apps are broken and emit garbage. The user knows better and _really_ wants to override things. For that case, one could argue that a header enricher is more explicit. Note that 1) we don't currently have one and 2) it adds a hop
- for some cases, in particular `application/octet-stream`, it may still make sense to allow override. `application/octect-stream` is really the MIME type version of "I have no clue what that thing is". Everything is bytes after all. `text/ -> application/json or xml` is another candidate

Let's use this issue as a discussion board.

**Comment by viniciusccarvalho** [comment]
I think this will be fixed once all the stories around content-type improvements are implemented

**Comment by sabbyanandan** [comment]
The problems described here are already addressed with the content-type improvements in the 2.x line.
