### ISSUE TITLE
Allow setting a message key for the Kafka binder

### ISSUE THREAD

**Issue by Jacuo** [spring-cloud/spring-cloud-stream#602]
Sending message to kafka topic, when cleanup.policy=compact causes error. It looks that problem is with key= null. I tried to set key using
```
MessageBuilder.withPayload(message)
		                    .setHeader(KafkaHeaders.MESSAGE_KEY, key)
```
but with no effect.
Is there any way to set key value ?

**Comment by mbogoevici** [comment]
Hi,

Thanks for pointing that out. I believe we are currently mistakingly always setting the key to null, which is not working with compacted topics.

**Comment by Jacuo** [comment]
Is there any prediction, when it will be fixed ?

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#51
