### ISSUE TITLE
DefaultBinding with null endpoint fails after AbstractMessageChannelBinder.doBindProducer()

### ISSUE THREAD

**Issue by CalamarBicefalo** [spring-cloud/spring-cloud-stream#607]
While implementing a SCS binder, dealing with MessageHandler in the producer side of it, if it does not implement the interface Lifecycle, `AbstractMessageChannelBinder` will send a null reference to `DefaultBinding`, which will cause an assertion exception, since the constructor verifies it.

```
public DefaultBinding(String name, String group, T target, Lifecycle endpoint) {
        Assert.notNull(target, "target must not be null");
        Assert.notNull(endpoint, "endpoint must not be null");
        this.name = name;
        this.group = group;
        this.target = target;
        this.endpoint = endpoint;
    }
```

The result is that non lifecycle implementing message handlers as the JmsSendingMessageHandler will not work out of the box.

**Comment by garyrussell** [comment]
IMHO, we should not mandate that the 'endpoint' implements `Lifecycle` (most `MessageHandler`s don't).

We should also consider renaming the field to `lifecycle` and/or adding a CTOR that does not take a `Lifecycle`.

**Comment by garyrussell** [comment]
See the s-c-s Slack discussion starting August 8 @12:31pm

**Comment by mbogoevici** [comment]
The assertion is superfluous. We can just make the field an `Object` and check on `unbind` whether it's a `Lifecycle` and take the necessary actions, and maybe do that for other interfaces (`DisposableBean` etc.) - wondering if we can have a better hook here to stop the active endpoints when they're unbound. Generally speaking, I'm not very happy with `Binding` emulating the context behaviour, but that is probably a much bigger change.
