### ISSUE TITLE
@EnableBinding with spring-cloud-config would create two more appilcation context

### ISSUE THREAD

**Issue by cccccccoder** [spring-cloud/spring-cloud-stream#609]
and fetch config-server twice?

**Comment by cccccccoder** [comment]
[](url)

**Comment by mbogoevici** [comment]
Hi,

This is normal. One context will be the bootstrap context of the config client. The other is the context of the binder. 

If you are encountering specific issues, please provide a detailed description of your application and of the problem that you are running into. Code examples, detailed logs will go a great way. Thanks!

**Comment by cccccccoder** [comment]
the logs:
the first time that fetch the config server, create two application context, seems normal.
`>2016-08-10 20:51:10.820 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3b6ddd1d: startup date [Wed Aug 10 20:51:10 CST 2016]; root of context hierarchy
........
2016-08-10 20:51:12.651 [main] INFO  o.s.c.c.client.ConfigServicePropertySourceLocator - Fetching config from server at: http://Blue-PC:8088/
>2016-08-10 20:51:14.557 [main] INFO  o.s.c.c.client.ConfigServicePropertySourceLocator - Located environment: name=demoapp2, profiles=[dev], label=master, version=e2efb20f5377730bbb5d328c9a51cf009eb06ce1
>2016-08-10 20:51:14.558 [main] INFO  o.s.c.b.c.PropertySourceBootstrapConfiguration - Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name='https://git.coding.net/klein/pistachio-config-repository.git/demoapp2/dev/demoapp2-dev.yaml']]]
>2016-08-10 20:51:14.572 [main] INFO  demo.pistachio.app.DemoApplication - The following profiles are active: dev
>2016-08-10 20:51:14.594 [main] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@69fa8e76: startup date [Wed Aug 10 20:51:14 CST 2016]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@3b6ddd1d
`


the second time, 

`>2016-08-10 20:51:22.276 [main] INFO  o.s.context.support.DefaultLifecycleProcessor - Starting beans in phase -2147482648
>2016-08-10 20:51:22.278 [main] INFO  o.s.context.support.DefaultLifecycleProcessor - Starting beans in phase -2147482648
>2016-08-10 20:51:22.279 [main] INFO  o.s.context.support.DefaultLifecycleProcessor - Starting beans in phase 0
>2016-08-10 20:51:22.285 [main] INFO  o.s.cloud.netflix.eureka.InstanceInfoFactory - Setting initial instance status as: STARTING
>2016-08-10 20:51:22.309 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using JSON encoding codec LegacyJacksonJson
>2016-08-10 20:51:22.310 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using JSON decoding codec LegacyJacksonJson
>2016-08-10 20:51:22.310 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using XML encoding codec XStreamXml
>2016-08-10 20:51:22.310 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using XML decoding codec XStreamXml
>2016-08-10 20:51:22.365 [main] INFO  c.n.d.shared.resolver.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
>2016-08-10 20:51:22.366 [main] INFO  com.netflix.discovery.DiscoveryClient - Disable delta property : false
>2016-08-10 20:51:22.366 [main] INFO  com.netflix.discovery.DiscoveryClient - Single vip registry refresh property : null
>2016-08-10 20:51:22.366 [main] INFO  com.netflix.discovery.DiscoveryClient - Force full registry fetch : false
>2016-08-10 20:51:22.366 [main] INFO  com.netflix.discovery.DiscoveryClient - Application is null : false
>2016-08-10 20:51:22.366 [main] INFO  com.netflix.discovery.DiscoveryClient - Registered Applications size is zero : true
>2016-08-10 20:51:22.366 [main] INFO  com.netflix.discovery.DiscoveryClient - Application version is -1: true
>2016-08-10 20:51:22.366 [main] INFO  com.netflix.discovery.DiscoveryClient - Getting all instance registry info from the eureka server
>2016-08-10 20:51:22.373 [main] INFO  com.netflix.discovery.DiscoveryClient - The response status is 200
>2016-08-10 20:51:22.374 [main] INFO  com.netflix.discovery.DiscoveryClient - Starting heartbeat executor: renew interval is: 20
>2016-08-10 20:51:22.376 [main] INFO  com.netflix.discovery.InstanceInfoReplicator - InstanceInfoReplicator onDemand update allowed rate per min is 4
>2016-08-10 20:51:22.378 [main] INFO  com.netflix.discovery.DiscoveryClient - Discovery Client initialized at timestamp 1470833482378 with initial instances count: 1
>2016-08-10 20:51:22.396 [main] INFO  o.s.c.n.eureka.EurekaDiscoveryClientConfiguration - Registering application demoapp2 with eureka with status UP
>2016-08-10 20:51:22.398 [main] INFO  com.netflix.discovery.DiscoveryClient - Saw local status change event StatusChangeEvent [timestamp=1470833482398, current=UP, previous=STARTING]
>2016-08-10 20:51:22.402 [DiscoveryClient-InstanceInfoReplicator-0] INFO  com.netflix.discovery.DiscoveryClient - DiscoveryClient_DEMOAPP2/Blue-PC:demoapp2:30001: registering service...
>2016-08-10 20:51:22.403 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'featuresEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=featuresEndpoint]
>2016-08-10 20:51:22.428 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'channelsEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=channelsEndpoint]
>2016-08-10 20:51:22.432 [DiscoveryClient-InstanceInfoReplicator-0] INFO  com.netflix.discovery.DiscoveryClient - DiscoveryClient_DEMOAPP2/Blue-PC:demoapp2:30001 - registration status: 204
>2016-08-10 20:51:22.433 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'requestMappingEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=requestMappingEndpoint]
>2016-08-10 20:51:22.437 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'environmentEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=environmentEndpoint]
>2016-08-10 20:51:22.440 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'healthEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=healthEndpoint]
>2016-08-10 20:51:22.442 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'beansEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=beansEndpoint]
>2016-08-10 20:51:22.445 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'infoEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=infoEndpoint]
>2016-08-10 20:51:22.447 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'metricsEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=metricsEndpoint]
>2016-08-10 20:51:22.450 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'traceEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=traceEndpoint]
>2016-08-10 20:51:22.452 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'dumpEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=dumpEndpoint]
>2016-08-10 20:51:22.455 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'autoConfigurationReportEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=autoConfigurationReportEndpoint]
>2016-08-10 20:51:22.457 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'configurationPropertiesReportEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=configurationPropertiesReportEndpoint]
>2016-08-10 20:51:22.460 [main] INFO  o.s.b.actuate.endpoint.jmx.EndpointMBeanExporter - Located managed bean 'archaiusEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=archaiusEndpoint]
>2016-08-10 20:51:22.461 [main] INFO  o.s.integration.endpoint.EventDrivenConsumer - Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
>2016-08-10 20:51:22.461 [main] INFO  o.s.integration.channel.PublishSubscribeChannel - Channel 'demoapp2:dev:30001.errorChannel' has 1 subscriber(s).
>2016-08-10 20:51:22.462 [main] INFO  o.s.integration.endpoint.EventDrivenConsumer - started _org.springframework.integration.errorLogger
>2016-08-10 20:51:22.462 [main] INFO  o.s.context.support.DefaultLifecycleProcessor - Starting beans in phase 2147482647
>2016-08-10 20:51:22.622 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2e9f5499: startup date [Wed Aug 10 20:51:22 CST 2016]; root of context hierarchy
>2016-08-10 20:51:22.653 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
>2016-08-10 20:51:22.655 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [class org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$270b4005] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
>2016-08-10 20:51:22.748 [main] INFO  o.s.cloud.netflix.eureka.InstanceInfoFactory - Setting initial instance status as: STARTING
>2016-08-10 20:51:22.773 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using JSON encoding codec LegacyJacksonJson
>2016-08-10 20:51:22.773 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using JSON decoding codec LegacyJacksonJson
>2016-08-10 20:51:22.773 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using XML encoding codec XStreamXml
>2016-08-10 20:51:22.773 [main] INFO  c.n.discovery.provider.DiscoveryJerseyProvider - Using XML decoding codec XStreamXml
>2016-08-10 20:51:22.849 [main] INFO  c.n.d.shared.resolver.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
>2016-08-10 20:51:22.850 [main] INFO  com.netflix.discovery.DiscoveryClient - Disable delta property : false
>2016-08-10 20:51:22.850 [main] INFO  com.netflix.discovery.DiscoveryClient - Single vip registry refresh property : null
>2016-08-10 20:51:22.850 [main] INFO  com.netflix.discovery.DiscoveryClient - Force full registry fetch : false
>2016-08-10 20:51:22.850 [main] INFO  com.netflix.discovery.DiscoveryClient - Application is null : false
>2016-08-10 20:51:22.850 [main] INFO  com.netflix.discovery.DiscoveryClient - Registered Applications size is zero : true
>2016-08-10 20:51:22.850 [main] INFO  com.netflix.discovery.DiscoveryClient - Application version is -1: true
>2016-08-10 20:51:22.850 [main] INFO  com.netflix.discovery.DiscoveryClient - Getting all instance registry info from the eureka server
>2016-08-10 20:51:22.855 [main] INFO  com.netflix.discovery.DiscoveryClient - The response status is 200
>2016-08-10 20:51:22.857 [main] INFO  com.netflix.discovery.DiscoveryClient - Not registering with Eureka server per configuration
>2016-08-10 20:51:22.857 [main] INFO  com.netflix.discovery.DiscoveryClient - Discovery Client initialized at timestamp 1470833482857 with initial instances count: 1
>2016-08-10 20:51:22.949 [main] INFO  o.s.context.support.DefaultLifecycleProcessor - Starting beans in phase 0
>2016-08-10 20:51:22.949 [main] INFO  o.s.c.n.eureka.EurekaDiscoveryClientConfiguration - Registering application demoapp2 with eureka with status UP
>2016-08-10 20:51:23.044 [main] INFO  o.s.c.c.client.ConfigServicePropertySourceLocator - Fetching config from server at: http://Blue-PC:8088/
>2016-08-10 20:51:23.555 [main] INFO  o.s.c.c.client.ConfigServicePropertySourceLocator - Located environment: name=demoapp2, profiles=[dev], label=master, version=e2efb20f5377730bbb5d328c9a51cf009eb06ce1
>2016-08-10 20:51:23.555 [main] INFO  o.s.c.b.c.PropertySourceBootstrapConfiguration - Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name='https://git.coding.net/klein/pistachio-config-repository.git/demoapp2/dev/demoapp2-dev.yaml']]]
>2016-08-10 20:51:23.559 [main] INFO  demo.pistachio.app.DemoApplication - The following profiles are active: dev
>2016-08-10 20:51:23.563 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@140fa482: startup date [Wed Aug 10 20:51:23 CST 2016]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@69fa8e76
>2016-08-10 20:51:23.576 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring`

it's has create tow new application contexts : AnnotationConfigApplicationContext@2e9f5499 and AnnotationConfigEmbeddedWebApplicationContext@69fa8e76

it's that normal?

**Comment by cccccccoder** [comment]
@mbogoevici
but it seems Registered in eureka-server twice..

**Comment by mbogoevici** [comment]
However, fetching the configuration twice looks dubious. Can you provide more detail on that, please? configuration, logs.

**Comment by mbogoevici** [comment]
Ok, thanks. We'll take a look.

**Comment by donovanmuller** [comment]
@cccccccoder @mbogoevici Could this be similar/related to https://github.com/spring-cloud/spring-cloud-consul/issues/180?

**Comment by cccccccoder** [comment]
i think i've found the reason
in org.springframework.cloud.stream.binder.DefaultBinderFactory#getBinder(String name)
line 184-185
`ConfigurableApplicationContext binderProducingContext = springApplicationBuilder.run(args.toArray(new String[args.size()]));`
this will fire a environmentPreparedEvent
and the org.springframework.cloud.bootstrap.BootstrapApplicationListener will receive the event again 
so it'll fetch the config-server twice

**Comment by mbogoevici** [comment]
Closing this, as the issue originates in Spring Cloud Config client - for any binder context, a bogus Bootstrap context is created by BootstrapApplicationListener (even if the parent's Bootstrap context would be inherited instead)
