### ISSUE TITLE
Refactor AbstractMessageChannelBinder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#614]
As a developer, I'd like to refactor createProducerMessageHandler() and createConsumerMessageHandler() APIs. The goal is to simplify the binder specific extensions.

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/commit/c194ae720f21249831eb99b850cd8f3fb4c0e830
