### ISSUE TITLE
Create external dependencies POM

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#615]
As a developer, I'd like to move dependencies to [spring-cloud-stream-starters](https://github.com/spring-cloud/spring-cloud-stream-starters) repo. With this change, the SCSt BOM depend on SCSt-Starters, so all the dependent artifacts are consistently consumed.

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/commit/ac443b56bc03d3b84cda5dd9f55b195a82020a1c
