### ISSUE TITLE
Documentation for MessageConverters

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#616]
There is a reference to "the MessageConverter mechanism" in the user guide but no details on how to use it, customize it etc. E.g. what if I want to add a new converter?

**Comment by ilayaperumalg** [comment]
I realized that we already have documentation for message converters. Submitted a PR with some minor polishing to existing doc: https://github.com/spring-cloud/spring-cloud-stream/pull/652
