### ISSUE TITLE
Infinite loop of exceptions with maxAttempts=1

### ISSUE THREAD

**Issue by Mati20041** [spring-cloud/spring-cloud-stream#627]
By using following properties (from https://stackoverflow.com/questions/39018400/how-to-create-processor-with-transaction-and-dlq-with-rabbit-binding ):

```
spring.cloud.stream.bindings.output.destination=so8400out

spring.cloud.stream.rabbit.bindings.output.producer.transacted=true

spring.cloud.stream.bindings.input.destination=so8400in
spring.cloud.stream.bindings.input.group=so8400

spring.cloud.stream.rabbit.bindings.input.consumer.durableSubscription=true
spring.cloud.stream.rabbit.bindings.input.consumer.autoBindDlq=true
spring.cloud.stream.rabbit.bindings.input.consumer.transacted=true
```

And adding additional property:

`spring.cloud.stream.bindings.input.consumer.max-attempts=1`

Processor falls into infinite loop of trying to handle message from the queue. For other values [of max-attempts] it behaves as expected. 

Processor implementation:
```
	@StreamListener(Processor.INPUT)
	public void handle(String payload) {
		throw new RuntimeException("OH NOES!");
	}
```

I was not sure if this issue should be posted in Spring AMQP or here, so sorry if it is in wrong place.

**Comment by garyrussell** [comment]
If you disable retry then you need to set `requeue-rejected` to false.

You can also use `republishToDlq` with `maxAttempts=1`.

See [the reference manual](http://docs.spring.io/spring-cloud-stream/docs/1.0.2.RELEASE/reference/htmlsingle/index.html#_rabbitmq_consumer_properties).

**Comment by sabbyanandan** [comment]
@Mati20041: could you please try @garyrussell's suggestion, share your findings, and perhaps close this issue?

**Comment by Mati20041** [comment]
@sabbyanandan Yeah sure, sorry for taking so long to respond for that question.
@garyrussell That worked fine, thanks! Just in my opinion (and some other people) I didn't find this intuitive. Shouldn't that be made easier?

**Comment by garyrussell** [comment]
Agreed; we've switched the default to `false`. See https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/15
