### ISSUE TITLE
Standardize header behaviour

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#628]
Currently, the binder's behaviour wrt headers is largely dependent on the underlying implementation (also a consequence of middlewares having or not having header support natively). It would be largely better if we brought some consistency into this. 

Here are a few proposals:
- lift the `headers` property from binder-specific level to general-purpose and make it act as a whitelist (current behaviour, appending to `STANDARD_HEADERS`);
- if not set, allow all headers to be transported by default;
- allow an `excludedHeaders` general-purpose property for blacklisting headers to be transported (that would help with reducing payloads by not propagating undesirable stuff);

**Comment by garyrussell** [comment]
>blacklisting

The RabbitMQ header mapper has a negative pattern match `!foo*` means all headers except those starting with `foo`.

**Comment by artembilan** [comment]
The related SI JIRA: https://jira.spring.io/browse/INT-4096

**Comment by garyrussell** [comment]
@artembilan that's a different issue - this is about headers being transported by the binders.

**Comment by mbogoevici** [comment]
@garyrussell Then we might not need an extra property at all, just model blacklisting after the configuration options available in RabbitMQ.

**Comment by olegz** [comment]
Closing it as duplicate to https://github.com/spring-cloud/spring-cloud-stream/issues/1169
