### ISSUE TITLE
PartitionKeyExtractorStrategy instances do not have access to application context

### ISSUE THREAD

**Issue by nbyl** [spring-cloud/spring-cloud-stream#631]
When selecting the partion of a kafka topic using a custom PartitionKeyExtractorStrategy, the instantiated objects are not initialized to use configuration values or beans from the application context. This would be very useful when selecting the partition based on a configurable value.

I have a provided a [demo](https://github.com/spring-cloud/spring-cloud-stream/files/434525/demo.zip). When starting it, the logging shows that the inserted `@Value` is null and not properly initialized.

If this is on purpose the documentation should provide more information what is initialized into the this object.

**Comment by garyrussell** [comment]
If you configure your strategy implementation as a `@Bean` in the application context with a bean name of the fully qualified class name, that bean will be fully initialized by Spring and used by the binder. If the binder doesn't find a bean with that name, it will create one (and add it to the context), but it won't get a full Spring initialization.

	@Bean(name="com.example.MyKeyExtractor")
	public MyKeyExtractor extractor() {
		return new MyKeyExtractor();
	}

**Comment by garyrussell** [comment]
Alternatively, you can implement `ApplicationContextAware` and the application context **will** be injected and you can get values from its environment (as well as beans etc).

**Comment by ilayaperumalg** [comment]
Thanks @garyrussell for the input. I will update the documentation with this info.

**Comment by mbogoevici** [comment]
@garyrussell @ilayaperumalg I am reviewing https://github.com/spring-cloud/spring-cloud-stream/issues/760 - wondering if we should consider deprecating this mechanism in a future release (1.2?) - at the risk of disabling creating such configurations per-binding. The whole mechanism is somewhat un-Spring-like.

**Comment by garyrussell** [comment]
Maybe replace it with a `beanName` ?

This was a carry-over from Spring XD where it was less-easy to add custom beans to the context.
