### ISSUE TITLE
Figures missing in references PDF since Brooklyn.M1

### ISSUE THREAD

**Issue by tan9** [spring-cloud/spring-cloud-stream#642]
Every figure in http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.M1/reference/pdf/spring-cloud-stream-reference.pdf are missing!

![pdf](https://cloud.githubusercontent.com/assets/638068/18299114/c9b76e5e-74f0-11e6-95d5-e34c4cc603ce.png)

The epub format has the same issue too.

![epub](https://cloud.githubusercontent.com/assets/638068/18299115/c9b7a752-74f0-11e6-8204-47bd74d5a21d.png)

**Comment by mbogoevici** [comment]
Thanks for reporting - will have this fixed for RELEASE.
