### ISSUE TITLE
Acknowledgements using redis

### ISSUE THREAD

**Issue by rkersche** [spring-cloud/spring-cloud-stream#646]
Is it possible to use message acknowledgements using redis as backend?

**Comment by markpollack** [comment]
There is a redis binder, but we have not found the pub/sub functionality in redis to be appropriate for production.  https://github.com/spring-cloud/spring-cloud-stream-binder-redis  Is this what you were after in your question?

**Comment by schellkenig** [comment]
It would be great to have a backend that is available managed by a cloud provider such as, https://aws.amazon.com/elasticache/. Honestly I would use anything else but I dont want to host rabbitmq in HA configuration and care about it during production.

**Comment by mbogoevici** [comment]
On the long run, we intend to provide support for Kinesis (which would be a suitable alternative in AWS I suppose). Despite having managed alternatives, Redis er se remains unsuitable as a binder transport.

**Comment by mbogoevici** [comment]
Closing this as it is out of date.
