### ISSUE TITLE
Consuming from multiple partitions in a single consumer instance-index

### ISSUE THREAD

**Issue by Bhilhanan** [spring-cloud/spring-cloud-stream#648]
I have a suggestion to add a feature that will allow a single instance-index to consume message from multiple partitions.
More details on the scenario I'm talking about is in this question
http://stackoverflow.com/questions/39477198/spring-cloud-stream-rabbitmq-specify-topics-in-the-consumer

**Comment by olegz** [comment]
Given the age of this issue and Gary's reference to the addressed issue I am closing it. If you still feel there is something that needs to be done please raise a new issue.
