### ISSUE TITLE
Auto partition assignment issue when there are more consumers than there are partitions

### ISSUE THREAD

**Issue by mnadelson** [spring-cloud/spring-cloud-stream#649]
I have a consumer that subscribes to a topic with 3 partitions.  I launch the same instance of that consumer multiple times (they will of course all have the same consumer group).  When I launch one instance the consumer gets all three partitions (as expected).  When I launch 3 instances each consumer gets one partition (as expected).  When I launch 4 instances two of the consumers got the same partition and received the same messages.  This was not expected.  I would either expect the 4th consumer to get none of the messages or the 4th consumer to round-robin the messages with the other consumer on the same partition.

**Comment by mbogoevici** [comment]
Looks like a Kafka binder issue - let's pursue this in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-kafka#41
