### ISSUE TITLE
Add support for variable/property expansion in @Input/@Output @StreamListener annotations

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-stream#651]
I have a need to do this:

```
@Output("${my.prop.name}")
    public MessageChannel myOutboundChannel();
```

But `KafkaMessageChannelBinder` receives the raw value, not replaced w/ the system/app property and dies here:

```
public static void validateTopicName(String topicName) {
        try {
            byte[] utf8 = topicName.getBytes("UTF-8");
            for (byte b : utf8) {
                if (!((b >= 'a') && (b <= 'z') || (b >= 'A') && (b <= 'Z') || (b >= '0') && (b <= '9') || (b == '.')
                        || (b == '-') || (b == '_'))) {
                    throw new IllegalArgumentException(
                            "Topic name can only have ASCII alphanumerics, '.', '_' and '-'");
                }
            }
        }
        catch (UnsupportedEncodingException e) {
            throw new AssertionError(e); // Can't happen
        }
    }
```

**Comment by mbogoevici** [comment]
Hi,

Channel names are static. 
You can use `spring.cloud.stream.bindings.myOutboundChannel.destination=<topicName>` to configure the target topic name.

You can also use `spring.cloud.stream.bindings.myOutboundChannel.destination=${my.prop.name}` to use a placeholder property, but if its only role is to configure the target topic, then that's already two levels of indirection.

**Comment by bitsofinfo** [comment]
I understand those other options, its just that I'm trying to create a re-usable component someone can drop in their app. The channel name itself can vary in each app that uses an *instance* of this component. Hence I need that configurable rather than hardwired

**Comment by mbogoevici** [comment]
Ok, I marked this as a future enhancement. 

Would it be possible to share an example of what you are trying to achieve?

**Comment by bitsofinfo** [comment]
Thanks, will try to get together a sample at some point.

**Comment by mbogoevici** [comment]
Thanks a lot, that would be very helpful!
If you would like to contribute this feature, we would really appreciate it.

**Comment by olegz** [comment]
Closing it due to the age if the issue and the amount of changes that went in after that. If you feel you still need this feature please raise a new issue taking into account latest functionality
