### ISSUE TITLE
Partitioning stream data

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-stream#653]
I  have problem definition where want to route spring cloud stream messages 2 different data store(may be same data store but different collection) depends upon type of message. I explored the stream partition option, But as per my understanding, partitioning routes the message to different instance of same app. Does partition can route to different channels or sink?

**Comment by mbogoevici** [comment]
Hi,

Yes, partitioning refers to partitioning between consumers. You can have different output channels that send data to different destinations, or you can make it dynamic, as in the example here:

https://github.com/spring-cloud/spring-cloud-stream-app-starters/tree/master/router/spring-cloud-starter-stream-sink-router

**Comment by sabbyanandan** [comment]
@sachkk76: Also, please see an example in this [SO thread](http://stackoverflow.com/questions/39279211/spring-cloud-dataflow-routing-by-json-header).

**Comment by sachkk76** [comment]
thanks @mbogoevici and @sabbyanandan, will these options. Thank you.

**Comment by sabbyanandan** [comment]
@sachkk76: Thanks for the update. If you have any other questions, please consider posting them on [StackOverflow](http://stackoverflow.com/questions/tagged/spring-cloud-stream).
