### ISSUE TITLE
What binders are currently maintained?

### ISSUE THREAD

**Issue by jrgonzalezg** [spring-cloud/spring-cloud-stream#655]
I have asked about the Redis binder on https://github.com/spring-cloud/spring-cloud-stream-binder-redis/issues/4 but there seems no one is answering the issues there.

I still see mentions of the Redis binder on places like http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/ but it does not work together with spring-cloud-stream-reactive and the new Reactor streams.

It is also not mentioned on https://cloud.spring.io/spring-cloud-stream/ where only Kafka and Rabbit MQ are listed. Should we migrate to one of those? What are the current plans on this? I would appreciate any reply so i could take proper decisions on my current projects. Thanks!

**Comment by mbogoevici** [comment]
Hi @jrgonzalezg,

Sorry for missing your question on the other repository. Thank you for asking for clarifications.

Currently only RabbitMQ and Kafka are production-ready and recommended binders. We have ongoing efforts to support JMS, Google Pub Sub and potentially Kinesis, but all of them are under development currently.

The Redis binder is compatible with Spring Cloud Stream 1.0, but not with Spring Cloud Stream 1.1 and is not maintained anymore. What is not clear is that we've never recommended using Redis as a production messaging system, even if we've provided guidelines to use it during development, which unfortunately was a confusing message. So we've deprecated it and will not continue maintaining it. We will update the 1.0 documentation as well.

Right now, I would recommend using RabbitMQ or Kafka.

**Comment by jrgonzalezg** [comment]
Thanks! I was trying to build a microservices architecture for a "production" project with very minimal resource usage and the Redis binder was useful for that. But since learning and using the features of the newer versions of Spring Cloud Stream / Boot / Framework is more important for me i guess it is time to change the binder then :)
