### ISSUE TITLE
Aggregate application does not expose metrics of the component apps

### ISSUE THREAD

**Issue by raulavila** [spring-cloud/spring-cloud-stream#660]
We have an aggregate application configured as follows:

```java
new AggregateApplicationBuilder(OurApplication.class, args)
                .from(OurSourceApplication.class).args(args)
                .to(OurDestinationApplication.class).args(args)
                .namespace("our-app")
                .run(args);
```

We would be interested in querying the number of messages consumed and produced by the second app of the aggregate (`OurSourceDestinationApplication`). However, the `/metrics` endpoint of the application deployed is only exposing properties of the aggregate app, ignoring the components, so, for example, we can't see the value for the property `integration.channel.output.sendCount`, which would be extremely useful for debugging.

**Comment by mbogoevici** [comment]
Thanks Raul,

Just as a quick note, 'namespaces' refer to individual applications, so in this case .namespace("our-app") applies to 'OurDestinationApplication.class' - just making that clear.

**Comment by raulavila** [comment]
Ok, thanks for this clarification!
