### ISSUE TITLE
Spring Cloud Stream Kafka dynamic channel - specify common producer properties in yml

### ISSUE THREAD

**Issue by ralston26** [spring-cloud/spring-cloud-stream#666]
Using BinderAwareChannelResolver of spring-cloud-stream kafka , I am dynamically resolving the channels based on an event, Since I have many producer channels and all the channels output kafka messages are going to be consumed by non-spring applications i need to set the headerMode of each channel as raw in application.properties which makes my configuration messy, Is there a way to specify the headerMode = raw common for all the producers that i use rather than specifying for each channel individually?

**Comment by mbogoevici** [comment]
Hi,

Thanks for filing this - this is another rendering of the requirements of https://github.com/spring-cloud/spring-cloud-stream/issues/446 so will close this in favour of that.
