### ISSUE TITLE
Kafka ProducerListener disabled in Camden.RELEASE

### ISSUE THREAD

**Issue by wblancqu** [spring-cloud/spring-cloud-stream#667]
Hi all,

We upgraded to the above release (including spring-cloud-stream-binder-kafka 1.1.0.RELEASE) to gain advantage of the "autoRebalanceEnabled" property. However, we noticed that in that release our ProducerListener doesn't work anymore.

I noticed in the code of KafkaBinderConfiguration (line 90) that setting the producer listener has been commented:

`//kafkaMessageChannelBinder.setProducerListener(producerListener);`

Any particular reason for this?

Thanks in advance

**Comment by ilayaperumalg** [comment]
Hi,

Thanks for reporting.
I don't see any specific reason for this as `KafkaMessageChannelBinder` is required to set the producer listener from the binder configuration class `KafkaBinderConfiguration` which in turn will set the `KafkaTemplate` with that producer listener. So, it looks like a bug. 
I see this change got introduced [here] (https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/1bf14ac3909b0ec097e2b2a2c10fb3c96d4b9cc2#diff-30c40a58b9dfd50d0385d03ec3d29663R64).

**Comment by mbogoevici** [comment]
Moving this to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka

**Comment by mbogoevici** [comment]
Just a quick note - we've separated binder implementations from the core project so that they can evolve independently. Closed and moved this to the Kafka binder repository. 

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/49
