### ISSUE TITLE
Could spring cloud stream config a DLX and a DLQ automatically?

### ISSUE THREAD

**Issue by frankskywalker** [spring-cloud/spring-cloud-stream#668]
Sorry, if it is a dum issue.
I googled a lot and go through the Docs and come to a conclusion that Spring Cloud Stream won't automatically config a DLX and DLQ for you, even if you set the autoBindDlq and republishToDlq to true:
`stream:
            rabbit:
                bindings:
                    input:
                        consumer:
                            republishToDlq: true
                            autoBindDlq: true`
I can config a DLX and DLQ myself through rabbitmq, but wouldn't it be nice, that spring cloud stream handle this for us. So I can just docker run rabbitmq. And worry nothing about rabbitmq anymore.

**Comment by garyrussell** [comment]
It does indeed auto create/bind the DLQ:

```
spring.cloud.stream.bindings.input.destination=filesToProcess
spring.cloud.stream.bindings.input.group=files
spring.cloud.stream.rabbit.bindings.input.consumer.auto-bind-dlq=true
```

<img width="411" alt="screen shot 2016-10-05 at 2 35 07 pm" src="https://cloud.githubusercontent.com/assets/483832/19126482/1d7f95ec-8b09-11e6-866e-5d3b2dd1666a.png">
<img width="424" alt="screen shot 2016-10-05 at 2 36 05 pm" src="https://cloud.githubusercontent.com/assets/483832/19126490/24aac364-8b09-11e6-8ca4-b8e6ffa52149.png">
<img width="385" alt="screen shot 2016-10-05 at 2 35 26 pm" src="https://cloud.githubusercontent.com/assets/483832/19126494/2b125028-8b09-11e6-8cf0-095802f05eb0.png">

__HOWEVER__ it can only do that if the queue doesn't exist already - queue arguments are immutable and can't be changed after the queue has been created.

If you are still seeing the issue after deleting the queue, turn on DEBUG logging to see the queue declaration behavior.

**Comment by frankskywalker** [comment]
Thanks Gary,
I tried your config and it works. 
The reason my config not working is I did not have the 'input.group' property, which I intensionally leaves blank for dev environment.

**Comment by sabbyanandan** [comment]
@frankskywalker: Thanks for using Spring Cloud Stream! If you have any other questions, please feel free to reach out to us via [StackOverflow](http://stackoverflow.com/questions/tagged/spring-cloud-stream).
