### ISSUE TITLE
spring-cloud-starter-stream-rabbit activates Apache Tomcat

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-stream#669]
one of its transitive dependencies brings in Apache Tomcat which Spring Boot then starts. Please exclude Apache Tomcat so that it doesn't clobber other people's web server choices.

**Comment by mbogoevici** [comment]
This is coming from Spring Boot itself. The transitive dependency that brings in Apache Tomcat is `spring-boot-starter-web`.  The only thing we can do on our end is to can discuss the extent to which we will want to bring the web starter in for the future. But it is good for metrics/actuator endpoints, so ATM I believe there's value to keep it in by default. It is however, possible to rely on applications supplying it in future versions. 

The standard way of swapping servers is documented here: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-jetty-instead-of-tomcat .

**Comment by mbogoevici** [comment]
Closing this for now, as it is relates to the Boot web starter - we might want to reconsider the transitive dependency set for SCSt 2.
