### ISSUE TITLE
Rabbit Binder retries on failed message even when max-attempts=1

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-stream#670]

**Comment by cppwfs** [comment]
when setting `spring.cloud.stream.bindings.input.consumer.maxAttempts=1`, I expected that upon failure (i.e. service activator throws exception) that it would not retry the message.  However the sink continues to retry to process the message.

The workaround was to set requeue-rejected to false.

**Comment by garyrussell** [comment]
We should probably just go ahead and set it to false by default - when retry is enabled, we always "recover" the message, either by republishing it, or rejecting it without requeue. It probably never makes sense to set this to true but it won't hurt to leave it there as a setting.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-rabbit#17
