### ISSUE TITLE
"Current" docs are wrong version

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#671]
This link (which is top of Google search for "spring cloud stream docs") has the wrong version (1.0.2): http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/

**Comment by ericbottard** [comment]
Changed `current` to point to `Brooklyn.RELEASE`. `current-SNAPSHOT` will need to be changed once a new version label appears
