### ISSUE TITLE
Sleuth support for binders with embedded headers

### ISSUE THREAD

**Issue by barrycommins** [spring-cloud/spring-cloud-stream#672]
Hi,

I've been investigating using Sleuth and Zipkin with Spring Cloud Stream.
It seems that Sleuth's headers (like most headers) are discarded for binders with embedded headers (e.g. Kafka) so that those messages are never included in a trace.
This is not an issue with things like Rabbit, since it natively supports headers, and it works nicely.

I know that Kafka's lack of headers means this isn't an ideal situation, but there is currently a mechanism to include content-type as an embedded header. Any thoughts on extending that support to Sleuth?

Thanks

**Comment by mbogoevici** [comment]
@barrycommins Spring Cloud Sleuth already uses the header embedding mechanism for Kafka and configures the binder accordingly.

**Comment by donovanmuller** [comment]
@barrycommins perhaps https://github.com/spring-cloud/spring-cloud-sleuth/issues/282 is related?

**Comment by barrycommins** [comment]
Hi @mbogoevici ,

does it? I'm willing to concede that it was something I've misconfigured :-)

What I'm seeing is that the headers are set correctly in the Spring Integration ```Message``` , but are not passed to the payload in the Kafka message, e.g. X-B3-TraceId, X-B3-SpanId, etc.

Edit:
@donovanmuller 's answer looks like a workable solution though. 

Thanks guys

**Comment by mbogoevici** [comment]
@barrycommins - you are welcome.  If would be good to know if this doesn't work out of the box and why, because the original issue should have been fixed via https://github.com/spring-cloud/spring-cloud-sleuth/issues/284.

**Comment by barrycommins** [comment]
@mbogoevici I've had a quick look at this again, and at the moment I'm using Kafka as a messaging broker, but not using it to send traces to Zipkin (I'm using HTTP).

I have ```spring-cloud-starter-stream-kafka``` on my classpath, but not ```spring-cloud-sleuth-stream```, so the fix in ```StreamEnvironmentPostProcessor``` is applied.

Perhaps this isn't really a valid use case?

**Comment by mbogoevici** [comment]
@barrycommins Ah, ok - the original issue referenced Sleuth, which is why I went that route. The configuration for transported headers is here: http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.BUILD-SNAPSHOT/reference/htmlsingle/#_kafka_binder_properties

And that is consistent with @donovanmuller 'suggestion (thanks!). We do require headers to be configured explicitly with the Kafka binder.

**Comment by barrycommins** [comment]
@mbogoevici , sorry for any confusion. This has all been useful information.
I think I have enough to proceed, so I'll close this issue.
Thanks again.
