### ISSUE TITLE
Support for Rabbitmq delayed queue

### ISSUE THREAD

**Issue by lchayoun** [spring-cloud/spring-cloud-stream#676]
add support for Rabbitmq delayed queue plugin.
described in:
http://docs.spring.io/spring-amqp/docs/1.6.3.RELEASE/reference/html/_reference.html#delayed-message-exchange
https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/

**Comment by garyrussell** [comment]
In addition to configuring the exchange with delay, this will need support in Spring Integration to avoid the binder having to rebuild the message to add the header.

[PR here](https://github.com/spring-projects/spring-integration/pull/1920).

If needed, we should be able to backport this to 4.3.x.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-binder-rabbit#26
