### ISSUE TITLE
/channels endpoint not showing up in apps using Spring Cloud Config client

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream#685]
It must be to do with the ordering of configurations. We are seeing the `ChannelBindingService` but not `ChannelsEndpoint` in the /beans endpoint. Messages are flowing and we are connected but the endpoint is not there (neither is the `ChannelBindingAutoConfiguration`).

This happens for applications that have a config client enabled.

**Comment by dsyer** [comment]
I actually don't know if there's anything pointing to Spring Cloud Config client, other than a coincidence that the apps we saw this break on were all using the client.

**Comment by mbogoevici** [comment]
The reason why I am mentioning it specifically is that using Spring Cloud Config client was the only way we've been able to reproduce this so far ... We can look for other underlying issues.

**Comment by ilayaperumalg** [comment]
I tried to reproduce the issue by add `spring-cloud-config-client` - versions 1.2.0.RELEASE and 1.3.0.BUILD-SNAPSHOT and am able to access the `/channels` endpoint. What version did you use to replicate the issue? would like to check if there is a specific version of `spring-cloud-config-client` that causes this.

**Comment by ilayaperumalg** [comment]
@dsyer Tried to run the app with/without spring cloud config server running and the `channels` endpoint shows up fine. Please comment if you still see the issue or if you see this on a specific version of SCSt/config client.

**Comment by ilayaperumalg** [comment]
This issue might have disappeared in the latest Spring Cloud Stream or Spring Cloud Config changes. Closing this for now. Please re-open it if it is still an issue.

**Comment by dsyer** [comment]
Still broken for me (e.g. with petflix demo). The /autoconfig report says that `BindingServiceConfiguration#bindingService` matches and is present but `ChannelBindingAutoConfiguration` did not.

**Comment by dsyer** [comment]
This issue went away when I upgraded to Dalston.RELEASE (RC1 was broken). Not sure if that means it's fixed or not.
