### ISSUE TITLE
Difficult to register Confluent schema registry client

### ISSUE THREAD

**Issue by sbb** [spring-cloud/spring-cloud-stream#695]
This repo 

[https://github.com/sbb/schema-registry-bug-report.git](url)

shows an issue where the DefaultSchemaRegistryClient instance gets used even if there is a @Configuration that contains an @Bean definition that specifies the use of the ConfluentSchemaRegistryClient.  Only if this @Bean definition is placed in the body of the Main class will it take effect; otherwise the DefaultSchemaRegistryClient will be used, and if a Confluent schema server is in use, NPEs will occur when a new schema is (attempted to be) dynamically registered with it, owing to protocol differences between the Confluent and the default (Spring Cloud Stream Schema Registry I believe).

The `README.adoc` file included in the git repo describes the problem is more detail and provides instructions on how to reproduce and then work around the problem.

**Comment by ilayaperumalg** [comment]
Hi @sbb ,

The link you posted above doesn't seem to work. Could you provide the correct one.

Also, please check [this] (https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-0.10-test/src/test/java/org/springframework/cloud/stream/binder/kafka/Kafka10BinderTests.java#L187) test case where Confluent Scheme registry server is used.

**Comment by ilayaperumalg** [comment]
@sbb Please re-open this ticket once you have the repo link corrected. Also, let us know what you think about the test case link posted above (where Confluent Schema registry is used).

Marking this as a `question` for now  and closing.
