### ISSUE TITLE
Schema is a reserved keyword in MySQL 5.7

### ISSUE THREAD

**Issue by parunruaivo** [spring-cloud/spring-cloud-stream#696]
Using schema registry server with MySQL 5.7 throws 
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'schema`

**Comment by mbogoevici** [comment]
We should use a more portable name for the schema table.

**Comment by viniciusccarvalho** [comment]
@parunruaivo Thank you so much for reporting this. We are working on fixing this right now, I'm taking this opportunity to up a notch and if time permits add other spring-data storage options.
