### ISSUE TITLE
Schema Server with Postgres

### ISSUE THREAD

**Issue by parunruaivo** [spring-cloud/spring-cloud-stream#697]
Me again :(

Well I was trying to use Postgres instead of MySQL but I'm getting

`org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode.`

The table used is

``` sql
CREATE TABLE schema
(
  ID         SERIAL PRIMARY KEY,
  DEFINITION TEXT         NOT NULL,
  FORMAT     VARCHAR(255) NOT NULL,
  SUBJECT    VARCHAR(255) NOT NULL,
  VERSION    INTEGER      NOT NULL
);
```

the schema used was

``` json
{
  "type" : "record",
  "name" : "CustomerCreated",
  "namespace" : "com.payments.mobile.commons.domain.events.customer",
  "fields" : [ {
    "name" : "customerId",
    "type" : "long"
  }, {
    "name" : "firstName",
    "type" : "string"
  }, {
    "name" : "lastName",
    "type" : "string"
  }, {
    "name" : "emailAddress",
    "type" : "string"
  }, {
    "name" : "occurredOn",
    "type" : {
      "type" : "record",
      "name" : "Date",
      "namespace" : "java.util",
      "fields" : [ ]
    }
  } ]
}
```

Debugging the line

``` java
List<Schema> registeredEntities = this.repository.findBySubjectAndFormatOrderByVersion(
                schema.getSubject(), schema.getFormat());
```

and checking schema.getDefinition() it had the schema with a lot `\r\n`.

Thanks

**Comment by mbogoevici** [comment]
Not sure if the formatting was the problem - I think it's the LOB mapping. That being said, we definitely shouldn't be in auto-commit mode I think - this hints at the operation being non-transactional.

**Comment by mbogoevici** [comment]
(Thanks for posting these by the way - this is very valuable)

**Comment by viniciusccarvalho** [comment]
Postgresql has a requirement on LOB being only used inside transactions. So even for read-only methods such as findbyXXX we need to add `@Transactional`. Thanks for bring this to attention @parunruaivo 

Reference: https://www.postgresql.org/docs/current/static/lo-interfaces.html

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream/commit/18c894689c32e17769b929720b36390da8107ca6
