### ISSUE TITLE
Global contentType for all bindings

### ISSUE THREAD

**Issue by ab712** [spring-cloud/spring-cloud-stream#699]
Is it possible to configure contentType for all bindings with just one property instead of per-binding?

Currently this would be necessary 10+ times in my config:
`spring.cloud.stream.bindings.output.contentType=application/json;charset=UTF-8`

**Comment by mbogoevici** [comment]
Hi @ab712,

Thanks for the interest. There currently is an open issue for global/default settings. We hope to get to it in one of our coming releases.

https://github.com/spring-cloud/spring-cloud-stream/issues/446

**Comment by mbogoevici** [comment]
Closing this as it is a duplicate of #446
