### ISSUE TITLE
Remove logback.xml in spring-cloud-stream-binder-test

### ISSUE THREAD

**Issue by SirWayne** [spring-cloud/spring-cloud-stream#704]
Since we have used `spring-cloud-stream-binder-test` in our  test projects our logback-spring.xml don't work anymore. As soon as a logback.xml is in the classpath, the logback-spring.xml meachnism is no longer recognized. 
Is it possible to remove the logback.xml?

**Comment by mbogoevici** [comment]
@SirWayne Thanks for the feedback - yes, we can configure the default logging levels as Boot properties.

**Comment by SirWayne** [comment]
Cool thanks :)

**Comment by ilayaperumalg** [comment]
@SirWayne Thanks for reporting this. Contributions via PRs are welcome too! :-)
