### ISSUE TITLE
Support dynamic multiple Output channels

### ISSUE THREAD

**Issue by raissi** [spring-cloud/spring-cloud-stream#708]
We want the output channels to be dynamically defined in config files. A good use case would be to have a kind of dispatcher application that receives messages or calls, and based on some conditions it will post messages to dynamically configured output channels (e.g: Kafka Topics).
Actually, in _Spring Cloud Stream_, output channels must be hardcoded by mapping each output to a given annotated method:
```java
@Output
MessageChannel foo();
```
So each time we want to add a new output channel, the code of the application must be changed and redeployed. Contrary to _input_ channels that can be configured in properties files like this:
```
spring.cloud.stream.bindings.input.destination=firstQueue, secondQueue
```
So, our suggestion, is to define a new annotation _Outputs_ that takes a list of the names of configured output channels, like this:
```
spring.cloud.stream.bindings.output1.destination=someQueue.4
spring.cloud.stream.bindings.output2.destination=someQueue.5

my.list.of.output.channels=output1,output2
```
And in the binding interface:
```
@Outputs("${my.list.of.output.channels}")
MessageChannel multipleOutput(String name);
```
The param _name_ passed to _multipleOutput_ is the one that will determine which channel to use.
The annotation should accept hard coded names: _@Outputs("output1,output2")_ but there is no great gain in this case (since the outputs are hardcoded)

**Comment by ilayaperumalg** [comment]
Hi @raissi, 
Thanks for input and suggestion. You can achieve binding to multiple `dynamic` destinations via built-in support by either setting `spring.cloud.stream.dynamicDestinations` to a list of `destination` names or keeping it as empty. The `BinderAwareChannelResolver` takes care of dynamically creating/binding the `outbound` channel for these dynamic destinations.

**Comment by ilayaperumalg** [comment]
Here is one such  [example] (https://github.com/spring-cloud-stream-app-starters/router/blob/master/spring-cloud-starter-stream-sink-router/src/main/java/org/springframework/cloud/stream/app/router/sink/RouterSinkConfiguration.java#L48) where dynamic destination resolver is used.

**Comment by raissi** [comment]
Hi @ilayaperumalg 
Thank you for your hint. My bad, I didn't check all the samples. I think adding _BinderAwareChannelResolver_ usage for dynamic routing to the docs would be very useful. 
Thanks again

**Comment by markfisher** [comment]
+1 for adding a section to the reference manual to cover this use-case

**Comment by mbogoevici** [comment]
Thanks @raissi for raising the issue and for providing a PR - looking forward to more contributions in the future! I've opened #710 to deal with this.
