### ISSUE TITLE
Issue with Quick Start Documentation

### ISSUE THREAD

**Issue by parmarsanjay** [spring-cloud/spring-cloud-stream#711]
I am following instruction on Spring Cloud Stream Quick start at this location.

https://cloud.spring.io/spring-cloud-stream/#quick-start

Instructions talk about including following dependencies. 

dependencies {
    compile 'org.springframework.cloud:spring-cloud-stream'
    **compile 'org.springframework.boot:spring-boot-starter-kafka'**
    compile 'org.springframework.cloud:spring-cloud-starter-stream-kafka'
}

For some reason, following is not getting resolved. It gives me following error. 

=======
 What went wrong:
Could not resolve all dependencies for configuration 'detachedConfiguration24'.
> Could not find org.springframework.boot:spring-boot-starter-kafka:.
  Searched in the following locations:
      http://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.pom
      http://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.jar
      http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.pom
      http://repo.spring.io/snapshot/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.jar
      https://repository.jboss.org/nexus/content/repositories/releases/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.pom
      https://repository.jboss.org/nexus/content/repositories/releases/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.jar
      https://oss.sonatype.org/content/repositories/releases/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.pom
      https://oss.sonatype.org/content/repositories/releases/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.jar
      https://oss.sonatype.org/content/repositories/snapshots/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.pom
      https://oss.sonatype.org/content/repositories/snapshots/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.jar
      http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.pom
      http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-kafka//spring-boot-starter-kafka-.jar
  Required by:
      project :core
=======

I looked up pom.xml in Brooklys.SR1 release and don't see any reference to spring-boot-starter-kafka. 

I changed it to following and it's able to resolve correctly.

compile group: 'org.springframework.cloud', name: 'spring-cloud-stream-binder-kafka'

Is this correct? Or I am missing something?

**Comment by mbogoevici** [comment]
Hi, thanks for reporting. The Gradle instructions are wrong.

**Comment by parmarsanjay** [comment]
Thanks for the update. So Do I need to add following to Gradle or  it's not needed.

compile group: 'org.springframework.cloud', name: 'spring-cloud-stream-binder-kafka'

Just having following should be fine?

compile 'org.springframework.cloud:spring-cloud-stream'
compile 'org.springframework.cloud:spring-cloud-starter-stream-kafka'

**Comment by mbogoevici** [comment]
The starters include the corresponding binders as transitive dependencies so they don't need to be included separately - just the starter should be fine.

**Comment by parmarsanjay** [comment]
Great. Thanks.

**Comment by luis-moral** [comment]
When are you gonna update the frontpage? thanks!
