### ISSUE TITLE
Add support for deleting schemas via HTTP

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-cloud/spring-cloud-stream#716]
For testing purposes, it is handy to be able to delete schemas from registry server via HTTP.

**Comment by mbogoevici** [comment]
Ca you provide a quick description of how you think this should work ? One option would be to delete all the versions of a specific subject - we should control this via a property and default it to false. This should never be used in production, as it disables reading old messages.

**Comment by PedroAlvarado** [comment]
Deleting a schema is a highly sensitive operation analogous to deleting a table in a RDBMS. Production operators should take preventive measures to backup schemas and such. Spring's opinion should be to let the production operators be responsible for the lifecycle of schemas and, to support this process, enable operators/administrator to delete schemas, perhaps, as outlined below. In addition, it would be great to have a configuration (allowSchemaDeletion) that disables schema deletion to help operators protect schemas from malfunctioning software. During maintenance, operators can temporarily disable this flag to delete any relevant schemas as tested in their pre-production environments and re-enable afterwards.

DELETE /{subject}/{format}/{version}
Delete an existing schema by its subject, format and version.

DELETE /schemas/{id}
Delete an existing schema by its id.

DELETE /{subject}
Delete an existing schema by its subject.

**Comment by mbogoevici** [comment]
Thanks @PedroAlvarado for the feedback - I suppose that `spring.cloud.stream.schema.server.alllowSchemaDeletion` would be an appropriate property name.
