### ISSUE TITLE
Validate input channels before starting

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#721]
In the specific case of `MessageChannel` bindings, if an input channel doesn't have a subscription before starting, it results in a series of dispatching errors from SI. Since all channels are now `SubscribableChannels` we shouldn't even allow an application to start if its input channels don't have subscriptions. We could disable this check via Boot configuration in case someone really needs to add their subscriptions after starting the application, but that is not the case for the average user.

**Comment by garyrussell** [comment]
@mbogoevici - don't you need some help from SI for this? `AbstractSubscribableChannel` maintains a `handlerCounter` field but it's not currently exposed as a property.

**Comment by mbogoevici** [comment]
@garyrussell I think we do. The fallback is reflective access (which feels more like a hack tbh, but might work until SI has support for it). I just filed the issue to as a way to discuss the best way to stave off unpredictable dispatcher exceptions at startup.

**Comment by garyrussell** [comment]
https://jira.spring.io/browse/INT-4174

**Comment by viniciusccarvalho** [comment]
After looking into this, and discussing with the team, I think it would be best to push this to a 2.0 release timeline. The only reason being focus on other more pressing issues.

Also, if we decide to implement a start/stop feature for endpoints, it could be (depending on how we decide to implement), that a channel may not have it's subscribers ready by the time we finish the binding lifecycle, they could be starter after via an API call, this would invalidate any check on `getSubscriberCount` that was handled at `doBindConsumer` for example

**Comment by sabbyanandan** [comment]
The framework has evolved significantly since this issue was raised; I will close this for now. If there are similar requirements in the future, we will revisit it.
