### ISSUE TITLE
Create 1.1.x branch

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#732]
As a developer, I'd like to create the 1.1.x branch, so we could support ongoing maintenance on 1.1.x release line.

**Comment by ilayaperumalg** [comment]
Created branch: https://github.com/spring-cloud/spring-cloud-stream/tree/1.1.x

Setting up CI build plan for it now.

**Comment by ilayaperumalg** [comment]
@sobychacko by mistake I thought this is in bamboo and I completely missed that SCSt builds are running on Jenkins ;) I am passing this story to your expertise to setup the CI for 1.1.x on Jenkins. Thank you!
