### ISSUE TITLE
AggregateApplicationBuilder forcing full auto-config

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream#737]
In `AggregateApplicationBuilder` there is no option to fully define what parent context will have as `ParentConfiguration` is always added. This config class has `@EnableAutoConfiguration` in it which makes it impossible to exclude auto-config classes which are known not to work in your app.

This is i.e. case with `gpfdist` which needs to disable `DataSourceAutoConfiguration` as otherwise we'll end up
```
2016-12-15 09:37:00.601 DEBUG 6016 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception

org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (no profiles are currently active).

```

We should not force feed `@EnableAutoConfiguration` to a user app.

**Comment by mbogoevici** [comment]
Thanks for submitting this @jvalkeal. We should be more flexible with the classes we want to include/exclude from autoconfiguration.

In the meantime I suggest trying to use `spring.autoconfigure.exclude` - see http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-auto-configuration.html#using-boot-disabling-specific-auto-configuration,

    new AggregateApplicationBuilder("--spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration")

**Comment by jvalkeal** [comment]
`spring.autoconfigure.exclude` worked so at least I can now play with aggregated apps.
