### ISSUE TITLE
Allow custom configuration of partition metadata producer.

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-cloud/spring-cloud-stream#744]
At the moment, we use the DefaultKafkaProducerFactory to create a new producer to fetch partition metadata. This producer uses a combination of hard-coded and default producer configuration making it difficult to tailor its configuration. 

A sample use-case for this feature is the case of local development where we want to fail fast when, say, the kafka broker is not working correctly. In this scenario, currently and out-of-the-box, spring cloud stream will wait 10 minutes (60000ms=max.block.ms * 10=SimpleRetryPolicy.maxAttempts) to fail. Moreover, there is not indication that retries are taking place, hence, the logs look like the application may have started successfully.

**Comment by mbogoevici** [comment]
Moved to `spring-cloud-stream-kafka-binder` as https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/76
