### ISSUE TITLE
Allow applications more control over binding/unbinding

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#746]
Currently, the `BindingService` provides some mechanisms that allow an application to create bindings dynamically - however it is too much dependent on Spring Boot property binding as well as the general application lifecycle. We intend to make the APIs around binding friendlier to users or frameworks that build on top of Spring Cloud Stream, that want to add bindings dynamically (e.g. Spring Cloud Function and #690).

**Comment by ilayaperumalg** [comment]
This SO question has some relevance on this feature (especially supporting dynamic destinations for consumer bindings): http://stackoverflow.com/questions/41675471/spring-cloud-stream-dynamic-channels

**Comment by jovani14** [comment]
Please let me know if BindingBeanDefinitionRegistryUtils is sufficient to add bindings dynamically for Processor or Sink at Runtime. It seems this class is used internally by the framework and the camel example provided http://stackoverflow.com/questions/41675471/spring-cloud-stream-dynamic-channels relies on starting the consumer. Do you have an example on using bindingService to achieve dynamic binding and creating Processor and or Sink dynamically?

**Comment by mbogoevici** [comment]
Duplicates #763
