### ISSUE TITLE
Can spring cloud stream kafka use high level consumers api ?

### ISSUE THREAD

**Issue by wcggit** [spring-cloud/spring-cloud-stream#750]
I found my consumers sent offsets to **__consumer_offsets** topic , i couldn't find any useful information on [here](http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/)

**Comment by mbogoevici** [comment]
@wcggit 

What version of Spring Cloud Stream Kafka are you using? Unless you have a hard requirement to use Kafka 0.8 I would suggest upgrading to version 1.1.

**Comment by ilayaperumalg** [comment]
I think this can be closed now.
