### ISSUE TITLE
Schema registry support: bypass dynamic registration if `contentType` header set

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#753]
The use case is producing `GenericRecord` outputs with schema already attached. The current process will try to infer the `contentType` header by comparing with known schemas - this process could be bypassed if the user populates the `contentType` header appropriately.

**Comment by viniciusccarvalho** [comment]
@mbogoevici I believe that by implementing #832 we will no longer need this feature. Unless performance tests prove otherwise, I see no overhead on looking up parsedSchemas from a cache.

**Comment by viniciusccarvalho** [comment]
This is going back to the icebox, #832 should fix any performance related issues, and if this level of control is required by the user, they could use the AvroMessageConverter that does not rely on the SchemaRegistry. If any use case shows a need for this, we can revisit in the future
