### ISSUE TITLE
org.springframework.cloud.stream.binding.MessageConverterConfigurer$PartitioningInterceptor Performance

### ISSUE THREAD

**Issue by maximkir** [spring-cloud/spring-cloud-stream#764]
I've noticed that ~200 milliseconds are spend at `PartitioningInterceptor.preSend()` method. This happens due to `ExpressionUtils.createStandardEvaluationContext` call which happens on every invocation and is expensive.

![image](https://cloud.githubusercontent.com/assets/4746489/21986153/fefdb0d2-dc06-11e6-86de-90b907c3c94d.png)

I suggest to refactor the class to:

```
	private final class PartitioningInterceptor extends ChannelInterceptorAdapter {

		private final BindingProperties bindingProperties;
		private final PartitionHandler partitionHandler;

		private PartitioningInterceptor(BindingProperties bindingProperties) {
			this.bindingProperties = bindingProperties;
			partitionHandler = new PartitionHandler(
				 MessageConverterConfigurer.this.beanFactory,
				 ExpressionUtils.createStandardEvaluationContext(MessageConverterConfigurer.this.beanFactory),
				 null,
				 this.bindingProperties.getProducer());
		}

		@Override
		public Message<?> preSend(Message<?> message, MessageChannel channel) {
			int partition = this.partitionHandler.determinePartition(message);
			return new MutableMessageBuilderFactory().fromMessage(message)
					.setHeader(BinderHeaders.PARTITION_HEADER, partition).build();

		}
	}
```
The partition handler will be created once during interceptor creation and will save run time => smaller latency.

**Comment by mbogoevici** [comment]
Thanks @maximkir !

If you don't mind changing your suggestion into a PR, we happily accept contributions!

**Comment by maximkir** [comment]
No problem, Am I need a permissions to submit my changes?

**Comment by ilayaperumalg** [comment]
No, You can submit a PR right away :-)  All you need is to sign the Contributor License Agreement which gives you notification when you submit a PR.

**Comment by maximkir** [comment]
Submitted.
