### ISSUE TITLE
Method checks in `StreamListenerBeanPostProcessor` involve eager bean creation

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#767]
In particular this bit works only if the bean exists:

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java#L169

We may want to be a bit lenient there, for cases when beans are created by other BeanPostProcessors.

Note: this might affect `invokeSetupMethodOnListenedChannel` as well.

**Comment by ilayaperumalg** [comment]
Given the `target` bean referred in the stream listener method should have been created (for instance [1](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java#L216) and [2](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java#L252)) when setting up/invoking the appropriate method invocation, I think it might be better to have the `StreamListenerAnnotationBeanPostProcessor` to get executed with `lowest` precedence order. What do you think?

**Comment by ilayaperumalg** [comment]
Something like [this](https://github.com/ilayaperumalg/spring-cloud-stream/commit/a6ad34c520a136bf0fad0ea36f332a22970fb65c)

**Comment by artembilan** [comment]
@ilayaperumalg , the ordering doesn't help here:

1. `MessagingAnnotationPostProcessor` doesn't implement `Ordered`, and it will be invoked lately:
```
PostProcessorRegistrationDelegate.registerBeanPostProcessors()
...
// First, register the BeanPostProcessors that implement PriorityOrdered.
registerBeanPostProcessors(beanFactory, priorityOrderedPostProcessors);
...
// Next, register the BeanPostProcessors that implement Ordered.
registerBeanPostProcessors(beanFactory, orderedPostProcessors);
...
// Now, register all regular BeanPostProcessors.
registerBeanPostProcessors(beanFactory, nonOrderedPostProcessors);
...
// Finally, re-register all internal BeanPostProcessors.
registerBeanPostProcessors(beanFactory, internalPostProcessors);
```
2. But even if we can do that and let `MessagingAnnotationPostProcessor` be higher than `StreamListenerAnnotationBeanPostProcessor` it won't help. Just because they are different `BPP`s for different beans. And there is no guaranty that bean with Messaging Annotations methods to auto-create channel beans would be called before we start to process `@StreamListener`.

**Comment by ilayaperumalg** [comment]
Looks like this is still an issue when referring to the message channels from the application context in the following places [1](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java#L259), [2](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java#L294), [3](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binding/StreamListenerAnnotationBeanPostProcessor.java#L366) and in few other places where `applicationContext.getBean()` is invoked on the bound element targets.
