### ISSUE TITLE
Consider Supporting Patterns in EmbeddedHeadersMessageConverter

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#769]
See http://stackoverflow.com/questions/41805743/spring-integration-not-forwarding-a-custom-header

The user doesn't know the header names he wants to transport ahead of time, so can't configure the binder.

**Comment by mbogoevici** [comment]
I think this complementary to #707.

**Comment by garyrussell** [comment]
Agreed; we can set the default to `*` to mirror RabbitMQ.

**Comment by garyrussell** [comment]
We should also consider improving the `EmbeddedHeadersMessageConverter`. I believe we can drop the `oldExtractHeaders()` method - the migration to the "new" format predates SCSt (it was done in XD).

We could detect that messages not starting `0xff` do not have embedded headers and just log a warn `No embedded headers detected; consider setting 'headerMode=raw?'` and return an unmodified buffer.

Currently, if the user fails to set `headerMode=raw` he gets an ugly

    java.lang.StringIndexOutOfBoundsException: String index out of range: 152

**Comment by mbogoevici** [comment]
@garyrussell How about we ditch the `0xff` check entirely and after failing to extract headers in `headerMode=embeddedHeaders` we notify the user tho consider setting `headerMode=raw`? We could also introduce a `headerMode=auto` that will just return the original buffer if the header parsing fails.

**Comment by garyrussell** [comment]
Yeah - maybe always returning the unmodified buffer if parsing fails (with a warning log) is always the right thing to do (so we don't really need another mode).

**Comment by mbogoevici** [comment]
Should be covered by #628
