### ISSUE TITLE
Wrong channel injection example

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#773]
See https://twitter.com/gandrille/status/824565337962270722 for details.

(We should also avoid @Autowired fields throughout the doc fwiw).

**Comment by garyrussell** [comment]
I am a bit confused; the Brooklyn SR1 docs show:

    @Autowired
    private MessageChannel output;

    @Autowired @Qualifier("customOutput")
    public SendingBean(MessageChannel output) {
        this.output = output;
    }

On master it's 

    @Autowired @Qualifier("customOutput")
    private MessageChannel output;

    @Autowired
    public SendingBean(MessageChannel output) {
        this.output = output;
    }

(change by @ilayaperumalg a few days after Brooklyn.SR1 - the qualifier moved from the ctor to the field).

Should the proper fix not have been...

    private MessageChannel output;

    @Autowired
    public SendingBean(@Qualifier("customOutput") MessageChannel output) {
        this.output = output;
    }

???

**Comment by mbogoevici** [comment]
Yes, the existing master is still wrong - the field shouldn't be autowired at all.
