### ISSUE TITLE
[Documentation] String message doesn't have declared toUpper method

### ISSUE THREAD

**Issue by martijnhaex** [spring-cloud/spring-cloud-stream#777]
As the spring-cloud-stream Guide shows:
`@EnableBinding(Processor.class)
public class TransformProcessor {
  @Transformer(inputChannel = Processor.INPUT, outputChannel = Processor.OUTPUT)
  public Object transform(String message) {
    return message.toUpper();
  }
}
 `
String doesn't have a declared method toUpper.

Correct documentation by using toUpperCase method.

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream/pull/778
