### ISSUE TITLE
EmbeddedHeadersMessageConverter extractHeader method can operate on byte[]

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#780]
It can be a convenient option to have the `EmbeddedHeadersMessageConverter` to have an overloaded method to extractHeader using just the `payload` and `requestHeaders` instead of using the `Message` object especially in cases where the message payload is already retrieved.

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/pull/781
