### ISSUE TITLE
"spring.cloud.stream.default" prefix is not used by BindingServiceProperties

### ISSUE THREAD

**Issue by reda-alaoui** [spring-cloud/spring-cloud-stream#782]
While using Brooklyn SR2 release, I am trying to set a default `contentType` by adding this to the properties file:
```properties
spring.cloud.stream.default.contentType=application/x-kryo
```

It doesn't work. 

After debugging, it appears that `EnvironmentEntryInitializingTreeMap` default values are only loaded by call to the `get` method. But `BindingServiceProperties` calls `get` only if `containsKey` return true:
```java
if (this.bindings.containsKey(bindingName)) {
			BeanUtils.copyProperties(this.bindings.get(bindingName), bindingProperties);
		}
```

Therefore, I think that `EnvironmentEntryInitializingTreeMap` should override `containsKey` by returning `get(key) != null`

I am going to submit a pull request with the fix.

**Comment by mbogoevici** [comment]
Thanks for the contribution!
