### ISSUE TITLE
Document SchemaRegistryClient properties

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#788]
Currently, the documentation for the SchemaRegistryClient properties is missing. Especially the one with `spring.cloud.stream.schemaRegistryClient.endpoint`.

Thanks to the StackOverflow [question](http://stackoverflow.com/questions/42116751/spring-cloud-stream-schema-client-how-to-easily-set-up-server-port)

**Comment by mbogoevici** [comment]
Duplicates #878
