### ISSUE TITLE
Service instances are not allowed to start if Kafka-Zookeeper is down

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream#790]
I have a microservice that among some other functions, uses Spring Cloud Streams (Kafka) to send messages to a topic. The point is that if Kafka-Zookeeper is down, the microservice is not allowed to start, it unregisters itself from Eureka and doesn't accept HTTP requests:

```
Caused by: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 10000
...
s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@34e9de8d: startup date [Thu Feb 09 09:36:14 CET 2017]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4bdc8b5d
o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
c.n.e.EurekaDiscoveryClientConfiguration : Unregistering application order-service with eureka with status DOWN
```

I have been looking at the documentation but haven't found a way of allowing the start of the service when Kafka is down.

**Comment by mbogoevici** [comment]
Hi,

Thanks for reporting. Late binding is not supported yet with Kafka - please follow https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/12 for details.
