### ISSUE TITLE
Reactor-based handlers do not properly handle errors

### ISSUE THREAD

**Issue by runningonfumes** [spring-cloud/spring-cloud-stream#792]
When using reactor-based handlers retry and DLQ logic is not done. On an exception the consumers even stop listening.

In the attached project is a little demo (using kafka, but the same for rabbit)

When you call http://localhost:8080/demo, a message is sent over kafka and the consumer randomly throws an exception. In the non-reactive version, messages are retried and put on an error topic after three retries.

If you use the reactive version (uncomment in class DemoInput and comment other method), this does not happen. On the first exception, the consumer stops without retry and without putting the message on a DLQ.

[demo.zip](https://github.com/spring-cloud/spring-cloud-stream/files/764088/demo.zip)

**Comment by viniciusccarvalho** [comment]
It's a known issue unfortunately, it's even worse I'm afraid. If the consumer has an error, the subscription is cancelled, but the MessageHandler that is connected to the InboundChannelAdapter continues to ack messages.

We are working on a solution, but for the moment, the user is responsible to handle errors on reactive types

**Comment by olegz** [comment]
This appears to be duplicate to https://github.com/spring-cloud/spring-cloud-stream/issues/1729 which is already in PR waiting for relevant libraries to be released.

Closing
