### ISSUE TITLE
Improve the content type and transformation section of the documentation

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream#797]
I have been struggling with serialization/deserialization for some days now, reading and rereading the documentation and debugging the source code.

Maybe it's just me but I would suggest that the documentation was cleared up a bit:

1. **Default serialization:** this [closed issue](https://github.com/spring-cloud/spring-cloud-stream/issues/156) discussed about the default serialization and the bad practice of having to share classes between the producer and consumer sides. The point is **that that bad practice is still the default option in the framework but we can't guess it from the docs.**. 

In my case, I send a `service1.Order` object:

`orderProcessor.output().send(MessageBuilder.withPayload(order).build());`

And the consuming service fails:

```
Caused by: org.springframework.core.serializer.support.SerializationFailedException: unable to deserialize [service1.Order]. Class not found.; nested exception is java.lang.ClassNotFoundException: service1.Order
	at org.springframework.cloud.stream.binder.AbstractBinder.deserializePayload(AbstractBinder.java:255) ~[spring-cloud-stream-1.1.0.RELEASE.jar:1.1.0.RELEASE]
```

This is my listener that expects service2.Order:

```
@StreamListener(OrderProcessor.INPUT)
public void handle(Order order){
```
I can see that the embedded headers indicate `contentType=application/x-java-object;type=service1.Order` so it's obvious why it's failing.

Specifying content-type: application/json in the configuration of the output channel solves this but, shouldn't it be indicated more clearly in the docs? I was kind of naive expecting a JSON conversion as the default one.

The documentation currently states: 

> Spring Cloud Stream attaches, by default, a contentType header to outbound messages

But IMO we can't directly guess that we will need by default to share classes between services.

2. **6.2 section:** I don't get what the columns really mean, my interpretation is:

    - **Source payload**: the object passed to the MessageBuilder.withPayload() function.
    - **Target payload**: the expected payload after the serialization, the one that will actually be transmitted (well, actually the source of the transmitted byte[]).
    - **content-type header vs content type**: the former a content type header passed while building the Message on the producer side. The latter the param that can be specified in the configuration property.

Am I right? 

Also, I guess that table only applies regarding the producing side, no the consuming side.

Finally I just want to point out that this is only a suggestion based on my Spring Cloud Stream newbie experience. The platform is great and I do appreciate the clarifications and feedback I have been getting from the team.

Regards

**Comment by mbogoevici** [comment]
Thanks @codependent! These are great suggestions and will help us get a better docs.
