### ISSUE TITLE
Document the error handling for reactor-based applications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#805]
As a user, I'd like to follow standardized error-handling practices when developing reactive applications. 

**Acceptance:**
- best practices documented
- samples included

**Comment by sabbyanandan** [comment]
@viniciusccarvalho While we are documenting it, maybe there's an opportunity for us to validate spring-cloud/spring-cloud-stream#792 as part of it.

**Comment by sabbyanandan** [comment]
@viniciusccarvalho ping

**Comment by viniciusccarvalho** [comment]
We are revisiting the reactive support for 2.0, closing this for now, will look into it again later
