### ISSUE TITLE
Use of spring-cloud-bus with spring-cloud-stream

### ISSUE THREAD

**Issue by tajdars** [spring-cloud/spring-cloud-stream#806]
Spring Boot Version : 1.5.1.RELEASE
This is a spring-cloud-stream-sink application

I am using different rabbitmq brokers for :
spring-cloud-stream-input
spring-cloud-bus
spring-cloud-sleuth

The properties for spring-cloud-bus broker are configured as
spring.rabbitmq.host ..

The properties for 

spring-cloud-stream
and
spring-cloud-sleuth

are configured as
spring.cloud.stream.binders.<binder>.environment.*

For some reason all 3 binders get attached to  spring-cloud-bus-broker

Any ideas ?

**Comment by mbogoevici** [comment]
Hi @tajdars  - can you update the issue with the configuration you're using? I suppose pasted some configuration, but for some reason nothing shows up :)

**Comment by tajdars** [comment]
Not sure what happened with the file attached but here is my simplified application.yml
I source the host/port/username/password from spring cloud config.

The spring cloud config application.properties also has values for
spring.rabbitmq..
which overrides anything I put in the application.yml




spring:
  cloud: 
    stream: 
      bindings: 
        sleuth: 
          destination: sleuth 
          binder: sleuth
        springCloudBusInput: 
          destination: spring.cloud.bus.topic 
          binder: springCloudBus           
        springCloudBusOutput: 
          destination: spring.cloud.bus.topic.output 
          binder: springCloudBus           
      binders: 
        sleuth: 
          type: rabbit 
          defaultCandidate: false
          environment: 
            spring: 
              rabbitmq: 
                host: host1
                port: 5672 
                username: guest
                password: guest
        springCloudBus: 
          type: rabbit 
          defaultCandidate: false
          environment: 
            spring: 
              rabbitmq: 
                host: host2
                port: 5672 
                username: guest
                password: guest

**Comment by tajdars** [comment]
Attaching files.


[pom.txt](https://github.com/spring-cloud/spring-cloud-stream/files/779809/pom.txt)

[application.txt](https://github.com/spring-cloud/spring-cloud-stream/files/779816/application.txt)

**Comment by tajdars** [comment]
Setting inheritEnvironment: false at each binder level achieves what I was expecting.

But looks like each binder tries to download config from localhost:8888 and logs a warning.
Ignores the ConfigServer settings at the jvm level.

main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused: connect; nested exception is java.net.ConnectException:

**Comment by mbogoevici** [comment]
@tajdars yes - because the parent environment values are not propagated to the binder. Can you set the configuration properties for the config server in the binders themselves?

**Comment by mbogoevici** [comment]
hi @tajdars - I will close this for now - feel free to reopen or open a new issue if you need more clarifications.
