### ISSUE TITLE
Make Aggregated App easier to build

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream#809]
Model for building apps has been like this:
```
AggregateApplicationBuilder builder = new AggregateApplicationBuilder(FilegpfdistApplication.class, args);
builder
  .from(FileApp.class).args(args)
  .to(GpfdistApp.class).args(args)
  .run();
```
Trouble with this is that user needs to track down what existing apps actually do to figure out what `@Configuration` classes should get imported, etc.

It'd be relatively nice if with every OOB app we'd have a class which have a predictable name like `TimeSource` for time source, `LogSink` for log sink, etc. Then user could just add an annotation
```
@AggregatedApplication({TimeSource.class, LogSink.class})
```

As you pass arrays to annotations you could also keep order for processors.
```
@AggregatedApplication({TimeSource.class, My1Processor.class, My2Processor.class, LogSink.class})
```

Maybe i.e. `TimeSource` could be meta-annotation which OOB time source app could also use. These naming conventions would then make it predictable how aggregated app is created out of OOB apps.

**Comment by sobychacko** [comment]
The OOB apps themselves are named with the binder extension (For ex - TimeSourceKafka, LogSinkRabbit etc.). Not sure how that will help even if the app names are predictable.

**Comment by jvalkeal** [comment]
For example if using time source app you need to import `TimeSourceConfiguration`. While me mostly follow same conventions, it's not guaranteed that source app has only one config class named `<AppSourceConfiguration>`. Point was that `TimeSource` would always contain all what app needs.

**Comment by olegz** [comment]
With Spring Cloud Function and composition it's already simpler. Also, aggregator builder is deprecated
