### ISSUE TITLE
AbstractMessageChannelBinder should handle BeanFactory

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-stream#813]
- Currently `createConsumerEndpoint` is handled just by
  requesting a `MessageProducer` from a sub-class implementation.
  Then `InitializingBean` and `Lifecycle` interface methods are
  called to do normal spring logic. This is not enough for full
  spring bean logic as i.e. `BeanFactory` is missing.
- Normally spring INT components needs to know about `BeanFactory`,
  thus binder could also call what is wired from a `BeanFactoryAware`.
- For example any impls for `AbstractReplyProducingMessageHandler` will
  fail if `beanFactory` is not set. Binder kinda assumes that instance
  passed to it is not handled by spring app container, thus it calls these
  methods by itself.
- You could pass a full blown `AbstractReplyProducingMessageHandler` to
  a binder as  `@Bean` but then that may raise other issue like  `InitializingBean`
  might already being called. Spring expect  `afterPropertiesSet` to get called
  only once.

**Comment by olegz** [comment]
@jvalkeal this I believe is part of the general effort of _"beanifying"_ binders (which is ongoing). So while I agree with the problem the way you describe it I think the solution will fall naturally in place once _"beanifying"_ effort is complete. 
We can then revisit ii and see if anything else needs to be added but I'll close it for now.
