### ISSUE TITLE
Sources that @Autowire Source Cannot be Aggregated

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream#819]
>I receive an error message "Field channels in org.springframework.cloud.stream.app.tcp.source.TcpSourceCon‌​figuration required a single bean, but 2 were found: 1- Source 2- .Processor

See http://stackoverflow.com/questions/42346872/how-to-handle-message-using-spring-cloud-stream-app-starter-tcp/42347372#comment71855225_42347372

One solution might be to configure the output channel by name so it is bound to the actual channel at runtime.

**Comment by mbogoevici** [comment]
Could this possibly be caused by 2 components/apps in the same package? - see https://github.com/spring-cloud/spring-cloud-stream/issues/785. That is an issue with classpath scanning.

**Comment by garyrussell** [comment]
Ah, could be; I didn't ask him that; I just pushed a PR for tcp (it was missing a test too).

**Comment by garyrussell** [comment]
Although, he was aggregating a custom app with the TCP source so it would be odd if he used the same package.

**Comment by mbogoevici** [comment]
Thanks @garyrussell - looks like this is an offshoot of https://github.com/spring-cloud/spring-cloud-stream/commit/6c861135a3d4b4efb42d594af5df74c665598c8b - we now register the bindings as beans in the parent, but obviously that throws off injection in the children (seemed simpler to do that registration at the time, but the flipside is that this is causing injection issues). Seems easy to fix if we just query the proper child context for retrieving the binding.

**Comment by rattek** [comment]
Hi, I'm the one who have created the stackoverflow post. Here's my configurations. I hope it can helps!

**MessagingTcpDasApplication.java**
 ```
package tcp.das;
import org.springframework.cloud.stream.app.tcp.source.TcpSourceConfiguration;
[...]
@SpringBootApplication
@ComponentScan("org.springframework.cloud.stream.app.tcp")
public class MessagingTcpDasApplication {
	public static void main(String[] args) {
		new AggregateApplicationBuilder()
			.from(TcpSourceConfiguration.class)
			.to(DasDataHandler.class).run(args);
	}
}
```
**DasDataHandler.java**
```
package tcp.das.handler;
[...]
@EnableBinding(Processor.class)
public class DasDataHandler {
	  @Transformer
	  public String handle(String inStream) {
		  System.out.println("test"+inStream);
	    return "test";
	  }
}
```
**application.properties**
```
spring.main.web-environment=false
tcp.port=13100
spring.cloud.stream.bindings.output.destination= iwls.newData
```

**build.gradle**
```
dependencies {
	compile('org.springframework.cloud:spring-cloud-starter-stream-rabbit')
	compile('org.springframework.cloud.stream.app:spring-cloud-starter-stream-source-tcp:1.1.1.RELEASE')
	compile('org.springframework.boot:spring-boot-devtools')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

**Stack trace massage**

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Field channels in org.springframework.cloud.stream.app.tcp.source.TcpSourceConfiguration required a single bean, but 2 were found:
> 	- org.springframework.cloud.stream.messaging.Source: defined in null
> 	- tcp.das.handler.DasDataHandler_1.org.springframework.cloud.stream.messaging.Processor: a programmatically registered singleton
> 
> Action:
> 
> Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**Comment by mbogoevici** [comment]
Thanks @rattek,

This confirms my comment on https://github.com/spring-cloud/spring-cloud-stream/issues/819#issuecomment-281195091 - we have a bug we need to fix.
