### ISSUE TITLE
Error while consuming RabbitMQ message by a spring boot application which is listening for a message

### ISSUE THREAD

**Issue by chmaheshkrishna** [spring-cloud/spring-cloud-stream#824]
Hello,

I have a message producer Application which creates messages using spring RestTemplate, where as the consumer application is built using spring-boot which listens to the message.

Noticed that the content-type of the message was received as application/octet-stream in the spring-boot app. I have created a custom MessageConverter of type ByteArrayMessageConverter. I see the message is appearing as of RMQTestMessage type and I am not able to read the message in spring-boot consumer app. 

Can you please help in this.!

**Comment by artembilan** [comment]
Looks like your Consumer application doesn't have that `RMQTestMessage` class in its classpath. I guess you can't just deserialize those `byte[]`.

This kind of questions should go to StackOverflow.
We don't provide support via GH issues. They are for new features requests and bugs reports.

**Comment by artembilan** [comment]
Great!
Please, share an SO link here and close the issue in favor of that SO question.

**Comment by chmaheshkrishna** [comment]
Reported issue in stackoverflow(link below) and closing this issue.

http://stackoverflow.com/questions/42401574/spring-cloud-stream-unable-to-parse-message-posted-to-rabbitmq-using-spring-rest
