### ISSUE TITLE
Retry and Backoff

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-stream#858]
SCS leverages Spring Retry and for Spring Cloud Data Flow this underlying infrastruture is use. However, how can we configure Retry and Backoff strategies so that operationally streaming apps can set this to avoid continuously retry connections when RabbitMQ etc. have connection failures>

**Comment by olegz** [comment]
@hvandenb a quick prototype shows that this could be as simple as exposing RetryTemplate as `@Bean` which then could be overriden by a developer. Would that suffice?

**Comment by hvandenb** [comment]
@olegz Sounds simple enough. Having this in the documentation or sample repo will be very useful.
