### ISSUE TITLE
Document how to create custom binder implementation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#864]

**Comment by dsibilio** [comment]
@sabbyanandan I only just noticed your mention, thank you very much! I'm really glad you liked it 😄 

@olegz Thank you for featuring the article in the documentation 🥇 

Keep rocking it with your amazing work!

**Comment by olegz** [comment]
@dsibilio you are always welcome! And huge thanks for doing that.

On different note, if at some point you would like to contribute that article into our user guide, feel free to submit a PR and your name will always be featured at the header of our user guide along with all that have contributed to it.
