### ISSUE TITLE
Spring Boot fail to start with using @EnableBinding and zkNodes not available

### ISSUE THREAD

**Issue by TodorSusnjevic** [spring-cloud/spring-cloud-stream#868]
I have consumer with spring.cloud.stream.kafka.binder.brokers=KAFKA_URL spring.cloud.stream.kafka.binder.zkNodes=ZKNODE_URL

If I try to run spring boot consumer app and zkNode is not up, entire spring boot app fails to start: rg.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: ... Caused by: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 10000

My question is: how to overcome this and prevent entire app to crash and also how to periodically retry to connect?

**Comment by ilayaperumalg** [comment]
Hi,

Thanks for reporting.
This is being tracked here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/12

**Comment by ilayaperumalg** [comment]
Closing this as you can check the update in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/12
