### ISSUE TITLE
Kafka configuration section in the docs 404s

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream#875]
As a user, I'm trying to configure common properties for Kafka binder and the [relevant section](http://docs.spring.io/spring-cloud-stream/docs/Chelsea.RC1/reference/htmlsingle/#_configuration_options_2) in the reference guide [404s](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream-docs/src/main/asciidoc/spring-cloud-stream-overview.adoc#configuration-options).

**Acceptance:**
Fix docs link

**Comment by mbogoevici** [comment]
Hm, this should be a relative link.

**Comment by mbogoevici** [comment]
Closed and reopened in Stream Kafka.
