### ISSUE TITLE
Scheme Registry Server not working on standalone tomcat

### ISSUE THREAD

**Issue by TodorSusnjevic** [spring-cloud/spring-cloud-stream#877]
Using Chelsea.RC1. I have in application.properties:
spring.cloud.stream.schemaRegistryClient.endpoint=http://localhost:8080/csl
spring.cloud.stream.schema.server.path=/csl

Getting error:

`org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'df2'; nested exception is java.lang.RuntimeException: Failed to register schema: <302 Found,{Location=[/csl/], Transfer-Encoding=[chunked], Date=[Mon, 27 Mar 2017 12:13:58 GMT]}>, failedMessage=GenericMessage [payload`

from access log on tomcat 
"POST /csl HTTP/1.1" 302 -

Using postgres for DB. Everything works fine if I run spring boot main class manually with embedded tomcat.

**Comment by viniciusccarvalho** [comment]
Hi, we have tested this and answered the original question at stackoverflow. Here's a configuration that works:

```spring.cloud.stream.bindings.output.contentType=application/*+avro
server.port=8080
spring.cloud.stream.schemaRegistryClient.endpoint=http://localhost:8080/csl/
spring.cloud.stream.schema.avro.dynamic-schema-generation-enabled=true
spring.rabbitmq.addresses=192.168.99.100
spring.cloud.stream.schema.server.path=csl
```
