### ISSUE TITLE
Improve documentation on Schema Server and Client configuration options

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-stream#878]
We should add a little more content on how to setup the server path, and also the endpoint on the client. 

A section explaining how we decide whether to dynamic generate a schema, or how we retrieve schemas is also important.

**Comment by mbogoevici** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream/commit/44f66543d0e05dc3bf56cde7526393e3b54cd854
