### ISSUE TITLE
No Kafka Consumer Group listed by kafka-consumer-groups.sh

### ISSUE THREAD

**Issue by erichhsun** [spring-cloud/spring-cloud-stream#882]
Doh. I realized I was using the wrong command to see consumer groups. Since offset information is no longer stored in Zookeeper as of Kafka 0.9 but instead in an internal broker topic called __consumer_offsets, I needed to use this command instead:
`./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list --new-consumer`

Feel free to close.

(Kafka 0.10.0.1, spring-cloud-stream:1.1.0.RELEASE)

When I run the following command: `/kafka-consumer-groups.sh --zookeeper localhost:2181 --list`, the consumer group name I have specified under my `spring.cloud.stream.bindings.<channelName>.group` configuration does not show up, even though my consumers are correctly joining their groups and consuming their messages from their respective partitions (no duplicates).

Interestingly, if I use the deprecated `kafka-consumer-offset-checker.sh` tool, it's able to detect offsets for my group:
```
/usr/local/kafka/bin$ kafka-consumer-offset-checker.sh --zookeeper localhost:2181 --topic exampletopic --group examplegroup
[2017-03-27 16:48:24,460] INFO Accepted socket connection from /0:0:0:0:0:0:0:1:65036 (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2017-03-27 16:48:24,468] INFO Client attempting to establish new session at /0:0:0:0:0:0:0:1:65036 (org.apache.zookeeper.server.ZooKeeperServer)
[2017-03-27 16:48:24,469] INFO Established session 0x15aecd274c202c3 with negotiated timeout 30000 for client /0:0:0:0:0:0:0:1:65036 (org.apache.zookeeper.server.ZooKeeperServer)
Group           Topic                          Pid Offset          logSize         Lag             Owner
examplegroup    exampletopic                   0   1000            1000            0               none
examplegroup    exampletopic                   1   1000            1000            0               none
```

I have created a topic with 2 partitions and a replication factor of 1 using `kafka-topics.sh`, and specified the `instanceCount` and `instanceIndex` properties as suggested from https://github.com/spring-cloud/spring-cloud-stream/issues/526, but I am still not seeing the kafka consumer group, but perhaps I'm not supposed to.

I noticed in the [documentation](http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#consumer-groups), it says `Spring Cloud Stream consumer groups are similar to and inspired by Kafka consumer groups.` If Spring Cloud Stream isn't actually using Kafka Consumer Groups underneath, how is it synchronizing consumers in a consumer group?

I took a look inside `org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder`, and it seems like the groupId is being passed to the actual KafkaConsumer instance via the `getConsumerConfig` method and I can also see that ` o.a.k.clients.consumer.ConsumerConfig` is printing out the group.id.

The Kafka Broker logs also seem to be aware of the group id:
```
[2017-03-27 16:10:17,082] INFO [GroupCoordinator 0]: Stabilized group examplegroup generation 2 (kafka.coordinator.GroupCoordinator)
```

I am using the following dependency versions:
```
    compile     "org.springframework.cloud:spring-cloud-stream:1.1.0.RELEASE"
    compile     "org.springframework.cloud:spring-cloud-starter-stream-kafka:1.1.0.RELEASE"
    compile     "org.springframework.kafka:spring-kafka:1.1.0.M2"
    compile     "org.springframework.integration:spring-integration-kafka:2.1.0.M1"
    compile     "org.apache.kafka:kafka_2.11:0.10.0.1"
```

Any guidance is greatly appreciated, thanks.

**Comment by mbogoevici** [comment]
Thanks for asking the question @erichhsun. By the fact that it's closed I assume you figured out the issue by now. 

Just a quick observation. In version 1.0, which used Kafka 0.8 we were not using the high-level client, but we were using the consumer group API support. Starting with release train Brooklyn (which uses 1.1 versions of the binder) we are using Kafka 0.9+ (0.10 in your case) and full consumer group support.
