### ISSUE TITLE
Spring Cloud Stream Metrics may emit stale metrics when application is inactive

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#883]
Due to the way in which Spring Boot collects Spring Integration metrics, it clashes with the lazy metrics update strategy of Spring Integration - that is, if there is no traffic, the metric values do not get updated. The solution is either to fix this upstream or provide a way to collect Spring Integration metrics correctly.

**Comment by sabbyanandan** [comment]
Depends on Spring Integration 4.3.9.
