### ISSUE TITLE
Fix metrics doc section

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-stream#902]
The docs indicate you can set delay, includes and excludes under the key `spring.cloud.stream.metrics`, but those properties are really under the control of boot with the prefix `spring.metrics.export`.  The docs should discuss the include/exclude props a bit since I think they aren't that well described in the boot docs.  There should be a link to the boot docs also http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metric-writers

**Comment by markpollack** [comment]
Also the example payload isn't accurate, should remove `instanceIndex`.   Prob best to run a sample and do a cut-n-paste job.

**Comment by mbogoevici** [comment]
List `spring.metric.exporter.triggers.application.*` as an finer-grained option.  (Also wrt fixing #903 ).
