### ISSUE TITLE
hdfs-datasets-sink - SIGTERM != graceful shutdown

### ISSUE THREAD

**Issue by bakabo** [spring-cloud/spring-cloud-stream#920]
Issue: 
There is a logical difference between SIGTERM and the /shutdown endpoint. But doesn't appear to be a difference between SIGKILL vs SIGTERM.
Attached are logs that show a scenario with 2 different kill sequences.

Reproducable steps.
Scenario 1: 
1. Start the hdfs-datasets-sink
2. Send a message to cache in the MessageStore
3. Send /shutdown request

Scenario 2:
1. Start the hdfs-datasets-sink
2. Send a message to cache in the MessageStore
3. kill -15 PID

The first scenario will gracefully shutdown. Meaning the data in the MessageStore will be flushed to disk.
The second scenario will not gracefully shutdown. The hook to HDFS will be closed before the MessageStore can flush the cache, resulting in an exception being thrown. 
- "Caused by: java.io.IOException: Filesystem closed"

Configurations.
hdfs.dataset:
  fs-uri: hdfs://localhost
  batch-size: 3
  idle-timeout: 10000
  format: parquet

endpoints.shutdown:
  sensitive: false
  enabled: true

Versions:
org.springframework.cloud.stream.app:spring-cloud-starter-stream-sink-hdfs-dataset:1.1.1.BUILD-SNAPSHOT
org.springframework.integration:spring-integration-kafka:2.1.0.RELEASE

org.springframework.cloud:spring-cloud-stream
org.springframework.cloud:spring-cloud-stream-schema
org.springframework.cloud:spring-cloud-stream-binder-kafka
org.springframework.cloud:spring-cloud-starter-consul-all

mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Camden.SR5'

[sink_kill_sigterm.txt](https://github.com/spring-cloud/spring-cloud-stream/files/917859/sink_kill_sigterm.txt)
[sink_shutdown_endpoint_graceful.txt](https://github.com/spring-cloud/spring-cloud-stream/files/917860/sink_shutdown_endpoint_graceful.txt)

**Comment by mbogoevici** [comment]
Hi,

This repository is for Spring Cloud Stream core features only. For specific issues with the HDFS sink please open an issue here: https://github.com/spring-cloud-stream-app-starters/hdfs .

**Comment by bakabo** [comment]
moved to https://github.com/spring-cloud-stream-app-starters/hdfs/issues/3
