### ISSUE TITLE
Docs for Stream in Brixton docs appear to have broken images

### ISSUE THREAD

**Issue by rseroter** [spring-cloud/spring-cloud-stream#924]
Broken image links here: http://cloud.spring.io/spring-cloud-static/Brixton.SR7/#_main_concepts

**Comment by sabbyanandan** [comment]
Hi, @rseroter. Thanks for reporting! The recent [Dalston.RELEASE](http://cloud.spring.io/spring-cloud-static/Dalston.RELEASE/#_main_concepts) (_includes Stream's [Chelsea.SR1](https://spring.io/blog/2017/04/13/spring-cloud-stream-chelsea-goes-ga)_) render the images properly. We will address the Brixton docs.

**Comment by mbogoevici** [comment]
@rseroter Unfortunately, there is an issue with how earlier Spring Cloud versions aggregate documents. As a side note, Spring Cloud Stream publishes its own documentation (as it is a release train in and by itself) - see http://cloud.spring.io/spring-cloud-stream/ and the links for reference documentation for Brooklyn (included in Camden), Chelsea (included in Dalston) and 1.0 (included in Brixton).

**Comment by mbogoevici** [comment]
Closing this as it is fixed in Dalston http://cloud.spring.io/spring-cloud-static/Dalston.RELEASE/#_rabbitmq_binder as indicated by @marcingrzejszczak.
