### ISSUE TITLE
HDFS source

### ISSUE THREAD

**Issue by ap1256** [spring-cloud/spring-cloud-stream#925]
I am looking to read data from HDFS. I don't see a HDFS source. All I see is HDFS sink. Would I be able to use fie source to read form HDFS?

**Comment by mbogoevici** [comment]
Hi @ap1256 - this repository deals with issues in the Spring Cloud Stream core. The HDFS starter is in https://github.com/spring-cloud-stream-app-starters/hdfs - I'd suggest to open an issue there.

**Comment by ap1256** [comment]
Ok thanksSent from XFINITY Connect Mobile App------ Original Message ------From: Marius BogoeviciTo: spring-cloud/spring-cloud-streamCc: ap1256, MentionSent: April 21, 2017 at 2:18 PMSubject: Re: [spring-cloud/spring-cloud-stream] HDFS source (#925)Hi @ap1256 - this repository deals with issues in the Spring Cloud Stream core. The HDFS starter is in https://github.com/spring-cloud-stream-app-starters/hdfs - I'd suggest to open an issue there.
