### ISSUE TITLE
random 'Dispatcher has no subscribers for channel' behaviour

### ISSUE THREAD

**Issue by pts-danielmanley** [spring-cloud/spring-cloud-stream#928]
Hi -- I've got a spring boot application where a front end listens for RESTful requests and sends messages to another spring boot application in the same JVM to do work.  the front end, before sending, creates a new topic on the fly based on a sequence number and includes that sequence number in the request to the back so that it knows to which topic to send the reply.  it blocks for 20 seconds in polling for the response.  it then deletes the topic when it's done receiving the response (or after timeout).  the backend is an `@StreamListener`

my problem is that the application behaves randomly between bootruns -
1) round trip requests/responses work 100%
2) round trip requests/responses work after a first failure where the backend replies on the unique response topic, but the front end, on a poll of 20 seconds, times out with no response
3) 100% failure where the logs say 'Dispatcher has no subscribers for channel' and the backend listener method is never called
4) same as 2 or 3, but after starting up, the listener picks up all of the "lost" messages from the previous round of tests

I'm somewhat new to Spring, but I've scoured the net for samples and pieced this together.  why would it work randomly like that?

The consumer...  note that logging shows that the `@PostConstruct` method is always invoked without fail.  I tried the class as a Service as well. 
```
@Component
@Slf4j
public class MessageConsumer {

  @Autowired
  KafkaTemplate<String, String> kafkaTemplate;

  @Autowired
  JsonMapper jsonMapper;

  @PostConstruct
  public void init() {
    System.out.println("MessageConsumer.init()");
    log.debug("MessageConsumer.init()");
  }

  @StreamListener(PartnerIntegrationRequest.PARTNER_INTEGRATION_REQUEST_LISTENER)
  public void receive(String payload) {
    log.info("got message: " + payload);

    Map<String, Object> payloadData = jsonMapper.parse(payload);
    String transactionId = (String) payloadData.get(Constants.TRANSACTION_ID.getValue());
    payloadData.put(Constants.STATUS.getValue(), "success");

    String topicName = "response-" + transactionId;
    log.debug("replying to topic ["+topicName+"]");
    kafkaTemplate.send(topicName, transactionId, jsonMapper.stringify(payloadData));
  }

}
```

The interface ...
```
public interface PartnerIntegrationRequest {

  public static final String PARTNER_INTEGRATION_REQUEST_PRODUCER = "partnerIntegrationRequestProducer";
  public static final String PARTNER_INTEGRATION_REQUEST_LISTENER = "partnerIntegrationRequestListener";

  @Output
  MessageChannel partnerIntegrationRequestProducer();

  @Input
  SubscribableChannel partnerIntegrationRequestListener();
}
```

Front end sending code....
``` 
private boolean sendMessageToPartnerIntegration(String stringify) {
    log.debug("sending message: {}", stringify);
    boolean result = partnerIntegrationRequest.partnerIntegrationRequestProducer().send(new GenericMessage<String>(stringify),
        10000);
    log.debug("send result {}", ""+result);
    return result;
  }
```

and front-end properties:
```
spring.cloud.stream.bindings.partnerIntegrationRequestProducer.destination=partnerIntegrationRequestListener
spring.cloud.stream.bindings.partnerIntegrationRequestProducer.content-type=application/json
spring.cloud.stream.bindings.partnerIntegrationRequestListener.destination=partnerIntegrationRequestListener
spring.cloud.stream.bindings.partnerIntegrationRequestListener.content-type=application/json
spring.cloud.stream.bindings.partnerIntegrationRequestListener.group=integrationsGroup
spring.cloud.stream.bindings.partnerIntegrationResponse.destination=endpointsResponseTopic
spring.cloud.stream.bindings.partnerIntegrationResponse.content-type=application/json
#spring.cloud.stream.bindings.partnerIntegrationResponse.group=endpointsGroup
spring.cloud.stream.kafka.bindings.input.consumer.resetOffsets=true
```

for the backend properties, they are identical except that I have resetOffsets commented out.  Hacking away with various little tweaks to see it work or not.

**Comment by pts-danielmanley** [comment]
additional note for no.2 above - I compared logging for good and bad runs -- a run where the backend replies but the frontend never gets it: the front end logging said it was going for offset 1 of the temp topic.  whereas the good run logged that it was going for offset 0.  so I'm seeking to offset 0 all the time.  why does this have to be done on a unique/fresh/temp topic?

```
    responseConsumer.subscribe(Collections.singletonList(topicName));
    responseConsumer.poll(1);
    responseConsumer.seek(new TopicPartition(topicName, 0), 0);

    sendMessageToPartnerIntegration(message);

    String response = null;

    log.debug("polling " + topicName);
    ConsumerRecords<String, String> records = responseConsumer.poll(20000);
```

**Comment by pts-danielmanley** [comment]
I think I've found the problem spot in the logs.  when the listener doesn't work, it's final logs are these:

```
2017-04-21 13:44:05.493  INFO [-,,,] 27226 --- [afka-consumer-1] o.s.c.s.b.k.KafkaMessageChannelBinder$1  : partitions revoked:[]
2017-04-21 13:44:08.354  INFO [-,,,] 27226 --- [afka-consumer-1] o.s.c.s.b.k.KafkaMessageChannelBinder$1  : partitions assigned:[]
```

but when it works, the partitions assigned *is* the topic I want.

**Comment by pts-danielmanley** [comment]
I've looked at logs in debug.  this is a successful startup:
```
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Joined group: {error_code=0,generation_id=181,group_protocol=range,leader_id=consumer-1-8d0b3838-7e9a-44e5-a9a6-44d33ae26322,member_id=consumer-1-61b8370d-3cb5-4059-a5f8-9e8b61967d4e,members=[]}
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Issuing follower SyncGroup (SYNC_GROUP: {group_id=integrationsGroup,generation_id=181,member_id=consumer-1-61b8370d-3cb5-4059-a5f8-9e8b61967d4e,group_assignment=[]}) to coordinator 2147483647
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Received successful sync group response for group integrationsGroup: {error_code=0,member_assignment=java.nio.HeapByteBuffer[pos=0 lim=53 cap=53]}
--- [afka-consumer-1] o.a.k.c.c.internals.ConsumerCoordinator  : Setting newly assigned partitions [partnerIntegrationRequestListener-0]
--- [afka-consumer-1] o.a.k.c.c.internals.ConsumerCoordinator  : Fetching committed offsets for partitions: [partnerIntegrationRequestListener-0]
--- [afka-consumer-1] o.a.k.c.consumer.internals.Fetcher       : Resetting offset for partition partnerIntegrationRequestListener-0 to the committed offset 174
--- [afka-consumer-1] o.a.k.c.c.internals.ConsumerCoordinator  : Committed offset 174 for partition partnerIntegrationRequestListener-0
--- [afka-consumer-1] o.s.c.s.b.k.KafkaMessageChannelBinder$1  : partitions assigned:[partnerIntegrationRequestListener-0]
--- [afka-consumer-1] org.apache.kafka.common.metrics.Metrics  : Added sensor with name topic.partnerIntegrationRequestListener.bytes-fetched
--- [afka-consumer-1] org.apache.kafka.common.metrics.Metrics  : Added sensor with name topic.partnerIntegrationRequestListener.records-fetched
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Received successful heartbeat response.
```

this is a startup where the listener doesn't pickup any messages:
```
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Joined group: {error_code=0,generation_id=179,group_protocol=range,leader_id=consumer-1-8d0b3838-7e9a-44e5-a9a6-44d33ae26322,member_id=consumer-1-aa7c589d-510f-4482-a579-b7b41ff92a51,members=[]}
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Issuing follower SyncGroup (SYNC_GROUP: {group_id=integrationsGroup,generation_id=179,member_id=consumer-1-aa7c589d-510f-4482-a579-b7b41ff92a51,group_assignment=[]}) to coordinator 2147483647
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Received successful sync group response for group integrationsGroup: {error_code=0,member_assignment=java.nio.HeapByteBuffer[pos=0 lim=10 cap=10]}
--- [afka-consumer-1] o.a.k.c.c.internals.ConsumerCoordinator  : Setting newly assigned partitions []
--- [afka-consumer-1] o.s.c.s.b.k.KafkaMessageChannelBinder$1  : partitions assigned:[]
--- [afka-consumer-1] o.a.k.c.c.internals.AbstractCoordinator  : Received successful heartbeat response.
```
I've noticed that when it's not going to work, the lim and cap are 10 each - `java.nio.HeapByteBuffer[pos=0 lim=10 cap=10]}` - but when it's going to work, they are 53 each.

**Comment by mbogoevici** [comment]
@pts-danielmanley Thanks for reaching out. `Dispatcher has no subscribers for channel` typically means that some beans are initialized in the wrong order. It's hard to tell what is going on there just from publishing/subscribing code. Would it be possible to publish a complete example that reproduces what you're experiencing?

**Comment by pts-danielmanley** [comment]
so, I paired down my code so that it was down to the basics of what I described earlier (no DB, no other parts of the project, etc).  and I started the app and it properly got the "partitions assigned" message every time and I got a round trip message to work.  i.e. I could not reproduce the failure scenario at all.  For fun, I went back to the original code base, and I've tried it now and it's 100% working from all my restart attempts so far.

One thing I had changed late on Friday was to remove an `@PostConstruct` method that did logging that I used to show that the bean was truly being initialized.  I did that after you said about bean order issues.  but I thought my runs on Friday were still showing failure start ups.  But now it's working.  It's truly the only change I made.  so I will keep an eye on this for the next few days and if it appears to be fixed, then I'll blame the PostConstruct usage.  What are your thoughts?

for the record, I had re-enabled the PostConstruct in the paired down code set.  perhaps it wasn't an issue because of the removal of all the beans from the rest of the project.

**Comment by pts-danielmanley** [comment]
I think I might have found the problem.... the interface for the `@Output` and `@Input` annotations was common between the REST front end and the processing backend (ie. for `@EnableBinding`).  The issue appears to be that randomly, the REST front end will steal the subscription to the topic even though it doesn't have an `@StreamListener` defined.  I noticed this because I just happen to CTRL-C the front end JVM when the backend JVM was still running and had been revoked from the partition.  as soon as the front end died, the backend logged that it was assigned the partition.  so I've reworked the project so that the `@Output` and `@Input` are in separate interfaces so that the front end won't register as a subscriber-like thing.

**Comment by mbogoevici** [comment]
Hi @pts-danielmanley - thanks for following up. Indeed, using the same channel name for an input and an output within the same application will yield very impredictable results. Is there anything else we can help with or can this issue be closed?

**Comment by pts-danielmanley** [comment]
Hi -- yes, I have a much better understanding of this setup now.  all is working with those changes.  thanks very much for all your help.  this can be closed.

**Comment by jkinzer** [comment]
@pts-danielmanley we just ran into this issue in our application that is using consumers and producers in the same application over the same channels. It seems like there is an opportunity for improvement here: the framework could throw an error if it attempts to bind a consumer and producer on the same channel name?
