### ISSUE TITLE
Synchronisation problem when resolving the channel

### ISSUE THREAD

**Issue by FcoJavierSainz** [spring-cloud/spring-cloud-stream#931]
Hi, We are getting an strange error when we try to get a channel 
`Could not register object [org.springframework.integration.channel.DirectChannel@2898b3cc] under bean name 'topic_name': there is already object [topic_name]`

I am using `BinderAwareChannelResolver::resolveDestination(topicName)`

Do you think we need to use a synchronized context there? Normally happens when we use concurrent threads at the beginning

**Comment by mbogoevici** [comment]
@FcoJavierSainz Could be a concurrency issue - what version of the framework are you using?

**Comment by FcoJavierSainz** [comment]
Here is the SCS version
```
dependencyManagement {
     imports {
          mavenBom 'org.springframework.cloud:spring-cloud-stream-dependencies:Brooklyn.SR3'
     }
}
```
And here the dependencies, we override `spring-integration-kafka`

```dependencies {
	compile 'org.springframework.integration:spring-integration-kafka:2.1.0.RELEASE'
	compile 'org.springframework.cloud:spring-cloud-stream'
	compile 'org.springframework.cloud:spring-cloud-starter-stream-kafka'
	compile('org.apache.kafka:kafka-clients:0.10.0.1') {
		exclude module: 'slf4j-log4j12'
	}```

**Comment by garyrussell** [comment]
@mbogoevici see my comment in Gitter - we need to recheck the bean can't be resolved inside the `synchronized` block.

**Comment by garyrussell** [comment]
I am on it.

**Comment by mbogoevici** [comment]
Thanks @garyrussell :)
