### ISSUE TITLE
Support default content type setting

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-stream#936]
I want all of my channels to use JSON serialization instead of the default Kryo. I can set the (output) content type on a per-channel basis using `spring.cloud.stream.bindings.<channelName>.content-type`, but this requires listing every channel individually.

I would like to be able to set a property such as `spring.cloud.stream.defaults.content-type=application/json` to make JSON the default.

(Also, there may currently be a way to do this programmatically in JavaConfig, but I haven't been able to figure out how; if there is, it would be a helpful addition to the docs.)

**Comment by mbogoevici** [comment]
Hi,

This is currently supported as of the Chelsea release train as`spring.cloud.stream.default.content-type` - see  http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR1/reference/htmlsingle/#binding-properties .

**Comment by chrylis** [comment]
I had managed to miss that, sorry! (As a note, STS doesn't recognize the `default` namespace. I don't know whether that's practical to remedy.)

**Comment by mbogoevici** [comment]
No problem - could be a metadata issue!
