### ISSUE TITLE
Lift void restriction on multiple @StreamListeners

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-stream#937]
Currently, dispatching to multiple listeners inside a single binding is supported, but only if no listener returns a value. By contrast, inside a single JVM, `@EventListener` can be used to "fan out" messages arbitrarily, including when listeners re-fire their own events. There's also nothing preventing `@StreamListener` methods from sending messages programmatically.

I suggest removing the restriction on returning/re-dispatching values from multiple listeners. The semantics of returning a value are well-defined, and the semantics of returning values from multiple listeners are not ambiguous.

**Comment by olegz** [comment]
Given that we are moving toward functional programming model we are not going to be adding any more enhancements to Stream Listener
