### ISSUE TITLE
JSON contentType handling when serializing the payload

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream#941]
When setting the `contentType` message header, the original content type from the payload should be checked with MimeType's type/subtype/parameter. 

For instance, the original contentType with the value `application/json;charset=UTF-8` currently serialized with the contentType `text/plain` based on this logic [here](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/AbstractBinder.java#L308)

**Comment by viniciusccarvalho** [comment]
@ilayaperumalg Could we make #940 as part of this issue?
