### ISSUE TITLE
Provide Kafka sink app starter

### ISSUE THREAD

**Issue by hekonsek** [spring-cloud/spring-cloud-stream#946]
Hi,

I would be interested in having Kafka sink available for Spring Cloud Stream. I'd like to use Kafka not only as binding messaging middleware, but rather forward messages from endpoints like HTTP or WebSocket into certain Kafka topics (and under certain message key). Topic and message key should be resolved from an incoming payload using SpEL.

I have created Kafka sink app starter [1] - do you think that it could be contributed as app starter project [2]? I guess that serious Kafka users will end up asking for sink like this.

Cheers!

[1] https://github.com/hekonsek/spring-cloud-kafka-app-starters
[2] https://github.com/spring-cloud-stream-app-starters

**Comment by markfisher** [comment]
The router sink does support SpEL as a way to determine what destination to send to (where destination can be any Kafka Topic in the case that the Router sink app is using the Kafka Binder): https://github.com/spring-cloud-stream-app-starters/router/tree/master/spring-cloud-starter-stream-sink-router

Would that be sufficient for your use-case?

**Comment by hekonsek** [comment]
Many thanks, Mark. Please correct me if I'm wrong but it seems that it is impossible to set Kafka message key using generic router. My implementation of sink allows you to do so using expression, so you can for example you can create a stream which binds certain HTTP header from source to target Kafka message key. Control over message key binding is a must-have for Kafka-based applications written in event-sourcing-like spirit promoted [1] by Confluent for example.

Also in the future some users might request additional control over the message sent to the Kafka (like control over partition ID, timestamp, timeout, acknowledgement level, etc). But controlling key is essential, so this is what I included in a base version of my sink.

Actually I think that any user willing to use Kafka more as a data hub, than plain messaging broker, will have the same requirement as I have :) . 

[1] https://www.confluent.io/making-sense-of-stream-processing-ebook-download/

**Comment by mbogoevici** [comment]
@hekonsek You can't set the message key via the router, but you have a few options to set the key in a regular application right now by setting the `KafkaHeaders.MESSAGE_KEY` header of the outbound message.

>Also in the future some users might request additional control over the message sent to the Kafka (like control over partition ID, timestamp, timeout, acknowledgement level, etc). But controlling key is essential, so this is what I included in a base version of my sink.

This is what we intend to do in the Kafka-specific binding consumer/producer properties - see http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR1/reference/htmlsingle/#_configuration_options_2.  We would prefer to enhance support for that as the sink is not fundamentally different from any other outbound producer - this saves us effort from maintaining a separate component (the sink). 

For solving this problem, I think it would be better to simply support  `messageKeyExpression` in the Kafka producer properties - i.e. http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR1/reference/htmlsingle/#_kafka_producer_properties.

**Comment by mbogoevici** [comment]
It goes without saying that the interest and feedback are highly appreciated :)

**Comment by hekonsek** [comment]
Many thanks, Marius. Let me check out if I can handle this use case using Kafka binder options - I hope so, as Kafka binder seems to be a better place for this kind of logic. I will open new issue under [1] so we can continue the discussion there.

Many thanks again!

[1] https://github.com/spring-cloud/spring-cloud-stream-binder-kafka

**Comment by hekonsek** [comment]
Closing on the behalf of https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/130 .
