### ISSUE TITLE
Consider dropping the redundant 'originalContentType' when headers are embedded

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#948]
When headers are embedded, having the `contentType`/`originalContentType` pair serves no purpose whatsoever, as `contentType` would always be overriden by `originalContentType`. We can drop it and while keeping things backwards compatible.

**Comment by smaudet** [comment]
This seems to be an especially valid use case if producing content for downstream non SCSt applications.

The current workaround is to manually specify contentType as a header on every message (where we care).

**Comment by mbogoevici** [comment]
As discussed with @garyrussell and @viniciusccarvalho we might want to do away with `originalContentType` completely.

**Comment by viniciusccarvalho** [comment]
We have agreed on dropping originalContentType for 2.0. The set of stories tagged with content-type-improvements will provide all the functionality to drop it, and support a legacy mode to read from 1.x producers
