### ISSUE TITLE
rabbitmq producer retry

### ISSUE THREAD

**Issue by tajdars** [spring-cloud/spring-cloud-stream#951]
spring-cloud-stream-binder-rabbit: 1.2.0.M1

```
org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder.createProducerMessageHandler
```
This method doesn't set any retry properties on `RabbitTemplate`

```
spring.rabbitmq.template.retry.*
```

How does the producer retry a failed publish (caused by for example a broker restart) ?

Thanx,

**Comment by artembilan** [comment]
From an external discussion:

> I’m noticing some unexpected behavior when trying to publish a message to RabbitMQ via Spring Cloud Stream. I’m using a TCP load balancer to balance connections between nodes in the RabbitMQ cluster. I’m testing the situation in which a node goes down but for a brief period the load balancer might still route requests to that node. In that case, the publisher, if routed to the down node fails to establish a connection and throws an exception. This is unexpected because I have spring.rabbitmq.template.retry.enabled: true set, which I expected would cause it to retry even if the connection attempt failed the first time. In fact, if I try using the auto-configured RabbitTemplate directly without Spring Cloud Stream, it is exhibiting the behavior I expect: a WARN log is published for the initial connection failure but it retries and the load balancer routes to the good node, a connection is established, and the message is successfully published.

IMO should be moved to the https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues

//CC @shakuzen

**Comment by tajdars** [comment]
Thanx @artembilan. Yup i agree. Will you be moving this ?

**Comment by artembilan** [comment]
Moved to https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/69
