### ISSUE TITLE
Spring Cloud Stream attaches, by default, a contentType header to outbound messages.

### ISSUE THREAD

**Issue by jprateekvmware** [spring-cloud/spring-cloud-stream#952]
Spring Cloud Stream attaches, by default, a contentType header to outbound messages.

http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/contenttypemanagement.html

Do i have the option to disable having contentType appended in the messages ?

 contentType
"text/plain"originalContentType2"application/x-java-object;type=java.util.HashMap"{"a

**Comment by olegz** [comment]
Hmm, not sure I fully understand. Are you saying you want to modify the content of the message by appending 'contentType' to the end of the content of the actual message?

**Comment by jprateekvmware** [comment]
I just want the payload to be published without contentType information, only JSON content
**contentType
"text/plain"originalContentType2"application/x-java-object;type=java.util.HashMap"**{"attributes":{"type":"Account","url":"/services/data

**Comment by ilayaperumalg** [comment]
@jprateekvmware The `contentType` here reflects the content type used by the corresponding `binder` during serializing the `payload` and this content type will be used when `de-serializing` the payload at the receiving side. The `originalContentType` is the actual contentType of the message which will be updated as `contentType` to the message after `de-serialization` at the consumer.

I think you need  `spring.cloud.stream.bindings.<channelName>.producer.headerMode=raw` in your case where you handle the message headers natively.

**Comment by olegz** [comment]
@jprateekvmware some of us have been discussing it internally and it would probably help if you share your use case a bit so we can understand why you don't want the header information. The embedded content type is primarily for internal use to be able to deal with messaging middleware that does not play well with headers (e.g., Kafka), but it should be completely transparent to you by the time you actually see the `Message<?>`, so personally I am still not sure what you are trying to accomplish.

**Comment by jprateekvmware** [comment]
@ilayaperumalg  not working
@olegz one of our consumer is not able to parse the JSON because of the header present. I have it working fine with no Issues with Most of the Sink. I am addressing the issue for one of our consumer of kafka queue, who is not within the SCS workflow.

return s.decode('utf-8')
  File "/usr/lib64/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by olegz** [comment]
Ok, I think that makes a bit more sense to me now - _". . .who is not within the SCS workflow. . ."_ since that is where the transparency I was talking about is gone.
You may want to try `org.springframework.cloud.stream.binder.EmbeddedHeaderUtils`
```java
MessageValues mv = EmbeddedHeaderUtils.extractHeaders(msg);
byte[] rawPayloadNoHeaders = mv.getPayload();
```

While the above may allow you to parse out ray payload, I am still wondering why suggestion from @ilayaperumalg is not working for you? I was assuming that by doing so the message would have no embedded headers.

**Comment by olegz** [comment]
Also, to better understand where everything is happening you may wan to look at `org.springframework.cloud.stream.binder.AbstractMessageChannelBinder`

**Comment by mbogoevici** [comment]
@jprateekvmware can you explain what is not working when you set `spring.cloud.stream.bindings.<channelName>.producer.headerMode=raw` ? It disables the embedding of headers (including contentType) into messages.

**Comment by jprateekvmware** [comment]
Passing it at the deployment time.
app.<application-name>.spring.cloud.stream.bindings.output.content-type=application/json
app.<application-name>.spring.cloud.stream.bindings.output.producer.headerMode=raw

Below is the error message.
Raw mode supports only application/octet-stream content typeclass java.lang.String

**Comment by mbogoevici** [comment]
What version are you using? This was as issue ( #855 ) that has been fixed since `Chelsea.RELEASE`.

**Comment by jprateekvmware** [comment]
Thanks I saw that , let me try with Chelsea.RELEASE release

**Comment by jprateekvmware** [comment]
Now its working @ilayaperumalg 
Thanks everyone for your support  and quick resolution.
have got it closed. Got little struck with common NoSuchMethodError with spring now a days but have it resolved.

Publishing pom snippet for anyone to put up dependencies. would be closing the issue.

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.3.RELEASE</version>
		<relativePath /> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud-dependencies.version>Dalston.RELEASE</spring-cloud-dependencies.version>
	</properties>

	<dependencies>
		
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>0.10.2.1</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>

**Comment by jprateekvmware** [comment]
Fixed based on recommendation from the Spring team.

**Comment by DevD08** [comment]
Hi @jprateekvmware ,

I am facing the same issue while i am trying to publish something over kafka in json format, using BinderAwareChannelResolver. Could you please help me with the fix

**Comment by olegz** [comment]
@DevD08 please do NOT comment on the closed and very old issue especially without providing any essential details. 
I appreciate you doing research, which helps with the context but please if you have an issue raise it as a new issue and optionally link to this one.
