### ISSUE TITLE
Decouple StreamListener from strict annotation processing only

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream#954]
Currently, StreamListener can only be used through `@StreamListener` annotation. We need to extract the common logic behind the functionality of a `StreamListener` into a possible API so that both annotation processing and dynamic registration of beans may use it.

**Comment by olegz** [comment]
Keep in mind that most if not all of it's functionality is on `StreamListenerAnnotationBeanPostProcessor` and ~60%+ of what `StreamListenerAnnotationBeanPostProcessor` does is already implemented `ServiceActivatingHandler` and its dependencioes. In fact the only thing it does extra is "conditional" and declarative handlers (i.e., Function). 
So if anything I'd probably start by extending from its SI counterpart.

**Comment by olegz** [comment]
Given that we are deprecating StreamListener there shouldn't be any more enhancements/features
