### ISSUE TITLE
Support setting a default destination name for SI channels

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-stream#961]
As described in #949, I have a case where I want to be able to bind both input and output channels to the same underlying message queue. Since SCS models bindings as one-to-one with channels, this requires enumerating every input and output channel in properties, which quickly gets unwieldy because of the inability to trivially compose Boot `application.properties`.

For cases like this (and potentially others), it would be useful to be able to override the _binding_ name that's applied to a channel. For example, given this code:

```
@Input(target = "message.input", binding = "message-binding")
...

@Output(target = "message.output", binding = "message-binding")
```

SCS would pull the binding properties (destination, content-type converters) for both of these channels from the same place, ensuring that changes to them are applied consistently. (In this case, among other implications, messages would be assured to loop back into the input channel when sent through the output channel.)

The default if no `binding` attribute is applied would simply be the `value`.

**Comment by mbogoevici** [comment]
> @Input(target = "message.input", binding = "message-binding")

Thanks @chrylis for submitting this - we'd probably want to call it `defaultDestination` as in the original discussion, as 'binding' has a different meaning (and gets constantly overloaded).

**Comment by dsyer** [comment]
I'm confused about what a "target" is as well. If it's a bean name, or channel name, maybe it could be given a more obvious correlation to what it will be used for?

**Comment by chrylis** [comment]
@dsyer `target` is the existing name for the attribute, and it's the channel name, I think.

@mbogoevici Perhaps the precise semantics I was seeking aren't feasible, but I was _specifically_ not referring to `defaultDestination`. I want to be able to specify `spring.cloud.stream.bindings.message-binding.destination: mbqueue` and have that destination configuration apply to both the input and output directions atomically.

**Comment by mbogoevici** [comment]
It's called 'target' as it is the binding target - we support other bindable targets such as `Flux`, `KStream`, etc.

@chrylis 
> I want to be able to specify spring.cloud.stream.bindings.message-binding.destination: mbqueue and have that destination configuration apply to both the input and output directions atomically.

I don't think it is unfeasible, but it requires a pretty serious reconsideration of the model. Basically creating a single 'binding' with separate channels for producers and consumers (which goes back to the 'scoping' discussion you brought).

Given that this is meant to solve a very specific use case (bus-like interaction), which might be a very popular one, but it is relatively easily (even if not tersely) solvable by providing configuration properties, it is hard to make it an immediate priority. 

We will try to fit this one roadmap, but in the mean time, if you are up to it and would like to contribute the feature, we are happy to help in any way we can.

**Comment by chrylis** [comment]
I'll look into it, but it won't be soon. At least part of my difficulty is that I've had a hard time understanding the documentation of the system model, and especially how SCS and SI relate and interaction patterns. When I get a chance (after this project is off the ground), I may start by trying to enhance the docs.

**Comment by mbogoevici** [comment]
Thanks - any contribution, large or small, is appreciated!

**Comment by chrylis** [comment]
One clarification: Part of the reason for the proposal is that I understood _the binding_ and _the channel_ to be distinct concepts. If they aren't, then the model change makes less sense, but if they are, I'm unclear why there are multiple terms.

**Comment by mbogoevici** [comment]
We should probably provide a better description of it, but a binding is an input or output connected to an external messaging system. The 'binding target' is the bean or the element that's referenceable by a `@StreamListener` for example. In most examples that we provided the binding targets are Spring Messaging/Spring Integration `MessageChannel` instances created by the framework, but they are not exclusively channels. For example, we want to support bindings to Kafka Streams - https://github.com/mbogoevici/spring-cloud-stream-binder-kstream/blob/master/spring-cloud-stream-binder-kstream/src/main/java/org/springframework/cloud/stream/kstream/annotations/KStreamProcessor.java or Reactive Streams-backed Reactor `Flux`: https://github.com/mbogoevici/spring-cloud-stream-binder-reactive-streams/blob/master/spring-cloud-stream-binder-reactive-streams-core/src/main/java/org/springframework/cloud/stream/reactive/ReactiveProcessor.java , none of which operates with the Spring Integration model.  

This why in the common use case the 'binding' and the 'channel' overlap, but in the general case a binding might not strictly refer to a channel.

**Comment by olegz** [comment]
Actually we consider binding input and output to the same destination an anti-pattern and actually have an issue to explicitly disallow it, we won't be addressing it.
