### ISSUE TITLE
Consumer pause/resume

### ISSUE THREAD

**Issue by tajdars** [spring-cloud/spring-cloud-stream#963]
Moved from 
https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/70

spring-cloud-stream-binder-rabbit: 1.2.0.M1

I have a requirement to pause/resume (not destroy) rabbitmq consumer(s).
I don't see the corresponding
org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer
registered as a bean.
(I was thinking of grabbing a reference to SimpleMessageListenerContainer and
stop/start against it).

Quoting @mbogoevici 

Thanks @tajdars - this requires an enhancement to the binder API, allowing the user more control over the input lifecycle. Would you mind closing this and opening an issue in the core? Thank you!

**Comment by mbogoevici** [comment]
Changed the title as this is not a Rabbit binder feature.

**Comment by sabbyanandan** [comment]
Closing this in favor of https://github.com/spring-cloud/spring-cloud-stream/issues/1055.
