### ISSUE TITLE
Fix Confluent Schema Registry client

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#965]
As per @jonarcher:

> Original implementation was getting the schema id and using it as the
version. This made deserialization fail since it would endeavor to
retrieve the schema by version using the id value.

**Comment by neptoon** [comment]
This fix (maybe accidentally) broke the registration of a new schema. See https://github.com/spring-cloud/spring-cloud-stream/commit/b1285c3d4aa994ae65094c5dac1aca894d7438a5#commitcomment-22493861
