### ISSUE TITLE
Reactive-message channel adapters should observe consumer concurrency

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream#980]
See original question on SO:

https://stackoverflow.com/questions/44345006/spring-cloud-stream-kafka-reactive-stream-partition-assignment

We currently dispatch everything on a single `Flux`, but we should dispatch messages to separate threads (while preserving consumer thread/dispatched thread affinity).

**Comment by mbogoevici** [comment]
As a note, since concurrency is generally intended to solve slow message processing inside the application, one possible option is to leave the consumer at a concurrency of 1, but process messages concurrently inside the `StreamListener`.

The caveat is that because messages will be dispatched to a separate thread, they will be acknowledged on consumption, not during processing, so this presents `at-most-once` guarantees.

**Comment by olegz** [comment]
Given that we are gradually deprecating reactive module in favor of the native support provided by SCF I am closing this issue
