### ISSUE TITLE
Does sream support transaction

### ISSUE THREAD

**Issue by michael8335** [spring-cloud/spring-cloud-stream#982]
Hi guys:
  I have never use sream,but I want to have a try ,There is a problerm,Does sream support transaction?,when input reviceve a message and deal success,the output can get ack message? Is there any way to support transaction

**Comment by ilayaperumalg** [comment]
Hi,

The acknowledgment of the `incoming` message is handled at the binder level (depending on the messaging system you use). For instance, you can set `acknowledgeMode` as a RabbitMQ consumer property and For Kafka, you can set `autoCommitOffset ` to control offsetting the consumed message. You can also refer this section: `14.3.4. Usage examples`  in documentation [here](http://docs.spring.io/spring-cloud-stream/docs/Chelsea.BUILD-SNAPSHOT/reference/htmlsingle/index.html) for manually handling acknowledgment.

You can track [this](https://github.com/spring-cloud/spring-cloud-stream/issues/536) to allow synchronization at the binder level using transaction manager.
