### ISSUE TITLE
Unable to register schema in ConfluentSchemaRegistry

### ISSUE THREAD

**Issue by davidkalosi** [spring-cloud/spring-cloud-stream#985]
With the current implementation the register does not work since if a schema is not present it returns an HTTP 404. I have seen that the implementation has changed and now the service which is called is POST /subjects/%s instead of /subjects/%s/versions. 

Which means the schema is never registered.

**Comment by viniciusccarvalho** [comment]
`/subjects/%s/versions` is the correct URL that was fixed via #965. It maybe due changes on Confluent's schema registry API, it seems that it has changed. The current version on SCSt is tested against the 3.2.x version of the Confluent platform.

What version are you testing this against? We are improving the docs on the confluent client so users are aware of the version we support.
