### ISSUE TITLE
No error logging when dlq is enabled

### ISSUE THREAD

**Issue by tschuettel** [spring-cloud/spring-cloud-stream#989]
I recently turned on a dead letter queue in my Spring Cloud Stream application. Whenever there is an error while processing incoming messages the failed messages are moved to the DLQ. This works fine.
However, the exception that caused the message to be forwarded to the DLQ is not logged.
Starting on line 279 in class org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder line, an error handler is set that does the forwarding to the DLQ. But it does not log out the exception.
In my particular case, the error was not due to a faulty message but a bad SQL for saving the message to a database. The exception was lost and it took me quite some time to trace the problem.
I would suggest to log the exception at this point. I am happy to provide a PR in case you agree.

Please provide feedback.
Thanks.
Tom

**Comment by mbogoevici** [comment]
Thanks Tom for the feedback - we will want to address this issue, together the more complex issue of error handling as part of #913 (PR #926) (including enhancing the DLQ error message) - does that solve your use case?

**Comment by tschuettel** [comment]
I reviewed the ticket and the PR but I did not completely get what you are trying to do. Is there a more elaborate description available?

**Comment by mbogoevici** [comment]
To follow up and confirm if the new error handling in 1.3 is addressing this.

**Comment by garyrussell** [comment]
Note: this no longer applies in 1.3, since [this PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/125) publishes errors to the global error channel, which has a logging channel adapter subscribed (by default); plus users can subscribe to the global or destination error channel.

Changed milestone to 1.2.2 for fixing in the 1.2.x branch.
