### ISSUE TITLE
Override StreamListenerAnnotationBeanPostProcessor not work

### ISSUE THREAD

**Issue by wiselyman** [spring-cloud/spring-cloud-stream#990]
I overrided StreamListenerAnnotationBeanPostProcessor like:
```
@Bean(name = STREAM_LISTENER_ANNOTATION_BEAN_POST_PROCESSOR_NAME)
	public BeanPostProcessor streamListenerAnnotationBeanPostProcessor() {

	}
```
 The configuration only woks when put it in the main class, and not work when put it in other `@Configuration` class. 

Thanks for your help

**Comment by mbogoevici** [comment]
@wiselyman The methor registering the `BeanPostProcessor` should be declared `static` - see the comment here: http://forum.spring.io/forum/spring-projects/container/123899-beanpostprocessor-with-bean-annotation-not-working .

**Comment by wiselyman** [comment]
@mbogoevici I have done like this already, and not work too. with static or no static works in main class，not work in other configuration classes

**Comment by mbogoevici** [comment]
@wiselyman That's strange. Would you mind sharing a sample that doesn't work?

**Comment by wiselyman** [comment]
@mbogoevici [https://github.com/wiselyman/Spring-Cloud-Stream-Kafka-CQRS-ES/blob/master/statistics/src/main/java/com/example/StatisticsApplication.java](https://github.com/wiselyman/Spring-Cloud-Stream-Kafka-CQRS-ES/blob/master/statistics/src/main/java/com/example/StatisticsApplication.java)

**Comment by mbogoevici** [comment]
Hi,

Dug a bit into your example: the issue manifests itself when the configuration is in a package or subpackage of the `@SpringBootApplication` class - in that case, component scanning will cause the bean to register before the default framework bean (i.e. you can try placing them your configuration class and annotation in a separate package that is *not* a subpackage of `com.example` - that would be somewhat expected if you wanted to put this in a separate library and reuse this in other applications). As a fix on our end, we could make the framework-provided `BeanPostProcessor` `@ConditionalOnMissingBean`.

**Comment by wiselyman** [comment]
@mbogoevici thanks ,it works.
